deepset-ai/haystack

- haystack/__init__.py
- haystack/indexing/io.py
- haystack/reader/farm.py
- haystack/reader/transformers.py
- haystack/retriever/tfidf.py
- haystack/utils.py
- requirements.txt
- tutorials/Tutorial1_Basic_QA_Pipeline.ipynb
- tutorials/Tutorial1_Basic_QA_Pipeline.py
Add an option to use QA models from huggingface's [Transformers](https://github.com/huggingface/transformers) as a Reader.
Advantages:
- users can leverage quite easily other community models (from here: https://huggingface.co/models) 
- simpler workflow for transformer users to use their own models (no need to convert to FARM model)
Hand in hand with this addition, it became clear that we want the pipeline to be more generalizable:
- let the retriever return documents and not only indexes+scores
- don't require the retriever to have a df in memory with the docs (needed for scaling, e.g. with elasticsearch backend)   
- make input to reader.predict more explicit
- simplify the format of the dict returned by reader.predict
> Refactor pipeline for better generalizability & Add TransformersReader 

- haystack/reader/farm.py
Fixes #2 where we found that "offset_start" was equal to "offset_end". Also adding a type cast for  "probability" from numpy array to proper float.
> Fix offsets in reader

- README.rst
- haystack/api/inference.py
- requirements.txt
Let's move towards FastAPI as it is fast, builds on ASGI rather than WSGI, is user friendly and simplifies our lives in documenting the API schema.
> Move API from flask to fastAPI

- haystack/reader/farm.py
- haystack/utils.py
- tutorials/Tutorial1_Basic_QA_Pipeline.py
So far we applied the n_ans_threshold on FARM side, but then dropped all no_answer results in the final aggregation step across all candidate paragraphs (in haystack):
We should add it to the results. There are a few different options how to go with this, but I would suggest: 
- Take the no_answer candidate from the paragraph with the best "real answer" (as both are really competing for the top 1 answer)
- Use as score: score of no_answer - no_answer_threshold (as no_answer_thresold is kinda boosting the score and this should be reflected in the final results, where we want to sort by score)
Adressing #23
> Add no_answer option to results

- haystack/__init__.py
So far we suppress most of the logging. Let's show the metrics during evaluation. Addressing #27
> Make eval during reader.train() more verbose

- haystack/__init__.py
- haystack/reader/farm.py
- tutorials/Tutorial1_Basic_QA_Pipeline.py
Please update to latest FARM master to the changes to work!
See https://github.com/deepset-ai/FARM/pull/258
- return a sorted list of predictions including "no answer" if applicable
- no answer is relative to top positive prediction
> Add no answer handling

- haystack/reader/farm.py
Predict method of farm.py was using the assignment of "document_name" but tfidf retriever was not generating that value hence it broke the code and was generating the error.
> Removed "document_name" from farm.py

- haystack/finder.py
Fix for #32.
The `document_name` is not always present in the metadata. We should set it to `None` for these cases.
> Fixing doc_name for TFIDF Retriever

- haystack/reader/farm.py
- tutorials/Tutorial2_Finetune_a_model_on_your_data.py
FARMReader.train() now takes max_seq_len and use_gpu params from FARMReader. If you would like a different value for either of these params at train vs inference, you can explicitly specify them when calling FARMReader.train()
> FARMReader.train() now takes default values from FARMReader

- haystack/api/controller/feedback.py
- haystack/api/elasticsearch_client.py
This PR moves Elasticsearch connection out of the `application.py`. It fixes a cyclic import issue that prevented running the `application.py` as a Python script for debugging.
> Fix cyclic import of Elasticsearch client

- haystack/database/elasticsearch.py
- haystack/finder.py
- haystack/retriever/elasticsearch.py
Added an option for custom queries and filters for elasticsearch.
An example filter can look like this:
```
filter = {"must": [{"term": {"tag": "irgendwas"}}, 
{"range": {"date": {"gte": "2020-01-01T00:00:00+0200"}}}]}
```
An example custom text query can look like this:
```
query = {"should": [{"match": {"text1": {"query": question, "boost": 2}}},
{"match": {"text2": question}}]}
```
> added option for custom elasticsearch queries and filters

- haystack/api/controller/feedback.py
- haystack/database/base.py
- haystack/database/elasticsearch.py
- haystack/finder.py
- haystack/indexing/io.py
- haystack/reader/farm.py
- haystack/reader/transformers.py
- haystack/retriever/elasticsearch.py
This PR makes the following changes:
- in the current implementation, Retrievers return a list of texts and their associated `meta_data`. This PR introduces a `Document` schema that encapsulates documents and their `meta_data`. It simplifies the Retriever-Reader pipeline since now Retrievers only need to return a list of `Document`.
- the document_id field(`Document.id`) is now the `_id` field from ES
- `external_source_id ` is added to identify the source file for the case when a large file is split across multiple ES documents.
- introduce Pydantic and Python type hints
> Standardize Finder, Readers, and Retriever interfaces

- haystack/api/config.py
- haystack/api/controller/model.py
- haystack/api/controller/utils.py
This PR adds a `RequestLimiter` class to limit concurrent requests for a given endpoint.
In the case of question answering on very large documents, the requests can take several seconds. With the default FastAPI/Uvicorn/Gunicorn deployment, the requests get processed concurrently on a GPU, slowing down **all** the requests. To provide consistent user experience, the API can respond with a server-busy error code if the in-process requests exceed the limit threshold.
> Add limit on concurrent requests for doc-qa

- haystack/api/controller/feedback.py
- haystack/api/controller/model.py
- haystack/database/base.py
- haystack/database/elasticsearch.py
- haystack/finder.py
- haystack/reader/farm.py
Let's return a bit more information from the `Finder` / in the API and adjust the response format: 
- offsets in the original doc (needed for feedback endpoint)
- custom meta data (whatever is available in elasticsearch and is not excluded via `excluded_meta_data`in the `ElasticsearchDocumentStore`
- move `name` into the meta field
```
{
"results": [
{
"question": "Why did revenue increase?",
"answers": [
{
"answer": "Total revenue for the first quarter of 2017 was approximately $1,437,000,000",
"score": 3.589367151260376,
"probability": 0.6103231806375512,
"context": "<Some context>",
"offset_start": 212,
"offset_end": 288,
"offset_start_in_doc": 5674,
"offset_end_in_doc": 5750,
"document_id": "cqjbqnABdLrIEs4cBtTh",
"meta": {
"quarter": "Q1",
"year": "2017",
"company": "<Some Name>", …
```
> Return more meta data & restructure reponse format

- haystack/api/controller/query.py
- haystack/database/elasticsearch.py
- haystack/retriever/elasticsearch.py
This PR splits the `ElasticsearchRetriever` into separate classes for embeddings based retrieval(`EmbeddingRetriever`) and plain ES retrieval(`ElasticsearchRetriever`).
> Refactor ElasticsearchRetriever into separate class

- haystack/database/elasticsearch.py
When using `get_all_documents()` for `ElasticsearchDocumentStore`, there is no query_score for the documents. This causes an exception when creating `Document` instances.
> Fix get_all_documents() in ElasticsearchDocumentStore

- .gitignore
- Dockerfile
- Dockerfile-GPU
- haystack/finder.py
- requirements.txt
- test/test_db.py
- test/test_finder.py
- test/test_imports.py
- test/test_in_memory_store.py
- tox.ini
Addin in-memory store. It is nice to have when experimenting with notebooks or trying to pickle a trained model.
> Inmemory store

- docker-compose.yml
- requirements.txt
- run_docker_gpu.sh
This PR adds a docker-compose file for running Haystack on CPU and a shell script to run on GPU.
> Add Docker Images for running Haystack

- tutorials/Tutorial2_Finetune_a_model_on_your_data.ipynb
- tutorials/Tutorial2_Finetune_a_model_on_your_data.py
As we got a question on how to save / load a fine-tuned reader, I am making this more explicit in Tutorial 2: 
```
reader.train(data_dir=train_data, train_filename="dev-v2.0.json", use_gpu=False, n_epochs=1, save_dir="my_model")
reader.save(directory="my_model")
new_reader = FARMReader(model_name_or_path="my_model")
```
> Make saving more explicit in tutorial

- haystack/database/base.py
In the `Document` pydantic schema, the `meta` class is a `Dict[str, str]` which breaks in the case of FAQ style QA(#101), as the question embeddings are vectors.
This PR makes the values of the `meta` dict of type `Any`.
> Make "meta" field generic for Document Schema

- haystack/database/elasticsearch.py
We currently require a document "name" field in the elastic index (`ElasticsearchDocumentStore.name_field`). Conversion from a ES hit to Doc will fail otherwise as reported in #99 and #97. 
While the name is helpful in many deployments (e.g. to display the origin of answers in a UI), I don't see a reason why it must be mandatory.
FYI @predoctech
> Make doc name optional

- haystack/finder.py
Add document metadata for results of `Finder.get_answers_via_similar_questions()`.
This PR fixes #105.
> Add document metadata for FAQ style QA

- README.rst
- haystack/database/base.py
- haystack/database/memory.py
- test/test_db.py
- test/test_document.py
- test/test_farm_reader.py
- test/test_in_memory_store.py
Storing and filtering tags in InMemory store. Adding meta obj to InMemory store.
> Add filtering by tags for InMemoryDocumentStore

- haystack/database/base.py
- haystack/database/memory.py
- haystack/retriever/tfidf.py
- test/test_db.py
- test/test_faq_retriever.py
- tox.ini
print of indices can get quite large and kill stdout on a container
> Add embedding query for InMemoryDocumentStore 

- haystack/retriever/elasticsearch.py
To avoid serialization issues when indexing to elasticsearch we are casting now from numpy.float32 to float64. In addition we are using the GPU arg now to init the model on the correct device. 
Related to https://github.com/deepset-ai/haystack/issues/116
> Fix embeddings from sentence-transformers (type cast & gpu flags)

- haystack/api/config.py
- haystack/api/elasticsearch_client.py
- haystack/database/elasticsearch.py
Addressing #128. 
- Allowing a to connect to ES at a custom port
- Adding some docs and removing  unused `tag_fields` arg.
- Fixing usage of ES_CONN_SCHEME in API
@tanaysoni Are you aware of any usage of the `tag_fields` arg? It seems outdated.
> Add custom port to ElasticsearchDocumentStore

- haystack/database/elasticsearch.py
Resolving #117 by increasing timeout for indexing docs (e.g. when using large models)
> Increase timeout for bulk indexing in ES

- haystack/api/controller/search.py
- haystack/retriever/elasticsearch.py
Google Colab Notebooks currently support Python v3.6.9 which does not have the `Literal` type.
This PR fixes #155.
> Remove Literal type hint

- haystack/reader/farm.py
- requirements.txt
This PR adds the conversion of PyTorch BERT models to ONNX format for inference with [ONNXRuntime](https://github.com/microsoft/onnxruntime).
Speed benchmarks: https://docs.google.com/spreadsheets/d/1ak9Cxj1zcNBDtjf7qn2j_ydKDDzpBgWiyJ7cO-7BPvA/edit#gid=0
Usage: 
```python
from haystack.reader.farm import FARMReader
from pathlib import Path
FARMReader.convert_to_onnx(
model_name_or_path="deepset/bert-base-cased-squad2", optimize_for="gpu_tensor_core"
)  # exports the model to ./onnx-export dir
FARMReader(model_name_or_path=Path("onnx-export"))  # load the ONNX model
```
> Add ONNXRuntime support

- haystack/indexing/file_converters/base.py
If the `sequences` param is an empty list, it raises an exception: #164.
> Fix boundary condition in detection of header/footer in file converters

- haystack/finder.py
- haystack/reader/farm.py
- tutorials/Tutorial5_Evaluation.py
fixes #173 by zipping predictions coming from FARM with its input.
If the ordering of FARM input and output is not preserved this hacky fix will create bugs.
We should handle the doc id in FARM inferencer in the next release.
Sorry about sneaking in some other code changes.
The relevant code changes are in haystack/reader/farm.py line 254 and 271
> Fix document id missing in farm inference output

- haystack/indexing/file_converters/pdf.py
This PR replaces the `capture_output` parameter as it is not supported in Python 3.6(#182).
> Adjust PDF conversion subprocess for Python v3.6

- requirements.txt
- rest_api/controller/file_upload.py
This PR adds a message in the HTTP response body when a file upload is successful. Additionally, `python-multipart` is added in requirements to support multipart/form-data enctype for file uploads.
Related issue: #183.
> Add success response for successful file upload API

- rest_api/controller/search.py
The REST API access logging for Gunicorn-Uvicorn seems to be broken. There are related discussions in https://github.com/encode/uvicorn/issues/527 and https://github.com/encode/uvicorn/issues/389.
For now, this PR adds logging of the time manually for the `/doc-qa` endpoint.
> Add response time in logs

- .gitignore
While the API and docker files mention "**models**", the .gitignore still reference "**model**". If I am correct, it refers to the same thing :  the folder where we store local models. Since we don't want git to interact with them, I suggest this modification
> gitignore fix

- haystack/reader/transformers.py
the Bug I had was:
```
pydantic.error_wrappers.ValidationError: 8 validation errors for Answers
haystack-api_1   | response -> results -> 0 -> answers -> 0 -> offset_start
haystack-api_1   |   field required (type=value_error.missing)
haystack-api_1   | response -> results -> 0 -> answers -> 0 -> offset_end
haystack-api_1   |   field required (type=value_error.missing)
haystack-api_1   | response -> results -> 0 -> answers -> 1 -> offset_start
haystack-api_1   |   field required (type=value_error.missing)
haystack-api_1   | response -> results -> 0 -> answers -> 1 -> offset_end
haystack-api_1   |   field required (type=value_error.missing)
haystack-api_1   | response -> results -> 0 -> answers -> 2 -> offset_start
haystack-api_1   |   field required (type=value_error.missing) …
```
> Fix naming of offset in answers of TransformersReader (for consistency with FARMReader)

- haystack/database/elasticsearch.py
'embedding_field' and 'embedding_dim' are useful not only for EmbeddingRetriever but also for DensePassageRetriever. Hence, could be good if you generalise as "dense retriever" in the comment.
> Update docstring for embedding_field and embedding_dim

- Dockerfile
Here is a proposal for this bug during Docker build :
```
Step 8/10 : COPY models /home/user/models
ERROR: Service 'haystack-api' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder648491496/models: no such file or directory
```
Problem is since we added **models** to the gitignore (my suggestion) we don't have the folder if we don't create it manually. So my suggestion is : we trick Docker with my suggestion (COPY always requires at least one file, in our case I chose the README)
Another solution would be to ignore everything but a README.md inside the models folder. up to you @tholor
> Fix Dockerfile to build successfully without models directory

- haystack/database/elasticsearch.py
For document_stores.write_docs(dicts), we want a similar behavior across different types of document stores. 
So far the meta data handling was different for elasticsearch, where we just indexed the dictionaries in the same structure as they came in. So if you passed [{"name": "some", "text": "some", "meta":{"author": "some"}}], it would result in the same nested structure in elasticsearch.  
This PR makes the behaviour similar to the other document stores by unnesting the "meta" field before indexing.
> Harmonize meta data handling across doc stores

- haystack/database/base.py
- haystack/database/elasticsearch.py
- haystack/database/memory.py
- haystack/database/sql.py
- haystack/indexing/utils.py
- test/conftest.py
- test/test_db.py
- test/test_dpr_retriever.py
- test/test_faq_retriever.py
- test/test_in_memory_store.py
- test/test_reader.py
- test/test_tfidf_retriever.py
This PR makes all three document stores(Elasticsearch, SQL, and InMemory) compliant in how they ingest documents using the `write_documents()` method.
The input dicts for `write_documents()` have a mandatory `text` field. All other metadata used for filtering documents(eg, name, author, category etc) can be passed under a `meta` dict. So, a sample dict would look like this:
```python
{
"text": "....body-of-the-document...",  # mandatory
"meta": {  # meta is optional
"year": "2019",  # all values are strings
"name": "xyz",
"author": "abc"
}
}
```
For _backward compatibility_, the `meta` fields can also be passed as top-level keys in the document dict. For example,
```python
{
"text": "....body-of-the-document...",  # mandatory
"name": "abc"  # optional; this will get interepreted as a …
```
> Move document_name attribute to meta

- haystack/reader/farm.py
- haystack/reader/transformers.py
- haystack/reader/transformers_utils.py
- requirements.txt
- test/conftest.py
- test/test_dpr_retriever.py
- test/test_finder.py
- test/test_reader.py
- tutorials/Tutorial5_Evaluation.py
Upgrading to latest FARM (0.4.6) which comes with PyTorch 1.5.1 and Transformers 3.0.2
This means: 
- Making FARMReader more powerful & stable (e.g. FARM 0.4.6. supports clearly typed input/output objects instead of "mysterious" dicts)
- More models & bug fixes for TransformersReader
- Fixing some problems in Colab related to PyTorch 1.5.0
> Upgrade to new FARM / Transformers / PyTorch versions

- tutorials/Tutorial5_Evaluation.ipynb
- tutorials/Tutorial5_Evaluation.py
The old eval dataset (nq_dev_subset v1) had answers that were incorrect either because the string couldn't be found in the text or because the indices were off. This PR points to nq_dev_subset v2 which fixes these issues.
> Fix Evaluation Dataset

- haystack/__init__.py
- haystack/reader/farm.py
- tutorials/Tutorial2_Finetune_a_model_on_your_data.ipynb
- tutorials/Tutorial2_Finetune_a_model_on_your_data.py
When calling FARMReader.train() with multiple GPUs using DataParallel, we were running into an error because we apply DataParallel twice(!). Once when initializing the FARMReader (so that we can use Dataparallel for inference), and then again in train() when we call initialize_optimizer(). 
This is a quick fix, but we should fix it upstream in FARM (e.g. by adding a check in optimize_model() and avoid applying DataParallel there if it was already done before). 
Fixing #224
> Fix multi gpu training via Dataparallel

- haystack/retriever/dense.py
- haystack/retriever/dpr_utils.py
- rest_api/controller/search.py
- test/test_dpr_retriever.py
- test/test_faq_retriever.py
- tutorials/Tutorial4_FAQ_style_QA.ipynb
- tutorials/Tutorial4_FAQ_style_QA.py
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
- tutorials/Tutorial6_Better_Retrieval_via_DPR.py
- Add `truncation=True` in the calls to transformers from Dense Passage Retriever to avoid new warnings in transformers 3.0.2
- Change arg `gpu` -> `use_gpu` in init of DPR and EmbeddingRetriever to be more compliant with Readers
Fixing #237
> Refactor DPR for latest transformers version & change init arg `gpu` -> `use_gpu` for DPR and EmbeddingRetriever

- haystack/database/elasticsearch.py
This PR removes the top-level `meta` field in documents after _unnesting_ the meta fields.
> Remove meta field when writing documents in Elasticsearch

- rest_api/controller/feedback.py
The "context" was not on the right level of the dict causing trouble in training / preprocessing (see #238).
Note: The context currently contains **all** text of the indexed document. If users index very long texts, they will have very long texts in the SQuAD "context", which will result in many negative training samples (passages with no annotated answer) and can impact training performance. We should address this in a future PR.
> Fix format of /export-doc-qa-feedback to comply with SQuAD

- haystack/database/elasticsearch.py
- haystack/retriever/dense.py
Changing return type of EmbeddingRetriever to List[np.array] to have consistent behaviour with DPR and fix bug in update_embeddings()
Fixing #244.
> Fix return type of EmbeddingRetriever to numpy array

- haystack/retriever/dense.py
After refactoring of query_by_embedding function in the commit 355be293b6ee17f4305aef66bffbf2ba052db327, DPR has stopped to work. 
According to your EmbeddingRetriever retrieve function implementation, I have fixed DPR retrieve function. Hope it helps.
> Fix type of query_emb in DPR.retrieve()

- haystack/reader/farm.py
In some cases (e.g. debugging or fine-tuning on small datasets) it can be useful to disable multiprocessing. 
Let's add an argument to reader.train() that allows this. 
Usage: 
```
num_processes = 0 or 1  --> Plain, single python process 
num_processes = 12 --> Multiprocessing with 12 processes
num_processes = None --> Multiprocessing with "number of CPU cores -1" processes
``` 
Related to  #268
> Add num_processes to reader.train() to configure multiprocessing

- haystack/database/base.py
- haystack/database/elasticsearch.py
- haystack/database/memory.py
- haystack/database/sql.py
- rest_api/controller/search.py
- test/test_tfidf_retriever.py
The `Document.id` values are currently expected to be UUIDs. They are either generated automatically by Haystack when indexing in a new document store or get UUIDs assigned from user-supplied hex string when reading from an existing document store.
To support arbitrary IDs(strings/numeric) from existing document stores, this PR refactors IDs to always be strings.
For creating new document stores, the IDs are still UUID strings to prevent duplicates.
Related issue: #278
> WIP: Cast document_ids as strings

- haystack/database/elasticsearch.py
This PR adds a `update_existing_documents ` parameter for the `ElasticsearchDocumentStore`. 
When the parameter is set to `True`, indexing new documents with explicit IDs will update any existing documents with the same ID. Otherwise, if set to `False`, the document store throws an error.
By default, the parameter is set to `False` to retain the same behaviour as before.
> Add option to update existing documents when indexing

- haystack/reader/base.py
- haystack/reader/farm.py
- haystack/reader/transformers.py
- test/conftest.py
Linked to #257 and #258 
Right now the Transformersreader just gives back "no answers" for each document it predicts on.
We need to aggregate those "no answers" and their scores, similar to what the FARMReader is doing.
The Transformersreader pipeline does not seem to have an option to 
1. modify the "no answer" bias
2. always return the "no answer" (no matter how unlikely it is)
Because of these limitations we need workarounds.
> Add "no answer" aggregation to Transformersreader

- haystack/database/base.py
- haystack/database/elasticsearch.py
- haystack/retriever/base.py
- tutorials/Tutorial5_Evaluation.py
This PR adds functionality to aggregate Label Objects into an Aggregated_Label Object.
The Aggregated_Label differs from a normal Label in 
- multiple_answers
- multiple_document_ids
- multiple_offset_start_in_docs
I am unsure how to aggregating values for is_correct_answer/document. I think for the use case of evaluating on QA datasets those fields are not needed
> Aggregate label objects for same questions

- haystack/database/base.py
- haystack/database/elasticsearch.py
- haystack/database/faiss.py
- haystack/database/memory.py
- haystack/database/sql.py
- requirements.txt
- test/conftest.py
- test/test_db.py
- test/test_dpr_retriever.py
- test/test_faiss.py
This PR adds a document store for very large scale embedding based dense retrievers like the [DPR](https://github.com/deepset-ai/haystack#densepassageretriever). It uses the [FAISS](https://github.com/facebookresearch/faiss) library for computing similarity between vector embeddings.
> Add FAISS Document Store

- haystack/database/elasticsearch.py
The Elasticsearch mappings for the meta fields are defined dynamically on-the-fly as they get indexed to an Elasticsearch index.
To ensure exact matches, a dynamic mapping template is added to the index to ensure all newly added fields get mapped as the `keyword` type.
Additionally, this PR remove ignore of HTTP `400` status code when creating indices as it swallows exceptions(other than index already exists).
> Ensure exact match when filtering by meta in Elasticsearch

- haystack/database/elasticsearch.py
- haystack/database/faiss.py
- haystack/retriever/dense.py
- test/test_dpr_retriever.py
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
- tutorials/Tutorial6_Better_Retrieval_via_DPR.py
This PR moves parts of the update_embedding method in ElasticsearchDocumentStore and FAISSDocumentStore to the embed_passages method in dense retrievers.
`embed_passages` now takes as argument a list of Documents instead of a list of strings (=documents) and another optional list of strings (=titles). Furthermore, `DensePassageRetriever` now contains the instance variable `embed_title` which can be set to include titles in embedding of passages.
```python
dpr = DensePassageRetriever(document_store, embedding_model)
list_of_documents = document_store.get_all_documents()
list_of_strings = [doc.text for doc in list_of_documents]
list_of_titles = [doc.meta["name"] for doc in list_of_documents]
embeddings = dpr.embed_passages(list_of_strings, list_of_titles)
```
```python
dpr = …
```
> Restructure update embeddings

- haystack/reader/transformers.py
The TransformersReader is adapted such that there is no need to provide a tokenizer as it can be inferred by the model name. 
Also, max_seq_len and doc_stride can now be set by the user.
> Align TransformersReader with FARMReader

- haystack/database/base.py
- test/test_db.py
This PR aggregates multiple no answers in different documents for the same question. Before, only one no answer was present in MultiLabel.
> Aggregate multiple no answers in MultiLabel

- haystack/database/faiss.py
- haystack/database/sql.py
> Improve speed for SQLDocumentStore

- haystack/database/memory.py
This is a work in progress pull request for the issue #316 as suggested by @tanaysoni.
Hi @tanaysoni, Implemented the update_embeddings method. Can you please review this? 
Question : Once the embeddings are generated by DPR, logic is to convert every document into dict, add the embedding to it, before converting it back into document to push it in memory store. I understand this is a one time process, is there a better way to handle this?
Do I need to create & run unit tests too?
P.S: This is my first pull request, pls let me know if there is anything amiss.
> DPR (Dense Retriever) for InMemoryDocumentStore #316

- haystack/indexing/utils.py
- haystack/reader/farm.py
- test/test_eval.py
- tutorials/Tutorial5_Evaluation.ipynb
- tutorials/Tutorial5_Evaluation.py
When evaluating using Reader.eval() we read data from file, store it in an ElasticsearchDocumentStore, reconstruct input dictionaries and then evaluate using a farm.Evaluator object. 
Two problems were arising, linked to the DocumentStore. 
1) When a duplicate question is asked on the same document (see squad dev set "What is the CJEU's duty?"), indexing into and fetching from the DocumentStore causes their labels to be merged. This can result in a list of answers longer than the default max number of answers 6. A quick solution is implemented here to reduce the list down to 6.
2) Only span labels are indexed into the DocumentStore and fetched, meaning that we lose the no_answer samples. This PR ensures that question which don't have a corresponding label in the DocumentStore are assigned …
> More robust Reader eval by limiting max answers and creating no answer labels

- README.rst
Port 80 may require `sudo` privileges, so it might be confusing for new users.
> Use port 8000 in documentation

- test/conftest.py
Changes includes -
1) Run ElasticSearch and Tika inside docker containers
2) For pdftotext tool download platform dependent binaries and also removing sudo requirement to copy pdftotext binaries to /usr/local/bin for MacOS
> This PR will fix test suite dependency issue on MacOS

- rest_api/config.py
- rest_api/controller/search.py
This PR removes embeddings from the metadata of the returned documents by the `/doc-qa` & `/faq-qa` REST APIs.  This resolves failure in schema validation(#387) of answers and reduces the payload size.
> Exclude embedding fields from the REST API

- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/finder.py
- haystack/schema.py
This PR moves the retrieval probability(pseudo probability by scaling query scores) calculations to the respective document stores.
It simplifies the similarity matching method(`get_answers_via_similar_questions()`) in the `Finder`. Additionally, now the retrieved documents have an explicit probability field that could be useful in the future.
> Move retriever probability calculations to document_store

- haystack/file_converter/base.py
- haystack/file_converter/docx.py
- haystack/file_converter/pdf.py
- haystack/file_converter/tika.py
- haystack/file_converter/txt.py
- haystack/preprocessor/utils.py
- rest_api/controller/file_upload.py
- test/test_docx_conversion.py
- test/test_pdf_conversion.py
This PR refactors the interface of file converters. 
The `extract_pages()` method is now `convert()`.
It takes file & optional meta as input and returns a dictionary containing extracted text & associated meta data. This dictionary can be passed to a preprocessor class(to be introduced later).
Resolves #380.
> Refactor file converter interface

- haystack/document_store/sql.py
- test/test_db.py
This PR refactors the SQLDocumentStore table schema. 
- many-to-many mapping table between `document` & `meta` table is removed
- `meta` table now has `document_id` as a foreign key
- filtering of documents by meta data key-value pairs is fixed 
- added more tests for filtering & updating meta data
Resolves #391.
> Fix document filtering in SQLDocumentStore

- haystack/document_store/faiss.py
- test/test_faiss.py
Addressing #392. 
We had duplicate vector ids when number of docs > index_buffer_size due to a missing offset.
> Fix duplicate vector ids in FAISS

- docs/_src/usage/usage/reader.md
In addition to the typo (i.e. `langauge`), I have also added correct link for the Italian Transformers model.
> Fix typo in documentation

- haystack/document_store/elasticsearch.py
By default, Elasticsearch creates an index called document. That's the biggest problem when initializing ElasticsearchDocumentStore through Haystack. Because when calling `_create_document_index`, you may end up doing nothing since `document` index is already created. This is not a problem for non-vector Retriever. 
But Embeddings needs special type "dense_vector" into Elasticsearch mapping definition. That's why it is important to update the default 'document' index in this case.
> fixing ElasticsearchDocumentStore initialisation

- haystack/retriever/dense.py
Originating from #428 
Adding an error message to help users if they want to use sentence-transformers but it is not installed yet.
> Make sentence-transformers usage more user-friendly

- README.rst
- annotation_tool/README.md
- annotation_tool/docker-compose.yml
> Add Docker Setup for the Annotation Tool

- Dockerfile
- Dockerfile-GPU
- docker-compose.yml
- haystack/document_store/elasticsearch.py
- requirements.txt
- rest_api/config.py
- run_docker_gpu.sh
> Update GPU docker & fix race condition with multiple workers

- haystack/preprocessor/utils.py
- test/test_utils.py
> Skip file conversion if file type is not supported

- haystack/retriever/dense.py
Adding explanation for embed_title as usage was unclear before (#458 )
> Update DPR docstring for embed_title

- haystack/document_store/faiss.py
- haystack/document_store/sql.py
- test/test_db.py
With this PR, the `SQLDocumentStore` has a new `vector_id` field in the `document` table. 
The `FAISSDocumentStore` now uses the new methods `get_documents_by_vector_ids()` & `update_vector_ids()` to perform bulk read & writes on vector_ids in the `SQLDocumentStore`.
Resolves #383.
> Enable bulk operations on vector IDs for FAISSDocumentStore

- haystack/document_store/elasticsearch.py
For the ElasticSearch's document_store, the filters are not working properly when using the query_by_embedding function.
I fixed the ElasticSearch query.
> bug: filters on a query_by_embedding

- haystack/document_store/faiss.py
- test/test_faiss.py
* Allow multiple write calls to existing FAISS index.
* Fixing issue when update_embeddings always create new FAISS index instead of clearing existing one. New index creation may not free existing used memory and cause memory leak.
> FAISS Store: allow multiple write calls and fix potential memory leak in update_embeddings

- docs/document_store.md
- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/sql.py
- test/conftest.py
- test/test_faiss.py
As described in https://github.com/deepset-ai/haystack/pull/422 we don't need the phi normalization trick anymore as HNSW supports the inner product metric. This will simplify the code a lot - especially for multiple subsequent writes of documents. 
`vector_size` -> `vector_dim`
Old:
`FAISSDocumentStore(...vector_size=768)`
New: 
`FAISSDocumentStore(...vector_dim=768)`
- There are more potential customizations for FAISS index types that we could make accessible for the end user. Some of them were proposed by @lalitpagaria in #385 . As of now most of them don't seem very relevant and rather blow up complexity, but we should re-evaluate when we did more experiments on diff. index types and models
- Currently we don't expose the metric type to the end user. This would be a simple addition, …
> Remove phi normalization from FAISS & support more index types

- haystack/file_converter/txt.py
Related to #477, #223.
This would just be a quick fix. The default encoding mode is set to utf-8. Users would still have to change the source code in order to switch to other encoding modes.
> add explicit encoding mode to file_converter/txt.py

- haystack/reader/farm.py
> Added automatic mixed precision (AMP) support for reader training from Haystack side

- haystack/document_store/faiss.py
- requirements.txt
To fix #446 
@tanaysoni Please review
> Fix windows platform installation

- haystack/finder.py
In the Finder, for each answer object, the corresponding document's `meta` is added.  In the case of multiple answers from the same document, the answers' `meta` references to the same dictionary in memory. This could lead to unintended behavior where changes to the `meta` of an answer get propagated to the `meta` of others answers.
> Add deepcopy for meta dicts in answers

- haystack/document_store/faiss.py
- haystack/retriever/sparse.py
- test/conftest.py
- test/test_dpr_retriever.py
- test/test_dummy_retriever.py
- test/test_elastic_retriever.py
- test/test_embedding_retriever.py
- test/test_eval.py
- test/test_faiss.py
- test/test_finder.py
- test/test_tfidf_retriever.py
To fix following issue (Refer https://github.com/deepset-ai/haystack/commit/1cebcb7dda40d324e01ac28a4c867fea5b9ba4a9#r43171379)
1. Prevent `update_embeddings` function in `FAISSDocumentStore` to set `faiss_index` as `None` when document store does not have any docs.
2. Cleaning up tests by adding `fixture` for `retriever`.
> Fix update_embeddings function in FAISSDocumentStore

- haystack/document_store/elasticsearch.py
Currently, we always try to create a label index if it does not exist yet. 
In some deployment scenarios this is not wanted (e.g. when no labels / eval is planned or the elasticsearch cluster is not managed by the user and he/she cannot easily create indices). 
With this PR we can disable all index creation by setting `create_index=False`  when initializting the `ElasticearchDocumentStore`
> Make creation of label index optional

- haystack/preprocessor/preprocessor.py
PreProcessor was failing when `meta` key was present but value was `None`
> Fix meta data = None in PreProcessor

- rest_api/controller/request.py
Let's allow again `null` as filter value (for backward compatibility).
Example: 
``` 
{
"questions": [
"Who is the father of Arya?"
],
"filters": {"test":null},
"top_k_retriever": 2
}
```
Currently, this is failing and causes trouble with older integrations.
> Make filter value optional in REST API

- README.rst
The example code was referencing a structure haystack.indexing which does not exist anymore. Modified that and the function call "extract_pages" with "convert".
> Updated the example code to Indexing PDF / Docx files

- haystack/preprocessor/preprocessor.py
- test/test_preprocessor.py
So far: 
We raise an exception for split_respect_sentence_boundary=True' and split_by='sentence'
Now: 
We allow split_respect_sentence_boundary=True' and split_by='sentence'. This makes more sense from a semantic perspective as we always respect sentence boundaries automatically when we split by sentence. It also simplifies usage, as the `split_respect_sentence_boundary` defaults to `True` in the latest master
> Restructure checks in PreProcessor

- tutorials/Tutorial1_Basic_QA_Pipeline.ipynb
- tutorials/Tutorial2_Finetune_a_model_on_your_data.ipynb
- tutorials/Tutorial3_Basic_QA_Pipeline_without_Elasticsearch.ipynb
- tutorials/Tutorial4_FAQ_style_QA.ipynb
- tutorials/Tutorial5_Evaluation.ipynb
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
Fixes #507. 
Google colab environments have preinstalled `urllib3==1.24.3`, but botocore 1.19.0 needs `urllib3<1.26,>=1.25.4`. This PR adds a pip install for `urllib3==1.25.4` on all colab examples.
> Add requirement to colab notebooks

- haystack/preprocessor/utils.py
The extraction of title information was failing if there are no "title" key in the QA documents.
I added a warning if no titles are present and made the title extraction optional.
> Make title info optional when evaluating on QA data

- test/conftest.py
- test/test_dpr_retriever.py
- test/test_embedding_retriever.py
- test/test_faiss.py
- test/test_finder.py
- test/test_reader.py
- test/test_rest_api.py
- Faiss index keep data in memory even after test execution. Hence now clearing memory held by it during fixture teardown.
- Marking slow test with pytest markers. So In future these tests can be optimized. Also command line option can be added to skip them refer https://pytest.org/en/stable/example/simple.html#control-skipping-of-tests-according-to-command-line-option
@tholor @tanaysoni Please review.
> Pytest fix memory leak and put pytest marker on slow tests

- haystack/document_store/base.py
- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/document_store/sql.py
- test/conftest.py
- test/test_dpr_retriever.py
> Add support to return embedding

- haystack/reader/farm.py
Previously, Reader.eval( ) was generating dictionaries without the "is_impossible" key, which sometimes contained answer lists populated by empty string span answers. e.g.
```
dictionary = {"answers": [empty_string_span_answer], ...}
```
This PR adds the the "is_impossible" key in the dictionary and represents no_answer dictionaries by setting dictionary
```
dictionary = {"answers": [ ], "is_impossible": True, ...}
```
This solves the drop in haystack/test/benchmarks/reader.py performance that is talked about in [this FARM issue](https://github.com/deepset-ai/FARM/commit/9055094e339285bb47b06a49cfb4589c735dc7b4)
> Fix FARMReader.eval( ) handling of no_answers

- haystack/document_store/elasticsearch.py
- haystack/preprocessor/utils.py
- haystack/reader/farm.py
- haystack/retriever/dense.py
Fixes: #526 
1. Few warnings need fix in FARM
2. Can't remove warning from docx library
> Removing warnings from the Haystack codebase.

- haystack/finder.py
- haystack/retriever/sparse.py
- requirements.txt
- rest_api/config.py
- rest_api/controller/search.py
If you are running the REST API within a docker container and want to debug, you want an easy way to switch the log level from info to debug.
This PR adds an environment variable `LOG_LEVEL` that you can set to the common python log level strings (INFO, DEBUG ...). It will be applied for all loggers within haystack (but not external ones like FARM or elasticsearch)
> Allow configuration of log level in REST API

- haystack/eval.py
- haystack/finder.py
- haystack/retriever/base.py
- test/test_eval.py
Fixes #536 
This PR adds the retriever metric `Mean Reciprocal Rank` and fixes `Mean Average Precision` in the closed-domain case.
It might make sense to add open-domain option for finder evaluation in a future PR.
> Fix retriever evaluation metrics

- haystack/document_store/elasticsearch.py
Elasticsearch natively supports different analyzers for dividing a `text` field into terms, including pre-configured options for different languages.  More info here: https://www.elastic.co/guide/en/elasticsearch/reference/7.9/analysis-analyzers.html
With this PR, a new `analyzer` parameter is added to the `ElasticsearchDocumentStore` that allows setting a default analyzer from one of the built-in analyzers. This default analyzer will be used both for indexing & query. 
Resolves #538
> Allow configuration for Elasticsearch Analyzer

- haystack/document_store/sql.py
This PR adds makes the `SQLDocumentStore` more generic to work with MySQL database.
Resolves #543.
> Add support for MySQL database

- rest_api/controller/request.py
- rest_api/controller/search.py
- test/test_rest_api.py
This PR allows the filters in the REST API to be a single string or a list of strings.
So, both queries are now valid:
`{"questions": ["Where does Carla lives?"], "filters": {"name": "filename1"}}` 
`{"questions": ["Where does Carla lives?"], "filters": {"name": ["filename1", "filename2"]}}` 
Resolves #567
> Allow list of filter values in REST API

- tutorials/Tutorial1_Basic_QA_Pipeline.ipynb
- tutorials/Tutorial2_Finetune_a_model_on_your_data.ipynb
- tutorials/Tutorial3_Basic_QA_Pipeline_without_Elasticsearch.ipynb
- tutorials/Tutorial4_FAQ_style_QA.ipynb
- tutorials/Tutorial5_Evaluation.ipynb
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
- tutorials/Tutorial7_RAG_Generator.ipynb
Google colab updated to Torch 1.7+cu101. However, Haystack requires FARM 0.5.0 which requires Torch>1.5 and Torch<1.7. When Haystack runs in Colab, it uninstalls Torch 1.7+cu101 for Torch 1.5.1 but without the appropriate Cuda version. The added lines here ensure that that Torch1.6+cu101 is installed
> Update Colab Torch Version

- haystack/document_store/elasticsearch.py
- requirements.txt
- test/test_reader.py
Haystack's requirements.txt ask for the latest version of Elasticsearch. A new ES release causes the `elasticsearch.helpers.scan()` function to now return a generator instead of a list. 
This PR casts the output of `scan()` to a list so that CI doesn't fail and restricts ES versioning so new releases won't introduce bugs.
The assert value of a reader test is also changed since the `deepset/roberta-base-squad2 `model was updated to version2.
> Fix CI bug due to new Elasticsearch release and new model release

- haystack/generator/transformers.py
Resolve #587 and #585 
for `num_return_sequences` refer.
https://github.com/huggingface/transformers/blob/a1bbcf3f6c20e15fe799a8659d6b7bd36fdf11ed/src/transformers/modeling_rag.py#L852
This should not be greater than `num_beams`  hence when use pass `top_k` value greater than `num_beams` we reset it to `num_beams` and print warning.
> [RAG] Fix various generator issues

- haystack/document_store/base.py
- haystack/document_store/elasticsearch.py
- haystack/document_store/memory.py
- haystack/document_store/sql.py
- test/test_db.py
This PR adds a filters parameter(similar to `get_all_documents()`) to `delete_all_documents()` for `ElasticsearchDocumentStore`.
> Add filters for delete_all_documents()

- haystack/document_store/faiss.py
- haystack/document_store/sql.py
- test/test_db.py
> Adding support for update_existing_documents to sql and faiss document stores

- docs/_src/benchmarks/retriever_map.json
Merge two lines in Retriever Accuracy benchmark graph since their performance is exactly the same
> Make benchmarks clearer

- docs/_src/benchmarks/retriever_map.json
An error was being thrown since we had too many columns defined in the chart for retriever mAP. This PR removes it
> Remove column in benchmark website

- README.md
The link to the DocumentStore page was broken in the readme. This fixes it.
> Fix link to DocumentStore page

- docs/_src/api/api/document_store.md
- docs/_src/api/api/file_converter.md
- docs/_src/api/api/generator.md
- docs/_src/api/api/preprocessor.md
- docs/_src/api/api/pydoc-markdown-document-store.yml
- docs/_src/api/api/pydoc-markdown-file-converters.yml
- docs/_src/api/api/pydoc-markdown-generator.yml
- docs/_src/api/api/pydoc-markdown-preprocessor.yml
- docs/_src/api/api/pydoc-markdown-reader.yml
- docs/_src/api/api/pydoc-markdown-retriever.yml
- docs/_src/api/api/reader.md
- docs/_src/api/api/retriever.md
> Cleaning the api docs

- haystack/retriever/dense.py
This is an idea brought up by @nliu86 in #602.
DPR._get_predictions() aggregates document and query embeddings as tensors stored on GPU. This is usually fine but can become a large amount of GPU memory overhead when datasets get large. This PR aims to move them from GPU to CPU as early as possible in the pipeline.
> Move DPR embeddings from GPU to CPU straight away

- haystack/document_store/base.py
- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/document_store/sql.py
- test/test_db.py
- test/test_dpr_retriever.py
- test/test_faiss.py
This PR adds a `return_embedding` parameter for `DocumentStore.get_all_document()` methods. 
Additionally, the default `return_embedding` parameters are set to `False`.
> Add return_embedding parameter for get_all_documents()

- README.md
Just give a small fix to Roadmap in the home page.
My editor (geany) clears out all leading spaces hope that's fine ;)
> README: Fix link to roadmap

- .github/workflows/formatting.yaml
- .github/workflows/shell_check.sh
- run_docker_gpu.sh
Let's add some small formatting checks for scripts. Small step toward more strict checks
> ops: add some formatting checks [now: shellchecks]

- haystack/retriever/dense.py
- remove unused tokenizer arg
- update desc of tqdm bar
> Refactor DensePassageRetriever._get_predictions

- README.md
- docs/_src/tutorials/tutorials/6.md
- docs/_src/usage/usage/document_store.md
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
- tutorials/Tutorial6_Better_Retrieval_via_DPR.py
Brought up in #634 
This PR makes it clearer how to pick a different flavor of FAISSDocumentStore (e.g. Flat vs HNSW). More information is now given in the tutorials and also on the website documentation.
> Add link to FAISS Info in documentation

- docs/_src/usage/usage/retriever.md
- haystack/document_store/base.py
- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/document_store/sql.py
- haystack/retriever/dense.py
- tutorials/Tutorial4_FAQ_style_QA.py
This PR makes improvements and fixes around the similarity functions used in embedding based retrieval. 
A warning will be logged in cases where there is a non-recommended Dense Retrieval Model / similarity function pairing. 
Scaling of dot product scores into probabilities is now also supported.
This addresses #661
TODO:
> Scale dot product into probabilities

- .github/workflows/ci.yml
- test/conftest.py
- test/test_faiss.py
- test/test_pipeline.py
- test/test_tfidf_retriever.py
This PR removes redundant fixtures for document stores and retrievers.
> Cleanup Pytest Fixtures

- .github/workflows/ci.yml
- haystack/document_store/elasticsearch.py
- haystack/retriever/base.py
- requirements.txt
The PR adds a new document store for the [Open Distro Elasticsearch](https://opendistro.github.io/for-elasticsearch/).
In addition to the filtering & query functionality of the `ElasticsearchDocumentStore`, the new document store provides efficient vector similarity implementation for large indices using the [KNN plugin](https://opendistro.github.io/for-elasticsearch/features/knn.html). 
Resolves #665
> Add DocumentStore for Open Distro Elasticsearch

- haystack/retriever/dense.py
the `num_negatives`  param in `TestSimilarityProcessor`  should be `num_positives`
#680
> fix a typo, num_negatives -> num_positives

- haystack/pipeline.py
- test/test_pipeline.py
With the new `Pipeline` class, a new node `JoinDocuments` was added to support combining results from multiple retrievers. By default, a `join_mode` called `concatenate` was implemented to collect documents retrieved by multiple retrievers. 
This PR adds a new `join_mode` called `merge` that can aggregate (weighted) scores for documents returned by multiple retrievers and return the top_k documents.
Resolves #125
> Add support for aggregating scores in JoinDocuments node

- haystack/retriever/dense.py
Fixes #677 and #678.
This PR unifies the default directory names for saving and loading DPR models. Furthermore, query and passage tokenizer are now saved in the correct directory.
> Fix saving tokenizers in DPR training + unify save and load dirs

- test/conftest.py
- test/test_db.py
The original issue is already resolved by #667. This PR now only adds a test.
Resolves #636
> Add support for custom embedding field for InMemoryDocumentStore

- README.md
On github mobile application logo is not visible on  if HTML is used instead of markdown embed image syntax. Refer image attached.
Also adding pypi download SDK badge
> Haystack logo is not visible on github mobile app

- haystack/document_store/sql.py
- requirements.txt
- test/test_faiss.py
To improve #601 
Generally ORM objects kept in memory cause performance issue
Hence using directly column name improve memory and performance.
Refer [StackOverflow](https://stackoverflow.com/questions/23185319/why-is-loading-sqlalchemy-objects-via-the-orm-5-8x-slower-than-rows-via-a-raw-my)
> Using Columns names instead of ORM to get all documents

- .github/workflows/ci.yml
- haystack/pipeline.py
- haystack/summarizer/base.py
- haystack/summarizer/transformers.py
- test/conftest.py
- test/pytest.ini
- test/test_faiss.py
- test/test_summarizer.py
To complete #651 
@tholor Please review, specially `generate_one_summary` option and one  TODO in `TransformersSummarizer`.
With `generate_one_summary` we can achieve both what you have [asked on original issue](https://github.com/deepset-ai/haystack/issues/651#issuecomment-737707756)
> I see two different options to implement:
> a) retrieve n docs and give 1 summary
> b) retrieve n docs and give 1 summary per doc
I am skipping tutorial and document (Readme etc) update for now. We can do in separate PR.
> Add Summarizer (standalone + node in custom pipelines + SearchSummarizationPipeline)

- README.md
Haystack pypi package name is `farm-haystack` instead of `haystack`
https://pepy.tech/project/farm-haystack
https://pypistats.org/packages/farm-haystack
> Correcting pypi download badge

- test/conftest.py
- test/test_faiss.py
This PR changes Pytest fixtures for `FAISSDocumentStore` & `SQLDocumentStore` to use in-memory SQLite. This avoids disk-IO related errors in tests running on Github Actions.
> Fix SQLite errors in tests

- haystack/schema.py
If we add new labels to elasticsearch and `update_existing_documents=True` for the DocumentStore, we will use elastic's `_op_type` `create` instead of `index`. However, this one requires us to supply an ID. Otherwise it crashes with: 
```
elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: an id must be provided if version type or value are set;')
``` 
This PR adds an ID field to the `Label` class in a similar way as we did with `Document`
> Add ID to Label schema

- haystack/document_store/elasticsearch.py
As discussed with @tholor in https://github.com/deepset-ai/haystack/issues/720, I've changed signature and docstring for `ca_certs` parameter in `ElasticsearchDocumentStore`.
> Change signature and docstring for ca_certs parameter

- haystack/document_store/base.py
- haystack/document_store/elasticsearch.py
- haystack/document_store/memory.py
- haystack/document_store/sql.py
- haystack/preprocessor/utils.py
- haystack/utils.py
- test/test_eval.py
When trying to add evaluation data containing millions of documents, my computer ran out of memory.
To solve this problem, this PR adds a method to add eval docs batch-wise so that not all eval docs have to be loaded to memory at once. Furthermore, this PR introduces the method `squad_json_to_jsonl` as the required format for `add_eval_data_batchwise` is jsonl.
> Make batchwise adding of evaluation data possible

- tutorials/Tutorial1_Basic_QA_Pipeline.py
- tutorials/Tutorial2_Finetune_a_model_on_your_data.py
- tutorials/Tutorial3_Basic_QA_Pipeline_without_Elasticsearch.py
- tutorials/Tutorial4_FAQ_style_QA.py
- tutorials/Tutorial5_Evaluation.py
- tutorials/Tutorial6_Better_Retrieval_via_DPR.py
- tutorials/Tutorial7_RAG_Generator.py
- tutorials/Tutorial8_Preprocessing.py
The tutorials are now encapsulated in methods and it is checked that the code is executed only by the main process but none of the subprocesses when using multiprocessing. This change only affects Windows users.
On Windows, this check is necessary to prevent the tutorial code from being executed in every subprocess when using multiprocessing. Without the check, every subprocess tries to spawn a new elasticsearch instance, write to the same log file, etc., which leads to "Permission denied" errors or "failed to obtain node locks" exceptions as reported in the following issue
closes #709
> Adding a guard that prevents the tutorial from being executed in every subprocess on windows

- haystack/document_store/base.py
Following PR #717, there was an issue on Windows file system paths. This PR aims at fixing this by adding the `Path `class from `pathlib`. 
@Timoeller
> use Path class in add_eval_data of haystack.document_store.base.py

- haystack/preprocessor/utils.py
Previously, `fetch_archive_from_http()` was taking up a lot of memory when uncompressing. This would cause the DPR training tutorial to trigger an Out of RAM Error. This problem is documented in #735. 
As suggested by @lalitpagaria, there is a more memory efficient way of performing the decompression. Their suggestion has been implemented here and it allows the notebook to run without problem.
> Reduce memory consumption of fetch_archive_from_http

- docs/_src/api/api/document_store.md
- haystack/document_store/memory.py
- haystack/document_store/sql.py
- test/conftest.py
- test/test_document.py
- test/test_document_store.py
This PR makes the following changes:
- `SQLDocumentStore.delete_all_documents()` was missing a database commit()
- The missing commit would not have been surfaced as an error by the tests. With this PR, the tests now inject a database transaction rollback, so similar issues can be caught by the tests.
- tests for deleting documents are extended to run for all document stores.
- `test_db.py` is renamed to `test_document_store.py`
- `test_document.py` is removed as it had no meaningful test cases
Additionally, the `InMemoryDocument.__init__()` had missing parameters that are now added.
> Fix delete_all_documents for the SQLDocumentStore

- docs/_src/api/api/retriever.md
- haystack/document_store/elasticsearch.py
- haystack/retriever/sparse.py
- test/test_elastic_retriever.py
This PR removes quotes around placeholders in Elasticsearch `custom_query` parameter. 
The placeholder terms(`$query`, `$years`) had quotes around them. For instance,
```python
retriever = ElasticsearchRetriever(
document_store=document_store,
custom_query="""
{
"size": 10, 
"query": {
"bool": {
"should": [{
"multi_match": {"query": "${query}", "type": "most_fields", "fields": ["text"]}}],
"filter": [{"term": {"year": "${years}"}}]}}}"""
)
```
The placeholders must be used without quotes. For instance,
```python
retriever = ElasticsearchRetriever(
document_store=document_store,
custom_query="""
{
"size": 10, 
"query": {
"bool": {
"should": [{
"multi_match": {"query": ${query}, "type": "most_fields", "fields": ["text"]}}],
"filter": [{"term": {"year": ${years}}}]}}}"""
)
```
> Remove quotes around placeholders in Elasticsearch custom query

- .github/workflows/ci.yml
- docs/_src/api/api/document_store.md
- haystack/document_store/base.py
- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/milvus.py
- haystack/document_store/sql.py
- haystack/generator/transformers.py
- requirements.txt
- test/conftest.py
- test/test_document_store.py
- test/test_dpr_retriever.py
- test/test_embedding_retriever.py
- test/test_faiss_and_milvus.py
- test/test_generator.py
- test/test_imports.py
- test/test_pipeline.py
- test/test_summarizer.py
This PR to integrate Milvus as document store with Haystack.
Task list -
Not handling these task in this PR, because it require discussion as milvus server need DB folder mounting for [persistent storage](https://milvus.io/docs/v0.10.5/milvus_config.md)  -
- Add tutorial
- Integrate milvus in docker compose instead of ES
> Milvus integration

- .github/workflows/ci.yml
Seems like the ubuntu image of the container running the CI has changed and does not include xpdf anymore :thinking:
> Fix pdftotext dependency in CI

- docs/_src/api/api/generator.md
- docs/_src/api/api/reader.md
- docs/_src/api/api/retriever.md
- haystack/generator/transformers.py
- haystack/reader/farm.py
- haystack/reader/transformers.py
- haystack/retriever/dense.py
- haystack/summarizer/transformers.py
The latest FARM version allows for specifying the model version when downloading a model from HuggingFace's Model Hub. This allows for the same model versioning to be done when initializing a FARM or Transformers Reader. Solves #712
> Add model versioning support

- docs/_src/api/api/document_store.md
- docs/_src/api/api/retriever.md
- haystack/document_store/base.py
- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/document_store/milvus.py
- haystack/document_store/sql.py
- haystack/generator/transformers.py
- haystack/reader/base.py
- haystack/retriever/dense.py
- haystack/schema.py
The numpy arrays were incorrectly typed as `np.array`(which is a function) instead of the type `np.ndarray`. The issue got surfaced with the latest `numpy` release.
This PR resolves the issue and removes some unnecessary type ignore.
> Fix mypy typing

- haystack/document_store/base.py
- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/document_store/milvus.py
- haystack/document_store/sql.py
- haystack/generator/transformers.py
- haystack/reader/base.py
- haystack/reader/farm.py
- haystack/reader/transformers.py
- haystack/retriever/dense.py
- haystack/retriever/sparse.py
- haystack/retriever/squad_to_dpr.py
- haystack/schema.py
- haystack/summarizer/transformers.py
- test/benchmarks/squad_to_dpr.py
Hello,
This is a first proposal for a squad to dpr dataset converter, as mentioned here: https://github.com/deepset-ai/haystack/issues/705#
I tried to take into account @brandenchan comments, although they may not follow what you had in mind (notably regarding to the API design). Still, it is a nice overview of where I am going with this.
I have also some doubts of how we could handle the large number of possible parameters (different arguments for different stores/retrievers). I took the path of "let the user handle that", so you can pass a dict with the appropriate config keywords to each document store/retriever you want to use.
As a side question, should we be able to treat SQuAD v1 datasets (without an `is_impossible` field) ?  For now, since we work with v1 SQuAD datasets, I just …
> SQuAD to DPR dataset converter

- haystack/document_store/base.py
- haystack/preprocessor/preprocessor.py
- haystack/preprocessor/utils.py
- test/test_preprocessor.py
There were problems with empty text in documents during preprocessing, as mentioned in https://github.com/deepset-ai/haystack/pull/751#issuecomment-765437866
This PR fixes #763 
Now also collects question IDs where the answer could not be converted and prints statistics about them, so it closes #774
> Improve preprocessing and adding of eval data

- docs/_src/api/api/document_store.md
- docs/_src/api/api/reader.md
- docs/_src/api/api/retriever.md
- haystack/document_store/faiss.py
- haystack/document_store/milvus.py
- haystack/reader/farm.py
- haystack/retriever/dense.py
At the moment every DPR query creates a tqdm progress bar when creating the embedding. If you run eval jobs with multiple thousand queries, logs will get very messy. Less disable tqdm for single samples
> Make tqdm progress bars optional (less verbose prod logs)

- docs/_src/api/api/document_store.md
- docs/_src/api/api/generator.md
- docs/_src/api/api/pipelines.md
- docs/_src/api/api/retriever.md
- haystack/__init__.py
- haystack/document_store/base.py
- haystack/generator/base.py
- haystack/pipeline.py
- haystack/reader/base.py
- haystack/retriever/base.py
- haystack/schema.py
- haystack/summarizer/base.py
- test/samples/pipeline/test_pipeline.yaml
- test/test_pipeline.py
This PR adds support to load a Pipeline with a YAML configuration file.
Here's a sample Pipeline YAML:
```yaml
version: '0.7'
components:    # define all the building-blocks for Pipeline
- name: MyReader       # custom-name for the component; helpful for visualization & debugging
type: FARMReader    # Haystack Class name for the component
params:
no_ans_boost: -10
model_name_or_path: deepset/roberta-base-squad2
- name: MyESRetriever
type: ElasticsearchRetriever
params:
document_store: MyDocumentStore    # params can reference other components defined in the YAML
custom_query: null
- name: MyDocumentStore
type: ElasticsearchDocumentStore
params:
index: haystack_test
pipelines:    # multiple Pipelines can be defined using the components from above
- name: my_query_pipeline    # a simple …
```
> Load Pipeline with YAML config file

- docs/_src/api/api/document_store.md
- haystack/document_store/__init__.py
- haystack/document_store/elasticsearch.py
- haystack/file_converter/__init__.py
- haystack/generator/__init__.py
- haystack/pipeline.py
- haystack/preprocessor/__init__.py
- haystack/reader/__init__.py
- haystack/retriever/__init__.py
- haystack/schema.py
- haystack/summarizer/__init__.py
With #785, a feature to create a Pipeline from a YAML configuration file was introduced. It iteratively loads components as defined in the YAML.
To support the loading of the components, the `BaseComponent` class registers all subclasses using the `__init_subclass__()`.  However, it may happen that a subclass is not yet evaluated by a Python interpreter, leading to a "component not found" error. The error did not get surfaced in the test cases as all the components used in the tests had already been imported and thus registered as subclasses of the `BaseComponent`.
This PR adds explicit import of components in their respective modules' `__init__.py` files.
Optionally, as a side benefit, it could simplify the import statements. For instance,
```python 
from …
```
> Fix building Pipeline with YAML

- rest_api/config.py
- rest_api/controller/file_upload.py
- test/test_rest_api.py
With the introduction of the `Preprocessor`, some cleaning steps like `remove_whitespace`, `remove_empty_lines ` were moved out of the file converters. This breaks the file upload API with the current Haystack version.
This PR adapts the file upload API to use the `Preprocessor` alongside the fie converters.
> Fix file upload API

- docs/_src/api/api/file_converter.md
- haystack/file_converter/pdf.py
- test/test_pdf_conversion.py
Fixes #805 
It seems that pdftotext uses different default encodings depending on the host machine. While on my machine all pdfs in #805 get converted correctly, the converter on a Google Colab notebook just produced gibberish.
It might be related to environment variables on the host like `LC_ALL` or `LANG`. 
With this PR we are enabling users to pass a custom `encoding` to `PDFToTextConverter.convert()`.
"Latin 1" is the default encoding of pdftotext. While this works well on many PDFs, it might be needed to switch to "UTF-8" or
others if your doc contains special characters (e.g. German Umlauts, Cyrillic characters ...).
Note: With "UTF-8" we experienced cases, where a simple "fi" gets wrongly parsed as "xef\xac\x81c" which is a [latin small …
> Fix encoding for pdftotext (Russian characters, German umlauts etc). Fix version in download instructions

- docs/_src/api/api/document_store.md
- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/document_store/milvus.py
- haystack/document_store/sql.py
- test/test_document_store.py
- test/test_faiss_and_milvus.py
The document stores provide a `update_embedding()` method that takes a retriever instance as an argument to create/update embeddings of all indexed documents. This works well for the creation of new document stores. However, this approach is inefficient when a large document collection is already present and you want to update only the newly added documents that don't have embeddings yet.
This PR introduces a new parameter `update_existing_embeddings` for `update_embeddings()`, which when set to `False`, will only generate embeddings for documents without embeddings. Additionally, `filters` are now also added to update embeddings for a subset of documents.
Resolves #806
> Introduce incremental updates for embeddings in document stores

- haystack/document_store/faiss.py
- requirements.txt
Since FAISS is now supported on Windows, we can remove the conditional import of `faiss` in the `FAISSDocumentDocumentStore`.
Resolves #817
> Remove conditional import of FAISS for Windows

- docker-compose.yml
- docs/_src/tutorials/tutorials/8.md
- rest_api/config.py
- rest_api/controller/search.py
- ui/utils.py
- ui/webapp.py
Problem occured on datasets with short docs. When putting the slider for top_k_reader to a high value (e.g. 10), while keeping top_k_retriever low (e.g. 1) the API returned less than the 10 expected answers and the UI crashed. Handled this case now + exposed a env variable for top_k_per_sample. We should further simplify this handling in #817
> Fix UI when API returns fewer answers than expected

- docs/_src/api/api/file_converter.md
- docs/_src/api/api/preprocessor.md
- haystack/document_store/base.py
- haystack/file_converter/base.py
- haystack/file_converter/docx.py
- haystack/file_converter/pdf.py
- haystack/file_converter/tika.py
- haystack/file_converter/txt.py
- haystack/pipeline.py
- haystack/preprocessor/base.py
- haystack/preprocessor/preprocessor.py
- haystack/reader/farm.py
- haystack/retriever/base.py
- test/samples/pipeline/test_pipeline.yaml
- test/test_pipeline.py
- test/test_retriever.py
The Pipelines were introduced to help build directed graphs from Haystack components to process a query.
This PR extends the Pipelines for building indexing workflows using components like file converters, preprocessors, retrievers, and document stores.
1. In the YAML configuration of Pipeline, a new field `type` is added. This can be used in the current version to specify `Query` & `Indexing` pipelines. In the future, additional types, for example, `RayQuery` can be added that builds a query pipeline with the Ray framework. This new `type` fields allows components like the Retriever to be "polymorphic". For instance, in the case of `Query`, it embeds a query, while, in an `Indexing` pipeline, it creates embeddings for the given list of documents.
2. There can be different root nodes …
> Add support for indexing pipelines

- README.md
The link to Quick Demo in ToC is fixed now.
> Fix link to Quick Demo in ToC.

- requirements.txt
Allow latest FAISS version. Benchmarks were ok, see #819.
Fixes #833
> Upgrade FAISS to 1.7.0

- docs/_src/api/api/document_store.md
- docs/_src/api/api/pydoc-markdown-document-store.yml
- docs/_src/usage/usage/document_store.md
Add documentation for the new Milvus document store.
> Add Milvus Documentation

- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/document_store/milvus.py
- haystack/reader/farm.py
- haystack/retriever/dense.py
We recently introduced the boolean argument `progress_bar` in various Haystack components to disable tqdm progress bars. However, the behavior was the opposite of the expected, i.e. `progress_bar=True` resulted in **not** showing the bar. Fixing this now.
Fixing #835
> Fix boolean `progress_bar` for disabling tqdm progressbar

- haystack/document_store/elasticsearch.py
There was a mixup in https://github.com/deepset-ai/haystack/commit/e641bff7a6f7e8e8154efd6bf561de39d6c9bf6b
This fixes the api key auth and http auth for elasticsearch
> Fixes elasticsearch auth

- docs/_src/api/api/generator.md
- docs/_src/api/api/pipelines.md
- docs/_src/api/api/reader.md
- docs/_src/api/api/retriever.md
- haystack/generator/base.py
- haystack/generator/transformers.py
- haystack/pipeline.py
- haystack/reader/farm.py
- haystack/reader/transformers.py
- haystack/retriever/base.py
- haystack/retriever/dense.py
- haystack/retriever/sparse.py
- haystack/summarizer/base.py
- haystack/summarizer/transformers.py
Pipelines allow specifying components to configured with YAML files. 
Currently, some parameters like `top_k` can be set dynamically for each query and are not available in the `__init__() of` components. 
This PR adds the missing parameters to enable configuring them with Pipelines.
The `top_k_answers` parameter in `RAGenerator` is renamed to `top_k` for consistency across components.
> Add runtime parameters to component initialization

- haystack/preprocessor/preprocessor.py
- test/test_preprocessor.py
The `split_respect_sentence_boundary` should only be applicable when the `split_by` parameter is set to `word.`
> Fix validation for `split_respect_sentence_boundary` in Preprocessor

- Dockerfile
- Dockerfile-GPU
> Add PDF converter in Dockerfiles

- haystack/pipeline.py
- test/test_pipeline.py
The current `Pipeline` supports parallel paths having exactly one node. For instance, the following graph will work with the existing `Pipeline` where nodes `C` and `D` are parallel paths.
However, when having more than 1 node in a parallel path is not supported. For instance, in the following graph, where `C`/`E` and `D` are in separate parallel paths.
This PR adds supports for the second type of graphs with multiple nodes in a parallel path.
> Add support for parallel paths in Pipeline

- README.md
I copy-pasted README.md to the premium account on https://grammarly.com and reviewed/applied all suggested changes.
> Run Grammarly over README.md

- docs/_src/api/api/pipelines.md
- haystack/pipeline.py
- test/test_pipeline.py
With #688, the `Pipeline` was extended to support executing graphs that have parallel nodes.
This worked well until there was a case with a graph having both "branch"(having multiple output streams) node and parallel nodes. In that case, the complete graph did not get executed, resulting in partial results.
Here's the graph:
When the `QueryRouter` returns `output_2`, then the pipeline executed only one of the two graph retriever nodes and returned the results.
This PR refactor the `run()` method which resolves the issue.
> WIP: Fix execution of Pipelines with parallel nodes

- docs/_src/api/api/retriever.md
- haystack/retriever/dense.py
- haystack/retriever/squad_to_dpr.py
- The key value pair "passage_id" was missing during conversion of squad to DPR.
- Added some minor improvements to the code.
- preprocessing of positive context (currently the whole passage is taken instead of a 100 word passage containing any of the annotated answers)
- the option for additional data besides SQuAD training set, such that hard negatives can be chosen from a larger pool of passages
- [optional] adding of no_answers as negative passages only (this change requires adjustments to the training code that always expects a positive context)
> Improve dpr conversion

- haystack/retriever/dense.py
When using the regular retriever.train method (as specified in Tutorial 9), the process fails in my local setting, due to an "cannot allocate memory error". 
After looking through the code, it turns out that the max_processes is by default 128 in farm's DataSilo. When I decreased it to a lower value, the method worked as expected.
Thus, I inserted the option to inject the max_processes value directly through the train method.
> fixed "cannot allocate memory" exception by specifying max_processes

- haystack/document_store/faiss.py
- haystack/document_store/milvus.py
Filters are not (yet) used in FAISS and Milvus: Warning is given, but no exception is raised. After this change filters can be used in a pipeline in other nodes. (see deepset-ai/haystack#912)
> Logged warning in Faiss and Milvus for filters

- docs/_src/usage/usage/retriever.md
Following the discussion on Slack ([link](https://haystack-community.slack.com/archives/C01J3TZM9HT/p1616749575046800)), the Y/N entries are simply copied over from the FAISS ones
> Add Milvus to the retriever / document store table

- haystack/eval.py
If the first query in the evaluation returns a document with `no_answer=True` we got a division by zero error because neither `self.has_answer_correct` or `self.has_answer_count` get incremented. This fix moves the `self.has_answer_recall` calculation within the if-else block.
> Fix division by zero error in EvalRetriever

- haystack/eval.py
A style proposal to reduce the precision shown in the `EvalRetriever.print` and `EvalReader.print` to 4 significant figures. If the user wants the full precision, they can access the class attributes directly.
Before
```
Retriever
-----------------
has_answer recall: 0.8739495798319328 (208/238)
no_answer recall:  1.00 (120/120) (no_answer samples are always treated as correctly retrieved)
recall: 0.9162011173184358 (328 / 358)
```
After
```
Retriever
-----------------
has_answer recall: 0.8739 (208/238)
no_answer recall:  1.00 (120/120) (no_answer samples are always treated as correctly retrieved)
recall: 0.9162 (328 / 358)
```
> Reduce precision in pipeline eval print functions

- docs/_src/api/api/document_store.md
- docs/_src/api/api/file_converter.md
- docs/_src/api/api/generator.md
- docs/_src/api/api/pipelines.md
- docs/_src/api/api/preprocessor.md
- docs/_src/api/api/reader.md
- docs/_src/api/api/retriever.md
pydoc-markdown changed handling of indentation as described here: https://github.com/NiklasRosenstein/pydoc-markdown/commit/f8ec013786698bce6ee0f88760ca210b89e0516b 
Previously, indentation was removed for all lines in docstring, including the code blocks. Now, indentation is preserved.
This PR adjusts the indentation according to the latest version of pydoc-markdown
Thanks @brandenchan for your support!
> Adding indentation to markup files

- haystack/pipeline.py
When loading a Pipeline, we check if any of the params reference another component. For instance, a Retriever instance can refer to a DocumentStore instance defined within the YAML.
This reference check throws an error in the case of a list as it tries to create a hash of it. This PR adds a validation that the parameter should be a string before checking if it references a component.
Resolves #951
> Fix passing a list as parameter value in Pipeline YAML

- haystack/document_store/elasticsearch.py
In order to use haystack in an aws sagemaker environment with an aws elasticsearch domain I needed the possibility to use the aws request signing. (Issue #966)
The ES client already has functionality for this included (see https://elasticsearch-py.readthedocs.io/en/v7.12.0/index.html?highlight=aws#running-on-aws-with-iam) but there is no option yet to funel this from the `ElasticsearchDocumentStore` to the `Elasticsearch` class. (at least I did not find an option)
This implementation enables the passing of an aws4auth object (see https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-python) to the `ElasticsearchDocumentStore` which then correctly instanciates the `Elasticsearch` with the needed request signing options.
This is …
> Feature: Enable AWS Elasticsearch IAM connection

- haystack/document_store/faiss.py
The FAISS library installation does not work out-of-the-box on some architectures like ppc64le. This PR enables Haystack to work without FAISS.
> Make FAISS import conditional

- haystack/document_store/faiss.py
FAISS import was made optional by #970. However, due to type hints and default parameter referencing `faiss`, the loading of Haystack does not work in the absence was FAISS.
> Fix optional FAISS import

- .github/workflows/ci.yml
- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/document_store/milvus.py
- test/conftest.py
- test/test_document_store.py
There are three main use cases for `update_embeddings()`:
1. Creating embeddings in a new document store after writing the documents. In this case, embeddings are created for all the documents in the document store. The default parameters for update_embeddings() are sufficient for this case.
2. Incremental update after adding more documents in an existing index. In this case, update_embeddings() can be called with `update_existing_embeddings` set to False to prevent recomputation of existing embeddings. 
3. Create/Update embeddings for a subset of documents in a document store using the `filters` parameter. For `FAISSDocumentStore`, `filters` cannot be used in conjunction with the `update_existing_embeddings` set to `True`.
This PR resolves #885 where `update_embeddings()` could result in …
> Fix update_embeddings() for FAISSDocumentStore

- haystack/pipeline.py
- test/test_pipeline.py
This PR adds a check to verify correct root node(`Query` or `File`) is used for creating a Pipeline.
> Add validation for root node in Pipeline

- test/test_faiss_and_milvus.py
This PR adds a test case to verify if the documents are loaded correctly from a saved FAISS Document Store and introduces the [tmp_path](https://docs.pytest.org/en/stable/tmpdir.html) fixture.
> Update tests for FAISSDocumentStore

- docs/_src/usage/usage/knowledge_graph.md
- haystack/graph_retriever/text_to_sparql.py
- haystack/knowledge_graph/graphdb.py
While we already have a [tutorial](https://github.com/deepset-ai/haystack/blob/master/tutorials/Tutorial10_Knowledge_Graph.py) about question answering on knowledge graphs, there is no documentation page yet.
This PR adds such a documentation page and covers the two classes GraphDBKnowledgeGraph and Text2SparqlRetriever.
As part of this PR, I added doc strings, which also list the parameters of the methods of the two classes.
> knowledge graph documentation

- haystack/utils.py
- tutorials/Tutorial11_Pipelines.ipynb
- tutorials/Tutorial11_Pipelines.py
This PR adds a notebook and .py tutorial which shows what can be done with Haystack pipelines
> Pipelines tutorial

- rest_api/controller/file_upload.py
- rest_api/pipelines.yaml
- ui/utils.py
- ui/webapp.py
- An Effort to Add file Upload Functionality
- Issue: #830
@Timoeller
> Add File Upload Functionality in UI

- docs/_src/usage/usage/document_store.md
Documentation for the feature introduced in #965: _How to use a aws elastic search service as document store._
(I'm not sure if the link to aws is really necessary. )
PS: Also removed some trailing whitespaces, I can revert that if it clashes with you code style guidelines.
> Docs: Add usage information detailes for aws elastic search service

- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/document_store/milvus.py
- haystack/document_store/sql.py
- haystack/file_converter/base.py
- haystack/file_converter/pdf.py
- haystack/file_converter/tika.py
- haystack/file_converter/txt.py
- haystack/generator/transformers.py
- haystack/graph_retriever/text_to_sparql.py
- haystack/knowledge_graph/graphdb.py
- haystack/pipeline.py
- haystack/preprocessor/preprocessor.py
- haystack/reader/farm.py
- haystack/reader/transformers.py
- haystack/retriever/dense.py
- haystack/retriever/sparse.py
- haystack/schema.py
- haystack/summarizer/transformers.py
- haystack/translator/base.py
- haystack/translator/transformers.py
- test/test_pipeline.py
This PR adds an `export_to_yaml()` method for the Pipeline class to create a YAML configuration for a loaded `Pipeline` instance. 
Under-the-hood, the `BaseComponent` saves the init parameters used to create a Component. These parameters are put together in `export_to_yaml() `to create the complete Pipeline config.
With this implementation, the init parameters are captured. Hence, any updates to a Component after it has been initialized are not reflected in the YAML.
An alternative approach to generating the YAML by taking a snapshot of instance attributes of Components when calling `export_to_yaml()` was also considered. With this approach, when export is called, we iterate over all the instance attributes of Components & filters the ones that are parameters in the corresponding …
> Add export of Pipeline YAML config

- ui/webapp.py
Earlier when we upload the file the response was shown in the query body which is inappropriate
I think it should be displayed in the sidebar like the below image
Earlier it was coming after Haystack Demo Title
**Review**
@oryx1729 @tholor
> change file-upload response to sidebar

- haystack/reader/farm.py
Adding the parameter `duplicate_filtering` to `FARMReader`
* added parameter in init()
* added parameter to config to enable export of component config as YAML
* use parameter value as setting for the prediction_head
* logging a warning if an older FARM version is used that does not support duplicate_filtering 
closes #990
> Allow filtering of duplicate answers as implemented in FARM

- haystack/reader/farm.py
- test/test_eval.py
Adding the parameter duplicate_filtering to FARMReader
added parameter in init()
added parameter to config to enable export of component config as YAML
use parameter value as setting for the prediction_head
logging a warning if an older FARM version is used that does not support duplicate_filtering
closes #990
> Filtering duplicate answers

- ui/requirements.txt
Resolves #1017
The `help` argument for `button()` is not available in streamlit v0.72.0. This PR upgrades it to the latest version.
> Fix evaluation mode in UI

- haystack/document_store/elasticsearch.py
`ElasticsearchDocumentStore` uses `ping()` to test the connection. This triggers an HTTP HEAD request to the Elasticsearch root URI. In case the user does not have sufficient privileges, it raises a Forbidden 403 response.
This PR adjusts the `ping()` to trigger only for the default Elasticsearch user as it might be helpful in debugging for new users.
> Fix Elasticsearch connection for non-admin users

- haystack/preprocessor/preprocessor.py
Logs a warning message if `PreProcessor.split()` causes whitespace normalization as a side effect. The need for this was raised by #983
> Add white space normalization warning

- haystack/document_store/base.py
- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/document_store/milvus.py
- haystack/document_store/sql.py
- test/test_document_store.py
…thod to delete_documents closed #1045
- ...
> [document_stores]Rename all document stores delete_all_documents() method to delete_documents

- haystack/document_store/base.py
- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/document_store/milvus.py
- haystack/document_store/sql.py
- haystack/errors.py
- test/test_document_store.py
- test/test_faiss_and_milvus.py
- Fixed duplicate documents issue.  fixed #1069
> Add options for handling duplicate documents (skip, fail, overwrite)

- haystack/document_store/sql.py
fixed #647
Current delete query took 12 m 54 s 892 ms on 10000000 records
```
DELETE FROM document WHERE document.id IN (SELECT document.id
FROM document
WHERE document.index = 'doc')
```
Updated delete query took 1 m 26 s 147 ms on 10000000 records
`DELETE FROM document WHERE document.index = 'doc'
`
**Sample data generation query:**
`insert into document (
id, text, index
)
select
s,
md5(random()::text),
'doc'
from generate_series(1, 10000000) s(i)`
- [] Added tests
> Improve the speed of FAISSDocumentStore.delete_documents()

- haystack/document_store/__init__.py
Add `OpenDistroElasticsearchDocumentStore` to `haystack/document_store/__init__.py` so that it can be loaded simply with
`from haystack.document_store import OpenDistroElasticsearchDocumentStore`
> Add OpenDistro init

- haystack/preprocessor/preprocessor.py
This PR solves #1023. 
Previously, `PreProcessor.split()` would normalize whitespace as an unintended side effect (`split_by = "word"` and `respect_sentence_boundary=False`). This is because text would go through these processing steps:
```
elements = text.split(" ")
segments = windowed(elements, n=split_length, step=split_length)
for seg in segments:
txt = " ".join([t for t in seg if not t])
```
The `if not t` in the list comprehension is used to filter out `None`s in the list but would also remove whitespace elements which would appear in the list if we had more than one space in a row in the original text. This list comprehension has been changed so that whitespaces are fully maintained.
This PR also removes a warning message that used to trigger when whitespace normalisation had …
> Preserve whitespace during PreProcessor.split()

- docs/_src/benchmarks/retriever_map.json
- docs/_src/benchmarks/retriever_performance.json
- docs/_src/benchmarks/retriever_speed.json
There is a duplicate benchmark run for BM25 / Elasticsearch at 100K docs.
The run is already removed from the csv. This PR removes it also from the json so that the website does not show it twice.
> Remove Duplicate Benchmark Run

- docs/_src/usage/usage/ranker.md
- haystack/ranker/farm.py
The ranker now distinguishes predictions with label "0" (dissimilar) and label "1" (similar) when extracting the probability of the prediction (similarity score).
Before this change, the re-ranking gave wrong results when documents to be re-ranked had a probability larger than 0.5 of being dissimilar. This probability was wrongly assumed to be the similarity score.
> Distinguish labels for calculating similarity scores

- docs/_src/usage/usage/ranker.md
- docs/_src/usage/usage/reader.md
- haystack/reader/farm.py
- Add more detailed documentation of confidence calibration to the reader's usage page.
- Add `calibrate_confidence_scores()` method to reader, which internally calls `eval()` method
closes #1032
> Add docu of confidence scores and calibration method

- haystack/document_store/faiss.py
- test/benchmarks/retriever_simplified.py
- test/benchmarks/utils.py
Allows FAISS HNSW to be initialized with L2 similarity. Also allows for more DocumentStore options in  `test/benchmarks/retriever_simplified.py`
> Add L2 support for FAISS HNSW

- haystack/eval.py
Rename `top_k_eval_documents` and allow it to be set in `EvalDocuments.run()`. Perform checks to ensure that `top_k_eval_documents` doesn't change over the course of evaluation and that we never get a situation where `EvalDocuments` is passed less documents than its `top_k`
> Add More top_k handling to EvalDocuments

- haystack/graph_retriever/text_to_sparql.py
- requirements.txt
Before the next Haystack release, we need to upgrade FARM from 0.7.1 to 0.8.0
I see only one problem that needs to be fixed. It's about the Text2SPARQL Retriever. The parameter `force_bos_token_to_be_generated` of the method `BartForConditionalGeneration.from_pretrained() `is deprecated now. as also discussed here https://github.com/huggingface/transformers/issues/11952 
All other tests pass and except for the transformers and torch upgrades there were no major changes in FARM. For DPR, I tested FARM and Haystack and we also got confirmation from https://github.com/deepset-ai/haystack/issues/1046#issuecomment-858559193
> Bump to FARM 0.8.0, torch 1.8.1 and transformers 4.6.1

- haystack/retriever/dense.py
Removed single_model_path because we don't use it anymore.
Added parameter `infer_tokenizer_classes` to `load` function of `DensePassageRetriever` so that DPR models with a non-BERT tokenizer can be loaded as required in #1046 
The loading can be done as follows after initializing from model hub and saving to disk:
```
retriever = DensePassageRetriever(
document_store=InMemoryDocumentStore(),
query_embedding_model="etalab-ia/dpr-question_encoder-fr_qa-camembert",
passage_embedding_model="etalab-ia/dpr-ctx_encoder-fr_qa-camembert",
max_seq_len_query=64,
max_seq_len_passage=256,
infer_tokenizer_classes=True
)
save_dir = "../saved_models/dpr"
retriever.save(save_dir=save_dir)
loaded_retriever = DensePassageRetriever.load(load_dir=save_dir, document_store=None, infer_tokenizer_classes=True) …
```
> Removed single_model_path; added infer_tokenizer to dpr load()

- haystack/document_store/weaviate.py
- Weaviate's replace method replaces the complete document with a new one where as "update" only updates the properties that are passed to the method and rest of the properties will be in tact. 
- Due to a defect in v1.3.0, Update Embeddings was implemented with replace. Now, changing the logic to use "update".
This is a minor change, all tests are passing.
> Update Embeddings - Use update instead of replace

- docs/_src/tutorials/tutorials/12.md
- tutorials/Tutorial12_LFQA.ipynb
- tutorials/Tutorial12_LFQA.py
Adding a little section to the new tutorials describing what we do
> Add about sections to Tutorial 12

- haystack/ranker/farm.py
- haystack/reader/farm.py
#234 introduced a quickfix that prevented Dataparallel from being applied twice. This quickfix is not needed anymore as the call of optimize_model in the Inferencer has been removed here deepset-ai/FARM@94c6b8d#diff-8a98ef73f1fa756ee7fdc0cd3a2f8bdc07f4e2eb490111356337ddc8c170066cR278
closes #1093
> Remove quickfix from reader and ranker

- haystack/reader/farm.py
> Remove unused method `_get_pseudo_prob()`

- test/conftest.py
- test/test_document_store.py
- test/test_generator.py
- test/test_retriever.py
Parametrizes document store tests allowing developers to select a subset of document stores in the generic document store related tests. 
~~This is just a preview and request for feedback. Only test/test_retriever.py tests have been updated for this preview. Updating other tests is trivial given this approach is approved.~~ All relevant generic document store tests have been updated.
To run tests for all document stores, an explicit parametrize annotation marker with a list of all document stores needs to be removed from a unit test function (see diff). However, we want to leave a particular explicit parametrize annotation in some test cases as the test might test a particular functionality for a specific document store. 
To try out an updated test approach, we'll …
> Improve document stores unit test parametrization

- haystack/generator/transformers.py
- haystack/reader/farm.py
- haystack/retriever/dense.py
- haystack/utils.py
- `init()` method now runs `initialize_device_settings(use_cuda=self.use_gpu)` to get Reader's device
- Reader's device is now used as default device of `eval()`, `eval_from_file()`, and `calibrate_confidence_scores()` but can be overwritten when calling these methods
- doc strings are updated accordingly
Note that `train()` also calls `initialize_device_settings(use_cuda=use_gpu,use_amp=use_amp)` as before because `train()` can be initialized with other a different value for `use_gpu` than the Reader itself.
closes #1137
> Use Reader's device by default

- rest_api/controller/search.py
Fix for #1122 
Let's not be so strict in what type of meta data we return. Even though we can't filter for other types yes, we could at least allow returning docs with these properties
> Relax typing for meta data

- haystack/file_converter/base.py
- haystack/preprocessor/base.py
- rest_api/controller/file_upload.py
- test/test_pipeline.py
- test/test_rest_api.py
- ui/utils.py
- Allow for batch indexing when using Pipelines ( fix #1168 )
> [pipeline] Allow for batch indexing when using Pipelines fix #1168

- haystack/document_store/sql.py
-In SQLDocumentStore write_labels using `self.label_index` and when calling get_label_count() we are using a different `self.index.` To solve this bug both indexes should be the same for labels.
> [document_store] SQLDocumentStore get_label_count() index bug fixed.

- haystack/document_store/elasticsearch.py
- Missing label_index var added.
> ElasticsearchDocumentStore get_label_count() bug fixed.

- haystack/document_store/sql.py
- SQLDocumentStore write_labels() id missing from label orm record. 
> Add `id` in `write_labels()` for `SQLDocumentStore`

- haystack/retriever/dense.py
Added global_loss_buffer_size to the DensePassageRetriever, in order to fix 'encoded data exceeds max_size' error.
- ...
> global_loss_buffer_size to the DensePassageRetriever, fix exceeds max_size

- haystack/ranker/__init__.py
- haystack/ranker/farm.py
- haystack/ranker/sentence_transformers.py
- test/conftest.py
- test/test_ranker.py
In contrast to FARMRanker, SentenceTransformerRanker uses the logit as similarity score and not the classifier's probability of label "1" 
see example here: https://www.sbert.net/docs/pretrained-models/ce-msmarco.html#usage-with-transformer
I tested with a subset of the nq_dev dataset. Here are the results of a pipeline with ElasticsearchRetriever and SentenceTransformerRanker with `"cross-encoder/ms-marco-MiniLM-L-12-v2"` as model:
```
EvalRetriever
-----------------
has_answer recall@2: 0.7200 (18/25)
no_answer recall@2:  1.00 (25/25) (no_answer samples are always treated as correctly retrieved)
has_answer mean_reciprocal_rank@2: 0.6200
no_answer mean_reciprocal_rank@2:  1.0000 (no_answer samples are always treated as correctly retrieved at rank 1)
recall@2: 0.8600 (43 / 50) …
```
> Add SentenceTransformersRanker with pre-trained Cross-Encoder

- README.md
In the readme file, links to tutorial 12 (LFQA) were missing. Adding these links with this PR.
> Add links to tutorial 12 to readme

- ui/requirements.txt
- ui/webapp.py
- update streamlit and st-annotated-text to latest version
- make use of latest st-annotated-test version to pass height argument for the iframe annotated text
Why?
stay up-to-date with streamlit features.
Context returned by haystack-api comes in various lenght and the annotated text library was using a fixed height, which sometime did not show entire context/answer and the layout was not optimal. With the latest st-annotated-text we can pass a dynamic height based on the result context lenght.
Breaking changes - None
Issue #1278
> Upgrade streamlit

- haystack/classifier/__init__.py
- haystack/classifier/base.py
- haystack/classifier/farm.py
- haystack/ranker/farm.py
- test/conftest.py
- test/test_classifier.py
- Add FARM classification node that enriches a List of Documents with class probabilities in `meta` field
**Status **:
> Add FARMClassifier node for Document Classification

- haystack/preprocessor/preprocessor.py
Reduce duplicated message when preprocessing
> Improve preprocessing logging

- haystack/document_store/base.py
- haystack/document_store/elasticsearch.py
- haystack/document_store/memory.py
- haystack/document_store/sql.py
- Raise warning when labels are overwritten  #1140
> [document_store] Raise warning when labels are overwritten

- haystack/document_store/sql.py
In SQLAlchemy relationships, `backref` creates bi-directional relationships automagically which is not needed in this case as both `DocumentORM` and `MetaORM` have "explicit" defined relationships. 
This PR replaces `backref` with `back_populates` and that removes the SQLAlchemy warnings as described [here](https://github.com/deepset-ai/haystack/issues/1250#issue-936218581).
> Fix SQLAlchemy relationship warnings

- haystack/document_store/elasticsearch.py
- Add support for connecting to elastic search without authentication, i.e no credentials, open to world instance
> feat: add support for elastic search to connect without any authentication

- docs/_src/usage/usage/question_generator.md
- haystack/document_store/base.py
- haystack/pipeline.py
- haystack/question_generator/__init__.py
- haystack/question_generator/question_generator.py
- haystack/reader/base.py
- test/conftest.py
- test/test_question_generator.py
- tutorials/Tutorial13_Question_generation.ipynb
- tutorials/Tutorial13_Question_generation.py
- tutorials/question_generation.py
This PR creates a QuestionGenerator class that takes a document as input and generates questions as output. Since the default models used only seem to generate about 3 questions per passage, input text is split into 50 word chunks with 10 word split overlap. This is somewhat inefficient since T5's max seq len is significantly longer. But this allows us to handle variable length documents.
As a bonus, this also allows the DocumentStore to be used as an iterator
TODO:
For future:
> Add QuestionGenerator

- requirements.txt
A new release of the Weaviate Python client breaks the tests.
> Pin Weaviate version

- haystack/__init__.py
There's verbose logging from FAISS when Haystack is initialized. This PR sets the log-level of `faiss.loader` to WARN level. 
Currently, haystack import looks like:
```python
>>> import haystack
07/29/2021 14:07:35 - INFO - faiss.loader -   Loading faiss with AVX2 support.
07/29/2021 14:07:35 - INFO - faiss.loader -   Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
07/29/2021 14:07:35 - INFO - faiss.loader -   Loading faiss.
07/29/2021 14:07:35 - INFO - faiss.loader -   Successfully loaded faiss.
07/29/2021 14:07:35 - INFO - farm.modeling.prediction_head -   Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
>>> 
```
With this PR:
```python
>>> import haystack
>>> 
```
> Suppress FAISS logs & apex warnings

- .github/workflows/ci.yml
- haystack/pipeline.py
- haystack/retriever/base.py
- haystack/schema.py
- requirements.txt
- test/samples/pipeline/test_pipeline.yaml
- test/test_pipeline.py
- test/test_ray.py
This PR is an initial prototype of how Haystack Pipelines can be scaled horizontally and distributed across a cluster of machines using the Ray framework. 
The design goal is to provide a standardized interface for Pipelines similar to the Haystack Components. A new `BasePipeline` class is added that is extended by `Pipeline` and `RayPipeline`. This allows users to switch between "execution engines" for the Pipelines while retaining the configuration for the Components.
The new `RayPipeline` has methods similar to the `Pipeline` class. With the current implementation, a `RayPipeline` can be instantiated locally or on a remote cluster using a Pipeline YAML configuration. Ray provides a `handle`, that allows easy integration of deployed Pipelines with Python code or REST APIs. 
Ray allows …
> Add Ray integration for Pipelines

- ui/requirements.txt
- ui/webapp.py
When using Haystack UI and streamlit, the default behavior is to upload one file at at time. Trying to upload a new file will override any file one has already uploaded. Streamlit now supports uploading multiple files and may be more intuitive for users of Haystack to use it as the default behavior.   
Return type for `st.sidebar.file_uploader` when `accept_multiple_files=True` is a list of the files and empty if no files are provided   
- Change `st.sidebar.file_uploader` to default to `accept_multiple_files=True` to allow for multiple files to be uploaded.   
> Allow multiple files to upload for Haystack UI

- docs/v0.8.0/_src/tutorials/tutorials/7.md
- haystack/generator/transformers.py
Initialize retriever in RAG generator
- ...
> Update docstring for RAG

- tutorials/Tutorial1_Basic_QA_Pipeline.ipynb
- tutorials/Tutorial3_Basic_QA_Pipeline_without_Elasticsearch.ipynb
- tutorials/Tutorial3_Basic_QA_Pipeline_without_Elasticsearch.py
- tutorials/Tutorial4_FAQ_style_QA.ipynb
- tutorials/Tutorial4_FAQ_style_QA.py
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
- tutorials/Tutorial6_Better_Retrieval_via_DPR.py
Removing the deprecated Finder from all remaining Tutorials
FYI @akkefa
> Remove Finder from tutorials

- haystack/document_store/elasticsearch.py
Fixes #1316 . 
In Haystack 0.9, the client is initialized [here](https://github.com/deepset-ai/haystack/blob/9e4d7bf9be8ac98de72338d8ba9db339d2af5d21/haystack/document_store/elasticsearch.py#L182). In this case, `hosts` is a dictionary that looks something like this:
```
hosts = [{'host': 'localhost', 'port': 9200}]
```
However, this doesn't work for an OpenDistro service. In [this thread](https://github.com/opendistro-for-elasticsearch/sample-code/issues/242) about OpenDistro, they present `hosts` as a list of strings. i.e.
```
hosts = ["https://admin:admin@localhost:9200/"]
```
This PR allows for this latter format of `hosts` to work.
> Support OpenDistro init

- README.md
- Our documentation how to run tests locally was outdated. This is particularly annoying for external, first-time contributors (see https://github.com/deepset-ai/haystack/issues/1353). While we should still simplify our test cases further, this PR at least updates the documentation to the current state of things.
> Update test documentation in readme

- haystack/pipeline.py
- rest_api/controller/search.py
Currently we enforce our `/search` endpoint in the REST API to return `Answers`. 
This doesn't work for pipelines that just have a retriever and return documents (like FAQ-Style).
For now we can mitigate it like this: 
- Add a `Docs2Answers` Node that can do the conversion in a pipeline
- Add a switch in there to distinguish between FAQ docs and regular ones
Long-term: We should rethink the API response format and also allow documents there
Usage Example:
```
version: '0.7'
components:    # define all the building-blocks for Pipelines
- name: ElasticsearchDocumentStore
type: ElasticsearchDocumentStore
params:
host: localhost
index: document
embedding_field: question_emb
embedding_dim: 768
excluded_meta_data:
- question_emb
- name: EBRetriever
type: EmbeddingRetriever …
```
> Add simple docs2answer node to allow FAQ style QA / Doc search in API

- haystack/document_store/milvus.py
Delete filtered set of vectors rather than the whole collection
- changed delete_documents() in MilvusDocumentStore to match expected behavior when deleting documents based on a filter
- Now deletes filtered set of vectors rather than the whole collection when deleting based on a filter
> Fix behavior of delete_documents() with filters for Milvus

- tutorials/Tutorial7_RAG_Generator.ipynb
- tutorials/Tutorial7_RAG_Generator.py
`delete_all_documents` --> `delete_documents` (cf. #1045)
> Rag tutorial fixes

- haystack/pipeline.py
- test/samples/pipeline/test_pipeline.yaml
- test/test_ray.py
In the current implementation of `RayPipeline`, `replicas` can be configured for each component in the YAML. For instance,
```YAML
version: '0.9'
components:
- name: ESRetriever
type: ElasticsearchRetriever
replicas: 2   # create replicas
params:
document_store: DocumentStore
- name: DocumentStore
type: ElasticsearchDocumentStore
pipelines:
- name: ray_query_pipeline
type: RayPipeline
nodes:
- name: ESRetriever
inputs: [ Query ]
```
The `replicas` is a configuration property for the `pipelines` rather than of the individual component. This PR updates that and adds a test case. With this, the YAML would look like this:
```YAML
version: '0.9'
components:
- name: ESRetriever
type: ElasticsearchRetriever
params:
document_store: DocumentStore
- name: DocumentStore
type: …
```
> Refactor `replicas` config for Ray Pipelines

- docs/_src/tutorials/tutorials/13.md
- tutorials/Tutorial13_Question_generation.ipynb
As suggested [here](https://github.com/deepset-ai/haystack/pull/1267#issuecomment-899000223), we can make Tutorial 13 run end-to-end in colab by supplying a no docker option for Elasticsearch.
Thanks @cvgoudar for pointing this out!
> Add support for no Docker envs in Tutorial 13

- haystack/document_store/__init__.py
Suggested by #1369. Add `WeaviateDocumentStore` to `document_store/__init__.py` so that it can be imported as follows:
`from haystack.document_store import WeaviateDocumentStore`
> Adjust WeaviateDocumentStore import

- docker-compose.yml
With this change, `docker-compose` will always check for new images for the API before running.
> docker-compose always pull REST API Image

- haystack/retriever/dense.py
Fixes #1305 
If `num_hard_negatives` is not 0, the retriever will create embeddings for empty hard negative passages when updating embeddings. This PR makes sure that `num_hard_negatives` is 0 when embedding passages.
> Ensure num_hard_negatives is 0 when embedding passages

- Dockerfile
- Dockerfile-GPU
- Automatic builds of Docker images were not running due to missing `-y` flag of tesseract installation
> Fix tesseract installation in Dockerfile

- README.md
- docker-compose-gpu.yml
- docker-compose.yml
- docker-compose finally allows a way to directly enable GPU resources: https://docs.docker.com/compose/gpu-support/
Prerequisite: You still need to have the nvidia-container-runtime installed on your host https://docs.docker.com/config/containers/resource_constraints/#gpu  
So you can now run the "demo-stack" via: 
```
docker-compose -f docker-compose-gpu.yml up -d
``` 
- Adding the public UI image to ensure that we have compatible versions and do not always need to build locally
- Removing `pull_policy` as this caused trouble with earlier docker-compose versions and even with most recent version did not work on all machines as intended
> Enable docker-compose for GPUs & Add public UI image

- haystack/pipeline.py
This PR makes mypy v0.910(latest) work on macOS.
> Add type ignore to resolve `mypy` errors

- rest_api/controller/file_upload.py
- rest_api/pipeline/pipelines.yaml
- rest_api/pipeline/pipelines_dpr.yaml
This PR adds the retriever in the indexing pipeline for the REST API module.
This automates the creation of embeddings in the case of dense retrievers like the DPR. 
An exemplary `pipelines_dpr.yaml` is added for using the `DensePassageRetriever`.
> Add support for Dense Retrievers in REST API Indexing Pipeline

- docker-compose-gpu.yml
- docker-compose.yml
The DocumentStore name was changed in #1430. This PR updates that for docker-compose files.
Resolves #1449.
> Update DocumentStore env in docker-compose

- docs/_src/api/api/document_store.md
- docs/_src/tutorials/tutorials/5.md
- tutorials/Tutorial5_Evaluation.ipynb
Update notebook so that it uses the same SAS as in the .py equivalent
> Define SAS model in notebook

- docs/_src/api/api/document_store.md
- docs/_src/tutorials/tutorials/5.md
- haystack/modeling/data_handler/data_silo.py
- haystack/modeling/infer.py
- haystack/modeling/utils.py
- test/conftest.py
- test/test_modeling_inference.py
- test/test_modeling_question_answering.py
- move last missing pieces from FARM to haystack: inferencer #1433
- moved util functions `calc_chunksize`, `log_ascii_workers` and `grouper` from `data_silo.py` to `uitls.py`
- not moved: `Benchmarker` class, streaming functionality of inferencer, `extract_vectors` method (using the language model only; no prediction head involved), `task_type == "embeddings"`
> Add inferencer for QA only

- docker-compose-gpu.yml
- docker-compose.yml
Related to #1497
Remove `restart=always` from `haystack-api` in both docker-compose files
**Status**:
- Ready to merge
> Remove 'restart=always' from 'haystack-api' in both docker-compose files

- haystack/preprocessor/utils.py
Download archive from url without temp file. To prevent issue similar to #1445
I will be splitting this PR https://github.com/deepset-ai/haystack/pull/1458 into 3 manageable parts.
1. Download archive via stream (This will cover in this PR)
2. Add Mac Runner based CI
3. Add Windows Runner based CI (It is very complex, hence better to do it in separate CI action file - Refer https://github.com/deepset-ai/haystack/pull/1458)
> Feat: Download archive from url without temp file

- haystack/file_converter/docx.py
This PR introduces a small change that introduces a newline character between paragraphs in the `DocxToTextConverter`. Before, separate paragraphs were concatenated without any space.
If the docx looked like this:
```
Introduction
This is the introduction...
```
The output string was:
```
IntroductionThis is the introduction...
```
With the changes made in this PR, the output string is:
```
Introduction
This is the introduction...
```
> Add newline between paragraphs in DocxToTextConverter

- CONTRIBUTING.md
- README.md
- docs/_src/api/api/document_store.md
- haystack/document_store/weaviate.py
- test/conftest.py
- test/pytest.ini
- test/test_document_store.py
- test/test_eval.py
- test/test_generator.py
- test/test_pipeline.py
- test/test_retriever.py
- test/test_summarizer.py
Running the tests locally is currently quite cumbersome as you need to start various external docker containers for elasticsearch, milvus etc. 
Let's simplify this and extend the option that was introduced in #1202, to run tests only on a subset or single documentstore. 
This means, when calling `pytest . --doc_store_type="memory"` we will run all tests that can be run just with the InMemoryDocumentStore, i.e.: 
- all the tests that we typically run on the whole "document store grid" will only be run for InMemoryDocumentStore
- any test that is specific to other document stores (e.g. elasticsearch) and is not supported by the chosen document store will be skipped (and marked in the logs accordingly)
Use one of the fixtures `document_store` or …
> Simplify tests & allow running on individual doc stores

- test/conftest.py
The selection of a certain `--document_store_type` introduced in #1487 did not work for tests that had multiple fixtures with parametrization as their signature rather looks like [faiss-farm] and the plain "faiss" keyword is therefore contained in item.keywords .
Extended the keyword check
FYI @lalitpagaria
> Fix document_store_type flag for tests with multiple fixtures

- docs/_src/api/api/ranker.md
- haystack/ranker/sentence_transformers.py
- After FARM migration #1492 there is no FARMRanker anymore and so this PR removes mentions of "FARM" from comments in the SentenceTransformersRanker class
> Remove mentions of FARM from Ranker comments

- haystack/modeling/conversion/transformers.py
This PR removes mentions of NER and text classification as possible task types from an error log message. Since FARM migration these task types are not supported anymore.
> Remove NER and text classification from model conversion

- requirements.txt
This PR removes one mention of `sentence-transformers` from the requirements. Before, there was `sentence-transformers` in line 20 and `sentence-transformers>=0.4.0` in line 44. This resulted in the following error when trying to install the requirements:
```
Double requirement given: sentence-transformers>=0.4.0 (from -r requirements.txt (line 44)) (already in sentence-transformers (from -r requirements.txt (line 20)), name=‘sentence-transformers’)
```
> Remove double mentions from requirements

- docs/_src/api/api/document_classifier.md
- haystack/document_classifier/transformers.py
- Format usage example of doc classifier so that formatting on docs website is correct. It's broken at the moment: https://haystack-website-git-transformers-docum-1662f6-deepset-overnice.vercel.app/reference/document-classifier
- Should instead look like other code snippets, e.g., https://haystack-website-git-transformers-docum-1662f6-deepset-overnice.vercel.app/reference/retriever
> Format doc classifier usage example

- rest_api/application.py
- rest_api/config.py
- rest_api/controller/document.py
- rest_api/controller/feedback.py
- rest_api/controller/router.py
- rest_api/controller/search.py
- rest_api/schema.py
- test/test_rest_api.py
Related to #797 
-----------------------
Adds a new `document` router and a new `DELETE /documents` endpoint, accepting filters, that allow deleting documents in the document store. Uses the underlying `BaseDocumentStore.delete_documents()` method.
> WIP Add rest api endpoint to delete documents by filter

- rest_api/controller/file_upload.py
- Disable file upload REST API for InMemoryDocStore. Indexing and query pipelines would create two different instances each with FAISS and InMemory document stores. While file upload with FAISS was already disabled, file upload with InMemoryDocStore was still enabled and this PR disables it.
A problem resulting from two separate instances of InMemoryDocStore in indexing and query pipelines where reported in #1637
> disable file upload for InMemoryDocStore

- docs/_src/api/api/document_store.md
- haystack/document_stores/elasticsearch.py
- haystack/document_stores/milvus.py
- haystack/document_stores/weaviate.py
Thanks to the changes in #1569, all document stores now support cosine similarity. This PR edits the doc strings to reflect this and also simplifies some wording so that it is clear to users.
> Standardize similarity argument description

- haystack/nodes/reader/table.py
This PR fixes a bug that arises when the TableReader model does not select any cells as answer cells but selects an aggregation operator.
> Fix TableReader when model does not select any cells

- docs/_src/usage/usage/preprocessing.md
- Documentation used the old `text` field name in document, which is now renamed to `content`.
> rename text variable of document to content

- Dockerfile
- Dockerfile-GPU
- docs/_src/api/api/document_classifier.md
- docs/_src/api/api/ranker.md
- docs/_src/api/api/reader.md
- docs/_src/api/api/summarizer.md
- docs/_src/api/api/translator.md
- haystack/__init__.py
- haystack/modeling/infer.py
- haystack/modeling/utils.py
- haystack/nodes/answer_generator/transformers.py
- haystack/nodes/document_classifier/transformers.py
- haystack/nodes/extractor/entity.py
- haystack/nodes/query_classifier/transformers.py
- haystack/nodes/question_generator/question_generator.py
- haystack/nodes/ranker/sentence_transformers.py
- haystack/nodes/reader/farm.py
- haystack/nodes/reader/table.py
- haystack/nodes/reader/transformers.py
- haystack/nodes/retriever/_embedding_encoder.py
- haystack/nodes/retriever/dense.py
- haystack/nodes/summarizer/transformers.py
- haystack/nodes/translator/transformers.py
- test/test_modeling_dpr.py
- test/test_modeling_prediction_head.py
Related to #1538 
This PR makes all nodes use the `initialize_device_settings` method from `haystack.modeling.utils` in order to set the device in a standard way.
Furthermore it sets the level for the StreamHandler defined in `haystack/__init__.py` to `INFO` in order to print the device settings to the console. However, I am not sure if we really want to do this, as this would increase the console output substantially. Also, it seems that the StreamHandler level that is set [here](https://github.com/deepset-ai/haystack/blob/27793814cf85d306e300e6fb06488e7f5b9d03c4/haystack/__init__.py#L10) overwrites the following lines where we set the logging level for `haystack.modeling.utils` to `INFO`.
> Standardize initialisation of device settings

- rest_api/application.py
- rest_api/controller/document.py
- rest_api/controller/feedback.py
- rest_api/controller/file_upload.py
- rest_api/controller/search.py
- rest_api/schema.py
- Introduce `operation_id` per endpoints as those will become part of the open API definition and is helpful when creating clients from there 
- Adding `response_model_exclude_none=True` to the search endpoint to exclude all fields with null value from the response (e.g. embedding=null won't be part of the response anymore)
> Improve open api spec

- docs/_src/api/api/document_store.md
- haystack/document_stores/faiss.py
- test/samples/pipeline/test_pipeline_faiss_indexing.yaml
- test/samples/pipeline/test_pipeline_faiss_retrieval.yaml
- test/test_faiss_and_milvus.py
- test/test_pipeline.py
- support faiss_index_path and faiss_config_path as constructor params
- override init or call recursively
- keep save() and load() class methods
- implement tests that use fresh FAISSDocumentStore and an existing
closes #1698
> Make FAISSDocumentStore work with yaml

- haystack/nodes/reader/farm.py
@ju-gu and I found a bug in the `eval()` method of `FARMReader` eval when using GermanQuAD. It seems that answers are wrongly aggregated such that answers to different questions end up in the same MultiLabel because the aggregation key label.id, label.query wasn't updated.
The label id is different for every annotation, while the query can be the same in multi-way annotated files.
- Use the tuple (doc_id, query) as key. There can't be multiple queries with the same text in the same document anyways. Questions with the same text can only occur in different documents. I am not sure why the label.id was included in the key.
**Open questions**:
- I saw that a question is assumed to be impossible to answer in case `label.no_answer == True:`. However, I could imagine that …
> Change answer aggregation key to (doc_id, query) instead of (label_id, query)

- docs/_src/api/api/pipelines.md
- haystack/nodes/base.py
- test/test_pipeline_debug_and_validation.py
Makes pipeline resistant to nodes that set strings or other non-dict values to their `_debug` output key. Related to https://github.com/deepset-ai/haystack-website/pull/191 
Right now whatever gets assigned to a node to their output `_debug` key will arrive in the pipeline's output as:
```
{
....
_debug: {
custom_node: {
input: { ... }
output: { ... }
runtime: { <content of the _debug key of the node> }
}
< other node's debug output >
},
....
}
```
> Pipelines now tolerate custom _debug content

- haystack/nodes/reader/table.py
Apparently, not all TaPas-based table reader models on the model hub contain an aggregation classifier. This PR changes the `TableReader` node such that these models without aggregation classification can be used as well.
> Allow TableReader models without aggregation classifier

- haystack/document_stores/elasticsearch.py
- test/test_document_store.py
Filter documents not containing embedding field
closes #1695
> Facilitate concurrent query / indexing in Elasticsearch with dense retrievers (new `skip_missing_embeddings` param)

- rest_api/pipeline/pipelines.yaml
- ui/utils.py
- ui/webapp.py
- Make the call that fetches the haystack version not critical (if it fails, ignore it) and quick (fail with a timeout of 100ms)
- Add a different error message if there is an error while decoding the API response (i.e. an error is returned instead of JSON)
- Fix parsing issue with nested MD/HTML (https://github.com/streamlit/streamlit/issues/3190)
- Make the default filters for the REST API /query endpoint an empty dict instead of None (https://github.com/deepset-ai/haystack/pull/1783)
- Return more context around each answer
> Small fixes to the public demo

- .github/workflows/linux_ci.yml
- .github/workflows/windows_ci.yml
- docs/_src/tutorials/tutorials/15.md
- requirements.txt
- tutorials/Tutorial15_TableQA.ipynb
This PR upgrades Pytorch to version 1.10.0. This should allow to use Haystack again inside Google Colab notebooks and, therefore, fix #1786, #1787 and #1788. The reason for the RestAPI tests to fail doesn't seem to be caused by the upgrade of the torch version, given that they fail on the current master branch as well.
> Upgrade torch to v1.10.0

- docs/_src/tutorials/tutorials/11.md
- tutorials/Tutorial11_Pipelines.ipynb
This PR removes the installation of the latest Haystack release from the Tutorial 11 notebook, as the latest release requires torch<1.10, which is causing problems on the current Google Colab environment.
> Fix Tutorial 11 on Google Colab

- test/test_rest_api.py
After removing a functionality that filtered out the "no-answer" replies from the Reader, some REST API test failed. 
This PR removes again these 'no-answer' results and tests only on the actual answers, as it was before.
> Fix the REST API tests

- ui/requirements.txt
The Streamlit UI Docker image seems to miss a dependency on `markdown`. I though it would get pulled as a dep of Streamlit, but somehow it is not. This fixes the deps list to include `markdown`.
> Add missing dependency to the Streamlit container

- docs/_src/tutorials/tutorials/16.md
- tutorials/Tutorial16_Document_Classifier_at_Index_Time.ipynb
- Link now points to tutorial 16 instead of tutorial 8
> Fix link to colab notebook in tutorial 16

- docker-compose-gpu.yml
- docker-compose.yml
- rest_api/pipeline/pipelines_dpr.yaml
Changes:
- Now both docker-compose files use Julian's countries dataset
- The GPU version uses DPR as the default pipeline in the REST API
- The GPU version has the file upload disabled to be ready to deploy as the hosted version (is this OK?)
Note: This assumes that the dataset used already has embeddings for the documents it contains. So do not merge before Julian confirms that the ES image has the embeddings too.
> Adapt docker-compose-gpu.yml to use DPR by default

- docs/_src/tutorials/tutorials/8.md
- haystack/nodes/__init__.py
- haystack/nodes/file_converter/__init__.py
- haystack/nodes/file_converter/azure.py
- haystack/nodes/file_converter/base.py
- haystack/nodes/file_converter/docx.py
- haystack/nodes/file_converter/formrecognizer.py
- haystack/nodes/file_converter/image.py
- haystack/nodes/file_converter/markdown.py
- haystack/nodes/file_converter/pdf.py
- haystack/nodes/file_converter/tika.py
- haystack/nodes/file_converter/txt.py
- haystack/utils/preprocessing.py
- requirements.txt
- test/test_file_converter.py
- tutorials/Tutorial8_Preprocessing.ipynb
- tutorials/Tutorial8_Preprocessing.py
This PR adds a file converter based on Microsoft Azure's Form Recognizer service capable of extracting text and tables. Given a file (e.g. PDF), it will return a list of dicts containing one dict for each table detected in the file and one dict containing the text of the file.
This PR changes the return type of all Converter nodes from `Dict[str, Any]` to `List[Dict[str, Any]]`. The reason for this is that the `AzureConverter` return a list of dicts containing one document dict of type `"text"` and n document dicts of type `"table"`. 
```python
converter = TextConverter()
doc = converter.convert(file_path=FILE_PATH)
```
```python
converter = TextConverter()
doc = converter.convert(file_path=FILE_PATH)[0]
```
> Add AzureConverter

- docker-compose-gpu.yml
- ui/utils.py
- ui/webapp.py
Removes the feedback buttons from no-answers: seems like Labels can't be created for them (which makes some sense). Also raises the number of concurrent requests per worker, given that I haven't found an easy way to raise the number of workers, to do some manual load tests tomorrow.
Also, in the last demo PR I added a line that didn't make sense :facepalm:. Here is how it should look like instead.
> Remove feedback from no-answers

- haystack/nodes/file_converter/azure.py
**Description**
1. When extracting tables and metadata with the form recognizer, it was iterated over the list of tables referencing to a changing meta dictionary, which was parsed to the final table result list. Each table thereby referred to the same meta dictionary. 
2. At the moment just the surrounding content length can be set , but not each individual for preceding and following content
1. Create a deepcopy of the individual meta field for each table and refer to this for the respective table solved the problem
2. Splitting "surrounding content length" in two variables "preceding content length" and "following content length"
> bugfix metadata extraction in form recognizer & split of surrounding content length

- haystack/nodes/retriever/dense.py
- ui/webapp.py
- Partially fix "Enter-to-run". Now works for user queries, but still doesn't for the random questions that are programmatically written in. Streamlit really offers no way to do this, seems impossible even to hack around this limitation.
- Add a proper page title and favicon
- Improved the dataset description a bit
- Fix minor issue with the Haystack version rendering
- Try a fix for a ghostly bug in Retriever occurring in case of many parallel requests hitting the server at the exact same instant.
> More demo bugfixes

- haystack/schema.py
> Fix loading and saving of EvaluationReszult

- ui/utils.py
- ui/webapp.py
Adds a link below the answer's context to the original Wikpedia article, if the page title and pare URL are available in the metadata of the document under the `title` and `url` keywords.
Falls back gracefully to the document's name, as it was before, if such data is not available.
> Add backlink below the context, if available in the doc's meta

- docs/_src/api/api/pipelines.md
- haystack/pipelines/base.py
- haystack/pipelines/standard_pipelines.py
- test/test_eval.py
- get rid of redundant queries param in pipeline.eval()
Each label already contains the query.
> remove queries param from pipeline.eval()

- docs/_src/api/api/evaluation.md
- haystack/nodes/evaluator/evaluator.py
- log warning in EvalDocuments and EvalAnswers constructors
- add warning to docstrings
Warning will be like:
```
WARNING - haystack.nodes.evaluator.evaluator -  EvalDocuments node is deprecated and will be removed in a future version. Please use pipeline.eval() instead.
WARNING - haystack.nodes.evaluator.evaluator -  EvalAnswers node is deprecated and will be removed in a future version. Please use pipeline.eval() instead.
```
**Status**:
closes #1717
must not be merged before #1760
> Deprecate old pipeline eval nodes: EvalDocuments and EvalAnswers

- haystack/modeling/model/prediction_head.py
- fix bug that only appears in torch 1.10.0 (not in torch 1.9)
- non-contiguous tensors cause CUDA errors
- based on https://github.com/pytorch/pytorch/pull/64954
closes #1833
> workaround torch bug with non-contiguous tensors

- haystack/nodes/ranker/sentence_transformers.py
- test/conftest.py
- test/test_ranker.py
The zip function used in line 110 intends to choose the logits array to be the key for the lambda function while it should be the first/second logit of the logit array which corresponds to the classification label (has_answer)
Question: which label is used for the gbert-reranking model hosted on huggingface.co/models ? I found in config.json just 0, 1 and I suppose 0 stands for no_answer, 1 stands for has_answer? Could you correct me if I am wrong thanks.
```python
sorted_scores_and_documents = sorted(zip(similarity_scores, documents),
key=lambda similarity_document_tuple: similarity_document_tuple[0],
reverse=True)
sorted_scores_and_documents = sorted(zip(similarity_scores, documents),
key=lambda similarity_document_tuple: similarity_document_tuple[0][1], …
```
> Fix bug ranker: wrong lambda function

- docs/_src/api/api/ranker.md
- haystack/modeling/model/optimization.py
- haystack/nodes/retriever/dense.py
This PR fixes #1820 by preventing to wrap an already existing DataParallel model in a second DataParallel model.
> Prevent wrapping DataParallel in second DataParallel

- docs/_src/api/api/primitives.md
- docs/_src/api/api/ranker.md
- haystack/pipelines/base.py
- haystack/schema.py
- introduce node_input parameter to `EvaluationResult.calculate_metrics()` and `EvaluationResult.wrong_examples()`
- introduce node_input as eval dataframe column with default value 'prediction'
- (node_input value for 'perfect retriever' would be 'label')
Closes #1850
> introduce node_input param

- docs/_src/tutorials/tutorials/convert_ipynb.py
- Adding UTF-8 encoding when reading the notebooks.
> Correct bug with encoding when generating Markdown documentation issue #1880

- .github/workflows/linux_ci.yml
- haystack/nodes/file_converter/azure.py
This PR adds the following improvements to the `AzureConverter`:
- Possibility to merge multiple column header rows
- Fixed ordering of preceding context and caption extracted from first row
- Possibility to convert a saved Azure JSON output
- Saving Azure output before processing it in order to have it saved in case of an error
> Add improvements to AzureConverter

- .github/workflows/windows_ci.yml
In my previous PR, I only set the version for mypy in the Linux CI. This PR also sets the version for mpy to 0.910 in the Windows CI, as  the newly released mypy version 0.920 seems to be incompatible with pydantic. We should review at a later point of time if future versions are compatible again.
> Fix WIndows CI

- haystack/utils/export_utils.py
**Proposed changes**
Export answers to csv method was broken since refactoring changes of the schema (answer format).
This PR fixes the export_answers_to_csv method
This method is not used at the moment.
> Changed export to csv method to new answer format

- requirements.txt
Related to #1310 
Motivated by compatibility problems between `ray==1.5.0` and M1 processors.
- Include later ray versions`ray>=1.5.0,<=1.8.0`
> Unpin ray version

- docs/_src/usage/usage/optimization.md
- docs/v0.10.0/_src/usage/usage/optimization.md
- docs/v0.9.0/_src/usage/usage/optimization.md
- docs/v1.0.0/_src/usage/usage/optimization.md
There was a small grammatical mistake on the page [https://haystack.deepset.ai/guides/optimization](url). The error was under "Document Length" in the second paragraph. The error was "we splitting documents to a maximum of 500 words " it should have been "we split documents to a maximum of 500 words."
> Fixed the grammatical issue in optimization guides #1940

- requirements.txt
This PR updates Ray to version 1.9.1 and higher. Earlier versions of Ray expose security vulnerabilities due to log4j.
Closes #1921
> Update Ray to version 1.9.1

- haystack/document_stores/weaviate.py
If we add Documents to `WeaviateDocumentStore` with `content_type=None`, we are not able to retrieve these Documents as `_convert_weaviate_result_to_document` will run into an `UnboundLocalError`. This PR makes sure that if we add a Document with `content_type=None`, we are setting `content_type` to `None` also when retrieving these documents.
Related to #1929
> Fix retrieving documents in `WeaviateDocumentStore` with `content_type=None`

- docs/_src/api/api/document_store.md
- haystack/document_stores/base.py
This PR fixes a Numba `TypingError` that occured when using a `DocumentStore` with `cosine` as similarity metric. There were two problems in `BaseDocumentStore`'s `normalize_embedding` method:
- Numba cannot handle the type `BaseDocumentStore`. Therefore, `normalize_embedding` needs to be a static method.
- Numba cannot handle the `axis` parameter of the `np.linalg.norm` method (see [here](https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html#linear-algebra))
Closes #1924
> Fix Numba TypingError in `normalize_embedding` for cosine similarity

- haystack/document_stores/faiss.py
- test/test_faiss_and_milvus.py
Loading a saved `FAISSDocumentStore` resulted in the following error: 
`TypeError: Object of type IndexFlat is not JSON serializable`
To fix this, I removed the `faiss_index` parameter from the config, as this cannot be serialized. 
Closes #1932
> Fix loading a saved `FAISSDocumentStore`

- haystack/document_stores/faiss.py
- haystack/document_stores/milvus.py
- haystack/document_stores/milvus2x.py
- Fix #1935
- [X ] First draft (up for discussions & feedback)
> Propagate duplicate_documents to base class initialization

- haystack/document_stores/faiss.py
Closes #1954
- [ X] First draft (up for discussions & feedback)
- [ X] Final code
> Fix vector_id collision in FAISS

- Dockerfile-GPU
- requirements.txt
We use `torch.set_warn_always` [here](torch.set_warn_always) that was introduced in torch v1.9.0.
This PR upgrades the minimum required version for PyTorch.
> Upgrade torch version

- docs/_src/api/api/retriever.md
- haystack/modeling/data_handler/data_silo.py
- haystack/nodes/retriever/dense.py
When we set the multiprocessing strategy based on a string given by the user we currently do not check whether that sharing strategy is actually available in the running operating system.
This PR adds that check with the help of https://pytorch.org/docs/stable/_modules/torch/multiprocessing.html#get_all_sharing_strategies
closes #1964 
> check multiprocessing sharing strategy is available

- docs/_src/api/api/reader.md
- haystack/modeling/data_handler/dataset.py
- this fixes https://github.com/deepset-ai/haystack/issues/1945 . According to torch, a list of numpy arrays should be converted to an array first for perfomance reasons.
- not sure if this needs tests as so far the function is not tested directly and it's probably tested at  a higher level.
- [ x] First draft (up for discussions & feedback)
> fix UserWarning from slow tensor conversion

- Dockerfile-GPU
- the new base image(#1960) doesn't have `curl`, so, the PDF converter install is moved after installing software dependencies.
- the latest version of `faiss` 1.7.1 installs without any errors, so the explicit pinned version is no longer required.
- `Cython` is probably not required?!
> Fix Dockerfile-GPU

- haystack/pipelines/base.py
For easier review of the evaluation dataframe the order of the columns was changed.
also the column df["node_input"] = "prediction", was deleted. I am not sure whether it is necessary if the whole column is set to "prediction". Might be even confusing for the retriever.
> change column order for evaluatation dataframe

- requirements.txt
Solves #1963
As discussed in the issue, the correct dependency should be `scikit-learn`, not `sklearn`. This change should have no impact on actual behavior because `scikit-learn` was still installed correctly as a 3rd party dependency.
I took the freedom to add `>=1.0.0` as version (which is already met currently).
> Use scikit-learn, not sklearn, in requirements.txt

- haystack/document_stores/elasticsearch.py
- do not set scores to None if the returned score from elasticsearch is 0.0
**impact**:
Downstream nodes like `JoinDocument`cannot deal with `None` scores.
fixes https://github.com/deepset-ai/haystack/issues/1911
> Fix elasticsearch scores if they are 0.0

- Dockerfile
- Dockerfile-GPU
- haystack/utils/docker.py
Introduces a small utility to download and cache the demo's model and NLTK data, then modifies Dockerimage and Dockerimage-GPU to call this function at build time.
This will provide users with a demo that does not need to download any model at its first run, making the demo installation process easier and a bit faster too.
Closes #1652
> Add models to demo docker image

- haystack/nodes/evaluator/evaluator.py
- process all prediction-label-combinations at once
closes #1769
> Enable batch mode for SAS cross encoders

- requirements.txt
Pillow:8.3.2 for python pil/pdfparser.py pdf parsing improper regular expression dos
Pillow package for python contains a flaw in pil/pdfparser.py that is triggered as carriage return characters are not properly handled in a regular expression. this may allow a context-dependent attacker to hang or slow down a python process using the library.
Security source: CVSS V3 from RBS
Fix version: 9.0.0
closes #1988
> Upgrade pillow version to 9.0.0

- docs/_src/tutorials/tutorials/2.md
- tutorials/Tutorial2_Finetune_a_model_on_your_data.ipynb
- Changed the link to the annotation tool to https://haystack.deepset.ai/guides/annotation (old link was pointing to a subsection of the readme that does not exist anymore)
Alternative link would have been https://annotate.deepset.ai/ but then users wouldn't be able to learn that they can host the tool themselves and what it does.
> update link to annotation tool docu

- docs/_src/tutorials/tutorials/5.md
- haystack/schema.py
- test/test_eval.py
nDCG is a popular Information Retrieval metric that we should support for document returning nodes.
It was officially requested in #925.
> Add nDCG to `pipeline.eval()`'s document metrics

- haystack/pipelines/base.py
Use parameters from `ElasticSearchDocumentStore` to fetch the signature, since `OpenSearchDocumentStore `and `OpenDistroElasticsearchDocumentStore` will return an incomplete list of availiable parameters.
linked issue #2012 
> Bugfix - save_to_yaml for OpenSearchDocumentStore

- .github/workflows/docker_build.yml
- Dockerfile
- Dockerfile-GPU
With this PR, 
- `haystack-cpu` Docker Image compressed size is reduced to 2.01 GB from 3.11 GB.
- `haystack-gpu` Docker Image compressed size is reduced to 4.4 GB from 6.66 GB.
> Disable pip cache for Dockerfiles

- requirements.txt
Due to the new 2.0.0 release, we should pin `pymilvus<2.0.0` for now
> Pin Milvus to <2.0.0

- docs/_src/api/api/document_store.md
- haystack/document_stores/elasticsearch.py
- test/test_document_store.py
- The `ElasticsearchDoumentStore` 's `get_all_documents_by_id` method should return documents for all ids that where passed in. Previously, a maximum of 10 documents was returned.
- [x ] Final code
- [ x] Added tests
- [ x] Updated documentation
> fix: get_documents_by_id should return docs for all passed ids

- haystack/nodes/other/join_docs.py
- test/test_standard_pipelines.py
Implements a solution to #2059
`JoinDocuments.run` takes an optional parameter `top_k_join` that overrides the instance `top_k_join` of `JoinDocuments`.
This allows `top_k_join` to be modified when `run`ing a pipeline, e.g.
```python
p = Pipeline()
p.add_node(component=retriever_1, name="R1", inputs=["Query"])
p.add_node(component=retriever_2, name="R2", inputs=["Query"])
p.add_node(component=JoinDocuments(join_mode="concatenate"), name="Join", inputs=["R1", "R2"])
results = p.run(query=query, params={ 'Join': { 'top_k_join': 1 } })
```
> Add `top_k_join` parameter to `JoinDocuments.run`

- docs/_src/tutorials/tutorials/2.md
- haystack/modeling/model/language_model.py
- tutorials/Tutorial2_Finetune_a_model_on_your_data.ipynb
- tutorials/Tutorial2_Finetune_a_model_on_your_data.py
Previously, the data augmentation and model distillation parts of the finetuning tutorial were not working due to 2 issues:
1) Wrong path to train file
2) The PR for implementing model distillation did not make sure that all `LanguageModel`s could actually return hidden states and attentions
This PR fixes those and uses a different dataset for model distillation in the tutorial to decrease notebook runtime (more than 1 h for distillation before). 
> Fix finetuning notebook augmentation

- rest_api/controller/search.py
- QueryResponse needs to be a dictionary where the documents contain embeddings as list of float but currently they are of type ndarray
Before returning the result of search queries check if any document contains an embedding of the wrong type and if so convert all of them.
The existing `to_json()` method of Document is never called neither by pydantic nor fastAPI. We should discuss whether a nicer solution than this PR that leverages the NumpyEncoder instead is possible. An alternative is described below.
closes #1815
**Alternative:**
As an alternative, we could only make changes in `rest_api/schema.py`, which define how to encode **QueryResponse** as json and keep the type of `embedding` in `DocumentSerialized` a `np.ndarray` (as in `Document`). In that case, the …
> Convert doc embedding from ndarray to list of float for REST API

- .github/workflows/linux_ci.yml
- .github/workflows/windows_ci.yml
Currently if the build-cache is hit, code changes take no effect:
- without editable mode, a wheel file for haystack is created and it is installed into the python env site-packages (farm_haystack-1.1.0.dist-info) linking to the haystack location. Although there is no code installed, changes of the next commit take no effect, probably due to the interplay of python caching and build chaching.
- with editable mode there is only a farm-haystack.egg-link created in the python env pointing to the haystack location
- install haystack in editable mode in CI scripts
> Fix CI build-cache issue causing code changes to take no effect

- .github/workflows/linux_ci.yml
- .github/workflows/windows_ci.yml
- haystack/__init__.py
- setup.cfg
It makes impossible to run tests reliably, as the cache will prevent the runner from picking up the latest code changes somehow.
While debugging this issue, let's disable the cache to not disrupt other PRs.
> Disable cache on the CI

- haystack/document_stores/elasticsearch.py
- test/test_document_store.py
Added the fix for the #2055 issue.
**Proposed changes:**
Once the search fields are set in the Elasticsearchdocument store initializing, those fields should be mapped as "text" fields while indexing. 
Added the code which will take the search fields and add the type as "text". This matches the checks added in "_create_document_index" and makes the search fields full-text searchable.
> Fixed the Search Field mapping in ElasticSearch DocumentStore

- haystack/modeling/training/base.py
Currently, all student hidden states and activations need to be copied to cuda:0. The teacher is also only on cuda:0. This means the total batch size is limited by the memory of cuda:0 and also negatively affects performance.
This PR solves this issue by calculating the intermediate layer loss on each GPU independently.
> Distribute intermediate layer distillation loss calculation over multiple GPUs

- haystack/modeling/training/base.py
#2090 introduced a bug because it was applying `DataParallel` twice for multiple GPUs. This PR fixes that.
> Do not apply DataParallel twice

- .github/workflows/update_docsstrings_tutorials.yml
Right now it commits the updates on every branch, which is a bit distracting, especially for external contributors. This change makes the bot work only on pushes to `master`, removing the disturbance for open PRs.
Adds a `workflow_dispatch` trigger to allow manual triggers of this action if needed.
> Make the docstring bot work only on master

- tutorials/Tutorial12_LFQA.ipynb
- Install faiss dependency in tutorial 12 as it uses a FAISSDocumentStore later on.
> Add faiss dependency to tutorial 12

- .github/workflows/generate_openapi_specs.yml
- .github/workflows/linux_ci.yml
- .github/workflows/windows_ci.yml
- Dockerfile
- rest_api/LICENSE
- rest_api/setup.py
- setup.cfg
- ui/Dockerfile
- ui/LICENSE
- ui/setup.py
As noticed with #2086, the dependency management of the UI and REST_API was suboptimal, as it treated the dependencies of these two packages as dependencies of Haystack itself. However, the UI does not even depend on Haystack, while the REST API should install Haystack as their own dependency, rather than the contrary.
As a solution I propose:
- Make a `setup.py` file for the `ui/` folder. 
- From now on, the UI will be installed (after a git clone) with `pip install ui/` (or `pip install .` from the `ui/` folder).
- Installing the UI will not install Haystack.
- There is no more `pip install farm-haystack[ui]`.
- In this case I chose a `setup.py` file because apparently a package cannot be installed if it lacks both `setup.py` and `pyproject.toml`. Given that both would be basically …
> Make `ui` and `rest` proper packages

- haystack/document_stores/base.py
- change a list to a set to make "exists" check linear time instead of quadratic time.
> Fixed performance bug. Using a list where a set is needed.

- haystack/utils/squad_data.py
- test/test_utils.py
I noticed that you need to basically initialize an empty `SquadData` class to perform conversion of a dataframe to SQuAD format while responding here https://github.com/deepset-ai/haystack/issues/2119#issuecomment-1028982968. This change makes the method a class method which allows to do the conversion directly.
- [ x] First draft (up for discussions & feedback)
- [ x] Added tests
> Simplify SQuAD data to df conversion

- Dockerfile-GPU
Remove leftover `rest` extra from Dockerfile-GPU (removed in #2098)
> Remove `rest` extra from Dockerfile-GPU

- docs/_src/api/api/document_store.md
- docs/_src/api/api/pipelines.md
- haystack/pipelines/base.py
- test/test_eval.py
- `pipeline.eval()` gets an additional parameter `pass_documents_as_input` that enables passing the gold documents specified in the labels to the first node in the pipeline as input. It's an alternative way to evaluate the reader node only, with the advantage that no retriever needs to be specified in the pipeline.
> Evaluating a pipeline consisting only of a reader node

- docs/_src/api/api/document_store.md
- setup.cfg
The latest Ray release made `aiorwlock` a required package. This PR adds `aiorwlock` to the `ray` extra dependency group.
It also fixes the range some dependencies which had no upper limit yet.
> Add aiorwlock to 'ray' extra & fix maximum version for some dependencies

- docs/_src/tutorials/tutorials/6.md
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
Removes the installation of `milvus` extra on the Colab notebook of Tutorial 6. It's needless (Milvus can't run on Colab anyway) and was probably causing the dependency resolution & backtracking issue we spotted occasionally.
> Fix dependency management in Tutorial 6

- docs/_src/api/openapi/generate_openapi_specs.py
Currently `openapi.json` is generated as a single line, making its diff nearly impossible to parse.
This PR makes `generate_openapi_specs` output a multiline `openapi.json` file.
> Make `openapi.json` multiline so the diff is parsable

- docs/_src/api/openapi/openapi.json
- docs/_src/tutorials/tutorials/6.md
- rest_api/application.py
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
The version for the REST API FastAPI application was hardcoded to 1.0.0. Here The version number is now aligned with Haystack's.
> Align REST API and Haystack versions

- docs/_src/api/api/pipelines.md
- haystack/pipelines/base.py
**Issue**
I noticed that pipelines with only a reader node cannot process labels that contain a filter setting. That's because the pipeline receives the filters via the parameters of the pipeline and the pipeline finds that none of its nodes can process this parameter. The error raised is: https://github.com/deepset-ai/haystack/blob/795c7c8a475ce34ad8920cf9d30cc0f1c8113df5/haystack/pipelines/base.py#L410
As either documents are given as input to the evaluation or there is a retriever that can deal with filters, I suggest the following change:
-  In `pipeline.eval()`, if the label contains a filter, the filter is applied unless documents are already given
> Apply filter in eval only if no gold docs are given as input

- README.md
- Section that tells the reader about what companies already use Haystack, this helps strengthen the horizontal relationships in the community
The inspiration is taken from the [Apache Superset repository](https://github.com/apache/superset/blob/master/RESOURCES/INTHEWILD.md)
> Add who uses Haystack section

- tutorials/Tutorial1_Basic_QA_Pipeline.py
because FAISSDocumentStore errored with ElasticSearchRetriever
- change DocumentStore as the FAISSDocumentstore is not compatible with the ElasticSearchRetriever used later on
- in the Notebook version of this tutorial there is no FAISSDocumentstore being used either
> Changed document_store to ElasticsearchDocumentStore

- rest_api/controller/file_upload.py
Related to https://github.com/deepset-ai/haystack-website/pull/235.
A URL in `POST /file-upload` was referring to localhost: this PR fixes the URL so that points to the Haystack website.
> Update url in POST /file-upload

- .github/utils/generate_json_schema.py
- json-schemas/haystack-pipeline-1.2.0rc0.schema.json
- json-schemas/haystack-pipeline.schema.json
Related to #2110.
- As noted in https://github.com/SchemaStore/schemastore/pull/2057#issuecomment-1024470105, Schemastore supports schema indices hosted remotely. They will allow us to be in control of the versioning of our schemas without the need to submit a PR to them every time we release a new schema version.
- Said index is generated in the CI and will always have at most one `rc` version in it (to avoid pollution). They're unstable anyway (they get overwritten at every push to master) so I don't think they should stay in the index once they become obsolete.
- This change also fixes the (currently failing) CI :sweat_smile:
**Status**:
> Generate JSON schema index for Schemastore

- docs/_src/api/openapi/openapi.json
- haystack/pipelines/base.py
- json-schemas/haystack-pipeline-1.2.0rc0.schema.json
- rest_api/controller/search.py
- test/test_pipeline.py
- test/test_standard_pipelines.py
- Add `components` property to `Pipeline`
- Improve `Pipeline.get_document_store()` by looking into `BaseRetriever` components' `document_store` field
fixes https://github.com/deepset-ai/haystack/issues/1823
> Fix Pipeline.components

- haystack/document_stores/elasticsearch.py
- test/test_document_store.py
This PR fixes the bug that the `skip_missing_embeddings` parameter is ignored when filters are specified. Closes #2113.
> Fix missing embeddings not skipped if filters are used

- docs/_src/api/openapi/openapi-1.2.0.json
Rename openapi specs for release
> Rename openapi-1.2.0rc0.json into openapi-1.2.0.json

- haystack/nodes/file_converter/parsr.py
This PR fixes the table extraction of the `ParsrConverter`. Previously, the number of columns was determined on the number of columns in the first row. However, due to merged cells, the number of columns can be larger in the following rows. The number of columns is now determined based on the max number of cells of each row.
> Fix table extraction in `ParsrConverter`

- conftest.py
- haystack/document_stores/milvus2.py
- test/conftest.py
- test/test_document_store.py
- test/test_retriever.py
- test/test_standard_pipelines.py
A lot of tests using document stores are currently being skipped. This PR makes sure that these tests are not skipped.
> Fix skipping of tests using document stores

- haystack/nodes/reader/base.py
- moved the predict assignment from line 82 to line 81 in reader/base.py
> Update reader/base.py to fix UnboundLocalError in #2273

- haystack/pipelines/base.py
- test/test_pipeline.py
- convert document stores to type `DeepsetCloudDocumentStore`
- show info 
INFO:
```
In order to be used on Deepset Cloud, component 'MyDocumentStore' of type 'ElasticsearchDocumentStore' has been automatically converted to type DeepsetCloudDocumentStore. 
Usually this replacement will result in equivalent pipeline quality.  
However depending on chosen settings of 'MyDocumentStore' differences might occur.
```
closes https://github.com/deepset-ai/haystack/issues/2235
> save_to_deepset_cloud: automatically convert document stores

- README.md
- haystack/utils/import_utils.py
- Adding quotes around square brackets in install commands to go around the zsh shell issue. Works for others as well
@ZanSara, I'll also add quotes to the line in `import_utils.py` below: 
```
def _optional_component_not_installed(component: str, dep_group: str, source_error: Exception):
raise ImportError(
f"Failed to import '{component}', "
"which is an optional component in Haystack.\n"
f"Run 'pip install farm-haystack[{dep_group}]' "
"to install the required dependencies and make this component available."
) from source_error
```
What this prompt suggests will also result in `zsh: no matches found: farm-haystack[crawler]`. 
But let me know if I should keep them out here.
- [ x] First draft (up for discussions & …
> adding quotes for zsh shell issue

- docs/_src/api/api/preprocessor.md
- haystack/nodes/preprocessor/base.py
- test/test_preprocessor.py
Due to an oversight from my side when merging a recent Preprocessor feature, the preprocessor tests now fail for a missing `Document` import.
This PR fixes the issue.
> Fix PreProcessor test

- .github/workflows/linux_ci.yml
**Problem**
CI is breaking on `hashFiles` after tests are run due to permission problem in the "volume" folders created by docker-compose into the haystack folder. https://github.com/deepset-ai/haystack/runs/5495633130?check_suite_focus=true 
Related to https://github.com/actions/cache/issues/753
**Solution**:
Start docker-compose outside of the haystack folder.
> create milvus2 containers outside of haystack

- haystack/nodes/preprocessor/preprocessor.py
- test/test_preprocessor.py
I actually just wanted to fix the bug in test `test_remove_substrings` as it uses a Document and not a dict. But I found it counterintuitive that preprocessor changes the input inplace if it's not splitting texts. This PR fixes this too.
- fix bug in `test_remove_substrings`
- deepcopy document if text is changed during cleaning
> Prevent Preprocessor from changing existing documents

- .github/workflows/windows_ci.yml
So far Windows CI won't try to install its dependencies if the cache missed. This PR fixes the issue.
> Make Windows CI more resistant to cache misses

- docs/_src/api/api/pipelines.md
- haystack/nodes/base.py
- haystack/pipelines/base.py
- haystack/pipelines/config.py
- test/test_pipeline.py
This fixes a NetworkUnfeasible Exception during topological_sort of component construction code lines in `generate_code()` if we need the retriever during indexing:
```Graph contains a cycle or graph changed during iteration```
Sample YAML to reproduce:
```yaml
version: 'unstable'
components:    # define all the building-blocks for Pipeline
- name: DocumentStore
type: DeepsetCloudDocumentStore
- name: Retriever
type: ElasticsearchRetriever
params:
document_store: DocumentStore    # params can reference other components defined in the YAML
- name: TextFileConverter
type: TextConverter
- name: Preprocessor
type: PreProcessor
pipelines:
- name: indexing
nodes:
- name: TextFileConverter
inputs: [File]
- name: Preprocessor
inputs: [TextFileConverter]
- name: Retriever
inputs: [Preprocessor]
- …
```
> Fix dependency graph for indexing pipelines during codegen

- haystack/nodes/evaluator/evaluator.py
- haystack/pipelines/base.py
- Added sas_batch_size and sas_use_gpu to pipeline.eval and semantic_answer_similarity
- sas_batch_size defaults to 32 as in CrossEncoder and SentenceTransformer
- sas_use_gpu defaults to True which is used to set device in semantic_answer_similarity to None which is the default behavior in CrossEncoder and SentenceTransformer and checks if GPU is available. If False, device is set to 'cpu'
> Sas gpu additions

- .github/release.yml
- Currently, the label to exclude a PR from the release notes is called `ignore-for-release`. That might be misleading. Let's rename it to `ignore-for-release-notes`. I have already renamed the label within GitHub.
> rename label: ignore-for-release-notes

- docs/_src/tutorials/tutorials/16.md
- docs/_src/tutorials/tutorials/4.md
- docs/_src/tutorials/tutorials/8.md
- haystack/telemetry.py
- haystack/utils/import_utils.py
- tutorials/Tutorial16_Document_Classifier_at_Index_Time.ipynb
- tutorials/Tutorial4_FAQ_style_QA.ipynb
- tutorials/Tutorial4_FAQ_style_QA.py
- tutorials/Tutorial8_Preprocessing.ipynb
- tutorials/Tutorial8_Preprocessing.py
I checked all tutorials and found a few problems. 
- Tutorial 4 and 8 weren't working because of the newly introduced `doc_dir` variable. They are working again with this PR.
- Tutorial 10 didn't send an event because the dataset is not stored in our standard dataset directory. I included this non-standard url to our short list of known tutorial urls.
- Tutorial 16 was missing the ocr dependencies and they are added now
- Tutorial 15 uses a slightly different data path now to include tables AND texts now
**Required changes addressed implemented in other PRs**:
- A bug in tutorial 14 will be fixed by this PR: https://github.com/deepset-ai/haystack/pull/2336
- Changes to tutorial 15 might done also in a separate PR: https://github.com/deepset-ai/haystack/pull/2325
> Fix tutorial dataset paths

- haystack/utils/doc_store.py
This fixes:
- `launch_weaviate()` was broken because of missing f-string
- `launch_*` scripts did not start existing containers with same name (docker run command errored out with message that there is already a container with such a name, but didn't start it)
- fix docker command in `launch_weaviate()`
- try to start existing containers in launch scripts
> Fix docker launch scripts

- .github/workflows/linux_ci.yml
- haystack/document_stores/pinecone.py
Previously, the Pinecone tests in our CI were failing as a result of multiple concurrent requests in the Pinecone API due to multiple open PRs. This PR makes sure that the Pinecone tests are only run in our CI, if any of the Pinecone related files (`document_stores/pinecone.py`, `document_stores/base.py`, `document_stores/sql.py`, `document_stores/filter_utils.py`) changes.
> Run Pinecone tests only if files related to Pinecone changed

- docs/_src/api/api/document_store.md
- haystack/document_stores/base.py
Currently when passing a single vector to `DocumentStore.normalize_embedding` an error is thrown if numba is installed. `normalize_embedding` expects 1-dimensional or 2-dimentional vectors, selecting an appropriate code path for each. However numba needs to compile the whole function. Thus the 2-dim path is also being compiled with 1-dim args resulting in a `TypingError` as `ascontigousarray()` only exists for ndarrays and not for floats:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/tstad/git/haystack/haystack/document_stores/weaviate.py", line 477, in write_documents
self.normalize_embedding(vector)
File "/home/tstad/miniconda3/envs/haystack-dev/lib/python3.7/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
error_rewrite(e, …
```
> Fix `normalize_embedding` using numba

- docs/_src/tutorials/tutorials/1.md
- tutorials/Tutorial1_Basic_QA_Pipeline.ipynb
- A comment in the tutorial described `Document` as having a `text` attribute. This has been renamed to `content`.
> Change document attribute from text to content

- haystack/telemetry.py
- Documentation text about how to opt-out of telemetry is changed to emphasize that the environment variable is not a global variable in the python code but a variable that can be set on the level of the operating system, explicitly pointing to the docu.
- The reason for this change is that a user could easily think that `HAYSTACK_TELEMETRY_ENABLED="False"` in python disables telemetry. However, this only sets the **name** of the environment variable that Haystack uses to check whether telemetry is disabled or not
> change docu text about how to opt-out

- docs/_src/tutorials/tutorials/9.md
- tutorials/Tutorial9_DPR_training.ipynb
Fix a broken link in the docs: `squad_to_dpr.py` was moved under the `utils` module.
> Fix link to squad_to_dpr.py in DPR train tutorial

- haystack/document_stores/elasticsearch.py
- haystack/nodes/_json_schema.py
- haystack/pipelines/utils.py
- test/test_retriever.py
- replace `should` operator of `multi_match` with `must` operator
**How to reproduce?**
- Run demo elasticsearch
- Hit postman with POST http://localhost:9200/document/_search and the following bodies
with `should`:
```json
{
"size": 10,
"query": {
"bool": {
"should": [
{"multi_match": {"query": "test", "type": "most_fields", "fields": ["content"]}}
],
"filter": {"term": {"content_type": "text"}}
}
}
}
```
returns
```json
...
"total": {
"value": 3827,
"relation": "eq"
},
...
```
with `must`:
```json
{
"size": 10,
"query": {
"bool": {
"must": [
{"multi_match": {"query": "test", "type": "most_fields", "fields": ["content"]}}
],
"filter": {"term": {"content_type": "text"}}
}
}
}
```
returns
```json
...
"total": {
"value": 66,
"relation": "eq"
},
...
```
**Status (please …
> Fix sparse retrieval with filters returns results without any text-match

- docs/_src/api/api/document_store.md
- docs/_src/api/api/retriever.md
- haystack/document_stores/base.py
- haystack/document_stores/deepsetcloud.py
- haystack/document_stores/elasticsearch.py
- haystack/json-schemas/haystack-pipeline-1.2.1rc0.schema.json
- haystack/json-schemas/haystack-pipeline-unstable.schema.json
- haystack/nodes/retriever/sparse.py
- haystack/utils/deepsetcloud.py
- test/test_document_store.py
- test/test_retriever.py
Currently we only support disjunctive queries in sparse retrieval. I.e. only one query term needs to be present in a document in order to be retrieved. This is a highly recall-favouring approach. In some use-cases (e.g. document retrieval) a more precision-focused approach might be better, however. Conjunctive queries ensure that all query terms must be present in a document in order to be retrieved. Within elasticsearch/OpenSearch this could easily be achieved by setting the `operator` param of the `match` clause to `AND`.
- add `all_terms_must_match` to `ElasticsearchRetriever`'s `query()` method
- set `operator` of match clause in elasticsearch and OpenSearch queries according to `all_terms_must_match`
- delegate `all_terms_must_match` to …
> Support conjunctive queries in sparse retrieval

- haystack/nodes/reader/table.py
- test/test_table_reader.py
Previously, when passing tables to the `TableReader` that do not contain any rows, the `TableReader` was running into `IndexError: index -1 is out of bounds for axis 0 with size 0`. This PR fixes this bug by skipping tables that do not contain any rows.
CC @Timoeller
> Fix `TableReader` for tables without rows

- test/test_faiss_and_milvus.py
This fixes the CI randomly failing due to milvus imprecisions.
- increase all_close absolute tolerance for milvus
- use `np.testing.assert_allclose` to get better assertion infos
> CI: Fix all_close comparison for milvus

- CONTRIBUTING.md
In `CONTRIBUTING.md`, instructions on how to launch all docstores for the tests were still referring to Milvus 1.x This PR updates that line and adds a few comments to the script.
> Update launch script for Milvus from 1.x to 2.x

- .gitignore
- setup.cfg
- test/conftest.py
- test/test_faiss_and_milvus.py
Fixes HTTP 405 during CI
- use requests-cache for huggingface requests during CI
> Use cache for hf requests during CI

- docs/_src/api/api/reader.md
- haystack/json-schemas/haystack-pipeline-1.2.1rc0.schema.json
- haystack/json-schemas/haystack-pipeline-unstable.schema.json
- haystack/nodes/reader/farm.py
This PR adds a parameter to filter out predictions below a certain confidence threshold.
This enables a simple way to not return answers next to our no_ans_boost because the no_ans_boost also changes the confidence score of valid answers (undesirable).
Also we can configure the FARMReader for downstream apps, e.g. we do not need to aplly the filtering in a UI where we display the results.
**Tests**
Because the feature is so small and non-invasive, I looked at existing tests and could only find test_topk, which I don't want to extend with this feature.
**Interaction with other apps**
I am slightly unsure about returning an empty list when filtering out all answers and its effect on consuming apps. I see that in the API we have a [fallback …
> Add confidence filtering to FARMReader

- docker-compose.yml
Reduces number of REST API workers from 8 to 2 to reduce memory consumption of the REST API docker. This is in response to #2399
> Reduce num REST API workers to accommodate smaller machines

- .github/workflows/autoformat.yml
- .github/workflows/docker_build.yml
- .github/workflows/linux_ci.yml
- .github/workflows/windows_ci.yml
Job https://github.com/deepset-ai/haystack/runs/5968089344?check_suite_focus=true got stuck occupying all available workers for over 4 hours. To prevent this we set down the timeout of jobs to 45 minutes.
- set individual job timeouts to 45 minutes
> Set CI job timeout to 45 minutes

- haystack/nodes/retriever/_embedding_encoder.py
- The auth token for HF private models is not passed to the EmbeddingRetriever initialization.
- [ x] Final code
> Fix: Auth token not passed for EmbeddingRetriever

- haystack/pipelines/base.py
- call `reset_index()` before returning dataframe
> enforce same index values before and after saving/loading eval dataframes

- .github/workflows/linux_ci.yml
- docs/_src/tutorials/tutorials/11.md
Has become needed to be able to install tesseract dependencies.
> Add `apt update` in Linux CI

- setup.cfg
**Problem**:
Python `beir` package depends on `pytrec_eval`, which can't be easily installed on Windows. Given that the `beir` dep group is part of the `all` install, this can give trouble in some cases.
**Solution**
`beir` will selectively install only if the platform is not Windows.
> Exclude `beir` from Windows install

- tutorials/Tutorial8_Preprocessing.ipynb
- I added two lines to download xpdf for the mac version, so that the pdftotext converter can be used and preprocssed
- The additional code is 'commented out'
Thank you.
> Added macos version of xpdf in tutorial 8

- .github/workflows/linux_ci.yml
- docs/_src/api/openapi/openapi-1.3.1rc0.json
- docs/_src/api/openapi/openapi.json
- docs/_src/tutorials/tutorials/8.md
- tutorials/Tutorial8_Preprocessing.ipynb
A new release of `pdftotext` broke the CI. This PR fixes it.
> Update `pdftotext` link

- Dockerfile-GPU-minimal
We didn't set the info about the execution environment yet in the "minimal GPU" image but only in the regular GPU image.
> Add info about execution env to minimal GPU image

- Dockerfile
- Dockerfile-GPU
- Dockerfile-GPU-minimal
xpdf [released](http://www.xpdfreader.com/download.html) a new version on Apr 18th. As they only host the latest version of command line tools, our docker builds failed as the old tar was not available anymore. 
Upgraded it quickly to 4.0.4 but haven't verified if there were any breaking changes in their release. 
> Upgrade xpdf to 4.0.4

- docs/_src/api/api/reader.md
- docs/_src/api/openapi/openapi-1.3.1rc0.json
- docs/_src/api/openapi/openapi.json
- docs/_src/tutorials/tutorials/11.md
- haystack/modeling/evaluation/eval.py
- haystack/modeling/model/prediction_head.py
- haystack/nodes/reader/farm.py
- test/test_eval.py
- test/test_modeling_question_answering.py
- test/test_reader.py
- set `use_confidence_scores_for_ranking`'s default value to `True`
- introduce flag `use_no_answer_legacy_confidence` which enables the existing no_answer confidence definition
- set `use_no_answer_legacy_confidence`'s default value to `False` which uses the same no_answer confidence definition as `FARMReader` when aggregating results across multiple documents.
fixes https://github.com/deepset-ai/haystack/issues/2410
> Match answer sorting in `QuestionAnsweringHead` with `FARMReader`

- haystack/pipelines/base.py
`pipeline.run(debug=True)` was producing a `_debug` key in the output with the debug information, while `pipeline.run(params={"debug":True})` was not.
This PR restores the same functionality for the second way of asking for debug output.
Closes #2440
> Make sure that `debug=True` and `params={'debug': True}` behaves the same way

- .github/workflows/linux_ci.yml
- docs/_src/api/api/document_store.md
- haystack/document_stores/elasticsearch.py
- haystack/document_stores/faiss.py
- haystack/document_stores/memory.py
- haystack/document_stores/milvus2.py
- haystack/document_stores/pinecone.py
- haystack/document_stores/sql.py
- haystack/document_stores/weaviate.py
- haystack/json-schemas/haystack-pipeline-master.schema.json
- test/conftest.py
- test/test_document_store.py
- test/test_eval.py
- test/test_retriever.py
- test/test_weaviate.py
To reset the document store for tests `delete_index` is cleaner than `delete_documents` as the latter does not remove properties that have been selected at index creation time (e.g. field mapping, embedding dimensions, similarity spaces). Additionally fixture `document_store` implements index deletion on its own for Milvus and Pinecone.
This PR facilitates and standardizes index cleaning in tests. 
- use `delete_index` instead of `delete_documents` in tests
- properly implement `delete_index` for all document stores
- add `recreate_index` param to Pincone, Milvus and Weaviate
> Fix and use delete_index instead of delete_documents in tests

- haystack/pipelines/base.py
- rename param "dataset" to "evaluation_set" to be consistent in terminology when logging to mlflow
> Rename dataset to evaluation_set when logging to mlflow

- docs/_src/api/api/document_store.md
- haystack/document_stores/deepsetcloud.py
- haystack/utils/deepsetcloud.py
Updating a few doc strings of the DeepsetCloudDocumentStore
@tstadel not sure about the usage of "DEFAULT_API_ENDPOINT". Where is this one actually used? Does it make sense to update it to the actual endpoint now?
> Update docs of DeepsetCloudDocumentStore

- haystack/document_stores/graphdb.py
- haystack/nodes/file_converter/parsr.py
- fixes mypy CI job
Reason: beginning with types-requests==2.27.21 BufferedReader is not accepted within the `files` param dict for `requests.post` any more
> Ignore mypy issues regarding files param of requests.post

- haystack/document_stores/elasticsearch.py
- test/test_document_store.py
- Add the support for alias in elasticsearch. indices.get() method from elasticsearch python library doesn't return alias name as key, but return indexes grouped by the alias, so we have to loop over all keys to check that every indices are correct
> Add support for aliases in elasticsearch document store

- docs/_src/api/api/retriever.md
- haystack/nodes/retriever/dense.py
Using a SOTA sentence transformers model like all-mpnet-base-v2 on linearized tables seems to outperform our existing Tri-Encoder approach. This PR adds this functionality and makes it default for the EmbeddingRetriever.
> Linearize tables in EmbeddingRetriever

- docs/_src/api/api/retriever.md
- haystack/json-schemas/haystack-pipeline-master.schema.json
- haystack/nodes/__init__.py
- haystack/nodes/retriever/__init__.py
- haystack/nodes/retriever/sparse.py
- test/conftest.py
- test/test_retriever.py
Similar to the PR renaming the ElasticsearchRetriever, I suggest to rename the ElasticsearchFilterOnlyRetriever to FilterRetriever to better reflect its functionality
> Renaming the ElasticsearchFilterOnlyRetriever to FilterRetriever

- haystack/nodes/reader/farm.py
- fix Total_text_answer (was wrongly muliplied by 100)
- return the same output in `reader.eval_on_file()` as in `reader.eval()`
> Fix reader.eval() and reader.eval_on_file() output

- haystack/nodes/base.py
- test/test_pipeline.py
- support positional args in pipeline.config() (and thus YAML creation)
```python
reader = FARMReader("my-model") # no model_name_or_path="my-model" required anymore
...
pipeline.add_node(name="reader", component=reader, inputs=["retriever"])
pipeline.save_to_yaml(...)
```
> Add support for positional args in pipeline.get_config()

- docs/_src/tutorials/tutorials/11.md
- docs/_src/tutorials/tutorials/14.md
- haystack/json-schemas/haystack-pipeline-master.schema.json
- tutorials/Tutorial11_Pipelines.ipynb
- tutorials/Tutorial11_Pipelines.py
- tutorials/Tutorial14_Query_Classifier.ipynb
- tutorials/Tutorial14_Query_Classifier.py
Quick fix for the variable names in the tutorials so that they are no longer 'es_retriever'
> changing the name of the retrievers from es_retriever to retriever

- docs/_src/api/api/reader.md
- haystack/json-schemas/haystack-pipeline-master.schema.json
- haystack/nodes/reader/transformers.py
- Set TransformersReader's default value for `return_no_answer` to False and for `top_k_per_candidate` to 3 to align it with the default values of FARMReader.
closes #2446 
> Align TransformersReader defaults with FARMReader

- docs/_src/api/api/document_store.md
- docs/_src/tutorials/tutorials/16.md
- haystack/document_stores/milvus1.py
This PR adds a warning message that the `Milvus1DocumentStore` is deprecated. 
In a future PR, when removing `Milvus1DocumentStore` ultimately, we need to make sure to remove everything related to Milvus1, including:
- installation dependencies
- tests
- documentation
Related to #2417
> Deprecate `Milvus1DocumentStore`

- docs/_src/api/api/document_store.md
- docs/_src/tutorials/tutorials/16.md
- haystack/document_stores/milvus2.py
- Change version number in links to milvus website from 2.0.0 to 2.0.x as the old links are not working anymore
**Old link**
**Updated link**
> change milvus links from 2.0.0 to 2.0.x

- .github/workflows/linux_ci.yml
- haystack/document_stores/elasticsearch.py
- test/test_document_store.py
> Fix `OpenSearchDocumentStore`'s `__init__`

- setup.cfg
- test/test_tokenization.py
This PR upgrades the `transformers` dependency from version 4.13.0 to 4.18.0. It seems that previous failing tokenizer tests with `RobertaTokenizer` pass now, probably due to [this PR](https://github.com/huggingface/transformers/pull/15429) which removes ineheritance of `GPT2Tokenizer` for `RobertaTokenizer`.
> Upgrade transformers version to 4.18.0

- docs/_src/api/api/primitives.md
- haystack/schema.py
Was going through the tutorial, then digging through the code and just noticed a small typo
- ...
> fix small typo in Document doc string

- docs/_src/api/api/other.md
- haystack/json-schemas/haystack-pipeline-master.schema.json
- haystack/nodes/other/join_answers.py
Add a sort argument to the initialization of JoinAnswers. This allows for joining of answers from a Generator and a Reader. Previously, this was not possible since the Generator returns a score of None. When they are sorted with the Answers coming from the Reader, this error was thrown:
```
TypeError: '<' not supported between instances of 'NoneType' and 'float'
```
Fixes #2435
> Add sort arg to JoinAnswers

- CONTRIBUTING.md
- README.md
In the README file, mention `brew install sentencepiece` that was needed when I set up Haystack on M1
For the CONTRIBUTING guidelines, contents were rearranged in a way that feels a bit more natural for a newcomer, in particular:
- I've added explicit mention to how we recommend setting up Haystack in a development environment with `pip install -e`
- The recommended way of running the tests comes first in the corresponding paragraph
- I've removed a few redundant sentences
Best way to review the contributing guidelines is to [look at the preview](https://github.com/deepset-ai/haystack/blob/massi/contributing/CONTRIBUTING.md) as the diff got a bit messy.
> rearrange contributing guidelines

- haystack/nodes/reader/transformers.py
The return format of transformers pipelines can vary in edge cases where a list of length 1 would be returned. By default, transformers flattens those lists which breaks our code. This PR checks for this and recreates the expected format.
> Handle transformers pipeline flattening lists of length 1

- tutorials/Tutorial5_Evaluation.ipynb
- tutorials/Tutorial5_Evaluation.py
-The change refers to the top_k value of the retriever in the Advanced Evaluation Metrics in the Tutorial5_Evaluation.py.
The actual value is set to 1 which is both suboptimal and inconsistent with all the previous utilized values of top_k for the retriever (equal to 5). Trying the script with other values leads to better SAS results. For example, setting it to 5 (to be consistent with the previous values) results in 0.528 compared to 0.443 using top_k = 1.
> set top_k to 5 in SAS to be consistent

- .github/workflows/docker_build.yml
The current GHA workflow that builds and pushes docker images is configured to add a tag with the haystack version to the images when there is a new release, but this version tag is never created.
- Add the missing trigger to the `docker_build` GHA workflow so it runs also when creating tags in the git repository, i.e. on a new version release.
- Replace the docker image tag based on the raw git tag for a rule handling semantic versions.
- Update versions of actions `docker/metadata-action` and `docker/build-push-action`.
> Fix docker image tag with semantic version for releases

- docs/_src/api/api/other.md
- docs/_src/tutorials/tutorials/5.md
- haystack/nodes/other/join_docs.py
As discussed in #2558, this PR improves the documentation of the `JoinDocuments` node regarding the score when a document is returned by multiple input nodes and concatenation is used.
- ...
> Documenting output score of JoinDocuments when using concatenation

- docs/_src/tutorials/tutorials/5.md
- setup.cfg
**Problem**:
- Ray 1.12.0 has a bug that prevents it from working properly on Windows (https://github.com/ray-project/ray/issues/24169)
**Solution**
- Conditionally avoid version 1.12.0 if the Haystack is being installed on Windows (should not affect Linux or MacOS installations).
> [CI refactoring] Avoid `ray==1.12.0` on Windows

- docs/_src/api/api/retriever.md
- docs/_src/tutorials/tutorials/5.md
- haystack/json-schemas/haystack-pipeline-master.schema.json
- haystack/nodes/retriever/dense.py
The `TableTextRetriever` already concatenates the meta data and the content when computing embeddings. This PR adds this functionality to the `EmbeddingRetriever`.
> Include meta data when computing embeddings in EmbeddingRetriever

- .github/workflows/demo.yaml
This PR changes the instance type of the public Haystack demo from p3.2xlarge to g4dn.2xlarge.
g4dn.2xlarge has 1 GPU, 8 vCPUs, 32 GiB of memory
p3.2xlarge had 1 GPU, 8 vCPUs, 61 GiB of memory
which results in 75% lower costs with g4dn.2xlarge.
I also tried out the even smaller g4dn.xlarge, which has 1 GPU, 4 vCPUs, 16 GiB of memory. However, the memory was not enough to run the demo. I tried out multiple requests at the same time and it worked well with g4dn.2xlarge. Requests are slightly slower as with the more powerful instance type but it's hard to notice.
> Smaller demo instance type

- ui/setup.py
- ui/webapp.py
This PR fixes a bug that let the "Random question" button in the public Haystack demo fail every time as reported in #2563 
**Proposed changes:**
- Change scriptrunner module path in streamlit ui according to the changes made in streamlit: 
- https://github.com/streamlit/streamlit/pull/4503
- https://github.com/streamlit/streamlit/pull/4557
For reviewing, you can compare the currently deployed demo and a demo with the changes applied in a separate EC2 instance:
- without changes: https://haystack-demo.deepset.ai/
- with changes: http://ec2-54-74-125-170.eu-west-1.compute.amazonaws.com:8501/
closes #2563 
> Update scriptrunner module path for streamlit ui

- haystack/document_stores/weaviate.py
- test/document_stores/test_weaviate.py
fixes #2517 
When a query returns less documents than available in the store (e.g. when there are more documents than `QUERY_MAXIMUM_RESULTS` (see [Weaviate docs](https://weaviate.io/developers/weaviate/current/graphql-references/filters.html#offset-argument-pagination)), the `while` loop paginating the results never exits. This is because the offset increases as we fetch more documents, but after `QUERY_MAXIMUM_RESULTS` docs, the query starts returning an empty list, the offset stays the same and we get stuck.
- While paginating results, we exit the loop if the query returns an empty list of documents.
> [Weaviate] Exit the while loop when we query less documents than available

- docs/_src/api/api/pipelines.md
- haystack/pipelines/base.py
- haystack/utils/deepsetcloud.py
- test/pipelines/test_pipeline.py
- show search endpoint after deployment
- show curl try out message after deployment
- add flag to omit curl message
Success output will be:
```
INFO - haystack.utils.deepsetcloud -  Pipeline config 'test_qa_pipeline_2' successfully deployed.
INFO - haystack.utils.deepsetcloud -  Search endpoint for pipeline config 'test_qa_pipeline_2' is up and running for you under https://api.test.cloud.deepset.ai/api/v1/workspaces/default/pipelines/test_qa_pipeline_2/search
INFO - haystack.utils.deepsetcloud -  Try it out using the following curl command:
curl -X 'POST' \
'https://api.test.cloud.deepset.ai/api/v1/workspaces/default/pipelines/test_qa_pipeline_2/search' \
-H 'accept: application/json' \
-H 'Authorization: Bearer <INSERT_TOKEN_HERE>' \
-H 'Content-Type: …
```
> Show search endpoint after deepset Cloud deployment

- docs/_src/api/api/retriever.md
- haystack/nodes/retriever/dense.py
Saving checkpoints while training a DPR model with `retriever.train` is currently not supported. However, that feature was added for reader.train in #1554 
This PR applies the same changes to `retriever.train` and to this end replaces `Trainer(...)` in `retriever.train()`  `create_or_load_checkpoint()`. This facilitates the saving of the model after certain steps and resuming training from the saved checkpoint.
> Add training checkpoint in retriever trainer

- haystack/pipelines/config.py
- test/pipelines/test_pipeline.py
Closes #2568 
**Problem**:
- `get_component_definitions` used to `deepcopy` the content of `_component_config` to convert it into the proper format and apply env vars. However, some objects contained in that dict are not supposed to be copied: for example the `aws4auth` param of Opensearch, which would trigger a `TypeError` as soon as the method tried to copy the SSL context .
**Solution**:
- The method could be slightly rewritten to avoid that `deepcopy` operation. 
- A test has been added.
> Do not copy `_component_config` in `get_components_definitions`

- haystack/nodes/connector/crawler.py
When trying to crawl for example sub-pages of the following page (`https://taz.de/!s=&OnlineRessort=5097/?search_page=0`), we get the following error:
```
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
```
This PR makes sure that we only try to crawl elements where the `href` attribute is available.
> Fix `StaleElementReferenceException` in Crawler

- haystack/pipelines/base.py
- do not set `api_endpoint` and `api_key` if they are `None`
closes https://github.com/deepset-ai/haystack/issues/2586
> Avoid empty `api_endpoint` in `load_from_deepset_cloud`

- docs/_src/api/api/question_generator.md
- docs/_src/api/api/retriever.md
- haystack/__init__.py
- haystack/json-schemas/haystack-pipeline-1.1.0.schema.json
- haystack/json-schemas/haystack-pipeline-1.3.0.schema.json
- haystack/json-schemas/haystack-pipeline-master.schema.json
- haystack/nodes/__init__.py
- haystack/nodes/label_generator/__init__.py
- haystack/nodes/label_generator/pseudo_label_generator.py
- haystack/nodes/question_generator/question_generator.py
- haystack/nodes/retriever/_embedding_encoder.py
- haystack/nodes/retriever/dense.py
- test/conftest.py
- test/nodes/test_label_generator.py
Adds [GPL](https://github.com/UKPLab/gpl) support to Haystack's EmbeddingRetriever (SentenceTransformer variant). 
**Motivation**:
Dense retrievers don't work well for out-of-domain data (data it hasn't seen during the pre-training or fine-tuning stage). To adapt the retriever to new data, we use [Generative Pseudo Labeling (GPL)](https://arxiv.org/abs/2112.07577), an efficient approach to adapt existing dense retrieval models to new domains & data.
**Proposal**:
PR, in its current form, seeks some early feedback about the general design and the approach to implementing GPL.  It currently implements GPL adaptation of Haystack's EmbeddingRetriever (SentenceTransformer variant). DPR retriever implementation is planned as well once the current approach is approved by …
> Add Generative Pseudo Labeling (GPL)

- test/nodes/test_connector.py
**Problem**
- For some reason, Crawler tests started failing on CI after the merge on master due to the instability of the ordering of crawled pages.
**Solution**:
- Make tests insensitive to ordering of crawled pages.
> Fix failing `Crawler` test

- haystack/utils/deepsetcloud.py
- test/others/test_utils.py
Currently success message is show even if evalset upload failed (together with the error). This PR fixes this
- show success message only if upload was successful
> Do not show success message on failed evalset upload

- .github/workflows/tests.yml
**Problem**:
- Currently when a PR is in draft, only a subset of the tests is run. Once is converted to ready for review, the whole tree is supposed to run, but the workflow will only trigger as soon as another commit is pushed.
**Solution**
- Make "Ready for review" an event that triggers the tests workflow, so that all PRs ready for review have at least one full run of the tests workflow.
> Make 'ready for review' an event that triggers the tests workflow

- test/nodes/test_label_generator.py
- Some GPL tests use the old `slow` marker instead of the new `integration` one, which causes pytest to fail.
- This PR fixes the affected markers
> Replace `slow` markers with `integration` in GPL tests

- annotation_tool/docker-compose.yml
Fixes https://github.com/deepset-ai/haystack/issues/2356
- Wait for postgres for being ready before starting the database migration
- Let docker compose manage the name of the containers to avoid clashes with common names
> wait for postgres to be ready before data migrations

- .github/workflows/tutorials_nightly.yml
- Now the nightly job for tutorials on CI runs on every PR by mistake. This PR removes the extra trigger.
> Remove `pull_request` from triggers of `Tutorials (nightly)`

- .github/utils/code_and_docs.sh
- .github/utils/convert_notebooks_into_webpages.py
- .github/workflows/autoformat.yml
- docs/_src/tutorials/tutorials/1.md
- docs/_src/tutorials/tutorials/10.md
- docs/_src/tutorials/tutorials/11.md
- docs/_src/tutorials/tutorials/14.md
- docs/_src/tutorials/tutorials/15.md
- docs/_src/tutorials/tutorials/17.md
- docs/_src/tutorials/tutorials/5.md
- A typo in `code_and_docs.sh` was preventing the tutorial conversion task to run. This PR fixes the typo
- `ffmpeg` should be installed in `autoformat.yml` to prevent a `libsndfile` warning (introduced with the audio nodes PR)
> Fix typo in `code_and_docs.sh`

- docs/_src/api/api/document_store.md
- haystack/document_stores/elasticsearch.py
Related issue: https://github.com/deepset-ai/haystack/issues/1764
- Create a new base class, `ElasticsearchCommon` implementing the code that Elasticsearch and Opensearch have in common at this moment
- There should be no functional change, with `ElasticsearchDocumentStore` implementing the same type as before
```
┌───────────────────────────┐                     
│                           │                     
│   KeywordDocumentStore    │                     
│                           │                     
│                           │                     
└───────────────────────────┘                     
▲                                   
│                                   
│                                   
┌───────────────────────────┐ …
```
> Extract common code for ES and OS into a base class

- docs/_src/tutorials/tutorials/4.md
- tutorials/Tutorial4_FAQ_style_QA.ipynb
- tutorials/Tutorial4_FAQ_style_QA.py
In Tutorial 4 we are initializing the DocumentStore without setting the `similarity` parameter. Therefore, the default value `"dot_product"` is used. However, as we are using a sentence-transformers model, we should use `"cosine"` similarity instead. This PR fixes this by explicitly setting `similarity="cosine"` when initializing the `ElasticsearchDocumentStore`.
(We are already doing this in the `.py` version of the tutorial.)
> Tutorial 4: Set similarity to `"cosine"` in DocStore initialization

- haystack/nodes/other/join.py
- haystack/utils/deepsetcloud.py
- test/document_stores/test_document_store.py
- fixes getting labels from deepset Cloud (needs name instead of id as path param)
> Fix EvaluationSetCliet.get_labels()

- .github/pull_request_template.md
**Problem**:
- In external PRs, contributor's seems to often be confused about which checkboxes to tick. In some cases they ignore the list, in others they go ahead and check boxes that we assume were dedicated to reviewers. This makes the checklist itself less effective.
**Solution**:
- I believe splitting the checklist into Contributor's and Reviewer's can bring more clarity and ease the reviewer's job.
- Some checkboxes seemed outdated and therefore removed (the first draft vs final code: now PRs can be marked as Draft, by the reviewers as well if necessary)
- Some checkboxes were added for the reviewers (the labels review)
**Contributor's Checklist**:
**Reviewer's Checklist**:
> Update contributor's checklists in PR template

- setup.cfg
Reverts deepset-ai/haystack#2694
The latest transformers 4.20.0 seems to be incompatible with espnet, which we use in the audio nodes. It seems that the import of `snapshot_download` would need to be changed within espnet. The following warning is triggered when running our tests:
```huggingface_hub/snapshot_download.py:11: FutureWarning: snapshot_download.py has been made private and will no longer be available from version 0.11. Please use `from huggingface_hub import snapshot_download` to import the only public function in this module. Other members of the file may be changed without a deprecation notice.```
And the audio tests are failing with:
```
test/nodes/test_audio.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
> Revert "Upgrade transformers to 4.20.0"

- haystack/utils/context_matching.py
- setup.cfg
- test/others/test_utils.py
**Related Issue(s)**:  ...
- fix failing test_utils.py tests noted in https://github.com/deepset-ai/haystack/pull/2718
- properly join the multiprocessing pool after closing it
- change the match_contexts test using multiprocessing to finish in a more reasonable time (joining multiprocessing tools takes a good amount of time overhead)
- pin rapidfuzz to version 2.0.13 as 2.0.14 produces different results than before (see https://github.com/maxbachmann/RapidFuzz/issues/231)
> Fix match_context tests in test_utils.py

- .github/actions/python_cache/action.yml
- haystack/nodes/base.py
**Related Issue(s)**:  no issue, addressing failing tests on `master`
- Stop relying on `.endswith` to determine if the instance is a leaf of the hierarchy tree. That check would mistakenly consider `BaseElasticsearchDocumentstore.__init__` be the same as `ElasticsearchDocumentstore.__init__`. We now manipulate and compare the actual tokens composing the fully qualified name of a `__init__` method.
- Do not store constructor's parameters for the ancestors of a node instance we want to save/load. This was supposed to fail but thanks to the bug from the point above continued working
- Remove the function `_get_signature` that was used to recursively collect all the params for all the constructors calls chain, the code isn't used anymore.
> Fix bugs in loading code from yaml

- .github/actions/python_cache/action.yml
- Some repeated code was extracted from `linux_ci.yml` into the `python_cache` action during the CI refactoring.
- `actions/checkout@v2` used to run on a specific PR, but once factored out, started running on master instead
- Given that the cache key is computed over the setup files, from that point on the cache was missing only on changes of setup files  on master
- The tests CI re-installs Haystack actually, but with a different extra, so some dependencies would come from the master's list, and some other from the partial installation, causing several errors to go unnoticed or becoming sticky on unrelated PRs
> Speficy `ref` in `python_cache` action

- haystack/document_stores/base.py
**Related Issue(s)**:  #1749
- In order to specify a correct log message, pass the index argument from `_handle_duplicate_documents` further on to `_drop_duplicate_documents` and change the logging there.
@ZanSara please give it a look.
> fix error in log message

- setup.cfg
**Related Issue(s)**:  fixes https://github.com/deepset-ai/haystack/issues/2628
- Pin es client so to include bugfixes for the 7.10 release line
> Pin es client to include bugfixes

- .github/actions/python_cache/action.yml
- .github/workflows/autoformat.yml
- .github/workflows/tests.yml
- .github/workflows/tutorials.yml
- .github/workflows/tutorials_nightly.yml
- setup.cfg
- Testing torch 1.12 upgrade
- Before merging, change torch dependency to `torch>1.9,<1.13`
Failing tests currently are about table reader and torch-scatter
```
if not torch_scatter_installed:
raise ImportError(
"Please install torch_scatter to use TableReader. You can follow the instructions here: https://github.com/rusty1s/pytorch_scatter"
)
if torch_scatter_wrong_version:
raise ImportError(
>               "torch_scatter could not be loaded. This could be caused by a mismatch between your cuda version and the one used by torch_scatter."
"Please try to reinstall torch-scatter. You can follow the instructions here: https://github.com/rusty1s/pytorch_scatter"
)
E           ImportError: torch_scatter could not be loaded. This could be caused by a mismatch between your …
```
> Upgrade torch to 1.12

- docs/_src/api/api/document_store.md
- haystack/document_stores/faiss.py
- haystack/document_stores/pinecone.py
- haystack/json-schemas/haystack-pipeline-master.schema.json
- The `_validate_index_sync()` method in FAISS and Pinecone hinders users from initializing a document store that already contains some documents but no embeddings yet. This situation can happen though if a large number of documents is written to the document store in multiple separate sessions and only after all documents are written, the `update_embeddings` step is called. This PR makes running the validation optional by adding a parameter to the document store's `init` method that allows choosing whether to run it or not. Default is `True`.
- Pinecone has a `_validate_index_sync()` but it was never called. This PR calls it as the final step of the document store's init `method`
> Make check of document & embedding count optional in FAISS and Pinecone

- .github/workflows/tutorials.yml
- docs/_src/tutorials/tutorials/18.md
- tutorials/Tutorial18_GPL.ipynb
**Related Issue(s)**:  https://github.com/deepset-ai/haystack/pull/2632, tutorial update
-Adds Colab GPU setup header and "open in colab" button to GPL tutorial
> GPL tutorial - add GPU header and open in colab button

- haystack/modeling/model/tokenization.py
- haystack/nodes/retriever/dense.py
- test/nodes/test_retriever.py
**Related Issue(s)**: #2711 
This PR resets the default tokenizer class for DPR from `AutoTokenizer` to `DPRQuestionEncoderTokenizer` and `DPRContextEncoderTokenizer`, respectively. This is needed, as for example the spanish DPR model [`IIC/dpr-spanish-passage_encoder-allqa-base`](https://huggingface.co/IIC/dpr-spanish-passage_encoder-allqa-base) sets the `tokenizer_class` to `"DPRContextEncoderTokenizer"`, but this can't be loaded using the `AutoTokenizer`. It is missing in transformers [`TOKENIZER_MAPPING_NAMES`](https://github.com/huggingface/transformers/blob/6cb19540c9a5288195445e8355646c06605a64fc/src/transformers/models/auto/tokenization_auto.py#L47), resulting in the error: 
`Tokenizer class DPRContextEncoderTokenizer does not exist or is not currently …
> Fix loading of tokenizers in DPR

- .github/workflows/tests.yml
- .github/workflows/tutorials.yml
- .github/workflows/tutorials_nightly.yml
- CONTRIBUTING.md
**Related Issue(s)**:
Randomly we get something like this error during CI, which means elasticsearch has not enough memory to process the request:
```
elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [129818900/123.8mb], which is larger than the limit of [127506841/121.5mb], real usage: [129818624/123.8mb], new bytes reserved: [276/276b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=276/276b, model_inference=0/0b, accounting=8356/8.1kb]')
```
- double max heap size of elasticsearch instances (from 128mb to 256mb)
> Double max heap size for elasticsearch in CI

- docs/_src/tutorials/tutorials/18.md
- tutorials/Tutorial18_GPL.ipynb
It seems that the "Open in Colab" button doesn't work in the Firefox browser because there is no new line break between the title of the section and the link. I am not 100% sure about this claim but that's the only difference I can find between Tutorial 18 and others - where the "Open in Colab" button works in Firefox. @agnieszka-m not sure how we can test this hypothesis before merging. LMK.
> Tutorial 18:Open in Colab doesn't work in Firefox

- haystack/pipelines/base.py
- test/pipelines/test_pipeline_debug_and_validation.py
- copy and merge `_debug` info of previous nodes when handling join nodes
**Additional context**:
This leads to losing eval data on the previous nodes during pipeline.eval().
/cc @wochinge @erendabanlioglu
> Fix _debug info getting lost for previous nodes when using join nodes

- haystack/pipelines/base.py
**Related Issue(s)**: 
Fixes the broken tests of PR #2776
- look if `_debug` is actual there before merging it
> fix pipeline run loop on joined pipelines whithout debug flag

- docs/_src/tutorials/tutorials/11.md
- tutorials/Tutorial11_Pipelines.ipynb
**Related Issue(s)**:  https://github.com/deepset-ai/haystack-website/pull/348
**Proposed changes**: Update the example
- ...
> Fix load_from_yaml example in the Pipelines tutorial

- docs/_src/api/api/document_store.md
- haystack/document_stores/memory.py
Documentation of write_documents mentioned the old dict key (and Document attribute) `text`. This PR replaces the two occurrences of `text` in the docstring with `content`.
> Change "text" to "content" as dict key

- rest_api/controller/search.py
- rest_api/test/test_rest_api.py
**Related Issue(s)**: fixes https://github.com/deepset-ai/haystack/issues/2656
The code processing requests to the `/search` endpoint assumes all the items in the `params` dictionary are also dictionaries, which is wrong. For example, users might want to pass `debug: True` to the endpoint.
- Ensure the item in `params` is a dictionary before accessing its keys.
> Allow values that are not dictionaries in the request params in the `/search` endpoint

- .github/workflows/tests.yml
**Related Issue(s)**:  https://github.com/deepset-ai/haystack/pull/2798 is unmergeable due to branch protection rules.
- Enable the `tests.yml` workflow on all PRs. Branch protection rules should then be re-evaluated for the corner cases in which tests are unnecessary.
- ~If this is a code change, I added tests or updated existing ones~
- ~If this is a code change, I updated the docstrings~
> Enable CI on tutorials

- haystack/errors.py
- haystack/nodes/answer_generator/openai.py
**Related Issue(s)**:  Closes #2787
- Before returning the result, we check that the response is valid.
Otherwise, we raise an Exception, such as the following:
> Exception: OpenAI returned an error. 
> Status code: 429
> Response body: {
>     "error": {
>         "message": "You exceeded your current quota, please check your plan and billing details.",
>         "type": "insufficient_quota",
>         "param": null,
>         "code": null
>     }
> }
> 
> ---
> Exception: OpenAI returned an error. 
> Status code: 401
> Response body: {
>     "error": {
>         "message": "Incorrect API key provided: s*******************************************y. You can find your API key at https://beta.openai.com.",
>         "type": "invalid_request_error",
>         "param": …
> Validate OpenAI response

- docs/_src/api/api/primitives.md
- haystack/schema.py
**Related Issue(s)**:
- fixes https://github.com/deepset-ai/haystack-private/issues/4
- quote all strings of the resulting csv from `EvaluationResult.save()`, so \r chars cannot corrupt the file
- pass through pandas csv serialization kwargs to `save()` and `load()` methods: csv serialization can be troublesome, it's almost impossible to foresee any issue, so let's better be flexible on that and provide the user any option there is to mitigate problems.
> Fix corrupted csv from `EvaluationResult.save()`

- .pre-commit-config.yaml
**Related Issue(s)**:  #2882 
- Remove the python version from the pre-commit-config
> Updating pre-commit-config to remove python version

- CONTRIBUTING.md
**Related Issue(s)**:  [#2870 (comment)](https://github.com/deepset-ai/haystack/pull/2870#issuecomment-1195709488)
- Following a recommendation from a contributor and earlier feedback from @masci, I propose to change `CONTRIBUTING.md` to recommend installing the pre-commit hooks on commit rather than on push.
- ~If this is a code change, I added tests or updated existing ones~
- ~If this is a code change, I updated the docstrings~
> Recommend installing pre-commit hook on commit

- setup.cfg
**Related Issue(s)**:   #2901
- Currently, when doing a **full haystack install** on a **Python 3.10** environment, an error is throw when installing the audio dependencies. 
- All this was caused by some dependency pinning **NumPy** to a version lower then [1.21.0](https://numpy.org/doc/stable/release/1.21.0-notes.html), which was the first to support Python 3.10. After some investigation, the problem was found to be on an _espnet dependency_, **pyworld**. After looking forward into the [pyworld source code](https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder/commits/v0.3.0) I noticed the latest version is mainly a formal commit, with minor changes. As so, I pinned **pyworld** to version **0.2.12** (the one just before 0.3.0, where NumPy was pinned and …
> Fix audio dependency chain issue on Python 3.10

- CONTRIBUTING.md
**Related Issue(s)**:  ...
None
- The CONTRIBUTING.md guidelines file has typos in the description of the Black code style configuration.
- [N/A] If this is a code change, I added tests or updated existing ones 
- [N/A] If this is a code change, I updated the docstrings
> Fix typos in Contributing.md

- .github/workflows/tests.yml
- docs/_src/api/api/document_store.md
- haystack/document_stores/opensearch.py
- pyproject.toml
- setup.cfg
- test/conftest.py
- test/document_stores/test_opensearch.py
Fixes: https://github.com/deepset-ai/haystack/issues/1764 https://github.com/deepset-ai/haystack/issues/2137 https://github.com/deepset-ai/haystack/issues/2802
- Use `opensearch-py` in `OpensearchDocumentStore` instead of the Elasticsearch client
- Cover the `OpensearchDocumentStore` logic with tests
- Change testing strategy for document stores to classes
The tests in this PR follow a new pattern that I'd like to introduce for document stores. Instead of having a complex matrix of fixtures, we use a class hierarchy so that `pytest` will repeat tests defined in the parent classes for every child. Example:
```
┌────────────────────────┐                         
│                        │                         
│TestKeywordDocumentStore│                         
│ …
```
> Use opensearch-py in OpenSearchDocumentStore

- haystack/document_stores/__init__.py
**Related Issue(s)**:  Fixes #2905
- Wrap opensearch imports into `safe_import` in `haystack/document_stores/__init__.py`
> Wrap opensearch imports into `safe_import`

- haystack/modeling/training/base.py
- haystack/nodes/retriever/dense.py
**Related Issue(s)**:  
- Fixes #2885 
- Fixes #2881
In the model forward call, rather than passing kwargs, we explicitly specify all parameters. Similarly, for AdaptiveModel's logits_to_loss function, we explicitly specify only the `labels` parameter rather than passing all parameters.
> Explicitly specify all parameters to forward call

- .pre-commit-config.yaml
- tutorials/Tutorial1_Basic_QA_Pipeline.ipynb
**Related Issue(s)**:  https://github.com/deepset-ai/haystack/pull/2910#issuecomment-1199199497
- Change the `black` pre-commit hook into `black-jupyter` to also check the Jupyter notebooks, as currently done by the CI
> Change `black` pre-commit hook into `black-jupyter`

- .github/workflows/black.yml
- .github/workflows/schemas.yml
- .pre-commit-config.yaml
**Related Issue(s)**: 
- https://github.com/deepset-ai/haystack/pull/2903#issuecomment-1199144894 
- https://github.com/deepset-ai/haystack/pull/2910#issuecomment-1199204754
- and other informal reports by @vblagoje 
- Remove `end-of-file-fixer`, `trailing-whitespace` and `pretty-format-json` from the hook's checks.
- `end-of-file-fixer`, `trailing-whitespace` seems to conflict with the API generation
- `pretty-format-json` conflicts with the JSON schema generation
- Both needs further investigation, but for usability issues they should be temporarily disabled in master.
> Disable a few checks in the pre-commit hook

- haystack/document_stores/weaviate.py
- test/document_stores/test_weaviate.py
If no filters param is passed in, then the original code retrieves *all* documents before then deleting by their IDs. There's no need for that, since we can delete by their IDs directly.
**Related Issue(s)**:  Closes #2898
Fix the ability to delete documents within a large Weaviate document store, as described in the issue.
> Bug fix Weaviate document deletion

- Dockerfile-GPU
**Related Issue(s)**:  [failed build](https://github.com/deepset-ai/haystack/runs/7648211441?check_suite_focus=true)
The existing `nvidia/cuda:11.1-runtime-ubuntu20.04` isn't available anymore on Dockerhub and the build is failing. `1.11.1` was published 2 months ago, most likely the `11.1` was recently removed.
- Use `nvidia/cuda:11.1.1-runtime-ubuntu20.04` instead (this will also pick up the latest bugfix release)
> fix docker tag for cuda

- docs/_src/api/api/pipelines.md
- haystack/pipelines/ray.py
- test/pipelines/test_ray.py
Fixes #2944
Ability to run Ray Serve detached - to allow running multiple instances of the app (HA).
See https://docs.ray.io/en/latest/serve/package-ref.html#core-apis
**Related Issue(s)**:  #2944 
- Adding a new arg to the Ray Serve pipeline - allowing Ray Serve to run in `detached` mode, which also allows you to run multiple instances of the application all connecting to the same detached Ray Serve instance.
- This will allow running the Haystack application in HA mode (eg more than one instances) while using the same Ray Serve for model serving, by allowing the same Ray Serve instance being used by multiple instances of the same Haystack app.
- The original functionality (`detached` mode is off) has been kept
- [ x ]  I have read the [contributors …
> Ability to run Ray Serve detached

- .github/workflows/tests.yml
- pyproject.toml
- test/document_stores/test_opensearch.py
- test/nodes/test_audio.py
**Related Issue(s)**:  
- fixes https://github.com/deepset-ai/haystack/issues/2943
- related to #2811 
- Add a new marker `unit` to explicitly mark tests that are intended to be as such according to the criteria in https://github.com/deepset-ai/haystack/issues/2811
- Create a new `Unit` job to run tests marked as `unit` on Linux, Windows and macOS
- Avoid to fail tests collection when the audio setup isn't complete
> Enable Opensearch unit tests in Windows CI

- CONTRIBUTING.md
**Related Issue(s)**:  
Proper schema generation requires  '.[all]' install. Update contributing guide with this clarification.
- update CONTRIBUTING.md
> Update contributing guide, clarify when '.[all]' install is needed

- docs/_src/api/api/ranker.md
- haystack/nodes/ranker/sentence_transformers.py
**Related Issue(s)**:  Fixes #2683 
- Add `python` code syntax to format it as the code snippet
> Fix docs code format for sentence transformers

- haystack/modeling/training/base.py
**Related Issue(s)**:  None
- Using `.lower()` when running this check `self.model.language_model.name.lower() != "debertav2"` because the name can be capitalized (e.g. `DebertaV2`)
> Better check for "DebertaV2" architecture in Trainer.train

- docs/_src/api/api/pipelines.md
- docs/_src/api/api/primitives.md
- haystack/pipelines/base.py
- haystack/pipelines/standard_pipelines.py
- haystack/pipelines/utils.py
- haystack/schema.py
**Related Issue(s)**:  Fixes https://github.com/deepset-ai/haystack/issues/2615
1.  Add wrong_examples_filter parameter to print_eval_report    
- include only certain fields of document/answer listed in wrong examples report
- allows users to print out wrong examples report but only with certain fields
2.  Add max_characters_per_wrong_examples_report parameter to print_eval_report
- include up to max_characters_per_wrong_examples_report in each wrong examples report
- effectively cuts the length of each report to max_characters_per_wrong_examples_report
4.  Add thresholds to print_eval_report
- introduces float threshold value for answer/document metric below which predictions are never shown as wrong examples
> Print eval reports improvements

- haystack/modeling/training/base.py
**Related Issue(s)**:  None
- Removed variable from function call because the variable can no longer be accepted. 
Code snippet for `AdaptiveModel.load` does not take `lm_name`
https://github.com/deepset-ai/haystack/blob/762a12fcb163f80a302c544f791f44d06efbe468/haystack/modeling/model/adaptive_model.py#L260-L266
> Remove unused variable

- docs/_src/api/api/generator.md
- haystack/nodes/answer_generator/transformers.py
**Related Issue(s)**:  #2939 
It fixes the documentation (it was wrong), clarifies which models can be used in Seq2SeqGenerator, and points the user to the HF hub where he/she can select models.
> Update Seq2SeqGenerator API documentation

- .github/utils/pydoc-markdown.py
- .pre-commit-config.yaml
- No issue, just the pre-commit hook was too slow
Instead of building all the docs at every commit to ensure docs were updated, this pre-hook script will only try to build the API docs corresponding to the files actually changed, and skip the build altogether if the changed files aren't relevant for a documentation change.
Just check out my branch, try changing a documented API and run `pre-commit` or try to actual make the commit.
This check makes several assumptions:
- The source of truth about whether or not we should build docs is the `search_path` field inside the pydoc config files
- For each pydoc config file, there is always one and only one entry in the `search_path` array
> Add enhanced pydoc-markdown pre-hook

- haystack/document_stores/elasticsearch.py
- haystack/schema.py
- related to #2989 (not sufficient to fix it, the bug affects all docstores).
- Add a warning into `ElasticsearchDocumentStore` in case of validation errors with the data extracted from the ES index.
- Includes a small change in the `str` method of `Label` and `MultiLabel` that was extremely useful in debugging. Can remove if it's too out-of-scope for the PR.
- The docstore behavior is unchanged and we usually don't test warnings. Tests will be added on request of the reviewer.
N / A
> feat: warn users if they're calling `get_all_labels` on a document index and vice-versa (Elasticsearch & Opensearch only)

- .github/workflows/tests.yml
Adds Slack notification when master fails
Sends a slack message whenever master fails using marketplace [Slack action](https://github.com/marketplace/actions/slack-github-actions-slack-integration)
I pushed on my haystack fork and caused a message trigger.
Requires adding our [webhook URL](https://github.com/marketplace/actions/slack-github-actions-slack-integration#slack_webhook_url-required) as a secret
> Send notifications on Slack when master build fails

- test/document_stores/test_document_store.py
- fixes #3010 
Use `labels` variable in `test_labels` relies on labels being returned from the doc store in a specific order.
Manual verification
`test/document_stores/test_document_store.py`
> switch label variables in test_labels

- test/document_stores/test_document_store.py
- fixes #3010 but for `test_multilabels`
* In #3010 noted that order of returned labels should not be important but is tested; this is fixed by #3011 (we could merge these two PRs if preferred, but #3011 has already been approved hence this PR)
* After continuing tests, I found the same issue in `test_multilabel`:
```python
document_store.write_labels(labels)
list_labels = document_store.get_all_labels()
assert list_labels == labels
```
Tests for the order of `list_labels`, changing both to `set` objects fixes the issue:
```python
document_store.write_labels(labels)
list_labels = document_store.get_all_labels()
assert set(list_labels) == set(labels)
```
I've checked the remaining label tests and cannot see any further issues like this
Manual tests with #2749 …
> Testing order in `test_multilabel`

- haystack/pipelines/base.py
- fixes #2985 
As explained in #2985, I simply moved `flattened_documents` definition
Manual test using the code proposed by @ZanSara in #2985.
Now `UnboundLocalError` is not raised anymore.
> bug: fix `UnboundLocalError` in `Pipeline.run_batch()` 

- docs/_src/api/api/ranker.md
- haystack/nodes/ranker/sentence_transformers.py
- fixes wrongly formatted code on https://haystack.deepset.ai/reference/ranker#sentencetransformersranker
Revert the `|` removal change, it turned out to be necessary to render the code on docs.
> revert Remove pipes

- setup.cfg
- fixes  #3012
- Move the `azure-core<1.23` pin from the core dependency list into `dev` with `pydoc-markdown`, to allow Bazel to properly freeze Haystack dependencies on non-development installations.
Manual testing by the affected contributor.
Wait for @tanertopal to confirm the fix works for them.
> fix: move `azure-core` pin into the dev dependency list

- .github/workflows/tests.yml
- fixes #3024
This PR increases the disk limit for Weaviate in the CI from the default 90% to 95%. Furthermore, it adds the [`gh-docker-logs`](https://github.com/jwalton/gh-docker-logs) action which will provide the Docker logs in cases where the CI fails.
> ci: Increase Weaviate's disk usage + print docker logs

- haystack/document_stores/opensearch.py
- test/document_stores/test_opensearch.py
- fixes #2816
- set `embeddings_field_supports_similarity=True` when creating index
- refactored duplicate code (probably caused by bad merge)
- fix when `method` is missing from the field mapping, `embeddings_field_supports_similarity` is always `False` (also probably caused by bad merge)
- reused existing tests rather than writing new ones
> Fix `embeddings_field_supports_similarity` of `OpenSearchDocumentStore` when creating index

- haystack/nodes/answer_generator/base.py
- fixes #3035 
Making the `BaseGenerator` 's run method more similar to the one from `BaseReader` by
- adding a param `add_isolated_node_eval` 
- in case the mode is active, taking the same approach as in BaseReader [here](https://github.com/deepset-ai/haystack/blob/da7836a9316d5b0369e955f0d226b1ad1f0b35c7/haystack/nodes/reader/base.py#L94). The only difference here is that we are not adding the meta data of documents, as the answers are not extracted from any direct docs but are generated. So a direct link here seems impropropriate from my perspective  
- manual test by replacing the reader in our Tutorial 5 by: `reader = OpenAIAnswerGenerator(api_key="<api-key>")`
- Let me know if you also agree, that the metadata linking (as done in the BaseReader) doesn't make sense here for the …
> feat: Enable isolated node eval for answer generator nodes (incl. OpenAI Node)

- docs/_src/api/api/translator.md
- haystack/nodes/translator/base.py
- haystack/nodes/translator/transformers.py
- haystack/pipelines/standard_pipelines.py
- fixes #2976
This PR fixes makes `TranslationWrapperPipeline` work with `QuestionAnswerGenerationPipeline` by overwriting the `output_translator`'s `run` method with its `run_batch` method. This is needed as the `QuestionAnswerGenerationPipeline` overwrites the reader's `run` method with its `run_batch` method as well. The reader's `run_batch` output is not compatible with the translator's `run` method.
The bug came up in the last section of Tutorial 13. Therefore, I verified the fix by executing Tutorial 13.
> bug: Make `TranslationWrapperPipeline` work with `QuestionAnswerGenerationPipeline`

- docs/_src/api/api/primitives.md
- haystack/schema.py
- fixes https://github.com/deepset-ai/haystack/issues/2872
- add `kwargs` to `MultiLabel` __init__ to pass fully serialized MultiLabel
- parse Answer and Document dicts within `Label`'s __init__ to workaround pydantic validation issue
run following script
```python
from haystack import MultiLabel, Label
l = {
"id": "011079cf-c93f-49e6-83bb-42cd850dce12",
"query": "When was the final season first shown on TV?",
"document": {
"content": "\n\n\n\n\nThe eighth and final season of the fantasy drama television series ''Game of Thrones'', produced by HBO, premiered on April 14, 2019, and concluded on May 19, 2019. Unlike the first six seasons, which consisted of ten episodes each, and the seventh season, which consisted of seven episodes, the eighth season consists of only six episodes.\n\nThe …
```
> Fix broken `MultiLabel` serialization

- docs/_src/api/openapi/openapi-1.6.1rc0.json
- docs/_src/api/openapi/openapi.json
- rest_api/controller/document.py
While checking the alignment of Haystack/DC REST APIs I came across what seems to be a tiny copy-paste error in the API documentation.
> chore: fix typo in API docs

- .github/workflows/demo.yaml
- .github/workflows/docker_build.yml
- .github/workflows/tests.yml
- Follow up of #2600
Change the branch name in places where the default redirect offered by Github wouldn't work
Not tested
Unrelated but I pinned the version of the action used in the demo deployment
> Adjust workflows to the new branch name

- setup.cfg
- fixes #3046 
Pins pyworld to version `<=0.2.12` so that it does not pin numpy to `<1.20.0` in its [pyproject.toml](https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder/blob/2b64f86197573497c685c785c6e0e743f407b63e/pyproject.toml#L6)
I created a new python 3.9 environment and ran `GRPC_PYTHON_BUILD_SYSTEM_ZLIB=true pip install -e '.[audio]'` to check for a successful installation.
> fix: pin version of pyworld to `0.2.12`

- test/mocks/pinecone.py
- Part of #2646 
The previous part-Pinecone part-SQL PineconeDocumentStore used the SQL db for many filtering tasks. With the update to a pure-Pinecone document store in #2749 this is no longer the case.
That means that *during tests*, filtering in the new PineconeDocumentStore relies solely on the filtering in the Pinecone mock instance. Unfortunately, this didn't work for more complex filters. This PR includes a new filtering function to handle these more complex filters.
Another need stemming from the pure-Pinecone document store is the need to handle labels *without* SQL. Part of the implementation for this includes the use of Pinecone's `update` method, which was not originally included in the mock. It has been added here.
Manual verification, unit tests
N/A
> test: update filtering of Pinecone mock to imitate doc store

- haystack/utils/docker.py
- no issue
- Take in input the list of models to cache instead of hardcoding only one
- Do not target `/root` as the folder to keep nltk cached data, let `nltk` manage that
tested in a Docker build
Backward compatibility is preserved using a default param
> feat: take the list of models to cache instead of hardcoding one

- docs/_src/api/api/translator.md
- haystack/nodes/translator/transformers.py
- test/nodes/test_translator.py
- fixes #2896
When you use the TransformersTranslator node, and send a List of Documents, after translation the node correctly output the translated texts. But, it's also changing the input. So, we got **inputs == outputs** after using the node.
Get Translator node to work as all other nodes, and even as itself when related to query and not document. Output translated documents and keep inputs like they were sent.
Translator unit tests and two new tests to check that input is not equal to output
The main word for this change is decoupling. It's not a good software engineering decision, generally, to allow a method to output something and at the same time change the input to the same data, going backward on the chain. Specially when there is no documentation, a strong and unique rare case …
> fix(translator): write translated text to output documents, while keeping input untouched

- haystack/document_stores/elasticsearch.py
- haystack/document_stores/filter_utils.py
- test/document_stores/test_document_store.py
Rewrite of https://github.com/deepset-ai/haystack/pull/2675#issuecomment-1195487118
- fixes https://github.com/deepset-ai/haystack/issues/2672
> Will match a field that contains all values in the list, no more, no less. Order does not matter.
Unit test
> feat: Allow exact list matching with field in Elasticsearch filtering

- docs/_src/tutorials/tutorials/3.md
- tutorials/Tutorial3_Basic_QA_Pipeline_without_Elasticsearch.ipynb
- no related issue, if I have to open one I will (I didn't find anything about this in the PR doc)
I only fixed the key in the document dictionary format so `write_documents()` won't raise an error. By the way the `write_documents()` error is really explanatory. Tutorial updated: `Tutorial3_Basic_QA_Pipeline_without_Elasticsearch.ipynb`, as far as I understood no need to fix anything in the `.py` version
No real-test needed I think, but I went trough the notebook executing every cell and I spot this error adding my own documents: changing the dictionary format fixed it.
> docs:fixed typo (or old documentation) in ipynb tutorial 3

- docs/_src/api/api/crawler.md
- haystack/nodes/connector/crawler.py
- fixes #3066 
Today, Crawler will instantiate ChromeDriver, use it, and it will never close the window or the ChromeDriver itself. 
This change will close the browser window and quit the ChromeDriver instance during object destruction.
Tested on all connector node tests.
After hundreds of Crawler instances being created, there are hundreds of zombie processes left behind. This leads to huge wasted memory being consumed by unused processes.
> fix: Crawler quits ChromeDriver on destruction

- test/document_stores/test_opensearch.py
- fixes #3082 
This PR makes a small change to `TestOpenSearchDocumentStore` by creating `query_emb` using `np.random.random_sample` instead of `numpy.ndaray`. This makes sure that there are no `nan` values in `query_emb`.  
I let the tests for `OpenSearchDocumentStore` run.
> test: Use `random_sample` instead of `ndarray` for random array in `OpenSearchDocumentStore` test

- docs/_src/api/api/reader.md
- docs/_src/api/api/retriever.md
- docs/_src/api/api/utils.md
- docs/_src/api/pydoc/utils.yml
- haystack/modeling/training/__init__.py
- haystack/modeling/training/base.py
- haystack/nodes/reader/farm.py
- haystack/nodes/retriever/dense.py
- haystack/utils/__init__.py
- haystack/utils/early_stopping.py
No issue
Add option to specify Early Stopping in the Reader trainer. This feature is already present, I just exposed the option to the `FARMReader.train` method. 
I've run a Reader training using Early Stopping on AWS and it worked as expected.
> feat: Early stopping can be used in Reader and Retriever training

- haystack/utils/deepsetcloud.py
Add a tqdm progress bar to `upload_files()` so that users get an better idea of the progress and remaining time until their files are uploaded to deepset Cloud. 
Manual testing
Tiny change to have a standard progress bar
> feat: add progressbar to upload_files() for deepset Cloud client

- docs/_src/api/api/document_store.md
- haystack/document_stores/opensearch.py
- haystack/json-schemas/haystack-pipeline-master.schema.json
- test/document_stores/test_opensearch.py
- solves https://github.com/deepset-ai/haystack/issues/2911
> feat: FAISS in OpenSearch: Support HNSW for dot product and l2

- haystack/document_stores/opensearch.py
- test/document_stores/test_opensearch.py
- fixes #2912
This PR adds a check whether the `knn_engine` provided at initialization of `OpenSearchDocumentStore` is equal to the `knn_engine` when an already existing index was initially created. If this is the case, we will fall back to slow exact vector calculation. 
I added a test case for this.
> feat: FAISS in OpenSearch: check existing index

- haystack/pipelines/config.py
- test/pipelines/test_pipeline.py
- fixes #3064
Add `custom_mapping` to the list of fields that accept JSON input.
Add a line into an existing unit test
> bug: `OpensearchDocumentStore.custom_mapping` should accept JSON strings at validation

- pyproject.toml
Upgrades and pins transformers to 4.21.2
The most important change for us allowing "mps" devices in [pipelines](https://github.com/huggingface/transformers/pull/18494)
After upgrading and pinning to 4.21.2, we can complete https://github.com/deepset-ai/haystack/pull/3062
We'll check whether any tests fail, for example, due to deprecated/discontinued features or breaking changes. We'll also comb through the changelog and check for any changes that might affect Haystack.
> chore: Upgrade and pin transformers to 4.21.2

- ui/setup.py
- ui/webapp.py
- fixes #3105
- Check if `streamlit` has `scriptrunner` attribute --> `streamlit`<1.12.0 --> old behavior is ok.
Otherwise --> `streamlit`>=1.12.0 --> use the new `runtime` attribute.
- I also pinned `streamlit`>=1.9.0 in setup.py, because, after the changes in #2566, the webapp is not compatible with `streamlit`<1.9.0 (I verified that it raises an exception with 1.8.0)
Manual verification
> bug: adapt UI random question for streamlit 1.12 and pin to streamlit>=1.9.0

- haystack/modeling/data_handler/data_silo.py
- haystack/modeling/data_handler/input_features.py
- haystack/modeling/data_handler/processor.py
- haystack/modeling/model/tokenization.py
- haystack/nodes/answer_generator/transformers.py
- haystack/nodes/reader/table.py
- test/modeling/test_tokenization.py
- fixes #3087 
- Eviscerate multiprocessing code in data_silo.py and replace it with large batches fast tokenization
- Remove all deprecated tokenization method invocations (`batch_encode_plus`, `encode_plus`)
No test yet
~~## Todo
This PR is mainly in the draft stage; need to keep the CI churning~~
> fix: Replace multiprocessing tokenization with batched fast tokenization

- pyproject.toml
- tests are failing https://github.com/deepset-ai/haystack/actions/workflows/tests.yml?query=branch%3Amain
Pin pydantic to 1.9.2
Pydantic 1.10 ships a heavy refactoring of the `dataclass` decorator that we use, causing multiple failures. While we investigate the problem, this should bring back the CI to a healthy state.
> build: pin pydantic to 1.9.2

- docs/_src/api/api/reader.md
- haystack/nodes/reader/farm.py
- addresses [#3081](https://github.com/deepset-ai/haystack/discussions/3081)
Add mention of the logging level of the evaluation report generated by `FARMReader.train()`
> Document FARMReader.train() evaluation report log level

- SECURITY.md
- n/a
After setting up an incident response process internally, we're ready to publish a Security Policy for Haystack
> feat: add a security policy for Haystack

- docs/_src/tutorials/tutorials/8.md
- tutorials/Tutorial8_Preprocessing.ipynb
- tutorials/Tutorial8_Preprocessing.py
- fixes https://github.com/deepset-ai/haystack/discussions/3103 
- fixes #3123 
In tutorial 8, when referring to splitting a document, we now consistently use 100. Previously it was sometimes 1,000, which is too long for some transformer models.
I ran the tutorial locally to ensure it still produced output.
- [] - not applicable - I added tests that demonstrate the correct behavior of the change
> docs: Fix the word length splitting; should be set to 100 not 1,000

- haystack/modeling/model/prediction_head.py
- pyproject.toml
- fixes #2926 
Implemented the recommended fix described in the issue. Basically, we perform one GPU to CPU copy of entire matrices instead of individually copying over elements of the matrix.
> fix: Reduce GPU to CPU copies at inference

- .github/workflows/tests.yml
- fixes #3146 
There is an ongoing effort to stabilize CI model HF caching. We added `SEGMENT_DOWNLOAD_TIMEOUT_MIN ` env variable and set it to 15 min. If there are download failures, we will get an exception/timeout rather than wait an hour for the task to timeout.  There is an ongoing effort to fix this issue on the GitHub side, and we expect a more permanent fix sometime in September. For more details, see https://github.com/actions/cache/issues/810
No tests have been added.
See the relevant and referenced issues
> fix: Add 15 min timeout for downloading cached HF models

- haystack/modeling/utils.py
- fixes #3160 
As version 4.21.2 in their pipelines, HF transformers only accept indexed Cuda devices. Therefore, we needed to replace instances of `torch.device("cuda")` with `torch.device("cuda:0")` in devices initialization util function.
A fix is trivial; I tried a small unit test in an interpreter but didn't add any additional unit tests 
Think of a potential scenario where the proposed fix breaks.
> Replace torch.device("cuda") with torch.device("cuda:0") in devices initialization

- docs/_src/api/api/retriever.md
- haystack/nodes/retriever/_embedding_encoder.py
- haystack/nodes/retriever/_losses.py
- haystack/nodes/retriever/dense.py
Add option to use MultipleNegativesRankingLoss for EmbeddingRetriever training with sentence-transformers.
- Resolves #3136 
Expose an option `train_loss` on `EmbeddingRetriever.train`. It is propagated to `_SentenceTransformersEmbeddingEncoder.train` and determines the loss that's used. Also influences the training data format that can be used/is expected. 
So the API is:
```python
embedding_retriever = EmbeddingRetriever(...)
training_data = [{"question": ..., "pos_doc": ...}, ...]
embedding_retriever.train(training_data=training_data, train_loss='mnrl') 
```
[A Colab notebook](https://colab.research.google.com/drive/1cZxlQN8yl57Yuq77aHlX9YyfJAofVfzl?usp=sharing) with a sample run. Qualitative comparison against the baseline model.
Some possible aspects up for discussion
- I exposed the …
> feat: Add option to use MultipleNegativesRankingLoss for EmbeddingRetriever training with sentence-transformers

- pyproject.toml
- test/others/test_utils.py
- failing `main`: https://github.com/deepset-ai/haystack/runs/8300467040?check_suite_focus=true
- Lower low boundary for accuracy in `test_calculate_context_similarity_on_non_matching_contexts` from 0.99 to 0.98
- The test passes locally (with accuracy=1) and on CI (with accuracy=0.9860646599777034)
- I attempted to use a more refined solution with `pytest.approx`, but that works with equality checks only, not with larger-than checks.
> test: lower low boundary for accuracy in `test_calculate_context_similarity_on_non_matching_contexts`

- docker-compose-gpu.yml
- docker-compose.yml
#3148 changed the folder structure of the rest_api, but the docker yaml files weren't updated to reflect this new path. Therefore the docker file isn't loading properly and throws the following error many times 
`FileNotFoundError: Not found: /home/user/rest_api/pipeline/pipelines_dpr.haystack-pipeline.yml. `
Changed the path and ran `docker compose up`
I don't know the codebase well enough to know where else to double-check for path updates... I presume there's probably some other yaml or other config files that are stale.
> Update rest_api Docker Compose yamls for recent refactoring of rest_api 

- .github/workflows/tests.yml
- fixes #3219 
Pin OpenJDK to latest 11 available
CI
> chore: fix Windows CI

- docker/Dockerfile.base
- docker/docker-bake.hcl
- no issue was reported yet
Include `fontconfig` in the final image, otherwise `pdftotext` will fail running
local docker build
Along with this PR:
- There was a clash, `base` was used both for a group and a target, now the target was renamed to `base-cpu`
- Similarly I have renamed the image from `cpu` to `base-cpu` to reflect the target and avoid confusion
> fix: Include fontconfig in the base Docker image

- haystack/nodes/file_converter/pdf.py
- fixes [#3225](https://github.com/deepset-ai/haystack/issues/3225)
- change verification of `pdftotext` installation to work with Windows
Manual tested the line in isolation on Mac and Windows , in environments where `pdftotext` is and isn't available.
> bug: fix pdftotext installation verification

- docs/_src/api/api/primitives.md
- haystack/schema.py
- test/others/test_schema.py
- Tutorial 15 is failing on a validation error https://github.com/deepset-ai/haystack-tutorials/pull/20
Convert Document's contents to `str` in the constructor when building `contexts`
A unit test reproducing the problem was added to this PR
> fix: handle Documents containing dataframes in Multilabel constructor

- .github/utils/pydoc-markdown.py
- docs/_src/api/pydoc/primitives.yml
- pre-commit hook doesn't invoke `pydoc-markdown` when it's needed
Use string replacement instead of path resolution
Tested locally on another PR where tests were failing because a missing api docs update
> fix: make pydoc-markdown hook correctly resolve paths relative to repo root

- haystack/pipelines/base.py
- fixes #3159 
Improper list access. Fixed the list access
TODO
Please review carefully and run the previous failing tests
> Proper retrieval of answers for batch eval

- docs/_src/api/api/document_classifier.md
- haystack/json-schemas/haystack-pipeline-main.schema.json
- haystack/nodes/document_classifier/transformers.py
- test/conftest.py
- test/document_stores/test_faiss_and_milvus.py
- test/nodes/test_document_classifier.py
- fixes #3167
`TransformersDocumentClassifier` output structure was different between ordinary and zero-shot classification.
Now the output is consistent. For `doc.meta['classification']` we always have a structure like this:
```
{"label": "love",
"score": 0.9608993530273438, 
"details": {"love": 0.9608993530273438, "joy": 0.032584577798843384, ...}}}
```
After the discussion in #3167, I decided to keep the `score` attribute in the first level of `doc.meta['classification']`: I think that it can be useful for filtering.
Manual verification.
I can add some tests if you think that's the case.
Other refactoring aspects:
- replaced the attribute `return_all_scores` with `top_k`: it mimicked the same attribute of the HF pipeline, which is now deprecated in favor of the latter.
- simplified …
> refactor: make `TransformersDocumentClassifier` output consistent between different types of classification

- docs/_src/api/api/pipelines.md
- haystack/pipelines/base.py
- haystack/pipelines/standard_pipelines.py
- haystack/telemetry.py
- haystack/utils/reflection.py
- test/conftest.py
- test/pipelines/test_eval.py
- test/pipelines/test_eval_batch.py
- test/pipelines/test_pipeline.py
- fixes https://github.com/deepset-ai/haystack-private/issues/10
- fixes https://github.com/deepset-ai/haystack-private/issues/11
- fixes https://github.com/deepset-ai/haystack-private/issues/12
The encompassing issue is https://github.com/deepset-ai/haystack-private/issues/9
Add a method that classifies the type of the pipeline based on components found
Repeated invocations from colab notebook on a branch where the update trigger is 2 min instead of 24 hours
Added a unit test for pipeline classification
Focus on `pipeline_invocation_counter` decorator in haystack/utils/reflection.py, how the even is triggered (time) and what details are sent to telemetry server
> Classify pipeline's type based on its components

- .github/workflows/tests.yml
- conftest.py
- haystack/json-schemas/haystack-pipeline-1.10.0rc0.schema.json
- test/conftest.py
- test/document_stores/test_faiss_and_milvus.py
- test/nodes/test_retriever.py
- fixes tests not run in https://github.com/deepset-ai/haystack/pull/3252/
- better inferencing of required document store
- fixed an issue with `test_faiss_and_milvus.py::test_cosine_similarity
- well actually run them finally
this is a follow-up PR to https://github.com/deepset-ai/haystack/pull/3252/
> Fix milvus and faiss tests not running

- haystack/pipelines/standard_pipelines.py
- test/pipelines/test_pipeline.py
- test/pipelines/test_standard_pipelines.py
- fixes #3256
MostSimilarDocumentsPipeline, unlike all other pipelines, doesn't have the underlying pipeline property/field. Any method from the superclass that relies on pipeline (get_type, save_to_yaml) will fail.
I added pipeline property, added document store to pipeline but I left the run methods as is - I don't think we can use BaseDocumentStore run method. @bogdankostic please confirm. 
Added a unit test for pipeline classification
Should we add unit tests that exercise other BaseStandardPipeline methods that rely on the pipeline?
> fix:MostSimilarDocumentsPipeline doesn't have pipeline property

- haystack/pipelines/ray.py
Add a simple fix for param name in docstring
> docs: Fix a docstring in ray.py

- test/nodes/test_document_classifier.py
I realized that the tests introduced in #3224 can be made more generic and stable; with the changes made, they will remain valid even if conftest.py changes.
CI
> refactor: better tests for `TransformersDocumentClassifier`

- haystack/pipelines/standard_pipelines.py
We get this error `AttributeError: 'Pipeline' object has no attribute 'pipeline'` when we try to create a `TranslationWrapperPipeline`. The problem is the extra `pipeline` in this line - the attribute doesn't exist. 
Manually tested by trying to use this pipeline. Problem goes away with this change.
> bugfix for TranslationWrapperPipeline

- haystack/modeling/infer.py
- test/conftest.py
- fixes #3272 
Inferencer multiprocessing just as in https://github.com/deepset-ai/haystack/issues/3087 started to cause lockups recently due to various inconsistencies around multiprocessing in torch. Some torch versions worked well, while others caused outright deadlocks.
As there are no performance benefits of multiprocessing, it is best to remove it altogether. Several examples were independently made on how multiprocessing slows down inferencing. 
CI tests, performance tests such as this colab [notebook](https://colab.research.google.com/drive/129-VEBDzBc0RF3D0dg8b2wWumSw8RhkU)
TBD
> refactor: remove Inferencer multiprocessing

- haystack/pipelines/config.py
- test/pipelines/test_pipeline.py
- test/pipelines/test_pipeline_yaml.py
- fixes #3249
Loading Pipelines from a Pipeline configuration with values for parameters that contained non-alphanumeric characters and spaces were failing as we checked them against [this RegEx](https://github.com/deepset-ai/haystack/blob/b84a6b17165dbf10665794b5decdefa113300749/haystack/pipelines/config.py#L24). This is too restrictive given that values can be arbitrary and is especially failing when using words from languages other than English.
I did manual tests. ~~Automatic tests will be added.~~ Unit test has been added.
I'm not sure if there was a good reason to not allow arbitrary values for parameters. Please let me know if this was the case.
> fix: Allow less restrictive values for parameters in Pipeline configurations

- haystack/pipelines/base.py
- test/pipelines/test_eval.py
If you want to run eval always with isolated mode if one node supports it, it's not practical to investigate the pipeline and set `add_isolated_node_eval` accordingly, especially if you have a ton of different pipelines.
Currently `Pipeline.eval` fails with 
```No node(s) or global parameter(s) named add_isolated_node_eval found in pipeline.```
if there is no node that supports it.
- add exception for `add_isolated_node_eval` in pipeline's node params validation
- added test
Downside of this would be that the user would not be notified that there is no node that supports isolated. Eval would be executed and only after calling `calculated_metrics(eval_mode="isolated")` the metrics would be empty.
I think this is acceptable as isolated is only supported by some nodes in the pipeline. So …
> fix: eval() with `add_isolated_node_eval=True` breaks if no node supports it

- haystack/document_stores/weaviate.py
- None
The current link to the Weaviate's schema documentation is dead and needs to be updated
I visited the link using a web browser
None
- [] I've used the [conventional commit convention](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title
> Update weaviate schema doc link

- haystack/modeling/evaluation/eval.py
- haystack/modeling/training/base.py
- test/modeling/test_dpr.py
- fixes #3353 
Added checks for `DataParallel` and `WrappedDataParallel` before calling the forward methods of `AdaptiveModel` or `BiAdaptiveModel` in `Trainer.compute_loss` and `Evaluator.eval` so that training works when using Data Parallelism. 
I ran multi GPU training of the FARMReader on AWS using 4 GPUs.
> fix: Added checks for DataParallel and WrappedDataParallel

- haystack/document_stores/faiss.py
- fixes #3254
Removed two lines of dead code.
> refactor: remove dead code from `FAISSDocumentStore`

- haystack/document_stores/base.py
- haystack/utils/__init__.py
- haystack/utils/labels.py
Label aggregation is encapsulated into `BaseDocumentStore`'s `get_all_labels_aggregate` and cannot be used outside the document store. Label aggregation should not be tied to DocumentStores.
- extract logic into method `aggregate_labels` of new module `haystack.utils.labels`
- refactor
- adjust docstrings
```python
from haystack.utils import aggregate_labels
labels = fetch_labels()  # from anywhere, returns List[Label]
aggregated_labels = aggregate_labels(labels)  # returns List[MultiLabel]
```
- rely on existing tests of `BaseDocumentStore.get_all_labels_aggregated()`
- None
> feat: extract label aggregation

- haystack/document_stores/faiss.py
- haystack/document_stores/sql.py
- test/conftest.py
- test/document_stores/test_document_store.py
- test/document_stores/test_faiss.py
- fixes #3327
In `SQLDocumentStore`:
- `vector_id` is no longer unique
- added a `UniqueConstraint` for `index` + `vector_id`
In `FAISSDocumentStore`:
- modified `update_embeddings` method to take this change into account.
Now for every index, `vector_id` starts at 0
- As suggested by @ZanSara, I locally ran the tests using PostgreSQL with `pytest . --document_store_type="sql,faiss"`
- Added new tests for `SQLDocumentStore` and `FAISSDocumentStore`
- Tests can be improved/redesigned. I am open to suggestions.
- New test in test_document_store.py will probably not run until #3332 is merged
- Fixed other little things here and there
> fix: allow same `vector_id` in different indexes for SQL-based Document stores

- haystack/nodes/question_generator/question_generator.py
- test/nodes/test_question_generator.py
- fixes #3380 
Properly accounts for questions generated and originating documents order
Added unit test
See if you can find a use case that again breaks the order of questions and documents.
> fix: QuestionGenerator generates wrong document questions for non-default `num_queries_per_doc` parameter

- haystack/json-schemas/haystack-pipeline-1.10.0rc0.schema.json
- haystack/json-schemas/haystack-pipeline-main.schema.json
- haystack/nodes/retriever/_embedding_encoder.py
- haystack/nodes/retriever/dense.py
- test/conftest.py
- test/nodes/test_retriever.py
- Doesn't fix, but is a part of #3306 
Added OpenAIEmbeddingEncoder as a method to create document and query embeddings. 
Added a unit test, needs to inject OpenAI API key in unit tests (as a secret)
LMK if anything is unclear
> feat: Add OpenAIEmbeddingEncoder to EmbeddingRetriever

- haystack/json-schemas/haystack-pipeline-1.10.0rc0.schema.json
- haystack/json-schemas/haystack-pipeline-main.schema.json
- haystack/json-schemas/haystack-pipeline.schema.json
- haystack/nodes/_json_schema.py
- Json schema ordering
- Used the `sort_keys=True` option in the `json.dump` function to order the keys
- Ordered the `anyof_list` which was causing the order of the `"type": "boolean"` and `"type": "string"` to switch depending on which system the schema generation was run
- Got it to pass the CI schema validation
> fix: Update how schema is ordered

- haystack/nodes/reader/farm.py
- #2771 
- Add comment to explain that no-answer samples are generated by the FARMReader during training if the passage is long
> docs: Add comment about the generation of no-answer samples in FARMReader training

- .github/workflows/tests.yml
- test/conftest.py
- test/nodes/test_summarizer.py
- test/nodes/test_summarizer_translation.py
- No open issue
- Changed summarizer model to a smaller one (2GB to 500MB) to save on space and speed up the tests. Looking at the CI for [integration-tests-linux(nodes)](https://github.com/deepset-ai/haystack/actions/runs/3271842021/jobs/5382520160) it looks like this change results in a large speedup (e.g. **Run Tests** goes from ~20min to ~8 min). Or another way to look at it is that the summarizer had 7/10 of the slowest tests before and now 0/10.
Updated affected CI tests.
I noticed that the integration tests for nodes were taking awhile and I found that we could achieve an easy win in speedup by swapping out the model used for summarization.
> feat: Speed up integration tests (nodes)

- haystack/errors.py
- haystack/nodes/answer_generator/openai.py
- haystack/nodes/retriever/_embedding_encoder.py
- haystack/utils/reflection.py
- test/others/test_utils.py
Adds exponential back-off decorator. This decorator can decorate a method making API invocations and in the case of rate limit errors, it simply attempts further invocations with exponential backoff. When dealing with OpenAI API requests, backoff and retry is a great strategy to minimize latency while avoiding rate limit errors, while being completely transparent to our users. 
Manually, not sure how to thoroughly test it with unit tests. Open to ideas.
> feat: Add exponential backoff decorator; apply it to OpenAI requests

- haystack/json-schemas/haystack-pipeline-1.11.0rc0.schema.json
- haystack/schema.py
- fixes #3382
As reported in #3382, there was a minor bug in `__repr__` method of the `Document` class.
Since "The truth value of an array with more than one element is ambiguous.", I check instead that the `embedding` `is not None`.
Manual tests
Other small fixes
> fix: improve Document `__repr__`

- pyproject.toml
- fixes #2931
As deeply discussed in the issue, for compatibility with different python versions,
I apply this pin in pyproject:
```toml
audio = [
"pyworld>=0.3.1; python_version >= '3.8'",
"pyworld<0.3.1; python_version < '3.8'",
```
Manual verification with different python versions
> Fix: update pyworld pin

- haystack/pipelines/base.py
- haystack/telemetry.py
- partially #3342 
Sends pipeline event at most once in 24 hours on two triggers: 100 queries processed by pipeline or running for 24 hours.
Tested manually by @vblagoje and @julian-risch
> feat: send event if number of queries exceeds threshold

- .github/workflows/readme_sync.yml
- fixes n/a
Most likely some copypasta, `-unstable` should be synced only when merging on `main`
Tested manually on the `v1.10.x` branch
> Fix the readme version to sync

- docs/_src/api/pydoc/utils.yml
- haystack/utils/doc_store.py
- format function docstrings so that they get generated by pydoc markdown (specifically the doc_store util functions)
- increase the number of util modules for which docstrings are being generated
- generated api docs locally
> docs: Extend utils API docs coverage

- haystack/pipelines/base.py
- fixes #3387 
When evaluating pipelines the user normally would use the in-built [eval_beir()](https://github.com/deepset-ai/haystack/blob/7290196c32abf44e269caa03e1d2178c77992b0e/haystack/pipelines/base.py#L727) method. This method doesn't contain a way of cropping the dataset of choice and for quick tests or reduced benchmarks when the dataset is huge that is a big plus.
This PR introduces a cropping feature (a new parameter) to allow this.
**Manually since there are no tests for `eval_beir()`.**
It can be manually tested with the following script (having enabled `Elasticsearch`):
```python
from haystack.document_stores.elasticsearch import ElasticsearchDocumentStore
from haystack.nodes.retriever import BM25Retriever
from haystack.nodes.file_converter …
```
> Feat: allow decreasing size of datasets loaded from BEIR

- haystack/schema.py
- test/others/test_schema.py
- n/a
- Add the `__contains__` method to the `Span` primitive
- This change will allow the following syntax: 
- `assert 10 in Span(5, 15)`
- `assert Span(10, 11) in Span(5, 15)`
- See the unit tests for plenty more examples
- Unit tests
- This PR was made just to have the convenience of the `in` syntax while working on some audio nodes, where Spans are heavily used to represent text/audio alignment data
> feat: add `__cointains__` to `Span`

- haystack/nodes/answer_generator/openai.py
The current prompt for the Answergenerator can exceed the allowed length. The prompt needs to account for the number of generated tokens as well since "The token count of your prompt **plus max_tokens** cannot exceed the model's context length.".
Subtract max_tokens from leftover_token_len
> Bug: Fix prompt length computation

- haystack/telemetry.py
- fixes #3439 
This PR adds a check before writing the telemetry config file. If telemetry is disabled, this file is not written. As a consequence no event will be sent (not even a file event that telemetry is turned off).
Previously, if no config file existed and telemetry was disabled via an environment variable, it could happen that a new user id was generated and stored in a config file. As a consequence a final event was sent, which causes the error 
```
ERROR:posthog:error uploading: HTTPSConnectionPool(host='tm.hs.deepset.ai', port=443): Max retries exceeded with url: /batch/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f07b4173c70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```
if there is no …
> fix: disabling telemetry prevents writing config

- haystack/nodes/retriever/_embedding_encoder.py
- fixes #3436 
Check that Document store uses a similarity function compatible with the Sentence Transformers embedding model
(we can deduce it from the model name).
If the similarity function is incompatible, show a warning.
Some manual tests
The topic of the Sentence Transformers nomenclature is a bit tricky.
So, if there is "-cos-" in the model name, we can undoubtedly say that the model is compatible with the cosine similarity, but it might also be compatible with the dot_product.
The solution I propose seems to me to be a good compromise, while the current warning is misleading.
> fix: warning if doc store similarity function is incompatible with Sentence Transformers model

- docs/_src/api/pydoc/utils.yml
- Fixes wrong title and slug of Utils API page
- This should also be applied to v1.10.x
> docs: Change slug and title of utils API pydoc

- haystack/pipelines/base.py
- haystack/utils/reflection.py
- test/pipelines/test_pipeline_debug_and_validation.py
- fixes https://github.com/deepset-ai/haystack-private/issues/19
Remove the decorator and instead use simple counter attribute in Pipeline.
This PR adds a new unit test thanks to @vblagoje 👍 
None
> bug: replace decorator with counter attribute for pipeline event

- README.md
- related to https://github.com/deepset-ai/haystack/issues/3479
- Add badge for the schema files generation in https://github.com/deepset-ai/haystack-json-schema to `README.md`
- Preview
- We should also connect it to the Slack bot
> feat: add Schemas badge on README.md

- .github/workflows/minor_version_release.yml
- fixes n/a
- Simplified a bit the workflow
- Install Haystack[all] and generate the new schema
- Add the schema to the PR that bumps the unstable version on `main`
Couldn't test it yet as the current release is in progress
> [release process] Create new schema when bumping unstable

- haystack/nodes/file_converter/pdf.py
- fixes #3477
- Remove path referencing the package folder from https://github.com/deepset-ai/haystack/blob/5ca96357ff526bf11aefa7fe4aa24fd11135cd0c/haystack/nodes/file_converter/pdf.py#L255
- This path causes issues if the package folder is not writable (non editable installs with Conda on Windows, just to name an example)
- CI
n/a
> fix: do not reference package directory in `PDFToTextOCRConverter.convert()`

- haystack/telemetry.py
- fixes #3428 
Added s3 link of the dataset used tutorial 19.
This PR can be merged even before the tutorial PR as it just tracks the download of the zip from S3.
Haven't tested yet.
Full tutorial at https://github.com/deepset-ai/haystack-tutorials/pull/52
> telemetry changes for tutorial 19

- docs/_src/api/pydoc/document-store.yml
n/a
- Add docs for `search_engine.py` This class documents many methods used by Elasticsearch and similar docstores.
n/a
- This is a patch on the fact that such method are not present in the document store classes themselves anymore.
- This is not a complete fix as they are still not very visible as ES methods. Better suggestions welcome.
> fix: generate docs for `search_engine.py`

- .github/actions/python_cache/action.yml
- .github/workflows/black.yml
- .github/workflows/cml.yaml
- .github/workflows/demo.yaml
- .github/workflows/docker_build.yml
- .github/workflows/minor_version_release.yml
- .github/workflows/openapi.yml
- .github/workflows/readme_sync.yml
- .github/workflows/tests.yml
- Fixes #3377
- Many GH actions we use are several version behind:
- `actions/checkout@v2` --> `actions/checkout@v3`
- `actions/setup-python@v2` --> `actions/setup-python@v4`
- `actions/cache@v2` --> `actions/cache@v3`
- CI
n/a
> refactor: upgrade actions version

- README.md
- no related issue
This PR fixes the link directing to our tutorials.
Manual test.
> docs: Fix link directing to tutorials in README.md

- .github/workflows/tests.yml
- haystack/document_stores/sql.py
- test/conftest.py
- test/document_stores/test_base.py
- test/document_stores/test_document_store.py
- test/document_stores/test_sql.py
- fixes n/a
Run the `DocumentStoreBaseTestAbstract` with `SQLDocumentStore` 
Tests are running in the CI
The `SQLDocumentStore` is buggy and partially implemented in several parts, so a bunch of the base tests were failing. I have skipped the failing tests in this PR as filling the feature gap would require quite an implementation effort.
> feat: add SQLDocumentStore tests

- test/nodes/test_retriever.py
Running the test locally for test_table_text_retriever_training didn't clean up model files after running.
Added tmp_path to the test function args and used it inside the test for model file creation.
re-ran the UT locally to make sure the folder isn't remaining
If all the tests pass, it should be safe to merge.
> bug: didn't clean up model files after running pytest for test_table_text_retriever_training

- docker/README.md
- Make changes to formatting and content of Docker readme file. This will become the readme of the Dockerhub repo.
> docs: Update docker readme

- haystack/errors.py
- haystack/telemetry.py
- related to #3309
Added a message field to all HaystackError(s) raised. If set message property will be visible in telemetry
Manual verification, there is no other way.
Someone familiar with telemetry needs to review. Otherwise, the context is rather big and requires time to pick up.
> Use telemetry to identify most common errors

- .github/workflows/tests.yml
- haystack/document_stores/weaviate.py
- haystack/utils/doc_store.py
- pyproject.toml
- test/conftest.py
- test/document_stores/test_base.py
- test/document_stores/test_weaviate.py
- fixes n/a
Move Weaviate tests into their own class deriving from `DocumentStoreBaseTestAbstract`
`pytest -m"document_store and integration" test/document_stores/test_weaviate.py`
- calls to `data_object`s were patched to avoid incurring in the warning 
"The non-class namespaced APIs (None value for `class_name`) are going to be removed in the future versions of the    Weaviate Server and Weaviate Python Client."
- Weaviate version running in CI was bumped to 1.16 so we get bugfixes we need for filtering
> refactor: Refactor Weaviate tests

- .github/workflows/tests.yml
- rest_api/pyproject.toml
- fixes https://github.com/deepset-ai/haystack/actions?query=workflow:Tests
Starlette started using `httpx` for their HTTP test client, and this is now required to run the `rest_api` tests.
CI
> CI: install httpx to run tests

- .github/release.yml
- fixes n/a
Ignore PRs labelled with `Proposal` when generating release notes.
> refactor: ignore proposals in release notes

- haystack/schema.py
- rest_api/rest_api/controller/document.py
REST API endpoint for search and get_documents does not work for tableQA. Therefore some small changes are needed
manually deployed docker and tested
@ZanSara
> fix: [rest_api] support TableQA in the endpoint `/documents/get_by_filters`

- .github/workflows/tests.yml
- conftest.py
- haystack/document_stores/pinecone.py
- test/document_stores/test_base.py
- test/document_stores/test_pinecone.py
- fixes n/a
- Implement Pinecone tests as a subclass of `DocumentStoreBaseTestAbstract`
- Fix Label metadata management: it was ignored before, probably a sign that's not a feature Pinecone users rely on very much, still had to fix it in order for the tests to pass.
`pytest -m"document_store and integration" test/document_stores/test_pinecone.py`
Tests run on Linux, Win and MacOS because the storage is mocked. Mock can be disabled passing `--mock-pinecone=false` so the test suite is still to be considered of kind "integration".
> refactor: Pinecone tests

- haystack/document_stores/es_converter.py
- test/document_stores/test_document_store.py
- fixes https://github.com/deepset-ai/haystack/issues/3571
- fix bug
- test adjusted
> fix: Elasticsearch / OpenSearch brownfield function does not incorporate meta

- haystack/document_stores/weaviate.py
- test/document_stores/test_base.py
- test/document_stores/test_weaviate.py
- fixes https://github.com/deepset-ai/haystack/actions?query=workflow:Tests
Weaviate hardcodes certain metadata fields into its index, in this case `name`. When `name` is not present in the original document, and _only if other metadata is set_, after one full roundtrip write/read you end up having `meta["name"] == None` in the resulting doc.
- Drop the `name` field from `meta` if its value is `None`
`pytest -m"document_store and integration" test/document_stores/test_weaviate.py -x -vv`
While running the tests, another bug was exposed: the `embedding` field in Document was set regardless of the `return_embeddings` init param - this is fixed now. 
I also noticed the original documents passed to `write_documents` are modified when they don't contain embeddings, which I think it's wrong but …
> fix: discard metadata fields if not set in Weaviate

- .github/workflows/tests.yml
- test/document_stores/test_document_store.py
- test/document_stores/test_milvus.py
- fixes n/a
Implement the Milvus tests as `DocumentStoreBaseTestAbstract`
`pytest -m"document_store and integration" test/document_stores/test_milvus.py -x`
> refactor: move milvus tests to their own module

- haystack/document_stores/sql.py
- test/document_stores/test_sql.py
- fixes #3434
- Use a JSON marshaller to store metadata values
- Remove the validator so we don't drop unsupported data types anymore
- Emit a warning when passing filters to `query()` as they won't work as expected if metadata have compound data types
Existing tests
- I am not sure about the warning on `query()` as it can get verbose, but I also don't want users to have the false perception the `SQLDocumentStore` fully supports lists metadata.
> feat: store metadata using JSON in SQLDocumentStore

- pyproject.toml
- mitigation of https://github.com/deepset-ai/haystack/issues/3600
- pin `faiss-cpu` to the latest working version while we investigate why 1.7.3 fails with `https://github.com/deepset-ai/haystack/issues/3600`
> fix: Pin faiss-cpu as 1.7.3 seems to have problems

- .github/workflows/readme_sync.yml
- fixes https://github.com/deepset-ai/haystack/actions/runs/3494995811
- Use a recent Python and only pin minor
CI
> CI: Update Python version in Readme Sync action

- haystack/nodes/file_converter/parsr.py
- fixes #3593
Since #2932, the form feed character ("\f") is used to separate different pages.
In the `ParsConverter`, for each page, there is this check:
https://github.com/deepset-ai/haystack/blob/dc26e6d43ef23c1746722c613347e28f05982eee/haystack/nodes/file_converter/parsr.py#L189-L190
that raises an error if `len(text)==0`. For example, we can have empty pages or pages where there is only a table.
I corrected this little bug.
Manual test using [this PDF](https://github.com/camelot-dev/camelot/blob/master/tests/files/medicine.pdf).
I also have doubts about https://github.com/deepset-ai/haystack/blob/dc26e6d43ef23c1746722c613347e28f05982eee/haystack/nodes/file_converter/parsr.py#L210
If the first page is blank, "\f" is stripped and page numbers may become incorrect.
@bogdankostic WDYT?
> fix: `ParsrConverter` fails on pages without text

- haystack/schema.py
- test/pipelines/test_eval.py
- fixes https://github.com/deepset-ai/haystack/issues/3590
- convert eval metrics from numpy to float
added asserts to extractive qa eval and sas test
> fix: Convert eval metrics to python float

- haystack/utils/labels.py
- add correct type hints to `aggregate_labels`
- existing tests
> chore: fix return type of `aggregate_labels`

- haystack/document_stores/weaviate.py
- test/document_stores/test_weaviate.py
- fixes #3553
- Uncomment a block of code that should enable filters with queries
- Enable the relative tests
- CI
n/a
> refactor: Weaviate query with filters

- haystack/utils/doc_store.py
- test/benchmarks/utils.py
- fixes #2631 
- Use `9200` as the default port, consistent with the `OpensearchDocumentStore` defaults.
- `launch_opensearch` now takes a `local_port` param that can be used to retain the old behaviour
- I fixed the benchmark script because it was relying on the old port
> fix: use 9200 as the default port in `launch_opensearch()`

- haystack/nodes/reader/table.py
- fixes N/A
This moves the entire forward pass of the `_TapasForScoredQA` variant of the TableReader under the `torch.no_grad()` context.
Used existing unit tests.
This is the recommended practice for running pytorch models at inference time because it saves on resource allocations. Specifically it tells Pytorch it does not need to allocate space for keeping track of the gradients of the tensors used in the forward pass, which saves on memory. This change does not affect the output of the model.
> fix: Move entire forward pass of TableQA within `torch.no_grad()`

- .pre-commit-config.yaml
- fixes #2930 
Now that we removed the schema generation from the developer workflow, we should be good re-enabling these super fast hooks.
Tested locally but not sure if there's any major implication I'm not seeing
> chore: Re-enable pre-commit hooks

- haystack/pipelines/base.py
- test/pipelines/test_eval.py
- fixes https://github.com/deepset-ai/haystack-private/issues/23
Add `gold_offsets_in_contexts` and `offsets_in_context` to evaluation result dataframe.
I extended one of the existing test cases. It now checks that all expected column names are part of the evaluation result dataframes, including `offsets_in_context `.
> feat: add offsets_in_context to evaluation result

- haystack/pipelines/base.py
- test/pipelines/test_pipeline.py
- partially resolves #3342 
get_type() misclassified some pipelines as "Unknown pipeline". These pipelines are now properly classified by type.
Unit test, see PR diff
Any other test cases from telemetry?
> Adjust get_type() method for pipelines

- .github/workflows/tests.yml
- haystack/document_stores/weaviate.py
- test/document_stores/test_weaviate.py
- fixes [this issue](https://github.com/deepset-ai/haystack/pull/3628#issuecomment-1331269953)
- Comment back lines https://github.com/deepset-ai/haystack/blob/main/haystack/document_stores/weaviate.py#L990-L1000
- Improve the relevant test  https://github.com/deepset-ai/haystack/blob/main/test/document_stores/test_weaviate.py#L182-L184
- Upgrade Weaviate in CI from `1.16` to `latest`
- Locally, CI
See the great analysis of the issue by @zoltan-fedor https://github.com/deepset-ai/haystack/pull/3628#issuecomment-1331269953 and vote for this issue on Weaviate: https://github.com/semi-technologies/weaviate/issues/2393
> fix: revert Weaviate query with filters and improve tests

- pyproject.toml
- fixes #3218
- Related to https://github.com/beir-cellar/beir/issues/71
- Remove the `beir` extra from the `all-gpu` extra. 
- `faiss-cpu` is hardcoded as a dependency of `beir`: https://github.com/beir-cellar/beir/blob/c3334fd5b336dba03c5e3e605a82fcfb1bdf667d/setup.py#L26
- and is incompatible with `faiss-gpu` https://github.com/facebookresearch/faiss/blob/main/INSTALL.md
- See https://github.com/beir-cellar/beir/issues/71
- Local installation
- CI
n/a
> fix: remove `beir` from `all-gpu`

- haystack/document_stores/memory.py
- haystack/document_stores/milvus.py
- haystack/document_stores/weaviate.py
- haystack/modeling/data_handler/data_silo.py
- haystack/modeling/data_handler/processor.py
- haystack/modeling/evaluation/eval.py
- haystack/modeling/infer.py
- haystack/modeling/training/base.py
- haystack/nodes/audio/document_to_speech.py
- haystack/nodes/retriever/base.py
- haystack/nodes/retriever/multimodal/embedder.py
- haystack/pipelines/base.py
- haystack/utils/augment_squad.py
- haystack/utils/context_matching.py
- haystack/utils/deepsetcloud.py
- haystack/utils/squad_data.py
- haystack/utils/squad_to_dpr.py
- There is no related issue
This is a minor fix making sure we consistently use tqdm.auto instead of tqdm
tqdm.auto renders progress bars appropriately in the detected execution environment i.e. Colab, Ipython etc
No unit tests provided
Don't integrate, lets first see the CI and try it out.
> bug: Use tqdm auto instead of plain tqdm 

- test/conftest.py
- test/nodes/test_table_reader.py
- fixes N/A
Expanded the unit tests to also check for the expected scores of the answers returned by the `TableReader`.
Ran the newly added checks to the unit tests.
This should help us check if any future changes to the code base cause the model scores to differ.
> feat: Update table reader tests to check the answer scores

- pyproject.toml
- fixes [CI failure](https://github.com/deepset-ai/haystack/actions/runs/3674242182/jobs/6212348208)
- Downgrade `espnet` to `202209` to keep the tests green.
- This is a workaround to keep the CI alive until we migrate audio nodes out.
- CI
n/a
> fix: pin `espnet` in the `audio` extra

- haystack/document_stores/pinecone.py
- test/document_stores/test_pinecone.py
- fixes #3659
The linked issue is caused by incompatibility for multilevel metadata dictionaries in Pinecone. To fix the issue, I added metadata processing steps to flatten (and 'un-flatten') the metadata dictionaries.
Using [this notebook](https://gist.github.com/jamescalam/3d5a219226b46539afbda8982b2bb2dd)
N/A
> fix: pinecone metadata format

- docker/Dockerfile.base
- fixes N/A
Forgot to remove `&& \` when updating the Dockerfile in PR #3703
> fix: fix Docker file

- .github/actions/python_cache/action.yml
- docker/docker-bake.hcl
- fixes N/A
Removes remaining references to torch-scatter that was originally removed as a dependency in Haystack in PR #3703
> fix: Removed overlooked torch scatter references

- haystack/nodes/retriever/_embedding_encoder.py
- haystack/nodes/retriever/dense.py
- No related issue. 
- Cohere [announced](https://txt.cohere.ai/multilingual/) a new multilingual embedding model today, so we are adding it to Haystack. The new model should perform better than any other open-source embedder while projecting in 768 dimensions - excellent!   
- Enabling the use of `finance-sentiment` embedding model. This is not a baseline model but is listed and available as a "Cohere finetuned model"
Adds a new model to cohere embedder. Use it by simply specifying it:
```
retriever = EmbeddingRetriever(
document_store=document_store,
embedding_model="multilingual-22-12", 
batch_size = 16,
api_key=my_cohere_api_key,
)
```
I ran a Collab [notebook](https://colab.research.google.com/drive/1jwwsxJsn_Ch9xU68K3rjYGDyL-Gs1-Km#scrollTo=kFwiPP60A6N7) to try it out. It worked as …
> feat: Update cohere embedding models

- pyproject.toml
- fixes #3683
- related issue #3521
- PyTorch 1.13.1 was released today and CI test passed. Version 1.13.0 and 1.13.1 both work now with Haystack so it is save to upgrade. Let's upgrade! We will use the same version range as transformers so we let transformers install torch as one of it's dependencies.
CI and so manual tests
> build: upgrade torch and let transformers pick the version 

- haystack/nodes/reader/table.py
- fixes N/A 
- related to PR #3601 
- Swapped out all `torch.no_grad()` calls with `torch.inference_mode()`
- Updated forward pass of `RCIReader` to use `with torch.inference_mode()`
Existing tests
> feat: Use torch.inference_mode() for TableQA

- .github/workflows/stale.yml
- proposals/0000-template.md
- proposals/README.md
- Clarify the process and the people involved in the process.
- Add a Github workflow to manage stale proposals
> Update the proposals process

- haystack/nodes/retriever/_embedding_encoder.py
- test/nodes/test_retriever.py
Enabled text-embedding-ada-002 for EmbeddingRetriever. See https://openai.com/blog/new-and-improved-embedding-model/ for more details. 
To enable this retriever use the model full name i.e. `text-embedding-ada-002`:
```
retriever = EmbeddingRetriever(
document_store=document_store,
embedding_model="text-embedding-ada-002",
batch_size = 32,
api_key=api_key,
max_seq_len = 8191,
)
```
Added unit test, ran Colab [notebook](https://colab.research.google.com/drive/1jwwsxJsn_Ch9xU68K3rjYGDyL-Gs1-Km)
Have a look at https://beta.openai.com/docs/guides/embeddings/what-are-embeddings 
We now have to deal with two generations of models. The old generation of models - as we have already dealt with them. We'll have users specify the full model name to use the new model. 
Have quick look at the unit …
> feat: Enable text-embedding-ada-002 for EmbeddingRetriever

- haystack/document_stores/weaviate.py
- test/document_stores/test_weaviate.py
- test/nodes/test_retriever.py
Unfortunately the BM25 support with Weaviate got broken with Haystack v1.11.0+, which is getting fixed with this commit.
Please see more details under issue [#3720](https://github.com/deepset-ai/haystack/issues/3720).
- fixes #3720 
The issue was caused by [this commit.](https://github.com/deepset-ai/haystack/commit/05c68b6624052ba25812a154671be70c05bf3979#diff-e5d25233b9303f763ce1fba1c35474eb3de067ef1a4ba4e44b99a44bf04361e0R206)
I have fixed it by:
- making the Weaviate document store to be a subclass of KeywordDocumentStore
- adding the query_batch() method to the Weaviate document store, although there is no batch querying in Weaviate currently, see @laura-ham 's [comment from Weaviate](https://stackoverflow.com/questions/71558676/does-weaviate-support-bulk-query#comment126569547_715619 …
> Fixing broken BM25 support with Weaviate - fixes #3720

- haystack/nodes/retriever/sparse.py
- little improvement of #3666
Previously, in `TfidfRetriever`, the parameter `queries` of the internal method `_calc_scores` was of type `Union[str, List[str]]`.
Now the type of `queries` is only `List[str]`.
In this PR, I remove a superfluous check.
CI
> refactor: remove unused code in `TfidfRetriever`

- haystack/nodes/reader/table.py
- test/nodes/test_table_reader.py
- fixes N/A
I made a small refactor to the TableReader code to help reduce duplicate code and added expanded unit tests. Instead of using a `_BaseTapasEncoder` to inherit from, static utility functions were made instead because they can be useful for all TableReader nodes (e.g. `_TapasEncoder`, `_TapasScoredEncoder`, and `RCIReader`). I also expanded on the unit tests to ensure that the `TableReader.predict_batch` function returned the expected output. 
Used existing tests and expanded on the existing tests.
This refactoring does not change the functionality of the TableReader or cause any breaking changes.
> refactor: Remove duplicate code in TableReader

- proposals/text/0000-demo-repository.md
- proposals/text/3695-demo-repository.md
- n/a
NLP applications showcasing Haystack's capabilities can be an invaluable learning resource
for its users, but at this moment we don't fully take advantage of the only one demo we have
as a documentation source.
This proposal aims at overcoming that limitation in two ways:
- Define better requirements for a demo application so that users can learn from it.
- Make it easier to add more demo applications showcasing Haystack.
> proposal: Create a dedicated Github repository for Haystack demos

- .github/workflows/docker_release.yml
- docker/Dockerfile.base
- fixes https://github.com/deepset-ai/haystack/issues/3619
We currently hardcode the installation process for `pdftotext` from xpdf into the base image. To speed up the build, we download and install the binary version distributed for amd_64 - this obviously can't work on the ARM image that we build with the same Dockerfile.
Instead of downloading and installing the binary version of `pdftotext`, we build it from source. This should work in a cross-platform fashion.
- Manually tested locally
- docker pull deepset/haystack:cpu-massi-xpdf
The docker build workflow contains changes I'm using to test this branch that need to be reverted before merging the PR.
> fix: build `pdftotext` from sources

- haystack/nodes/query_classifier/sklearn.py
- haystack/nodes/query_classifier/transformers.py
- related: https://github.com/deepset-ai/haystack/issues/2904 
Our S3 bucket for scikitlearn models for query classification nodes contains the old version of the models with the original names:
[gradboost_query_classifier_statements/](https://s3.console.aws.amazon.com/s3/buckets/ext-models-haystack?region=eu-central-1&prefix=gradboost_query_classifier_statements/&showversions=false)
[gradboost_query_classifier/](https://s3.console.aws.amazon.com/s3/buckets/ext-models-haystack?region=eu-central-1&prefix=gradboost_query_classifier/&showversions=false)
and also the newly trained models that have better compatibility with new scikit learn versions:
[gradboost_query_classifier_statements_2022/](https://s3.console.aws.amazon.com/s3/buckets/ext-models-haystack?region=eu-central-1&prefix=gradboos …
> feat: make new sklearn models default in QueryClassifier

- docker/Dockerfile.api
- fixes #3255 
Runs gunicorn command inside docker container as a non-root user. This was a requirement from one of the users who had a requirement to run gunicorn non-root. 
Adapted from https://stackoverflow.com/questions/68155641/should-i-run-things-inside-a-docker-container-as-non-root-for-safety
I ran the gpu image and didn't notice any issues. Will do another round of tests
Try to see if gunicorn behaviour changed somehow
> feat: Run commands inside docker container as a non root user

- haystack/nodes/summarizer/base.py
- haystack/nodes/summarizer/transformers.py
- test/conftest.py
- test/nodes/test_summarizer.py
- As proposed in https://github.com/deepset-ai/haystack/pull/3452#issuecomment-1295095248, in Haystack 1.10,  `generate_single_summary` and `separator_for_single_summary` parameters were deprecated.
- we agreed that we would remove them in version 1.12. So I'm removing these parameters now.
CI
> refactor: remove deprecated parameters from `Summarizer`
