deepset-ai/haystack

- haystack/indexing/io.py
- requirements.txt
- tutorials/Tutorial3_Elasticsearch_backend.py
Let's add a minimal example how to use elasticsearch backend. 
I also corrected a minor typo (split_paragrahs) and updated requirements.
> Add minimal tutorial for ES

- haystack/database/elasticsearch.py
> Fix `get_all_documents` query for Elasticsearch

- haystack/__init__.py
- haystack/database/elasticsearch.py
- haystack/finder.py
- haystack/retriever/elasticsearch.py
- requirements.txt
Let's make it simpler to configure haystack with an already existing, custom elasticsearch index.
> More flexbile es config & support for filters

- haystack/database/elasticsearch.py
- haystack/reader/farm.py
Adding more parameters to configure the elasticsearch connection for https.
> Add more ES connection params

- Dockerfile
- Dockerfile-GPU
- haystack/__init__.py
- haystack/database/elasticsearch.py
- haystack/finder.py
- Adding a Docker for GPU deployment
- Making logging a bit more verbose for easier monitoring of deployments
- Returning no answers if there are no docs that match the requested filters
> Add gpu dockerfile, improve logging, fix minor bug with filtering

- Dockerfile
- Dockerfile-GPU
- haystack/api/inference.py
- haystack/finder.py
- haystack/reader/farm.py
- requirements.txt
- setup.py
Several enhancements & fixes to simplify deployment of the REST API: 
- Remove ENV variables from docker and rather use defaults in the fastAPI app
- More config params for the API to configure containers more easily at runtime
- Skip reader if retriever doesn't return results
- Fix top_k_per_sample to not return too many similar answers from one passage
- Improve logging
- Make some fields in request / response optional
> Improve deployment of REST API (Configs, logging, minor bugs)

- haystack/retriever/elasticsearch.py
Add params to retriever to create more flexible embeddings
- extraction_strategy 
- extraction_layer
> Add params to create_embeddings in retriever

- haystack/reader/transformers.py
- haystack/retriever/tfidf.py
Also before adding this change , even with the FarmReader, the metadata document_name was not getting captured.
> Add document_id with Transformers Reader 

- haystack/reader/farm.py
Prepare for upgrade to next FARM version
> WIP update inferencer args (num_processes, chunksize) to latest FARM version

- README.rst
- haystack/database/base.py
- haystack/finder.py
- haystack/retriever/elasticsearch.py
- tutorials/Tutorial4_FAQ_style_QA.ipynb
- tutorials/Tutorial4_FAQ_style_QA.py
Let's add a basic Tutorial for FAQ-based QA. 
Related to #97
> Add basic tutorial for FAQ-based QA & batch comp. of embeddings

- haystack/database/elasticsearch.py
> Remove hard-coded embedding field

- haystack/database/elasticsearch.py
> Increase timeout for Elasticsearch bulk indexing

- haystack/retriever/elasticsearch.py
> Fix device arg for sentence transformers

- haystack/api/application.py
- haystack/api/config.py
- haystack/api/controller/feedback.py
- haystack/api/controller/search.py
There was some configuration missing from the config.py to properly run the gunicorn API
> Missing PORT and SCHEME for elasticsearch to run the API

- README.rst
- haystack/finder.py
see https://github.com/deepset-ai/haystack/issues/144
> Typo fixes

- haystack/api/config.py
- haystack/api/controller/search.py
- haystack/database/elasticsearch.py
> Make FAQ question field customizable

- requirements.txt
- setup.py
> Fix for installing PyTorch on Windows OS

- haystack/reader/farm.py
> Adjust to farm handling of no answer

- rest_api/controller/file_upload.py
This PR adds directory creation(if not exists) for uploading files from the REST API.
> Create file upload directory in the REST API

- Dockerfile
I am not sure, but reading your codebase I have the feeling that you did some code refactoring recently. Here is a proposal to reflect that
> Fix rest api in Docker image after refactoring

- Dockerfile
- haystack/database/elasticsearch.py
- test/conftest.py
- test/test_farm_reader.py
- test/test_finder.py
- test/test_reader.py
Let's add more tests for the Reader and Finder - especially to test for breaking changes from transformers or FARM.
> Add more tests

- tutorials/Tutorial4_FAQ_style_QA.ipynb
> Fix embedding method in FAQ-QA Tutorial

- haystack/reader/transformers.py
Implementation discussed here: https://github.com/deepset-ai/haystack/issues/257
> Added support for unanswerable questions in TransformersReader

- rest_api/controller/search.py
> Modified search endpoints logs to dump json

- haystack/database/base.py
- haystack/database/elasticsearch.py
- haystack/retriever/dense.py
The effectiveness of this PR is discussed in #295.
Some information: 
1. I have seen that today it was integrated FAISS in Haystack. In the future, you can add the same support also in FAISS adapting the code for `update_embeddings` (i.e. [here](https://github.com/deepset-ai/haystack/blob/master/haystack/database/faiss.py#L103))
2. If this commit is not consistent with your PR in #273, feel free to change and adapt it with your new refactoring.
> Added title during DPR passage embedding && ElasticsearchDocumentStore

- .github/workflows/ci.yml
- README.rst
- haystack/indexing/file_converters/base.py
- haystack/indexing/file_converters/docx.py
- haystack/indexing/file_converters/pdf.py
- haystack/indexing/file_converters/tika.py
- haystack/indexing/file_converters/txt.py
- haystack/indexing/utils.py
- requirements.txt
- test/conftest.py
- test/test_docx_conversion.py
- test/test_pdf_conversion.py
Thank you for your contribution, @dany-nonstop (#306).
This PR adds support for file conversions using Apache Tika.
The `extract_pages()` for all file converters now optionally return the file meta, along with the pages.
> Add Tika Converter

- haystack/database/base.py
- test/test_db.py
- Add Tests for MultiLabel
- Fix bug in MultiLabel aggregation when 'no answer' is present
- Exclude Labels with `is_correct_answer=False` from MultiLabels
> Add Tests for MultiLabel

- haystack/database/elasticsearch.py
Addressing https://github.com/deepset-ai/haystack/issues/320
> Add refresh_type arg to ElasticsearchDocumentStore

- requirements.txt
- tutorials/Tutorial1_Basic_QA_Pipeline.ipynb
- tutorials/Tutorial2_Finetune_a_model_on_your_data.ipynb
- tutorials/Tutorial3_Basic_QA_Pipeline_without_Elasticsearch.ipynb
- tutorials/Tutorial4_FAQ_style_QA.ipynb
- tutorials/Tutorial5_Evaluation.ipynb
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
Bump FARM to 0.4.9. Remove custom torch installation from colab tutorials
> Bump FARM to 0.4.9

- docs/_src/usage/usage/reader.md
> Fix typo in documentation 

- docs/_src/usage/usage/database.md
- docs/_src/usage/usage/get_started.md
- docs/_src/usage/usage/reader.md
The website haystack.deepset.ai already have tabs but there are no nested tabs and the user can choose only one tab per page. I changed the tabs from links to radio buttons so that they are indpendet from each other. Moreover, there are nested tabs button. With the help of css, the radio buttons look like the tabs we had before. 
Fixing issues for respository haystack-website
> fixed tabs for haystack-website issues

- haystack/reader/farm.py
The PR updates ONNX conversion for the FARMReader as per https://github.com/deepset-ai/FARM/pull/557 (issue #419)
> Update ONNX conversion for FARMReader

- haystack/finder.py
- haystack/reader/farm.py
- haystack/retriever/base.py
This PR adds an option for Finder and Retriever evaluation to return the predictions when doing evaluation.
> Make returning predictions in evaluation possible

- haystack/retriever/dense.py
> Typo in dense.py comment

- Dockerfile
- Dockerfile-GPU
> Fix sentencepiece dependencies in Dockerfiles

- haystack/retriever/dense.py
- test/test_dpr_retriever.py
Fixes #542 .
This PR adds the methods `save_models()` and `load_models()` to the DensePassageRetriever.
> Add save and load method for DPR

- docs/_src/api/api/retriever.md
- haystack/retriever/dense.py
- haystack/retriever/sparse.py
> Added new formatting for examples in docstrings

- haystack/preprocessor/preprocessor.py
- test/test_preprocessor.py
> Add needed whitespace before sentence start

- rest_api/config.py
- rest_api/controller/search.py
> Fixing defaults configs for rest_apis

- README.md
- docs/_src/tutorials/tutorials/1.md
- docs/_src/tutorials/tutorials/2.md
- docs/_src/tutorials/tutorials/3.md
- docs/_src/tutorials/tutorials/4.md
- docs/_src/tutorials/tutorials/5.md
- docs/_src/tutorials/tutorials/6.md
- docs/_src/tutorials/tutorials/7.md
- docs/_src/tutorials/tutorials/headers.py
- docs/_src/usage/usage/document_store.md
- docs/_src/usage/usage/generator.md
- docs/_src/usage/usage/intro.md
- docs/_src/usage/usage/optimization.md
- docs/_src/usage/usage/preprocessing.md
- docs/_src/usage/usage/retriever.md
- docs/_src/usage/usage/terms.md
- docs/_src/usage/usage/use_cases.md
- tutorials/Tutorial7_RAG_Generator.ipynb
This PR updates the tutorial pages on the website and adds more details about generative QA.
New pages created:
tutorials/7.md
usage/generator.md
usage/optimization.md
> Make more changes to documentation

- README.md
Adding a badge for new and trending contributors to thank them publicly for their contributions.
> Add contributor hall of fame

- docs/_src/usage/usage/document_store.md
- docs/_src/usage/usage/domain_adaptation.md
- docs/_src/usage/usage/generator.md
- docs/_src/usage/usage/get_started.md
- docs/_src/usage/usage/reader.md
- docs/_src/usage/usage/retriever.md
@brandenchan Please feel free to add the boxes to all recommendations.
> Add boxes for recommendations

- docs/_src/api/api/document_store.md
- docs/_src/api/api/file_converter.md
- docs/_src/api/api/generator.md
- docs/_src/api/api/preprocessor.md
- docs/_src/api/api/reader.md
- docs/_src/api/api/retriever.md
This adds the API docs generated from the function doc strings.
> Update md files for API docs

- test/benchmarks/retriever.py
- test/benchmarks/run.py
- test/benchmarks/utils.py
> Fix benchmarks

- .github/workflows/ci.yml
- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/sql.py
- haystack/generator/base.py
- haystack/generator/transformers.py
- haystack/pipeline.py
- haystack/reader/base.py
- haystack/retriever/base.py
- haystack/retriever/dense.py
- haystack/retriever/sparse.py
- haystack/schema.py
- test/conftest.py
- test/pytest.ini
- test/test_db.py
- test/test_faiss.py
- test/test_generator.py
- test/test_pipeline.py
- tutorials/Tutorial7_RAG_Generator.ipynb
- tutorials/Tutorial7_RAG_Generator.py
> Add pipelines for GenerativeQA & FAQs

- haystack/pipeline.py
- haystack/reader/farm.py
- test/conftest.py
- test/test_reader.py
This PR adds a method to FARMReader to update parameters for an already loaded model.
> Enable dynamic parameter updates for the FARMReader

- docs/_src/tutorials/tutorials/2.md
- docs/_src/tutorials/tutorials/6.md
- tutorials/Tutorial2_Finetune_a_model_on_your_data.ipynb
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
Related to #654. Fixes broken links in tutorials
> Fix image links in tutorial

- haystack/generator/transformers.py
this PR is for #610 
adding RAGenerator support for GPU
> add gpu support for rag

- README.md
> Remove sourcerer.io widget

- Dockerfile-GPU
Installation of Scikit-learn was failing in the latest version.
> Fix GPU docker build

- docs/_src/api/api/preprocessor.md
- docs/_src/api/api/pydoc-markdown-document-store.yml
- docs/_src/api/api/pydoc-markdown-file-converters.yml
- docs/_src/api/api/pydoc-markdown-generator.yml
- docs/_src/api/api/pydoc-markdown-preprocessor.yml
- docs/_src/api/api/pydoc-markdown-reader.yml
- docs/_src/api/api/pydoc-markdown-retriever.yml
- docs/_src/usage/usage/preprocessing.md
- haystack/preprocessor/preprocessor.py
- test/test_preprocessor.py
- tutorials/Tutorial7_RAG_Generator.ipynb
- tutorials/Tutorial8_Preprocessing.ipynb
- tutorials/Tutorial8_Preprocessing.py
Add preprocessing tutorial ipynb and py file. Sample data is at s3 deepset.ai-farm-qa/datasets/documents/preprocessing_tutorial.zip. PreProcessor.split_stride renamed to PreProcessor.split_overlap
> Create Preprocessing Tutorial

- tutorials/Tutorial9_DPR_training.ipynb
- tutorials/Tutorial9_DPR_training.py
Add repo download in notebook
set train file
> Fix Tutorial 9 

- README.md
Let's add links to Slack, Twitter, Medium.
> Add links to more resources

- haystack/reader/farm.py
- haystack/retriever/dense.py
- haystack/summarizer/transformers.py
- requirements.txt
- test/test_dpr_retriever.py
This change will also increase transformers to 4.1.1
Increasing pytorch to 1.7.0
tests passing
Also tested several Tutorials:
2 - finetune model
5 - Evaluation
6 - DPR
7 - RAG
Did not check colab, should be good to go though.
> Increase FARM to Version 0.6.2

- haystack/document_store/sql.py
- test/test_document_store.py
> Add flag for use of window queries in SQLDocumentStore

- haystack/generator/transformers.py
> Remove RAG todos after transformers update

- docs/_src/tutorials/tutorials/1.md
- docs/_src/tutorials/tutorials/2.md
- docs/_src/tutorials/tutorials/3.md
- docs/_src/tutorials/tutorials/4.md
- docs/_src/tutorials/tutorials/5.md
- docs/_src/tutorials/tutorials/6.md
- docs/_src/tutorials/tutorials/7.md
- docs/_src/tutorials/tutorials/8.md
- docs/_src/tutorials/tutorials/9.md
- haystack/pipeline.py
- haystack/retriever/squad_to_dpr.py
- run_docker_gpu.sh
- tutorials/Tutorial1_Basic_QA_Pipeline.ipynb
- tutorials/Tutorial1_Basic_QA_Pipeline.py
- tutorials/Tutorial2_Finetune_a_model_on_your_data.ipynb
- tutorials/Tutorial3_Basic_QA_Pipeline_without_Elasticsearch.ipynb
- tutorials/Tutorial3_Basic_QA_Pipeline_without_Elasticsearch.py
- tutorials/Tutorial4_FAQ_style_QA.ipynb
- tutorials/Tutorial4_FAQ_style_QA.py
- tutorials/Tutorial5_Evaluation.ipynb
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
- tutorials/Tutorial6_Better_Retrieval_via_DPR.py
- tutorials/Tutorial7_RAG_Generator.ipynb
- tutorials/Tutorial7_RAG_Generator.py
- tutorials/Tutorial8_Preprocessing.ipynb
- tutorials/Tutorial9_DPR_training.ipynb
> Update tutorials (torch versions, ES version, replace Finder with Pipeline)

- haystack/preprocessor/preprocessor.py
Hello,
I implemented a fix as discussed in #842. 
The preprocessor should be working even in the mode offline.
> fix download ntlk preprocessor

- annotation_tool/docker-compose.yml
This is the fix for data persistence issue. Please review and take it forward.
> Annotation Tool: data is not persisted when using local version #853

- haystack/connector/crawler.py
- haystack/pipeline.py
- haystack/preprocessor/utils.py
- haystack/retriever/squad_to_dpr.py
- haystack/utils.py
Fix error when is_impossible not is_impossible and json dump encoding in multilingual data
Fixing #867
> Fix error when is_impossible not is_impossible and json dump encoding error

- haystack/connector/crawler.py
- haystack/document_store/base.py
- haystack/file_converter/base.py
- haystack/generator/base.py
- haystack/preprocessor/base.py
- haystack/reader/base.py
- haystack/retriever/base.py
- haystack/schema.py
- haystack/summarizer/base.py
Let's make it a bit clearer what a custom node in a pipeline must implement.
Even though the signature for run() changes depending on the type of node ...
> Add abstract run method to basecomponent

- .github/workflows/ci.yml
- README.md
- docs/_src/api/api/file_converter.md
- haystack/file_converter/__init__.py
- haystack/file_converter/base.py
- haystack/file_converter/docx.py
- haystack/file_converter/markdown.py
- haystack/file_converter/pdf.py
- haystack/file_converter/tika.py
- haystack/file_converter/txt.py
- requirements-dev.txt
- requirements.txt
- test/samples/markdown/sample.md
- test/test_file_converter.py
- To deliver #668 
- Adding extra requirements-dev.txt for tests and dev testing dependencies
> Add Markdown file convertor

- docs/_src/api/api/retriever.md
- haystack/reader/farm.py
default val of 1 was preventing batching
fixes #915
> Better default value for mp chunksize

- docs/v0.7.0/_src/usage/usage/pipelines.md
No big deal: Fixing inconsistency between pipe and p in the doc
> Fixing inconsistency

- rest_api/application.py
- rest_api/config.py
Following my feature suggestion, I created a PR to illustrate what i meant
> adding root_path option

- haystack/retriever/dense.py
Add maxsamples and convert data dir to path
fixes #985
> DPR Training parameter

- docs/_src/tutorials/tutorials/11.md
- docs/_src/tutorials/tutorials/headers.py
Add header and generate md file for Tutorial 11 on Pipelines
> Add tutorial pages

- docs/_src/api/api/document_store.md
- docs/_src/api/api/graph_retriever.md
- docs/_src/api/api/knowledge_graph.md
- docs/_src/api/api/pipelines.md
- docs/_src/api/api/retriever.md
Regenerate api docs so they can be inspected on our staging website
> Regen api docs

- .github/workflows/ci.yml
- requirements.txt
CI was failing lately because of mismatch between Milvus python SDK (1.1) and docker image (1.0)
`E           milvus.client.exceptions.VersionError: Version of python SDK(1.1.0) not match that of server1.0.0, excepted is ('1.1.x',)
`
> Upgrade milvus to 1.1.0

- haystack/document_store/elasticsearch.py
- haystack/document_store/faiss.py
- haystack/document_store/memory.py
- haystack/document_store/milvus.py
- haystack/retriever/dense.py
- test/test_document_store.py
…the overall documents progress closed #1037
- ...
> Improve the progress bar in update_embeddings() + Fix filters in update_embeddings() 

- Dockerfile
- Dockerfile-GPU
- Add requirements for PDF converter in Docker images
Timo edit: fixes #1094
> Add PDF converter dependencies Docker

- haystack/pipeline.py
save_to_yaml() was failing for pipelines with a JoinDocuments Node as it had no pipeline_config attribute.
Also renamed top_k to top_k_join to conform with other parts in haystack
> Add config to JoinDocuments node to allow yaml export in pipelines

- docs/_src/api/api/document_store.md
- docs/_src/api/api/evaluation.md
- docs/_src/api/api/reader.md
Manually trigger a refresh of API documentation to reflect the latest changes in the docstrings.
> Refresh API docs

- .github/workflows/ci.yml
- haystack/retriever/dense.py
To fix https://github.com/deepset-ai/haystack/issues/1161
> Fixing issues caused due to mypy upgrade

- .github/workflows/ci.yml
- docs/_src/usage/usage/faq.md
- haystack/retriever/dense.py
Adds an FAQ page to the documentation website.
> Add FAQ page

- .github/workflows/ci.yml
- docs/_src/usage/usage/document_store.md
- docs/_src/usage/usage/languages.md
- docs/_src/usage/usage/optimization.md
- docs/_src/usage/usage/pipelines.md
- haystack/retriever/dense.py
A range of general documentation updates that come from #992
> Documentation update

- docs/_src/usage/usage/document_store.md
- Super minor change, but in line with other DocumentStore's
> Minor change with a link to the Weaviate docs

- haystack/pipeline.py
Simple typo fix which I noticed today.
> FIx typo in Query Classifier Exception Message

- setup.py
increased haystack version to 0.9.0
> Increase Haystack version

- haystack/preprocessor/preprocessor.py
> Add PreProcessor optional language parameter.

- rest_api/controller/search.py
- ui/Dockerfile
- ui/webapp.py
-  top_k_reader and top_k_retriever are now passed correctly in API requests
- minor changes and documentation in UI 
> Small UI and REST API fixes

- tutorials/Tutorial11_Pipelines.py
As in all other tutorials, we would like to encapsulate the code of tutorial 11 in a method to prevent problems with parallelization and forking. See earlier PR for other tutorials: https://github.com/deepset-ai/haystack/pull/729
> Encapsulate tutorial code in method

- haystack/connector/crawler.py
> Serialize crawler output to JSON

- tutorials/Tutorial2_Finetune_a_model_on_your_data.ipynb
- tutorials/Tutorial2_Finetune_a_model_on_your_data.py
- tutorials/Tutorial5_Evaluation.ipynb
- tutorials/Tutorial5_Evaluation.py
> Change variable names in tutorials

- .github/workflows/ci.yml
- docs/_src/usage/usage/document_store.md
> bump Weaviate version to 1.5

- rest_api/application.py
> Add Header in sample REST API Search Request

- haystack/summarizer/transformers.py
-  I added the `truncation=True` parameter which is supported by the pipeline module.
> Transformer summarizer truncation bug fixed 

- README.md
Just noticed the readme wasn't updated for the new tutorial by @brandenchan, while I was adding my tutorial
> Update README.md for tutorial 13 Question Generation 

- tutorials/Tutorial1_Basic_QA_Pipeline.py
-  Tutorial1 remove finder class from import
> Tutorial1 remove finder class from import

- annotation_tool/README.md
- docs/_src/usage/usage/annotation.md
Fixes #1332
- Let's add the annotation tool FAQ here so that users can find it more easily. 
> Add faq annotation

- docs/_src/usage/usage/document_store.md
> Bump Weaviate version

- haystack/eval.py
Added link to arxiv paper to doc string on evaluation with new SAS metric
> Add link to arxiv paper on SAS

- test/test_connector.py
-  Add test cases for the Crawler module  #fixes 
closes #1283
> Add tests for Crawler

- docs/_src/tutorials/tutorials/1.md
- docs/_src/tutorials/tutorials/11.md
- docs/_src/tutorials/tutorials/2.md
- docs/_src/tutorials/tutorials/3.md
- docs/_src/tutorials/tutorials/4.md
- docs/_src/tutorials/tutorials/5.md
- docs/_src/tutorials/tutorials/6.md
- docs/_src/tutorials/tutorials/8.md
- I updated the tutorials to the latest version. At the moment, there is no automation for that. But we will resolve this issue with the upcoming new docs website
> updated tutorials

- docs/_src/tutorials/tutorials/13.md
- docs/_src/tutorials/tutorials/14.md
- docs/_src/tutorials/tutorials/headers.py
- Adding tutorials 13 and 14 to the docs
> Adding tutorial 13 and 14

- haystack/connector/crawler.py
- haystack/pipeline.py
- test/test_connector.py
- Add Crawler support for index pipeline 
closes #1322
> Add Crawler support for indexing pipeline 

- docs/_src/usage/usage/query_classifier.md
Adding usage docs to resolve #1155 
> Add query classifier usage docs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/question.md
- README.md
- docs/README.md
- haystack/connector/crawler.py
- haystack/eval.py
- haystack/pipeline.py
- test/samples/markdown/sample.md
- test/test_connector.py
- ui/README.md
- ui/webapp.py
- We implemented a new docs website and added new processes. Therefore we changed the documentation
> Editing docs read.me for new docs website workflow

- haystack/document_store/elasticsearch.py
-  Catch Elastic's search_phase_execution_exception exception and raise with a descriptive message.
closes #1135
>  Catch Elastic's search_phase_execution and raise with descriptive message.

- docs/_src/api/api/crawler.md
> crawler api docs updated.

- .github/workflows/ci.yml
- Dockerfile
- README.md
- haystack/file_converter/__init__.py
- haystack/file_converter/base.py
- haystack/file_converter/image.py
- haystack/file_converter/pdf.py
- haystack/file_converter/tika.py
- requirements.txt
- test/test_file_converter.py
Initial draft of module `image.py` with class `ImageToTextConverter` to resolve #1248 
Hi @tholor, please take a look and let me know how it looks. I will also add `PDFToImageConverter` in `pdf.py`.
> Add ImageToTextConverter and PDFToTextOCRConverter that utilize OCR

- haystack/file_converter/image.py
- Seems that the CI in the PR #1349  was showing green even though not all stages were executed. Fixing the remaining issues here..
FYI @shahrukhx01
> Fix CI (introduced by OCR PR #1349)

- tutorials/Tutorial4_FAQ_style_QA.ipynb
- tutorials/Tutorial4_FAQ_style_QA.py
Updating the Sentence Retriever model used in FAQ tutorial as suggested by Nils Reimers
> Update sentence transformer model in FAQ tutorial

- .github/workflows/ci.yml
- README.md
- docs/_src/usage/usage/document_store.md
- requirements.txt
- Bumped Weaviate to the latest version
> Bump Weaviate version to 1.7.0

- rest_api/controller/search.py
Fix handling of `None` value for `filters`
> Fix handling of filters in Search REST API

- haystack/pipeline.py
Sometimes you just want to access a loaded component in the current pipeline (e.g. documentstore) but you don't know the name of the node.
> QoL function: access certain nodes in pipeline

- haystack/connector/crawler.py
- rest_api/controller/search.py
- `crawler()` module on capable of running in an environment where `google-chrome` could be installed. This PR aims at making `crawler()` usable in google colab as well by adding a small usecase for google colab. 
For more info see: https://github.com/deepset-ai/haystack/discussions/1420#discussioncomment-1311135
> Added functionality for Google Colab usecase in Crawler Module

- haystack/document_store/faiss.py
- test/test_faiss_and_milvus.py
- This modifies the faiss document store so that it supports cosine as a similarity metric
- changes are discussed in #1337 
> feat: normalize embeddings for faiss cosine similarity

- haystack/document_store/faiss.py
- test/test_faiss_and_milvus.py
Fix #135 inaccuracy in FAISS config file path handling
> Fix bug when loading FAISS from supplied config file path

- rest_api/application.py
- rest_api/controller/document.py
- rest_api/controller/feedback.py
- rest_api/controller/search.py
- test/test_rest_api.py
Related to #1546
-----------
Fix a circular import accidentally introduced in #1546 and not immediately detected by running with Uvicorn.
> Fix circular import in the REST API

- haystack/retriever/dense.py
This PR fixes #1507 Although the tests pass, I'd love first to test it in demos as well, and in the meantime, it would be great hear your thoughts @julian-risch 
> LFQA: Remove InferenceProcessor dependency

- docs/_src/tutorials/tutorials/15.md
- tutorials/Tutorial15_TableQA.ipynb
Great tutorial! 👍 Just spotted a small typo during the demo.
> fixed typo

- haystack/nodes/retriever/dense.py
- check if model is an instance of DataParallel, in case it is call the method via `model.module` else use current call
> fix issue #1687 - DPR training fails on multiple GPU's

- docs/_src/api/api/document_classifier.md
- docs/_src/tutorials/tutorials/15.md
- docs/_src/tutorials/tutorials/16.md
- docs/_src/tutorials/tutorials/headers.py
- haystack/nodes/document_classifier/base.py
- haystack/nodes/document_classifier/transformers.py
- haystack/nodes/file_classifier/file_type.py
- test/conftest.py
- test/samples/pipeline/test_pipeline.yaml
- test/test_document_classifier.py
- test/test_pipeline.py
- tutorials/Tutorial16_Document_Classifier_at_Index_Time.ipynb
- tutorials/Tutorial16_Document_Classifier_at_Index_Time.py
- Introduce new Tutorial: Tutorial16_Document_Classifier_at_Index_Time
- Show how to integrate DocumentClassifier in preprocessing logic
- Show how to query dynamically added classification results at query time
- Extend DocumentClassifier for batch_size
- Make DocumentClassifier ready for indexing pipelines
Closes https://github.com/deepset-ai/haystack/issues/1281
> Tutorial for DocumentClassifier at Index Time

- haystack/modeling/evaluation/eval.py
- haystack/modeling/utils.py
- tutorials/Tutorial5_Evaluation.ipynb
- tutorials/Tutorial5_Evaluation.py
Fixes #1732 
Introduced by #1683
> Fix another self.device/s typo

- docs/_src/api/api/document_classifier.md
- docs/_src/api/api/evaluation.md
- docs/_src/api/api/pipelines.md
- docs/_src/api/api/primitives.md
- docs/_src/api/api/query_classifier.md
- docs/_src/api/api/question_generator.md
- docs/_src/api/api/ranker.md
- haystack/pipelines/base.py
- haystack/pipelines/standard_pipelines.py
- haystack/schema.py
- test/test_pipeline_extractive_qa.py
- introduce eval() method on Pipeline
- push eval output to dataframe by using debug flag of pipeline.run()
- introduce EvaluationResult class for load and save mechanisms
- make eval() support multiple queries and labels
closes #1711
> Multi query eval

- .github/workflows/windows_ci.yml
- exclude test_summarizer_translation.py for windows_ci as it takes to much memory
> Exclude test_summarizer_translation.py for windows_ci

- ui/eval_labels_example.csv
- ui/webapp.py
and add three example questions related to the countries dataset.
Current UI:
> Improve the Random Question functionality

- ui/eval_labels_example.csv
- ui/webapp.py
Changes:
- Add a description box below the title. The description is a bit of a placeholder, should be reviewed later. 
- Restores the Retriever's default doc number to 3 
- Changes the no-answer boxes to light blue 
- Changes the default question
Merge only when #1810 can be merged as well.
> Add description to the demo

- haystack/document_stores/sql.py
- test/test_faiss_and_milvus.py
An issue with the JOIN statements in the `_query` method was creating wrong queries in case of several filters present in the request. This PR fixes the `_query` method by aliasing the many JOIN condition.
The query will go from the current state:
```sql
SELECT document.id, document.content, document.vector_id 
FROM document 
JOIN meta_document ON document.id = meta_document.document_id 
WHERE document.index = 'haystack_test' AND 
meta_document.name = 'month' AND 
meta_document.value IN ('01') AND 
document.id = meta_document.document_id AND 
meta_document.name = 'year' AND 
meta_document.value IN ('2020') AND 
document.id = meta_document.document_id
```
to this:
```sql
SELECT document.id, document.content, document.vector_id 
FROM document 
JOIN meta_document AS meta_document_1 ON …
```
> Allow SQLDocumentStore to filter by many filters

- .github/release.yml
- Group PRs by labels in auto-generated release notes
> Add config for github release notes

- .github/release.yml
- Adjust categories in release notes
> Extend categories for release notes

- .github/workflows/demo.yaml
- .github/workflows/demo/docker-compose.demo.yml
- .github/workflows/demo/ec2-autoscaling-group.yaml
- docker-compose-gpu.yml
- docker-compose.yml
- ui/utils.py
- ui/webapp.py
- Add `Demo` workflow to deploy it
- Add CloudFormation template to manage an Autoscaling Group that takes care of the rolling deployment of new EC2 instances
> Deploy demo

- rest_api/application.py
The REST API had an old version. Let's bump it to 1.0
> Bump version in REST api

- .github/workflows/demo.yaml
- .github/workflows/demo/ec2-autoscaling-group.yaml
- Fix wrong deployment branch and repo pointing to fork
- Show deployment progress with CloudFormation stack events
- Send EC2 instance logs to CloudWatch
> Fix demo deployment

- docs/_src/tutorials/tutorials/11.md
- docs/_src/tutorials/tutorials/6.md
- tutorials/Tutorial11_Pipelines.ipynb
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
- Updated tutorials 6 and 11, called to print_answers called with details="minimum", the was a typo and details="minimal" was being used.
- Linked with issue Wrong argument for print_answers in tutorials 6 and 11 (notebooks) #1882
> NOTE: it seems there are a lot of changes in the notebooks but in fact is just "minimal" > "minimum"
> Exchanged minimal with minimum in print_answers function call

- haystack/utils/export_utils.py
- Improved version of `print_answers` to solve issue #1887 
- [x ] Updated documentation - *no documentation changes required*
> Improved version of print_answers

- docs/README.md
I just added a missing "r" to the word "contributions" at the "Overview and Usage" section. I skipped many of the steps for submitting a PR as it was just a small typo. Thanks
- Self-contained in the pull request. It is literally just one missing character :)
- [ X] Updated documentation
> Minor typo

- haystack/document_stores/elasticsearch.py
- raise exception if one of the specified `search_fields` in `ElasticsearchDocumentStore` has not the correct datatype
**Background**:
Search fields for fulltext search must be of type 'text' for elastic search/open search. Otherwise no results will be returned and no exception occurs. This is especially a problem if you migrate from haystack pre-1.0 to haystack 1.0:
In haystack pre 1.0 the default search_field was called `text`. All other fields were defaulted to the 'keyword' type. In haystack 1.0 we renamed the default search_field to `content`.
If a pre-1.0 index is not explicitly deleted by calling `CURL -X DELETE`, the mapping will stay the same. If you now try to insert new documents with haystack 1.0 their content will be indexed as default type 'keyword' …
> Raise exception if Elasticsearch search_fields have wrong datatype

- .github/workflows/linux_ci.yml
- .github/workflows/windows_ci.yml
- docs/_src/api/api/file_converter.md
- haystack/nodes/__init__.py
- haystack/nodes/file_converter/__init__.py
- haystack/nodes/file_converter/azure.py
- haystack/nodes/file_converter/base.py
- haystack/nodes/file_converter/image.py
- haystack/nodes/file_converter/parsr.py
- haystack/nodes/file_converter/pdf.py
- haystack/nodes/file_converter/tika.py
- haystack/nodes/file_converter/txt.py
- test/test_file_converter.py
This PR adds a file converter based on the open-source Parsr tool by axa-group capable of extracting text and tables. Given a file (PDF or DOCX), it will return a list of dicts containing one dict for each table detected in the file and one dict containing the text of the file.
Closes #1858
> Add ParsrConverter

- .github/workflows/docker_build.yml
- Dockerfile-GPU
This PR adds Docker Build for the GPU Image as a GitHub Action.
For each commit on the master branch, a new Image with the commit hash as tag gets created.
> Add GitHub Action for Docker Build for GPU

- docs/_src/tutorials/tutorials/15.md
- tutorials/Tutorial15_TableQA.ipynb
-  It took me a bit of time debugging before I've realized there are hardcoded variables in the tutorial 15 :)
> Remove hard-coded variables from the Tutorial 15

- docs/_src/tutorials/tutorials/5.md
- tutorials/Tutorial5_Evaluation.ipynb
- tutorials/Tutorial5_Evaluation.py
- Calculate pipeline eval report additionally based on label input
- Corresponding PR to update the guide on the docs website is here: https://github.com/deepset-ai/haystack-website/pull/228
closes https://github.com/deepset-ai/haystack/issues/1849
> Extend Tutorial 5 with Upper Bound Reader Eval Metrics

- docs/_src/tutorials/tutorials/2.md
- haystack/utils/augment_squad.py
- test/test_utils.py
- tutorials/Tutorial2_Finetune_a_model_on_your_data.ipynb
- tutorials/Tutorial2_Finetune_a_model_on_your_data.py
This adds model distillation to the finetuning tutorial as discussed in deepset-ai/haystack-website#231.
> Add distillation to finetuning tutorial

- docs/_src/api/api/primitives.md
- haystack/schema.py
- add ndcg as metric to docs
- add eval_mode as dataframe column to docs
- reorder dataframe columns in docs
> Add ndcg and eval_mode to docs

- tutorials/Tutorial7_RAG_Generator.ipynb
- tutorials/Tutorial7_RAG_Generator.py
- Small fix because tutorial 7 was not working with the "new" Answer class
> fix answer is not subscriptable error

- haystack/document_stores/faiss.py
- pass batch_size to SQLDocumentStore
> pass faiss batch_size to sqldocumentstore

- docs/_src/api/api/generator.md
- haystack/nodes/answer_generator/base.py
- haystack/nodes/answer_generator/transformers.py
- test/test_generator.py
- return proper `Answer` objects in `Seq2SeqGenerator`
fixes https://github.com/deepset-ai/haystack/issues/2094
> Fix Seq2SeqGenerator return type

- .github/workflows/linux_ci.yml
It was accidentally removed in #2117
> Reintroduce push on master trigger for Linux CI

- docs/_src/api/api/pipelines.md
- haystack/pipelines/base.py
- fix type annotation so that `documents` can be a List of None
> fix type annotation

- docs/_src/api/api/pipelines.md
- haystack/pipelines/base.py
- test/test_pipeline.py
> Fix typo in save_to_deepset_cloud()

- .github/utils/generate_json_schema.py
- docs/_src/api/api/pipelines.md
- docs/_src/api/openapi/openapi.json
- haystack/pipelines/base.py
- json-schemas/haystack-pipeline-1.1.0.schema.json
- rest_api/pipeline/pipeline_empty.yaml
- rest_api/pipeline/pipelines.yaml
- rest_api/pipeline/pipelines_dpr.yaml
- rest_api/test/samples/pipeline/test_pipeline.yaml
- rest_api/test/samples/pipeline/test_pipeline_faiss_indexing.yaml
- rest_api/test/samples/pipeline/test_pipeline_faiss_retrieval.yaml
- rest_api/test/samples/pipeline/test_pipeline_tfidfretriever.yaml
- test/samples/pipeline/test_pipeline.yaml
- test/samples/pipeline/test_pipeline_faiss_indexing.yaml
- test/samples/pipeline/test_pipeline_faiss_retrieval.yaml
- test/samples/pipeline/test_pipeline_tfidfretriever.yaml
- test/test_pipeline.py
- Make YAML files get the same version as Haystack when saved with `save_to_yaml()` 
- Throw a warning in `load_from_yaml()` in case of mismatch (no error will be thrown)
- Update tests and test pipeline YAMLs to comply
Closes #2042
> YAML versioning

- docs/_src/tutorials/tutorials/6.md
- tutorials/Tutorial6_Better_Retrieval_via_DPR.ipynb
- Milvus cannot be started within a Colab notebook. Therefore we comment out the Milvus cell in Tutorial6, not to break the execution flow on Colab.
- We decided not to delete it, as a reference for people running locally.
> Comment out Milvus cell on Tutorial6

- haystack/pipelines/utils.py
- json-schemas/haystack-pipeline-1.2.1rc0.schema.json
- fix `Pipeline.print_eval_report
> Fix `Pipeline.print_eval_report`

- docs/_src/api/api/other.md
- docs/_src/api/pydoc/other.yml
Added two new node names to the other.yml file do document the api of JoinAnswers and RouteDocuments.
> Update other.yml with new node names

- docs/_src/tutorials/tutorials/11.md
- tutorials/Tutorial11_Pipelines.ipynb
- added URL to ipynb to point to images in img-folder
> ipynb: inserted links to graph images

- setup.cfg
- add jsonschema dependency to core dependencies
- remove duplicate azure-core restriction
> Fix install because of missing jsonschema dependency

- haystack/document_stores/elasticsearch.py
> Using default OpenSearch parameters

- haystack/telemetry.py
- disable unnecessary telemetry logs
fixes https://github.com/deepset-ai/haystack/issues/2405
> Disable telemetry logs per default

- haystack/document_stores/pinecone.py
- Modified metric check for "dot_product" to convert to "dotproduct" to solve problem noted in #2493 
closes #2493
> fix dot_product metric

- docs/_src/tutorials/tutorials/4.md
- docs/_src/tutorials/tutorials/7.md
- docs/_src/tutorials/tutorials/8.md
- tutorials/Tutorial4_FAQ_style_QA.ipynb
- tutorials/Tutorial7_RAG_Generator.ipynb
- tutorials/Tutorial7_RAG_Generator.py
- tutorials/Tutorial8_Preprocessing.ipynb
This PR fixes some minor bugs in Tutorials 4, 7 and 8 which prevent the notebooks from running smoothly on colab.
> Fix tutorials 4, 7 and 8

- .github/workflows/autoformat.yml
- .github/workflows/linux_ci.yml
- .github/workflows/windows_ci.yml
- setup.cfg
This PR upgrades the torch version from 1.10 to 1.11.
closes #2371
> Upgrade torch version to 1.11

- docs/_src/api/api/document_store.md
- haystack/document_stores/deepsetcloud.py
- haystack/nodes/base.py
- haystack/utils/__init__.py
- haystack/utils/reflection.py
- test/pipelines/test_pipeline.py
- replace exceptions with warnings in write operations
- log input of write operations
closes https://github.com/deepset-ai/haystack/issues/2472
> Warnings for write operations of `DeepsetCloudDocumentStore`

- docs/_src/api/api/pipelines.md
- haystack/pipelines/ray.py
> Update Ray pipeline docs with validation info

- haystack/modeling/model/language_model.py
> Minor lg updates to doc strings

- haystack/document_stores/faiss.py
- haystack/document_stores/milvus1.py
- haystack/document_stores/milvus2.py
- haystack/modeling/data_handler/data_silo.py
- haystack/modeling/evaluation/metrics.py
- haystack/modeling/model/optimization.py
- haystack/modeling/model/prediction_head.py
- haystack/modeling/model/tokenization.py
- haystack/modeling/utils.py
- haystack/nodes/evaluator/evaluator.py
- haystack/nodes/file_converter/parsr.py
- haystack/pipelines/base.py
- haystack/schema.py
- haystack/utils/squad_to_dpr.py
- pyproject.toml
**Problem**:
- Due to an upgrade of PyLint, a few new errors were added and we observed them failing in some points of our codebase
**Solution**:
- This PR fixes the issues where detected and disables the errors in the few spots where it does not make sense
**Notes**:
- `unnecessary-lambda-assignment` would need a second look. At the moment it seems to trigger on very legit uses of lambdas, where I disabled it. To be seen: if it becomes too annoying we should disable it globally.
> Fix new PyLint errors

- haystack/schema.py
- Create target folder if not exists in EvalResult.save()
> Create target folder if not exists in EvalResult.save()

- docs/_src/api/api/retriever.md
- haystack/nodes/label_generator/pseudo_label_generator.py
- haystack/nodes/retriever/_embedding_encoder.py
> Update docstrings for GPL

- docs/_src/api/api/pseudo_label_generator.md
- docs/_src/api/pydoc/pseudo-label-generator.yml
- haystack/json-schemas/haystack-pipeline-master.schema.json
- haystack/nodes/label_generator/pseudo_label_generator.py
- test/nodes/test_label_generator.py
Add GPL API docs, increase default GPL batch size and update unit tests
> Add GPL API docs, unit tests update

- setup.cfg
- Upgrade transformers dependency to latest release: https://github.com/huggingface/transformers/releases/tag/v4.20.0
> Upgrade transformers to 4.20.0

- docs/_src/tutorials/tutorials/14.md
- setup.py
- For some reason the bot did not apply doc changes to the recent Tutorial 14 PR (#2663), and it's now spamming other unrelated PRs with those changes.
- This PR will merge these changes and stop the bot from spamming.
> Tutorial 14 doc changes

- haystack/nodes/connector/crawler.py
- test/nodes/test_connector.py
https://github.com/SeleniumHQ/selenium/blob/557141504199308ddac51131803ff53fe7204915/py/CHANGES#L2
> Replace deprecated Selenium methods

- README.md
This PR adds the links to Tutorials 16, 17 and 18 to the README file.
> Add Tutorials 16, 17 and 18 to README

- haystack/nodes/answer_generator/openai.py
- Adjust doc strings to adhere to the Haystack documentation style
> Clean OpenAIAnswerGenerator docstrings

- haystack/pipelines/base.py
**Related Issue(s)**:
- fixes Tutorial15 crash
- fixes calculation of context_similarity for table documents
- convert dataframes to string before calculating context similarity
> Fix gold_contexts_similarity for table retrieval evaluation

- test/mocks/pinecone.py
**Related Issue(s)**:  #2646 
- Switch mock pinecone client to use dict structure for indexing rather than list, when using a list the "replace by default" behavior of pinecone during `write_documents` is not replicated. This is less obvious with the first Pinecone document store implementation, but becomes a problem with the proposed upgrade #2749
> changed mock pinecone to use dict rather than list index

- haystack/modeling/evaluation/eval.py
**Related Issue(s)**:  Closes #2885
- Fix parameters mismatch in `eval.py`
> Add switch for `BiAdaptive` and `TriAdaptiveModel` in `Evaluator`

- .github/workflows/tests.yml
Speed up integration tests by downloading all larger models before tests being run
> Add HF model caching for integration tests

- haystack/nodes/connector/crawler.py
- setup.cfg
**Related Issue(s)**:  Issue #2920 
- Update minimum requirements in setup.cfg
- Change how the error is raised when running the crawler in google colab so the trace is more obvious
> Update minimum selenium version supported for crawler

- docs/_src/api/api/document_classifier.md
- docs/_src/api/api/query_classifier.md
- docs/_src/api/api/question_generator.md
- docs/_src/api/api/ranker.md
- docs/_src/api/api/reader.md
- docs/_src/api/api/summarizer.md
- haystack/json-schemas/haystack-pipeline-master.schema.json
- haystack/nodes/document_classifier/transformers.py
- haystack/nodes/extractor/entity.py
- haystack/nodes/query_classifier/transformers.py
- haystack/nodes/question_generator/question_generator.py
- haystack/nodes/ranker/sentence_transformers.py
- haystack/nodes/reader/transformers.py
- haystack/nodes/summarizer/transformers.py
**Related Issue(s)**: 
https://github.com/deepset-ai/haystack/issues/2954
https://github.com/deepset-ai/haystack/issues/2580
Fixes https://github.com/deepset-ai/haystack/issues/2954 as we have 2+ components that raise CUDA out of memory error if batch_size is not specified. For consistency, let's convert all batch_size Optional component constructor parameters to 16.
See https://github.com/deepset-ai/haystack/issues/2954 for more details and rationale
> Component batch_size  should be defined rather than Optional

- docs/_src/api/api/ranker.md
- haystack/nodes/ranker/sentence_transformers.py
**Related Issue(s)**:  Fixes #2683
- Remove pipes from code block
> Remove pipes from code block

- ui/setup.py
- fixes vulnerability found by dependabot
- Bump streamlit to 1.11.1
- Relax the version constraint in `setup.py` to include subsequent minors
Tested locally on OSX
> Bump streamlit version to latest

- haystack/utils/deepsetcloud.py
- test/others/test_utils.py
Adds `delete_all_files()` to `FileClient` in deepsetcloud module
Unit test was added.
should be a no-brainer
> feat: Add `delete_all_files()` to `FileClient`

- docs/_src/api/api/summarizer.md
- haystack/nodes/summarizer/base.py
- Fixes https://github.com/deepset-ai/haystack-website/issues/380
Change mention of `Document.text` to `Document.content`
> Update Summarizer Docs

- docs/_src/api/api/file_classifier.md
- haystack/nodes/file_classifier/file_type.py
- First raised in #2999
- Change docstring to reflect the fact that there is now no limit on outgoing edges in BaseComponent.
- Markdown file generated
> docs: update File Classifier Docstring

- CONTRIBUTING.md
- README.md
Simply updating the readme to say 'Discord' instead of Slack :)
> changing Slack to Discord

- docs/_src/api/api/generator.md
- docs/_src/api/pydoc/answer-generator.yml
- docs/v1.7.0/_src/api/pydoc/answer-generator.yml
- haystack/nodes/answer_generator/openai.py
- Adds OpenAI AnswerGenerator to API docs
> Add OpenAI Answer Generator API

- CONTRIBUTING.md
- related to #2811
Add to the dev docs the outcome of #2811
Ideally, newly added tests will follow those requirements while we progressively adapt the existing tests to the new model.
> docs: add tests types to CONTRIBUTING.md

- .github/workflows/tests.yml
- related to #3219 
- Temporary disable ES Windows test and Windows integration tests
- CI
- Let's remove such tasks from the list of mandatory tasks, or no PR will be mergeable after this one.
> chore: disable Windows ES tests on CI

- haystack/json-schemas/haystack-pipeline-1.10.0rc0.schema.json
- fixes detected schema discrepancy
> Fix schema for 1.10.x

- .github/workflows/black.yml
- .github/workflows/docker_release.yml
- .github/workflows/readme_integration.yml
- .github/workflows/schemas.yml
- .github/workflows/tests.yml
We want to test every push to a release branch
> Run checks on release branches

- .github/workflows/docker_release.yml
Leftover from the testing phase
Tested in the release branch
> fix: remove debug step from job

- test/benchmarks/README.md
- Addresses remaining review comments from https://github.com/deepset-ai/haystack/pull/2766
> docs: improve readability of benchmarks readme

- .github/workflows/docker_release.yml
- docker/README.md
- docker/docker-bake.hcl
- fixes n/a
Build the new Docker images for both amd64 and arm64 architectures
- Local build
- Images available here https://hub.docker.com/repository/docker/deepset/haystack/tags?page=1&ordering=last_updated&name=massi
- The `target "docker-metadata-action"` was removed because a leftover from an old Github action setup
> feat: add multi-platform Docker images

- Dockerfile
- Dockerfile-GPU
- Dockerfile-GPU-minimal
- n/a
Add a comment to the old dockerfiles so that users can be redirected to the new ones
No tests needed
> chore: add deprecation notice to the old dockerfiles

- docker-compose.yml
- docker/Dockerfile.demo-es
- ui/Dockerfile
- ui/webapp.py
- fixes n/a
- Fix Streamlit errors
- Simplify the ui Dockerfile
- Use the newer Haystack image
- Add an health check to avoid errors while Elasticsearch is booting
- Simplify the docker-compose file
- Tested locally on Apple M1 Pro
> fix: demo won't start through Docker compose

- .pre-commit-config.yaml
- haystack/json-schemas/haystack-pipeline-1.10.0rc0.schema.json
- haystack/json-schemas/haystack-pipeline-main.schema.json
- haystack/nodes/_json_schema.py
- fixes #3334
- Sort the keys of the schema before writing it to file
- Add pre-commit hook that verifies that keys are sorted
- Manually
- This change might not pass CI right away. We might need to disable the schema check temporarily.
-  ~I added tests that demonstrate the correct behavior of the change~
-  ~I documented my code~
> fix: stable YAML schema generation

- docs/_src/api/pydoc/retriever.yml
- Generate API docs for the Multimodal Retriever
- Manually generated API docs locally
> docs: Add multimodal retrieval to API docs

- .github/workflows/tests.yml
- haystack/errors.py
- haystack/nodes/retriever/_embedding_encoder.py
- haystack/nodes/retriever/dense.py
- test/conftest.py
- test/nodes/test_retriever.py
- partially fixes #3306 
- fixes https://github.com/deepset-ai/haystack/issues/3423
Added CohereEmbeddingEncoder as a method to create document and query embeddings.
Added unit tests, the same tests used to test OpenAI embeddings
See if we need more unit tests
> feat: Add CohereEmbeddingEncoder to EmbeddingRetriever

- README.md
> fix: fix docs badge

- .github/workflows/docker_release.yml
- n/a
Adjust the pattern matching with the right syntax
Already ported to 1.10.x and used it for the release
> fix: pattern to match tags push

- Dockerfile-GPU-minimal
- fixes https://github.com/deepset-ai/haystack/actions/runs/3345231800/jobs/5540497483
Rearrange the build in a way that works
Local build
Not sure which one of my changes actually fixed the build but I didn't change any upstream dependency so we should be good
> fix docker minimal deprecated image

- .github/workflows/project.yml
- fixes n/a
Add a workflow that adds new issues to the GH project
not tested here
> add workflow to triage new issues with GH projects

- .github/workflows/project.yml
- fixes n/a
Use a dedicated Personal Access Token, scoped down to project-level permissions
> Use a dedicated PAT

- .github/workflows/demo.yaml
- Remove the `push` directive from the demo deployment workflow file.
> Deploy the demo only manually

- .github/utils/pydoc-markdown.sh
- docs/_src/api/pydoc/document-store.yml
- fixes https://github.com/deepset-ai/haystack/actions/runs/3468881451
- adjust `milvus` package name
- ran the script locally
- Added a clean up step that's useful when running the script locally
> CI: fix milvus imports in docs generator

- haystack/nodes/__init__.py
- haystack/nodes/other/__init__.py
- haystack/pipelines/__init__.py
- enable class imports
-  `from haystack.nodes import DocumentMerger`
- `from haystack.pipelines import TextIndexingPipeline`
- Manually tested
> feat: Update DocumentMerger and TextIndexingPipeline imports

- .github/labeler.yml
- .github/workflows/labeler.yml
- fixes n/a
Add a labeler job, for now only used for `Proposal`s
> CI: add labeler to the repo

- pyproject.toml
- fixes https://github.com/deepset-ai/haystack-tutorials/issues/76
Pin `pillow` when running in Colab (issue only happens there)
Manual test pip-installing this branch from Colab
I removed the pin to `requests` as it seems it's not needed anymore
> fix: revamp `colab` extra dependencies

- haystack/nodes/summarizer/transformers.py
> fixing the url for document merger

- haystack/nodes/query_classifier/sklearn.py
- part of #2904
Running the `SklearnQueryClassifier` model with a version of scikit-learn>1.0.2 raises this error:
`AttributeError: 'GradientBoostingClassifier' object has no attribute '_loss'`
Studying a bit the [scikit-learn code](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/ensemble/_gb.py), I see that we can easily monkey patch the missing attribute as a **temporary** solution.
Manual test
> fix: monkey patch for `SklearnQueryClassifier`

- pyproject.toml
- fixes #3631 
- Remove the `test` extra
- Adjust `all` extras accordingly
- Local install
- CI
n/a
> refactor: remove `test` extra

- haystack/nodes/retriever/multimodal/retriever.py
This is a test to check if the API docs are properly updated (the documents seem up to date but the log is empty).
> chore: fix log

- proposals/text/3665-prompt-node.md
- Proposes a fix for  #3306
This feature proposes adding PromptNode wrapping an LLM to be used in the Haystack ecosystem.
N/A
See attached issues and the colab notebook for the high-fidelity version of this proposal.
> proposal: Add PromptNode based on LLM

- .github/workflows/readme_sync.yml
Updated the rdme action version to the latest one.
> Update the readme action version

- haystack/modeling/data_handler/processor.py
- haystack/modeling/infer.py
- fixes #3093
In #3093, we have seen that the `EmbeddingRetriever` is not thread safe. The `EmbeddingRetriever` uses the `InferenceProcessor` which caused the problem. The problem was that the processed queries were appended to the instance variable `self.baskets` which was shared among the threads.
This PR removes `self.baskets` and instead introduces a local variable `baskets` to the `dataset_from_dicts` method of the `TextClassificationProcessor`. (We do this already in every other `Processor`!)
I tested this manually using the script provided in #3093. I tested both running the rest API directly with `gunicorn` and running a docker container. 
I inspected the content of [`samples`](https://github.com/deepset-ai/haystack/blob/f24cbdbb5d9c71c8e0a264ccfcb72d4257e66946/haystack/modeling/in …
> fix: Make `InferenceProcessor` thread safe

- .github/workflows/compliance.yml
- Unblocks https://github.com/deepset-ai/haystack/pull/3764#issuecomment-1374872280
Fix the conditional logic used to skip jobs when running from forks.
Tested in https://github.com/deepset-ai/haystack/pull/3764#issuecomment-1374874692
> CI: fix `if` clause in job skip logic

- haystack/document_stores/faiss.py
There was a number of questions from the community about how the load&save methods work for FAISS.
More explicit documentation for init, save, and load. Added links to the guide as well.
> Docs: Update FAISSDocStore load and save descriptions

- .github/pull_request_template.md
- fixes n/a
List the commit types in the PR template itself to ease adoption
> docs: list conventional commit types in the PR template

- proposals/text/3784-input-output-shaper.md
- proposals/text/3784-shaper.md
Add a proposal for InputOutputShaper, aka Shaper pipeline component needed to make the PromptNode work more flexibly. 
N/A
N/A
> proposal: Shaper pipeline component

- test/conftest.py
- test/others/test_utils.py
- extracted from #3697
- Add the version deprecation fixture for future use
- See the usage example in the docstring
- unit test
n/a
> test: add version deprecation fixture

- haystack/nodes/prompt/prompt_node.py
No related issue, small code refactoring regarding the resolution of PromptTemplates in PromptNode
This refactoring simplifies PromptNode's central prompt method by pushing the template substitution to PromtTemplate, where it, one can argue, belongs. PromptNode main loop is thus simplified and easier to understand.  
No additional tests were added, PromptNode already has substantial unit test coverage
Please scrutinize every line of code
> refactor: Simplify PromptTemplate substitution in PromptNode

- haystack/document_stores/base.py
- haystack/document_stores/pinecone.py
- haystack/modeling/infer.py
- haystack/modeling/model/triadaptive_model.py
- haystack/nodes/reader/farm.py
- haystack/schema.py
- haystack/utils/labels.py
n/a
- Enables `singleton-comparison`'s PyLint error
- Fix a few offending lines (`variable == True/False/None` instead of `variable is True/False/None`)
CI
n/a
> chore: enable `singleton-comparison` and cleanup

- haystack/document_stores/opensearch.py
- issue noted in Discord: https://discord.com/channels/993534733298450452/993539071815200889/1066576199352070175
- Update `OpensearchDocumentStore` docstring: `AWS Elasticsearch Service --> Amazon OpenSearch Service` 
n/a
n/a
~I added tests that demonstrate the correct behavior of the change~
> docs: `OpensearchDocumentStore` docstring

- test/modeling/test_distillation.py
- test/nodes/test_prompt_node.py
> fix: change model in distillation test

- haystack/nodes/image_to_text/base.py
- haystack/nodes/image_to_text/transformers.py
Update the language in doc strings.
> Docs: Update ImageToText docstrings

- .github/workflows/docker_release.yml
Fixes failing CI like [this case](https://github.com/deepset-ai/haystack/actions/runs/4022916642/jobs/6913176453).
> ci: Fix docker image testing on release

- docs/_src/api/pydoc/transformers-img-to-text.yml
- fixes [#3996](https://github.com/deepset-ai/haystack/pull/3966)
Fixed the quotation marks
- [x ] I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_conduct.txt)
> Fix: Fix quotation marks

- .github/labeler.yml
- fixes n/a
Assign labels to PRs automatically based on the files in the changeset
not tested
This also contains a fix for the label `proposal` that were wrongly listed as `Proposal` with a capital P
> chore: add `topic:*` labels automatically whenever possible

- .github/utils/pydoc-markdown.sh
- .gitignore
- docs/pydoc/config/answer-generator.yml
- docs/pydoc/config/crawler.yml
- docs/pydoc/config/document-classifier.yml
- docs/pydoc/config/document-store.yml
- docs/pydoc/config/evaluation.yml
- docs/pydoc/config/extractor.yml
- docs/pydoc/config/file-classifier.yml
- docs/pydoc/config/file-converters.yml
- docs/pydoc/config/other.yml
- docs/pydoc/config/pipelines.yml
- docs/pydoc/config/preprocessor.yml
- docs/pydoc/config/primitives.yml
- docs/pydoc/config/prompt-node.yml
- docs/pydoc/config/pseudo-label-generator.yml
- docs/pydoc/config/query-classifier.yml
- docs/pydoc/config/question-generator.yml
- docs/pydoc/config/ranker.yml
- docs/pydoc/config/reader.yml
- docs/pydoc/config/retriever.yml
- docs/pydoc/config/summarizer.yml
- docs/pydoc/config/transformers-img-to-text.yml
- docs/pydoc/config/translator.yml
- docs/pydoc/config/utils.yml
- fixes https://github.com/deepset-ai/haystack/actions/runs/4075568183
Fix the docs build and make more obvious the layout for the files needed to build api docs
locally run the docs build script
> chore: re-organize pydoc config files

- .github/workflows/rest_api_tests.yml
- .github/workflows/tests.yml
Disable the `tests.yml` workflow if no `*.py` or `pyproject.toml` file has been modified in PR.
This approach would require to disable all required jobs in `tests.yml` otherwise PRs will be stuck. 
My initial idea was to keep the required checks but skip them using the [official documented approach](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks) like in #4046. 
In this case since most jobs use the matrix strategy, that would mean creating a pretty long list of jobs with the same name that are run then `tests.yml` is skipped. This would make the CI harder to maintaing since adding a new test job would mean …
> ci: Make tests run conditionally in CI

- docs/_src/api/pydoc/other.yml
> Add shaper api

- docs/pydoc/config/other.yml
> Docs: Add shaper to api docs

- docker/Dockerfile.base
- fixes #4089 
Removed torchaudio dependency after confirming it will work with dC.
Have not but as mentioned, confirmed with dC.
> fix: fix torchaudio version

- haystack/nodes/prompt/prompt_node.py
Updated docstrings to make them easier to understand.
> Docs: Update docstrings

- haystack/nodes/prompt/prompt_node.py
- test/nodes/test_prompt_node.py
- fixes broken PromptTemplate unit tests (affected after docs update)
Let's have CI do a complete run
Updated existing tests to reflect the docs changes
> Update PromptTemplate unit tests

- .github/workflows/docker_release.yml
Remove unnecessary commas in bash script that tests Docker images.
See failure [here](https://github.com/deepset-ai/haystack/actions/runs/4145963401/jobs/7171030050).
N/A
> ci: Fix Docker images test on release

- docs/pydoc/config/extractor.yml
Mentioned here: https://github.com/deepset-ai/haystack/pull/4132
Added a filter to the yaml config to hide the _EntityPostProcessor class
I didn't
- [ x] I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_conduct.txt)
- [x ] I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.
> Docs: Add filter to hide entity post processor

- haystack/nodes/prompt/prompt_node.py
> Docs: Update top_k description for PromptNode

- .github/workflows/linting.yml
- haystack/nodes/prompt/prompt_node.py
- fixes https://github.com/deepset-ai/haystack/pull/4224 was merged with failing tests
> fix: apply black formatting

- test/nodes/test_summarizer.py
- fixes failing builds on `main`
Skip the tests while we find a solution
> test: skip summarizer tests to reduce pressure on the CI

- .github/workflows/tests.yml
- test/agents/test_agent.py
- n/a 
Run the tests according to the new structure (unit / integration)
CI
> test: fix agents tests

- haystack/environment.py
- n/a
A typo was found in the detection of the `google.colab` package by the telemetry code. This PR fixes the typo.
n/a
n/a
> bug: fix typo in `google.colab` package detection

- proposals/text/4084-agent-demo.md
- is a part of https://github.com/deepset-ai/haystack/issues/3753 epic
Adds a proposal for the agent demo app. Some fine details are intentionally omitted not to constrict the final version reached via proposal comments and discussion.  Even if we make a pivot regarding the final demo, the components proposed in this agent demo are most likely to be required regardless. 
No tests were required.
N/A
> proposal: Implement Agent demo

- test/nodes/test_prompt_node.py
- fixes [unit tests failing on HF failure](https://github.com/deepset-ai/haystack/actions/runs/4283763790/jobs/7459850655) (unit test should not rely on external services)
Mark the failing test as `integration`
CI
> fix: mark test correctly

- .github/workflows/openapi_sync.yml
- haystack/agents/base.py
- haystack/nodes/prompt/prompt_node.py
- test/agents/test_agent.py
While testing the new Agent for a use case I had in mind, my agent failed after the first step because it could not identify the tool + tool input from the output the Agent generated. 
Key issues: 
- It was hard to understand initially why the agent failed 
- Using the default prompt template, the agent produced `Tool: [Some Name], Tool Info: Some instructions for my node` => The default `tool_pattern` didn't find any match and therefore failed to extract the relevant info for the next step
- Adding a more descriptive error message if the agent fails to detect Tool + Tool input
- Adjusting the prompt template to avoid the LLM producing brackets "[ ]" around the tool name 
- Restricting the name for a tool to letters,digits,underscores (so that it's compliant with the default …
> refactor: Make extraction of "Tool" and "Tool input" more robust and user-friendly 

- haystack/nodes/answer_generator/openai.py
- haystack/nodes/prompt/prompt_node.py
- test/conftest.py
- test/nodes/test_generator.py
- test/nodes/test_prompt_node.py
- fixes #3890 
Add Azure as OpenAI endpoint for PromptNode and OpenAIAnswerGenerator
Waiting for credentials so we can test it
Don't review yet, this PR needs credentials setup
> feat: Add Azure as OpenAI endpoint

- README.md
- Add Intelijus as one of the companies who use Haystack
Previously discussed with @TuanaCelik
> chore: Add Intelijus as using Haystack

- haystack/nodes/prompt/prompt_node.py
- haystack/nodes/prompt/providers.py
- test/nodes/test_prompt_node.py
- n/a
- Improves the detection and loading of new `PromptModelInvocationLayer`s
PromptNode tests.
> refactor: simplify registration of `PromptModelInvocationLayer`

- haystack/document_stores/sql.py
- haystack/nodes/file_converter/azure.py
- haystack/utils/export_utils.py
- test/nodes/test_reader.py
- fixes failures on main related to hf-tiny-roberta model and mypy issues on everyone's local
cc: @silvanocerza 
integration tests are already in place
I know this is an ugly way to fix two unrelated issues but it will unblock everyone much faster.
> fix: hf-tiny-roberta model loading from disk and mypy errors

- haystack/nodes/retriever/web.py
> refactor: minor WebRetriever improvements

- haystack/environment.py
- fixes n/a
Avoid `is_containerized` to return `None`
Make the detection process a bit more robust and avoid returning `None`
Locally tested mounting the source tree into docker containers and running the code manually
> feat: improve is_containerized()

- docs/pydoc/config/agent.yml
> Docs: Fix order and category of agent

- docs/pydoc/config/agent.yml
> Docs: Fix agent module

- test/prompt/test_prompt_node.py
> fix: Update test to reflect change in max token length

- haystack/agents/base.py
- haystack/agents/types.py
- haystack/agents/utils.py
- haystack/nodes/prompt/prompt_node.py
- pyproject.toml
- no assigned issue, part of the agent UX improvements (token streaming, logging)
Adds agent event emission and handling using the events library
Manually verified that agent stream logging works
> feat:Add agent event callbacks

- docs/pydoc/config/whisper.yml
https://github.com/deepset-ai/haystack/pull/4335
Adds WhisperTranscriber API docs
> Docs: Add whisper api

- .github/workflows/docker_release.yml
> fix: do not override bake's platform definitions

- .github/config/failure-message-slack-payload.json
- .github/workflows/compliance.yml
- .github/workflows/examples-tests.yml
- .github/workflows/rest_api_tests.yml
- .github/workflows/tests.yml
Fix the formatting of messages sent to Slack when job fail in CI.
Can't be tested really.
N/A
> ci: Fix Slack messages formatting on job failure

- annotation_tool/README.md
- annotation_tool/docker-compose.yml
The new Docker Image `deepset/haystack-annotation:latest` has updated the config variables.
> fix: update envs for the backend image of annotation tool

- haystack/nodes/other/shaper.py
> Docs: Shaper API update

- docker/Dockerfile.xpdf
- fixes n/a
Pin the Ubuntu version we use to build `xpdf` for better compatibility
> build xpdf on bionic

- README.md
We just noticed a missing emoji with Silvano :D
> chore: Adding missing emoji

- haystack/nodes/question_generator/question_generator.py
- haystack/nodes/summarizer/transformers.py
- fixes #3606 and #4525
Added descriptions to missing QuestionGenerator params.
Updated the lg of Summarizer docstrings.
Please pay special attention to whether I documented the missing QG params correctly.
- [x ] I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.
> Docs: Fix QuestionGenerator and Summarizer docstrings

- haystack/nodes/prompt/invocation_layer/chatgpt.py
- haystack/nodes/prompt/prompt_model.py
> feat: support for gpt-4

- docs/pydoc/config/pipelines.yml
- docs/pydoc/config/prompt-node.yml
- docs/pydoc/config/whisper.yml
- haystack/agents/base.py
- haystack/agents/utils.py
- haystack/errors.py
- haystack/nodes/prompt/invocation_layer/__init__.py
- haystack/nodes/prompt/invocation_layer/hugging_face.py
- haystack/nodes/prompt/invocation_layer/hugging_face_inference.py
- test/agents/test_agent.py
- test/conftest.py
- no related issue
Proposed Changes:
Adds HFInferenceEndpointInvocationLayer as PromptModelInvocationLayer implementation for the support of: 
- [HF Inferencing API](https://huggingface.co/docs/api-inference/index)
- [HF Inferencing](https://huggingface.co/inference-endpoints) deployed models (all text2text-generation and text-generation models)
HF Inferencing API is free to use with HF token and is rate-limited. However, it is still useful for our users. Some useful and capable instruction following models are kept warm and ready for use i.e. https://huggingface.co/google/flan-t5-xxl
How did you test it?
No tests have been added yet; unit tests and documentation are coming soon
To test this model, you must invoke the HF inferencing API or HF inferencing deployed model. I'll provide you …
> feat: Add Hugging Face inferencing PromptNode layer 

- haystack/preview/__init__.py
- test/preview/pipeline/test_pipeline.py
n/a
- Make Haystack compatible with [the latest Canals](https://pypi.org/project/canals/0.0.2/)
- CI
n/a
> refactor: `node->component`

- README.md
Adding another name in our 'who uses' section
> chore: Updating readme

- haystack/nodes/prompt/invocation_layer/__init__.py
- haystack/nodes/prompt/invocation_layer/azure_chatgpt.py
- haystack/nodes/prompt/prompt_model.py
- fixes #4517
Add an Invocation Layer to allow the use of Azure AI Chat GPT Endpoints
with the following code
```python
from haystack.nodes import PromptNode, PromptModel
import os
api_key = os.environ.get("AZURE_API_KEY")
deployment_name = os.environ.get("AZURE_DEPLOYMENT_NAME")
base_url = os.environ.get("AZURE_BASE_URL")
azure_chat = PromptModel(
model_name_or_path="gpt-35-turbo",
api_key=api_key
model_kwargs={
"azure_deployment_name": deployment_name,
"azure_base_url": base_url,
},
)
prompt_node = PromptNode(
azure_chat,
)
messages = []
messages.append(
{
"role": "system",
"content": "You are an AI assistant that helps people find information.",
}
)
def build_chat(user_input: str = "", system_input: str = ""):
if user_input != "":
messages.append({"role": "user", "content": …
```
> feat: Add AzureChatGPT Capability using new InvocationLayer style

- haystack/utils/openai_utils.py
- Fixes #4738 4738
Just force the tokenizer if the model is `gpt-35-turbo` basically.
This is currently in open PR with Tiktoken, but it's been sat there for a while: https://github.com/openai/tiktoken/pull/72
> fix: Tiktoken does not support Azure gpt-35-turbo

- .github/workflows/tests.yml
- fixes n/a, came up in PR #4691 
This PR adds `pipelines` and `utils` to the unit-test test suite in our CI.
Tested via CI: https://github.com/deepset-ai/haystack/actions/runs/4795994633/jobs/8535488471
> ci: Execute pipelines and utils unit tests in CI

- haystack/document_stores/base.py
- haystack/document_stores/graphdb.py
- haystack/document_stores/memory_knowledgegraph.py
- haystack/nodes/retriever/text2sparql.py
- fixes #4552
Add deprecation notes to API docs, follow-up of #4500
> docs: add deprecation notes to docstrings

- README.md
- pyproject.toml
- test/nodes/test_image_to_text.py
- test/pipelines/test_eval.py
- test/pipelines/test_eval_batch.py
- No issue
Let's upgrade to transformers [4.28.0](https://github.com/huggingface/transformers/releases/tag/v4.28.0), see how CI goes, if we have some strange errors etc.
No tests needed
N/A
> Upgrade transformers to 4.28.1

- test/agents/test_agent.py
- no related issue
Makes the test easier to pass, 10/10 runs green
Slightly changed unit test
N/A
> refactor: Make agent test more robust

- .github/workflows/tests.yml
- .gitignore
- pyproject.toml
Add steps to track unit tests coverage using Coveralls.
Can't really test without running CI.
I formatted the `tests.yml` with the first commit.
> ci: Add coverage tracking with Coveralls

- test/nodes/test_generator.py
- Adding leftover Deprecation tests from #4745
> chore: Added deprecation tests for seq2seq generator and RAG Generator

- haystack/preview/pipeline.py
- test/preview/pipeline/test_pipeline.py
Update `preview.Pipelines` to reflect changes in [deepset-ai/canals](https://github.com/deepset-ai/canals/).
I ran tests locally with new `canals` version.
N/A
> feat: Update preview Pipelines following Canals changes

- .github/workflows/imports.yml
- fixes https://github.com/deepset-ai/haystack/issues/4844
- Adds a matrix to `imports.yml` running the base-install task on ubuntu, macos and windows
- CI
n/a
> ci: check that base install succeeds on all platforms

- docs/pydoc/config/pipelines.yml
- docs/pydoc/config/prompt-node.yml
> docs: fix Prompt_Node and Pipelines API reference

- test/preview/components/base.py
- n/a
- Add base test class for v2 Components
- Just a tiny wrapper on top of Canals', adding the requests mock.
n/a
n/a
> Add base test class for v2 Components

- test/nodes/test_shaper.py
- fixes n/a
Add a test case for the fix introduced with #4929 
Unit test
I didn't know how to test it when I first reviewed #4929 but I wanted to ship the fix as fast as possible. Completing the job with this PR.
> add test case for #4929

- pyproject.toml
- fixes build on `main` branch until https://github.com/weaviate/weaviate-python-client/issues/333 is fixed
> Pin Weaviate client

- haystack/nodes/search_engine/web.py
Corrected spelling and added GoogleAPI
> docstrings update in web.py 

- README.md
Adding our retrieval augmentation demo to the readme: https://huggingface.co/spaces/deepset/retrieval-augmentation-svb
> Add retrieval augmentation demo to readme

- .github/workflows/rest_api_tests.yml
- .github/workflows/tests.yml
Fix Datadog event handling added with #4957.
Example workflow failures:
* https://github.com/deepset-ai/haystack/actions/runs/5024394593/jobs/9010069558
* https://github.com/deepset-ai/haystack/actions/runs/5024394587/jobs/9010069879
> ci: Fix step failing to calculate Datadog event type

- .github/workflows/examples-tests.yml
Add event sending for examples tests as we did for other tests in #4957.
> ci: Add Datadog event send in examples tests workflow

- test/document_stores/test_weaviate.py
> test: leftover from merge conflict

- .github/labeler.yml
- .github/release.yml
- .github/workflows/cml.yml
- .github/workflows/e2e.yml
- CONTRIBUTING.md
- docs/pydoc/config/document-store.yml
- docs/pydoc/config/retriever.yml
- pyproject.toml
- test/conftest.py
- fixes docs build
https://github.com/deepset-ai/haystack/pull/4953 wasn't complete, with this PR we remove the leftovers, fixing the docs build.
Manually built docs locally
> chore: leftovers from removing knowledge graph support

- docs/pydoc/config/file-converters.yml
- fixes docs build https://github.com/deepset-ai/haystack/actions/runs/5058939625/jobs/9079764369
> fix: remove old dependency from file-converters.yml

- .github/workflows/license_compliance.yml
- n/a 
Send events instead of posting slack messages
Not tested
> ci: track license compliance failures with Datadog

- .github/workflows/license_compliance.yml
- fixes https://github.com/deepset-ai/haystack/actions/runs/5080334934/jobs/9127163533 due to the output of the license checker somehow containing text that's not ok for the Event body
- the old body message said "failed" and that was wrong anyways, since we always send the event, whether it failed or succeeded
> ci: fix Datadog event body

- .github/pull_request_template.md
Change checklist to simple list in Pull Requests template has it was never used properly by anyone.
No need to test this.
N/A
> chore: Change checklist to simple list in PR template 

- pyproject.toml
- fixes #5075
- pin generalimport
- n/a
n/a
> fix: pin `generalimport`

- .github/workflows/docker_release.yml
> revert fix: change the Docker workflow runner

- pyproject.toml
- None
- Upgrade transformers to most recent release (9th of June) https://github.com/huggingface/transformers/releases/tag/v4.30.1
~~Let's see whether CI tests pass~~ -> CI tests pass. I haven't run any local tests.
The two main features of the release that are relevant to us are:
* 4-bit quantization for loading large models https://github.com/huggingface/transformers/pull/23479
* Prompts are now hosted on the Hub https://github.com/huggingface/transformers/pull/23662
- …
> build: Upgrade transformers to v4.30.1

- test/prompt/test_prompt_node.py
- fixes #4561
Skip a flaky test.
There's nothing to test.
Supersedes #4697.
> test: Skip flaky PromptNode test

- haystack/utils/openai_utils.py
Creating another PR due to issus with CLA on last one
- fixes #5143
Increase max token count when 16k models used.
Manual tests. 
N/A …
> fix: increase max token length for openai 16k models

- haystack/utils/openai_utils.py
- test/utils/test_openai_utils.py
- fixes #5103
The fallback to gpt2 can now be used again in the intended way
Waiting for CI
> fix: model_tokenizer in  openai text completion tokenization details

- haystack/preview/components/retrievers/memory.py
- haystack/preview/document_stores/memory/document_store.py
- test/preview/components/retrievers/test_memory_retriever.py
- test/preview/document_stores/test_memory.py
**What?**
* This PR introduces two new components: `MemoryDocumentStore` and `MemoryRetriever` in the Haystack preview.
* MemoryDocumentStore is a class that manages the in-memory storage of documents. It supports the BM25 retrieval algorithm and can store documents with content type as text or table.
* MemoryRetriever is a component that utilizes a MemoryDocumentStore to retrieve the most relevant documents based on a given query.
* These classes serve as components for the in-memory `Document` retrieval approach using the BM25 algorithm.
**Why?** 
As the preview part of the project grows we need a lightweight, in-memory document store and retriever to bootstrap the migration process to nextgen Haystack. 
Unit tests were written for each method of the MemoryDocumentStore and …
> feat: BM25 retrieval for `MemoryDocumentStore`

- docs/pydoc/config/agent.yml
> docs: update Agent API reference to include memory classes

- haystack/document_stores/elasticsearch/es7.py
- haystack/document_stores/elasticsearch/es8.py
- test/document_stores/test_elasticsearch.py
- follow up of https://github.com/deepset-ai/haystack/pull/5231
Make method static and clarify init comments …
> refactor: fix method type and add comments

- pyproject.toml
- temporarily fixes multiple failures in multiple places
> Pin pydantic to 1.x

- haystack/nodes/retriever/dense.py
- fixes N/A
Added some missing docstrings (e.g. for `headers`) and fixed some grammatical mistakes.
> docs: Small documentation updates to dense.py

- .github/labeler.yml
- n/a
This PR updates the `labeler.yml` file to account for the changes made when we added support for Elasticsearch 8.
> ci: Update labeler.yml to account for Elasticsearch changes

- haystack/modeling/training/base.py
> chore: fix typo in base.py

- haystack/preview/__init__.py
- haystack/preview/document_stores/__init__.py
- haystack/preview/document_stores/decorator.py
- haystack/preview/document_stores/memory/document_store.py
- haystack/preview/document_stores/mixins.py
- haystack/preview/document_stores/protocols.py
- haystack/preview/pipeline.py
- test/preview/components/retrievers/test_memory_retriever.py
- test/preview/pipeline/test_pipeline.py
Fixes #5433
Add a `@store` decorator to add `Store`s to a registry to ease save and loading `Pipeline`s from file.
The decorator also adds a `__haystack_store__` field to ease runtime checks when using `Store`s.
This also makes the `@runtime_checkable` `Store` decorator redundant so I removed it.
I ran all preview tests.
I don't think new tests are required as of now as the decorator only adds classes to a registry.
If there are issues with registering new `Store`s in the future we'd find out cause saving and loading `Pipeline`s from file will fail. 
I removed the `Store` protocol `runtime_checkable` decorator as `@store` adds a `__haystack_store__` field and that's faster to check.
I'm debating whether we should remove the `Store` Protocol in favor of enforcing the checks using the …
> feat: Add @store decorator

- rest_api/rest_api/controller/file_upload.py
- rest_api/test/test_rest_api.py
- n/a
Currently the `rest_api` keeps the original files that were uploaded after the indexing step. Under the most common use cases, those files are not used anymore after being indexed, filling up the filesystem. This has proven particularly annoying in Docker environments, forcing users to work around the problem by manually cleaning the upload directory.
To keep the original behaviour availble, a new query param called `keep_files` was introduced. The param defaults to the new behaviour, hence the breaking change.
Unit tests …
> feat!: remove original files after indexing

- rest_api/rest_api/controller/document.py
- rest_api/rest_api/controller/feedback.py
- rest_api/test/test_rest_api.py
- fixes #5443
Added optional index parameter with default None value to all the relevant endpoints.
using curl command to send requests.
> feat: add optional index selection for endpoints

- .github/workflows/tests.yml
- .github/workflows/tests_skipper.yml
Skip triggering `tests.yml` when editing Python files in `docs` folder since there are no related tests for them.
No need to test this.
N/A …
> chore: Skip running tests in CI when editing docs Python files

- README.md
Let's emphasize a bit the installation instructions for running local inference. Together with "choosing a specific vector DB", I expect this to be the most common "non-default" installation people need.   …
> docs: update installation instructions in README.md

- docs/pydoc/config/agent.yml
- haystack/agents/conversational.py
* Fix agent.yml after adding new modules
* Update ConversationalAgent docstrings
I built md files locally
N/A
> Fix Agent API

- haystack/nodes/prompt/invocation_layer/hugging_face.py
Updating docstrings up to the standard.
> docs: update docstrings in HF invocation layer

- haystack/document_stores/filter_utils.py
- haystack/modeling/evaluation/metrics.py
- haystack/nodes/doc_language_classifier/langdetect.py
- haystack/nodes/file_converter/base.py
- haystack/nodes/file_converter/docx.py
- haystack/nodes/file_converter/tika.py
- haystack/nodes/preprocessor/preprocessor.py
- haystack/utils/context_matching.py
- fixes n/a
- Replaces more custom optional imports with `LazyImport`.
CI
Large PR in files count, but it's all about replacing imports. Any other change should be pointed out. …
> chore: normalize more optional imports

- haystack/preview/testing/factory.py
- releasenotes/notes/store-factory-91e7da46aeb7ff21.yaml
- test/preview/testing/test_factory.py
Add a utility function to create custom `Store`s for testing purposes.
N/A
> Add Store class factory

- docker/README.md
Updates docker readme file to account for new inferencing images. Please check the wording is clear and precise.
- fixes #5533
> feat: Update Docker readme

- docs/pydoc/config/ranker.yml
Added cohere ranker module to the config file.
> Fix: Add cohere ranker api

- haystack/preview/__init__.py
- haystack/preview/dataclasses/__init__.py
- haystack/preview/dataclasses/answer.py
- releasenotes/notes/add-v2-answer-class-31bc8d3116922594.yaml
- adds Answer class from #5553 
Adds three classes: Answer, ExtractiveAnswer, GenerativeAnswer
It might be confusing to have so many classes and fields called answer. …
> Add Answer class

- examples/web_lfqa_with_rankers.py
Update example name and questions
> fix: Rename web_lfqa_improved example and update questions

- releasenotes/notes/remove-document-store-aware-mixin-8eef714844ee04f2.yaml
Fix release notes on `DocumentStoreAwareMixin`.
N/A
N/A
> Fix release notes 

- pyproject.toml
- releasenotes/notes/bump-transformers-to-4-32-341a42ff09796725.yaml
Upgrade transformers to the most recent release https://github.com/huggingface/transformers/releases/tag/v4.32.0
Let's see whether CI tests pass
Some features of the release that can be relevant to us are:
- GPTQ quantization 
- full integration of MPT models
- I …
> build: upgrade Transformers to 4.32.0

- releasenotes/notes/remove-template-vars-invocation-kwargs-060f186fd1250fe4.yaml
Updates release note for #5526. Please verify if it clearly identifies affected users and provides a path about addressing the changes required.
> chore: Update release note for #5526

- haystack/preview/components/audio/whisper_remote.py
- test/preview/components/audio/test_whisper_remote.py
- See https://github.com/deepset-ai/haystack/pull/5647 for all the context.
- Serialization methods for `RemoteWhisperTranscriber` …
> chore: serialization methods for `RemoteWhisperTranscriber`

- .github/workflows/e2e.yml
- e2e/pipelines/test_pipeline_topologies.py
- e2e/pipelines/test_standard_pipelines.py
- e2e/samples/pipelines/test.haystack-pipeline.yml
- fixes https://github.com/deepset-ai/haystack/actions/runs/6018856046/job/16327780836
- Fixes several smaller errors in the e2e tests
CI
n/a …
> test: fix e2e test failures

- proposals/text/3558-embedding_retriever.md
To avoid confusion, add a reference to the more recent embedders proposal
> Update 3558-embedding_retriever.md, link to the new embedders proposal

- .github/workflows/linting.yml
* https://github.com/actions/checkout/releases
* https://github.com/tj-actions/changed-files/releases …
> ci: linting.yml: Upgrade GitHub Actions

- .github/workflows/benchmarks.yml
- .github/workflows/docker_release.yml
- .github/workflows/docstring_labeler.yml
- .github/workflows/e2e.yml
- .github/workflows/examples_tests.yml
- .github/workflows/imports.yml
- .github/workflows/license_compliance.yml
- .github/workflows/minor_version_release.yml
- .github/workflows/openapi_sync.yml
- .github/workflows/project.yml
- .github/workflows/pypi_release.yml
- .github/workflows/readme_sync.yml
- .github/workflows/release_notes.yml
- .github/workflows/rest_api_tests.yml
- .github/workflows/stale.yml
- .github/workflows/tests.yml
- .github/workflows/workflows_linting.yml
- .github/workflows/xpdf_release.yml
1. [act10ns/slack@v2](https://github.com/act10ns/slack/releases)
2. [actions/add-to-project@v0.5.0](https://github.com/actions/add-to-project/releases)
3. [actions/checkout@v4](https://github.com/actions/checkout/releases)
4. [actions/labeler@v4](https://github.com/actions/labeler/releases)
5. [actions/setup-python@v4](https://github.com/actions/setup-python/releases)
6. [actions/stale@v8](https://github.com/actions/stale/releases)
7. [actions/upload-artifact@v3](https://github.com/actions/upload-artifact/releases)
8. [coverallsapp/github-action@v2](https://github.com/coverallsapp/github-action/releases)
9. [docker/bake-action@v4](https://github.com/docker/bake-action/releases)
10. [docker/login-action@v3](https://github.com/docker/login-action/releases)
11. …
> ci: Upgrade GitHub Actions

- haystack/nodes/retriever/_openai_encoder.py
- haystack/utils/openai_utils.py
- pyproject.toml
- releasenotes/upgrade-tiktoken-0.5.1-3cea9bf90fddb2f2.yaml
Undoes https://github.com/deepset-ai/haystack/pull/5774.
See https://github.com/openai/tiktoken/blob/main/CHANGELOG.md#v051 and https://github.com/openai/tiktoken/issues/193
> Use newer tiktoken

- .github/workflows/e2e.yml
- fixes https://github.com/deepset-ai/haystack/actions/runs/6179109209/job/16788317566?pr=5803
> ci: run apt-get update

- .github/workflows/tests.yml
- n/a
This PR adds the preview integration tests to the CI.
> ci: Run preview integration tests in CI

- .github/workflows/tests.yml
> fix: add missing dependency in preview integration

- proposals/text/0000-evaluation-haystack-2.md
- proposals/text/0000-evaluation-haystack-2.py
This PR introduces a new proposal to define at an high level how evaluation and metrics calculation should work in the upcoming Haystack version 2.x.
> Rework evaluation and metrics calculation for Haystack 2.x

- .github/workflows/examples_tests.yml
- .github/workflows/pypi_release.yml
- .github/workflows/rest_api_tests.yml
- .github/workflows/tests.yml
- fixes n/a
- Remove unused secrets
- Target a different Slack channel for notifications
I didn't
> chore: clean up the Slack integrations

- .github/workflows/license_compliance.yml
- pyproject.toml
- Upgrade canals to 0.8.1, which ships an improved version of `Pipeline.draw()`
> feat: update canals to 0.8.1

- haystack/preview/README.md
> Add end2end tests as getting started to HS2.0 readme

- haystack/preview/components/file_converters/html.py
- test/preview/components/file_converters/test_html_to_document.py
Extend the input handling capabilities of `HTMLToDocument` to process `ByteStream` inputs, thus enhancing the flexibility and utility of these converters.
- Updated `HTMLToDocument` to handle `ByteStream` input.
Proper testing was performed including unit and integration tests to validate the functionality of the updated input handling mechanism. Manual testing was also conducted to ensure `ByteStream` inputs were processed accurately.
- Would appreciate a review of the updated input handling logic to ensure it aligns with project standards and efficiently handles `ByteStream` inputs without any glitches.
> feat: Update `HTMLToDocument` to handle `ByteStream` inputs

- proposals/text/6001-document-store-filter-rework.md
This PR introduces a new proposal defining a detailed specification for filtering Document Stores in Haystack 2.x.
> Proposal: Document Stores filter specification for Haystack 2.x

- .github/workflows/linting_preview.yml
- haystack/nodes/prompt/invocation_layer/anthropic_claude.py
- haystack/nodes/prompt/invocation_layer/cohere.py
- haystack/nodes/prompt/invocation_layer/hugging_face_inference.py
- haystack/nodes/prompt/invocation_layer/sagemaker_hf_infer.py
- haystack/nodes/prompt/invocation_layer/sagemaker_hf_text_gen.py
- haystack/nodes/prompt/invocation_layer/sagemaker_meta.py
- haystack/nodes/prompt/prompt_template.py
- haystack/nodes/ranker/cohere.py
For some reason `mypy` is failing when running checks in `linting_preview.yml` workflow. [Example failure](https://github.com/deepset-ai/haystack/actions/runs/6524795469/job/17716804986?pr=6052#step:6:69). 
The strange thing is that the check is failing only when running the linting in the `preview` module, the normal `linting.yml` is not failing.
This PR should fix the code that is making it fail. 
Run the same check that is run in `linting_preview.yml` locally.
When running the check locally create a new env from scratch and install the same dependencies installed in [`linting_preview.yml:40`](https://github.com/deepset-ai/haystack/blob/c78e1a7eb308d56632d6a3bebe5f77287d683326/.github/workflows/linting_preview.yml#L40) to verify the failure is fixed.
When running the check with a full …
> chore: Fix mypy errors when running preview linting in CI

- releasenotes/notes/refactor-openai-document-embedder.yaml
I incorrectly merged a PR with a wrong release note (incorrect section).
I'm fixing it.
> chore: fix wrong release note

- haystack/preview/components/audio/whisper_remote.py
- test/preview/components/audio/test_whisper_remote.py
Fix a Whisper test that somehow escaped CI, and add small code simplification.
> fix: Fix failing whisper test

- proposals/text/6141-meta-field-ranker.md
The proposal was missing closing quotation marks so it was formatted badly
> fix: missing closing quotation marks

- test/nodes/test_file_converter.py
- Cleaning up in preparation of 1.22
> chore: remove leftovers from old release

- haystack/nodes/retriever/dense.py
- fixes #4812 
Added identation and number pointers to show distinction between parameters and parameter options.
Manual verification …
> fix: Update Indentation in dense.py

- docker/Dockerfile.base
- fixes  https://github.com/deepset-ai/haystack/actions/runs/6744094285
> chore: pin trio to <0.23

- docker/Dockerfile.base
- fixes #6238 (please read)
Unpin trio during the Docker image build
CI
> chore: unpin trio in Docker image build

- .github/workflows/github_release.yml
- releasenotes/config.yaml
- fixes https://github.com/deepset-ai/haystack/issues/5450
> ci: Generate release notes in a Github workflow

- haystack/preview/components/retrievers/in_memory_bm25_retriever.py
- haystack/preview/components/retrievers/in_memory_embedding_retriever.py
- test/preview/components/retrievers/test_in_memory_bm25_retriever.py
- test/preview/components/retrievers/test_in_memory_embedding_retriever.py
Updated the docstrings language.
I didn't.
> Docs: Update docstrings lg

- haystack/modeling/model/adaptive_model.py
- haystack/nodes/file_converter/azure.py
- haystack/pipelines/base.py
- haystack/preview/components/audio/whisper_local.py
- haystack/preview/components/embedders/backends/sentence_transformers_backend.py
- haystack/preview/components/file_converters/azure.py
- haystack/preview/components/rankers/transformers_similarity.py
- haystack/preview/components/readers/extractive.py
- haystack/preview/components/samplers/top_p.py
- haystack/utils/import_utils.py
- fixes #6295
- improve the error messages of `LazyImport`, using a common format and making sure that they can be copy-pasted
- clean up some of these messages, which pointed to specific versions for no known reason.
Local manual verification
- I …
> chore: improve the error messages of `LazyImport`

- .github/workflows/e2e_preview.yml
- .github/workflows/linting_preview.yml
- .github/workflows/tests_preview.yml
- pyproject.toml
- releasenotes/notes/transformers-4-35-2-1739bbaa8c6f0111.yaml
Upgrade Transformers dependencies to the latest version 4.35.2
CI
> build: upgrade to `transformers==4.35.2`

- haystack/preview/testing/document_store.py
Move `filter_documents` tests with equal filters from `DocumentStoreBaseTests` into `LegacyFilterDocumentsLessThanEqualTest` class.
`LegacyFilterDocumentsTest` now inherits `LegacyFilterDocumentsLessThanEqualTest`.
Depends on #6346. …
> Move `filter_documents` tests with less than equal filters from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Related to #6284
Rework tests for `write_documents()` so they don't require filtering to be fully implemented to pass.
Depends on #6360 …
> refactor: Rework `write_documents` tests

- haystack/preview/utils/filters.py
- test/preview/utils/test_filters.py
Related to #6284.
This handles 
I added some tests for the corner cases and the error handling. …
> fix: Fix corner cases and error handling with filters conversion

- haystack/preview/components/readers/extractive.py
I changed "confidence score" to "probability score" everywhere because the field in the answer object is actually called "probability". I believe Julian already opened a PR to change the "confidence score threshold" param to "probability threshold" as well.  …
> Docs: Update Reader's doc strings

- haystack/nodes/retriever/web.py
- haystack/nodes/search_engine/providers.py
- haystack/nodes/search_engine/web.py
- haystack/preview/components/websearch/__init__.py
- haystack/preview/components/websearch/searchapi.py
- proposals/text/4084-agent-demo.md
- releasenotes/notes/add-searchapi-integration-bb9130485c3c9429.yaml
- test/nodes/test_web_search.py
- test/preview/components/websearch/test_searchapi.py
- Added SearchApi as a `providers`
- Added SearchApi as a `websearch` component
- Unit tests
- If you want to run e2e tests for SearchApi, let us know, and we'll give you credits.
- Feel free to assign @SebastjanPrachovskij as a main reviewer for any SearchApi-related PRs. We will be glad to help and support Haystack development. …
> feat: Add SearchApi integration

- .github/workflows/tests.yml
PRs to `main` are currently block cause they're waiting for the required `catch-all` job. We lost that job during the branch off for 2.x.
This PR brings back that job.
This PR.
N/A …
> ci: Add `catch-all` job in `tests.yml`

- .github/workflows/linting.yml
- haystack/dataclasses/document.py
- pyproject.toml
Fix `mypy` failures in CI.
[Example failure.
](https://github.com/deepset-ai/haystack/actions/runs/7008763207/job/19065752216?pr=6428)
I run `mypy` locally and on this PR.
This changes are also in #6413 but it's not yet merged. …
> ci: Fix `mypy` failures in CI

- .github/labeler.yml
> chore: add label for `core` PRs

- haystack/testing/document_store.py
Rework how `Document`s are compared in `testing/document_store.py` so that it's more versatile.
Some Document Stores might return `Document` lists with `score` or `meta` set differently from the one we expect in the testing classes.
To make it easier to use the class we add a function that can be overriden to customise how `Document` lists are compared.
N/A …
> refactor: Reworked Document Store testing comparison to be more versatile

- docs/pydoc/config-preview/generator.yml
- docs/pydoc/config-preview/router.yml
Adding recently created `CohereGenerator` and `ConditionalRouter` to API docs.
> docs: add CohereGenerator and ConditionalRouter API docs

- .github/utils/pydoc-markdown.sh
- docs/pydoc/config/builder.yml
- docs/pydoc/config/caching.yml
- docs/pydoc/config/classifier.yml
- docs/pydoc/config/converter.yml
- docs/pydoc/config/dataclass.yml
- docs/pydoc/config/document_store.yml
- docs/pydoc/config/embedder.yml
- docs/pydoc/config/fetcher.yml
- docs/pydoc/config/generator.yml
- docs/pydoc/config/pipeline.yml
- docs/pydoc/config/preprocessor.yml
- docs/pydoc/config/ranker.yml
- docs/pydoc/config/reader.yml
- docs/pydoc/config/retriever.yml
- docs/pydoc/config/router.yml
- docs/pydoc/config/sampler.yml
- docs/pydoc/config/websearch.yml
- docs/pydoc/config/whisper.yml
- docs/pydoc/config/writer.yml
- fixes #6162 
- Added Data Classes to API reference
- Changed the order of pages
- Deleted `/preview/` folder path
- Renamed `config-preview` folder to simply `config` …
> docs: add Data Classes API ref and cleanup

- haystack/components/generators/hugging_face_local.py
corrected the argument name
On Colab
The actual code works without any error, this is just a docstring change
> docs: update for HuggingFaceLocalGenerator

- .github/labeler.yml
- .github/workflows/labeler.yml
- n/a
Update the action to the latest version 5 and fix the config file according to the new format
> chore: update labeler to latest version

- haystack/components/builders/dynamic_prompt_builder.py
Clarify motivation for `DynamicPromptBuilder` existence and give better example usage scenarios 
- **Clarification of Usage:** Additional explanations are added to illustrate the advantages of using `DynamicPromptBuilder`, especially in server environments where continuous service and efficiency are crucial.
- **Removal of Redundant Warning:** The warning regarding the absence of `runtime_variables` has been removed, streamlining the initialization process, not scaring users any longer.
The updated `DynamicPromptBuilder` can be used in scenarios where various types of prompts need to be generated dynamically. It's particularly beneficial in chatbot applications or any interactive system requiring prompt customization based on user input, without the overhead of reloading the entire …
> docs: Clarify DynamicPromptBuilder Raison d’Être

- .github/workflows/e2e.yml
- .github/workflows/linting.yml
- .github/workflows/tests.yml
- pyproject.toml
- test/test_requirements.txt
- keep track of the dependencies needed to run tests in a unique requirements file
- remove `audio` dependency group (consistently with 2.x approach)
CI
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#ins …
> chore: simplify the management of test dependencies

- .github/workflows/github_release.yml
> ci: use the right version

- haystack/components/builders/answer_builder.py
- haystack/components/builders/dynamic_prompt_builder.py
- haystack/components/builders/prompt_builder.py
- haystack/components/generators/chat/hugging_face_tgi.py
Newlines need to be escaped in docs for them to be rendered properly.
> docs: fix formatting

- haystack/components/audio/whisper_remote.py
- haystack/components/embedders/openai_document_embedder.py
- haystack/components/embedders/openai_text_embedder.py
- haystack/components/generators/chat/openai.py
- haystack/components/generators/openai.py
- pyproject.toml
- releasenotes/notes/upgrade-openai-client-15fda68fc769f95b.yaml
- test/components/audio/test_whisper_remote.py
- test/components/embedders/test_openai_document_embedder.py
- test/components/embedders/test_openai_text_embedder.py
- test/components/generators/chat/test_openai.py
- test/components/generators/conftest.py
- test/components/generators/test_openai.py
- test/conftest.py
- test/pipelines/test_rag_pipelines.py
This Pull Request aims to update the OpenAI Python client in the Haystack 2.x framework, aiming to take advantage of newer features, improved stability, or better performance of the updated client library.
- **Upgrade of OpenAI Python Client**: The core change involves upgrading the OpenAI Python client to a newer version. This upgrade affects several components within the Haystack project, primarily those interfacing with OpenAI's API for various functionalities like audio transcription and text embedding.
- **Refactoring of Code**: The upgrade necessitated refactoring across multiple files, including `whisper_remote.py`, `openai_document_embedder.py`, `openai_text_embedder.py`, and others, to accommodate the changes in the OpenAI client API.
- **Improvement in Code Readability and …
> feat: Update OpenAI Python Client in Haystack 2.x

- .github/workflows/tests.yml
- .github/workflows/tests_skipper.yml
- test/test_requirements.txt
> chore: upgrade transformers to 4.36.2 in test requirements

- haystack/components/samplers/top_p.py
This update improves the documentation and functionality of the `TopPSampler` component. It enhances the clarity and usability, which is crucial for users working with document filtering based on cumulative probability scores.
The `TopPSampler` class underwent documentation improvements and minor code updates. Key changes include:
1. **Documentation Enhancement:** 
- Revised class description for better clarity and detail.
- Expanded usage examples with more informative comments.
- Detailed parameter descriptions for the constructor and `run` method.
2. **Code Updates:**
- Modified the constructor's `top_p` parameter to clarify its purpose and default behavior.
- Enhanced the `run` method's documentation and error handling:
- Added descriptions for input parameters and the return value.
- …
> chore: Update and improve `TopPSampler` docs

- docs/pydoc/config/document-store.yml
- haystack/document_stores/__init__.py
- haystack/document_stores/mongodb_atlas.py
No issues
* Register MongoDBAtlasDocumentStore doc strings for API reference
* Update import path of MongoDBAtlasDocumentStore
I generated the md files for the API reference locally
N/A …
> Add MongoDBAtlasDocumentStore api reference

- haystack/components/connectors/openapi_service.py
- haystack/components/generators/chat/openai.py
- haystack/components/generators/openai.py
- releasenotes/notes/update-openai-chat-tools-3d3636b2ffea9736.yaml
- test/components/connectors/test_openapi_service.py
Adds enhancements to the OpenAIChatGenerator and OpenAPIServiceConnector to improve functionality and handling of tools and function calling.
1. **OpenAPIServiceConnector**: Modified to handle `tools` and `functions` parameters more efficiently. This includes parsing chat messages to extract method invocation descriptors and invoking methods with dynamic service responses.
2. **OpenAIChatGenerator**:
- Adjusted to support streaming and non-streaming modes, particularly handling `tools` and `functions` parameters.
- Enhanced to build message payloads more accurately, especially when dealing with tools or function calls.
- Updated to ensure proper handling of content and meta information during chat message generation.
3. **General Code Enhancements**: Various additions and deletions in the …
> feat: Update OpenAIChatGenerator to handle both tools and functions calling

- README.md
> chore: use GitHub markdown for warning about beta version in Readme

- docs/pydoc/config/builder.yml
- haystack/components/audio/whisper_remote.py
- haystack/components/preprocessors/document_splitter.py
- haystack/components/routers/metadata_router.py
1. Fixing formatting in docstrings
2. Adding DynamicChatPromptBuilder to API Reference
> docs: docstrings formatting

- haystack/modeling/model/prediction_head.py
- haystack/nodes/reader/farm.py
- haystack/utils/torch_utils.py
- releasenotes/notes/farmreader-kwargs-130e0b1a89f75fef.yaml
- test/nodes/test_reader.py
- fixes N/A
- Needs PR https://github.com/deepset-ai/haystack/pull/6627 for the extract_torch_dtype method
- Allows us to load a FARMReader in torch.float16
- This speeds up inference time around 2x …
> feat: Add model kwargs to FARMReader

- .github/workflows/tests.yml
- fixes #6571 
Reintroduce the upload step in the unit testsuite
not tested
> ci: re-enable coverage report

- haystack/components/caching/__init__.py
- haystack/components/caching/cache_checker.py
- releasenotes/notes/make-urlcachechecker-generic-e159d40bbd943081.yaml
- test/components/caching/test_url_cache_checker.py
Originally, the component `UrlCacheChecker` was designed to check for the presence of documents in the DocumentStore based specifically on URL fields. This limits the component's usefulness to only caching based on URLs, which could be restrictive for different use-cases where other fields might be equally or more important for caching purposes.
The change aims to generalize the caching mechanism so that it can be used with any field of the documents, not just the URL. This makes the caching component more versatile, allowing it to be integrated into various pipeline configurations and scenarios, which could potentially involve different fields for caching checks.
The expected impact of this change is to provide users with a more generic cache checking capability, thereby enhancing the …
> feat: Improve UrlCacheChecker, make it more generic

- haystack/document_stores/pinecone.py
- releasenotes/notes/optimize-pinecone-upsert.yaml
- test/document_stores/test_pinecone.py
- test/mocks/pinecone.py
- fixes https://github.com/deepset-ai/haystack/issues/6642
See https://github.com/deepset-ai/haystack/pull/6644
> feat: Pinecone upsert documents optimizations

- .github/workflows/tests.yml
We're not tracking coverage anymore for 1.x but only for 2.x, so we can remove this.
Can't test this.
N/A
> ci: Remove coverage reporting in 1.x tests.yml

- test/core/pipeline/test_pipeline.py
- fixes https://github.com/deepset-ai/haystack/actions/runs/7528104540/job/20489856130
- previously (before #6730), tests were not run on haystack/core, so the error was not detected
make tests pass
local tests, CI …
> fix: fix Pipeline test error

- e2e/pipelines/test_dense_doc_search.py
- e2e/pipelines/test_extractive_qa_pipeline.py
- e2e/pipelines/test_hybrid_doc_search_pipeline.py
- e2e/pipelines/test_preprocessing_pipeline.py
- e2e/pipelines/test_rag_pipelines_e2e.py
- fixes #6389
Update serde calls to use the new API.
E2E
> test: Update E2E tests to use `Pipeline.dump/load`

- haystack/components/converters/html.py
- test/components/converters/test_html_to_document.py
> feat: Add serde methods to `HTMLToDocument`

- README.md
- fixes #6764
Adding a short overview of how telemetry works in Haystack with a link to docs.
> readme: add telemetry overview

- haystack/utils/openai_utils.py
- releasenotes/notes/support-gpt-3.5-turbo-1106-6de58fee16cc0c0a.yaml
- test/utils/test_openai_utils.py
- fixes #6770 
Update `_openai_text_completion_tokenization_details`
added a unit test
> feat: Add support for `gpt-3.5-turbo-1106`

- docs/pydoc/config/embedder.yml
- docs/pydoc/config/extractor.yml
Adding missing NER extractor, embedders and generators to API reference.
> docs: add missing components to API reference

- .github/ISSUE_TEMPLATE/breaking-change-proposal.md
N/A
Add a "Breaking Change Proposal" as we have in [haystack-core-integrations](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/ISSUE_TEMPLATE/breaking-change-proposal.md)
n/a
n/a …
> Create breaking-change-proposal.md issue template

- e2e/pipelines/test_rag_pipelines_e2e.py
> chore: Use the default Secret api key resolution in e2e rag pipeline test

- haystack/components/converters/output_adapter.py
- test/components/converters/test_output_adapter.py
This change is motivated by the need to enhance the `OutputAdapter` by enabling the serialization and deserialization of custom filters, the update allows for more dynamic and customizable output data processing. This ensures that users can tailor output data processing to meet their specific needs, increasing the adaptability and efficiency of data handling within the Haystack ecosystem.
- Added functionality to serialize and deserialize custom filters in the `OutputAdapter` class.
- Updated the `to_dict` and `from_dict` methods to handle serialization and deserialization of custom filters.
- Implemented testing to validate serialization and deserialization functionality of custom filters.
- Enhance output data processing by applying custom filters.
- Serialize `OutputAdapter` instances …
> feat: Add OutputAdapter sede for custom filters

- docs/pydoc/config/validators_api.yml
- haystack/components/validators/__init__.py
- haystack/components/validators/json_schema.py
- releasenotes/notes/introduce-jsonschema-validator-65debc51a3b64975.yaml
- test/components/validators/test_json_schema.py
- test/test_requirements.txt
Part of #6939 
In many cases, including in function calling,  users must ensure that LLM-generated JSON adheres to specific schemas. This is crucial for maintaining the quality and integrity of data processed by chatbots or other Haystack 2.x pipelines that need LLM validation. By validating against predefined JSON schemas, the system can filter out invalid data, prevent potential errors, and even correct the output via pipeline correction loops.
- partially fixes https://github.com/deepset-ai/haystack/issues/6923
- **New Validator Component:** A `JsonSchemaValidator` class was introduced to validate the JSON content of `ChatMessage` instances against a provided JSON schema.
- **Dynamic Error Messaging:** The validator has capabilities to provide detailed error messages which can be …
> feat: Add JsonSchemaValidator

- docs/pydoc/config/eval_api.yml
- fixes https://github.com/deepset-ai/haystack/actions/runs/7919224752/job/21619485213
> fix: fix docs config for evaluators

- .github/workflows/readme_sync.yml
- twin PR of https://github.com/deepset-ai/haystack-core-integrations/pull/438
the workflow runs smoothly: https://github.com/deepset-ai/haystack/actions/runs/7948679390/job/21698968267?pr=7029 …
> ci: update "Sync docs with Readme"

- README.md
@anakin87 - here is the updated section on contributions
> Add the Contributions wanted project

- .github/workflows/tests.yml
- haystack/templates/indexing.yaml.jinja2
- haystack/templates/rag.yaml.jinja2
- fixes https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7960682486/job/21730253353?pr=442
Adopt the new management of devices for Sentence Transformers embedders in Pipeline templates
CI …
> fix: Pipeline templates with new devices mgmt

- haystack/tracing/datadog.py
- haystack/tracing/tracer.py
- releasenotes/notes/datadog-tracer-b084cf64fcc575c6.yaml
- test/test_requirements.txt
- test/tracing/test_datadog.py
- test/tracing/test_tracer.py
- related to https://github.com/deepset-ai/haystack/issues/7026
- add Datadog tracer
- auto enable datadog tracer if `ddtrace` is installed
- some cheeky unit tests :-)  …
> feat: datadog tracer

- docker/Dockerfile.base
- fixes https://nvd.nist.gov/vuln/detail/CVE-2022-40897
> build: fix CVE-2022-40897

- docs/pydoc/config/preprocessors_api.yml
- fixes https://github.com/deepset-ai/haystack/actions/runs/8066688280/job/22035348138
- wrong config introduced in #7219
> docs: fix wrong docs config

- haystack/document_stores/in_memory/document_store.py
- haystack/document_stores/types/protocol.py
> fixing docstrings

- docs/pydoc/config/routers_api.yml
- haystack/components/routers/conditional_router.py
- haystack/components/routers/file_type_router.py
- haystack/components/routers/metadata_router.py
- haystack/components/routers/text_language_router.py
- test/components/routers/test_text_language_router.py
- fixes #7115
- fixes #7170 (only a small change in `excerpt`)
> docs: review `Routers` docstrings

- pyproject.toml
- releasenotes/notes/pin-typing-extensions-c4026f59603445b7.yaml
- pin typing_extensions due to https://community.openai.com/t/error-while-importing-openai-from-open-import-openai/578166/26
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installat …
> build: pin typing-extensions

- docs/pydoc/config/generators_api.yml
- haystack/components/generators/chat/azure.py
- haystack/components/generators/chat/hugging_face_local.py
- haystack/components/generators/chat/hugging_face_tgi.py
- haystack/components/generators/chat/openai.py
> docs: docstrings - `generators.chat`

- haystack/dataclasses/document.py
> docs: API Docs - haystack.dataclasses

- haystack/components/validators/json_schema.py
- test/components/validators/test_json_schema.py
- fixes https://github.com/deepset-ai/haystack/issues/7117
- fixes https://github.com/deepset-ai/haystack/issues/7172
- **chore: make private**
- **docs: review and normalize docstrings** …
> docs: review docstrings in `haystack.components.validators`

- .github/workflows/rest_api_tests.yml
- install missing dependencies for rest api tests
> ci: fix rest-api tests

- haystack/components/writers/document_writer.py
> docs: Update docstrings for `haystack.components.writers`

- .github/workflows/rest_api_tests.yml
backport of https://github.com/deepset-ai/haystack/pull/7256
> ci: fix rest-api tests (#7256)

- haystack/components/embedders/azure_document_embedder.py
- haystack/components/embedders/azure_text_embedder.py
- haystack/components/embedders/hugging_face_tei_document_embedder.py
- haystack/components/embedders/hugging_face_tei_text_embedder.py
- haystack/components/embedders/openai_document_embedder.py
- haystack/components/embedders/openai_text_embedder.py
- haystack/components/embedders/sentence_transformers_document_embedder.py
- haystack/components/embedders/sentence_transformers_text_embedder.py
- fixes #7104 
Update docstring for all `embedders` Components.
I generated docs locally.
N/A
> docs: Update `embedders` docstrings

- haystack/components/retrievers/__init__.py
- haystack/utils/hf.py
- pyproject.toml
- ci: add ruff to CI
- chore: fix ruff issues
- ci: fix ruff deprecation warnings
- manually executed commands
> ci: add ruff to CI + bring config up to date

- haystack/core/component/sockets.py
- haystack/core/component/types.py
- haystack/core/pipeline/pipeline.py
- haystack/core/pipeline/template.py
- haystack/core/serialization.py
> docs: Update docstrings for `haystack.core`

- test/core/pipeline/test_pipeline.py
- fixes https://github.com/deepset-ai/haystack/actions/runs/8110957377/job/22170715763
Latest version of the template doesn't have conditional components, this slipped through the cracks …
> fix tests on main

- haystack/components/retrievers/filter_retriever.py
- haystack/components/retrievers/in_memory/bm25_retriever.py
- haystack/components/retrievers/in_memory/embedding_retriever.py
> docs: Update docstrings for `haystack.components.retrievers`

- docs/pydoc/config/joiners_api.yml
- haystack/components/joiners/document_joiner.py
- fixes #7109 
- fixes #7164 
Update docstrings for all `joiners` components and related config.
I generated docs locally.
N/A …
> docs: Update `joiners` docstrings and configs

- haystack/utils/auth.py
- haystack/utils/hf.py
- haystack/utils/requests_utils.py
Updates docstrings for  `haystack.utils` package
- fixes https://github.com/deepset-ai/haystack/issues/7124
> docs: Update docstrings for `haystack.utils`

- haystack/components/generators/azure.py
- haystack/components/generators/hugging_face_tgi.py
- haystack/components/generators/openai.py
> docs: last fixes on non-chat generators

- haystack/components/converters/openapi_functions.py
- test/components/converters/test_openapi_functions.py
Simplifies OpenAPIServiceToFunctions run signature. 
It focuses on simplifying the process of extracting and utilizing functions from OpenAPI specs, reducing complexity and improving readability of the code. The modifications are intended to enhance the component's functionality by removing unnecessary parameters, refining the extraction logic, and improving the output format for further processing or integration with OpenAI function calling mechanisms.
- Removed dependencies on external libraries (`requests`) for fetching OpenAPI specs from URLs, streamlining the focus on local file paths and `ByteStream` objects.
- Simplified the `run` method by removing the `system_messages` parameter, focusing on processing OpenAPI specifications more directly.
- Enhanced error handling and logging, …
> feat: Improve OpenAPIServiceToFunctions signature

- docs/pydoc/config/utils_api.yml
- fixes https://github.com/deepset-ai/haystack/issues/7179
> docs: Add haystack.utils API docs

- docs/pydoc/config/audio_api.yml
> docs: edit audio docstrings order

- docs/pydoc/config/utils_api.yml
- haystack/utils/auth.py
- haystack/utils/filters.py
- haystack/utils/jupyter.py
- haystack/utils/requests_utils.py
- haystack/utils/type_serialization.py
> docs: `haystack.utils` docfixes

- README.md
- Changed wording in the readme: documentation search -> document search
> docs: documentation search -> document search in Readme

- docs/pydoc/config/audio_api.yml
- docs/pydoc/config/builders_api.yml
- docs/pydoc/config/caching_api.yml
- docs/pydoc/config/classifiers_api.yml
- docs/pydoc/config/connectors.yml
- docs/pydoc/config/converters_api.yml
- docs/pydoc/config/data_classess_api.yml
- docs/pydoc/config/document_stores_api.yml
- docs/pydoc/config/document_writers_api.yml
- docs/pydoc/config/embedders_api.yml
- docs/pydoc/config/extractors_api.yml
- docs/pydoc/config/fetchers_api.yml
- docs/pydoc/config/generators_api.yml
- docs/pydoc/config/joiners_api.yml
- docs/pydoc/config/others_api.yml
- docs/pydoc/config/pipeline_api.yml
- docs/pydoc/config/preprocessors_api.yml
- docs/pydoc/config/rankers_api.yml
- docs/pydoc/config/readers_api.yml
- docs/pydoc/config/retrievers_api.yml
- docs/pydoc/config/routers_api.yml
- docs/pydoc/config/samplers_api.yml
- docs/pydoc/config/utils_api.yml
- docs/pydoc/config/validators_api.yml
- docs/pydoc/config/websearch_api.yml
**Proposed Changes**
- disable class def in readme
**Old**
**New**
> docs: disable class def rendering

- pyproject.toml
This is a test dependency.
Pinning it temporarily to avoid CI failures due to the 0.22.0 release: https://github.com/deepset-ai/haystack/actions/runs/8422628045/job/23062679697?pr=7362
> ci: pin huggingface_hub in tests dependencies

- docs/pydoc/config/routers_api.yml
Adds TransformersZeroShotTextRouter to docs
> chore: Add TransformersZeroShotTextRouter to docs

- haystack/components/evaluators/__init__.py
Update `evaluators/__init__.py` with all the newly created evaluator components.
I didn't test it really, this shouldn't cause any issue.
N/A …
> chore: Export evaluators in `__init__.py`

- haystack/components/converters/html.py
- releasenotes/notes/enhanced-htmltodocument-content-extraction-229d63e7c7119807.yaml
- test/components/converters/test_html_to_document.py
- test/test_files/html/paul_graham_superlinear.html
The previous implementation for HTML content extraction was rigid, only allowing the use of a single, user-specified extractor. This approach had limitations, particularly when the chosen extractor failed to process certain documents, leading to either empty or skipped documents without attempting alternative extraction methods. The update aims to enhance document processing robustness by iteratively trying a predefined list of extractors until successful text extraction occurs, ensuring the system is more resilient and capable of handling a wider variety of HTML documents.
- fixes https://github.com/deepset-ai/haystack/issues/6760
- Introduced a list of potential extractors, ensuring the user's preferred extractor is tried first, followed by a sequence of fallback extractors.
- Changed …
> feat: Use all HTMLToDocument extractors until content is extracted

- haystack/tracing/datadog.py
- haystack/tracing/opentelemetry.py
- haystack/tracing/tracer.py
- haystack/tracing/utils.py
> chore: fix docstrints format for tracing package

- haystack/dataclasses/sparse_embedding.py
- haystack/marshal/yaml.py
- haystack/telemetry/_telemetry.py
- some more docstring fixes to pass the ruff linting
> some more docstring fixes

- haystack/components/evaluators/__init__.py
- haystack/components/evaluators/evaluation_result.py
- haystack/components/evaluators/results_evaluator.py
- releasenotes/notes/implemeting-eval-results-API-25b2f8707495bea0.yaml
- test/components/evaluators/test_results_evaluator.py
- handles #7508 
- a new Evaluator component to present evaluation results
- unit tests for each new method
> feat: implementing evalualtion results API

- haystack/logging.py
> chore: fix docstrings in logging module

- pyproject.toml
- Cohere Command R Support (added in [4.39.0](https://github.com/huggingface/transformers/releases/tag/v4.39.0)) …
> chore: bump transformers to 4.39.3 (Cohere Command R support)

- pyproject.toml
-  n/a
Properly use Hatch's [context formatting](https://hatch.pypa.io/1.9/config/environment/advanced/#context-formatting) in the test scripts, so that custom arguments can be passed down. …
> chore: fix hatch scripts

- releasenotes/notes/bedrock-support-for-mistralai-and-new-claude-3-models-f141aef0a7690ef3.yaml
- releasenotes/notes/bump-transformers-to-4-39-2de45528eff50ce8.yaml
- releasenotes/notes/fix-os-es-get-metadata-values-by-key-d5e34c79998c322d.yaml
> fix: add missing reno files for 7543, 7562 and 7535

- .github/workflows/minor_version_release.yml
This PR updates the body description of the PR created by `minor_version_release.yml` to clearly describe what has been done by the workflow.
> ci: Enhance version bump PR body description

- .github/workflows/license_compliance.yml
Update the license check allow-list removing the old v1.x packages
> chore: Remove leftovers from Haystack 1.x

- haystack/core/pipeline/pipeline.py
See https://github.com/deepset-ai/haystack/pull/7545#issuecomment-2093783375
> Remove logger line using forbidden logrecord property

- docs/pydoc/config/converters_api.yml
> docs: add pdfminer to converters

- test/core/pipeline/features/README.md
Add some more information on the `Pipeline.run()` tests `README.md`.
> test: Update `Pipeline.run()` tests `README.md`

- .github/workflows/github_release.yml
> ci: ignore rc0 releases

- haystack/components/converters/pypdf.py
> docs: Update doc string of pypdf.py

- pyproject.toml
- upgrade transformers to the latest stable version (released a week ago)
- reorganize a bit the test dependencies
CI
> chore: upgrade transformers test dependency

- README.md
> Added NOS Portugal to list of companies in README.md

- CONTRIBUTING.md
- no issue related
Update the contribution guidelines
> docs: update contributor guidelines

- haystack/logging.py
> chore: remove unused import

- .github/workflows/workflows_linting.yml
This should fix so it runs correctly.
I opened this PR to trigger the workflow.
I noticed the workflow never ran from [here](https://github.com/deepset-ai/haystack/actions/workflows/workflows_linting.yml). …
> ci: Fix `workflows_linting.yml` never running

- test/components/audio/test_whisper_remote.py
- Fixes whisper integration test by ensuring that the required `OPENAI_API_KEY` env var is set
- Rename test
> chore: Fix whisper test

- .pre-commit-config.yaml
Update pre-commit hooks versions.
I just created a new commit.
N/A
> build: Update pre-commit hooks versions

- haystack/core/pipeline/base.py
- releasenotes/notes/better-deserialization-errors-f2b0e226534f4cd2.yaml
- test/core/pipeline/test_pipeline.py
This PR expands some errors messages that can potentially be displayed during the pipeline serialization process, pointing the user in the right direction for troubleshooting.
Unit test …
> refactor: Improve error messages shown during pipeline deserialization

- test/components/retrievers/test_sentence_window_retriever.py
- actually use a Pipeline and not isolated components for the `SentenceWindowRetrieval`
- unit tests, integration tests
> updating sentence window retriever tests

- pyproject.toml
- releasenotes/notes/pin-structlog-39d991a70590dd6e.yaml
- test/components/generators/chat/test_hugging_face_api.py
Contains following PRs:
- https://github.com/deepset-ai/haystack/pull/8044
- https://github.com/deepset-ai/haystack/pull/8043
> chore: Combined main unblock

- haystack/components/writers/document_writer.py
> Docs: Update  DocumentWriter docstrings

- haystack/components/converters/__init__.py
- releasenotes/notes/pptx-import-edc6b8d6274e4023.yaml
> fix: fix PPTX import

- releasenotes/notes/pptx-import-edc6b8d6274e4023.yaml
> chore: fix PPTX release note

- haystack/components/retrievers/in_memory/embedding_retriever.py
> Docs:  Update InMemoryEmbeddingRetriever docstrings

- haystack/components/retrievers/in_memory/bm25_retriever.py
> docs: clean up and clarify InMemoryBM25Retrieve docstrings

- haystack/components/joiners/document_joiner.py
> Docs: Update DocumentJoiner docstrings

- haystack/components/preprocessors/document_cleaner.py
> Docs: Update DocumentCleaner docstrings

- haystack/components/embedders/sentence_transformers_document_embedder.py
> Docs: Update DocumentEmbedder docstrings

- haystack/components/builders/answer_builder.py
> docs: clean up docstrings of AnswerBuilder

- haystack/components/converters/pypdf.py
> Docs: Update PyPDFToDocument docstrings

- haystack/components/converters/txt.py
> Docs: Update TextFileToDocument docstrings

- haystack/components/rankers/transformers_similarity.py
> docs: clean up docstrings of TransformersSimilarityRanker

- haystack/components/retrievers/filter_retriever.py
> Docs: Update FilterRetriever docstrings

- haystack/components/fetchers/link_content.py
> Docs: Update LinkContentFetcher docstrings

- haystack/components/retrievers/sentence_window_retriever.py
> Docs: update SentenceWindowRetriever docstrings

- haystack/components/retrievers/filter_retriever.py
- haystack/components/routers/conditional_router.py
> Docs: Update ConditionalRouter docstrings

- haystack/components/generators/chat/hugging_face_api.py
> Docs: Update HuggingFaceAPIChatGEnertaor docstrings

- haystack/components/generators/hugging_face_local.py
> Docs: Update HFLocalGenerator docstrings

- haystack/components/generators/chat/hugging_face_local.py
> Docs: Update HFLocalChatGenerator docstrings

- pyproject.toml
- releasenotes/notes/python-3.11-3.12-857850f74f2e1ceb.yaml
- **docs: add Python 3.11 and 3.12 to supported versions**
- **docs: add release notes**
> docs: document Python 3.11 and 3.12 support

- CONTRIBUTING.md
> doc: adding some more hatch info to CONTRIBUTING.md

- docs/pydoc/config/retrievers_api.yml
- haystack/components/retrievers/__init__.py
- haystack/components/retrievers/sentence_window_retrieval.py
- releasenotes/notes/deprecate-sentence-window-retrieval-9d7f8a61429a514b.yaml
- test/components/retrievers/test_sentence_window_retrieval.py
> Cherry-pick SentenceWindowRetrieval commit (#8206) to 2.4.x

- haystack/components/caching/cache_checker.py
- haystack/components/retrievers/filter_retriever.py
- haystack/components/retrievers/sentence_window_retriever.py
- haystack/components/writers/document_writer.py
- haystack/utils/__init__.py
- haystack/utils/docstore_deserialization.py
- releasenotes/notes/docstore-deserialization-in-init-params-a123a39d5fbc957f.yaml
- releasenotes/notes/use-document-store-from-dict-db7975d0e0e5e451.yaml
- test/components/caching/test_url_cache_checker.py
- test/components/retrievers/test_sentence_window_retriever.py
- test/components/writers/test_document_writer.py
- test/utils/test_docstore_deserialization.py
Cherry-pick the commits of #8207 and #8226
CI
> Cherry-pick docstores deserialization refactoring to 2.4.x

- haystack/components/converters/azure.py
> Docs: update AzureOCRConverter docstrings

- haystack/components/caching/cache_checker.py
> clean up docstrings: CacheChecker

- haystack/components/classifiers/document_language_classifier.py
> clean up docstrings: DocumentLanguageClassifier

- pyproject.toml
Upgrade `transformers` to the latest stable version (released 5 days ago), as we do from time to time, to ensure that we retain compatibility.
CI
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installati …
> chore: upgrade `transformers` test dependency to `4.44.2`

- .github/workflows/docstrings_linting.yml
Fix the `docstrings_linting.yml` never running.
I'm running it in this PR with a trigger file.
N/A
> ci: Fix docstrings linting workflow never running

- haystack/components/builders/chat_prompt_builder.py
- haystack/components/embedders/hugging_face_api_document_embedder.py
- haystack/components/embedders/hugging_face_api_text_embedder.py
- haystack/components/preprocessors/document_splitter.py
- haystack/components/rankers/meta_field.py
- haystack/components/retrievers/sentence_window_retriever.py
- haystack/components/routers/transformers_text_router.py
- fixes #[8324](https://github.com/deepset-ai/haystack/issues/8324)
> docs: fix broken markdown

- README.md
Two versions:
* As a tip box (smaller)
* As a new section
> Add studio to the readme

- haystack/components/extractors/named_entity_extractor.py
- haystack/components/generators/chat/hugging_face_local.py
- haystack/components/generators/hugging_face_local.py
- haystack/utils/device.py
- haystack/utils/hf.py
> docs: adding missing commas in "pip install transformers[torch]"

- .github/utils/readme_api.py
Fix [this CI failure](https://github.com/deepset-ai/haystack/actions/runs/10881091274/job/30190040285).
> chore: Remove type hint

- haystack/components/routers/transformers_text_router.py
- haystack/components/routers/zero_shot_text_router.py
> fix: Remove incorrect output types line

- test/components/joiners/test_answer_joiner.py
- test/core/pipeline/features/pipeline_run.feature
- test/core/pipeline/features/test_run.py
> chore: Move AnswerJoiner pipeline test to behavorial tests

- README.md
> chore: Update cookbook url in README.md

- haystack/core/pipeline/pipeline.py
> chore: update pipeline.py

- .github/workflows/readme_sync.yml
> chore: update readme_sync.yml

- CONTRIBUTING.md
Fix the incorrect command in CONTRIBUTING.md
See https://github.com/deepset-ai/haystack/blob/dfd339ca2df61ab405404bba8955ab6fa50d9275/pyproject.toml#L145-L151
I tried it locally …
> docs: fix hatch command in CONTRIBUTING.md

- haystack/components/retrievers/sentence_window_retriever.py
- releasenotes/notes/add-window-size-parameter-runtime-e841c4471f9d6b9c.yaml
- test/components/retrievers/test_sentence_window_retriever.py
- fixes #8459
added new unit test
> fix: window_size set during run instead of construction

- README.md
* Add info to README for installation from main branch
* Update some old links
N/A
N/A
> Add info to README for installation from main branch

- e2e/pipelines/test_preprocessing_pipeline.py
> fix: removing unused import

- haystack/__init__.py
- None
Removed a comment "FixMe" from `__init__.py`
-
-
> chore: Remove fixme from __init__.py

- haystack/components/generators/chat/azure.py
- releasenotes/notes/azurechatgenerator-tools-9622b7c96e452404.yaml
- test/components/generators/chat/test_azure.py
- fixes #8730
- introduce support for tools in `AzureOpenAIChatGenerator`
- (small PRs since the underlying functionality is already available in `OpenAIChatGenerator`, which is the parent class of this component)
CI; added more tests for this component (for `Tool` and serialization/deserialization). …
> feat: `AzureOpenAIChatGenerator` - support for tools

- haystack/components/tools/tool_invoker.py
- fixes #8748
- remove warning
> chore: `ToolInvoker` - remove warning

- haystack/components/generators/chat/hugging_face_api.py
- haystack/components/generators/chat/hugging_face_local.py
- haystack/components/generators/hugging_face_api.py
- test/components/generators/test_hugging_face_api.py
- fixes #8820: mypy 1.15.0 complains about some HF components
- several small internal adjustments to make mypy happy
CI …
> chore: fix Hugging Face components for mypy 1.15.0

- docs/pydoc/config/extractors_api.yml
- haystack/components/extractors/__init__.py
- haystack/components/extractors/llm_metadata_extractor.py
- haystack/utils/__init__.py
- haystack/utils/utils.py
- pyproject.toml
- releasenotes/notes/adding-LLMMetadataExtractor-7ff55cf132122f1f.yaml
- test/components/extractors/test_llm_metadata_extractor.py
- fixes #8785 
- unit tests, integration tests, manual verification …
> feat: adding `LLMMetadataExtractor`

- proposals/README.md
- proposals/text/4084-agent-demo.md
- proposals/text/4284-drop-basecomponent.md
- proposals/text/4370-documentstores-and-retrievers.md
- proposals/text/5540-llm-support-2.0.md
- proposals/text/6784-integrations-for-eval-framworks.md
Hey, our tool caught a few typos in your repository.
Also, here is your site's error report: https://triplechecker.com/s/K9MDCC/deepset.ai
Hope it's helpful!
> chore: Fix typos in proposals

- haystack/core/pipeline/async_pipeline.py
Remove run_inner code snippet from sync run
> docs: update the api docs of AsyncPipeline

- test/core/pipeline/test_type_utils.py
- partially addresses https://github.com/deepset-ai/haystack/issues/8866
This PR expands and refactors the existing type util tests in preparation of adding a "relaxed" and "off" version of type validation. 
Only changed testing code. …
> refactor: Refactor and expand tests for type utils

- haystack/core/component/component.py
- haystack/core/pipeline/base.py
- test/components/evaluators/test_context_relevance_evaluator.py
- test/components/routers/test_file_router.py
Remove print statements from tests and mention of old name
No tests needed
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#inst …
> chore: Remove print statements from tests and mention of old name

- pyproject.toml
- update `transformers` version, as we do from time to time, to make sure that Haystack stays compatible
- (this is just an interal test dependency)
CI …
> chore: update `transformers` test dependency to 4.48.3

- test/core/pipeline/test_type_utils.py
> fix: Fix type util tests

- pyproject.toml
Pinning ruff to fix formatting/linting tests.
> chore: Pin ruff

- releasenotes/notes/refactor-openai-streaming-include-usage-cf00fed05b59682d.yaml
Add missing release note for PR https://github.com/deepset-ai/haystack/pull/9046
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.m …
> chore: Add missing release note for PR https://github.com/deepset-ai/haystack/pull/9046

- examples/data_based_breakpoints.py
- examples/resume_breakpoints.py
- haystack/core/pipeline/pipeline.py
-  adding initial PoC based on state saving in JSON)
> feat: adding initial PoC based on state saving in JSON

- haystack/core/pipeline/async_pipeline.py
* Update formatting of the docstring
* Pass the correct prepared data to the tracer (following what's done for the normal Pipeline)
* Get rid of "shadows from outer scope" warnings, where we reuse the same variable names in an outer scope within a function that has the potential to cause unexpected behavior. It looks in this case it was fine, but best to avoid.  …
> Update docstring and prevent name collisions

- haystack/core/pipeline/pipeline.py
- @Amnah199 a small validation function to validate breakpoints
> feat: adding function to validate breakpoints

- haystack/core/pipeline/pipeline.py
- adding logic/reasoning for counting
- moving some variables as class attributes since they are used in multiple places …
> feat: add reasoning to breakpoints considering visit counts values

- haystack/components/joiners/document_joiner.py
- removing unused variable in `DocumentJoiner`
- unit tests, integration tests, CI tests
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installation …
> chore: removing unused variable in `DocumentJoiner`

- haystack/dataclasses/chat_message.py
- pyproject.toml
Bump transformers version to latest. We make sure to pin patched version `4.51.1` to avoid this [issue](https://github.com/huggingface/transformers/issues/37326) in `4.51.0` …
> chore: Bump transformers

- haystack/components/embedders/hugging_face_api_document_embedder.py
- haystack/components/generators/chat/hugging_face_local.py
- haystack/utils/hf.py
- we introduced `transformers==4.51.1` in #9178
- mypy did not run on the original PR and now we have failures: https://github.com/deepset-ai/haystack/actions/runs/14352303827/job/40234015550
- some issues depend on transformers: https://github.com/huggingface/transformers/issues/37339
- as mentioned in https://github.com/huggingface/transformers/issues/37339, fix some of the issues by using a different import path
- other fixes
CI …
> chore: fix mypy issues due to transformers 4.51.1

- haystack/components/extractors/__init__.py
- haystack/components/extractors/llm_metadata_extractor.py
- releasenotes/notes/llmmetadata-extractor-rm-deprecated-params-a55634bfdf39a908.yaml
- test/components/extractors/test_llm_metadata_extractor.py
- fixes #9106
- remove the deprecated initialization parameters and simplify the component
CI; refactored tests. …
> chore: `LLMMetadataExtractor` - remove deprecated parameters

- pyproject.toml
- test/components/embedders/test_hugging_face_api_text_embedder.py
- remove some unused dependencies: most of them are related to tests and used in 1.x
- remove unused test markers: they were used in 1.x
- remove `tool.ruff.lint.per-file-ignores`: some of the files in this list no longer exist, others have changed and `ignore` is no longer needed
CI; I also locally ran all commands associated with `test` environment, and they work as expected. …
> chore: remove unused dependencies and clean pyproject.toml

- haystack/components/agents/agent.py
- releasenotes/notes/agent-run-async-28d3a6dd7ea4d888.yaml
- test/components/agents/test_agent.py
- fixes #9153 
- Add a run_async to Agent
- Add two unit tests
- Refactor by extracting `_check_exit_conditions`
new unit tests …
> feat: Add run_async to Agent

- test/components/generators/conftest.py
- removing a duplicated import
> chore: removing a duplicated import

- haystack/components/agents/agent.py
- haystack/core/pipeline/async_pipeline.py
- haystack/core/pipeline/base.py
- haystack/core/pipeline/pipeline.py
- releasenotes/notes/add-tracing-to-agent-da75b81fe68d33a2.yaml
- test/components/agents/test_agent.py
- test/core/pipeline/test_pipeline.py
- fixes https://github.com/deepset-ai/haystack/issues/9154
- Adds tracing support to the Agent's `run` and `run_async` methods.
- Adds an Agent span that then houses two child spans, one around ChatGenerator and one around ToolInvoker
- the `Pipeline._run_component` and `AsyncPipeline._run_component_async` handle the span creations of the `ChatGenerator` and `ToolInvoker`
- To avoid duplicate code and reuse the tracing spans set up by Pipeline I refactored Pipeline and AsyncPipeline slightly to allow us to reuse the `_run_component` and `_run_component_async`. As a benefit this also simplified the `run_async` method of Agent cc @julian-risch 
- Existing tests
- Added unit tests to test tracing
Here is an example of what the trace looks like in Langfuse …
> feat: Agent tracing

- test/tracing/test_datadog.py
Fixes tests due to new release of ddtrace
> fix: Fix datadog tracer tests

- haystack/components/preprocessors/document_preprocessor.py
- None
- Add import,  change `DocumentPreProcessor` to `DocumentPreprocessor` and change `results` to `result` in usage example
locally …
> docs: fix DocumentPreprocessor usage example

- haystack/components/agents/agent.py
- haystack/components/tools/tool_invoker.py
- releasenotes/notes/add-toolset-to-agent-d4a14822c4aed001.yaml
- test/components/agents/test_agent.py
- test/components/tools/test_tool_invoker.py
- fixes https://github.com/deepset-ai/haystack/issues/9283
- follow up to https://github.com/deepset-ai/haystack/pull/9177
- Add Toolset to the type hint of Agent
- Update to_dict to properly serialize a Toolset
Added tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in case the PR includes breaking …
> feat: Add Toolset to Agent

- .github/workflows/slow.yml
- test/components/converters/test_azure_ocr_doc_converter.py
- test/components/embedders/test_hugging_face_api_text_embedder.py
- test/components/fetchers/test_link_content_fetcher.py
- test/components/generators/chat/test_openai.py
- test/components/generators/chat/test_openai_async.py
- test/components/generators/test_hugging_face_local_generator.py
- test/components/generators/test_openai.py
- test/components/rankers/test_sentence_transformers_diversity.py
- test/components/rankers/test_transformers_similarity.py
- test/dataclasses/test_chat_message.py
As suggested by @sjrl, I investigated existing integration tests to find if some of them can be converted into unit tests
- convert some integration tests into unit tests by using mocks
- remove integration tests that are substantially duplicates or do not add significant value
- merge some integration tests that perform similar calls to external services in order to test different aspects in the response
CI
I know that this can be hard to review. For this reason, I tried to make atomic commits and comment where helpful.
- …
> test: review integration tests

- test/components/converters/test_azure_ocr_doc_converter.py
Fixes a test that fails on forks. Introduce in https://github.com/deepset-ai/haystack/pull/9306 …
> fix: Fix Azure test on forks

- releasenotes/notes/dont-deepcopy-components-tools-b1be7ef7b4365116.yaml
- releasenotes/notes/fix-deepcopy-in-pipeline-run-2b575c7b860f642f.yaml
> fix: Remove old reno and update reno

- test/components/agents/test_agent.py
- test/components/builders/test_answer_builder.py
- test/components/builders/test_chat_prompt_builder.py
- removed unused fixtures
- removed unused imports
- added a missing header LICENSE …
> chore: cleaning up tests

- test/test_logging.py
Updates test to add new fields added by new version of structlog being released
https://github.com/hynek/structlog/blob/main/CHANGELOG.md#2540---2025-06-02
- I ran …
> fix: Fix structlog test

- releasenotes/notes/add-current-date-promptbuilder-ff60c846f5a70dc6.yaml
- releasenotes/notes/rename-streaming-callback-f4e6653c0aac8765.yaml
> chore: fixing release notes

- test/components/tools/test_tool_invoker.py
Add unit test to ToolInvoker to check we can call tools with no arguments. 
Part of https://github.com/deepset-ai/haystack-core-integrations/issues/1947
Added a test
It already works, but I thought adding a unit test would be smart to ensure this behavior is tested …
> chore: Add unit test to ToolInvoker to check we can call tools with no arguments

- .github/utils/pydoc-markdown.sh
- pyproject.toml
- fixes https://github.com/deepset-ai/haystack-private/issues/149
See issue description
manual tests
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md# …
> chore: Update pydoc-markdown.sh

- haystack/components/extractors/llm_metadata_extractor.py
> fix: Small change to prompt

- README.md
> docs: Fix the deepset platform logo

- README.md
Added table of contents and made minor grammatical fixes with enhancing the readability of the file …
> upgraded README.md

- haystack/components/agents/agent.py
- haystack/core/errors.py
- haystack/core/pipeline/breakpoint.py
- haystack/core/pipeline/pipeline.py
- haystack/dataclasses/breakpoints.py
- test/components/agents/test_agent_breakpoints_inside_pipeline.py
- test/components/agents/test_agent_breakpoints_isolation_async.py
- test/components/agents/test_agent_breakpoints_isolation_sync.py
- test/conftest.py
- test/core/pipeline/test_breakpoint.py
- test/core/pipeline/test_pipeline_breakpoints_answer_joiner.py
- test/core/pipeline/test_pipeline_breakpoints_branch_joiner.py
- test/core/pipeline/test_pipeline_breakpoints_list_joiner.py
- test/core/pipeline/test_pipeline_breakpoints_loops.py
- test/core/pipeline/test_pipeline_breakpoints_rag_hybrid.py
- test/core/pipeline/test_pipeline_breakpoints_string_joiner.py
This is a proposal to introduce new dataclasses to represent a `PipelineSnapshot`. And then refactor the code to use these new dataclasses.
I've left some comments down below highlighting some of the changes. I'd most appreciate your thoughts on the dataclass structure and if anything there could be further refined. 
- Updated existing tests
- Unit tests and integration tests for breakpoints are passing …
> feat: Add dataclasses to represent a `PipelineSnapshot` and refactored to use it

- haystack/components/converters/image/document_to_image.py
> fix: Fix example in DocumentToImageContent

- haystack/components/converters/azure.py
- haystack/components/generators/chat/hugging_face_api.py
- haystack/components/generators/chat/hugging_face_local.py
- haystack/components/generators/chat/openai.py
- haystack/components/generators/hugging_face_local.py
- haystack/components/generators/openai_dalle.py
- haystack/components/preprocessors/csv_document_cleaner.py
- haystack/components/preprocessors/csv_document_splitter.py
- haystack/components/preprocessors/recursive_splitter.py
- haystack/components/rankers/meta_field_grouping_ranker.py
- haystack/components/rankers/transformers_similarity.py
- haystack/components/tools/tool_invoker.py
- haystack/components/websearch/serper_dev.py
- haystack/core/pipeline/base.py
- haystack/core/pipeline/descriptions.py
- haystack/core/pipeline/draw.py
- haystack/testing/sample_components/accumulate.py
- haystack/tools/parameters_schema_utils.py
- pyproject.toml
- remove unused `type:ignore` and `cast`
- modify mypy configuration to raise errors if unused `type:ignore` and `cast` are introduced
CI …
> chore: remove unused `type:ignore` and `cast`

- test/tools/test_pipeline_tool.py
> test: Increase robustness of PipelineTool integration tests

- haystack/components/tools/tool_invoker.py
- test/components/tools/test_tool_invoker.py
- Refactoring ToolInvoker while working on adding better support for Human in the Loop tools. Refactor is to make the code easier to understand to make it easier to add new features.
- Also found that `ToolInvoker.to_dict` was missing the `max_workers` parameter …
> chore: Refactor tool invoker
