deepset-ai/haystack

- haystack/nodes/reader/transformers.py
- test/nodes/test_reader.py
- test/pipelines/test_eval_batch.py
- fixes #3707
This PR fixes the `predict_batch` of `TransformersReader` when the input is a single query and a single nested list of Documents. If the number of provided Document lists was 1, we further nested the returned predictions coming from transformers into a third list. This was wrong. We should only nest the returned predictions into a list if the returned predictions are not a already a nested list. This is only the case when the number of inputs we provide to transformers is 1.
I added the `transformers` fixture for `test_extractive_qa_eval` in `test_eval_batch.py` and created a new test `test_output_batch_single_query_single_nested_doc_list` in `test_reader.py`.
> fix: Fix `predict_batch` in `TransformersReader` for single nested Document list

- .github/workflows/pipeline_schema.yml
- fixes #3751
- Trigger the pipeline schema workflow after every successful docker release workflow and include the source ref in the payload (branch name or tag).
- Support manually running the pipeline schema workflow with a specific ref.
https://github.com/deepset-ai/haystack-json-schema/pull/2 adapts the workflow in the deepset-ai/haystack-json-schema repository to use the released Haystack docker images and get the ref from the dispatch payload to update the pipeline schemas.
Manual verification in forked repositories.
> fix: Trigger pipeline schema update on tagged releases

- haystack/modeling/data_handler/processor.py
- haystack/modeling/model/feature_extraction.py
- haystack/modeling/model/language_model.py
- haystack/modeling/model/prediction_head.py
- haystack/utils/squad_data.py
- fixes N/A
Changed opening of files to use `with open()` context to make sure files are explicitly closed once exiting the context manager. Previously in some places, we were using code like `config = json.load(open(filename))` which doesn't guarantee that the file, `filename`, is closed after use. This can cause warnings to appear which I show below.
To get rid of the warning messages and avoid other potential [pitfalls](https://stackoverflow.com/questions/7395542/is-explicitly-closing-files-important) I updated those code lines to use the `with open()` context manager.
Made sure existing unit tests passed. Also checked locally that these types of warning messages
```python
/home/ubuntu/code/haystack/haystack/modeling/model/language_model.py:865: ResourceWarning: unclosed file …
```
> refactor: Using `with open()` to read files

- docker/Dockerfile.base
- docker/docker-bake.hcl
- fixes #3303
Based GPU image on  nvidia/cuda image
Bump GPU image to python to 3.9
CPU image already uses 3.10 - didn't change it
I wanted to update python to 3.10, currently available via  `ppa:deadsnakes/ppa` apt repository. However, the repository hosting the python 3.10 image for ubuntu seems so overwhelmed that the build timed out, waiting for gpg keys multiple times. These timeouts impede the build process and make it less reliable. Python 3.9 is available via more "standard" repositories - let's use those until 3.10 gets released.  
Tested by running haystack demo, need to set the right pipeline path, but the containers start ok.
Supercedes https://github.com/deepset-ai/haystack/pull/3323
Note how I had to remove beir dependency. Otherwise, I would get 
```
AttributeError: module …
```
> feat: Bump python to 3.10 for gpu docker image, use nvidia/cuda 

- .github/utils/generate_openapi_specs.py
- docs/_src/api/openapi/openapi-1.12.0rc0.json
- docs/_src/api/openapi/openapi-1.13.0rc0.json
- docs/_src/api/openapi/openapi.json
n/a
* "proxy-enabled": disable CORS proxy
* "samples-languages": display two languages initially
* I generated `openapi-1.12.0rc0.json` as this is the default 
* As #3775 is merged, `servers` was added for `openapi.json` and `openapi-1.13.0rc0.json` but still missing in `openapi-1.12.0rc0.json`. I added this info with this PR.
* Additional API documentation changes were made with #3772. These changes are already in `openapi.json` and `openapi-1.13.0rc0.json` but now `openapi-1.12.0rc0.json` includes them as well
> fix: add additional settings to OpenAPI schema

- pyproject.toml
- fixes #3231
Explicitly pin the protobuf version we need
Locally + CI
> fix: pin protobuf version

- test/nodes/test_prompt_node.py
No related issue, making sure PromptNode unit tests are more robust to model output
For some unknown reason model output didn't contain one key token but instead hallucinated and produced related text without the key token, making one of the tests fail. 
Unit tests
Do not integrate yet; let's see if this occurs again.
> test: Improve robustness of PromptNode unit tests

- docker/Dockerfile.base
- haystack/utils/docker.py
- fixes https://github.com/deepset-ai/haystack/pull/3701#issuecomment-1367250204
Add a function that triggers the schema generation, mainly to be used inside Docker containers for caching purposes.
I wrongly called this issue resolved in #3701 but my solution was relying on a side effect that happens only under certain circumstances: this is extremely unreliable and indeed the current `main` Docker images are broken.
Built locally with bake, then run the api container to ensure the schema is there:
```
docker run -ti --entrypoint /bin/sh docker.io/deepset/haystack:cpu-local
$ ls /opt/venv/lib/python3.10/site-packages/haystack/json-schemas
haystack-pipeline-main.schema.json
```
/cc @mayankjobanputra @vblagoje
> feat: utility function to explicitly invoke JSON schema generation

- haystack/pipelines/base.py
- test/pipelines/test_pipeline_yaml.py
- fixes #3575
Raise one DocumentStoreError instead of two PipelineConfigErrors if loading a pipeline from yaml fails because an ElasticsearchDocumentStore can't connect to an elasticsearch instance. (instance not running, wrong hostname, wrong port, etc.)
The new error message is:
> "Failed loading pipeline component 'DocumentStore': 'Initial connection to Elasticsearch failed. Make sure you run an Elasticsearch instance at `[{'host': 'localhost', 'port': 9200}]` and that it has finished the initial ramp up (can take > 30s).'"
Before this PR, two PipelineConfigErrors were raised (not just one) because of recursion. The recursive method is `_load_or_get_component`, which processes pipeline components and their parameters, which can be components themselves. First, the DocumentStore …
> feat: change PipelineConfigError to DocumentStoreError with more details

- docker/Dockerfile.api
- docker/docker-bake.hcl
None
If you set the `IMAGE_NAME` variable, then the base image will be tagged with that name, but the api image would previously use a hardcoded `deepset/haystack` image name in the `FROM` statement. With this PR it will use the name provided with the `IMAGE_NAME` variable in the `FROM` statement.
Built a base image and api image with a different name
None
> fix(docker): Use IMAGE_NAME in api image

- haystack/utils/doc_store.py
- fixes #3794
launch_milvus() fails when `Path.home() ` is not same as `/home/$USER/milvus/`
changed
```
status = subprocess.run(["cd /home/$USER/milvus/ && docker-compose up -d"], shell=True)
```
to
```
status = subprocess.run([f"cd {milvus_dir} && docker-compose up -d"], shell=True)
```
ran locally
> bug: Fix launch_milvus() by cd'ing to milvus_dir

- haystack/modeling/infer.py
- haystack/nodes/reader/base.py
- haystack/nodes/reader/farm.py
- haystack/nodes/reader/transformers.py
- test/nodes/test_reader.py
- test/pipelines/test_eval.py
- fixes #3556 
- Filter out empty documents from the list of documents passed as input to reader models
- If there is not even one predicted answer, we return a no_answer with score 1.0
- added new tests
Unfortunately, the code is relatively complex due to several edge cases that need to be handled.
Checking for empty documents is done by checking for `d.content.strip() != ""` because a document containing only whitespaces is also processed like an empty document later on.
I did not change the behavior for empty tables but only focused on empty documents with content type text instead.
There is an open ToDo regarding `pipeline.eval_batch` that is not addressed by this PR:
```python
```
> bug: skip empty documents in reader

- haystack/document_stores/base.py
- haystack/document_stores/pinecone.py
- test/document_stores/test_pinecone.py
- test/nodes/test_retriever.py
- fixes https://github.com/deepset-ai/haystack/issues/3668
- fixes https://github.com/deepset-ai/haystack/issues/3717
before validating the shape of embeddings in `_validate_embeddings_shape`, check if list of passed embeddings is non-empty. If it is empty, skip the validation and the updating of the embeddings for that batch and continue with the next batch. Otherwise proceed with validation and updating of the embeddings.
tested manually:
```python
from haystack.document_stores import PineconeDocumentStore
from haystack.nodes import EmbeddingRetriever
doc_store = PineconeDocumentStore(api_key="...", similarity="cosine", embedding_dim=384, recreate_index=True)
doc_store.write_documents([{"content":"text"}])
retriever = EmbeddingRetriever(document_store=doc_store, …
```
> bug: skip validating empty embeddings

- haystack/document_stores/search_engine.py
- test/nodes/test_retriever.py
- fixes #3812
- fixes #3737 
- escape query using `json.dumps`
- extended custom_query test
> fix: linefeeds in custom_query

- .github/workflows/compliance.yml
- unblocks  https://github.com/deepset-ai/haystack/pull/3764#issuecomment-1374098898
Do not run the FOSSA check from forks, because the check would always fail not being able to access the secret containing the api-key we use to push and check
CI
> CI: skip fossa check from forks

- haystack/nodes/reader/table.py
- test/nodes/test_table_reader.py
- fixes N/A
Add table = table.astype(str) to make sure cells are converted into to strings to be compatible with the TableReader.
This was already being done for the `RCIReader` (another type of TableReader) so I've added it for the Tapas-based `TableReader` as well.
Updated unit test to include a table that contains integer types.
> fix: Convert table cells to strings for compatibility with TableReader

- haystack/nodes/reader/table.py
- test/nodes/test_table_reader.py
- fixes N/A
I added a call to make sure to set the TableReader model to eval mode when running a prediction. Otherwise, currently, if the model is set to train mode the predictions become random due to layers like BatchNorm and dropout being present in the underlying model architecture. This is something we already do for some of our nodes like the DensePassageRetriever.
I added a new unit test to make sure everything works. I did confirm that this unit test fails without the new changes.
This probably was not noticed before because the model is set to eval mode by default when loading it.
> fix: Ensure eval mode for TableReader model for predictions

- haystack/nodes/prompt/prompt_node.py
- fixes #3806 
Adds missing pydoc
No new tests needed 
cc @agnieszka-m please check the added docs
> fix: Add missing docstrings to PromptNode, PromptTemplate and PromptModel

- haystack/nodes/preprocessor/preprocessor.py
- test/nodes/test_preprocessor.py
- fixes https://github.com/deepset-ai/haystack/issues/3514
- fix: use temp path for downloading punkt resources
- fix: gracefully handle file exists error during download
- unit test
> fix: gracefully handle `FileExistsError` during `Preprocessor` resource download

- haystack/nodes/reader/farm.py
- fixes #3771 
* Rename `student_batch_size` to `batch_size` so that it is consistent with other training methods
* Remove doc strings about unused `tinybert_loss` etc.
* Allow setting `processor` and `distillation_loss_weight` in the method `distil_intermediate_layers_from`
We had an example in the code that otherwise would not be possible to run as it sets `distillation_loss_weight` in the method `distil_intermediate_layers_from`:
```python
student = FARMReader(model_name_or_path="prajjwal1/bert-medium")
teacher = FARMReader(model_name_or_path="huawei-noah/TinyBERT_General_6L_768D")
student.distil_intermediate_layers_from(teacher, data_dir="squad2", train_filename="train.json", test_filename="dev.json", learning_rate=3e-5, distillation_loss_weight=1.0, temperature=5)
```
There are …
> bug: consistent batch_size parameter names in distillation

- .github/workflows/tests.yml
- haystack/nodes/connector/crawler.py
- test/nodes/test_connector.py
- fixes https://github.com/deepset-ai/haystack/issues/3832
https://github.com/deepset-ai/haystack/blob/5b0b338175c5eea8a237861da9812e3993b79f50/haystack/nodes/connector/crawler.py#L104
In the `__init__` method of the crawler, `os.geteuid()` is called.
It only works on Linux.
**On Windows, it raises an `AttributeError`.**
My hunch is that on Windows `IS_ROOT` can be set to `False` without affecting the proper functioning of the crawler.
- Manual verification on Windows 11
- The crawler is not tested on Windows in the CI. Let's try it and see what happens... ❌ 
**Since the tests don't properly work on Windows, I'm also changing them a bit**
> fix: make the crawler runnable and testable on Windows

- docker-compose.yml
- n/a
* Change the image to `deepset/haystack:cpu`, this is a more stable image
- n/a
- n/a
> feat: update the docker image for haystack-api service

- haystack/pipelines/base.py
- test/pipelines/test_pipeline.py
- fixes #3833
If a pipeline component was initialised passing a non-serializable param, just ignore it when computing the hash of the pipeline object.
I cleaned up the unused imports from the test module
> fix: ignore non-serializable params when hashing pipeline objects

- .github/workflows/compliance.yml
- haystack/document_stores/weaviate.py
- pyproject.toml
Adding the `replicationConfig => factor` parameter to the Weaviate class at the time of class creation, allowing the user to have Haystack create a Weaviate "Class" with a replication factor set above 1.
This enables the use of Weaviate in a HA (High Availability) fashion, where the created class is stored on multiple Weaviate nodes increasing Weaviate's throughput and also ensuring high availability.
- fixes #3763
Weaviate has just introduced [HA support in v1.17.0](https://github.com/semi-technologies/weaviate/releases/tag/v1.17.0l).
This PR allows Haystack to take advantage of this new functionality by allowing the setting of the `replicationConfig => factor` Weaviate class parameter.
I have called the dev version and confirmed in Weaviate that the class gets created with the right …
> feat: add HA support for Weaviate

- haystack/utils/doc_store.py
- spotted during community guide
- Upgrade the ES version in `launch_es()` to match the version we use in tests (`7.9.2` --> `7.17.6`)
n/a
n/a
> fix: upgrade `launch_es()` to the version used in CI

- .github/actions/python_cache/action.yml
- .github/workflows/tests.yml
- haystack/document_stores/graphdb.py
- haystack/document_stores/memory.py
- haystack/document_stores/memory_knowledgegraph.py
- haystack/document_stores/opensearch.py
- haystack/document_stores/sql.py
- haystack/modeling/data_handler/data_silo.py
- haystack/modeling/evaluation/eval.py
- haystack/modeling/evaluation/metrics.py
- haystack/modeling/infer.py
- haystack/modeling/model/adaptive_model.py
- haystack/modeling/model/biadaptive_model.py
- haystack/modeling/model/feature_extraction.py
- haystack/modeling/model/language_model.py
- haystack/modeling/model/multimodal/__init__.py
- haystack/modeling/model/optimization.py
- haystack/modeling/model/triadaptive_model.py
- haystack/modeling/training/base.py
- haystack/modeling/utils.py
- haystack/nodes/audio/_text_to_speech.py
- haystack/nodes/reader/farm.py
- haystack/nodes/retriever/_embedding_encoder.py
- haystack/nodes/retriever/dense.py
- haystack/pipelines/standard_pipelines.py
- haystack/schema.py
- haystack/utils/augment_squad.py
- haystack/utils/context_matching.py
- fixes #2149
- fixes #2351
- Adds `# type: ignore [<specific error>]` or every line that was failing mypy after haystack is installed
- Simplify the CI to make use of this
- CI
- This PR is only adding `# type: ignore` to several lines, hence the huge diff. None of these lines was actually fixed.
- The only important changes to review are in the GitHub workflow.
~:warning:  **HOWEVER**~
~Mypy used to be the fastest check in the CI at about 37 seconds. With these changes, the runtime goes up to about 7 minutes, way more than PyLint at 2 mins :disappointed: I'd argue this is the right price to pay for actual type checking, but up for discussion on this point.~
Solved, see comment below. Execution time now depends on the size of the PR, but for a PR with 26 Python files like this it takes …
> chore: make Mypy work when Haystack is installed

- rest_api/rest_api/pipeline/__init__.py
- rest_api/test/samples/test.bogus_pipeline.yml
- rest_api/test/samples/test.in-memory-haystack-pipeline.yml
- rest_api/test/test_rest_api.py
- Unblocks #3618 for simple InMemPipelines
Currently, Haystack REST-API is launched with a single worker. With a single worker, it's okay to allow indexing FAISSDocumentStore & InMemoryDocumentStore as there will not be multiple in-memory copies and no race-conditions.
Added a unit-test to capture the warning and make sure a Pipeline instance is returned instead of None.
> fix: Allowing InMemStore and FAISSDocStore for indexing using single worker

- haystack/nodes/prompt/prompt_node.py
- test/nodes/test_prompt_node.py
No related issue. This is a refactoring of the existing codebase. This PR introduces a small change where we stop using the pipeline meta field to store PromptNode invocation context and use the custom pipeline parameter `invocation_context` dictionary to store all invocation context payload. Any potential conflict with other meta payloads is avoided, and invocation context will not end up in some document store. 
Simplifies and cleans up suboptimal usage of meta pipeline variable to store invocation context dictionary. We migrate the invocation context to a separate pipeline variable called `invocation_context` of type `Dict[str, Any]`
No tests have been added, but all unit tests that test for the presence of a particular state in the invocation context have been updated.
N/A
> refactor: Move invocation_context from meta to own pipeline variable

- haystack/nodes/prompt/prompt_node.py
- test/nodes/test_prompt_node.py
- fixes #3862
Implements stop_words on the level of the PromptNode (for all models). Users can specify `stop_words` parameter in the `__init()__` of the PromptNode or from a YAML file. When one of the generated tokens is one of the specified stop words, the text generation will abort. The stop word is not included in the generated text.
Added a unit test (tests stop words for all models)
We debated whether to implement the stop words on the PromptNode abstraction level or PromptTemplate. As for our immediate needs having stop words on the level of PromptNode is satisfactory - hence this PR. If we find use cases where having stop words on the level of PromptTemplate abstraction is necessary, we'll also implement it at that level. In that case, the stop words from PromptTemplate will …
> feat: PromptNode - implement stop words

- haystack/nodes/file_converter/parsr.py
Remove a duplicated `super().__init__()` call in `ParsrConverter.__init__()`.
Didn't test it.
None.
> fix: Remove double super class init from ParsrConverter init

- haystack/document_stores/base.py
- haystack/document_stores/search_engine.py
- haystack/modeling/infer.py
- haystack/nodes/_json_schema.py
- haystack/nodes/audio/_text_to_speech.py
- haystack/nodes/file_classifier/file_type.py
- haystack/nodes/preprocessor/preprocessor.py
- haystack/nodes/prompt/prompt_node.py
- haystack/nodes/retriever/_embedding_encoder.py
- haystack/nodes/retriever/dense.py
- haystack/nodes/retriever/multimodal/embedder.py
- haystack/pipelines/base.py
- haystack/schema.py
- pyproject.toml
n/a
- re-enables PyLint's `f-string-without-interpolation`
- removes a few other warnings that were silencing no issues:
-  `wrong-spelling-in-docstring`
-  `wrong-spelling-in-comment`
- `anomalous-backlash-in-string`
- CI
Don't worry for the diff: this PR only removes `f` prefixes from strings that are doing no interpolation.
~I added tests that demonstrate the correct behavior of the change~
~I documented my code~
> chore: enable `f-string-without-interpolation`

- haystack/nodes/prompt/prompt_node.py
- test/nodes/test_prompt_node.py
- minor additional fixes for #3884 
- I created an inconsistency where simple prompts i.e. `node("What is the capital of Germany?")` do not pass the stop words to the underlying model invocation
- I corrected this inconsistency (all prompts are equal) and added more stop words unit tests variants
- Implement stop words consistently for all prompts (simple, with default installed template, and new prompt template)
- Allow kwargs stop_words to override the default stop words set in PN init
- Add more unit tests
Added more variants of `test_stop_words` unit tests
Ping me if anything not clear
> refactor: Improve stop_words handling, add unit test cases

- haystack/__init__.py
- haystack/environment.py
- test/others/test_utils.py
- fixes #3521
setting TORCH_FORCE_WEIGHTS_ONLY_LOAD to 1 by default
added unit test
To load secure-only model pytorch requires the value of TORCH_FORCE_WEIGHTS_ONLY_LOAD to be ["1", "y", "yes", "true"]
For more details please refer to pytorch PR https://github.com/pytorch/pytorch/pull/87443.
> feat: adding secure loading of models by default for haystack

- haystack/nodes/prompt/prompt_node.py
- test/nodes/test_prompt_node.py
- fixes #3878
As noted by the author of #3878 the results of intermediate PromptNode(s) in the pipeline are stored under the invocation_context results variable thus making them a bit less accessible than having it ideally as they key under the root of the resulting dictionary returned to the Haystack pipeline user. 
The change required is relatively simple. We elevate `output_variable` value under the root output dictionary returned to the Haystack pipeline user. However, we also leave it in invocation_context so other nodes down the pipeline can use it. 
No new tests were added but the existing tests have been adjusted to check for presence of `output_variable` in the resulting dictionary. We also check the value of that variable for validity. 
There is some duplication of keys and …
> feat: Expose `output_variable` in PromptNode result, adjust unit tests

- haystack/nodes/reader/farm.py
- n/a
This PR changes the type of the `private` argument in `FARMReader`'s `save_to_remote` method from `Optional[bool]` to `bool` and sets the default value to `False`.
mypy
This issue came up due to many recent PRs failing the mypy check. `huggingface_hub`'s `create_repo` method only allows bools as parameter for `private`, `None` is not allowed.
> fix: Fix type in `FARMReader`'s `save_to_remote`

- haystack/nodes/prompt/prompt_node.py
- test/nodes/test_prompt_node.py
I stumbled on a unit test case where I wanted to use *two* exact YAML definitions of a PromptNode in the pipeline. The pipeline refused to include these two PromptNode(s), complaining that they are the same objects. I remembered that I implemented the PromptNode hashes and equality (in the early version) to prevent multiple same PromptNodes from being injected in the pipeline. That was when we didn't have the PromptModel object, only heavyweight PromptNode. However, now that we can have multiple "light" PromptNodes sharing PromptModel, this reasonable restriction can potentially become a liability. 
To prevent potential issues in the future, I believe we should remove hash and equality functions from PromptNode. This will be in line will all other components in Haystack. None of them …
> refactor: Remove PromptNode hash and equality functions

- .github/actions/python_cache/action.yml
- .github/workflows/tests.yml
https://github.com/deepset-ai/haystack/actions/runs/4014088908/jobs/6894191362
Remove the step that install `mypy` deps in the `python_cache` action.
`mypy` deps installation is now done directly when invoked on modified `*.py` files, this should also make it faster since it only installs depedencies necessary to test those files.
This PR also removes the `mypy` caching step in `python_cache` action as there would be nothing to cache.
I didn't, it's CI stuff. I just tested that the commands are correct by running them locally first.
The step that install `mypy` deps in `python_cache` was called with both `--install-types` and `--non-interactive` flags, as documented [here](https://mypy.readthedocs.io/en/stable/running_mypy.html#library-stubs-not-installed) those two flags used in …
> ci: Remove mypy deps install step in python_cache action

- .github/workflows/readme_sync.yml
- docs/pydoc/renderers.py
- fixes n/a
Bump pydoc-markdown to 4.6.4 so we pull in some improvements and fixes we need.
The internal API has changed a bit and I had to adjust two method calls but the logic stays the same
> chore: bump pydoc-markdown version used in the CI

- docs/_src/api/pydoc/transformers-img-to-text.yml
Add the API documentation for TransformersImageToText
> Docs: Add TransformersImageToText API doc

- docs/_src/api/pydoc/file-converters.yml
The CSVConverter is missing from API documentation.
Add CSVConverter to API docs.
> Docs: Add CSVconverter to API docs

- haystack/nodes/connector/crawler.py
Fix #3932
Updates the Crawler docstring to reflect change in documentation.
Documentation has already been updated.
See [this Colab notebook](https://colab.research.google.com/drive/1b05bB2-SjVtjY3mrECKL0MbZOS1jgDMa?usp=sharing) to test it out.
> docs: Update Crawler docstring for correct usage in Google colab

- .github/workflows/examples-tests.yml
- examples/basic_faq_pipeline.py
- examples/basic_qa_pipeline.py
- fixes flakyness in example tests
move the call to `launch_es` in the `main` function of the script, so that it won't be called from the tests.
CI
> ci: do not run `launch_es` in the CI

- .github/workflows/cml.yaml
- n/a
Benchmarks are supposed to run only manually or when a PR is labelled in a certain way. This means that the jobs are almost always skipped, cluttering the list of checks you see in a PR.
Run benchmarks manually, removing the PR event trigger
CI
> chore: make the benchmark workflow run only manually

- .github/workflows/tests.yml
- fixes CI failures
Pin Weaviate Docker tag, as `latest` might point to preview or unstable images
CI
> ci: pin weaviate version

- haystack/nodes/__init__.py
n/a
Allow users to import `TransformersImageToText` as `fro,m haystack.nodes import TransformersImageToText`
n/a
n/a
> Missing import for `TransformersImageToText`

- .github/workflows/docker_release.yml
Simplifies the docker images testing using a bash function and making it clearer what's the cause of the failure.
Also fixes an issue that was causing tests to always fail. 
The `--platform` flag of the `docker run` command was set after the image name making it part of the command to run in the image instead of an option of the `docker run` command. 
I ran the bash script locally, final test will be running in CI.
This will fix `docker_release.yml` failures in `main` like [this one](https://github.com/deepset-ai/haystack/actions/runs/4025115208/jobs/6917929038).
> Simplifies and fix docker images tests on release

- .github/workflows/docker_release.yml
N/A 
Remove Haystack Docker image after testing it to prevent GtiHub runner to fail because there is no space left.
See [this workflow run](https://github.com/deepset-ai/haystack/actions/runs/4044500130) as an example.
Can't test it.
N/A
> ci: Delete Docker images after testing to prevent workflow failure

- haystack/nodes/prompt/prompt_node.py
- test/nodes/test_prompt_node.py
This is the second PR to fix #3817.
Earlier attempt for this was at https://github.com/deepset-ai/haystack/pull/3827 . At the comments of that PR we agreed with @vblagoje  that I will make a new attempt to fix this issue.
- fixes #3817 
- add the prompt used by the `PromptNode` to the debug log
- add the prompt(s) used by the `PromtNode` to the "standard" debug output of the pipeline ([see](https://github.com/deepset-ai/haystack/blob/main/haystack/pipelines/base.py#L481) and [see](https://github.com/deepset-ai/haystack/blob/ad8fbe56eef1cbc68a741db7772b07c89e1c1c78/haystack/nodes/base.py#L256) ). As the constructed prompt is NOT an input or an output to the PromptNode, the prompt ended up being included in the debug as a `runtime` debug info, [see …
> fix: Add a verbose option to PromptNode to let users understand the prompts being used #2

- haystack/telemetry.py
- fixes #3994
So far, we were just setting the log level of posthog to CRITICAL. With this PR we now also add a handler to the posthog logger that prevents it from from sending errors to stderr when an exception is encountered during an emit() call. Further, we prevent posthog from propagating any log messages to loggers higher in the chain.
I changed the url in telemetry.py that is `posthog.host = "https://tm.hs.deepset.ai"` to `"https://tm.hs.deepset.ai/services"` to trigger a 403 error (503 should work just the same).
As an alternative, there is a module-wide setting that prevents any module from sending errors that happen in logging to stderr. It's documented here: https://docs.python.org/3/howto/logging.html#exceptions-raised-during-logging
```python
import logging …
```
> fix: prevent posthog from sending errors to stderr

- haystack/nodes/prompt/prompt_node.py
- fixes https://github.com/deepset-ai/haystack/issues/4020
In PromptNode reuse tokenizer instead of loading a new one for stop words when using HF models.
Existing tests
> refactor: In PromptNode reuse tokenizer instead of loading new one for stop words

- README.md
- No issue. Many badges could be added (YouTube channel etc.) but it shouldn't become a wall of badges. Discord invite link definitely makes sense in my opinion.
- add discord badge with invite link showing number of active users
- changed the style of the Twitter badge. I can also change it back if you want @TuanaCelik I changed it so that it's consistent with the style of all the other badges.
Tried it manually. Server id extracted from the desktop app.
> chore: add discord badge to readme

- .github/config/pypi-release-slack-notification.yml
- .github/workflows/pypi_release.yml
Partly fixes #3116.
Automate the build and PyPi publish steps of the release process, the workflow will be triggered each time a `v[0-9].[0-9]+.[0-9]+*` tag is pushed.
I didn't test the whole process as that would imply making a release, also there's close to nothing to test.
Though I tested that the Slack notifications would be sent as expected by using [a separate repository](https://github.com/silvanocerza/nodenode) with a similar `act10n/slack` config file.
⚠️⚠️⚠️
`PYPI_API_TOKEN` secret must be set before merging this PR.
The secret must contain an [API token](https://pypi.org/help/#apitoken) of a user authorized to publish the project.
⚠️⚠️⚠️
The notifications received on Slack will be similar to this:
Ideally in the future the success of this workflow will trigger the workflow that …
> ci: Automate release on PyPi

- .github/workflows/compliance.yml
- .github/workflows/examples-tests.yml
- .github/workflows/tests.yml
Bump all occurences of `act10ns/slack` from `v1` to `v2`.
There's also two occurences in the `compliance.yml` workflow that use a specific commit, I bumped those too.
There are no major changes in `v2` apart from the Node version used by the action. 
`v1` was still using Node.js 12 that's been deprecated in Github Runnners, this will silence the warnings in most workflows.
For more info see official [GH blog post](https://github.blog/changelog/2022-05-20-actions-can-now-run-in-a-node-js-16-runtime/).
> ci: Bump act10ns/slack from v1 to v2

- pyproject.toml
- CI is red on `main`
Quick and dirty fix, let's just ignore the error (along with the many we already have 😢)
> ci: latest version of pylint is failing, ignore new errors

- .github/actionlint.yml
- .github/actions/python_cache/action.yml
- .github/workflows/minor_version_release.yml
- .github/workflows/readme_sync.yml
- .github/workflows/workflows_linting.yml
- .pre-commit-config.yaml
Add a pre-commit hook and a related workflow to run [`actionlint`](https://github.com/rhysd/actionlint), a static linter for Github Workflows .yaml files.
The hook will only run if any workflow file is edited, and only on those files.
The workflow will run only when a PR that edits a file in `.github/workflows` is edited, it will lint all workflow files.
I ran the hook locally.
N/A
> ci: Add linting of workflow and related pre-commit hook

- pyproject.toml
`pylint` version `2.16.0` crashes and is causing CI to fail repeatdly, PyCQA/pylint#8163 fixes the issue but has not been released yet.
So we fix `pylint` to `2.15.10` for the time being to keep CI from failing, we'll unfix it as soon as a new version that includes the fix is released.
> ci: Fix pylint version to prevent crash

- .github/workflows/pypi_release.yml
Add a missing `VERSION` env var in `Notify Slack` step in `pypi_release.yml` workflow.
N/A
> ci: Add missing env var in PyPi release slack notification

- haystack/nodes/connector/crawler.py
- fixes #4002 
There is no single reason for the error reported in the issue. (`WebDriverException: unknown error: DevToolsActivePort file doesn't exist while trying to initiate Chrome Browser`)
It is a generic error.
However, in the [StackOverflow thread](https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t) suggested by @sjrl, there are several strategies to solve/mitigate these errors.
- I added some reasonable `webdriver_options` when running on Windows
- Little refactoring of the options code
CI
> fix: make the crawler more robust on Windows

- .github/workflows/readme_sync.yml
- fixes https://github.com/deepset-ai/haystack/actions/runs/4083866575
Leftover from last PR: sync the files from the new path
> fix: readme sync workflow wrong path

- haystack/pipelines/ray.py
- fixes #4065
RayPipeline with a decision node fails.
Error message
```
File ~/.local/share/virtualenvs/llm_demo-hW1oTPAF/src/farm-haystack/haystack/pipelines/ray.py:255, in RayPipeline._add_ray_deployment_in_graph(self, handle, name, outgoing_edges, inputs)
253     assert "output_" in input_edge_name, f"'{input_edge_name}' is not a valid edge name."
254     outgoing_edges_input_node = self.graph.nodes[input_node_name]["component"].outgoing_edges
--> 255     assert int(input_edge_name.split("_")[1]) <= outgoing_edges_input_node, (
256         f"Cannot connect '{input_edge_name}' from '{input_node_name}' as it only has "
257         f"{outgoing_edges_input_node} outgoing edge(s)."
258     )
259 else:
260     outgoing_edges_input_node = self.graph.nodes[i]["outgoing_edges"]
TypeError: '<=' …
```
> fix: use correct count of outgoing edges in RayPipeline

- haystack/document_stores/sql.py
- fixes #3834
When we delete documents or labels in SQLDocumentStore, the inner SQL query is aliased now.
MYSQL doesn't allow queries where changes are made to a table that is referenced in an inner table [(stackoverflow)](https://stackoverflow.com/questions/4429319/you-cant-specify-target-table-for-update-in-from-clause).
Therefore, we now use an alias for the table in the inner query.
Before (simplified):
```sql
DELETE FROM document WHERE document.id IN (SELECT document.id 
FROM document 
WHERE document.`index` = %(index_1)s AND document.id IN (%(id_1_1)s))
```
After (simplified:
```sql
DELETE FROM document WHERE document.id IN 
(SELECT document_inner_table.id FROM (SELECT * FROM document) AS document_inner_table
WHERE document_inner_table.`index` = %(index_1)s AND …
```
> fix: Add inner query for mysql compatibility

- .github/workflows/linting.yml
Ignore tests files in `pylint` workflow check.
Fixes linting in PRs like [this failure here](https://github.com/deepset-ai/haystack/actions/runs/4105464145/jobs/7082357140).
> ci: Fix pylint workflow check running on tests files

- haystack/nodes/prompt/prompt_node.py
- test/nodes/test_prompt_node.py
- no related issue
Adds __repr__ method to PromptTemplate
See unit test
> fix: Add PromptTemplate __repr__ method

- haystack/pipelines/ray.py
- fixes #4077
Currently you can only run one` RayPipeline` within one app, because the `RayPipeline` always tries to initialize a new Ray connection - if one is already initialized then it will simply fail.
See the Ray initialization at https://github.com/deepset-ai/haystack/blob/main/haystack/pipelines/ray.py#L80
Due to that, the app will fail when it starts to initialize the second `RayPipeline`, as the first one has already initialized the Ray connection and an error will be thrown:
```
File "/app/raypipelines/qa_pipeline.py", line 87, in __init__
self.raypipeline = RayPipeline.load_from_yaml(
File "/hW1oTPAF/src/farm-haystack/haystack/pipelines/ray.py", line 193, in load_from_yaml
return cls.load_from_config(
File "/hW1oTPAF/src/farm-haystack/haystack/pipelines/ray.py", line 101, in …
```
> feat: Support multiple `RayPipelines`

- haystack/nodes/answer_generator/openai.py
- haystack/nodes/prompt/prompt_node.py
- test/nodes/test_prompt_node.py
- fixes #4069
As specified in #4069, if the `finish_reason` in the OpenAI response is `"length"`,
the completion is probably truncated.
We want to print a warning that suggests increasing the `max_tokens` parameter.
Added a new test.
(I didn't verify it locally, because I don't have OpenAI credits :smiley:) 
Also updated some old URLs
> feat: OpenAI - warn users if `max_tokens` is too short

- .github/workflows/rest_api_tests.yml
Add missing env vars in `rest_api_tests.yml`.
We moved `rest_api` from `tests.yml` with #4086 but I forgot to also move the env vars used by those tests.
> ci: Add missing env vars in rest_api CI tests

- haystack/nodes/retriever/dense.py
- test/nodes/test_retriever.py
- fixes #4012
Following the suggestion laid out in issue #4012 I removed the extra loop and just call `embed_queries` directly since `embed_queries` already batches the queries inside the function. This removes the excessive tqdm printing and removes unnecessary double batching. 
Reactivated existing unit tests for the embedding retriever. Reran the colab notebook provided in the issue and checked the printing is now a single tqdm bar.
> Remove double batching in retrieve_batch

- .github/workflows/linting.yml
Skip `pylint` if there are no modified files to check. This is the same approach used in the `mypy` check.
Can't test.
This is a corner case that would happen in a PR that modifies a `pyproject.toml` file without editing any `*.py` files. See #4088 as an example.
> ci: Fix pylint CI check running with no files

- rest_api/rest_api/controller/search.py
- rest_api/test/test_rest_api.py
Query filters for date types are currently not working on the REST API. 
For instance, the query below 
```json
{
"query": "blah",
"params": {
"filters": {
"date": {
"$gte": "2013-09-11",
"$lt": "2015-08-31"
}
}
}
}
```
gets the date filter clause typecasted as a list by `_format_filters()`:
```python
{'date': [{'$gte': '2013-09-11', '$lt': '2015-08-31'}]}
```
This breaks things downstream in the construction of the OpenSearch query with the `ComparisonOperation`.
This PR removes the `_format_filters()` method entirely as its legacy code. 
In addition, it would ease maintenance & documentation if we keep the Pipeline & REST API filter format consistent. 
None as I could not find an integration test suite for the REST API that could cover this case.
I'm not sure if it has implications for …
> fix: query filters in REST API

- haystack/document_stores/memory.py
- test/document_stores/test_memory.py
- A test in #4048 is failing due to missing BM25 support for tables in `InMemoryDocumentStore`.
This PR adds BM25 support for tables in `InMemoryDocumentStore` by converting them to strings using pandas' `to_csv` method.
I added an integration test.
> feat: Add BM25 support for tables in InMemoryDocumentStore

- .github/workflows/tests.yml
Disable the `tests.yml` workflow from running if `*.py` files in `.github/` are modified. 
Not essential but avoids running tests when not necessary.
> ci: Exclude .github folder from triggering tests

- .github/utils/docstrings_checksum.py
- .github/workflows/docstring-labeler.yml
- fixes #3967
This PR introduces a new workflow that will run for every PR and labels them if there's been any docstrings edit.
I ran the `docstrings_checksum.py` script locally. We'll test the workflow later.
I'll probably create a follow-up PR that edits a random docstring and use this as base to verify the workflow behaviour.
> ci: Add workflow to label PRs that edit docstrings

- haystack/nodes/reader/base.py
- test/pipelines/test_eval.py
- test/pipelines/test_eval_batch.py
- fixes #4092
This PR reverts a change introduced in #3773. In this PR, we make sure to deduplicate same Documents in a MultiLabel based on their Document ID when doing isolated evaluation of Reader nodes.
Also, we were missing deduplication in `ran_batch`, so added it there as well.
I adapted `EVAL_LABELS` by adding a second `Label` using the same Document but a different Answer span. I added a check to `test_extractive_qa_eval_isolated` to check that the number of produced predictions does not exceed top_k_per_candidate.
> fix: Deduplicate same Documents in isolated evaluation of Reader

- docs/pydoc/config/prompt-node.yml
- fixes n/a
This PR adapts the configuration of PromptNode API documentation to exclude `PromptModelInvocationLayer`, `StopWordsCriteria`, `HFLocalInvocationLayer`, and `OpenAIInvocationLayer` from the API reference of Haystack documentation.
I ran `pydoc-markdown` locally.
> docs: Remove some classes regarding PromptNode from API reference docs

- .github/workflows/docker_release.yml
This PR sets the `load` argument to `true` for the steps that build Docker images that will be tested in the following steps. 
That will make the `docker/bake-action` call `docker buildx bake` with the `--load` flag so the built images will also be saved in the `docker images` registry and will be reused by the test steps with no need to pull them.
See the [Docker docs](https://docs.docker.com/engine/reference/commandline/buildx_build/#load) for info on `--load` flag.
I can't.
Am not sure if the `load` and `push` flag will conflict with each other, I'd expect not to. 
If it will break in `main` I'll revert it right away.
> ci: Add load arg to docker/bake-action before testing Docker images

- .github/workflows/docker_release.yml
Fixes failing [`docker_release.yml` workflow](https://github.com/deepset-ai/haystack/actions/runs/4145863954/jobs/7170799165#logs).
Turns out that we can't set both `load` and `push` arguments to `true`, that makes the `bake` action fail.
> Revert changes introduced in PR #4124

- annotation_tool/README.md
- related to #3958
This PR removes the statement that we can import labels from an existing SQuAD-style dataset from the Annotation Tool README and instead adds that we can import a list of predefined questions.
> docs: Update Annotation Tool README.md

- haystack/document_stores/memory.py
- test/document_stores/test_memory.py
- fixes #4080
- implement @bogdankostic's proposal: 
> ignoring the Documents without embeddings during retrieval. (We should probably print a warning message for this case.) 
- remove mypy ignore comments and fix the errors
- fix `get_scores_numpy `and `get_scores_torch` methods (there were some errors also pointed out by mypy)
- CI
- added new test for documents without embeddings
> refactor: `InMemoryDocumentStore` - manage documents without embedding & fix mypy errors

- haystack/nodes/prompt/prompt_node.py
- test/nodes/test_prompt_node.py
- fixes N/A
I believe adding the `model_kwargs` parameter to the `__init__` function for `PromptNode` would allow users to easily set the default values of the underlying model without being required to pass a `PromptModel`. We already pass these parameters`model_name_or_path, max_length, api_key, use_auth_token, use_gpu, devices` from `PromptNode.__init__` to the loading of the underlying `PromptModel` so I think adding `model_kwargs` here also makes sense.
This also would simplify the yaml file (example added in tests) to be able to set the default model parameters from the initialization of the `PromptNode`. It would not require creating a separate `PromptModel` to be able to set default parameters, which I think streamlines the yaml file. 
Added two new unit tests
> feat: Add model_kwargs option to PromptNode

- .github/utils/docstrings_checksum.py
- .github/workflows/docstring-labeler.yml
This changes the event that triggers the docstring-labeler.yml workflow from [pull_request](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) to [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target).
The job has been changed a bit too.
Instead of executing the `docstrings_checksum.py` directly after checkout we first copy it to a temp directory after checking out base ref. This way we prevent executing code in forks' PRs since the version of the script will always be the one from the PR's base.
A malicious user would have to manage to merge in `main` a modified version of the script before being able to exploit it.
This is probably a better and simpler …
> ci: Update docstring-labeler.yml workflow to safely run in PRs from forks

- .github/actionlint.yml
- .github/workflows/docker_release.yml
Use larger builder to fix out of space errors during Docker images builds.
We triggered a build with this branch, [this is the run](https://github.com/deepset-ai/haystack/actions/runs/4196301152/jobs/7277152867).
N/A
> ci: Use larger runner for Docker release workflow

- haystack/nodes/prompt/prompt_node.py
This is a super small PR based on a problem I noticed in the `PromptNode` API reference. The `prompt_template` argument for the `.prompt()` function doesn't only have to be the name, it can also be the object as far as I see..
> chore: Fixing PromptNode .prompt() docstring to include the PromptTemplate object as an option

- .github/workflows/xpdf_release.yml
- docker/Dockerfile.base
- docker/Dockerfile.xpdf
- docker/docker-bake-xpdf.hcl
Speed up the base Docker images build process by removing the `xpdf` build and moving into a separate container, so that we'll need only to `COPY --from=deepset/xpdf:latest` to get the `pdftotext` binary in the published image.
The `deepset/xpdf` image will be built whenever `docker/docker-bake-xpdf.hcl` or `docker/Dockerfile.xpdf` are modified in `main`.
Can't be tested until it's merged. Am pretty confident it will work as the process is extremely similar to the Haystack images.
I tried another approach with branch [`xpdf-build`](https://github.com/deepset-ai/haystack/tree/xpdf-build) but sadly it's not feasible.
The idea was to run the builds in CI and upload the binaries to S3, so that the Haystack base image could download it directly with no need to build it each time.
But we can't …
> ci: Move xpdf build into separate container

- haystack/schema.py
- test/others/test_schema.py
- n/a
This PR removes the `id_hash_keys` parameter in the `from_dict` method of `Document`. `id_hash_keys` is deprecated since 1.13 and should be removed in 1.15 according to our deprecation policy.
> refactor: Remove `id_hash_keys` parameter in `from_dict` method

- docker/Dockerfile.xpdf
Fix [`publish-xpdf-image`](https://github.com/deepset-ai/haystack/actions/runs/4224096355/jobs/7334623717) workflow failing.
`curl` is failing in the image cause of missing certificates, installing `ca-certificates` will solve the issue.
Built image locally.
I didn't notice the issue in the PR that introduced the building of the container as I was hotspotting in the airport and didn't want to waste data downloading Docker images. <3
> ci: Add ca-certificates installation to xpdf container

- docker/Dockerfile.base
Docker release is failing cause of missing `git` in the base image, add a step to install it and fix the issue.
Built the image locally.
N/A
> ci: Fix Dockerfile.base failing cause of missing git

- docker/Dockerfile.api
- No issues
Corrected `chmod` permissions
checked manually by building the image locally
> fix: allowing file-upload api to write files to disk

- haystack/nodes/answer_generator/openai.py
- test/nodes/test_generator.py
- fixes #4211 
Fixed bug for using custom templates in OpenAIAnswerGenerator due to a bad check.
Added new test using custom template.
> fix: Fix bug in prompt template check of OpenAIAnswerGenerator

- haystack/nodes/other/shaper.py
- test/nodes/test_shaper.py
- fixes N/A
- Fix bug in storing multiple outputs
- Checking if output keys and output_values are the same length and if not print a warning to the user
Added two new tests
> fix: Shaper store all outputs from function

- docker/Dockerfile.base
Add missing dependencies in `Dockerfile.base` image to fix build failure.
I built the image locally from start to end.
I was dumb enough to not run the build from start to finish after the fix from #4210 but only waited for the git fetch to work and then interrupted the build.
I should have caught that then. 🤦
> ci: Fix Dockerfile.base failing cause of missing dependencies

- test/nodes/test_prompt_node.py
- fixes regression in `main` https://github.com/deepset-ai/haystack/actions/runs/4240528244/jobs/7370627082
Do not use full match to pass the test
> fix: relax test assertion

- haystack/nodes/other/shaper.py
- test/nodes/test_shaper.py
- fixes https://github.com/deepset-ai/haystack/issues/4230
- add `publish_outputs` option, defaults to `True` (same behavior as before)
- when `False` `outputs` won't be published to the pipeline result
- add `answers` to the eligible outputs that can be published
- added tests
- This will save us two additional `Shapers` in a QA pipeline using `PromptNode`. See the issue above for more information.
- The yaml of the issue pipeline would then look like this:
```yaml
version: '1.13.2'
components:
- name: DocumentStore
type: InMemoryDocumentStore
- name: Retriever
type: BM25Retriever
params:
document_store: DocumentStore
top_k: 3
- name: PromptModel
type: PromptModel
params:
model_name_or_path: google/flan-t5-large
model_kwargs:
model_kwargs:
num_return_sequences: 3
num_beams: 3
- name: …
```
> fix: add option to not override results by `Shaper`

- .github/workflows/openapi_sync.yml
Add missing dependencies installation in `openapi_sync.yml` workflow.
Will fix [this failure](https://github.com/deepset-ai/haystack/actions/runs/4245094590/jobs/7380143850).
> ci: Add missing dependencies in openapi upload workflow

- .github/workflows/tests.yml
- .github/workflows/tests_skipper.yml
Add a new `catch-all` job in `tests.yml` that runs only after all integration tests have passed.
This also adds a `tests_skipper.yml` that runs whenever `tests.yml` doesn't, it only contains a `catch-all` job.
This way we'll be able to mark only the `catch-all` job as required instead of having to create a workflow that mirrors the `tests.yml`.
Can't be tested locally.
I already added the `Catch-all check` as required in the repo settings.
> ci: Add a simple way to skip required tests checks

- .github/workflows/tests.yml
- n/a
- Sets an env var called `HAYSTACK_TELEMETRY_VERSION` to 0 in the test's workflow, to prevent spamming the telemetry server with useless events.
n/a
Double-check whether this is the right way to set env vars in workflows.
> bug: disable telemetry in CI

- .github/workflows/openapi_sync.yml
Add a step to retrieve specs ID for the version that triggered the workflow and use that ID to upload the updated specs. 
I ran the workflow on this branch using dry run to avoid uploading the specs.
The workflow run: https://github.com/deepset-ai/haystack/actions/runs/4253725575/jobs/7398971419
This is safe as long as we keep creating new versions in Readme.io using the previous version as base.
The call to Readme.io API returns a list of specs like the one below, the `version` field is the spec id we need and it's always identical for every item. Yes, the ID is not the `id` field for some reason. 🤷 
```
$ curl https://dash.readme.com/api/v1/api-specification -u "$README_API_KEY:" --header 'x-readme-version: v1.14' | jq
[
{
"title": "Haystack REST API",
"source": "file",
"_id": …
```
> ci: Fix OpenAPI spec sync

- haystack/document_stores/deepsetcloud.py
- haystack/document_stores/weaviate.py
- haystack/modeling/training/base.py
- haystack/nodes/_json_schema.py
- haystack/nodes/audio/_text_to_speech.py
- haystack/nodes/connector/crawler.py
- haystack/nodes/file_classifier/file_type.py
- haystack/pipelines/base.py
- haystack/pipelines/config.py
- haystack/utils/docker.py
- haystack/utils/linting.py
- haystack/utils/squad_data.py
- haystack/utils/squad_to_dpr.py
- pyproject.toml
- rest_api/rest_api/__about__.py
- rest_api/rest_api/pipeline/__init__.py
- test/benchmarks/nq_to_squad.py
- test/others/test_utils.py
- test/pipelines/test_pipeline.py
- fixes #4202
- Replace all direct calls to `logging.debug|info|warning|error|critical` with calls to each file's dedicated logger instance.
- Add a custom PyLint checker to prevent future occurrences of the same issue
- Add a test that makes sure that handlers are not set.
- CI
- Manual run of PyLint locally
Check out the linked issue for the reasoning behind this change. The only changes applied here are related to logging lines and replace `logging` with `logger`, adding the linter and the test: everything else is out of scope.
> refactor: remove direct logging without a logger

- .github/workflows/openapi_sync.yml
Change the property retrieved from `api-specification` endpoint.
I ran the commands locally.
I cleaned up some files on Readme.io so now we can be sure that `/api/v1/api-specification` endpoint will always return only a single item list.
> ci: Fix OpenAPI specs upload

- .github/workflows/minor_version_release.yml
Remove generation of OpenAPI specs when running `minor_version_release.yml` since they're not necessary anymore.
OpenAPI specs are now generate and uploaded by `openapi_sync.yml` only when necessary.
There are some styling changes in the PR too to fix `actionlint` complaints.
> ci: Remove unnecessary operations in minor_version_release.yml

- .github/workflows/docker_release.yml
Split build process of Docker images using `matrix` strategy, this way we'll have a single job for each target and platform combination.
Triggered a workflow in this branch.
https://github.com/deepset-ai/haystack/actions/runs/4263932762
I removed the last step that was testing the `api-latest` target using the `docker-compose.yml` in the root as I didn't find it that useful, and neither it was easy to integrate with the new matrix strategy.
Also I changed `ubuntu-latest-4-cores` back to `ubuntu-latest`.
> ci: Parallellize Docker build job

- haystack/modeling/model/feature_extraction.py
- test/nodes/test_reader.py
- fixes https://github.com/deepset-ai/haystack-private/issues/48
- Changed int16 to int32
- Added test case that failed before and now passes
- Added integration test
I think int32 is sufficient because Documents with more than 2^32 ~4 billion characters are unlikely and would also be problematic in number of tokens and the time it takes to tokenize. 2^16 was just ~65000 characters so not a surprise that we hit that limit now.
> fix: FARMReader produces Answers with negative start and end position

- haystack/document_stores/opensearch.py
- haystack/testing/document_store.py
- fixes https://github.com/deepset-ai/haystack/issues/4292
- check if index exists before IVF cleanup
- added test
> fix: `OpenSearchDocumentStore.delete_index` doesn't raise

- .github/workflows/docker_release.yml
- .github/workflows/pypi_release.yml
Make `docker_release.yml` run only on push/merges in `main` and after the `pypi_release.yml` workflow is sucessful.
`workflow_run` can't be tested. 
I verified it would run on push by triggering it in this branch just to verify it would start, I cancelled the job right after.
The run is [here](https://github.com/deepset-ai/haystack/actions/runs/4294119725).
This is done in preparation to future changes in the `Dockerfile.base` that will install Haystack directly from PyPi with no need to clone the repo.
> ci: Change docker_release.yml workflow to run after successful PyPi release

- docs/pydoc/config/shaper.yml
- n/a
This PR fixes the search path for creating API docs for Shaper.
I tested this manually.
> docs: Fix search path for Shaper API docs

- .github/workflows/docstring-labeler.yml
`docstring-labeler.yml` workflow is not working correctly as the `GITHUB_WORKSPACE` variable is not stored in the `env` context.
This PR fixes that.
N/A
> ci: Fix docstring-labeler.yml workflow

- pyproject.toml
New version of `requests-cache` released yesterday is causing segfaults in certain tests.
Here we pin it to fix the segfaults.
Run segfaulting tests locally.
N/A.
> test: Pin requests-cache test dependency to <1.0.0

- haystack/nodes/retriever/_openai_encoder.py
- haystack/nodes/retriever/dense.py
- test/conftest.py
- test/nodes/test_retriever.py
- fixes #3890
- Azure OpenAI endpoints can be enabled on the EmbeddingRetriever
- To avoid turning on/off all third-party tests if only one env is not set up, separate tests should be run.
Current tests, new tests and local tests using Azure OpenAI API
- Same pattern used by @vblagoje on the AnswerGenerator and related code/tests were adopted with minor changes
- Azure OpenAI embedding endpoint doesn't accept multiple _inputs_; so we are doing one query per input
- Azure OpenAI only supports the latest ada-002 model and similarity ones, none of the search are supported
- AZURE_OPENAI_DEPLOYMENT_NAME_EMBED has been used because Azure demands a unique name for deployments, and AZURE_OPENAI_DEPLOYMENT_NAME is being used for the davinci-003 deployment.
> feat: Add Azure OpenAI embeddings support

- haystack/nodes/__init__.py
- haystack/nodes/prompt/__init__.py
- haystack/nodes/prompt/prompt_node.py
- haystack/nodes/prompt/providers.py
- test/nodes/test_prompt_node.py
Not fixing any issues, refactors PromptNode by separating all PromptModelInvocationLayer implementations to a separate file called providers.py. In addition, there are a few more enhancements:
- Simplified custom layer injection via PromptModel init
~~- Users can provide their custom PromptModelInvocationLayer using class reference~~ (Can't do this)
- Users can provide their custom PromptModelInvocationLayer using the name of the class str (pipelines YAML friendly)
- Added unit tests for custom PromptModelInvocationLayer 
- Some minor renamings in ValueErrors raised
Add providers.py
Move PromptModelInvocationLayer to providers.py along with all layers
Unclatters prompt_node.py and prepares codebase for the addition of new PromptModelInvocationLayers (cohere, chatgpt)
Added unit tests; see …
> refactor: Separate PromptModelInvocationLayers in providers.py

- .github/workflows/ci_metrics.yml
- .github/workflows/e2e.yml
- .github/workflows/linting-skipper.yml
- .github/workflows/linting.yml
- .github/workflows/rest_api_tests.yml
- .github/workflows/tests.yml
- .github/workflows/tests_skipper.yml
Add a `ci_metrics.yml` workflow that, as the name implies, will send CI metrics to Datadog. This way we'll be able to better track trends in the CI, notice when tests are taking longer than usual, number of failures, contributors, PRs and what not.
We'll send metrics after a PR is opened or closed and when the following workflows finish running:
* `e2e.yml`
* `linting.yml` and `linting-skipper.yml`
* `rest_api_tests.yml`
* `tests.yml` and `tests_skipper.yml`
Before merging we need to add `DATADOG_API_KEY` as a repo secret.
There's an option to also collect steps metrics using the `collect-step-metrics`, I decided not to enable it as I feel it might create too much noise right now. Maybe we'll enable it in the future.
> ci: Add workflow to push CI metrics to Datadog

- .github/labeler.yml
Add the new `topic:promptnode` label to the workflow
> chore: add `topic:promptnode` label

- haystack/document_stores/sql.py
- fixes #4285
Since limiting the length of this value to 100 is too restrictive, I increased it to 1000.
CI.
_(The original issue went unnoticed also because we don't test `SQLDocumentStore `using PostgreSQL, and SQLlite doesn't enforce these constraints)_
> fix: increase `MetaDocumentORM` value length in `SQLDocumentStore`

- docker/Dockerfile.api
- rest_api/pyproject.toml
- fixes #3913 
This PR changes the Dockerfile of our REST API to use `uvicorn` as a server instead of using `gunicorn` with a single uvicorn worker.
cc: @mayankjobanputra 
I built and ran the Docker image locally.
> build: Use `uvicorn` instead of `gunicorn` as server in REST API's Dockerfile

- haystack/agents/base.py
- test/agents/test_agent.py
- Not an issue, small refactor to simplify agent tool interaction
- I discovered the need for this change when I added my tool with an output variable "output"
This refactoring inverts responsibilities (in a good sense) between the agent and the tool. Currently, we attempt to retrieve tool results from an agent code and guess the variable's name where the result is stored (if dictionary)! However, this approach will always be insufficient as the tool should extract its own result and return it to the agent, not vice-versa. 
Slightly adjusted unit tests and simplified code significantly. 
The diff should be enough to see this change. There is also a slight change regarding the agent transcript (line 202). We shouldn't hardcode the agent trace as custom agent prompts might not assume this …
> refactor: Simplify agent and tool interaction

- haystack/nodes/reader/table.py
Answer should be checked if it is not none before adding id to it
> fix: check that `answer` is not `None` before accessing it in `table.py`

- docs/pydoc/config/doc-language-classifier.yml
- haystack/nodes/doc_language_classifier/langdetect.py
- haystack/nodes/doc_language_classifier/transformers.py
- missing API docs from #2994
Added an API config file.
I've tried to be consistent with the [guide](https://github.com/deepset-ai/haystack/blob/main/docs/README.md), but please take a careful look.
> docs: add `DocumentLanguageClassifier` API

- .github/utils/pydoc-markdown.sh
- docs/pydoc/renderers.py
- docs/pydoc/requirements.txt
- fixes n/a
The conversion script fails when run locally because the reaadme.io api key is missing. This is problematic when you want to test the markdown generation locally.
Use a fake ID and spit a warning instead of `sys.exit`ing the program
Locally tested
I pinned `docspec` as a temporary fix for the current failure of the readme sync workflow.
> chore: make the docs generator runnable without an API key

- .github/workflows/tests.yml
Use a bigger runner to run certain tests in CI to avoid failure cause of limited disk space.
Failure example: https://github.com/deepset-ai/haystack/actions/runs/4407823874
N/A
> ci: Use bigger runner for integration-tests-linux

- pyproject.toml
- test/nodes/test_whisper.py
`espnet` depends on a library called `typeguard` that recently released a breaking `3.0.0` version, this PR fixes the version to `2.13.3` to fix import errors.
Run tests locally.
This is a quick fix that will be removed as soon as we merge #4391, we'll still need to port the fix in the `haystack-extras` repo.
> test: Fix audio tests failing

- haystack/nodes/prompt/providers.py
- haystack/utils/openai_utils.py
- pyproject.toml
- test/nodes/test_prompt_node.py
- related to #4286 
Token streaming significantly elevates UX as users don't have to wait for the entire LLM response to be generated but can start seeing the results of the model generation immediately and can follow its progression. Blame it on chatGPT if you want!
The only models that currently support streaming are OpenAI text and gpt turbo models. 
Unfortunately, there is an additional dependency here. However, it's very light and pure Python, so it shouldn't cause any issues.
> feat: add PromptNode OpenAI token streaming

- test/nodes/test_connector.py
Most `Crawler` tests run Selenium and make requests to local files, those are now marked as integration tests.
Only one test has been left as unit as it doesn't need to run Selenium or make requests. It also mock `selenium.webdriver`.
I run `pytest test/nodes/test_connector.py` locally.
N/A
> tests: Mark Crawler tests correctly

- test/conftest.py
The main `conftest.py` has an unnecessary import and related `ImportError` that returns a error that is not clear.
```
ImportError: Failed to import 'test', which is an optional component in Haystack.
Run 'pip install 'farm-haystack[test]'' to install the required dependencies and make this component available.
(Original error: No module named 'weaviate')
```
The `test` extra doesn't exist.
I ran `pytest -m "unit" test` locally and it passed. Am not sure about other tests.
This should fix some CI errors in #4429.
> test: Remove unnecessary imports in conftest.py

- .github/workflows/tests.yml
- fixes n/a
We are hitting the 5 concurrent jobs limit on OSX runner very often, and we have no workaround on the billing side. 
Let's stop running tests on OSX for the time being.
> test: stop running the CI on macos

- .github/workflows/readme_sync.yml
This PR makes `readme_sync.yml` in PRs that edit the docs configs without uploading to Readme.io, this way we'll avoid failure in `main` if there are issues with them.
Can't be tested locally.
We won't mark this as required, hopefully contributors wil be mindful of the check and avoid merging if it fails. ❤️
> ci: Run readme_sync.yml in PRs

- test/nodes/test_retriever.py
Test is failing randomly with no clear reason, fixing takes time and lots of investigation.
We'll skip it for the time being and then rework it.
> test: Skip flaky test_multimodal_retriever_query

- haystack/nodes/prompt/prompt_node.py
- haystack/nodes/prompt/providers.py
- test/prompt/test_prompt_node.py
- fixes #4322
Enables PromptNode to run [text-generation](https://huggingface.co/models?pipeline_tag=text-generation) models 
There has been a surge of requests to run bloomz and bloom models. People have contacted me personally about specialized LLMs they need to use and yet they can't.  
Add a unit test using a small text-generation model to test loading and simple invocation
Will add more tests, currently looking for immediate regression issues and potential roadblocks 
This PR is not ready for review; let's consult which other unit tests to add.
> feat: Enable PromptNode to use text-generation models

- rest_api/rest_api/controller/file_upload.py
- fixes #4404 
Allows to indicate additional params, besides the converter and preprocessor ones, in json format. For instance:
--form additional_params='{"index": "myindex"}' 
Running a local rest api and using this feature to specify the name of the elasticsearch index I wanted to use:
```
curl --request POST \
--url http://127.0.0.1:8000/file-upload \
--header 'accept: application/json' \
--header 'content-type: multipart/form-data' \
--form files="@{}" \
--form additional_params='{"index": "nvm"}' \
--form meta=null \;
```
> feat: add additional params to file upload endpoint

- haystack/nodes/retriever/_embedding_encoder.py
- haystack/utils/openai_utils.py
- haystack/utils/reflection.py
- test/others/test_utils.py
- fixes #4316
Remove all references to `retry_with_exponential_backoff` function and use `tenacity` library instead.
I didn't as I don't have API keys to run the tests that use exponential backoff. Also it's kinda hard to trigger it.
N/A
> refactor: Remove retry_with_exponential_backoff in favor of tenacity

- haystack/nodes/prompt/prompt_node.py
- test/prompt/test_prompt_node.py
Allow the ability to control debug output on PromptNode
- fixes #4477 
Debug was implicit in PromptNode.  Made it only output if you define either `debug: true` as global on the pipeline, or in `params` for the PromptNode
Made a punt at the code, then tested all the possible variations of global and specific debug settings against PromptNode and the pipeline.
> fix: Fix debug on PromptNode

- pyproject.toml
- fossa license check fails with `⚑ GPL-2.0-only license detected in rdflib@6.3.2` [here](https://github.com/deepset-ai/haystack/actions/runs/4526970233/jobs/7976623026)
- Exclude rdflib 6.3.2
CI tests on https://github.com/deepset-ai/haystack/pull/4437
We will deprecate KnowledgeGraph features so let's save some time and not spend much time on investigating this issue.
> bug: Exclude rdflib 6.3.2 because of license issues

- haystack/nodes/__init__.py
- haystack/nodes/retriever/__init__.py
- haystack/nodes/retriever/sparse.py
- haystack/pipelines/ray.py
Remove deprecated `ElasticsearchRetriever` and `ElasticsearchFilterOnlyRetriever`.
Didn't.
N/A
> refactor: Remove ElasticsearchRetriever and ElasticsearchFilterOnlyRetriever

- haystack/document_stores/milvus.py
- test/document_stores/test_milvus.py
Marks `MilvusDocumentStore` as deprecated.
Ran `pytest -m "unit" test/document_stores/test_milvus.py`.
N/A
> refactor: Mark MilvusDocumentStore as deprecated

- haystack/nodes/__init__.py
- haystack/nodes/prompt/__init__.py
- fixes `from haystack.nodes import AnswerParser` raises
- fixes `from haystack.nodes.prompt import AnswerParser` raises
- correct imports wiring up `AnswerParser`
- run `from haystack.nodes import AnswerParser`
- it was already possible to load `AnswerParser` via `from haystack.nodes.prompt.prompt_node import AnswerParser`
> chore: wire up `AnswerParser`

- .github/utils/release_docs.py
- .github/workflows/minor_version_release.yml
This PR cleans up a bit the `release_docs.py` script that is run in `minor_version_release.yml`. It removes unused functions, make the logic more straightforward and adds more documentation.
The process has also been changed to be less prone to errors. The process now works like so, assume we're publishing `1.79`:
* Verify that received `1.79` version is formatted as expected
* Checks if both the new `1.79.0` and `1.80.0-unstable` are not published
* Exits gracefully if both are published as there's nothing to do
* Fails miserably if either version is already published
* Check the version being published has an `1.79.0-unstable` version on Readme.io
* Fails miserably if it doesn't exist
* Create new `1.80.0-unstable` by copying and incrementing minor of current `1.79.0-unstable`
* Rename …
> ci: Enhance release_docs.py

- .github/workflows/compliance.yml
- .github/workflows/examples-tests.yml
- .github/workflows/rest_api_tests.yml
- .github/workflows/tests.yml
Use official Slack action to post job failures messages to Slack instead of previous one.
I decided to remove the `pypi_release.yml` Slack notification since it's not easy to customize as of now. 
I might write a script to generate a dynamic one.
Also it would be great if first we could test it in `main`.
> ci: Use new Slack action to send failure messages

- haystack/nodes/audio/whisper_transcriber.py
- test/nodes/test_whisper.py
- no related issue, discovered this usability flow during documentation writing
Adjust WhisperTranscriber to run method signature. Use file_paths as input parameter
Made a [colab](https://colab.research.google.com/drive/1FEy0fhRzMAaHWJ5famSF2S9chkzglkvU?usp=sharing)
What should we do with other params?
> refactor: Adjust WhisperTranscriber to pipeline run methods

- .github/workflows/docker_release.yml
- .github/workflows/pypi_release.yml
Revert the changes from #4293.
The release process is broken as of now since the `docker/metadata-action` can't pick up the version from the tag ref since we're triggering the release process with a `workflow_run`. If we use that trigger the ref will always be `main`.
This is a quick fix, in the future we should find a better solution to keep using `workflow_run`.
This must be included in `1.15.0` otherwise we won't be able to release version tagged images.
> ci: Fix docker release process after PyPi release

- haystack/telemetry.py
- This function got accidentally removed with the telemetry changes. This PR adds it back.
- Original PR https://github.com/deepset-ai/haystack/pull/4155
n/a
n/a
> fix: add back `tutorial_running()`

- haystack/document_stores/weaviate.py
- test/nodes/test_retriever.py
- fixes #4384 
We were waiting for Weaviate v1.18.0 to close a gap of functionality - lack of support for using filters with BM25 searching.
Version v1.18.0 just has been released and now it has this missing functionality, so I was uncommenting all the places where I left code in for the time when Weaviate starts supporting this.
I have some local tests with some live data in Weaviate, plus there is also a unit test which was activated for the Weaviate BM25 search with filter scenario.
None
- [x I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_conduct.txt)
> Adding filtering support for Weaviate when used for BM25 querying

- haystack/nodes/reader/farm.py
- fixes #2836
Followed [kalki7](https://github.com/kalki7) proposal for the fix by changing save_dir path.
Tested the farm reader with the new changes based on this tutorial 👉 [Tutorial: Build Your First Question Answering System](https://haystack.deepset.ai/tutorials/01_basic_qa_pipeline)
> feat: Change default save_dir for FARMReader.train

- haystack/nodes/audio/whisper_transcriber.py
- test/nodes/test_whisper.py
- fixes #4540 
- Removed duplicate test
- Mentioned in docstring that local installation of whisper supports a parameter that the API doesn't support
-
The local installation of whisper and and the API do not support the same parameters. That's why the tests for both are also not the exact same.
> test: Remove duplicate whisper test

- test/prompt/test_prompt_node.py
Skip `test_pipeline_with_prompt_template_at_query_time` for the time being as it's failing a TON in CI. 
This is meant to be temporary as I plan to change most of those integration tests into unit ones.
Nothing to test really.
Related to #4561
> test: Skip flaky prompt node integration test

- haystack/nodes/__init__.py
- haystack/nodes/retriever/__init__.py
- haystack/nodes/search_engine/providers.py
- haystack/nodes/search_engine/web.py
Some direct imports of new nodes raise errors.
(eg `from haystack.nodes import WebRetriever`)
Add imports to `__init__`
CI
Just a draft, feel free to correct me. 
Should abstract base classes (`SearchEngine`) also be directly importable?
In the `__init__` there are conflicting examples...
> refactor: remove variadic parameters in `WebSearch` initialization; make new nodes directly importable

- haystack/nodes/prompt/providers.py
- test/prompt/test_prompt_node.py
- https://github.com/deepset-ai/haystack/issues/4587 
Confirmed independently during HF agent streaming experiments. 
Slightly adjusts stop words algorithm for HF. We must also place tokens on the appropriate device before doing torch ops. 
Added a unit test for a single-stop word. We now test single and two words stop words scenarios. The previous test should have included both scenarios (one and two stop words). 
See changes
> fix: Adjust HF stop words (single stop word)

- haystack/nodes/prompt/prompt_node.py
- test/conftest.py
- test/prompt/conftest.py
- test/prompt/test_prompt_model.py
- test/prompt/test_prompt_node.py
Rewrite most `PromptNode` tests.
I ran `pytest --cov="haystack/nodes/prompt"  -m "unit" test/prompt/` locally.
This PR also improves the coverage of the unit tests, even if we currently are not tracking it this is before:
```
---------- coverage: platform darwin, python 3.8.16-final-0 ----------
Name                                       Stmts   Miss  Cover
--------------------------------------------------------------
haystack/nodes/prompt/__init__.py              5      0   100%
haystack/nodes/prompt/prompt_model.py         48      7    85%
haystack/nodes/prompt/prompt_node.py         198    133    33%
haystack/nodes/prompt/prompt_template.py     131     16    88%
haystack/nodes/prompt/providers.py           246    166    33%
haystack/nodes/prompt/shapers.py              23      2 …
```
> refactor: Rework prompt tests

- test/conftest.py
- test/nodes/test_connector.py
- test/nodes/test_sampler.py
This PR adds a `pytest` fixture that is applied to all tests, those that are decorated with `@pytest.mark.unit` will have the `requests` module monkeypatched to avoid making HTTP requests by mistake.
I ran `pytest -m "unit" test` locally.
N/A
> test: Add pytest fixture to block requests in unit tests

- haystack/utils/requests.py
- test/utils/test_requests.py
Add a utility method to make HTTP requests with retries in case of failures.
Example usage:
```
res = request_with_retry(method="GET", url="https://example.com")
res = request_with_retry(method="GET", url="https://example.com", attempts=10)
res = request_with_retry(method="GET", url="https://example.com", status_codes=[408, 503])
res = request_with_retry(method="GET", url="https://example.com", timeout=5)
class CustomAuth(requests.auth.AuthBase):
def __call__(self, r):
r.headers["authorization"] = "Basic <my_token_here>"
return r
res = request_with_retry(method="GET", url="https://example.com", auth=CustomAuth())
res = request_with_retry(
method="GET",
url="https://example.com",
auth=CustomAuth(),
attempts=10,
status_codes[408, 503],
timeout=5
)
res = request_with_retry(method="POST", …
```
> feat: Add util method to make HTTP requests with configurable retry

- haystack/nodes/connector/crawler.py
- test/nodes/test_connector.py
- test/samples/crawler/page1.html
- test/samples/crawler/page1_subpage1.html
- test/samples/crawler/page1_subpage2.html
- test/samples/crawler/page2.html
- test/samples/crawler/page2_subpage1.html
- fixes #3674 
Implements the proposed crawler depth > 1. 
Added two additional tests (along with their mock HTML files) in `test_connector.py` following the method of the existing tests.
I changed one thing about the existing filter logic (and one existing test): If a URL does not match any of `filter_urls`, its page will not be searched for matching sublinks either. This seemed more straightforward because the complete link tree would have to be crawled otherwise (e.g. if you want to crawl a webpage that includes a link to Wikipedia you would not want to crawl Wikipedia for links back to your page). Let me know if that makes sense to you.
> feat: arbitrary `crawler_depth` for `Crawler` class

- haystack/utils/requests.py
Add the `503` status code in the list of status codes that would trigger a retry on failure in `request_with_retry` as per @julian-risch [comment](https://github.com/deepset-ai/haystack/pull/4627#discussion_r1162479325). 
I ran `pytest test/utils/test_requests.py` and everything was green.
N/A
> refactor: Add 503 as status code that triggers retry in request_with_retry

- .github/workflows/docstring-labeler.yml
Change the `docstring-labeler.yml` work to checkout the correct repository when trigger in PRs from forks.
See example failure [here](https://github.com/deepset-ai/haystack/actions/runs/4678099751/jobs/8286417917?pr=4512).
Can't really be tested easily.
N/A
> ci: Fix docstring-labeler.yml not working in PR from forks

- haystack/nodes/prompt/invocation_layer/hugging_face.py
- test/prompt/test_prompt_node.py
- fixes #4647
Adds support for generation kwargs (and GenerationConfig) to PromptNode's HuggingFace invocation layer
This feature will enable users to finely adjust generation params for text generation using local runtime HuggingFace models
Added mocked tests to ensure that these params are pushed down to the underlying pipeline in HFLocalInvocationLayer
Please review my mock usage and the implementation logic of course :-)
The mocked method checking params is this [one](https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/base.py#L1114)
> feat: Add GenerationConfig option to PromptNode's HuggingFace invocation layer

- docs/pydoc/config/file-converters.yml
- fixes #4569
This PR adapts `docs/pydoc/config/file-converters.yml` such that the API reference for the `PDFToTextOCRConverter` is shown again on the documentation website.
n/a
> docs: Add PDFToTextOCRConverter to API Docs

- haystack/nodes/prompt/invocation_layer/hugging_face.py
- test/prompt/test_prompt_node.py
- fixes #4379
Introduces a new PromptNode HF parameter allowing users to override `model_max_length` for HF PromptNode. Until now, the maximum sequence length of HF models has been determined from the model tokenizer field. However, in some rare cases, as with T5 Flan models, the model can infer longer sequence lengths than specified by the tokenizer (512). In such cases, we want to have the ability to specify a custom maximum sequence length. Users can now do the following:
```
prompt_node = PromptNode("google/flan-t5-xxl", model_kwargs={"model_max_length" : 1024})
```
And thus override the maximum sequence length of 512 and set it to 1024, as in the example above.
Added unit test
Note that this is only relevant for HF models and other invocation layers will ignore this parameter.
> fix: Add model_max_length model_kwargs parameter to HF PromptNode

- test/conftest.py
- test/prompt/test_prompt_node.py
This PR is practically to #4433, why I'm adding it again? 
Because with #4614, the conftests rework, I removed it by mistake while fixing conflicts. 🤦 
I ran `pytest -m "unit" test` locally and it was green. ✅ 
N/A
> test: Add requests blocker fixture

- haystack/nodes/prompt/prompt_node.py
- fixes #4642 
Added a docstring to PromptNode describing the debug attribute
> docs: Add docstring for PromptNode debug attribute

- haystack/document_stores/pinecone.py
- fixes #3107 
As @jamescalam mentioned in the issue, if `delete_documents` is called right after PineconeDocumentStore initialization, an error is raised due to the fact that the code attempts to access `self.all_ids`'s (a temporary/helper/local dictionary which is completely empty after initializing the store) value for that particular index.
Thus, adding the index to the dict with an empty set() avoids this error being thrown and does not affect the `delete_documents` flows from my analysis.
Also, this seems to be a avoidable user experience point of attrition at this time, considering that [https://docs.haystack.deepset.ai/docs/faq](https://docs.haystack.deepset.ai/docs/faq) question related with seeing duplicate answers (although it does not mention Pinecone directly) incentivizes …
> fix: PineconeDocumentStore error when delete_documents right after initialization

- .github/workflows/imports.yml
- haystack/nodes/doc_language_classifier/langdetect.py
- haystack/nodes/file_converter/base.py
- fixes #4684
- Fixes the `langdetect` import to be actually optional
- Adds a CI job to check that the minimal Haystack install is importable.
- Manually
- CI
n/a
> fix: make `langdetect` truly optional

- test/conftest.py
Block HTTP calls made by `requests_cache` in unit tests.
`pytest -u "unit" test`, everything was green.
N/A
> test: Block requests_cache in unit tests

- docs/pydoc/config/retriever.yml
adding `web` to retriever API docs
> docs: add web retriever to api docs

- haystack/nodes/other/shaper.py
- fixes #4478
This PR removes the `(TODO: fix)` message from the `join_documents` method in shapers. We found that there's no obvious way on how to keep differing metadata, so we decided that we'll keep dropping the metadata. Also, `Shaper` is not needed anymore with `PromptNode` and the new way of joining Documents doesn't drop metadata.
n/a
> docs: Adapt Shaper docstrings regarding dropping metadata

- haystack/agents/base.py
Without this fix observation is logged on the same line as the previous step as in the image below.
I've made a small change to the code to make it so that Observation gets logged in the line below. 
PS: It's easy to not notice this because often in notebooks a ipython widget (for things like 'Calculating embeddings' gets added before, meaning it looks like observation is on the next line..)
> fix: Log 'Observation on new line

- haystack/document_stores/weaviate.py
- fixes #4702 
We should be calling the Weaviate client's query builder class' `with_bm25()` method with the correct params instead of a dict, see https://github.com/weaviate/weaviate-python-client/blob/27f6254bc01480ad8c1ce5e47be965bf8b19b6b6/weaviate/gql/get.py#L913
Unit tests + testing it locally.
This should be a rather easy thing to approve (I hope).
> fix: Fixing the Weaviate BM25 query builder bug

- pyproject.toml
- n/a
This PR loosens the required version for `weaviate-client` to `>=3.10,<4`
CI passes.
> build: Update weaviate-client

- haystack/agents/base.py
- fixes n/a
This PR reverts the changes made in #4704.
The newline character was initially added because of the way how agent observations were printed in notebooks. However, after merging #4704 we noticed that there's too many newline characters for agent observations when using the agent from a script.
> chore: Revert "fix: Log 'Observation' on new line (#4704)"

- haystack/nodes/prompt/invocation_layer/hugging_face.py
- test/prompt/test_prompt_model.py
- fixes #4669 Loading local HF models using PromptModel 
- 
In [HFLocalInvocationLayer]( https://github.com/deepset-ai/haystack/blob/main/haystack/nodes/prompt/invocation_layer/hugging_face.py#L112) while trying to use a local model, one should be able to pass task_type as an argument as well. if it exists in kwargs use that instead. 
Tested it Manually to see, if i can load a local HD model using PromptModel (in combination with [HFLocalInvocationLayer](https://github.com/deepset-ai/haystack/blob/main/haystack/nodes/prompt/invocation_layer/hugging_face.py)
> fix: loads local HF Models in PromptNode pipeline

- docs/pydoc/config/retriever.yml
- haystack/agents/utils.py
- None
Adds gpt-3.5-turbo to list of agents that can stream tokens
Manually
N/A
> fix: gpt-3.5-turbo is an agent streaming model

- README.md
Fixing README to explain how to install from main branch
- fixes #4689
- Current installation is from the latest branch
- Added instructions on how to install from `main`
> fix: README latest and main installation

- haystack/nodes/prompt/prompt_template.py
- test/prompt/test_prompt_template.py
- fixes #4365 #4366 
Properly logs which prompt params are missing
Unit test, see diff
N/A
> Enhance the error logging in PromptTemplate variable resolution

- haystack/document_stores/opensearch.py
- test/document_stores/test_opensearch.py
- test/document_stores/test_search_engine.py
- fixes n/a
This PR adds a separate `query` method for the `OpenSearchDocumentStore`. Previously, it was using the `query` method of `SearchEngineDocumentStore`. This caused the following error, introduced by #4602:
```
OpenSearch.search() got an unexpected keyword argument 'query'
```
I added a unit test.
> fix: Add separate query method for OpenSearchDocumentStore

- haystack/nodes/ranker/sentence_transformers.py
- test/nodes/test_ranker.py
- fixes #4252 
Implements fix proposed in #4252 
Added unit test
> fix: SentenceTransformersRanker's predict_batch returns wrong number of documents

- haystack/modeling/evaluation/metrics.py
- haystack/utils/context_matching.py
- haystack/utils/experiment_tracking.py
- fixes n/a
Update the `ImportError` messages according to the new `metrics` dependency
Tested runing [Evaluation Tutorial](https://colab.research.google.com/github/deepset-ai/haystack-tutorials/blob/main/tutorials/05_Evaluation.ipynb)
n/a
> fix: update ImportError for 'metrics' dependency

- haystack/agents/base.py
- haystack/agents/types.py
- haystack/nodes/prompt/invocation_layer/handlers.py
- haystack/nodes/prompt/invocation_layer/hugging_face.py
- test/prompt/test_prompt_node.py
- Adds local HF model streaming
Adds streaming token support released in HF transformers 4.28.0
This PR introduces `HFTokenStreamingHandler`, Haystack internal class, which hooks into transformers streaming and bridges to our customer-facing `TokenStreamingHandler` higher-level abstraction. Therefore our clients who implement `TokenStreamingHandler` can use any underlying invocation layer supporting streaming via that interface.  One of these implementations of TokenStreamingHandler is our own `AgentTokenStreamingHandler` that we currently use for both HF and OpenAI models. Tomorrow we'll add support for Anthropic and Cohere. And for them, we'll implement internal streaming hooks and expose them via already familiar `TokenStreamingHandler` abstraction as well, thus enabling a single …
> feat: Add HF local runtime token streaming support

- haystack/nodes/prompt/invocation_layer/hugging_face.py
- fixes #4729 
Specify which InvocationLayer and task to use in the promptModel of the YAML file.
pytest prompt/
=============== 71 passed, 46 skipped, 9 warnings in 44.37s =======================
PromptModel
> fix: load the local finetuning model from pipeline yaml (#4729)

- .github/workflows/tests.yml
Add the `test/others` folder to `unit-tests` job, this way we'll get coverage for that too.
Can't really be tested as its a CI thing.
N/A
> test: Add others folder to unit test job

- .github/utils/release_docs.py
Change `release_docs.py` to create docs versions on release using correct `<major>.<minor>` string instead of `<major>.<minor>.0`.
I ran the script locally skipping the last steps that actually reflect the changes on Readme.io.
N/A
> ci: Fix release_docs.py to create docs with correct version

- examples/agent_multihop_qa.py
- haystack/agents/agent_step.py
- haystack/agents/base.py
- test/agents/test_agent.py
- test/agents/test_tools_manager.py
- NA
- Note: this is the first PR in a series of PRs related to adding conversational agents, memory, and self-reflection. 
Converts previously monolithic Agent containing tools management by default to a less assuming Agent that:
- Might not have tools at all (e.g. conversational agent)
- Extracts all tools logic into a new class `ToolsManager` responsible for management and invocation of tools
In addition, this refactoring opportunity was used to remove `run_batch` Agent method. We concluded internally it was not needed except in some very specific circumstances. 
No additional unit tests were added
Manual test of `examples/agent_multihop_qa.py` performed to test for regressions
A unit test `test_agent_chooses_no_action` has been removed as we now allow Agents without tools
run batch …
> refactor: Extract ToolsManager, add it to Agent by composition

- haystack/document_stores/pinecone.py
- haystack/document_stores/weaviate.py
- test/document_stores/test_pinecone.py
- test/document_stores/test_weaviate.py
- fixes #4629
This PR adds support for the `_split_overlap` meta field to the `PineconeDocumentStore` and adds support for any metadata of type `dict` to `WeaviateDocumentStore`. 
Weaviate and Pinecone don't support dict type natively, so the workaround is to convert dict metadata fields to JSON strings at index time and convert the JSON strings back to dicts at query time. I haven't found a way to support dict in general for Pinecone, so I restricted the implementation to at least support the `_split_overlap` meta field.
> fix: Add support for `_split_overlap` meta to Pinecone and `dict` metadata in general to Weaviate

- haystack/document_stores/utils.py
- haystack/utils/squad_to_dpr.py
Fixes two issues where an integer value is handles as a `str`.
see #4754 and #4753
> fix: str issues in `squad_to_dpr`

- haystack/nodes/answer_generator/openai.py
- haystack/nodes/prompt/prompt_node.py
- haystack/nodes/prompt/prompt_template.py
- test/agents/test_agent.py
- test/nodes/test_generator.py
- test/nodes/test_shaper.py
- test/prompt/test_prompt_node.py
- test/prompt/test_prompt_template.py
- fixes #4710
This PR deprecates the parameter `name` of `PromptTemplate` and introduces instead the parameter `template_name`.
**⚠️ Breaking Change ⚠️**
The changes made in this PR are breaking as they change the order of arguments in `PromptTemplate`'s `__init__` method. `prompt_text` will become the 1st argument (previously the 2nd one) and `template_name` will become the 2nd argument (previously the 1st argument).
I decided to remove the deprecated `name` parameter with Haystack 2.0, but this is not set in stone. Let me know if you would like to remove it before that.
> refactor!: Deprecate `name` param in `PromptTemplate` and introduce `template_name` instead

- haystack/nodes/other/join.py
- test/nodes/test_join_answers.py
- test/nodes/test_join_documents.py
- fixes https://github.com/deepset-ai/haystack-private/issues/51
- `JoinNode` subclasses are dropping several parameters that they are not merging, but some, namely `root_node`, should be preserved for other nodes like `Retriever`s to work when placed downstream.
- This PR forces `JoinNode`s to retain `root_node` in their output and adds tests.
- Added tests
n/a
> fix: preserve `root_node` in `JoinNode`'s output

- .github/workflows/tests.yml
- test/modeling/samples/test_get_tokenizer_from_path/tokenizer_config.json
- test/modeling/test_feature_extraction.py
- test/modeling/test_model_loading.py
Add the test/modeling folder to unit-tests job, this way we'll get coverage for that too.
I did run these unit tests locally, but I did get an error for some of them. For example 
```python
@pytest.mark.unit
def test_get_tokenizer_path(mock_autotokenizer, tmp_path):
tokenizer = FeatureExtractor(pretrained_model_name_or_path=tmp_path / "test-path")
>       tokenizer.mocker.from_pretrained.assert_called_with(
pretrained_model_name_or_path=str(tmp_path / "test-path"), revision=None, use_fast=True, use_auth_token=None
)
E       AttributeError: 'FeatureExtractor' object has no attribute 'mocker'
```
Unfortunately, I'm not too familiar with Mocking so I'm unsure how to fix this.
Quite a few tests in this folder were tagged and updated to be unit tests in the last week.
> Add modeling to unit tests so it we can get coverage for that

- test/agents/test_agent.py
- fixes flaky test
- Skips `test/agents/test_agent.py::test_agent_run` due to increasing flakyness
- CI
n/a
> chore: skip flaky test

- haystack/utils/openai_utils.py
- test/utils/test_openai_utils.py
- fixes #4799
When migrating to `tenacity` with PR #4460 I missed an error handling in `openai_request` function, this PR adds it back.
Added unit tests to verify failing and success cases.
N/A
> fix: Fix missing error in openai_request retry strategy

- .github/workflows/tests.yml
Add all unit test topics to `upload-coverage` job `carryforward` input and add a warning to remind people to update it when adding new topics to `unit-test` matrix.
I triggered a run on this branch and the coverage upload ran fine, the workflow failed later on for unrelated reasons.
https://github.com/deepset-ai/haystack/actions/runs/4934763052
> ci: Add missing unit tests topics to coverage upload step

- pyproject.toml
- fixes https://github.com/deepset-ai/haystack/issues/4852
- pin `canals==0.1.2` to shield against breaking changes
n/a
n/a
> chore: pin `canals`

- test/preview/dataclasses/test_dataclasses.py
- test/preview/document_stores/_base.py
- fixes n/a
- Add `pytest.mark.unit` to all tests in `haystack/preview` that did not have it.
- CI
Needed for the coverage to show up on Coveralls
> fix: add `unit` markers to several v2 tests

- haystack/schema.py
- test/others/test_schema.py
- test/samples/schema/text_answer.json
- test/samples/schema/text_doc.json
- test/samples/schema/text_doc_emb.json
- test/samples/schema/text_label.json
- fixes N/A
- Update tests in `test/others/test_schema.py` to follow the recommended changes by @silvanocerza from this PR https://github.com/deepset-ai/haystack/pull/4747 
- Existing and updated unit tests.
> test: Update unit tests for schema

- .github/workflows/tests.yml
Coverage upload is always done after the `unit-test` matrix job finishes running, even if there are failing tests.
This causes reruns to fail on upload since the `coverage-upload` job "closes" the run and it won't let it accept any more coverage reports.
Preventing the upload even if a single test fails should solve the issue. 
Can't really be tested.
Example job failing on rerun after previous failure: https://github.com/deepset-ai/haystack/actions/runs/4927098118/jobs/8819249825?pr=4853
> ci: Upload coverage only if all unit tests pass

- .github/workflows/examples-tests.yml
- .github/workflows/linting.yml
- .github/workflows/openapi_sync.yml
- .github/workflows/tests.yml
- CONTRIBUTING.md
- README.md
- pyproject.toml
- n/a
We are currently installing `dev` with `pip install farm-haystack[all]`. With this change we want to give `all` the meaning of "all I need to run haystack" and not just "all that's listed in pyproject.toml". This will improve the licensing management and will let us be less conservative when picking development tools.
> build: do not install 'dev' extras with 'all'

- .github/utils/pyproject_to_requirements.py
- .github/workflows/license_compliance.yml
- pyproject.toml
- n/a
Add a job that checks only dependencies explicitly listed in `pyproject.toml` (so called "direct dependencies")
I added a script that extracts the list of dependencies included the optional ones from `pyproject.toml`
> ci: add a job to vet license of direct dependencies only

- README.md
As discussed internally this PR adds Datadog to list of organizations that we know are using Haystack.
> chore: Add Datadog in Who Uses Haystack README.md section

- docs/pydoc/config/prompt-node.yml
- haystack/errors.py
- haystack/nodes/prompt/invocation_layer/__init__.py
- haystack/nodes/prompt/invocation_layer/cohere.py
- haystack/nodes/prompt/invocation_layer/handlers.py
- test/prompt/invocation_layer/test_cohere.py
- test/prompt/test_handlers.py
- fixes #3863
Add Cohere command and command-light model support. Both models support token streaming
Manually, unit tests
> feat: Add Cohere PromptNode invocation layer

- haystack/pipelines/base.py
- haystack/telemetry.py
- fixes #4871
This PR send an event to our telemetry for every 100 pipeline runs. If a pipeline configuration has not changed, we only send the config hash instead of the whole configuration.
> feat: Send pipeline config hash every 100 runs

- haystack/modeling/data_handler/processor.py
- test/modeling/test_processor.py
- fixes #4320
Currently, the parameter `max_answers` is hardcoded to 6 and will throw an IndexError if the dataset contains a sample with more than 6 answers. 
This is not a nice user experience, especially when `SquadProcessor` is not used directly but is automatically instantiated (e.g. in `FARMReader`. The user would have to know about this hardcoded value, instantiate a `SquadProcessor` manually and pass it to `FARMReader`.
This PR solves this by dynamically determining `max_answers` from the data dict by default. The parameter `max_answers` can still be set manually. If max_answers is manually set to be less than the actual maximum amount of answers, the answers will be truncated and the logger will issue a warning.
Added two unit tests in test_processor.py
> fix: Dynamic `max_answers` for SquadProcessor (fixes IndexError when max_answers is less than the number of answers in the dataset)

- pyproject.toml
- fixes #4914
- There was a new transformers release https://github.com/huggingface/transformers/releases and we need to test it
- Main features relevant to us are Transformers Agents, Open-Llama model and potentially Assisted Generation
- Just upgraded the dependency version
Tried it in this internal colab notebook: https://colab.research.google.com/drive/1BJBx52BLdYT54UoPchpstNXaEkJV6FSb?usp=sharing and CI
I checked the very short [list of breaking changes ](https://github.com/huggingface/transformers/releases/tag/v4.29.0) but there is nothing relevant to Haystack.
> build: Upgrade transformers to 4.29.1

- haystack/schema.py
- test/others/test_schema.py
- test/pipelines/test_eval.py
- fixes https://github.com/deepset-ai/haystack/issues/4905
- ensure None values stay the same
- ensure index is set correctly
- extended existing tests
> fix: `EvaluationResult` serialization changes dataframes

- haystack/nodes/other/shaper.py
* When retriever retrieves 0 documents from the documentStore, shaper will raise an exception.
- fixes #4928 
don't filter the empty list [], when assign the documents to invocation_context["documents"] 
mypy, pylint, black
> fix: shaper exception when retriever return 0 docs.

- examples/agent_multihop_qa.py
- examples/conversational_agent.py
- haystack/agents/agent_step.py
- haystack/agents/base.py
- haystack/agents/conversational.py
- haystack/agents/types.py
- haystack/nodes/prompt/prompt_template.py
- test/agents/test_agent.py
- test/agents/test_agent_step.py
- test/agents/test_conversational_agent.py
- test/agents/test_tools_manager.py
- test/prompt/test_prompt_node.py
- adds ConversationalAgent
- adjusts Agent base to handle different kinds of Agents
We are adding a new class of Agents - ConversationalAgent, which uses recently integrated Memory
Unit tests, examples, see `examples` directory
During manual testing, a bug was discovered in `haystack/agents/memory/conversation_summary_memory.py`, and a new unit test was added (2a2dc50c3b1f792c237d1e0f508bc071a2e886b4) I ran manual checks and debugger checks to ensure correct execution of summary memory. Repeat these tests yourself.  
Run `examples/agent_multihop_qa.py` to ensure no regressions were introduced and run `examples/conversational_agent.py` with regular memory (default) and change memory to use `ConversationSummaryMemory`. Run at least 5-10 rounds of chats, and check memory contents with both …
> feat: Add conversational agent

- haystack/nodes/retriever/dense.py
- test/nodes/test_retriever.py
- fixes #4897 
This PR changes the tokenizer in `DensePassageRetriever` from `DPRQuestionEncoderTokenizerFast`/`DPRContextEncoderTokenizerFast` to `AutoTokenizer`.
I manually loaded `etalab-ia/dpr-question_encoder-fr_qa-camembert` and `etalab-ia/dpr-ctx_encoder-fr_qa-camembert` which was previously failing.
> fix: Use `AutoTokenizer` instead of DPR specific tokenizer

- haystack/nodes/prompt/prompt_model.py
No related issue. We should remove this warning as more and more LLMs (and instructions following LLMs) are being released daily, and it is impossible to track them. This warning has become inaccurate and moot. 
Remove the warning
No tests were added
> fix: Remove instruction following warning

- test/document_stores/test_weaviate.py
-n/a 
Fix the mocking introduced with #4805 to avoid importing the client from the test module
Tested locally
Stumbled upon this while trying to unblock #4028
> test: avoid importing the weaviate client directly from the test module

- haystack/agents/base.py
- test/agents/test_tools_manager.py
- fixes https://github.com/deepset-ai/haystack/issues/4575
Change the default ToolsManager tools pattern to match multiple lines of tool input yet be backwards compatible with the old tools pattern
All the existing tools' pattern tests are run against the new default regex pattern
Added a unit test specifically for the use case of multi-line input `test_extract_tool_name_and_tool_multi_line_input`
Please try to find a counter-example that breaks the pattern.
> fix: Adjust tool pattern to support multi-line inputs

- .github/workflows/rest_api_tests.yml
- .github/workflows/tests.yml
Set shell explicitly in all `calculator` steps to fix failures when running job in Windows.
Example failures:
* https://github.com/deepset-ai/haystack/actions/runs/5024559843/jobs/9010481882
* https://github.com/deepset-ai/haystack/actions/runs/5024559845/jobs/9010484619
> ci: Set calculator shell explicitly to handle Windows runs

- .github/workflows/examples_tests.yml
- .github/workflows/rest_api_tests.yml
- .github/workflows/tests.yml
Add the workflow run id to event tags sent to Datadog.
Related to #4957.
> ci: Add workflow id to Datadog event tags

- haystack/nodes/file_converter/markdown.py
- fixes #4861
This PR corrects the error message specifying which extra is needed for using the `MarkdownConverter`. It's `file-conversion`, not `preprocessing`.
> fix: Fix necessary extra for MarkdownConverter

- haystack/nodes/prompt/invocation_layer/anthropic_claude.py
- haystack/nodes/prompt/invocation_layer/cohere.py
- haystack/nodes/prompt/invocation_layer/hugging_face_inference.py
Recently we changed a keyword argument in `request_with_retry` from `status_codes` to `status_codes_to_retry`.
That broke some invocation layers that retry on custom status codes.
PR that introduced the change: #4950
This PR fixes the issue by using the correct kwarg.
I ran `AnthropicClaudeInvocationLayer` integration tests locally. 
As of now `AnthropicClaudeInvocationLayer` integration tests are not run in CI as the `ANTHROPIC_CLAUDE_API_KEY` env var is not set.
> fix: Fix request_with_retry kwargs

- haystack/schema.py
- pyproject.toml
Pin `typing_extensions` to version `4.5.0` to fix Pydantic failing when trying to import Haystack.
`typing_extensions` version `4.6.0` was released 8 hours ago, that version causes Pydantic to fail.
Created a new virtualenv with Python `3.8.16`, run `pip install .` and then `python -c 'import haystack'`.
Some additional info regarding the failure in here can be found in the Pydantic issue: pydantic/pydantic#5821.
Imports have been moved around in `schema.py` to please `pylint`.
> fix: Pin typing_extensions to fix Pydantic issue

- haystack/nodes/answer_generator/openai.py
- haystack/nodes/prompt/invocation_layer/open_ai.py
- haystack/nodes/retriever/_openai_encoder.py
- haystack/utils/openai_utils.py
- pyproject.toml
- Part of #4417 
- Related to GitHub discussion: https://github.com/deepset-ai/haystack/discussions/4969
- Remove conditional statements from tiktoken in open ai utils as we don't need to handle any alternative anymore
- Remove limitations on tiktoken from pyproject.toml
> build: Remove tiktoken alternative

- haystack/agents/conversational.py
- Follow-up on @TuanaCelik comment in the ConversationalAgentWithTools PR: https://github.com/deepset-ai/haystack/pull/4940/files#r1202130074
- Make the use of PromptTemplate in Agent, ConversationalAgent and ConversationalAgentWithTools (PR pending for the latter) consistent
- Add a prompt_template param the the init of ConversationalAgent and thus ignore the default_prompt_tempalte of the PromptNode just as in Agent and ConversationalAgentWithTools
> feat: Add prompt_template to conversational agent init params

- test/agents/test_conversational_agent.py
- n/a
This PR mocks the `_fetch_from_prompthub` in `test/agents/test_conversational_agent.py::test_init_with_summary_memory`. The test was previously failing as we don't allow making http requests in unit tests.
> test: Mock request from prompt hub in unit test

- haystack/nodes/prompt/legacy_default_templates.py
- haystack/nodes/prompt/prompt_node.py
- test/prompt/test_prompt_node.py
Add the hardcoded `PromptTemplate` remove with PR #4879.
Add a new test that verifies the expected legacy template is returned when using legacy template names.
There's more information in the comment at the top of `legacy_default_templates.py`.
> feat: Add back hardcoded default templates

- .github/workflows/tests.yml
- haystack/nodes/file_converter/__init__.py
- fixes n/a
- Fix the PyMuPDF/xpdf import switcher. Since the introduction of `generalimport`, no import errors were raised, causing Haystack to select always PyMuPDF
n/a
n/a
> fix: `fitz` import switcher

- haystack/document_stores/opensearch.py
- Updated several references to Elasticsearch to say OpenSearch
- Added backlinks to OpenSearch's documentation where documentation was present
N/A
There were several references to Elasticsearch in the OpenSearch Document store docstrings. I updated them to say OpenSearch and changed several links to reference OpenSearch's documentation except where documentation may still need to be added.  
No tests as it's just docs. 
Feel free to reach out if there are issues with anything Ive added. 
~~ - [ ] I added tests that demonstrate the correct behavior of the change ~~
> docs: updating docstrings to say OpenSearch and backlink to correct docs

- pyproject.toml
- fixes #4988 
This PR changes how we install protobuf. With this PR, we now install protobuf through a transformers extra called sentencepiece. In addition to protobuf it also installs sentencepiece, which we anyway need for Haystack's core dependency sentence-transformers. They can't be used separately anyway and transformers pins protobuf to the working version.
> build: Install protobuf via transformers extra sentencepiece

- haystack/__init__.py
- haystack/modeling/training/base.py
- pyproject.toml
- Part of https://github.com/deepset-ai/haystack/pull/4417
Remove dill dependency and remove dill from from saving models via torch.save with pickle_module set to dill.
- Trained a tiny DPR model with the dill module installed: https://colab.research.google.com/drive/1jgjn_4cdbmxK7ZFXeRXTbjxrgqKDQBHD?usp=sharing
- Loaded the trained DPR model here without installing dill: https://colab.research.google.com/drive/1xDpRXh-ArDKLqz4q1PzYyVrWVwefiZfm?usp=sharing
dill was introduced in FARM in https://github.com/deepset-ai/FARM/pull/271 At that time we used torch.save to not only store the state dicts but also the model itself. As the AdaptiveModel allows defining a loss function as a callable, it was not serializable out of the box and we introduced dill to save it.
In Haystack, we're not …
> build: Remove dill dependency

- examples/agent_multihop_qa.py
- examples/web_lfqa.py
- fixes n/a
- Remove mentions to `prompt_text` in the examples
n/a
n/a
> fix: remove `prompt_text` in examples

- haystack/document_stores/memory.py
- haystack/nodes/extractor/entity.py
- haystack/nodes/file_converter/parsr.py
- haystack/nodes/preprocessor/base.py
- haystack/nodes/reader/table.py
- haystack/nodes/retriever/_embedding_encoder.py
- haystack/nodes/retriever/dense.py
- haystack/pipelines/base.py
- haystack/pipelines/standard_pipelines.py
- haystack/pipelines/utils.py
- haystack/schema.py
- haystack/utils/deepsetcloud.py
- haystack/utils/early_stopping.py
- pyproject.toml
- rest_api/rest_api/schema.py
- fixes #4997
Remove the pinned version of `typing_extensions` and all its uses in the codebase as it's not necessary.
`python -c 'import haystack'` and it went smooth.
Installing `pydantic` still brings in `typing_extensions` but we must not rely on it.
> chore: Unpin typing_extensions and remove all its uses

- haystack/nodes/reader/farm.py
Documentation lists `offsets_in_context` twice. It should be `offsets_in_documents` and `offsets_in_context`.
> docs: Fix doc for `FARMReader.predict`

- test/benchmarks/retriever.py
- test/benchmarks/retriever_reader.py
- test/benchmarks/run.py
- n/a
This PR changes the benchmark script such that we use the queries from the aggregated labels to run the benchmarks on. Also, it adds the benchmark config to the final JSON file. 
Manual verification. …
> fix: Use queries from aggregated labels in benchmarks

- .github/workflows/tests.yml
n/a
- Adds the cli package to the test packages in the `tests.yml` workflow matrix
n/a
n/a
> ci: `cli` tests not running in CI

- haystack/document_stores/search_engine.py
- haystack/document_stores/weaviate.py
- test/document_stores/test_weaviate.py
- n/a
This PR adds the parameter `batch_size` to `WeaviateDocumentStore`'s constructor which sets the size of number of Documents to index at once. 
Also, if the type of the provided `timeout_config` value is a list, it will be casted to a `tuple`. This is necessary as we can't specify tuples in YAML-files but Weaviate expects a tuple, so setting a custom value for `timeout_config` in a Pipeline YAML config file currently results in an error.
I added a unit test.
The methods `get_documents_by_id` and `_get_all_documents_in_index` take a `batch_size` argument which is never used. To avoid breaking changes, I decided to not remove them. We should review in the future if and how we can make use of batch size in these methods.
This PR also removes an instance of `tqdm` in …
> feat: Add batch_size parameter and cast timeout_config value to tuple for `WeaviateDocumentStore`

- haystack/nodes/prompt/invocation_layer/anthropic_claude.py
- haystack/nodes/prompt/invocation_layer/handlers.py
- test/prompt/invocation_layer/test_anthropic_claude.py
- test/prompt/test_handlers.py
- fixes #4990 
Change the default streaming handler in `AnthropicClaudeInvocationLayer` to a custom one, so that the received streamed response is handled gracefully.
I added new tests for the `AnthropicTokenStreamingHandler` and changed the `AnthropicClaudeInvocationLayer` tests.
More info available in the linked issue.
> fix: Fix handling of streaming response in AnthropicClaudeInvocationLayer

- pyproject.toml
- n/a
Mlflow had a release yesterday that breaks our `cache_schema` method, which breaks our docker builds. This PR pins `mlflow` to `<2.4.0` …
> build: Pin mlflow

- haystack/agents/base.py
- test/agents/test_agent.py
- fixes #5010 
- Consider the prompt node's default prompt template when initializing the Agent
- Add a unit test checking that prompt template passed to Agent directly overrules prompt template set as default of the prompt node, which again overrules the default prompt template set in the Agent's implementation
- Added new test case and ran it locally
The changes in this PR are consistent with ConversationalAgent (open PR https://github.com/deepset-ai/haystack/pull/5065/files#diff-25bbf5718d62689cb1c872451bb4562d145d08d66641b5dd9b06d33720e291d6R79 ) and I expect ConversationalAgentWithTools to not be added. It's also consistent with Memory: https://github.com/deepset-ai/haystack/blob/main/haystack/agents/memory/conversation_summary_memory.py#L35 …
> feat: Consider prompt_node's default_prompt_template in agent

- haystack/modeling/data_handler/data_silo.py
- fixes #4977
This PR makes sure that we don't log any info message about clipped sequences when using `DataSilo` in combination with `SquadProcessor`.
Manual verification.
As explained in #4977, `SquadProcessor` doesn't clip sequences but generates multiple overlapping samples in case a sequence exceeds `max_seq_len`.  …
> fix: Don't log info message in DataSilo with SquadProcessor about clipping

- .github/workflows/tests.yml
- test/agents/test_agent.py
- test/agents/test_conversational_agent.py
- test/agents/test_tools_manager.py
- test/conftest.py
- test/nodes/test_generator.py
- test/prompt/invocation_layer/test_anthropic_claude.py
- test/prompt/invocation_layer/test_cohere.py
- test/prompt/invocation_layer/test_hugging_face.py
- test/prompt/invocation_layer/test_hugging_face_inference.py
- test/prompt/test_handlers.py
- fixes https://github.com/deepset-ai/haystack/issues/4868
- Add fixture monkeypatching `urlopen` instead of `requests`
- CI
n/a …
> chore: block all HTTP requests in CI

- haystack/nodes/prompt/prompt_template.py
- test/prompt/test_prompt_node.py
- test/prompt/test_prompt_template.py
- fixes #4878
- Show warning if documents are expected by prompt template but not provided
- Add empty list of documents to prompt parameters if documents parameter was expected but not provided
- Add two unit tests
- New unit tests
- Manually without mocking in a pipeline …
> fix: PromptNode falls back to empty list of documents if none are provided but expected

- haystack/nodes/prompt/invocation_layer/chatgpt.py
- test/prompt/invocation_layer/test_chatgpt.py
- OpenAI announced new ChatGPT models, gpt-3.5-turbo-0613 and gpt-3.5-turbo-16k. Haystack currently doesn't allow using these models because our model name check is too strict. https://openai.com/blog/function-calling-and-other-api-updates
- fixes #5141
- Relax the name check in the ChatGPTInvocationLayer
- Tested locally …
> fix: Relax ChatGPT model name check to support gpt-3.5-turbo-0613

- haystack/preview/pipeline.py
- test/preview/pipeline/test_pipeline.py
Small bug found in pair-programming with @vblagoje 
- adds a missing return statements
- improves a test to make sure the pipeline returns
- local tests run
n/a
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTIN …
> fix: small improvement to pipeline v2 tests

- haystack/nodes/prompt/prompt_model.py
- fixes #5069
When using Azure OpenAI services, the wrong invocation layer class was taken in prompt_model.py because of the order of the invocation layer classes.
To correct this, I added a filter that take only Azure invocation layer classes when AZURE_BASE_URL is filled.
Manual verification to ensure it was working correctly.
Pytest was run successfully.
N/A
> fix: azure openai authentication error

- .github/workflows/tests.yml
- README.md
- haystack/document_stores/memory.py
- haystack/environment.py
- haystack/modeling/infer.py
- haystack/modeling/model/feature_extraction.py
- haystack/nodes/answer_generator/transformers.py
- haystack/nodes/audio/whisper_transcriber.py
- haystack/nodes/doc_language_classifier/transformers.py
- haystack/nodes/document_classifier/transformers.py
- haystack/nodes/extractor/entity.py
- haystack/nodes/image_to_text/transformers.py
- haystack/nodes/label_generator/pseudo_label_generator.py
- haystack/nodes/prompt/invocation_layer/hugging_face.py
- haystack/nodes/prompt/prompt_model.py
- haystack/nodes/prompt/prompt_node.py
- haystack/nodes/query_classifier/transformers.py
- haystack/nodes/question_generator/question_generator.py
- haystack/nodes/ranker/sentence_transformers.py
- haystack/nodes/reader/farm.py
- haystack/nodes/reader/table.py
- haystack/nodes/reader/transformers.py
- haystack/nodes/retriever/_embedding_encoder.py
- haystack/nodes/retriever/dense.py
- haystack/nodes/retriever/multimodal/embedder.py
- haystack/nodes/retriever/multimodal/retriever.py
- haystack/nodes/sampler/top_p_sampler.py
- haystack/nodes/summarizer/transformers.py
- haystack/nodes/translator/transformers.py
- pyproject.toml
- fixes #4233 
- fixes #4417 
- Users who want to just use PromptNode with OpenAI or with a model from transformers should not need to install torch and cuda dependencies, sentencepiece or the huggingface hub dependencies but at the moment it's a must.
- **TLDR**:  `pip install farm-haystack` -> `pip install farm-haystack[inference]`. Users who ran the former in the past now need to run the latter to install the same set of dependencies.
- This PR adds a new extra, for now called `inference`. ~~Let's discuss the name of this extra.~~
- The `inference` extra contains torch, sentencepiece extras of transformers so that the versions that are compatible with transformers are installed. It also contains the huggingface hub dependency and sentence-transformers.
- The standard Haystack …
> feat!: Add extra for inference dependencies such as torch

- haystack/nodes/prompt/invocation_layer/chatgpt.py
- haystack/utils/openai_utils.py
- test/prompt/invocation_layer/conftest.py
- test/prompt/invocation_layer/test_chatgpt.py
- test/prompt/invocation_layer/test_openai.py
- test/prompt/test_prompt_node.py
- fixes https://github.com/deepset-ai/haystack-private/issues/61
- Adds an implementation for the `ChatGPTInvocationLayer._ensure_token_limit` that closely follows the one for `OpenAIInvocationLayer`
- This PR only handles the token truncation for a single prompt. It does not handle the case when the prompt is a list of dictionaries (e.g. messages) which occurs when the prompt node is used in chat mode.
- These changes will work for both the OpenAI and Azure Invocation layers
- Added new tests. Unfortunately, I could not make them unit tests because the library `tiktoken` makes an URL request to fetch the tokenizer for the corresponding OpenAI model.  …
> feat: add ensure token limit for direct prompting of ChatGPT

- docs/pydoc/config/answer-generator.yml
- n/a
`Seq2SeqGenerator` and `RAGenerator` were removed in #5180 and with that the `transformers.py` module was removed as well. This PR adapts the docs config for the Answer Generator API to account for that. …
> docs: Remove transformers module from AnswerGenerator API docs

- haystack/nodes/ranker/sentence_transformers.py
- test/nodes/test_ranker.py
- fixes N/A
- Adding unit tests to test private methods of `SentenceTransformersRanker`
- I only added unit tests for private methods in the Ranker node. In the future, we can use mocking to add unit tests for the `predict` and `predict_batch` methods. 
- I documented …
> test: Adding unit tests to Ranker

- haystack/agents/base.py
- test/agents/test_agent.py
- test/agents/test_tools_manager.py
- fixes #5108 
This PR removed the `add_tool` method from `ToolsManager`. Also, it adds a warning log to the `add_tool` method of `Agent` that is triggered if the Agent already contains a tool with the same name.
I adapted a unit test to check for the warning message.
- …
> chore: Remove `add_tool` from `ToolsManager`

- haystack/nodes/other/shaper.py
- haystack/nodes/prompt/prompt_template.py
- haystack/nodes/prompt/shapers.py
- test/nodes/test_shaper.py
- fixes #5111
- Adds the `current_datetime` shaper function.
- Explicitly adds it to the default allowed function of `PromptTemplate`.
Example usage:
- as code:
```python
shaper = Shaper(func="current_datetime", inputs={}, outputs=["date_time"], params={"format": "%y-%m-%d"})
```
- as a Shaper:
```yaml
components:
- name: shaper
type: Shaper
params:
func: current_datetime
params:
format: "%y-%m-%d"
outputs:
- date_time
```
- as a prompt template function
```python
prompt = PromptTemplate("It's now {current_datetime(format='%m/%d/%y')}. Given the context and keeping in mind the current time, please answer the question. Context: {join(documents)}; Question: ")
```
Note: in all examples, the `format` parameter is optional and defaults to `"%H:%M:%S %d/%m/%y"`
- Local run of new tests
n/a
- I …
> feat: `current_datetime` shaper function

- haystack/nodes/preprocessor/preprocessor.py
- test/nodes/test_preprocessor.py
- fixes https://github.com/deepset-ai/haystack-private/issues/62
- Split documents into shorted ones if they are longer than `max_chars_check`.
- The split is recursive, i.e. if the split document is still too long, it will be split again and again until all the chunks are below the threshold.
- Updated `test/nodes/test_preprocessor.py::test_preprocessor_very_long_document`
n/a …
> feat: hard document length limit at `max_chars_check`

- haystack/nodes/prompt/invocation_layer/__init__.py
- haystack/nodes/prompt/invocation_layer/sagemaker_hf_text_gen.py
- test/prompt/invocation_layer/test_sagemaker_hf_text_gen.py
We are changing the class name `SageMakerInvocationLayer` to `SageMakerHFTextGenerationInvocationLayer`.
What seems to be occurring is a transition within SageMaker to use containers running the latest Hugging Face project, known as [text-generation-inference](https://github.com/huggingface/text-generation-inference). The client API of this project has an input/output data format that closely aligns with our `SageMakerHFTextGenerationInvocationLayer`. You can see this in the project's [client.py](https://github.com/huggingface/text-generation-inference/blob/main/clients/python/text_generation/client.py#L17) file. For the time being, until the full transition to `text-generation-interface` project, it will be crucial for us to continue supporting both …
> fix:Rename SageMakerInvocationLayer -> SageMakerHFTextGenerationInvocationLayer

- haystack/agents/utils.py
- haystack/nodes/prompt/prompt_template.py
- Related to https://github.com/deepset-ai/prompthub/issues/40
Rename `{history}` as `{memory}` to have a better consistency
Ran conversational_agent.py
N/A
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md …
> Change 'history' to 'memory' in the ConversationalAgent prompts

- haystack/nodes/prompt/invocation_layer/__init__.py
- haystack/nodes/prompt/invocation_layer/sagemaker_base.py
- haystack/nodes/prompt/invocation_layer/sagemaker_hf_infer.py
- haystack/nodes/prompt/invocation_layer/sagemaker_hf_text_gen.py
- haystack/nodes/prompt/prompt_model.py
- test/prompt/invocation_layer/test_sagemaker_hf_infer.py
- test/prompt/invocation_layer/test_sagemaker_hf_text_gen.py
We are introducing a new class, `SageMakerHFInferenceInvocationLayer`, which supports a variety of Hugging Face text generation models including: MPT, Dolly V2, Flan-U2, Flan-T5, RedPajama, Open Llama, GPT-J-6B and others.
- fixes #5201
During our continuous testing of the PromptNode and SageMaker integration, we discovered that the JSON payload format and parameters for the models supported by `SageMakerHFInferenceInvocationLayer` are different from those used by `SageMakerHFTextGenerationInvocationLayer`. Due to the common abstractions shared by both classes, we've introduced a new superclass, `SageMakerBaseInvocationLayer`, from which both classes now inherit.
What seems to be occurring is a transition within SageMaker to use containers running the latest Hugging Face project, known as …
> fix: Support all SageMaker HF text generation models (other than Falcon)

- haystack/nodes/reader/table.py
- test/nodes/test_table_reader.py
> Remove deprecated param `return_table_cell`

- haystack/document_stores/elasticsearch/__init__.py
- haystack/document_stores/elasticsearch/es7.py
- test/document_stores/test_elasticsearch.py
As discussed in https://github.com/deepset-ai/haystack/pull/5216, in order to support version 8 of the Elasticsearch client, we're going to:
- introduce a base class for two new Document Stores, `Elasticsearch7DocumentStore` and `Elasticsearch8DocumentStore`
- Depending on the client available in the system, Haystack will import either of the two under the name `ElasticsearchDocumentStore` to keep backward compatibility
As pointed out in https://github.com/deepset-ai/haystack/pull/5216/files#r1245685837 the best course of action to keep the code well encapsulated and readable is to move `haystack.document_stores.elasticsearch` from a module into a package, where most of the subsequent refactoring will happen.
unit tests, …
> refactor: prepare support to Elasticsearch 8

- haystack/document_stores/filter_utils.py
- test/document_stores/test_memory.py
- fixes #5146
This PR adds support for filtering on list fields in `InMemoryDocumentStore` for the following operators
- `$in`/`$nin`
- `$gt`/`$gte`
- `$lt`/`$lte`
I removed the `skip` mark on the tests. These tests are passing now.
- I ran …
> fix: Allow filtering on list fields in `InMemoryDocumentStore` with all operators

- haystack/document_stores/elasticsearch/__init__.py
- haystack/document_stores/elasticsearch/es8.py
- pyproject.toml
- test/document_stores/test_elasticsearch.py
- test/document_stores/test_search_engine.py
- follow up of https://github.com/deepset-ai/haystack/pull/5228
Add a new module `es8.py` with a document store that can run with ES 8 and later.
Manually tested for now, no changes to the CI were made.
Tests would pick the right Document Store class depending on the client installed …
> refactor: add a new Document Store supporting Elasticsearch 8

- haystack/document_stores/opensearch.py
- haystack/document_stores/search_engine.py
- test/document_stores/test_opensearch.py
Isolate calls to `self.client.*` so that we can override them in the class supporting ES8
locally run the tests …
> refactor: isolate Elasticsearch client calls

- .github/workflows/rest_api_tests.yml
- rest_api/rest_api/controller/feedback.py
- rest_api/rest_api/utils.py
- fixes [failing REST API CI](https://github.com/deepset-ai/haystack/actions/runs/5442095146/jobs/9896900307)
- `InMemoryDocumentStore` requires `inference` and is used in the REST API tests. This PR adds that extra to the CI.
CI
n/a
- I ran …
> fix: install `inference` in REST API tests

- haystack/utils/import_utils.py
- test/others/test_utils.py
- fixes #5198
The extension of the archive was determined by splitting the URL at `"."` using `rpartition` and then using the string to the right of the `"."` as the file extension.
This pull request uses `urllib.parse.urlparse` to split the URL into its components. Then I use `splitext` to split the archive extension from the path in the URL. 
Manual test with the To Reproduce instruction from #5198
> fix: `import_utils fetch_archive_from_http` -  improve url parsing for fetching archive from http

- haystack/schema.py
- test/others/test_schema.py
- fixes https://github.com/deepset-ai/haystack/issues/5256
- Update `MultiLabel` to convert `Label`s to dicts using `Label.to_dict()`. `Label.to_dict()` already converts pandas dataframes into a lists of lists which is json serliazable which allows `Multilable.to_json()` to work as expected for Table Labels.
- Similarily the `MultiLabel.from_dict()` method was updated to use `Label.from_dict()`
- added a new unit test …
> fix: MultiLabel `to_json` works with Table Labels

- haystack/document_stores/elasticsearch/base.py
- haystack/document_stores/elasticsearch/es8.py
- haystack/document_stores/search_engine.py
Remove deprecation warnings by using the new client api.
manual verification after running integration tests locally:
```sh
pytest -m"integration and document_store" test/document_stores/test_elasticsearch.py 
```
- `es_converter.py` still needs to be adjusted - instead of using a document store instance it uses the client directly, so it requires quite some rework, probably too much for this PR.
- the PR contains some leftovers from the previous iteration, where I didn't port the calls to `self.client.*` in `base.py`
- I …
> refactor: remove Elasticsearch client version 8 deprecation warnings

- test/conftest.py
- related to https://github.com/deepset-ai/haystack/pull/5218
- remove the return_table_cell from the conftest.py
- Ran table tests locally. They aren't run in CI since they are mostly marked as integration tests. However, integration tests are not run for the nodes folder and in reality these tests should most likely be considered end-to-end tests. …
> chore: Remove deprecated return_table_cell from conftest.py

- test/benchmarks/configs/retriever_reader/mpnetbase-debertabase-opensearch-100k.yml
- test/benchmarks/configs/retriever_reader/mpnetbase-debertalarge-opensearch-100k.yml
- test/benchmarks/configs/retriever_reader/mpnetbase-tinyroberta-opensearch-100k.yml
- fixes n/a
This PR adapts the batch size parameter of `OpenSearchDocumentStore` for three of the retriever-reader configurations. This is needed as the benchmarks fail with a batch size of 5000 on a p3.2xlarge instance.
I manually ran the changed configurations on a p3.2xlarge instance. …
> test: Adapt batch size in retriever-reader benchmarks

- docker/Dockerfile.base
This PR introduces a fix for our Docker base image build by adding explicit dependencies for `libxml2-dev` and `libxslt1-dev` packages.  We added them to the RUN apt-get directive in our Dockerfile.
The Docker base image build has been failing because of missing dependencies required by `python-docx` and its dependency `lxml`. These two Python packages require `libxml2-dev` and `libxslt1-dev` to be present in the environment. Since `python-docx` is included in the base image as a part of our file-conversion optional dependency, it is crucial that these packages are installed for successful image builds.
This is an internal change and does not affect users. It only ensures that our Docker images can be built successfully.
The absence of `libxml2-dev` and `libxslt1-dev` was noticed during …
> fix: Add dependecies to build lxml successfully in base Docker image

- test/conftest.py
Remove caching of requests to `huggingface.co` when running tests to integration tests failures. 
`huggingface_hub` already handles caching by itself as [documented](https://huggingface.co/docs/huggingface_hub/guides/manage-cache) so this shouldn't affect our limits.
I ran CI with PR #5282 to troubleshoot the issue, turns out that removing cache makes tests run correctly.
The failures weren't reproducible locally while running individual tests.
Failures examples: https://github.com/deepset-ai/haystack/actions/runs/5473396123 …
> Remove requests_cache in tests

- haystack/nodes/prompt/invocation_layer/azure_chatgpt.py
- haystack/nodes/prompt/invocation_layer/azure_open_ai.py
- haystack/nodes/prompt/invocation_layer/chatgpt.py
- haystack/nodes/prompt/invocation_layer/open_ai.py
- haystack/nodes/prompt/invocation_layer/utils.py
- haystack/nodes/prompt/prompt_model.py
- test/prompt/test_prompt_node.py
This PR introduces a refactoring change that removes the dependency on Azure layers check within the PromptModel (see loc [90-95](https://github.com/deepset-ai/haystack/blob/main/haystack/nodes/prompt/prompt_model.py#L90)). As part of this change, we have added a utility function `has_azure_parameters` which simplifies the logic of selecting the right invocation layer between Azure and OpenAI:
```python
def has_azure_parameters(**kwargs) -> bool:
azure_params = ["azure_base_url", "azure_deployment_name"]
return any(kwargs.get(param) for param in azure_params)
```    
Currently, a small kludge in the PromptModel checks for the presence of Azure layers. However, PromptModel should not know specific implementation details related to Azure layers. This change relies on the existing logic from …
> refactor: Simplify selection of Azure vs OpenAI invocation layers

- haystack/nodes/prompt/invocation_layer/__init__.py
- haystack/nodes/prompt/invocation_layer/hugging_face.py
- test/prompt/invocation_layer/test_hugging_face.py
- test/prompt/invocation_layer/test_invocation_layers.py
- fixes #4848 
Before this fix, the HF invocation layer was tested early which caused the process not to reach the correct invocation layer check if the HF servers were unresponsive. This PR changes the invocation order so HF is checked later and adds a timeout of 1s so it can't get stuck waiting for a response from the HF servers.
I added a unit test that checks that the timeout is handled correctly. There is also a new test checking that the huggingface checks are in the last five invocation layer checks.
The timeout is set to 1s and can't be changed by the user. This could potentially lead to issues. I am also not sure about whether the test for the invocation layer order should be different because it does not make sure the methods are actually called in that order.
I have discussed …
> fix: Improve robustness of get_task HF pipeline invocations

- .github/workflows/docker_release.yml
- docker/docker-bake.hcl
- haystack/nodes/retriever/web.py
- rest_api/rest_api/pipeline/pipelines_web_lfqa.haystack-pipeline.yaml
Introduces a new Docker image, `haystack:cpu-remote-inference-<version>`, to our existing images: `haystack:gpu-<version>` and `haystack:cpu-<version>`. This image is a slimmed-down version of cpu/gpu images, specifically designed for PromptNode inferencing using remote-hosted models such as HuggingFace Inference, OpenAI, Cohere, Anthropic etc.
- fixes #5172
The motivation behind the introduction of this new Docker image is to provide a more efficient and lightweight option for users who primarily perform remote Large Language Model (LLM) inference. The existing Docker images for Haystack are comprehensive and can be larger than necessary for users primarily using remote LLM inferencing. By introducing this new Docker image, we offer a more streamlined and efficient option for Haystack …
> Add `cpu-remote-inference` Docker image

- haystack/nodes/answer_generator/base.py
- test/conftest.py
- test/nodes/test_generator.py
- test/pipelines/test_eval.py
- related to #3275
This PR adds the parameter `add_isolated_node_eval` to the `run_batch` method of the `BaseGenerator`. This is needed for cases where a user calls `eval_batch` on a Pipeline with `add_isolated_node_eval=True`. Previously, this parameter was just ignored.
I added two unit tests, one for `run` and one for `run_batch`.
I moved the `EVAL_LABELS` from `test_eval.py` to a fixture in `conftest.py` to be able to use them in `test_generator.py`.
- I've used one of …
> fix: Support isolated node eval in run_batch in Generators

- haystack/nodes/answer_generator/openai.py
- haystack/nodes/prompt/invocation_layer/open_ai.py
- haystack/nodes/retriever/_openai_encoder.py
- haystack/nodes/retriever/dense.py
- test/nodes/test_generator.py
- test/nodes/test_retriever.py
- test/prompt/invocation_layer/test_openai.py
- fixes #5210
- Added the (optional) `OpenAI-Organization` string to headers for requests to OpenAI API
- In `OpenAIInvocationLayer`, `OpenAIAnswerGenerator` and `EmbeddingRetriever`
New unit tests for each node involved. …
> feat: support `OpenAI-Organization` for authentication

- haystack/preview/document_stores/__init__.py
- haystack/preview/document_stores/memory/document_store.py
- haystack/preview/document_stores/protocols.py
- haystack/preview/pipeline.py
- test/preview/document_stores/_base.py
- test/preview/document_stores/test_memory.py
- ground work for https://github.com/deepset-ai/haystack/issues/5238
- Introduces a Store protocol with the 4 methods specified in the original proposal
- Adapts typing in Pipeline
- Adds typing in tests
- Existing tests
Should we test Protocols, and if yes, how? In my opinion they don't need, but I''l wait for @silvanocerza's opinion. …
> feat: introduce `Store` protocol (v2)

- haystack/preview/components/retrievers/memory.py
- test/preview/components/retrievers/test_memory_retriever.py
- fixes https://github.com/deepset-ai/haystack/issues/5286
- Change `MemoryRetriever` to accept `queries: List[str]` in place of `query: str` and output `documents: List[List[Documents]]` in place of `documents: List[Documents]`.
- Update and add tests
Local tests run.
n/a …
> feat: batch mode for `MemoryRetriever` (v2)

- docs/pydoc/renderers.py
Add `parentDocSlug` in API reference docs frontmatter. 
Set `renderer.parent_doc_slug` in docs config yamls to create the hierarchy.
I generated docs locally and uploaded them to Readme.io to verify the hierarchy would be created correctly.
An empty or unset `parent_doc_slug` won't make render or upload fail. …
> chore: Add support for hierarchical docs

- pyproject.toml
- related to #5027
This PR adds the installation extras `elasticsearch7` and `elasticsearch8` and points the installation extra `elasticsearch` to `elasticsearch7`.
I manually executed `pip install .[elasticsearch]`, `pip install .[elasticsearch7]`, and `pip install .[elasticsearch8]`.
We decided that with Haystack 1.21, Elasticsearch 8 will become the default one and we will remove the extra `elasticsearch8`. Instead, the extra `elasticsearch` will install version 8 of the Elasticsearch client. …
> build: Add `elasticsearch7` and `elasticsearch8` extra

- haystack/document_stores/elasticsearch/es7.py
- related to #5027
This PR adapts the import error message for the `ElasticsearchDocumentStore` in `es7.py` to prepare the user for the fact that starting from Haystack 1.21, the `elasticsearch` extra will install client version 8 and require a Elasticsearch 8 instance.
I manually checked that the new error message is printed. …
> chore: Adapt import message for Elasticsearch7

- .github/workflows/tests.yml
- related to #5027
- depends on #5296 
This PR renames the job `integration-tests-elasticsearch` to `integration-tests-elasticsearch7` and lets it run using Elasticsearch 7.17.6 to test `es7.ElasticsearchDocumentStore`. 
Furthermore, it adds the job `integration-tests-elasticsearch8` which installs the installation extra `elasticsearch8` and, therefore, uses  `es8.ElasticsearchDocumentStore` for the integration tests using Elasticsearch 8.8.0.
This PR depends on #5296.
- I've …
> ci: Add job for ES8 integration tests

- test/nodes/test_retriever.py
- fixes N/A
Refactored some retriever tests into unit tests.
> test: Refactor some retriever tests into unit tests

- haystack/nodes/query_classifier/sklearn.py
- pyproject.toml
- test/nodes/test_query_classifier.py
- fixes #5323
Classic deprecation procedure for `SklearnQueryClassifier`
New deprecation warning test
> chore: deprecate `SklearnQueryClassifier`

- haystack/nodes/retriever/dense.py
- test/conftest.py
- test/nodes/test_retriever.py
- fixes #5294 
Updates the `EmbeddingRetriever._preprocess_documents` function to support embedding meta fields that contain a list of values. 
Added a new unit test to check that meta fields are added to the beginning of the document as expected. …
> feat: Add support for meta fields that are lists when using embed_meta_fields

- docs/pydoc/config/invocation-layers.yml
- fixes #5170 
Adding a new API reference page dedicated to invocation layers.
> create invocation-layers API reference page

- pyproject.toml
- part of #5321
Simply pin `scikit-learn>=1.3.0`
> chore: pin `scikit-learn>=1.3.0`

- haystack/nodes/prompt/invocation_layer/hugging_face.py
- haystack/nodes/prompt/invocation_layer/hugging_face_inference.py
- haystack/nodes/prompt/invocation_layer/utils.py
- test/prompt/invocation_layer/test_hugging_face.py
- test/prompt/invocation_layer/test_hugging_face_inference.py
- #4848 
HFLocalInvocationLayer.supports would previously fail if the optional inference dependencies are not installed. This PR causes it not to fail and instead to return false.
I added a test case in test_hugging_face.py::test_supports.
@vblagoje originally discovered the bug and discussed the solution with me as #4848 affects when this problem occurs. …
> fix: Run HFLocalInvocationLayer.supports even if inference packages are not installed

- docs/pydoc/config/retriever.yml
- examples/link_content_blog_post_summary.py
- haystack/nodes/__init__.py
- haystack/nodes/retriever/__init__.py
- haystack/nodes/retriever/link_content.py
- test/nodes/test_link_content_fetcher.py
- test/nodes/test_link_content_retriever.py
Introduces a new component, `LinkContentRetriever`. This component already implicitly exists within `WebRetriever` but has never been explicitly exposed until now.
There is a growing necessity to separate `LinkContentRetriever` from the existing `WebRetriever` code base and expose it as an independent component yet allow it to be reused within WebRetriever. The standalone `LinkContentRetriever` will be particularly beneficial in pipeline and agent scenarios where content needs to be fetched from a specific URL link. This will be useful in scenarios such as, "Read https://pythonspeed.com/articles/base-image-python-docker-images/ and extract the main conclusion from the blog post, be brief." `LinkContentRetriever` will be particularly beneficial for Haystack V2, as it will enable the …
> refactor: Extract link retrieval from WebRetriever, introduce LinkContentRetriever

- haystack/nodes/retriever/web.py
- fixes #5214 
- added docstrings for `api_key`, `search_engine_provider` and `top_search_results`
- changed default `mode` to "preprocessed_documents" as stated in docstrings …
> fix: update WebRetriever docstrings and default mode

- haystack/document_stores/elasticsearch/base.py
- haystack/document_stores/elasticsearch/es7.py
- haystack/document_stores/elasticsearch/es8.py
- haystack/document_stores/search_engine.py
- test/document_stores/test_elasticsearch.py
- test/document_stores/test_opensearch.py
- fixes #5068
This PR adds a check to `elasticsearch/es7.py` and `elasticsearch/es8.py` that checks the version of the connected Elasticsearch server and logs a warning if the server version is not consistent with the version of the used `ElasticsearchDocumentStore`.
Also, this PR adds support for Elasticsearch versions <= 7.5 by using a different vector similarity query for Elasticsearch servers with versions <= 7.5.
I added two unit tests to test that the `"source"` field of the ES query is formatted according to the used version.
- I have updated the related issue with new insights …
> feat: Check version of Elasticsearch server and add support for Elasticsearch <= 7.5

- haystack/nodes/prompt/invocation_layer/hugging_face.py
- test/prompt/invocation_layer/test_hugging_face.py
- fixes [#issue-number](https://github.com/deepset-ai/haystack/issues/5315)
- get the last generated token instead of getting the whole output ids 
- remove all() 
use the example mentioned in the related issue
since the other PR is not merged into the main, the example can't be tested directly. You need to hard-code the generat_kwargs in the `invoke` method except the `stop_words`. …
> fix: a small bug in StopWordsCriteria

- test/prompt/invocation_layer/test_openai.py
This PR improves the unit tests for OpenAIInvocationLayer focusing on token limitation triggering (and not)
A user raised an issue in [#5184](https://github.com/deepset-ai/haystack/issues/5184), which appears to be unrelated. However, this presented an opportunity to enhance the unit tests for OpenAIInvocationLayer.
This PR does not affect the functionality used by end-users. It solely enhances the internal testing mechanisms for the OpenAIInvocationLayer.
There are no code changes. The changes are about unit testing for OpenAIInvocationLayer.
> tests: Improve token limit tests for OpenAI PromptNode layer

- .github/workflows/e2e.yml
- e2e/document_search/test_standard_pipeline.py
- e2e/models_to_cache.txt
- fixes https://github.com/deepset-ai/haystack/issues/5333
We want to set up end-to-end tests and as a first step aim to re-enable the existing e2e workflow.
- Update installation of Haystack with required extras
- Start spinning up docker containers for document stores earlier to give more time for starting up while Haystack is installed 
- Trigger by cron job for nightly runs (plus manually)
- Use only one simple end-to-end test with a DocumentSearchPipeline with common parameter settings and deactivate all other tests. Refactoring of old, deactivated tests is a separate issue: https://github.com/deepset-ai/haystack/issues/5350
I tested the docker commands and `pytest e2e/document_stores` locally. The tests themselves took only 2 minutes. 
I also tested `pip install …
> test: Re-activate end-to-end tests workflow

- docs/pydoc/requirements.txt
- [Failing workflow](https://github.com/deepset-ai/haystack/pull/5400#issue-1813916701) on `main`
This PR pins `PyYAML` to `5.3.1` for our `Sync docs with Readme` workflow. 
Workflow is running in the CI of this PR.
There was a release of a new major version of Cython which doesn't seem to be compatible with PyYAML 5.4. …
> docs: Pin `PyYAML` to `5.3.1`

- docs/pydoc/requirements.txt
- fixes pinning a version of PyYAML that's too old
Update `pydoc-markdown` so we can unpin everything else and get more recent versions of its dependencies
Manualyl tested locally …
> chore: bump pydoc-markdown version

- pyproject.toml
Upgrade transformers to most recent release (18th of July) https://github.com/huggingface/transformers/releases/tag/v4.31.0
Let's see whether CI tests pass
Some features of the release that are relevant to us are:
- Llama v2
- RoPE scaling for LLaMa and GPTNeoX families of models
> build: upgrade transformers to v4.31.0

- examples/link_content_blog_post_summary.py
- haystack/nodes/prompt/invocation_layer/anthropic_claude.py
- haystack/nodes/prompt/invocation_layer/handlers.py
- test/prompt/invocation_layer/test_anthropic_claude.py
- test/prompt/test_handlers.py
This PR updates several parameters in the AnthropicClaudeInvocationLayer to align it with the recent updates of the Anthropic Claude models, specifically related to their ability to handle larger context window sizes. Additionally, the `examples/link_content_blog_post_summary.py` script has been converted to use Claude models to foster a practice of easy interaction and testing of Anthropic models more often.
We want to enable our community to use the latest Anthropic Claude models. These models now offer larger context window sizes, and updating our AnthropicClaudeInvocationLayer will enable us to leverage these improvements fully. Additionally, by integrating Claude models into our example scripts, we provide a straightforward way for users and developers to interact with and test these …
> feat: Update Claude support with the latest models, new streaming API, context window sizes

- haystack/nodes/ranker/recentness_ranker.py
- The error message suggested that only 0, 0.5 and 1.0 are valid values but any value in range [0,1] is valid.
Change error message so that it mentions that any value in range [0,1] is valid. …
> fix: Error message about weight param in RecentnessRanker

- .github/CODEOWNERS
- CONTRIBUTING.md
- pyproject.toml
- releasenotes/config.yaml
- releasenotes/notes/add-reno-e284cb173ab45ab3.yaml
- part of https://github.com/deepset-ai/haystack/issues/5408
Introduce [`reno`](https://docs.openstack.org/reno/latest/index.html) to manage release notes. Upcoming release of
Haystack 1.19 will still use PR titles to form the changelog, but we'll start using the new format immediately in the unstable branch.
Automation and sanity checks will be added immediately after this PR, in the meantime we'll rely on manual review to ensure release notes are present in PRs we merge in `main`. …
> feat: add `reno` to manage release notes

- haystack/testing/document_store.py
- test/pipelines/test_eval.py
- test/pipelines/test_eval_batch.py
- fixes N/A, but related to bug fix in PR https://github.com/deepset-ai/haystack/pull/5223 in the sense that the bug was originally missed due to pipeline.eval tests not being run in CI. 
- ~~Activates a subset of existing `pipeline.eval` tests by marking them with integration or unit if they follow the guidelines. I followed the guidelines outlined [here](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and I believe I gave each test an appropriate label. None of the tests request outside resources and the major difference between them relate to scope of logic being tested.~~
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_conduc …
> test: reactivate unit tests in `test_eval.py`

- rest_api/rest_api/controller/health.py
In this PR, we make an improvement to the log warning in the REST API /health endpoint. Specifically, we change the warning message from "No NVIDIA GPU found." to "Couldn't collect GPU stats: <the actual underlying nvml error>".
The current warning message is misleading and may cause confusion among users, potentially leading to unnecessary new issues being created. By giving a more descriptive and accurate warning, we aim to provide a better user experience and minimize confusion.
This change is internal and does not affect the way users interact with the REST API /health endpoint. The improvement will only affect the content of the log messages generated when a request is made to this endpoint.
The testing for this change is still ongoing. Manual testing is currently being conducted to …
> fix:Improve log warnings in REST API /health endpoint

- pyproject.toml
`mlflow` previously pinned in #5094.
Remove the pin since new releases came out that fixed the bug that was breaking our schema generation.
Constraint `dulwich` and `botocore` versions to speed up dependency tree resolution.
Run `cache_schema` after installing new `mlflow` version.
https://github.com/deepset-ai/haystack/blob/7940ec048277354e3dadf07584b7a145fc904961/haystack/utils/docker.py#L41
This should also fix the long running installation time that we're seeing currently in CI.
Like this: https://github.com/deepset-ai/haystack/actions/runs/5659647804
`dulwich` is a [`reno` dependency](https://opendev.org/openstack/reno/src/branch/master/requirements.txt#L7).
`botocore` is a [`boto3` dependency](https://github.com/boto/boto3/blob/dae73bef223abbedfa7317a783070831febc0c90/setup.py#L16). …
> build: Unpin mlflow, constraint dulwich and botocore

- .github/workflows/release_notes.yml
- fixes #5426 
Add a workflow that checks for the presence of a `.yaml` file in the `releasenotes/notes` folder in each PR. The check is skipped if the PR has the `ignore-for-release-notes` label attached.
Manually tested on a different repo
This check doesn't validate the actual content of the release notes, this might be a nice-to-have follow up. …
> chore: Add a workflow to check the presence of release notes

- haystack/nodes/prompt/invocation_layer/azure_open_ai.py
- haystack/nodes/prompt/invocation_layer/open_ai.py
- haystack/nodes/retriever/dense.py
- releasenotes/notes/restrict-openai-supports-method-fb126583e4beb057.yaml
- test/prompt/invocation_layer/test_openai.py
- fixes #5419
I found out that the OpenAI invocation layer intercepted the HF model "ybelkada/flan-t5-xl-sharded-bf16" because it has the string "ada" in its name. (In HF, there are > 1000 models containing the string "ada")
We don't particularly like the current invocation layers' "magic" mechanism, but in the meantime, I restricted the criteria to identify an OpenAI model by name.
- New unit test: it only tests that now the OpenAI invocation layer recognizes a more limited set of model names.
- Manual test to check the overall behavior.
- (existing tests).
Similarly, I updated the Azure invocation layer and the OpenAI model identification in the Retriever. …
> fix: restrict `supports` method in the OpenAI invocation layer and a similar method in the `EmbeddingRetriever`

- .github/workflows/readme_sync.yml
- docs/pydoc/renderers.py
Change the generated frontmatter in docs markdown to use `parentDoc` ID instead of `parentDocSlug`.
This should fix this kind of failures: https://github.com/deepset-ai/haystack/actions/runs/5724634323/job/15511516957
Can't really test it without merging in `main` first.
The problem stems from `rdme` CLI fetching the existing document from Readme.io and then updating with the fields from the markdown frontmatter. See [this code snippet](https://github.com/readmeio/rdme/blob/01ed07d63eeeda9be92b4907c59bdf1283a0b4ce/src/cmds/docs/edit.ts#L97-L99).
This causes upload to fail with this message:
> We couldn't save this doc (received both a `parentDoc` and a `parentDocSlug`, expecting only one).
This happens because internally they use `parentDoc` to create hierarchies, so they return that when …
> chore: Rework docs generation

- pyproject.toml
- releasenotes/notes/remove-upper-bound-for-weaviate-client-126daeccdbbe6939.yaml
- failing Weaviate tests due to installing version 2 of the client (see this [workflow run](https://github.com/deepset-ai/haystack/actions/runs/5728939628/job/15531313930?pr=5314) for example)
This PR removes the upper bound for the version of the Weaviate client and ensure to install at least version 3.
Ci is running through. …
> build: Remove upper bound for weaviate client

- examples/web_lfqa.py
- haystack/nodes/retriever/web.py
- haystack/nodes/search_engine/web.py
- releasenotes/notes/refactor-web-retriever-a0604ead72b84fdc.yaml
- test/nodes/test_web_retriever.py
This pull request proposes simplifying the existing `WebRetriever` component by internally utilizing the recently isolated `LinkContentFetcher`(see #5227 for more details).
After successfully extracting `LinkContentFetcher` from the existing code base, it's now appropriate to utilize this standalone component within `WebRetriever` as well. This refactoring not only improves the structure of our code but also enhances maintainability and readability.
The use of `WebRetriever` remains unaffected by this change. The refactoring does not alter any public APIs, so we can continue to use `WebRetriever` as we did previously.
The refactoring is validated by updating the existing unit tests and adding new comprehensive ones to ensure the robustness of the WebRetriever post-refactoring. …
> refactor: Update WebRetriever to use LinkContentFetcher

- haystack/nodes/ranker/diversity.py
- releasenotes/notes/diversity-ranker-add-topk-24f23136f316129a.yaml
- test/nodes/test_diversity_ranker.py
This PR introduces a `top_k` parameter to the `DiversityRanker` class. The `top_k` parameter allows users to specify the number of top documents to be returned after the ranking process.
The `top_k` parameter provides more flexibility and control to the users over the ranking process. It allows users to limit the number of documents returned, which can be beneficial in scenarios where only the top few documents are of interest.
- fixes https://github.com/deepset-ai/haystack/issues/5489
The `top_k` parameter can be used during the initialization of the `DiversityRanker` class. Here's an example:
```python
ranker = DiversityRanker(top_k=5)
```
In this example, the `DiversityRanker` will return the top 5 documents after the ranking process.
The new feature was tested by adding unit tests …
> feat: Add `top_k` parameter to `DiversityRanker` init method

- docs/pydoc/config/ranker.yml
- examples/web_lfqa_improved.py
- haystack/nodes/ranker/lost_in_the_middle.py
- releasenotes/notes/add-lost-in-the-middle-ranker-6ad7dda754fad5a9.yaml
- test/nodes/test_lost_in_the_middle.py
Introduces a new ranker, `LostInTheMiddleRanker`. This ranker ranks documents based on the "Lost in the Middle" order, designed to position "the best" documents (low index in the given list of documents) at the beginning and the end of the resulting list while placing "the worst" documents (high index in the given list of documents) in the middle. 
The "Lost in the Middle" order is a strategy for laying out paragraphs in a way that places the most relevant paragraphs at the beginning or end of the LLMs context window while the least relevant paragraphs are placed in the middle. This strategy is based on the recent research [paper](https://arxiv.org/abs/2307.03172) "Lost in the Middle: How Language Models Use Long Contexts" by Liu et al. Implementing this strategy as a ranker in Haystack …
> feat: Add LostInTheMiddleRanker

- releasenotes/notes/improve-hf-invocation-layer-tests-c42250d11d1d06c1.yaml
- test/prompt/invocation_layer/test_hugging_face.py
This pull request modifies two existing tests for the `HFLocalInvocationLayer` class, specifically `test_generation_kwargs_from_constructor` and `test_generation_kwargs_from_invoke`. The tests were previously marked as integration tests but have been converted to unit tests in this PR.
Unit tests are generally faster and more isolated than integration tests, making them more suitable for testing individual components of a system. By converting these tests from integration to unit tests, we can improve the speed of our test suite overall.
These changes do not directly affect the usage of the `HFLocalInvocationLayer` class. However, they do improve the speed of our test suite.
The modified tests were run as part of the existing test suite to ensure they still pass after being converted to …
> test: Convert two HFLocalInvocationLayer integration to unit tests

- haystack/document_stores/deepsetcloud.py
- haystack/utils/deepsetcloud.py
- releasenotes/notes/deepset-cloud-document-store-search-fields-40b2322466f808a3.yaml
- fixes https://github.com/deepset-ai/haystack/issues/5456
- add `search_fields` to `DeepsetCloudDocumentStore`
- no explicit tests needed, we only want that this param is allowed during Haystack schema validation …
> feat: support search_fields in DeepsetCloudDocumentStore

- examples/web_lfqa_improved.py
This PR improves the `examples/web_lfqa_improved.py` example by tweaking the prompt for longer, more elaborate answers. It also adds functionality to switch between different LLMs used in the PromptNode easily. We also add more questions requiring complex, elaborate answers. 
The changes were made to enhance the flexibility and usability of the LFQA web example. By allowing easy switching between different LLMs, users can experiment with various models and observe their performance. Tweaking the prompt for longer answers can help in generating more detailed and informative responses.
The changes were implemented by modifying the `examples/web_lfqa_improved.py` script. The prompt was adjusted to encourage the generation of longer answers. Additionally, a mechanism was added to facilitate …
> feat: Improve LFQA Web Example

- CONTRIBUTING.md
- discussion: #5521
The ui directory was removed in #3829.
The contributing guidelines still mention this directory in the text and in some commands.
I simply removed these references.
No need to test it. …
> chore: contributing guidelines - remove references to the ui directory

- test/benchmarks/datadog/metric_handler.py
Benchmarks data not being ingested
> fix: Fix datadog client init in benchmarks

- haystack/nodes/prompt/invocation_layer/hugging_face.py
- releasenotes/notes/fix-stop-words-criteria-check-order-bug-4badfcc021dfc92a.yaml
- test/prompt/invocation_layer/test_hugging_face.py
- fixes #5502 
- remove `torch.isin()`
- add logic to examine the sublist in a continuous and sequential order
unit test
> fix: StopWordsCriteria doesn't compare the stop word token ids with the input ids in a continuous and sequential order

- haystack/nodes/connector/crawler.py
- pyproject.toml
- releasenotes/notes/update-crawler-selenium-4.11-30fec9f6e345834f.yaml
- test/nodes/test_connector.py
- fixes #5500 
With the recent release of Selenium, the Crawler started failing both locally and in Colab.
Thanks to changes recently introduced in Selenium, we can get rid of the `webdriver-manager` dependency:
[now Selenium automatically finds or installs the required drivers](https://stackoverflow.com/questions/76799165/selenium-webdriver-manager-results-in-webdriverexception-message-can-not-con).
- I pinned selenium>=4.11.0 (and removed webdriver-manager)
- I changed the crawler initialization to make it work
- I took the opportunity to refactor and simplify the code 
Existing tests (CI), manual tests on Ubuntu and in Colab. …
> refactor: update Crawler to support selenium>=4.11.0 and simplify it

- haystack/nodes/prompt/prompt_node.py
- haystack/nodes/prompt/prompt_template.py
- releasenotes/notes/remove-template-vars-invocation-kwargs-060f186fd1250fe4.yaml
- test/prompt/test_prompt_node.py
- test/prompt/test_prompt_template.py
The primary motivation behind this change is to simplify the way we handle `kwargs` in the `PromptModel` invocation layers. By removing template parameters from all `kwargs` passed to these layers, we aim to eliminate the "kwarg guards" present in each underlying layer. This change will shift the responsibility of passing the correct `kwargs` to the `PromptNode` user, ensuring a cleaner and more maintainable codebase.
A new function, `remove_template_params`, has been added to the `PromptTemplate`. This function is designed to process and remove any template parameters from `kwargs` before they are passed on to the invocation layers. This ensures that only the necessary arguments are passed down, reducing the complexity and potential for errors.
It's important to note that this is an …
> feat: Remove template variables from PromptNode invocation kwargs

- pyproject.toml
Docker image builds are failing: https://github.com/deepset-ai/haystack/actions/runs/5797416046/job/15712906773
It is related to the new release of safetensors (0.3.2).
[safetensors issue](https://github.com/huggingface/safetensors/issues/314)
Pin safetensors<0.3.2
Should be unpinned when saftensor issue is solved. …
> build: pin safetensors

- haystack/nodes/image_to_text/transformers.py
- releasenotes/notes/fix-issue-#5485-efa4486a414ce584.yaml
- fixes #5485
If the user passes a string as image_file_paths, an Exception is raised.
Manual verification with the code snippet provided by @bilgeyucel in issue #5485  …
> fix: TransformersImageToText.generate_captions accepts "str" #5485

- haystack/document_stores/weaviate.py
Updating the weaviate docstrings to replace the old URL with the new correct one. The old one now gives a 404.
> docs: update weaviate.py docstrings

- haystack/preview/document_stores/decorator.py
- haystack/preview/document_stores/errors.py
- haystack/preview/document_stores/memory/document_store.py
- haystack/preview/document_stores/protocols.py
- releasenotes/notes/stores-serialisation-a09398d158b01ae6.yaml
- test/preview/document_stores/test_decorator.py
- test/preview/document_stores/test_memory.py
Add `to_dict` and `from_dict` methods to `Store` `Protocol`.
Also add a default implementation to all classes decoratored with `@store`.
Added unit tests.
N/A
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING. …
> Add `to_dict` and `from_dict` methods for Stores

- haystack/preview/__init__.py
- haystack/preview/components/retrievers/memory.py
- haystack/preview/document_stores/__init__.py
- haystack/preview/document_stores/decorator.py
- haystack/preview/document_stores/errors.py
- haystack/preview/document_stores/memory/document_store.py
- haystack/preview/document_stores/mixins.py
- haystack/preview/document_stores/protocols.py
- haystack/preview/pipeline.py
- haystack/preview/testing/factory.py
- haystack/testing/preview/document_store.py
- test/preview/components/retrievers/test_memory_retriever.py
- test/preview/document_stores/test_decorator.py
- test/preview/document_stores/test_memory.py
- test/preview/pipeline/test_pipeline.py
- test/preview/testing/test_factory.py
- fixes n/a
Rename `@store` do `@document_store` and use `DocumentStore` instead of `Store` across the codebase
Unit tests
No functional changes, only renaming
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING …
> chore: rename `store` to `document_store` for clarity

- test/benchmarks/datadog/metric_handler.py
- fixes n/a
Datadog's `send` method expects a list of (timestamp, value) pairs as points, so this PR changes the type of the value passed to the `points` parameter to `List[Tuple]`. Also, the timestamp should be an int instead of a float.
I manually sent metrics to datadog, which are now displayed correctly.  …
> fix: Use correct type for points in datadog (benchmarks)

- haystack/preview/components/audio/whisper_remote.py
- pyproject.toml
Update `canals` version to `0.5.0`. This update includes a new way to serialise `Component`s and `Pipeline`.
I ran `pytest -m "unit" -x test/preview`.
`RemoteWhisperTranscriber` serialises the API key it uses as plain text, this is bad but we still need to figure a way to handle secrets properly for serialisation. …
> Update `canals` to `0.5.0`

- haystack/preview/components/audio/whisper_remote.py
- haystack/preview/document_stores/memory/document_store.py
- haystack/preview/utils/__init__.py
- haystack/preview/utils/expit.py
- haystack/preview/utils/requests_utils.py
- test/preview/components/audio/test_whisper_remote.py
- fixes n/a
Copy over two small utilities into `preview` to avoid depending on `farm-haystack`. This will ease the creation of a `preview` installable package, very much needed as the preview code gets more and more usable.
- I didn't copy over the `numba`-dependent code, we don't need it to be fast now and I'm optimising for simplicity
- I had to fix a weird call to `expit` that was exposed by mypy …
> chore: remove haystack dependencies from preview

- haystack/nodes/retriever/web.py
- releasenotes/notes/adjust-web-retriever-caching-logic-2e05fbc972a86f29.yaml
- test/nodes/test_web_retriever.py
The primary motivation behind this change is to enhance the efficiency and relevance of the caching mechanism in the `WebRetriever`. Previously, the caching logic was based on the query, which led to often useless caching and did not fully utilize the potential of caching based on search engine results. Previously we would rarely get a cache hit while in the new caching algorithm, the caching hit rate should be increased for relatively similar (semantically/topically) query searches, especially when scoped (more on this below). By caching link content based on search engine results, we can ensure that the most relevant and frequently accessed content is readily cached, reducing retrieval times and improving overall pipeline performance. This is especially useful for the next improvement …
> refactor: Rework WebRetriever caching, adjust tests

- releasenotes/config.yaml
- releasenotes/notes/add-file-extension-classifier-preview-40f31c27bbd7cff9.yaml
- releasenotes/notes/add-v2-answer-class-31bc8d3116922594.yaml
- releasenotes/notes/canals-0.4.0-b69b19069c4a9e0f.yaml
- releasenotes/notes/document-writer-v2-bbe0a62b3066f9cf.yaml
- releasenotes/notes/lazy-import-v2-82902270867d9899.yaml
- releasenotes/notes/store-factory-91e7da46aeb7ff21.yaml
- releasenotes/notes/stores-serialisation-a09398d158b01ae6.yaml
- releasenotes/notes/textfile-to-document-v2-341987623765ec95.yaml
- Add a new section (`preview`)  to categorize changes related to Haystack 2.0
- Update the existing notes related to Haystack 2.0 …
> chore: add `preview` section to release notes

- haystack/preview/__init__.py
- haystack/preview/components/__init__.py
- haystack/preview/components/audio/__init__.py
- haystack/preview/components/classifiers/__init__.py
- haystack/preview/components/file_converters/__init__.py
- haystack/preview/components/retrievers/__init__.py
- haystack/preview/components/writers/__init__.py
- haystack/preview/document_stores/__init__.py
- releasenotes/notes/change-import-paths-3d4eae690412e545.yaml
- test/preview/components/audio/__init__.py
- test/preview/components/audio/test_whisper_local.py
- test/preview/pipeline/test_pipeline.py
The import paths have several issues at the moment:
- they are not consistent, some names are exported up to the `preview.*` namespace, others are not
- components are exported up to `preview.*` but they shouldn't be, currently (for example) audio dependencies are always imported, even if you only need a text-to-document converter
- Leave a handful of names at the `preview.*` level, namely `component` and the types from `dataclasses`
- use `__all__` extensively, so we can control what we expose at each level
- limit pollution as much as possible
unit tests
I left out imports of `Pipeline` to minize conflicts with other ongoing PRs removing that code …
> chore: change import paths under `preview`

- haystack/preview/components/file_converters/txt.py
#5580 introduced lazy imports but `preview` is still depending on haystack v1.x in one place
> chore: leftover from #5580

- haystack/preview/components/retrievers/memory.py
- releasenotes/notes/rework-memory-retriever-73c5d3221bd96759.yaml
- test/preview/components/retrievers/test_memory_retriever.py
Rework `MemoryRetriever` so it doesn't inhering the `DocumentStoreAwareMixin` anymore.
The required `MemoryDocumentStore` is set at init time. I think this is much better as it also makes it clear that this `Component` requires that `DocumentStore` to behave correctly.
It's also easier to check if the `DocumentStore` provided is supported by the retriever this way.
As you notice we also don't require the check in `MemoryRetriever.run()` anymore as we can be sure `self.document_store` has been set.
I updated `MemoryRetriever` tests and run all `preview` package tests.
I had to comment out two `MemoryRetriever` tests as they are related to serialisation.
We'll update them after we close #5550 and when implmenting `to_dict` and `from_dict`. …
> Rework `MemoryRetriever`

- haystack/preview/components/writers/document_writer.py
- releasenotes/notes/rework-document-writer-4958db2024070f6f.yaml
- test/preview/components/writers/document_writer.py
Rework `DocumentWriter` so it doesn't inhering the `DocumentStoreAwareMixin` anymore.
The required `DocumentStore` is set at init time. I think this is much better as it also makes it clear that this `Component` requires that `DocumentStore` to behave correctly.
As you notice we also don't require the check in `DocumentWriter.run()` anymore as we can be sure `self.document_store` has been set.
I updated `DocumentWriter` tests and run all `preview` package tests.
Depends on #5582. …
> Rework `DocumentWriter`

- .github/workflows/tests.yml
`catch-all` step is meant to run only after all other jobs have finished sucessfully. 
Some jobs were missing from the list, this PR adds the missing ones.
Can't test it.
N/A …
> Add missing integration tests to catch-all required step in tests.yml

- .github/workflows/benchmarks.yml
Add back the `terminate-runner` job in `benchmarks.yml` since the `cml` tool is not 100% reliable as if we use the `--single` flag it stops the runner after the first job finished instead of waiting for the whole workflow.
See [this run](https://github.com/deepset-ai/haystack/actions/runs/5914287605) as an example.
We triggered a new run in branch `fix-benchmarks-run`.
https://github.com/deepset-ai/haystack/actions/runs/5940401105
N/A …
> Add terminate-runner job in benchmarks.yml

- .github/workflows/pypi_release_preview.yml
Add a new workflow to send a `repository_dispatch` to `deepset-ai/haystack-preview-package` to trigger the release of the Haystack preview package workflow.
The workflow to be triggered: https://github.com/deepset-ai/haystack-preview-package/blob/main/.github/workflows/pypi_release.yml
I recreated the workflows setup in two personal repositories to verify the required permissions by the API call to trigger the `repository_dispatch` event in the other repository.
As the default `GITHUB_TOKEN` can't be used as it only has permissions for the repository that triggered the workflow, in this case `deepset-ai/haystack-preview-package`, I created another Personal Access Token using the HaystackBot with the necessary permissions. …
> Add workflow to trigger preview package release

- haystack/preview/components/audio/whisper_local.py
- fixes n/a
- Update `LocalWhisperTranscriber` to not call `warm_up()` when transcribing to be coherent with all other Haystack 2.0 components.
Local tests run
n/a
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBU …
> chore: remove `self.warm_up()`

- haystack/nodes/retriever/link_content.py
- releasenotes/notes/link-content-include-snippet-if-blocked-53b0e3108f010315.yaml
- test/nodes/test_link_content_fetcher.py
The primary motivation for this change is to improve the robustness and utility of the `LinkContentFetcher` and by extension `WebRetriever` component as well. Previously, if a request for content scraping from a URL link was blocked, these components would return empty content. This PR aims to address this limitation by returning search engine snippet text as a fallback. In certain scenarios, this snippet text might be sufficient to achieve the task objective, thereby enhancing the overall functionality of these components.
The core of this change revolves around the `LinkContentFetcher` fetch logic. The logic has been slightly modified to return search engine snippet text when content scraping from a URL is blocked. Additionally, the unit tests have been adjusted to validate this new …
> fix: LinkContentFetcher - when no content retrieved (i.e. request blocked), default to snippet text

- haystack/preview/components/classifiers/file_classifier.py
- test/preview/components/classifiers/test_file_classifier.py
- See https://github.com/deepset-ai/haystack/pull/5647 for all the context.
- Serialization methods for `FileExtensionClassifier` …
> chore: serialization methods for `FileExtensionClassifier`

- haystack/preview/components/embedders/sentence_transformers_text_embedder.py
- test/preview/components/embedders/test_sentence_transformers_text_embedder.py
- See https://github.com/deepset-ai/haystack/pull/5647 for all the context.
- Serialization methods for `SentenceTransformersTextEmbedder` …
> chore: serialization methods for `SentenceTransformersTextEmbedder`

- haystack/preview/components/file_converters/txt.py
- test/preview/components/file_converters/test_textfile_to_document.py
- See https://github.com/deepset-ai/haystack/pull/5647 for all the context.
- Serialization methods for `TextFileToDocument` …
> chore: serialization methods for `TextFileToDocument`

- haystack/nodes/query_classifier/transformers.py
- test/nodes/test_query_classifier.py
- fixes #5637
`use_auth_token` is deprecated in transformers in favor of `token`. This PR changes the parameter `use_auth_token` to `token` in `TransformersQueryClassifier`.
I added a unit test and tested it manually. …
> fix: Change `use_auth_token` to `token` in `TransformersQueryClassifier`

- haystack/nodes/retriever/web.py
- releasenotes/notes/web-retriever-allow-custom-link-content-fetcher-8728141d81d7a5e5.yaml
The purpose of this change is to enhance the flexibility and customization options available to users of the `WebRetriever` component. Previously, users were limited to the default `LinkContentFetcher` settings, which might not be suitable for all use-cases. For example, users might want to specify a custom user-agent setting for web content fetching. By allowing users to provide their custom `LinkContentFetcher`, we enable them to fine-tune its behavior according to their specific needs.
The change is focused on the `init` method of the `WebRetriever` component. The method has been modified to accept a custom `LinkContentFetcher` object as an optional parameter, allowing users to specify their customized fetcher.
Here is how users can specify their custom LinkContentFetcher. 
```python …
```
> feat: Allow WebRetrieve to use custom LinkContentFetcher

- .github/workflows/e2e.yml
- fixes n/a
- Automatically trigger the e2e workflow on PRs that involve the e2e folder.
n/a
n/a
> ci: auto trigger e2e workflow on PRs that affect it

- examples/talk_to_website.py
- examples/web_lfqa_with_rankers.py
- haystack/nodes/ranker/__init__.py
- haystack/nodes/ranker/diversity.py
The PR aims to standardize how new rankers: `RecentnessRanker`, `DiversityRanker`, and `LostInTheMiddleRanker` are imported in Haystack. Currently, these rankers are inconsistently imported compared to existing rankers. By modifying `haystack/nodes/ranker/__init__.py`, we make it possible for users to import these rankers in a manner consistent with existing ones.
Updated `haystack/nodes/ranker/__init__.py` to include the new rankers and also updated examples to reflect this change.
After this change, users can import the new rankers as shown below, which is consistent with how existing rankers are imported:
```python
from haystack.nodes.ranker import DiversityRanker, LostInTheMiddleRanker, RecentnessRanker
```
Manually tested the new import paths in the `haystack/examples` directory to …
> fix: Improve imports for new rankers

- haystack/preview/dataclasses/answer.py
- n/a
This PR renames the `question` field of the `Answer` dataclass to `query`. We use `query` much more often in the codebase and should be consistent with naming.
n/a …
> Rename `question` to `query` in `Answer` dataclass (2.0)

- haystack/nodes/prompt/invocation_layer/handlers.py
- releasenotes/notes/fix-model_max_length-prompt_handler-7f34c40c62a8c55b.yaml
- test/prompt/test_handlers.py
- fixes #5589 
This PR sets the `model_max_length` parameter of the tokenizer of `DefaultPromptHandler`. 
I added a unit test + added a test case in an integration test.
Without this change, users are getting a warning message from the transformers library that the sequence length is too long for the model they are using in case they are using models supporting larger sequence length than 1024. …
> fix: Set model_max_length in the Tokenizer of `DefaultPromptHandler`

- haystack/preview/components/builders/answers_builder.py
- haystack/preview/dataclasses/answer.py
- releasenotes/notes/add-answersbuilder-2.0-5dd255eeba68041f.yaml
- test/preview/components/builders/test_answers_builders.py
- fixes #5624
This PR adds the `AnswersBuilder` component that would typically used after a `Generator` component. It takes the string output of `Generator` models and creates `GeneratedAnswer` objects of them based on regular expressions.
`AnswersBuilder` corresponds to `AnswerParser` In Haystack 1.x. …
> feat: Add `AnswersBuilder` component (2.0)

- haystack/preview/components/generators/prompt_builder.py
- pyproject.toml
- releasenotes/notes/prompt-builder-d22954ef9c4a2a7b.yaml
- test/preview/components/generators/test_prompt_builder.py
- Closes #[5622](https://github.com/deepset-ai/haystack/issues/5622)
Add minimal `PromptBuilder` implementation to render string templates to prompt strings so they can be passed to Generator Components.
Usage:
```
from haystack.preview.components.generators.prompt_builder import PromptBuilder
template = "Translate the following context to {{ target_language }}. Context: {{ snippet }}; Translation:"
builder = PromptBuilder(template=template)
res = builder.run(target_language="spanish", snippet="I can't speak spanish.")
assert res["prompt"] == "Translate the following context to spanish. Context: I can't speak spanish.; Translation:"
```
Added unit tests.
I didn't add support for PromptHub as we still have no prompt templates using the new format. 
Also it can be easily added in the future …
> Add `PromptBuilder`

- .github/workflows/e2e.yml
- e2e/preview/components/test_whisper_local.py
- haystack/preview/__init__.py
- haystack/preview/components/audio/whisper_local.py
- pyproject.toml
n/a
- As we began adding e2e tests to the CI under the `e2e/preview` folder, we should enable those too.
- Fix a `LocalWhisperTranscriber` e2e test that was failing.
Local run of the tests …
> chore: enable e2e preview tests

- annotation_tool/README.md
- n/a
The hosted version of the annotation tool has been discontinued, this PR removes the link to it.
> docs: Remove mention of hosted annotation tool

- e2e/preview/components/test_whisper_local.py
- e2e/preview/components/test_whisper_remote.py
- fixes CI failure
- The test was skipped in the PR that enabled it and did not fail the CI. At the first execution it actually failed.
Local test run
n/a
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#i …
> chore: fix RemoteWhisperTranscriber e2e tests

- haystack/preview/components/builders/answer_builder.py
- test/preview/components/builders/test_answer_builder.py
- n/a
The `AnswerBuilder` was directly returning the answers instead of putting them in a dictionary. This PR fixes this by putting the answers as a value to the key `"answers"` of a dictionary and returning that dictionary in the `run` method.
- …
> fix: Fix output of AnswerBuilder

- haystack/nodes/retriever/web.py
Small improvement. Easier to know what to put in the `search_engine_providers` without having to look in the source code
> Updating WebRetriver API docs

- e2e/pipelines/test_standard_pipelines.py
- test/pipelines/test_standard_pipelines.py
The e2e test is a bit weak. [Sometimes it fails](https://github.com/deepset-ai/haystack/actions/runs/6120866794/job/16613539589?pr=5746).
I made it more robust.
I also modified an identical integration test, but probably it does not run.
Please let me know if I need to do anything about it... …
> test: make `WebQAPipeline` tests more robust

- pyproject.toml
> fix: temporary pin tiktoken

- e2e/preview/components/test_gpt35_generator.py
- fixes https://github.com/deepset-ai/haystack/actions/runs/6122946746/job/16619792413?pr=5744
- Remove remove `test_gpt35_generator_run_above_context_length` from the GPT35Generator end2end tests
n/a
n/a …
> chore: remove flaky end2end test for `GPT35Generator`

- pyproject.toml
By setting upper limits on code complexity we can use the code review process to require contributors who want to increase the limits to justify why increased complexity is required. These can also be metrics for continuous improvement.
```toml
[tool.pylint.'DESIGN']
max-args = 37  # Default is 5
max-attributes = 27  # Default is 7
max-branches = 33  # Default is 12
max-locals = 44  # Default is 15
max-statements = 205  # Default is 50
```
% `pipx run pylint haystack`
- I added unit tests and updated …
> ci: Use pylint to set limits on code complexity

- .github/dependabot.yml
As suggested in https://github.com/deepset-ai/haystack/pull/5787
Let dependabot update the version of github actions in use
> ci: let dependabot update github actions

- .github/workflows/license_compliance.yml
`license_compliance.yml` workflow always fail when running in PRs opened from forks. That happens cause we try to send check result event to Datadog but since `secrets` are not accessible from those PRs it always fails. 
That can cause confusion so this PR disables the step sending the event in PRs opened from forks. The workflow will still fail when the license check fails for a proper reason.
Example failure: https://github.com/deepset-ai/haystack/actions/runs/6168513914?pr=5783
The first commit of this PR is just a reformatting of the workflow file, feel free to ignore it.
> Fix license compliance workflow

- .github/workflows/openapi_sync.yml
- .github/workflows/readme_sync.yml
Reverts deepset-ai/haystack#5789
I optimistically merged the dependabot PR,
but now our [docs sync actions fails](https://github.com/deepset-ai/haystack/actions/runs/6170299645/job/16746320164).
We should better investigate why, but in the meantime, I'm reverting the PR...
> Revert "build(deps): bump readmeio/rdme from 8.3.1 to 8.6.6"

- .github/workflows/license_compliance.yml
Run the step that send the license check outcome to Datadog only if the api key is set.
I didn't. Setting a testing ground for this takes more time that testing directly in CI and it doesn't block development so I believe it's still worth.
Attempted fix with #5791 but it didn't work as the `github.repository` is set to `deepset-ai/haystack` even if PR comes from a fork.
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my …
> Fix license compliance check failing when running in PR from forks

- haystack/preview/components/retrievers/memory.py
- test/preview/components/retrievers/test_memory_retriever.py
- fixes https://github.com/deepset-ai/haystack/issues/5767
- Changes the input of `MemoryBM25Retriever` to accept a single query.
- Fixes all the tests
Local unit tests run
See https://github.com/deepset-ai/haystack/issues/5754 …
> feat: make `MemoryBM25Retriever` non batch

- haystack/document_stores/pinecone.py
- releasenotes/notes/refactor-pinecone-document-store.yaml
- test/document_stores/test_pinecone.py
**Related Issues**
Resolves: [Refactoring Pinecone document store #5721](https://github.com/deepset-ai/haystack/issues/5721)
**Proposed Changes**
Refactor Pinecone document store to use _doc_type_ metadata field instead of namespaces to make distinction between:
documents without embedding (_doc_type_ = no-vector)
documents with embedding (_doc_type_ = vector)
labels (_doc_type_ = label)
**How did you test it?**
Testing is done through existing unit and integration tests, as well as manually.
**Notes for the reviewer**
It is a **breaking change** and the migration for all users who are using Pinecone document store for their documents is necessary.
**Checklist**
-  [x] I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code …
> feat: Pinecone document store refactoring

- haystack/preview/components/embedders/sentence_transformers_text_embedder.py
- test/preview/components/embedders/test_sentence_transformers_text_embedder.py
- fixes #5806
(part of #5754)
- Change the input of `SentenceTransformersTextEmbedder` to accept a single text
- Fix the tests
Local tests run …
> feat: make `SentenceTransformersTextEmbedder` non batch

- haystack/preview/document_stores/errors.py
- haystack/preview/document_stores/memory/__init__.py
- haystack/preview/document_stores/memory/document_store.py
- haystack/preview/document_stores/memory/errors.py
- haystack/preview/errors.py
- haystack/preview/testing/document_store.py
- haystack/preview/utils/__init__.py
- haystack/preview/utils/filters.py
- related to #5680 
This PR moves the filtering utilities from `preview/document_stores/memory/_filters.py` to `preview/filters/utils.py` as they are not only useful for the `MemoryDocumentStore`, but also for other components like the `MetadataRouter`.
With this refactoring `FilterError` isn't part of `preview/document_stores/memory/errors.py` anymore, but moved to `preview/errors.py`.
Also, I decided to rename the `match` method of `filters.py` to `document_matches_filter` to make it more descriptive. Let me know if we should keep the old name.
- I have updated the related issue with …
> refactor: Move filter utilities (2.0)

- haystack/preview/components/retrievers/memory.py
- test/preview/components/retrievers/test_memory_retriever.py
- fixes #5807
(part of #5754)
- Change the input of `MemoryEmbeddingRetriever` to accept a single query embedding.
- Fix the tests
Local tests run
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installat …
> feat: make `MemoryEmbeddingRetriever` non-batch

- haystack/document_stores/pinecone.py
- fixes failing Docker build
Removes `from __future__ import annotation` from `pinecone.py`, breaking the JSON schema generation.
CI …
> fix: remove `__future__` import from `pinecone.py`

- .pre-commit-config.yaml
I have been encountering some issues with `ruff` pre-commit hook: it raises "line too long (E501)."
`line-length` is quite high
https://github.com/deepset-ai/haystack/blob/cab21da87be6560977d6d604ae3867aa64696202/pyproject.toml#L405
but it is not correctly working.
(I also tried with a clean Haystack installation)
Possible reason: [`line-length` is not consistent between `ruff` and `black`](https://beta.ruff.rs/docs/faq/#is-ruff-compatible-with-black)
Then, I also found that [**Ruff's pre-commit hook should be placed after other formatting tools, such as Black and isort**](https://beta.ruff.rs/docs/usage/#pre-commit).
Move `ruff` pre-commit hook after `black` hook
Local run.
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and …
> ci: pre-commit - move `ruff` after `black`

- haystack/preview/components/embedders/sentence_transformers_document_embedder.py
- haystack/preview/dataclasses/document.py
- haystack/preview/document_stores/memory/document_store.py
- releasenotes/notes/fix-document-constructor-18b9e5dd9522a918.yaml
- test/preview/dataclasses/test_document.py
- test/preview/testing/test_factory.py
Document constructor expected an `id` parameter, thought it was ignored and completely and generated given the `text` param.
This behaviour is extremely confusing so this PR removes the `id` parameter from `__init__`.
This is a breaking change.
Updated `preview` tests and ran all of them.
N/A …
> Fix Document constructor accepting unused id parameter

- haystack/preview/testing/document_store.py
This function has been bugging me because mypy, pylint, and two different sets of ruff rules did not like it.  To me it seemed like `doc` was an _undefined name_ in the contest of the `or`.  It finally strikes me that the `or` should be an `if`.
- …
> test: Fix the test_nin_filter_embedding() function

- .github/workflows/linting.yml
- fixes #5782
As discussed at https://github.com/deepset-ai/haystack/pull/5771#issuecomment-1714833290 the current pylint GitHub Action builds all haystack which is not required for lining with pylint.  This pull request eliminates unneeded steps so that pylint results are returned in seconds (14 sec. for 50+ Python files modified), instead of [7 to 11 minutes](https://github.com/deepset-ai/haystack/actions/workflows/linting.yml). 
Run `ruff --select=UP --fix .` to modify 50+ Python files and ensure pylint runs correctly. …
> ci: Speed up pylint GitHub Action

- .github/workflows/linting.yml
Reverts deepset-ai/haystack#5828
* Reverts https://github.com/deepset-ai/haystack/pull/5828 which worked OK in a pull request but generated pylint import errors when merged to main. @masci
> Revert "ci: Speed up pylint GitHub Action"

- haystack/nodes/prompt/invocation_layer/chatgpt.py
- haystack/nodes/prompt/invocation_layer/open_ai.py
- releasenotes/notes/support-gpt-3.5-turbo-instruct-79236835a8be143c.yaml
- test/prompt/invocation_layer/test_chatgpt.py
- test/prompt/invocation_layer/test_openai.py
Let's add support for the very recently released model gpt-3.5.-turbo-instruct (see [HN](https://news.ycombinator.com/item?id=37558911))
As this is an instruction model (not a chat model), it is implemented in OpenAI's legacy completion API endpoint.
Therefore, I am adding the support in the `OpenAIInvocationlayer` (and not `ChatGPTInvocationLayer`)
- Validated manually that OpenAI really uses the legacy completions endpoint for it
- Extended the unit tests for supported model names …
> feat: Add support for OpenAI's `gpt-3.5-turbo-instruct` model

- haystack/preview/components/embedders/sentence_transformers_document_embedder.py
- haystack/preview/dataclasses/document.py
- haystack/preview/document_stores/memory/document_store.py
- releasenotes/notes/pass-id-to-doc-init-c6b44d30978f2d9f.yaml
- test/preview/dataclasses/test_document.py
- test/preview/testing/test_factory.py
- revert #5826
The current logic forces you to remove the `id` key from the document dictionary when serialized.
The new logic passes the `id` param to the constructor, so documents can go through a full roundtrip without removing the key from the document dict.
The `id` param is optional, if not passed we create one with the same logic as before.
unit tests …
> feat: optionally pass an id to the Document constructor

- haystack/preview/testing/test_utils.py
- haystack/preview/utils/set_seeds.py
- test/preview/components/readers/test_extractive.py
- test/preview/conftest.py
The Integration tests of the Extractive Reader are randomly failing ([see an example](https://github.com/deepset-ai/haystack/actions/runs/6297461927/job/17095016616))
- Add an absolute tolerance of 1e-4 to prevent groundless failures.
- (unrelated: force the reader to use the CPU in `test_matches_hf_pipeline`. Otherwise, in local environments where GPU is available, this test fails with `RuntimeError: Expected all tensors to be on the same device...`)
CI, local tests
- I've …
> chore: make preview integration tests reproducible

- e2e/pipelines/test_standard_pipelines.py
- e2e/samples/pipelines/async_test_pipeline.yml
- haystack/nodes/asyncio/sleeper.py
- haystack/nodes/base.py
- haystack/pipelines/base.py
- releasenotes/notes/async-pipeline-20649b54ecff2706.yaml
Add `Pipeline._arun()`, this enables the execution of asynchronous nodes in `Pipeline`.
This makes it possible to run a `Pipeline` while another is waiting for a node to return its output.
Example usage:
```
queries = [...]
futures = []
for query in queries:
future = pipeline._arun(query=query)
futures.append(future)
await asyncio.gather(*futures)
```
I added end to end tests to verify asynchronous running of `Pipelines`.
This PR also adds a `Sleeper` component that has an async run to ease testing.
- I added unit tests …
> Add Pipelines async run

- pyproject.toml
- trying to temporarily fix #5889 
Pin `setuptools_scm<8.0` in the `metrics` extra to avoid errors in Windows tests while installing `seqeval`
It is an attempt and I could not test it …
> chore: pin `setuptools_scm` in the `metrics` extra

- pyproject.toml
- https://github.com/deepset-ai/haystack/issues/5889
Pin `setuptools_scm` **only for Windows**, as suggested in https://github.com/deepset-ai/haystack/pull/5891#discussion_r1337392947 …
> chore: pin `setuptools_scm` in the `metrics` extra only for Windows

- .github/workflows/e2e.yml
- fixes https://github.com/deepset-ai/haystack/actions/runs/6319649460/job/17160939287
- Add `preview` extra to e2e tests
n/a …
> fix: Add `preview` extra to e2e tests

- test/preview/components/file_converters/test_azure_ocr_doc_converter.py
- Azure tests failing in a PR from an external contributor (#5736)
- More robust `skipif` conditions in Azure integration tests
Local run
I am not sure if this solves the failures in #5736, but in any case, it seems like an improvement.
- I ran …
> test: make Azure integration tests more robust

- haystack/preview/components/builders/answer_builder.py
- test/preview/components/builders/test_answer_builder.py
- fixes n/a
- For small demos I found that passing the metadata makes the pipeline definition a bit more noisy than necessary.
- Metadata is not an optional field
- Tests have been added
- Local unit tests run …
> feat: Make `metadata` optional in AnswerBuilder

- haystack/preview/components/file_converters/__init__.py
- haystack/preview/components/file_converters/html.py
- releasenotes/notes/add-html-to-document-21fe38b244388f4d.yaml
- test/preview/components/file_converters/test_html_to_document.py
- test/preview/test_files/html/what_is_haystack.html
Haystack 2.0 requires a default component to convert HTML content into a Document with raw text. This is essential for processing web content within the Haystack framework.
- fixes https://github.com/deepset-ai/haystack/issues/5905
A new component, `HTMLToDocument`, has been introduced and added to the `file_converters` package. This component is specifically designed to convert HTML files into `Document` objects, which can then be utilized within Haystack pipelines.
Here's a code snippet demonstrating the usage of the new `HTMLToDocument` component:
```python
from haystack.preview.components.file_converters import HTMLToDocument
paths = ["what_is_haystack.html"]
converter = HTMLToDocument()
output = converter.run(paths=paths)
docs = output["documents"]
assert len(docs) == 1
assert …
```
> feat: Add HTMLToDocument component (v2)

- haystack/nodes/prompt/prompt_model.py
- haystack/nodes/prompt/prompt_node.py
- releasenotes/notes/add-promptnode-arun-bc4c2bcc9c653015.yaml
- test/prompt/test_prompt_model.py
- test/prompt/test_prompt_node.py
- fixes n/a
Add an `arun` async method to the `PromptNode` so it can be executed within a `pipeline._arun`.
Unit tests.
This PR propagates the async functionality all the way down to the invocation layers, but none of them supports asyncio yet. That will come with a subsequent PR. …
> feat: add async PromptNode run

- haystack/preview/components/classifiers/__init__.py
- n/a
This PR removes the `classifiers` folder from the `preview` package. The `FileExtensionClassifier` has been renamed to `FileExtensionRouter` and moved to the `routers` folder in #5824. …
> chore: Remove classifiers directory from preview package

- haystack/utils/getting_started.py
We want the getting started code to run with haystacks minimal installation `pip install farm-haystack`
using langdetec needs additional dependencies. It is not needed in the getting started, so we remove the check with this PR.
> fix: Remove language validation from getting started

- haystack/preview/components/writers/document_writer.py
- releasenotes/notes/add-document-writer-number-of-documents-written-2c57f3a5d6ae2131.yaml
- fixes #5780 
Document writer now returns number of documents written.
Automated CI tests
> feat: `DocumentWriter` returns number of documents written

- haystack/nodes/prompt/invocation_layer/open_ai.py
- haystack/nodes/prompt/prompt_model.py
- haystack/utils/openai_utils.py
- pyproject.toml
- releasenotes/notes/add-openai-async-1f65701142f77181.yaml
- test/prompt/invocation_layer/test_chatgpt.py
- test/prompt/test_prompt_node.py
- add a secondary, async api `ainvoke` to the OpenAI invocation layer.
Code was manually tested with the following snippet:
```py
import asyncio
import os
from haystack.pipelines import Pipeline
from haystack.nodes import PromptNode, PromptTemplate, AnswerParser
from haystack.schema import Document
lfqa_prompt = PromptTemplate(
prompt="""Synthesize a comprehensive answer from the following topk most relevant paragraphs and the given question.
Provide a clear and concise response that summarizes the key points and information presented in the paragraphs.
Your answer should be in your own words and be no longer than 50 words.
\n\n Paragraphs: {join(documents)} \n\n Question: {query} \n\n Answer:""",
output_parser=AnswerParser(),
)
doc_1 = "Contrails are a manmade type …
```
> feat: add support for async openai calls

- haystack/nodes/answer_generator/openai.py
- releasenotes/notes/deprecate-openai-answergenerator-537266612ba1ffff.yaml
- test/nodes/test_generator.py
- fixes #5349
Deprecate this component in favor of `PromptNode`.
As discussed internally, if we release this deprecation with Haystack 1.21.1,
we can remove this component in 1.23.
CI. Added deprecation test. …
> chore: deprecate `OpenAIAnswerGenerator`

- .github/workflows/tests_preview.yml
- During the CI split for v2 I accidentally left over a matrix for the Linux CI. This PR removes it.
CI
n/a
> chore: remove matrix from Linux CI

- .pre-commit-config.yaml
- pyproject.toml
- fixes #5931
Added isort to `pyproject.toml` and `.pre-commit-config.yaml`
manual verification
- Have not committed changes using isort because that will change a lot of code and make seeing the important changes difficult.
- I have not yet modified any github pipeline files since it would probably make sense to talk with a maintainer about that. …
> ci: added isort

- README.md
- N/A
- The 💙 emoji in the anchor does not actually resolve. Should be `#contributing`.
- Fix broken contributor link. As this ultimately links to the actual contributing page, simply redirect to *CONTRIBUTING.md* instead of `#-contributing`
- Manually viewed preview
- Single line documentation edit
> fix: fix contributing link in readme

- haystack/utils/deepsetcloud.py
- releasenotes/notes/update-deepset-cloud-sdk-save-pipeline-config-ff820838846f5f38.yaml
- test/samples/dc/pipeline_config.json
- test/utils/test_deepset_cloud.py
- part of https://github.com/deepset-ai/haystack-hub-ui/issues/2375
- We are adapting the dC endpoint for saving pipelines to accept JSON payloads instead of YAML. This has the advantage that we can have pipeline name and pipeline config. This rids us of the schema difference regarding the "name" between Haystack and deepset Cloud.
> chore: adapt deepset cloud sdk endpoint format for saving pipelines

- .pre-commit-config.yaml
- pyproject.toml
This PR reverts commit 64243540fb1f2cb6d4dfbb5b12db3aaf59a21b4a There is no easy way to make isort and black constantly overwrite each other. I tried this solution https://pycqa.github.io/isort/docs/configuration/black_compatibility.html but it didn't work. Let's find another one and in the meantime continue development unabated.
> Revert "ci: added isort to pyproject.toml and pre-commit (#5933)"

- haystack/preview/dataclasses/document.py
- test/preview/dataclasses/test_document.py
As a part of the ongoing improvements for https://github.com/deepset-ai/haystack/issues/5945 let's unfreeze Document as it is blocking for https://github.com/deepset-ai/haystack/pull/5923
> feat: Unfreeze Document in Haystack 2.0

- haystack/nodes/prompt/invocation_layer/chatgpt.py
- releasenotes/notes/fix-chatgpt-invocation-layer-bc25d0ea5f77f05c.yaml
- test/prompt/invocation_layer/test_chatgpt.py
- test/prompt/test_prompt_node.py
- failing examples tests: https://github.com/deepset-ai/haystack/actions/runs/6415666359/job/17417960613
- https://github.com/deepset-ai/haystack/pull/5946/files#r1347216493
`ChatGPTInvocationLayer` inherits from `OpenAIInvocationLayer` and has its own custom method `_execute_openai_request` that also creates requests with `messages` field (required in models such as `gpt-3.5-turbo`).
After #5946, this method was no longer called and requests with the wrong format were created.
- include the logic of the old method  `_execute_openai_request` in synchronous and asynchronous invocation methods.
CI. Manual tests. …
> fix: fix ChatGPT invocation layer (and add async support)

- annotation_tool/docker-compose.yml
The docker-compose.yml file for annotation tool
('annotation_tool/domain-compose.yml') is giving an error with latest image.
The annotation-tool demands the `DOMAIN_WHITELIST` envvar to be defined that is not a part of the given template referenced by the documentation.
- fixes #issue-number: No issue recorded
The docker-compose.yml file for annotation tool
('annotation_tool/domain-compose.yml') is giving an error with latest image.
The annotation-tool demands the `DOMAIN_WHITELIST` envvar to be defined that is not a part of the given template referenced by the documentation.
Yes.
- I …
> fix: annotation-tool is missing `DOMAIN_WHITELIST` envvar

- proposals/text/5794-evaluation-haystack-2.md
- proposals/text/5794-evaluation-haystack-2.py
- pyproject.toml
I had to add `rouge` in the ignored words for codespell as the `ROUGE` metric name at line 22 of `5794-evaluation-haystack-2.md` was causing it to fail.
> chore: Rename proposal to respect specifications

- haystack/preview/components/samplers/__init__.py
- haystack/preview/components/samplers/top_p.py
- releasenotes/notes/add-top-p-sampler-ad6e0f5d623a6bb5.yaml
- test/preview/components/samplers/test_top_p.py
In the realm of document sampling, we often need a mechanism that doesn't just pick the top-scoring documents but considers a range of high-scoring documents. Enter `TopPSampler`. This component leverages the concept of top p (nucleus) sampling, which selects documents based on the cumulative probability of their scores. It's a more dynamic approach compared to just picking the top N documents and can lead to more diverse and potentially insightful selections.
We're introducing the `TopPSampler` to our samplers package. This new sampler will allow users to harness the power of top p sampling in their document selection process.
Here's a quick example to get a feel for it:
```python
from haystack.preview import Document
from haystack.preview.components.sampler import TopPSampler
sampler = …
```
> feat: Add TopPSampler Haystack 2.0 component

- e2e/preview/pipelines/test_extractive_qa_pipeline.py
- e2e/preview/pipelines/test_rag_pipelines.py
- haystack/preview/components/generators/openai/gpt.py
- related to https://github.com/deepset-ai/canals/issues/108
-  Enhance e2e tests to also draw and serialize/deserialize all the test pipelines under `e2e/preview/pipelines`.
- CI
Bugs that are discovered should be fixed in parallel PRs before merging this one
- I …
> test: enhance e2e tests to also draw and serialize/deserialize the test pipelines

- README.md
- fixes #5925 
- Added a quick get started code to Haystack readme.md
> docs: readme-get-started

- .github/workflows/linting.yml
- .github/workflows/linting_preview.yml
We need to configure linting for preview in a separate file because we'll have different haystack install directives as we split from the old repo
> feat: Split linting preview into a separate file

- haystack/preview/testing/document_store.py
`contains_same_docs` always returned `True` if the two input lists of documents had the same length. This happened because the implementation uses the return value of `sort` instead of `sorted`.
Four tests using the utility were actually broken due to issues in the implementation of the tests.
* Use `sorted` instead of `sort`, which returns the sorted list so that it can be compared to the other sorted list of documents.
* Fix four broken tests that used the utility. Three of them contained just small mistakes. One had a problem comparing int `-2` and float `-2.0` for equality.
Manual tests for the `contains_same_docs`. It's a small utility function of `DocumentStoreBaseTests` and I didn't want to add tests for it.
Updated unit tests. …
> test: Utility to compare two lists of documents for equality

- haystack/preview/components/rankers/similarity.py
- test/preview/components/rankers/test_similarity.py
- To enhance the `SimilarityRanker` functionality by introducing a `top_k` parameter.
- Added `top_k` parameter to `SimilarityRanker` allowing users to specify the number of top similar documents to be retrieved.
- Instantiate `SimilarityRanker` with the `top_k` parameter to define the number of top similar documents you want to retrieve.
- Added unit tests in `test/preview/components/rankers/test_similarity.py` to ensure correct functionality.
- We simply forgot to add top_k if you can believe
> feat: Add top_k to SimilarityRanker

- .github/workflows/tests.yml
- haystack/pipelines/base.py
- pyproject.toml
- releasenotes/notes/review-all-extras-42d5a3a3d61f5393.yaml
- test/pipelines/test_ray.py
- fixes failing CI
Removes the `audio`, `ray`, `onnx` and `beir` extras from the extra group `all` due to dependency conflicts between `openai-whisper` and other components that require `torch`.
CI
I marked this change as breaking, even though hopefully the impact should be minimal.
I checked mainly CI workflows and Docker images. Please help me make sure we're not forgetting some other usage of the `all` extra. …
> chore: review `all` extra

- haystack/preview/components/preprocessors/__init__.py
- haystack/preview/components/preprocessors/text_language_classifier.py
- releasenotes/notes/text-language-classifier-0d1e1a97f1bb8ac6.yaml
- test/preview/components/preprocessors/test_text_language_classifier.py
- First part of https://github.com/deepset-ai/haystack/issues/5677
Add TextLanguageClassifier component that takes list of string as input and routes to different output connections based on detected language. LangDetect is used for language detection.
Newly added unit tests and manually with the following code snippet:
```python
def test_pipe(self):
document_store = MemoryDocumentStore()
document_store.write_documents(documents=[Document(text="Emma lives in Berlin.")])
p = Pipeline()
p.add_component(instance=TextLanguageClassifier(), name="text_language_classifier")
p.add_component(instance=MemoryBM25Retriever(document_store=document_store), name="retriever")
p.connect("text_language_classifier.en", "retriever.query")
result = p.run({"text_language_classifier": {"text": "Who lives in …
```
> feat: Add TextLanguageClassifier 2.0

- .github/workflows/preview_imports.yml
I've noticed more and more occasions in `haystack.preview` imports to non preview `haystack`, that's an issue as we want to keep `haystack.preview` completely isolated and separated from old `haystack`.
This PR adds a workflow to verify that we don't actually add files in `haystack.preview` containing old `haystack` imports.
The workflow won't be required but at least will give a warning when creating PRs with bad imports.
I tested in an personal repo:
* [PR](https://github.com/silvanocerza/nodenode/pull/35)
* [Failing workflow](https://github.com/silvanocerza/nodenode/actions/runs/6524708624)
N/A
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_co …
> ci: Add a workflow to verify haystack.preview doesn't import non preview modules

- pyproject.toml
- twin PR of https://github.com/deepset-ai/haystack-preview-package/pull/9
We want to keep the effective dependencies of the preview package up to date.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#ins …
> chore: add posthog to the dependencies of preview extra

- haystack/preview/__init__.py
- haystack/preview/components/fetchers/link_content.py
- haystack/preview/telemetry/_environment.py
- haystack/preview/version.py
Fix `link_content.py` and `_environment.py` importing `__version__` from `haystack` instead of `haystack.preview` module.
Manually.
I'll add a CI check to prevent this imports as I already caught some other occurences in past reviews.
- I ran …
> chore: Fix preview module importing from old haystack

- pyproject.toml
`pyyaml` is a missing dependency of the preview package. I already added it in [deepset-ai/haystack-preview-package](https://github.com/deepset-ai/haystack-preview-package).
> chore: Add missing preview dependency

- .github/workflows/linting.yml
- .github/workflows/linting_preview.yml
- .github/workflows/linting_skipper.yml
I discovered that when we modify preview e2e tests,
the workflow `linting` is running instead of `linting_preview`.
- `linting` will not run on preview e2e tests
- instead, `linting_preview` will run on them
I haven't tested it.
- I ran …
> CI: make only `linting_preview` run on preview e2e tests

- haystack/preview/components/preprocessors/text_document_cleaner.py
- haystack/preview/components/preprocessors/text_document_splitter.py
- releasenotes/notes/fix-splitter-cleaner-hash-key-3b6f042af7da9ab4.yaml
- test/preview/components/preprocessors/test_text_document_cleaner.py
- test/preview/components/preprocessors/test_text_document_splitter.py
- fixes #6079 
- deepcopy `id_hash_keys` to newly created Documents after cleaning the text with DocumentCleaner or splitting the text with DocumentSplitter
With this PR, two documents with the same text but different metadata and `id_hash_keys` listing the corresponding metadata key will have different document ids. Before the PR they would have they same document id.
added new unit tests …
> fix: DocumentSplitter and DocumentCleaner copy `id_hash_keys` to newly created Documents

- haystack/preview/components/preprocessors/text_document_splitter.py
- releasenotes/notes/fix-text-splitter-65870db474338749.yaml
- test/preview/components/preprocessors/test_text_document_splitter.py
`TextDocumentSplitter` right now fails if run with an empty list, the error message is also quite confusing.
This PR changes the behaviour so it doesn't fail when an empty list is use as input.
I ran `TextDocumentSplitter` tests.
N/A
- I ran …
> fix: Fix TextDocumentSplitter failing if run with empty list

- e2e/preview/pipelines/test_extractive_qa_pipeline.py
- e2e/preview/pipelines/test_rag_pipelines.py
- haystack/preview/components/preprocessors/text_document_cleaner.py
- haystack/preview/components/preprocessors/text_language_classifier.py
- haystack/preview/components/retrievers/__init__.py
- haystack/preview/components/retrievers/in_memory_bm25_retriever.py
- haystack/preview/components/retrievers/in_memory_embedding_retriever.py
- haystack/preview/document_stores/__init__.py
- haystack/preview/document_stores/in_memory/__init__.py
- haystack/preview/document_stores/in_memory/document_store.py
- haystack/preview/document_stores/memory/__init__.py
- releasenotes/notes/rename-memory-doc-store-2a9960d11d2aa492.yaml
- test/preview/components/caching/test_url_cache_checker.py
- test/preview/components/retrievers/test_in_memory_bm25_retriever.py
- test/preview/components/retrievers/test_in_memory_embedding_retriever.py
- test/preview/document_stores/test_in_memory.py
Some early users of Haystack 2.x noticed that `MemoryDocumentStore` sounds confusing and might incorrectly allude to the memory concept in Language Agents.
After an internal discussion, we decided to rename it to `InMemoryDocumentStore`.
- Rename `MemoryDocumentStore` to `InMemoryDocumentStore`
- Rename `MemoryBM25Retriever` to `InMemoryBM25Retriever`
- Rename `MemoryEmbeddingRetriever` to `InMemoryEmbeddingRetriever`
CI …
> refactor!: rename `MemoryDocumentStore` and related Retrievers

- pyproject.toml
Twin PR in the preview package: https://github.com/deepset-ai/haystack-preview-package/pull/10
`more-itertools` is a lightweight dependency needed by `TextDocumentSplitter`.
In most environments (e.g. Colab), it is already installed by other libraries, so it is difficult to notice its absence.
Add `more-itertools` to `preview` extra. …
> Add `more-itertools` to preview dependencies

- haystack/preview/components/embedders/openai_document_embedder.py
- haystack/preview/dataclasses/document.py
- releasenotes/notes/refactor-openai-document-embedder.yaml
- fixes a part of #6107 
Proposed Changes:
Enrich documents with embeddings instead of recreating documents for  OpenAIDocumentEmbedder.
Requesting Review:
@anakin87
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRI …
> Enrich documents with embeddings for OpenAIDocumentEmbedder

- haystack/preview/dataclasses/document.py
- releasenotes/notes/doc-id-rework-85e82b5359282f7e.yaml
- test/preview/components/retrievers/test_in_memory_embedding_retriever.py
- test/preview/dataclasses/test_document.py
- test/preview/document_stores/test_in_memory.py
Change how `Document.id` is generated when not explicitly set.
Now it uses all `Document` fields.
`Document.id_hash_keys` is not used anymore but it will removed in a later PR as there are several Components that sest it.
Ran unit tests.
This is the first of a series of PRs to rework `Document`. …
> refactor: Rework `Document.id` generation

- haystack/preview/components/preprocessors/text_document_cleaner.py
- haystack/preview/components/preprocessors/text_document_splitter.py
- test/preview/components/preprocessors/test_text_document_cleaner.py
- test/preview/components/preprocessors/test_text_document_splitter.py
This PR changes `TextDocumentSplitter` so it doesn't build `Document` with `id_hash_keys` anymore.
Ran unit tests locally.
Depends on #6123.
Release notes will be updated at a later time in a separate following PR. …
> refactor: Remove `id_hash_keys` from `TextDocumentSplitter`

- haystack/preview/dataclasses/document.py
- haystack/preview/testing/document_store.py
- releasenotes/notes/document-embedding-type-d66c44ac6878fbdd.yaml
- test/preview/components/retrievers/test_in_memory_embedding_retriever.py
- test/preview/dataclasses/test_document.py
- test/preview/document_stores/test_in_memory.py
- fixes #6132
This PR changes the `Document.embedding` from `numpy.ndarray` to `List[float]` to ease usage of embeddings.
It also changes all usages and tests that were setting embedding as an `ndarray`. Some tests were already using it as a `List[float]` so they weren't changed.
Ran unit tests locally.
Depends on #6127. …
> refactor: Change `Document.embedding` type to list of floats

- haystack/preview/components/file_converters/azure.py
- haystack/preview/components/websearch/serper_dev.py
- releasenotes/notes/remove-api-key-from-serialization-2474a1539b86e233.yaml
- test/preview/components/file_converters/test_azure_ocr_doc_converter.py
- test/preview/components/websearch/test_serperdev.py
- fixes #6116 
Remove `api_key` from serialization of `AzureOCRDocumentConverter` and `SerperDevWebSearch`
Unit Tests have been updated to test the serialization without `api_key`.
I have opened a PR (https://github.com/deepset-ai/haystack/pull/6149) for migrating `RemoteWhisperTranscriber` to the OpenAI SDK. The `RemoteWhisperTranscriber` implementation in that PR does not serialize the `api_key` and is fixed as part of that PR. …
> refactor: Remove api_key from serialization of `AzureOCRDocumentConverter` and `SerperDevWebSearch`

- haystack/preview/dataclasses/__init__.py
- haystack/preview/dataclasses/chat_message.py
- releasenotes/notes/add-chat-message-c456e4603529ae85.yaml
- test/preview/dataclasses/test_chat_message.py
- To introduce the `ChatMessage` and `ChatRole` data classes to better handle chat-related LLM interactions
- Added `ChatMessage` and `ChatRole` data classes in `haystack/preview/dataclasses`.
- Updated `__all__` in `__init__.py` to include the new data classes.
- Utilize `ChatMessage` and `ChatRole` for structured handling and representation of LLM chat interactions within Haystack framework (that part will come soon).
- Basic unit tests added in `test/preview/dataclasses/test_chat_message.py`. However,  ChatMessage and ChatRole were tested manually in a larger change context (including serialization) 
- Review the implementation of `ChatMessage` and `ChatRole` to ensure it meets our standards
> feat: Add ChatMessage class to Haystack 2.0

- haystack/preview/dataclasses/byte_stream.py
- releasenotes/notes/byte-stream-mime-type-b060e96791c4993a.yaml
- test/preview/dataclasses/test_byte_stream.py
Add `mime_type` field to `ByteStream` dataclass.
Ran unit tests locally.
We're going to remove `mime_type` in `Document` and change `blob` to `ByteStream` after this. …
> feature: Add `mime_type` field to `ByteStream`

- haystack/preview/__init__.py
- haystack/preview/marshal/__init__.py
- haystack/preview/marshal/protocol.py
- haystack/preview/marshal/yaml.py
- haystack/preview/pipeline.py
- releasenotes/notes/add-yaml-marshaller-030e889f46484573.yaml
- test/preview/test_files/yaml/test_pipeline.yaml
- test/preview/test_pipeline.py
- fixes https://github.com/deepset-ai/haystack/issues/6010
We add the following methods to the `Pipeline` class:
- `dumps` to return its string representation
- `dump` to write its string representation to a file-like object passed to the method
- `loads` to return a `Pipeline` instance from its string representation
- `load` to return a `Pipeline` instance reading its string representation from a file-like object
All the methods can be invoked passing a `Marshaller` object that will determine what's the string representation format, defaulting to Yaml (the only format available at the moment).
Unit tests covering the default marshaller. …
> feat: add pipeline Yaml marshaller

- haystack/preview/components/builders/prompt_builder.py
- releasenotes/notes/add-dynamic-per-message-templating-908468226c5e3d45.yaml
- test/preview/components/builders/test_prompt_builder.py
After recently adding ChatMessage(s), it follows that we should introduce dynamic per ChatMessage templating in the `PromptBuilder` as well. This feature facilitates more interactive and dynamic templating by allowing different templates for each user message, adapting the prompt based on the user's input.
- fixes partially https://github.com/deepset-ai/haystack/issues/6035
The implementation involves updates to the `PromptBuilder` where we now have the option to initialize it with `template_variables` instead of just single static `template` to be used for all invocations. When initialized with `template_variables`, the `PromptBuilder` enables dynamic templating based on user ChatMessage(s). 
Here are the significant changes:
1. Introduced a new initialization parameter …
> feat: Add dynamic per-user ChatMessage templating support

- haystack/preview/components/readers/extractive.py
- releasenotes/notes/rename-reader-input-af739955bf4f71b5.yaml
ExtractiveReader's input was called `document` but is of type List[Document], which is a mismatch.
- Renamed `document` to `documents` to match its type List[Document]
- Added usage example
- Added docstrings to run method …
> chore: Rename ExtractiveReader's input from `document` to `documents` to match its type List[Document]

- .github/labeler.yml
- fixes missing labels on PRs touching the `preview` package
Add `preview/**/*` and `test/preview/**/*` to the labeller
not tested …
> Update labeler for `2.x`

- haystack/preview/components/audio/whisper_remote.py
- releasenotes/notes/migrate-remote-whisper-transcriber-to-openai-sdk-980ae6f54ddfd7df.yaml
- test/preview/components/audio/test_whisper_remote.py
- fixes #5731 
- fixes a part of #6116 
Migrate `RemoteWhisperTranscriber` to use the OpenAI SDK.
Added Unit and Integration Tests.
- The Whisper Transcription endpoint supports an optional [`response_format`](https://platform.openai.com/docs/api-reference/audio/createTranscription#audio/createTranscription-response_format) parameter. 
- This parameter controls the format of the transcribed output, and supports the following options: json, text, srt, verbose_json, or vtt. By default the API returns a "json" object with the transcribed text under the "text" key.
- The implementation in this PR only supports the "json" option for the `response_format` parameter. We can add support for the other options in a future PR if required. …
> refactor: Migrate `RemoteWhisperTranscriber` to OpenAI SDK.

- .github/utils/pydoc-markdown.sh
- .github/workflows/readme_sync.yml
- docs/pydoc/config-preview/audio.yml
- docs/pydoc/renderers.py
- fixes #5883 
- Add step in the readme sync action to publish 2.0 docs
- Add rendering of markdown files for preview with a custom renderer
- Add example config yml for audio docs
- GitHub action: https://github.com/deepset-ai/haystack/actions/runs/6656706170/job/18089859339 for the commit [skip sync docs for current release for testing](https://github.com/deepset-ai/haystack/pull/6173/commits/20e7fd27e23972a7d6c5a161782591f6c8cf6e77) ran through and successfully uploaded https://docs.haystack.deepset.ai/v2.0/reference/local-whisper-transcriber-api
- Locally tested `./.github/utils/pydoc-markdown.sh`
The last commit prepares the branch to be merged into main. Check the previous commit to see the action triggered. …
> docs: Add readme sync for API docs 2.0

- haystack/nodes/audio/whisper_transcriber.py
- fixes #5717
Improving docstring of `transcribe` and `run` function by adding return type
manual verification
Changes are made in `whisper_transcriber.py`
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md# …
> docs: add return types in docstring for transcribe and run function

- haystack/preview/components/builders/__init__.py
- haystack/preview/components/caching/__init__.py
- haystack/preview/components/fetchers/__init__.py
- haystack/preview/components/readers/__init__.py
- haystack/preview/components/websearch/__init__.py
Some of these files are missing and some others don't follow the common format
Fixed this
CI
> chore: make __init__.py files uniform in preview

- haystack/nodes/retriever/web.py
- releasenotes/notes/add-search_engine_kwargs-to-web-retriever-67fac44ef0039b7f.yaml
I was trying to use WebRetriever with GoogleAPI as the search engine provider, and then it prompted me to provide an engine id for the Google Custom Search to work. Based on #4796, I understood that it has to be provided in a dictionary in the argument `search_engine_kwargs` in the initialization of the WebSearch node class. Based on the current code of WebRetriever does not allow `search_engine_kwargs` to be passed, so I have made the relevant changes and created the PR.
> fix: Add search_engine_kwargs param to WebRetriever to pass to WebSearch

- haystack/nodes/prompt/invocation_layer/anthropic_claude.py
Added a direct link to Anthropic kwagrs https://docs.anthropic.com/claude/reference/complete_post instead of general docs link. …
> docs: update anthropic doc link

- haystack/preview/dataclasses/document.py
- haystack/preview/document_stores/in_memory/document_store.py
- haystack/preview/utils/filters.py
- releasenotes/notes/document-backward-compatible-07c4151e98ef8511.yaml
- test/preview/dataclasses/test_document.py
This PR changes `Document` serialisation to ease storaging in most DBs.
The most notable change is that the `Document.flatten()` method has been removed.
`Document.to_dict()` now has a `flatten` parameter, that defaults to `True` for backward compatibility.
It will flatten metadata keys at the same level of other `Document` fields when converting to `dict`.
`to_json` and `from_json` have been removed, as `to_dict` and `from_dict` already handle serialisation
of `dataframe` and `blob` fields.
Now `metadata` must only contain primitives that can be serialised to JSON with no custom encoders.
If any Document Store needs custom serialisation they can implement their own logic.
`Document` has also been made backward compatible so that it can be created using dictionaries
structured as the …
> Refactor: Document serialization and backward compatibility

- haystack/preview/components/audio/whisper_local.py
- haystack/preview/components/audio/whisper_remote.py
- haystack/preview/components/embedders/openai_document_embedder.py
- haystack/preview/components/embedders/sentence_transformers_document_embedder.py
- haystack/preview/components/file_converters/txt.py
- haystack/preview/components/preprocessors/text_document_cleaner.py
- haystack/preview/components/preprocessors/text_document_splitter.py
- haystack/preview/components/samplers/top_p.py
- haystack/preview/components/websearch/serper_dev.py
- haystack/preview/dataclasses/document.py
- haystack/preview/testing/document_store.py
- proposals/text/5794-evaluation-haystack-2.py
- releasenotes/notes/document-metadata-to-meta-8564aa3c045bb526.yaml
- test/preview/components/audio/test_whisper_local.py
- test/preview/components/audio/test_whisper_remote.py
- test/preview/components/builders/test_answer_builder.py
- test/preview/components/caching/test_url_cache_checker.py
- test/preview/components/embedders/test_openai_document_embedder.py
- test/preview/components/embedders/test_sentence_transformers_document_embedder.py
- test/preview/components/file_converters/test_textfile_to_document.py
- test/preview/components/preprocessors/test_text_document_cleaner.py
- test/preview/components/preprocessors/test_text_document_splitter.py
- test/preview/components/routers/test_metadata_router.py
- test/preview/components/samplers/test_top_p.py
- test/preview/dataclasses/test_document.py
- test/preview/document_stores/test_in_memory.py
- test/preview/utils/test_filters.py
This PR renames all occurences of `Document`'s `metadata` field to `meta` to enhance backward compatbility.
Ran unit tests locally.
This depends on #6181.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#i …
> refactor: Rename `Document`'s `metadata` field to `meta`

- haystack/preview/components/generators/hf_utils.py
- haystack/preview/components/generators/utils.py
- test/preview/components/generators/test_hf_utils.py
- test/preview/components/generators/test_utils.py
The general utility methods are aimed at serializing and deserializing callback handlers which are crucial for managing streaming responses. 
HuggingFace specific utility methods provide robust checking mechanisms for generation parameters and model validation against the HuggingFace Hub. These utility methods enhance code robustness, readability, and maintainability.
This PR introduces two sets of utility methods:
`serialize_callback_handler`: Serializes the streaming callback handler function to a string representing its full path.
`deserialize_callback_handler`: Deserializes the string representing the full path of the streaming callback handler function to the actual function object. Raises a DeserializationError if the function cannot be found.
`check_generation_params`: Validates …
> feat: Add general and HF util methods

- haystack/nodes/__init__.py
- releasenotes/notes/add-new-rankers-schema-generation-7ad92fd5c5de8937.yaml
The `LostInTheMiddleRanker`, `DiversityRanker`, and `RecentnessRanker` are not currently included in the `__init__.py` file of the haystack nodes directory (`haystack/nodes/__init__.py`), resulting in their omission from the generated JSON schema for Haystack pipelines. 
- fixes https://github.com/deepset-ai/haystack/issues/6213
- Added `LostInTheMiddleRanker`, `DiversityRanker`, and `RecentnessRanker` to `__init__.py` in the haystack nodes directory to ensure they are included in the JSON schema generation.
With these additions, users can now validate their pipeline configurations against the updated JSON schema which now includes definitions for `LostInTheMiddleRanker`, `DiversityRanker`, and `RecentnessRanker`.
- Generated the JSON schema post-modification to verify the inclusion of …
> fix: Add new rankers to nodes __init__.py

- haystack/preview/components/generators/hugging_face/hugging_face_local.py
- releasenotes/notes/hflocalgenerator-generation-kwargs-in-run-2bde10d398a3712a.yaml
- test/preview/components/generators/hugging_face/test_hugging_face_local_generator.py
Currently, changing the `generation_kwargs` of a text generation model in the `HuggingFaceLocalGenerator` requires reloading the model, which is slow and inconvenient for such a common scenario.
- allow passing `generation_kwargs` in `run` method
CI, new unit test
- I …
> feat: `HuggingFaceLocalGenerator`- allow passing `generation_kwargs` in `run` method

- haystack/preview/components/generators/__init__.py
- haystack/preview/components/generators/hf_utils.py
- haystack/preview/components/generators/hugging_face_tgi.py
- releasenotes/notes/add-huggingface-tgi-generator-9d7eed86f5246ea9.yaml
- test/preview/components/generators/test_hugging_face_tgi.py
To enable inferencing for non-chat Hugging Face LLMs using the text-generation-inferencing (TGI) backend. This component is compatible with any TGI deployed model regardless of whether it is deployed on:
- paid HF Inference Endpoints 
- free HF Inference API
- customers own infrastructure running TGI backend 
- Component `HuggingFaceTGIGenerator`, is being introduced, designed to work with any chat LLM deployed with the TGI framework.
```python
from haystack.preview.components.generators import HuggingFaceTGIGenerator
client = HuggingFaceTGIGenerator(model="mistralai/Mistral-7B-v0.1", token="<your-token>")
client.warm_up()
response = client.run("What's Natural Language Processing?")
print(response)
```
These examples demonstrate how users can inference llama-2 LLM deployed on the free …
> feat: Add `HuggingFaceTGIGenerator` Haystack 2.x component

- haystack/preview/components/generators/chat/hugging_face_tgi.py
- haystack/preview/components/generators/hf_utils.py
- haystack/preview/components/generators/hugging_face_tgi.py
- fixes #6251 
Add lazy import blocks for transformers dependencies in TGI Generators
CI
> fix: lazy import transformers in TGI Generators

- haystack/preview/dataclasses/document.py
- releasenotes/notes/document-blob-ae28734c5be561d9.yaml
- test/preview/dataclasses/test_document.py
This PR changes the type of the `blob` field in `Document` from `bytes` to `ByteStream`.
It also removes the `mime_type` field from `Document` as it's already present in `ByteStream`.
I updated tests and run unit tests locally.
I also removed some `Document` unit tests that were outdated. …
> refactor: Change Document.blob type and remove mime_type field

- haystack/preview/components/generators/chat/hugging_face_tgi.py
- haystack/preview/components/generators/hf_utils.py
- haystack/preview/components/generators/hugging_face_tgi.py
In #6252, I incorrectly used  `haystack.lazy_imports` for preview components, instead of `haystack.preview.lazy_imports`.
I'm fixing this error.
Can't be easily tested without releasing a new version of `hasytack-ai` …
> fix: replace `haystack.lazy_imports` with `haystack.preview.lazy_imports`

- e2e/preview/pipelines/test_rag_pipelines.py
- haystack/preview/components/generators/chat/__init__.py
- haystack/preview/components/generators/chat/openai.py
- haystack/preview/dataclasses/chat_message.py
- releasenotes/notes/migrate-gpt-generator-for-chat-generator-b1edb394f3d6c9ef.yaml
- test/preview/components/generators/chat/test_openai.py
- test/preview/components/generators/test_openai.py
To provide a straightforward approach for users to interact with OpenAI's gpt-3.5-turbo and gpt-4 models for chat-based text generation using the chat completions API endpoint.
Introducing `GPTChatGenerator`, a component allowing users to easily generate text responses from OpenAI's large language models (LLMs) in a chat-based scenario.
```python
from haystack.preview.components.generators.chat import GPTChatGenerator
from haystack.preview.dataclasses import ChatMessage
messages = [ChatMessage.from_user("What's Natural Language Processing?")]
client = GPTChatGenerator()
response = client.run(messages)
print(response)
```
Users can pass any valid text generation parameters to the `**generation_kwargs` parameter in the `__init__` method or the `run` method, as supported by the …
> feat: Add `GPTChatGenerator` to Haystack 2.x

- haystack/preview/components/readers/extractive.py
- releasenotes/notes/add-model-kwargs-extractive-reader-c0b65ab34572408f.yaml
- test/preview/components/readers/test_extractive.py
- fixes #N/A
Add new variable `model_kwargs` to the `ExtractiveReader` so we can pass different loading options supported by HuggingFace. This is similar to the `pipeline_kwargs` used by the HuggingFaceLocalGenerator to pass kwargs to the underlying HF pipeline. In this case I named the variable `model_kwargs` because we are loading the extractive QA model under-the-hood.
- Updated unit test to check we are passing the kwargs properly.
- Also ran locally to check the passed model_kwargs impacted model loading.
- I added …
> feat: Add `model_kwargs` to ExtractiveReader to impact model loading

- haystack/nodes/other/join_docs.py
- releasenotes/notes/fix-join-docs-null-score-746c392a87adffcc.yaml
- test/nodes/test_join_documents.py
- fixes #6253 
When using `JoinDocuments` with `join_mode=concatenate` (default) and passing duplicate documents, including some with a null score, this node raised an exception.
- fix this behavior, considering null scores == -inf for ordering purposes
New unit test, CI …
> fix: make `JoinDocuments` correctly handle duplicate documents w null scores

- haystack/preview/dataclasses/document.py
Wrap JSON string in `io.StringIO` when calling `pands.read_json()` as calling it with a JSON string is deprecated. See [official docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html#pandas-read-json).
The currently pinned version `2.0.3` of Pandas doesn't emit the warning since reading a JSON string directly as been deprecated only from `2.1.0`.
Still worth to fix this now to avoid future pains.
I omitted the release note as this doesn't change any public API or functionality. …
> chore: Fix deprecation warning when calling Document.from_dict()

- haystack/preview/components/file_converters/pypdf.py
- releasenotes/notes/add-custom-converter-hook-to-pypdf-cc7c333a6e7fc5f7.yaml
- test/preview/components/file_converters/test_pypdf_to_document.py
Add support for a custom converter callable in PyPDFToDocument to enhance conversion flexibility and allow for more complex conversions tailored to specific use cases. This change was inspired by community discussions https://github.com/deepset-ai/haystack/discussions/4467 and https://github.com/deepset-ai/haystack/issues/5963
We've added the ability to specify a custom converter function to the PyPDFToDocument component. This function takes a `PdfReader` object and returns a `Document` object, allowing for customized text extraction logic.
You can now pass a custom converter to PyPDFToDocument like so:
```python
from pypdf import PdfReader
from haystack.preview.components.file_converters.pypdf import PyPDFToDocument
from haystack.preview.dataclasses import Document
def …
```
> feat: Add custom conversion callable to PyPDFToDocument - Haystack 2.x

- haystack/preview/components/file_converters/pypdf.py
- fixes: using the `PdfReader` symbol when `pypdf` is not installed
> fix: make types work without installing pypdf

- examples/seq2seq_replacement.py
- haystack/modeling/data_handler/data_silo.py
- haystack/utils/augment_squad.py
- since the release of mypy 1.7, we have seen errors like [this](https://github.com/deepset-ai/haystack/actions/runs/6826288135/job/18565889872?pr=6276)
- I ran mypy on the repository and I'm simply ignoring the specific types of errors raised by mypy
CI
- I documented …
> chore: ignore new mypy errors (due to 1.7 release)

- haystack/preview/dataclasses/document.py
- releasenotes/notes/fix-document-init-09c1cbb14202be7d.yaml
- test/preview/dataclasses/test_document.py
- fixes #6259 
The `_BackwardCompatible` metaclass made it possible to create a `Document` by passing any parameter to it.
This parameters would end up in the `meta` field.
This PR fixes that so that only legacy and new fields can be used to build a `Document`.
`from_dict` has been updated accordingly to handle flattened dictionaries.
Updated unit tests.
N/A …
> Fix Document init when passing non existing fields

- haystack/preview/components/retrievers/in_memory_bm25_retriever.py
- haystack/preview/components/retrievers/in_memory_embedding_retriever.py
- haystack/preview/document_stores/in_memory/document_store.py
- releasenotes/notes/scale-score-false-h2-3c8e4e7e543e8cce.yaml
- test/preview/components/retrievers/test_in_memory_bm25_retriever.py
- test/preview/components/retrievers/test_in_memory_embedding_retriever.py
- fixes #6271
- changed the default value of `scale_score` to False
CI, changed some tests
> refactor!: set `scale_score` default value to False

- haystack/preview/components/file_converters/html.py
The explanation of 'sources' is inadequate especially because this is probably going to be most used with `LinkContentFetcher` that returns `List[ByteStream]`
> Update docstring in html.py

- haystack/preview/components/rankers/meta_field.py
- releasenotes/notes/remove-query-param-MetaFieldRanker-56883ab0377b7605.yaml
- test/preview/components/rankers/test_metafield.py
- fixes #6292 
Removes the `query` parameter from the run method of `MetaFieldRanker`.
Updated existing Unit and Integration tests. …
> feat!: Remove unused query parameter from `MetaFieldRanker`

- haystack/preview/components/rankers/__init__.py
- fixes an issue that prevented importing `from haystack.preview.components.rankers import MetaFieldRanker`
- add MetaFieldRanker to rankers `__init__.py`
```python
from haystack.preview import Document
from haystack.preview.components.rankers import MetaFieldRanker
docs = [Document(content="Paris", meta={"rating": 1.3}), Document(content="Berlin", meta={"rating": 0.7})]
ranker = MetaFieldRanker(metadata_field="rating")
ranker.run(documents=docs, top_k=1)
```
- I've used one …
> chore: Add `MetaFieldRanker` to rankers `__init__.py`

- haystack/preview/components/readers/extractive.py
- releasenotes/notes/fix-reader-top-k-b4f7e29be5ba5ee1.yaml
2.0 Reader returns top_k+1 answers if no_answer is enabled (default), while the documentation claims that top_k answers will be returned. For example, the following code returns two answers although top_k is set to 1. One answer is a the correct text answer and the other is a no_answer with no text and the probability that the other answer is incorrect.
```python
from haystack.preview import Document
from haystack.preview.components.readers import ExtractiveReader
docs = [Document(content="Paris is the capital of France."), Document(content="Berlin is the capital of Germany.")]
reader = ExtractiveReader()
reader.warm_up()
reader.run(query="What is the capital of France?", documents=docs, top_k=1)
```
- Updated the doc strings explaining that Reader returns top_k+1 answers if no_answer is …
> docs: Reader returns top_k+1 answers if no_answer is enabled

- haystack/document_stores/utils.py
- releasenotes/notes/metadata_enhancement_for_SQuAD_files-2247c72f07760465.yaml
- test/others/test_eval_data_from_json.py
- Fixes #5978
Load additional fields from SQUAD-format file to meta field for labels. This change ensures that `eval_data_from_json` loads additional fields for Labels into the `meta` field, analogous to how it's done for Documents.
I added new unit tests to cover the changes, ensuring that the loading of additional fields for Labels functions as expected. Additionally, I performed manual verification by running the modified `eval_data_from_json` function on a SQUAD-format file with additional fields for Labels.
I've followed the structure of `eval_data_from_json` for Documents and extended it to support Labels.
> fix: Load additional fields from SQUAD-format file to meta field for labels #5978

- .github/workflows/e2e_preview.yml
- .github/workflows/linting.yml
- .github/workflows/linting_preview.yml
- .github/workflows/tests_preview.yml
- haystack/nodes/audio/whisper_transcriber.py
- haystack/preview/components/audio/whisper_local.py
- pyproject.toml
- releasenotes/notes/simplify-whisper-installation-1e347e2527cbf913.yaml
The previous openai-whisper version pinned tiktoken causing a version conflict with Haystack's dependencies. The most recent openai-whisper version now unpins tiktoken, which resolves the conflict: https://github.com/openai/whisper/blob/v20231106/requirements.txt#L6
- Upgrade openai-whisper to the latest version
- Re-introduce audio extra
- Install audio extra in workflows
Still pending
I am still testing this and will report back here.
- Opened https://github.com/deepset-ai/haystack/pull/6321 to fix an unrelated error in the e2e preview tests in a preprocessing pipeline
- I have …
> build: Upgrade openai-whisper and re-introduce audio extra

- haystack/preview/dataclasses/document.py
- releasenotes/notes/fix-document-flatten-metadata-ef61dbbae08b1db7.yaml
- test/preview/dataclasses/test_document.py
- follow-up of #6286
After #6286, creating a document with `Document(meta={"key": "value"})` would fail with:
`TypeError: haystack.preview.dataclasses.document.Document() got multiple values for keyword argument 'meta'`
- Remove the `meta` key from the `data` dictionary while we iterate the fields to unflatten meta
- This change fixes https://github.com/deepset-ai/haystack-core-integrations/actions/runs/6884405007/job/18726839670
- Unit tests
I don't think we'll have a case where we receive both `meta=` and flatten keywords, but the current logic accounts for that.
- I have updated the …
> fix: fix un-flattening of metadata

- haystack/preview/dataclasses/document.py
- releasenotes/notes/document-equality-4bc1b5273bd5b7f1.yaml
- test/preview/document_stores/test_in_memory.py
This PR changes how different `Document`s are compared.
Previously two `Document`s with all different fields but identical `id`s would be considered equal.
That's an unexpected that could cause confusion in users.
So this PR changes `Document.__eq__()` to compare the dictionary representation of two `Document`s.
I ran unit tests locally and edited the failing ones.
This is also necessary for #6284. …
> feat: Change `Document.__eq__` to compare all fields

- .github/workflows/e2e.yml
- e2e/preview/pipelines/test_extractive_qa_pipeline.py
One of the e2e preview tests fails because of a missing dependency, langdetect: https://github.com/deepset-ai/haystack/actions/workflows/e2e.yml
`FAILED e2e/preview/pipelines/test_preprocessing_pipeline.py::test_preprocessing_pipeline - ImportError: Failed to import 'langdetect'. Run 'pip install langdetect'. Original error: No module named 'langdetect'`
- Install langdetect dependency
- Compare doc content and id only in test_extractive_qa_pipeline.py to account for changes to `Document.__eq__` in https://github.com/deepset-ai/haystack/pull/6323
e2e tests are passing: https://github.com/deepset-ai/haystack/actions/runs/6901284179 …
> test: Add langdetect installation to e2e tests

- haystack/preview/components/generators/chat/openai.py
GPTChatGenerator, when doing function calling, returns a message.function_call, an OpenAIObject. This object wasn't converted to a string. This resulted in inconsistencies in message handling as the ChatMessage content field didn't contain a string.
I modified GPTChatGenerator to ensure that message.function_call, when received as an OpenAIObject, is converted to a string. This string can then be converted into JSON and processed further but it complies with our ChatMessage content field.
The modification allows GPTChatGenerator to handle function messages properly
Manually. I wanted to add a unit test, but I didn't for two reasons. These kinds of things can only be tested with a live call, and function calling has been [deprecated](https://platform.openai.com/docs/api-reference/chat/creat …
> feat: Convert OpenAI GPT function call JSON response to string

- e2e/preview/pipelines/test_extractive_qa_pipeline.py
- haystack/preview/components/readers/extractive.py
- haystack/preview/document_stores/decorator.py
- pyproject.toml
- releasenotes/notes/canals-0.10.0-bfa4020a8cf207c4.yaml
- releasenotes/notes/fix-reader-top-k-b4f7e29be5ba5ee1.yaml
- test/preview/components/audio/test_whisper_local.py
- test/preview/components/audio/test_whisper_remote.py
- test/preview/components/builders/test_prompt_builder.py
- test/preview/components/caching/test_url_cache_checker.py
- test/preview/components/embedders/test_openai_document_embedder.py
- test/preview/components/embedders/test_openai_text_embedder.py
- test/preview/components/embedders/test_sentence_transformers_document_embedder.py
- test/preview/components/embedders/test_sentence_transformers_text_embedder.py
- test/preview/components/file_converters/test_azure_ocr_doc_converter.py
- test/preview/components/generators/chat/test_openai.py
- test/preview/components/generators/test_hugging_face_local_generator.py
- test/preview/components/generators/test_openai.py
- test/preview/components/rankers/test_metafield.py
- test/preview/components/rankers/test_transformers_similarity.py
- test/preview/components/readers/test_extractive.py
- test/preview/components/retrievers/test_in_memory_bm25_retriever.py
- test/preview/components/retrievers/test_in_memory_embedding_retriever.py
- test/preview/components/websearch/test_serperdev.py
- test/preview/components/writers/test_document_writer.py
- test/preview/document_stores/test_in_memory.py
- test/preview/test_files/yaml/test_pipeline.yaml
- test/preview/test_telemetry.py
- test/preview/testing/test_factory.py
- Upgrade canals to 0.10.1
Local tests, CI
- https://github.com/deepset-ai/canals/pull/167 changed the way the class of components are saved to dict, so I needed to update all (de)serialization tests. …
> feat: upgrade canals to 0.10.1

- .github/workflows/tests_preview.yml
- test/preview/components/builders/test_answer_builder.py
Change CI for `preview` to run all tests not marked with `@pytest.mark.integration`.
I had to fix some tests as they weren't run with the current approach.
Run `pytest -m "not integration"  test/preview` locally.
In a future PR I will remove all `@pytest.mark.unit` decorators from tests in `test/preview`. …
> ci: Change preview tests to run all tests except integration ones

- haystack/preview/dataclasses/document.py
- haystack/preview/testing/document_store.py
- releasenotes/notes/document-equality-4bc1b5273bd5b7f1.yaml
- test/preview/document_stores/test_in_memory.py
Remove `DocumentStoreBaseTests.contains_same_docs` method as it's not necessary anymore to compare list of `Document`s.
Developers can now just compare the lists of `Document`s directly with `==`.
Depends on #6323
- I …
> refactor: Remove unecessary method to compare list of `Document`s in `DocumentStoreBaseTests`

- haystack/preview/dataclasses/document.py
- releasenotes/notes/better-doc-repr-6d35de1cf4b25697.yaml
- fixes #6315
(Discussed with @masci)
- define a more descriptive `__repr__` for Document
- do not define `__str__` (`__repr__` will be used)
**Example**
`doc = Document(content="dfd", meta={"name": "test"}, score=0.9, embedding=[1, 2, 3])`
will have this representation:
`Document(id=0e2e032e0f638d798e971143e0a4439f606a46e304ed6c50a01501e820940e19, `
`content: 'dfd', meta: {'name': 'test'}, score: 0.9, embedding: vector of size 3)`
CI …
> refactor: improve Document representation

- haystack/preview/testing/document_store.py
Move `count_documents` tests from `DocumentStoreBaseTests` into `CountDocumentsTest` class.
`DocumentStoreBaseTests` now inherits `CountDocumentsTest`.
Depends on #6324. …
> refactor: Move tests for `count_documents` from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move `write_documents` tests from `DocumentStoreBaseTests` into `WriteDocumentsTest` class.
`DocumentStoreBaseTests` now inherits `WriteDocumentsTest`.
Depends on #6332. …
> refactor: Move tests for `write_documents` from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move `filter_documents` tests with equal filters from `DocumentStoreBaseTests` into `LegacyFilterDocumentsNestedLogicalTest` class.
`LegacyFilterDocumentsTest` now inherits `LegacyFilterDocumentsNestedLogicalTest`.
Depends on #6348. …
> Move `filter_documents` tests with nested logical filters from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move `filter_documents` tests with equal filters from `DocumentStoreBaseTests` into `LegacyFilterDocumentsSimpleLogicalTest` class.
`LegacyFilterDocumentsTest` now inherits `LegacyFilterDocumentsSimpleLogicalTest`.
Depends on #6347. …
> Move `filter_documents` tests with simple logical filters from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move `filter_documents` tests with equal filters from `DocumentStoreBaseTests` into `LegacyFilterDocumentsLessThanTest` class.
`LegacyFilterDocumentsTest` now inherits `LegacyFilterDocumentsLessThanTest`.
Depends on #6345. …
> Move `filter_documents` tests with less than filters from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move `filter_documents` tests with equal filters from `DocumentStoreBaseTests` into `LegacyFilterDocumentsGreaterThanEqualTest` class.
`LegacyFilterDocumentsTest` now inherits `LegacyFilterDocumentsGreaterThanEqualTest`.
Depends on #6344. …
> Move `filter_documents` tests with greater than equal filters from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move `filter_documents` tests with equal filters from `DocumentStoreBaseTests` into `LegacyFilterDocumentsGreaterThanTest` class.
`LegacyFilterDocumentsTest` now inherits `LegacyFilterDocumentsGreaterThanTest`.
Depends on #6343.
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my …
> Move `filter_documents` tests with greater than filters from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move `filter_documents` tests with equal filters from `DocumentStoreBaseTests` into `LegacyFilterDocumentsNotInTest` class.
`LegacyFilterDocumentsTest` now inherits `LegacyFilterDocumentsNotInTest`.
Depends on #6342. …
> Move `filter_documents` tests with not in filters from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move `filter_documents` tests with equal filters from `DocumentStoreBaseTests` into `LegacyFilterDocumentsInTest` class.
`LegacyFilterDocumentsTest` now inherits `LegacyFilterDocumentsInTest`.
Depends on #6341. …
> Move `filter_documents` tests with in filters from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move `filter_documents` tests with equal filters from `DocumentStoreBaseTests` into `LegacyFilterDocumentsNotEqualTest` class.
`LegacyFilterDocumentsTest` now inherits `LegacyFilterDocumentsNotEqualTest`.
Depends on #6340. …
> Move `filter_documents` tests with not equal filters from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move `filter_documents` tests with equal filters from `DocumentStoreBaseTests` into `LegacyFilterDocumentsEqualTest` class.
`LegacyFilterDocumentsTest` now inherits `LegacyFilterDocumentsEqualTest`.
Depends on #6339. …
> Move `filter_documents` tests with equal filters from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move `filter_documents` tests with invalid filters from `DocumentStoreBaseTests` into `LegacyFilterDocumentsInvalidFiltersTest` class.
`LegacyFilterDocumentsTest` now inherits `LegacyFilterDocumentsInvalidFiltersTest`.
Depends on #6338. …
> refactor: Move `filter_documents` tests with invalid filters from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move generic `filter_documents` tests from `DocumentStoreBaseTests` into `LegacyFilterDocumentsTest` class.
`DocumentStoreBaseTests` now inherits `LegacyFilterDocumentsTest`.
Depends on #6337. …
> refactor: Move generic `filter_documents` tests from `DocumentStoreBaseTests` to separate class

- haystack/preview/testing/document_store.py
Move `filterable_docs` fixture tests from `DocumentStoreBaseTests` into `FilterableDocsFixtureMixin` mixin class.
`DocumentStoreBaseTests` now inherits `FilterableDocsFixtureMixin`.
Depends on #6336. …
> Move `filterable_docs` fixture from `DocumentStoreBaseTests` to separate mixin class

- haystack/preview/testing/document_store.py
Move `delete_documents` tests from `DocumentStoreBaseTests` into `DeleteDocumentsTest` class.
`DocumentStoreBaseTests` now inherits `DeleteDocumentsTest`.
Depends on #6334. …
> refactor: Move tests for `delete_documents` from `DocumentStoreBaseTests` to separate class

- haystack/preview/document_stores/in_memory/document_store.py
- releasenotes/notes/inmemory-return-written-documents-488b7f90df84bc59.yaml
- test/preview/document_stores/test_in_memory.py
- Related to https://github.com/deepset-ai/haystack/pull/6006
- Make `InMemoryDocumentStore` return the number of docs actually written
Unit test
Should be merged after the related issue above …
> feat: make `InMemoryDocumentStore` return the number of docs actually written

- haystack/preview/document_stores/in_memory/document_store.py
- fixes #6310
- The issue was related to recent refactorings of the Document class.
- To recreate the document from a dictionary, I correctly use `from_dict`
- CI
- [Colab example](https://colab.research.google.com/drive/17ZYL6MiohzSRHdJU_EJ5BQCzjQnOnQpf#scrollTo=XYuRkc7tljbK) is working …
> fix: InMemoryDocumentStore - recreate Documents in the right way during embedding retrieval

- conftest.py
Make a small change in `pytest_generate_tests` to skip polluting `preview` tests with unwanted, hard to debug hidden parametrization.
I discovered this after #6360.  …
> test: Prevent `pytest_generate_tests` from polluting `preview` tests

- conftest.py
- haystack/preview/testing/document_store.py
- test/preview/document_stores/test_in_memory.py
Related to #6284
Rename `doctstore` fixture used by Document Store tests to `document_store` for consistency.
I ran tests locally and updated the ones using the fixture.
Depends on #6361.
- I …
> refactor: Rename `docstore` fixture to `document_store`

- haystack/preview/document_stores/in_memory/document_store.py
- haystack/preview/testing/document_store.py
Related to #6284
Rework tests for `delete_documents()`.
This PR also changes the expected behaviour of `delete_document()` to not fail when the specified to delete doesn't exist. That's much more sensible and makes the method idempotent. 
Depends on #6362 …
> refactor: Rework `delete_documents` tests

- docs/pydoc/config-preview/router.yml
Add DocumentJoiner to API docs of routers
> docs: Add DocumentJoiner 2.0 to API docs

- haystack/preview/components/routers/__init__.py
Add `DocumentJoiner` to routers' init to enable importing `from haystack.preview.components.routers import DocumentJoiner` …
> fix: Add DocumentJoiner to routers' init

- haystack/preview/components/generators/hugging_face_local.py
- fixes #6353 (added a comment to explain the bug)
- Merge the lazy import blocks of transformers and torch
- Make sure that the class `StopWordsCriteria` is contained in this block. It is required since it uses both transformers and torch.
Manual test on a fresh venv
- …
> fix: `HuggingFaceLocalGenerator` - merge lazy import blocks

- haystack/preview/components/routers/document_joiner.py
- Add TextEmbedder to DocumentJoiner usage example as the hybrid retrieval pipeline requires it
Ran the usage example manually …
> docs: Include TextEmbedder in DocumentJoiner usage example

- haystack/nodes/retriever/dense.py
- releasenotes/notes/embedding-instructions-4feb216cbf796678.yaml
- test/conftest.py
- test/nodes/test_retriever.py
New family of dense retrievers are fine tuned on specific tasks using a prefix instruction for embedding; e.g. "embed this query", "embed this passage for Q&A retrieval"; See [LLM-Embedder](https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/llm_embedder) for such an example, where every type of task has a pair of query-passage embedding instructions. 
The proposed change is introducing 2 optional arguments to `EmbeddingRetriever` and use them as prefix before embedding. 
Created a test that can be run via 
```
pytest test/nodes/test_retriever.py::test_embedding_with_instructions
```
All done.
> feat: embedding instructions for dense retrieval

- haystack/preview/testing/document_store.py
Related to #6284.
Remove tests verifying behaviour of badly formatted legacy filter. …
> test: Remove Document Store test with invalid filter

- haystack/preview/components/writers/document_writer.py
- test/preview/components/writers/test_document_writer.py
- #6362 requires the `write_documents` method of Document Stores to return the number of Documents actually written
- for the `InMemoryDocumentStore`, this was implemented in #6006
- align the Document Writer component with the `write_documents` method, making it return the actual number of Documents written (instead of the initial number of docs)
CI …
> feat: make `DocumentWriter` return the actual number of documents written

- haystack/preview/components/file_converters/html.py
- releasenotes/notes/add-metadata-HTMLToDocument-42dbd074a46c979e.yaml
- test/preview/components/file_converters/test_html_to_document.py
- fixes #6275 
- fixes a part of #6131 
- Adds `ByteStream` metadata to `Document` metadata on creation of documents.
- Adds an optional `meta` parameter in the `run()` method, that allows the users to pass additional metadata to the `Documents`.
Unit tests, Integration tests and manual verification.
Usage examples showcasing the various methods for adding metadata to the documents can be viewed in this [Colab Notebook](https://colab.research.google.com/drive/1u7g0DzRg9OcgNWqoLQyvgjScb_PVIAbS?usp=sharing). It also has an example utilizing HTMLToDocument with LinkContentFetcher.
- I have …
> feat: Add `ByteStream` metadata and other metadata to `Documents` created by `HTMLToDocument`  

- haystack/preview/document_stores/protocols.py
Pyright reporting 
> Function with declared return type "int" must return value on all code paths
on the protocol methods definitions
Use an ellipsis to signal the type checker that the method will be implemented eventually
Locally tested with pyright, mypy was already happy with the previous code …
> fix: fix type hints on `DocumentStore` protocol

- examples/preview/retrievers/in_memory_bm25_documentsearch.py
- examples/preview/retrievers/in_memory_bm25_rag.py
We want code snippets for each component. During user interviews, our outstanding documentation came up a lot. Users also love our code snippets and want even more of them. We should ensure that we have code snippets for each component and that those code snippets work.
- will showcase simple usage of each component: usage of the component itself, within a pipeline, or both
- keep code snippets on GitHub and their usage inside documentation in sync (TBD how we sync with docs, for now documentation team will be notified of any changes to existing snippets, as well as when snippets fail to run)
- will be tested only if they run through (to be clear: there will be no assertions on code level) 
- constitute of one .py file per code snippet
- we have a folder structure similar to …
> Feat: Create code snippets for each component

- haystack/preview/components/builders/prompt_builder.py
- test/preview/components/builders/test_prompt_builder.py
This Pull Request reverts the `PromptBuilder` class back to its more straightforward implementation before attempts to use it for both chat and non-chat messages. With the introduction of [DynamicPromptBuilder](https://github.com/deepset-ai/haystack/pull/6328), the original PromptBuilder will serve static prompt use cases. We'll subsequently see if it makes sense to adapt `PromptBuilder` to support chat-based prompting. 
The PR includes the following changes:
- Removal of the capability to use dynamic templates based on template variables. The `PromptBuilder` will no longer support different templates for each message or dynamic templating on a per-user message basis.
- Simplification of the `PromptBuilder` class. It now solely focuses on rendering a prompt from a Jinja2 template string. …
> fix: Revert back to straightforward PromptBuilder

- docs/pydoc/config-preview/builder.yml
- haystack/preview/components/builders/__init__.py
- haystack/preview/components/builders/dynamic_prompt_builder.py
- pyproject.toml
- releasenotes/notes/add-dynamic-prompt-builder-e61c4b11405b8d80.yaml
- test/preview/components/builders/test_dynamic_prompt_builder.py
This pull request introduces the `DynamicPromptBuilder` component. This new prompt builder enables dynamic and parametrized prompting, significantly enhancing the flexibility and functionality of prompt generation within the haystack pipeline.
The following key changes have been made in this PR:
1. **DynamicPromptBuilder Implementation**: The main addition is `DynamicPromptBuilder` class in `dynamic_prompt_builder.py`. This class leverages Jinja2 templating to dynamically generate prompts based on either a list of `ChatMessage` instances or a string template. It can operate in chat or non-chat mode and supports injecting variables resolved at runtime.
2. **__init__.py Update**: Modified to include `DynamicPromptBuilder` in the module's `__all__` list, making it accessible as part of the …
> feat: Add DynamicPromptBuilder to Haystack 2.x

- haystack/preview/components/converters/pypdf.py
- releasenotes/notes/fix-pypdf-serialization-93744fd01ef5b841.yaml
- test/preview/components/converters/test_pypdf_to_document.py
- fixes #6388
The component accepted an object (`converter`) as an initialization parameter and this made the serialization/deserialization fail.
After discussing with @masci, we decided to:
- create a registry of available converters
- accept `converter_name` instead of `converter`
In the most common use case, we still use the same default converter.
The advanced user can insert its custom converter in the registry.
While not great from the UX perspective, it seems a good temporary solution that we can refine in the future.
CI, new test, manual tests based on #6388
- I have updated the …
> fix!: make `PyPDFToDocument` JSON-serializable

- pyproject.toml
- rest_api/pyproject.toml
Fixed #6119
Remove `pydoc-markdown` dependency from `dev` extra.
`pydoc-markdown` is only used in `readme_sync.yml` workflow and is also installed via `docs/pydoc/requirements.txt` ignoring Haystack `pyproject.toml`.
So it's safe to remove.
This also unpins `fastapi` version in `rest_api`.
There's nothing much to test really.
N/A …
> chore: Remove `pydoc-markdown` from dev dependencies

- docs/pydoc/config/file-converters.yml
- `PptxConverter` was introduced in #6399, but I forgot to to create an entry in pydoc config
- Add the entry to pydoc config
- (sort the entries in alphabetical order) …
> chore: add `PptxConverter` to pydoc configuration

- haystack/preview/components/generators/cohere.py
- test/preview/components/generators/test_cohere_generators.py
- fixes failing import in `haystack-ai`
- `from haystack.lazy_import` --> `from haystack.preview.lazy_import` in `cohere.py` (the [recently introduced](https://github.com/deepset-ai/haystack/pull/6395) `CohereGenerator`)
- renames `model` to `model_name` for consistency
CI
@bilgeyucel  …
> Fix wrong import in `cohere.py` and change `model` to `model_name` for consistency

- haystack/preview/components/readers/extractive.py
- test/preview/components/readers/test_extractive.py
- fixes https://github.com/deepset-ai/haystack/issues/6098
Some tokenizers seems to have their `token_to_chars` function returning None on some inputs, while the function should always return a tuple as long as the token is in the context, according to its own docstring. 
Considering that this is likely a bug of the tokenizer, and to prevent such issues from crashing the reader, I propose to use None as start/end positions when this bug occurs. This choice means that if the starting token points to position None, it will match the start of the document, and if the end token points to position None, it will match the end of the document. Such occurrences are logged.
Alternatively we could raise an error message, but the source of this behavior is unclear and likely tokenizer-dependent, see …
> fix: make `ExtractiveReader` handle situations where `token_to_chars` returns None instead of a (start, end) tuple

- haystack/preview/components/generators/cohere.py
`from haystack.preview.components.generators import GPTGenerator`
fails:
```
NameError                                 Traceback (most recent call last)
[<ipython-input-7-eb9e460423a2>](https://localhost:8080/#) in <cell line: 3>()
1 from haystack.preview import Pipeline
2 from haystack.preview.components.builders.prompt_builder import PromptBuilder
----> 3 from haystack.preview.components.generators import GPTGenerator
4 
5 prompt_template = """
2 frames
[/usr/local/lib/python3.10/dist-packages/haystack/preview/components/generators/__init__.py](https://localhost:8080/#) in <module>
----> 1 from haystack.preview.components.generators.cohere import CohereGenerator
2 from haystack.preview.components.generators.hugging_face_local import HuggingFaceLocalGenerator
3 from …
```
> fix: Cohere - better handling of `COHERE_API_URL`

- e2e/preview/pipelines/test_preprocessing_pipeline.py
- haystack/preview/components/routers/metadata_router.py
- haystack/preview/document_stores/in_memory/document_store.py
- haystack/preview/document_stores/protocols.py
- haystack/preview/testing/document_store.py
- haystack/preview/utils/filters.py
- releasenotes/notes/rework-filters-1bb103d196a1912b.yaml
- test/preview/components/routers/test_metadata_router.py
- test/preview/document_stores/test_in_memory.py
- test/preview/utils/test_filters.py
This PR changes `MetadataRouter` and  `InMemoryDocumentStore` to support new filters as defined in proposal #6001.
I also updated the `DocumentStore` protocol docstring to reflect the support of new filters.
I added new tests and update the ones failing cause of the behaviour change.
`InMemoryDocumentStore` still uses legacy filters converted to new ones in tests as I'll add tests for new filters in `testing/document_store.py` in a later PR. …
> refactor: Add support for new filters declaration

- .github/workflows/snippets_tests.yml
- examples/pipeline_loop_to_autocorrect_json.py
- Fixes https://github.com/deepset-ai/haystack/issues/5989
- Let's add it as an example here in the main repo
- @bilgeyucel will create a tutorial out of the notebook here, too (separate stream work) …
> docs: Add example for loop in pipeline to autocorrect JSON

- examples/pipelines/indexing_pipeline.py
- fixes #6014 
- Add example of an indexing pipeline that converts txt and pdf to documents, joins resulting lists, cleans and splits them, creates embeddings and then writes them to a document store.
Manually with and without a directory containing txt and pdf files. 
This code is also a subset of the code used in one of our e2e tests: https://github.com/deepset-ai/haystack/blob/main/e2e/pipelines/test_preprocessing_pipeline.py …
> docs: Add indexing example

- haystack/document_stores/in_memory/document_store.py
- haystack/testing/document_store.py
- releasenotes/notes/document-store-testing-c1a8050f06ff3e97.yaml
- fixes #6284
Add `FilterDocumentsTest` to test Document Stores using new filters format.
N/A
> refactor: Add new filters tests for Document Store testing

- haystack/document_stores/in_memory/document_store.py
- haystack/document_stores/protocols.py
- haystack/testing/document_store.py
- releasenotes/notes/default-write-documents-policy-95afe5fb34fc73ad.yaml
- test/document_stores/test_in_memory.py
- fixes #6430
Change the default `DuplicatePolicy` for the `DocumentStore.write_documents()` protocol from `DuplicatePolicy.FAIL` to `DuplicatePolicy.NONE`.
This way Document Stores implementers will be able to choose their own default policy instead of being forced to use `DuplicatePolicy.FAIL`.
This PR also changes the `WriteDocumentsTest` class to raise when testing the default behaviour of `DocumentStore.write_documents`. This is done so we don't enforce a default behaviour again and so that the implementer is aware it should handle the default policy.
I also had to update the tests for `InMemoryDocumentStore`.
N/A …
> feat: Change default `DuplicatePolicy` in `DocumentStore.write_documents()`

- haystack/components/generators/hugging_face_local.py
- haystack/components/readers/extractive.py
- fixes N/A
Add quotes around type hints for optional dependencies. 
Locally tested by trying to import ExtractiveReader when torch isn't installed.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#install …
> Fix: torch type hints put into quotes

- examples/pipelines/rag_pipeline.py
- Adding an example that can be used in the get started page for 2.0: https://docs.haystack.deepset.ai/v2.0/docs/get_started
@dfokina @Timoeller 
- Adding a RAG query pipeline example. No indexing is used. The RAG pipeline uses sparse retrieval for simplicity. 
Ran manually
Once we have ready made pipelines https://github.com/deepset-ai/haystack/issues/5992, we can update this example. We can also simplify `rag_pipeline.run(...)` once simple input resolution is merged https://github.com/deepset-ai/haystack/pull/6413.
- I …
> docs: Add RAG pipeline example

- haystack/pipelines/base.py
- releasenotes/notes/fix-load-from-deepset-cloud-8a86053ccb246494.yaml
- test/pipelines/test_pipeline.py
- fixes https://github.com/deepset-ai/haystack/issues/6469
- fix `Pipeline.load_from_deepset_cloud` if yaml does not contain `"name"`. This is the case for all newly created dC pipelines.
- ran existing sdk tests (They were actually catching the bug).
- unfortunately the sdk tests are not run during CI. I ran them all locally and fixed where needed. …
> fix: load_from_deepset_cloud without name in yaml

- test/core/pipeline/test_complex_pipeline.py
- test/core/pipeline/test_default_value.py
- test/core/pipeline/test_distinct_loops_pipeline.py
- test/core/pipeline/test_double_loop_pipeline.py
- test/core/pipeline/test_dynamic_inputs_pipeline.py
- test/core/pipeline/test_fixed_decision_and_merge_pipeline.py
- test/core/pipeline/test_fixed_decision_pipeline.py
- test/core/pipeline/test_fixed_merging_pipeline.py
- test/core/pipeline/test_joiners.py
- test/core/pipeline/test_linear_pipeline.py
- test/core/pipeline/test_looping_and_merge_pipeline.py
- test/core/pipeline/test_looping_pipeline.py
- test/core/pipeline/test_mutable_inputs.py
- test/core/pipeline/test_parallel_branches_pipeline.py
- test/core/pipeline/test_self_loop.py
- test/core/pipeline/test_validation_pipeline_io.py
- test/core/pipeline/test_variable_decision_and_merge_pipeline.py
- test/core/pipeline/test_variable_decision_pipeline.py
- test/core/pipeline/test_variable_merging_pipeline.py
Remove leftovers from canals migration:
- Remove prints
- Remove calls to `draw()`
- Remove `__main__` entrypoint
`pytest -m"not integration" test/core/pipeline`
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTI …
> chore: clean up `core` tests

- .github/workflows/readme_sync.yml
- API Reference is not currently updated on changes
Reintroduce a minimal readme_sync workflow, that only pushes changes on main to the 2.0 API reference
I need help to configure the workflow right …
> ci: reintroduce readme_sync workflow

- docs/pydoc/config/dataclass.yml
- fixes https://github.com/deepset-ai/haystack/actions/runs/7114326817
Fix typo
Run locally ./.github/utils/pydoc-markdown.sh …
> fix: fix typo in pydoc config

- haystack/nodes/document_classifier/transformers.py
When I tried using the TransformersDocumentClassifier with the task 'text-classification' I always had an error because it used 'use_auth_token' in the creation of the pipeline, instead of 'token'.
Manual verification on the scrypt it was first intented to use it.
- I …
> Change use_auth_token to token in TransformersDocumentClassifier

- haystack/nodes/prompt/prompt_model.py
- releasenotes/notes/prompt-model-invocation-layer-e7a69a3ac3beb5a7.yaml
- test/prompt/test_prompt_model.py
- fixes #6495
This PR changes `PromptModel` `invocation_layer_class` init parameter type. Now it can either be a `PromptModelInvocationLayer` class or `str` pointing to the invocation layer class.
If `str` is used the class module will be imported automatically.
Example usage:
```
model = PromptModel(
invocation_layer_class="haystack.nodes.prompt.invocation_layer.CohereInvocationLayer", api_key="fake_api_key"
)
```
I added a unit test and tested serialisation manually.
This is not a complete fix to the serialisation issue but at least it makes possible to set a custom `invocation_layer_class` in YAML.
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_o …
> feat: Change type of PromptModel invocation_layer_class init param

- e2e/pipelines/test_extractive_qa_pipeline.py
- e2e/pipelines/test_rag_pipelines.py
- haystack/components/builders/answer_builder.py
- haystack/components/readers/extractive.py
- haystack/dataclasses/answer.py
- releasenotes/notes/answer-refactoring-b617afa946311ac8.yaml
- test/components/builders/test_answer_builder.py
- test/components/readers/test_extractive.py
- test/dataclasses/test_answer.py
- test/dataclasses/test_document.py
Closes #6184
Refactor `Answer` dataclass and classes that inherited it.
Now `Answer` is a Protocol, classes that used to inherit it now respect that interface.
We also added a new `ExtractiveTableAnswer` to be used for table question answering. 
So now we have three classes:
* `ExtractiveAnswer`
* `ExtractiveTableAnswer`
* `GeneratedAnswer`
All classes now are easily serializable using `to_dict()` and `from_dict()` like `Document` and components.
Fields have been modified too so that each class only has the information strictly necessary.
I added tests for the serialisation and fixed tests affected by the refactor.
This PR supersedes #6506. …
> refacotr: Refactor answer dataclasses

- pyproject.toml
Remove the `haystack_linter` plugin for Pylint as it doesn't exist anymore for Haystack 2.x.
Nothing to test.
N/A
> chore: Remove old Pylint plugin

- haystack/nodes/prompt/prompt_model.py
- test/prompt/test_prompt_model.py
I am seeing a pylint error on Haystack v1.x after the [recent prompt model PR](https://github.com/deepset-ai/haystack/pull/6497). It's haystack/nodes/prompt/prompt_model.py:101: error: "str" not callable  [operator]  now that invocation_layer_class can be a string: https://github.com/deepset-ai/haystack/pull/6497/files#diff-8a69dcdf57e9a29aff18add4eaa63876f41273bfb905a5b2b9be988a78fe6f76R77
- Use two variables to avoid re-assignment and fix `"str" not callable``
- Add `raise` to fix `pointless-exception-statement`error
- Add mocked tokenizer to unit test to fix error caused by our `urlopen_mock` check
Ran mypy locally
Other option could be # type: ignore 
The test added in the previous PR is not a unit test but marked as one and is failing for that reason: …
> fix: mypy `"str" not callable` for `PromptModelInvocationLayer`

- haystack/nodes/prompt/invocation_layer/hugging_face.py
- test/prompt/invocation_layer/test_hugging_face.py
- fixes #6501
Investigating the issue, I discovered that all the problems disappear if we create a Hugging Face Pipeline using `token` instead of the old `use_auth_token`.
- Internally convert `use_auth_token` to `token`
- I chose to not change the parameter name in the public API, to avoid a breaking change. In 2.0, we already have the right parameter name.
CI. Addition to existing test. Manual verification (described here: https://github.com/deepset-ai/haystack/issues/6501#issuecomment-1851890184).
- I added unit tests …
> fix: `HFInvocationLayer` - convert `use_auth_token` to `token`

- haystack/core/pipeline/draw/draw.py
- haystack/core/pipeline/pipeline.py
- releasenotes/notes/remove-image-from-debug-c83d61db92bcbfc2.yaml
- fixes #6265 
Remove the code with the problematic `deepcopy`, users can still `draw()` the pipeline after a debug run
> fix: do not dump pipeline graph into the debug payload

- releasenotes/config.yaml
> chore: Remove 'preview' from the release notes template

- .github/labeler.yml
No issue, just the 2.x/1.x labelling for PRs is currently manual and unreliable
Automate allthethings
> chore: add version label to PRs

- .github/workflows/minor_version_release.yml
Changes all mentions of the workflow to `main` to `v1.x` to make the workflow work on the correct branch.
Can't test …
> fix: make `minor_version_release.yml` to run on the v1.x branch

- haystack/components/generators/hugging_face_tgi.py
The run method of `HuggingFaceTGIGenerator` does not have this input. There are generation kwargs, which might differ per model as far as I can tell? This code block will generate errors. I am also fixing docs
> Fixing incorrect docstring

- .github/workflows/tests.yml
- haystack/components/converters/html.py
- pyproject.toml
- releasenotes/notes/ship-boilerpy3-0bffbd7955c89dd4.yaml
The additional `pip install boilerpy3` is ubiquitous in our docs and code examples, let's just make it part of `haystack-ai`
Add `boilerpy3` as a dependency, it's only 22kb …
> chore: add boilerpy3 to the core dependencies

- haystack/components/routers/file_type_router.py
- releasenotes/notes/add-markdown-file-type-router-support-39a607faa5c1436f.yaml
- test/components/routers/test_file_router.py
Enhances the router's capability to recognize and handle Markdown files, which are commonly used in documentation and other text-based content.
- fixes https://github.com/deepset-ai/haystack/issues/6391
The modifications include two commits with the following changes:
- **File: `haystack/components/routers/file_type_router.py`**
- Added a method `get_custom_mime_mappings` to return a dictionary of custom file extension to MIME type mappings. This includes mappings for `.md` and `.markdown` files as `text/markdown`.
- Updated the `get_mime_type` method to include custom MIME type mappings, allowing the router to recognize Markdown files.
- **File: `test/components/routers/test_file_router.py`**
- Modified the test `test_run_with_bytestreams_and_file_paths` to include a Markdown file and …
> feat: Add FileTypeRouter markdown support

- haystack/components/converters/azure.py
- haystack/components/converters/html.py
- haystack/components/converters/markdown.py
- haystack/components/converters/pypdf.py
- haystack/components/converters/tika.py
- haystack/components/converters/txt.py
- releasenotes/notes/converters-allow-passing-meta-70fb498b6eb80468.yaml
- test/components/converters/test_azure_ocr_doc_converter.py
- test/components/converters/test_markdown_to_document.py
- test/components/converters/test_pypdf_to_document.py
- test/components/converters/test_textfile_to_document.py
- test/components/converters/test_tika_doc_converter.py
- part of #6546
- based on #6540
_please do not merge the current one before the base has been merged_
- Make all Converters accept `meta` in the `run` method, so that users can provide their own metadata.
The length of this list should match the number of `sources`.
CI, new unit tests …
> feat: Converters - allow passing `meta` in the `run` method

- .github/workflows/github_release.yml
- Automate the current beta releases
At every tag `v2.0.0-beta.X` reno will go through the release notes and publish them in a Github pre-release
Partially tested on a test repo
This is temporary, until we don't branch off the final 2.0.0
- I ran …
> ci: custom release creator for beta versions

- haystack/document_stores/in_memory/document_store.py
- pyproject.toml
- releasenotes/notes/switch-bm25-dep-9b9d1c596f5ff4d0.yaml
- part of https://github.com/deepset-ai/haystack/issues/1006
Let Haystack depend on our own fork of the unmaintained `rank_bm25` called `haystack_bm25`, now available on conda forge. …
> build: depend on `haystack_bm25` instead of `rank_bm25`

- haystack/components/audio/whisper_local.py
- releasenotes/notes/change-localwhispertranscriber-run-3b0a818060867720.yaml
- test/components/audio/test_whisper_local.py
- part of #6101 
- Uniforms the `run` argument names for `LocalWhisperTranscriber`
- Component had support for binary input but it was not exposed through the `run` API, that was also fixed
- Unit and Integration tests, locally …
> refactor!: uniform run api for LocalWhisperTranscriber

- haystack/agents/base.py
- releasenotes/notes/improve-agent-final-answer-matching-21f5710035a498d8.yaml
- test/agents/test_agent.py
- fixes #5743
The agent would discard the final answer if this was distributed on multiple lines. I added a modifier in the regex so that the `.` matches also newline characters.
One possibility is to use the agent to generate code, in this case we should see the bug and then the fix.
In the 2.0 I'd change this structure to pass a flag or to give a closing sequence as well. …
> bug: fix Agent Final Response Discarding text after newline

- haystack/components/rankers/transformers_similarity.py
- releasenotes/notes/transformers-similarity-embed-meta-7f2b15988549f805.yaml
- test/components/rankers/test_transformers_similarity.py
- fixes #6563 
Add `metadata_fields_to_embed` following the implementation in `SentenceTransformersDocumentEmbedder` to be able to embed metadata fields along with the content of the document. 
Added a new unit test to check the behavior. Updated existing tests for serializing the object. …
> feat: Add `meta_fields_to_embed` to `TransformersSimilarityRanker`

- haystack/components/converters/html.py
- releasenotes/notes/htmlconverter-allow-extractor-customizability-730ae129db17327a.yaml
- test/components/converters/test_html_to_document.py
- fixes #6579
- allow choosing the boilerpy3 extractor to extract the content from the HTML document
- change the default extractor to `DefaultExtractor`, which is better for generic use cases than the previous default (`ArticleExtractor`).
CI, new test.
- I documented …
> feat!: `HTMLToDocument` - allow choosing the boilerpy3 extractor

- haystack/components/connectors/__init__.py
- haystack/components/connectors/openapi_service.py
- haystack/components/converters/__init__.py
- haystack/components/converters/openapi_functions.py
- releasenotes/notes/add-rag-openapi-services-f3e377c49ff0f258.yaml
- test/components/connectors/test_openapi_service.py
- test/components/converters/test_openapi_functions.py
- test/test_requirements.txt
This PR aims to enhance the Haystack 2.x framework by enabling it to connect with OpenAPI services. This will allow Haystack to seamlessly call methods specified in an OpenAPI specification and use retrieved data in service RAG, just like paragraphs of text are used in the gen-text RAG setup.
The PR introduces new components into the Haystack codebase: 
1. `OpenAPIServiceConnector`: This connector allows invoking methods as specified by an OpenAPI service. It uses `ChatMessage` objects to determine the method to call and its parameters. The responses from the service are returned within `ChatMessage` objects.
2. `OpenAPIServiceToFunctions`: This component converts an OpenAPI service specification into a format that can be utilized for function calling with LLMs. It's a crucial component …
> feat: Add RAG based OpenAPI service integration

- haystack/components/writers/document_writer.py
- releasenotes/notes/document-writer-default-policy-693027781629fc73.yaml
- test/components/writers/test_document_writer.py
`DocumentStore` protocol default policy is `DuplicatePolicy.NONE`, this gives different Document Stores the chance to pick the default that best fit their implementation.
With this PR `DocumentWriter` default `policy` changes from `DuplicatePolicy.FAIL` to `DuplicatePolicy.NONE` too.
Run unit tests locally.
N/A …
> feat: Change `DocumentWriter` default `policy` from `DuplicatePolicy.FAIL` to `DuplicatePolicy.NONE`

- haystack/core/component/connection.py
- releasenotes/notes/fix-connect-with-same-name-5ce470f7f0451362.yaml
- test/core/pipeline/test_connections.py
Fix #6515
Change the `Pipeline.connect()` logic to correctly connect two sockets with identical name when multiple possible connections are found.
Previously if multiple input sockets were found that had a compatible type with the output socket the first input socket would be connect with the output. So the connection depended also on the order of declaration of the inputs.
Now if multiple compatible input sockets are found and one has the same name as the output socket the connection will be created between these two sockets.
I added a new unit test.
N/A
- I have updated the related …
> fix: Fix `Pipeline.connect()` when multiple compatible sockets are found

- docs/pydoc/config/others.yml
Add docs config for `others` module.
n/a
n/a
> docs: add docs config for `others` module

- .github/workflows/tests.yml
This PR should speed up `tests.yml` run time by leveraging the `cache` action to avoid installing Haystack `pip` dependencies multiple times but only once.
I didn't.
N/A …
> ci: Speed up tests.yml by caching dependencies

- test/conftest.py
- test/pipelines/test_indexing_pipeline.py
- test/pipelines/test_rag_pipelines.py
We used to have this fixture before the 2.x branching off.
I changed it a bit to reflect the way we write tests now. 
Previously it used to block all HTTP requests made in tests marked with `@pytest.mark.unit`.
Now it blocks them in tests that are NOT marked with `@pytest.mark.integration`.
> test: Add fixture to block requests in tests

- e2e/pipelines/test_rag_pipelines.py
- examples/pipelines/rag_pipeline.py
- test/components/generators/chat/test_openai.py
- test/components/generators/test_openai.py
- fixes https://github.com/deepset-ai/haystack/actions/runs/7287648714/job/19859015505
- **this is a quick fix to make the CI green again**
- however, https://github.com/deepset-ai/haystack/issues/6570 is not complete. I'm reopening it
CI
- I ran …
> chore: replace metadata w meta in tests/examples

- haystack/components/converters/txt.py
- haystack/components/converters/utils.py
- releasenotes/notes/single-metadata-txt-converter-a02bf90c60262701.yaml
- test/components/converters/test_textfile_to_document.py
- test/components/converters/test_utils.py
Adds support for single metadata dictionary input in `TextFileToDocument`. In this way, additional metadata can be added to all files processed by this component even when the length of the list of sources is unknown. …
> feat: add support for single meta dict in `TextFileToDocument`

- haystack/nodes/other/join_docs.py
- releasenotes/notes/join-docs-weighting-rrf-c52ba00a25004fd4.yaml
- test/nodes/test_join_documents.py
- test/prompt/test_prompt_model.py
- fixes #5551 by adding weighting and score normalization for reciprocal rank fusion in `JoinDocuments` node.
- Modifies calculation of RRF scores by including weights, as well as normalizing by dividing by maximum possible score.
- **Non-breaking:** providing equal weights (or not providing weights) leads to same doc ordering as before.
- Manual tests ongoing, but weighting and normalization calculations are pretty simple math.
- Node is currently configured to obligatorily perform score normalization, but can easily be revised so that normalization is optional. However, I haven't encountered a use for raw RRF scores in the wild.
- In this PR draft, raw (pre-normalization) RRF scores are each multiplied by the number of input rankings (`len(results)` in the formula `(weight * …
> feat: Weights and score normalization for `JoinDocuments` node with reciprocal rank fusion

- haystack/components/converters/html.py
- releasenotes/notes/single-meta-in-htm2document-199ea44a4ae5c02b.yaml
- test/components/converters/test_html_to_document.py
Adds support for single metadata dictionary input in `HTMLToDocument`. In this way, additional metadata can be added to all files processed by this component even when the length of the list of sources is unknown. …
> feat: support single metadata dictionary in `HTMLToDocument`

- e2e/pipelines/test_extractive_qa_pipeline.py
- e2e test for extractive QA was failing since deduplication PR: https://github.com/deepset-ai/haystack/pull/6459
- Previously all returned answers were from the top relevant Document. With deduplication, some answers are from other Documents, which caused the e2e test to fail.
Check only the correctness of the top answer.
Ran e2e test locally.  …
> test: Check only top answer in extractive QA e2e test

- haystack/components/converters/pypdf.py
- releasenotes/notes/single-meta-in-pypdf2document-99e15f1cb9f65892.yaml
- test/components/converters/test_pypdf_to_document.py
Adds support for single metadata dictionary input in `PyPDFToDocument`. In this way, additional metadata can be added to all files processed by this component even when the length of the list of sources is unknown. …
> feat: support single metadata dictionary in `PyPDFToDocument`

- haystack/nodes/prompt/invocation_layer/hugging_face.py
- haystack/nodes/ranker/sentence_transformers.py
- haystack/utils/torch_utils.py
- releasenotes/notes/ranker-model-kwargs-0f60508b69d7d46e.yaml
- test/nodes/test_ranker.py
- test/utils/test_torch_utils.py
- fixes N/A
Updates cross encoder init to take model kwargs so we can pass float16 as a loading option. Increases speed of ranking 40 docs by 4x when using float16. …
> feat: Add model kwargs to SentenceTransformersRanker

- e2e/pipelines/test_rag_pipelines.py
- examples/pipeline_loop_to_autocorrect_json.py
- examples/pipelines/rag_pipeline.py
- examples/rag/rag_self_correction.py
- examples/retrievers/in_memory_bm25_rag.py
- haystack/components/builders/dynamic_prompt_builder.py
- haystack/components/generators/__init__.py
- haystack/components/generators/chat/__init__.py
- haystack/components/generators/chat/openai.py
- haystack/components/generators/openai.py
- haystack/pipeline_utils/rag.py
- releasenotes/notes/rename-gpt-generators-f25011d251fafd6d.yaml
- test/components/generators/chat/test_openai.py
- test/components/generators/test_openai.py
The purpose of this pull request is to rename GPT generators within the Haystack framework. The change aims to update the naming convention of these generators to align with current naming standards. 
- fixes https://github.com/deepset-ai/haystack/issues/6587
The decision to rename the class from GPTChatGenerator to OpenAIChatGenerator is rooted in the need for compatibility with various providers and models. Unlike the original name, which specifically referenced 'GPT', the new name, OpenAIChatGenerator, is more inclusive and accurately reflects the class's capability to work seamlessly with a diverse range of providers such as together.ai, anyscale, and deepinfra.com, as well as with different AI models like mixtral. 
The pull request includes several modifications across various files …
> chore: Rename GPT generators, deprecate old names

- .github/workflows/tests.yml
- [the first Tika integration test is often failing in MacOs](https://github.com/deepset-ai/haystack/actions/runs/7290308355/job/19867245664)
- this happens because when the test begins, the service is not yet available, so it converts one file instead of 2
- try to add a healthcheck
CI
~~There are conflicting resources on the healthcheck topic, so I'm not sure it works~~
Edit: we can't rely on github services (don't run on MacOs), so I'm manually setting the docker healthcheck... …
> ci: make Tika service smoothly run on MacOs

- examples/retrievers/in_memory_bm25_rag.py
- haystack/components/builders/dynamic_chat_prompt_builder.py
- haystack/components/embedders/hugging_face_tei_document_embedder.py
- haystack/components/embedders/openai_document_embedder.py
- haystack/components/embedders/openai_text_embedder.py
- haystack/components/embedders/sentence_transformers_document_embedder.py
- haystack/components/rankers/meta_field.py
- haystack/pipeline_utils/indexing.py
- releasenotes/notes/change-metadata-to-meta-0fada93f04628c79.yaml
- test/components/embedders/test_hugging_face_tei_document_embedder.py
- test/components/embedders/test_openai_document_embedder.py
- test/components/embedders/test_openai_text_embedder.py
- test/components/embedders/test_sentence_transformers_document_embedder.py
- test/components/rankers/test_metafield.py
- test/components/routers/test_conditional_router.py
- part of #6570
- continues the work done in #6605 and #6612
- change `metadata` to `meta`
- (in some cases, I may gone a little too far with the renaming, but probably it's not a problem)
CI …
> refactor!: rename all remaining `metadata` to `meta`

- .github/workflows/tests.yml
- despite my try (#6619), Tika tests on macOS keep failing: https://github.com/deepset-ai/haystack/actions/runs/7338857067/job/19982190045
- macOS integration tests are significantly slower compared to other platforms. This also happens because we install Docker, which is only needed for Tika tests
- skip Tika tests on macOS, as we already do for Windows
I temporarily added this branch to those to be tested in the CI, so we can see if everything is OK.
Once the tests pass, I will remove this branch from the list.
**Update**:
- the tests ran correctly and significantly faster than before (7m instead of 10m): https://github.com/deepset-ai/haystack/actions/runs/7346846952/job/20002436166?pr=6654
- (I removed this branch from those to be tested) …
> ci: skip Tika tests in macOS integration tests

- pyproject.toml
- Haystack is now compatible with the OpenAI client (openai package) >1 (#6584)
- Haystack does not work with openai<1
- the first stable release of openai>1 is 1.1.0 (1.0.0 was buggy)
- pin openai>=1.1.0
- this prevents people who already have openai<1 installed from running `pip install haystack-ai` and getting incompatibility bugs
Local test with openai==1.1.0 …
> build: pin openai>=1.1.0

- e2e/pipelines/test_pipeline_topologies.py
- e2e/pipelines/test_standard_pipelines.py
- examples/web_lfqa.py
- examples/web_qa.py
- haystack/nodes/prompt/invocation_layer/azure_open_ai.py
- haystack/nodes/prompt/invocation_layer/open_ai.py
- haystack/nodes/sampler/top_p_sampler.py
- test/pipelines/test_standard_pipelines.py
- test/prompt/conftest.py
- test/prompt/invocation_layer/test_openai.py
- test/prompt/test_prompt_node.py
- test/utils/test_openai_utils.py
- fixes #6589
Replace all usage of the deprecated `text-davinci-003` model with the `gpt-3.5-turbo-instruct` model
CI. ~~I expect some tests to fail because of slightly different LLM outputs.~~
I opened a [PR](https://github.com/deepset-ai/haystack-tutorials/pull/265) for updating the tutorials too. No updates are needed for 2.0. …
> fix: Replace deprecated `text-davinci-003` model with `gpt-3.5-turbo-instruct` model

- pyproject.toml
No issue.
The transformers dependency has a critical vulnerability that is fix from 4.36.0 onwards. https://github.com/advisories/GHSA-v68g-wm8c-6x7j
Not tested.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTI …
> chore: bump transformers version to 4.36.2 with vulnerability fix

- haystack/components/builders/dynamic_chat_prompt_builder.py
- haystack/components/builders/dynamic_prompt_builder.py
- test/components/builders/test_dynamic_chat_prompt_builder.py
- test/components/builders/test_dynamic_prompt_builder.py
This pull request updates the dynamic prompt builders examples, making them more user-friendly and comprehensive. The example switched from GPTChatGenerator to OpenAIChatGenerator to showcase the use of the OpenAI API for text generation. It also integrates the functionality of the new DynamicPromptBuilder class, demonstrating how to use runtime variables and connect them to the DocumentProducer component in the Haystack pipeline.
- Updated the examples in the `haystack/components/builders/dynamic_chat_prompt_builder.py` and `haystack/components/builders/dynamic_prompt_builder.py` files to use the OpenAI API instead of the GPT API.
- Added a new test, `test_example_in_pipeline`, in the `test/components/builders/test_dynamic_prompt_builder.py` file to demonstrate the usage of runtime …
> Update prompt builders examples

- haystack/components/embedders/__init__.py
- haystack/components/embedders/azure_document_embedder.py
- haystack/components/embedders/azure_text_embedder.py
- releasenotes/notes/add-azure-embedders-fd5f4fbcab0e1c48.yaml
- test/components/embedders/test_azure_document_embedder.py
- test/components/embedders/test_azure_text_embedder.py
Add new embedding components that leverage Azure's cognitive services for text and document embedding. These new components are intended to provide users with more embedding options and utilize Azure's models.
The main changes introduced in the `azure_embedders` branch include:
1. **Addition of Azure Embedders**: The `AzureOpenAITextEmbedder` and `AzureOpenAIDocumentEmbedder` classes have been added. These are similar to their OpenAI counterparts but use Azure API for embedding texts and documents.
2. **Modifications in `__init__.py`**: The `__init__.py` file within the embedders directory has been modified to include the newly added Azure embedder classes.
3. **Unit Tests**: New unit tests have been added for both the `AzureOpenAITextEmbedder` and `AzureOpenAIDocumentEmbedder` to ensure …
> feat: Add Azure embedders support

- haystack/nodes/summarizer/transformers.py
- haystack/utils/torch_utils.py
- releasenotes/notes/summarizer-kwargs-speed-148714d268773f60.yaml
- test/nodes/test_summarizer.py
- fixes N/A
- Needs PR https://github.com/deepset-ai/haystack/pull/6627 for the `extract_torch_dtype` method
- fixes slow inference and indexing times for a client's pipeline that uses the TransformerSummarizer
- use batching in the predict method since multiple documents are usually passed at inference time
- allow the model to be loaded in torch.float16 by adding pipeline_kwargs to the init method …
> feat: Add pipeline_kwargs to TransformersSummarizer

- test/components/embedders/test_openai_document_embedder.py
- test/components/embedders/test_openai_text_embedder.py
- test/pipelines/test_indexing_pipeline.py
- test/pipelines/test_rag_pipelines.py
Skip integration tests if `OPENAI_API_KEY` is not set.
PR opened by external contributors don't have access to CI secrets, so they're always going to fail.
This change will prevent those failures.
Example of PR check failing 👇 
https://github.com/deepset-ai/haystack/actions/runs/7445097734/job/20253017272?pr=6680
Let's update #6680 after this is merged.
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my …
> test: Skip integration tests if env var is missing

- test/components/embedders/test_openai_document_embedder.py
- test/components/embedders/test_openai_text_embedder.py
- test/pipelines/test_indexing_pipeline.py
- test/pipelines/test_rag_pipelines.py
Fix `skipif` not skipping tests if `OPENAI_API_KEY` is set to an empty string.
Run tests locally after settings `OPENAI_API_KEY` to empty string.
N/A
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#instal …
> test: Fix skipif with empty env var

- haystack/components/converters/tika.py
- releasenotes/notes/single-meta-in-tikaconverter-89b454c451a2ed93.yaml
- test/components/converters/test_tika_doc_converter.py
Adds support for single metadata dictionary input in `TikaDocumentConverter`. In this way, additional metadata can be added to all files processed by this component even when the length of the list of sources is unknown. …
> feat: support single metadata dictionary in `TikaDocumentConverter`

- haystack/components/converters/azure.py
- releasenotes/notes/single-meta-in-azureconverter-ce1cc196a9b161f3.yaml
- test/components/converters/test_azure_ocr_doc_converter.py
Adds support for single metadata dictionary input in `AzureOCRDocumentConverter`. In this way, additional metadata can be added to all files processed by this component even when the length of the list of sources is unknown. …
> feat: support single metadata dictionary in `AzureOCRDocumentConverter`

- haystack/components/caching/cache_checker.py
- releasenotes/notes/cache_checker_output_type-0b05e75ca41aab61.yaml
- test/components/caching/test_url_cache_checker.py
- fixes n/a
- Modify the output type of `CacheChecker` from `List[Any]` to `List` to make it possible to connect it in a Pipeline.
Unit tests
n/a
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installati …
> feat: Tweak `CacheChecker` output type

- docs/pydoc/config/caching.yml
- docs/pydoc/config/classifier.yml
- docs/pydoc/config/joiner.yml
- docs/pydoc/config/others.yml
- docs/pydoc/config/whisper.yml
Updated the pages to come in alphabetical order.
Renamed Language Classifiers to simply Classifiers (futureproofing).
Updated CacheChecker name.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installatio …
> docs: reorder and rename Classifier and CacheChecker files

- .github/workflows/tests.yml
- haystack/core/component/component.py
- releasenotes/notes/fix-descriptor-__dict__-doesnt-apply-to-bf6d47872345ed24.yaml
- no issue, reported offline
Steps to reproduce:
```
In [1]: from haystack.components.builders import AnswerBuilder
In [2]: a = AnswerBuilder()
In [3]: dir(a)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 dir(a)
TypeError: descriptor '__dict__' for 'AnswerBuilder' objects doesn't apply to a 'AnswerBuilder' object
```
When programmatically creating the final class in the `_component` decorator, while building the class namespace skip `__dict__` and `__weakref__` so that Python will recreate them in the correct way.
Manually tested + unit/integration tests in CI
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIB …
> fix: Fix error when calling `dir()` on a component instance

- test/components/generators/test_hugging_face_local_generator.py
- fixes https://github.com/deepset-ai/haystack/actions/runs/7501830147/job/20423561987
- related to #6534 
rename `model_name_or_path` to `model` in `HuggingFaceLocalGenerator` test …
> fix: rename `model_name_or_path` to `model` in `HuggingFaceLocalGenerator` test

- haystack/components/audio/whisper_local.py
- haystack/components/audio/whisper_remote.py
- releasenotes/notes/rename-model-param--transcribers-71dbe7cfb86950e0.yaml
- test/components/audio/test_whisper_local.py
- test/components/audio/test_whisper_remote.py
- related to #6534 
- Rename `model_name` or `model_name_or_path` to `model` in all Transcriber classes.
Local tests run, CI
n/a …
> feat!: Rename `model_name` or `model_name_or_path` to `model` in all Transcriber classes

- e2e/pipelines/test_eval_rag_pipelines.py
Failing e2e test.
Rename `model_name_or_path` to `model` for `HuggingFaceLocalGenerator`, to align the test to the changes introduced in this PR: https://github.com/deepset-ai/haystack/pull/6715 …
> fix: fix leftover `model_name_or_path` param in e2e tests

- haystack/components/builders/prompt_builder.py
- haystack/core/component/component.py
- releasenotes/notes/set-input-type-328589ee51ffa21b.yaml
Add method to set a Component input type with default value. 
I tested it manually.
This is a necessary improvement for the Pipeline run refactoring that is coming up. …
> feat: Add method to set a Component input type with default value

- haystack/components/rankers/transformers_similarity.py
- releasenotes/notes/rename-model-param-rankers-be3d6163597e0a9b.yaml
- test/components/rankers/test_transformers_similarity.py
- related to #6534 
- Rename `model_name_or_path` to `model` in `TransformersSimilarityRanker`.
Local tests run, CI
n/a
> feat!: Rename `model_name_or_path` to `model` in `TransformersSimilarityRanker`

- haystack/core/pipeline/draw/draw.py
- haystack/core/pipeline/draw/mermaid.py
- haystack/core/pipeline/pipeline.py
- releasenotes/notes/highlight-optional-conns-in-draw-cf107ee210b7b8e7.yaml
- related to https://github.com/deepset-ai/haystack/issues/6723
Modify the output of `Pipeline.draw()` to:
- add a ` (opt.)` suffix to optional connections.
- in Mermaid, make the relative arrow dotted instead of solid.
Example before:
Example after:
Manual testing
n/a …
> feat: Highlight optional connections in `Pipeline.draw()`

- haystack/components/generators/hf_utils.py
- haystack/components/generators/hugging_face_local.py
- test/components/generators/test_hugging_face_local_generator.py
The changes in the pull request serve to improve the modularization and robustness of the stop words criteria feature in the Haystack library. The motivation behind these adjustments is to ensure that the functionality for stopping text generation when specific words are produced is localized, easier to maintain, and less prone to errors caused by invalid tokenizer usage or missing special tokens in the tokenizer. By encapsulating this functionality into the `hf_utils` module and explicitly checking for a valid tokenizer and required special tokens, the quality of the Haystack library is enhanced, and developers can more reliably integrate stopping criteria into their text generation processes.
- Moved the `StopWordsCriteria` class from `hugging_face_local.py` to `hf_utils.py`.
- This …
> refactor: Extract HF stop words handling in `hf_utils.py`

- haystack/components/rankers/meta_field.py
- releasenotes/notes/metafieldranker_sort-order_refactor-2000d89dc40dc15a.yaml
- test/components/rankers/test_metafield.py
- partially addresses the RecentnessRanker in issue https://github.com/deepset-ai/haystack/issues/6673. Only partially because this does not introduce the `infer_type` boolean discussed with @masci that would toggle whether we try to auto detect the type of the specified meta_field if all values of that meta field value are strings. Instead in this PR we focused on robustness of the MetaFieldRanker to fail less often by handling more edge cases and writing appropriate warning messages for them. 
- Makes the MetaFieldRanker more robust. Specifically to prevent the ranker from throwing an error if one or more of the documents doesn't contain the specific meta data field. Now those documents will be ignored for ranking purposes and placed at the end of the ranked list so we don't completely …
> feat: MetaFieldRanker update

- haystack/components/builders/dynamic_chat_prompt_builder.py
- haystack/components/builders/dynamic_prompt_builder.py
- related to https://github.com/deepset-ai/haystack/issues/6534
Fix the content of a couple of docstrings from `model_name` to simply `model`, as mentioned in the linked issue. …
> chore: fix docstrings using `model_name` instead of `model`

- haystack/components/extractors/named_entity_extractor.py
- releasenotes/notes/rename-model-param-ner-dce7536f2e7866fe.yaml
- test/components/extractors/test_named_entity_extractor.py
- related to #6534 
- Rename `model_name_or_path` to `model` in `NamedEntityExtractor`.
Local tests run, CI
n/a
> feat!: rename `model_name_or_path` to `model` in `NamedEntityExtractor`

- haystack/components/generators/hugging_face_local.py
The pull request addresses an issue related to lazy importing within the `HuggingFaceLocalGenerator` of the Haystack library. Specifically, it fixes an improper import of `StopWordsCriteria` that potentially causes failures when the component is utilized.
- A single line has been changed in `haystack/components/generators/hugging_face_local.py`.
- The `StopWordsCriteria` import statement has been moved from the global scope to within the function body, making it a lazy import.
- The change ensures that the `StopWordsCriteria` is only imported when necessary.
- Manually by running a docker image
- This change should not affect the overall functionality of the `HuggingFaceLocalGenerator`, but instead improve the reliability of imports.
- Ensure that this change does not negatively interact …
> chore: Fix lazy import in HuggingFaceLocalGenerator

- haystack/components/preprocessors/document_splitter.py
- releasenotes/notes/add-split-by-page-to-DocumentSplitter-63232c17d858d787.yaml
- test/components/preprocessors/test_document_splitter.py
- fixes #6707 
- The new split_by value, 'page', has been introduced in the DocumentSplitter to enable users to split documents based on the "\f" character, facilitating the preservation of context and allowing for more flexible chunking options.
> feat: added split by page to `DocumentSplitter`

- haystack/components/generators/hugging_face_local.py
- haystack/components/rankers/transformers_similarity.py
- haystack/components/readers/extractive.py
- haystack/utils/hf.py
Moves some common code used to serialize/deserialize HF model args to a separate utility submodule.
> refactor: Move HF-specific model serde code to a new submodule.

- haystack/components/converters/pypdf.py
- haystack/components/converters/utils.py
- releasenotes/notes/pypdf-page-breaks-b6842d93f4c69185.yaml
- test/components/converters/test_pypdf_to_document.py
- fixes https://github.com/deepset-ai/haystack/issues/6706
In Haystack v1 we learned that being able to keep track of the source page number that a Document comes from when converting a PDF into Haystack Document is extremely useful for down stream applications. In particular when users want to easily retrieve the original PDF page that is being referenced in an answer or retrieved Haystack Document.
We accomplished this in Haystack v1 by counting page breaks "\f" in the text outputted by the v1 PDFToText converters. However, our current DefaultConverter in v2 for the PyPDFToDocument does not count empty pages or keeps the page breaks. 
So in this PR we:
- updated the `DefaultConverter` to add back in page breaks
- count empty pages so we can correctly count the total number of pages in …
> feat: Add page breaks to default PDF to Document converter

- haystack/version.py
- releasenotes/notes/fix-version-47afaec913788a01.yaml
- fixes #6759
Set `__version__` to `"main"` if `haystack-ai` is not installed.
This can happen when using a local clone of the repository for development purposes.
Manually locally.
N/A …
> Fix `__version__` handling

- haystack/dataclasses/document.py
- releasenotes/notes/speedup-import-b542f7a8323ef376.yaml
`document.py` was really slow to import as it was importing the whole `numpy` and `pandas` packages.
This PR changes the import to only import `pandas.DataFrame`, `pandas.read_json` and `numpy.ndarray`.
On my local machine calling `import haystack` I saw a speed change from 4.35 seconds to 0.676 seconds.
I profiled `import haystack` using [`cProfile`](https://docs.python.org/3.8/library/profile.html) and visualized the report using [SnakeViz](https://jiffyclub.github.io/snakeviz/).
```
echo "import haystack" >> my_program.py
python -m cProfile -o my_report.prof my_program.py
snakeviz my_report.prof
```
N/A …
> perf: Speed up `Document` dataclass import

- haystack/components/generators/chat/__init__.py
- haystack/components/generators/chat/hugging_face_local.py
- haystack/components/generators/hf_utils.py
- releasenotes/notes/add-hugging-face-chat-local-5fe7a88e24fde11b.yaml
- test/components/generators/chat/test_hugging_face_local.py
The addition in this PR aims to enhance the Haystack library by enabling local runtime text generation for chat models from the Hugging Face model hub. It empowers users to generate chat responses using chat-based models and provides customization through generation parameters, stop words, and chat templates.
- fixes https://github.com/deepset-ai/haystack/issues/6172
- Added `HuggingFaceLocalChatGenerator` for local runtime chat response generation.
- Extended `__init__.py` under `haystack/components/generators/chat/` to include the new chat generator.
- Implemented `hugging_face_local.py` containing the generator class with initializing, serialization, and run methods.
- Adjusted `hf_utils.py` with supporting classes and utility functions for the chat generator.
- Created a release note …
> feat: Add `HuggingFaceLocalChatGenerator`

- rest_api/pyproject.toml
Latest `fastapi` version breaks `rest_api`.
More info in [this discussion](https://github.com/deepset-ai/haystack/discussions/6766).
> Pin `fastapi` version in `rest_api`

- haystack/components/connectors/openapi_service.py
- test/components/connectors/test_openapi_service.py
This change modifies the `run` method in `openapi_service.py` to handle service responses better. Instead of directly converting the service response to a `ChatMessage` object, the code now accesses the raw JSON data of the response and serializes it into a string before creating the `ChatMessage` object. This approach avoids issues related to (de)serialization and allows us to manipulate the raw JSON as needed. 
A concrete need for this change request arose when a demo application required only a partial JSON service response. To save tokens and preserve the precious LLM context window, users can inject the subtree of JSON response into a ChatMessage instead of packing the entire JSON response into a message. Previously, this was not feasible as we mistakenly serialized an openapi3 model …
> feat: Improve OpenAPIServiceConnector service response serialization

- haystack/components/generators/chat/hugging_face_local.py
An import got moved outside of the lazy guarded section. Let's move HFTokenStreamingHandler to a guarded import.
> chore: Move import to lazy import section

- haystack/components/generators/chat/hugging_face_local.py
It seems that Python evaluates annotations in method signatures when the class/function gets loaded. In this case, HuggingFaceLocalChatGenerator is loaded from the package init file. This is obviously different from how the function's or method's code is called when the lazy import checks are executed. 
After I added forward references for type hints ("PreTrainedTokenizer" and "PreTrainedTokenizerFast"), the NamedError didn't happen, and everything works as intended in env where transformers are not installed. 
Ther error trace was:
```
File "/opt/venv/lib/python3.10/site-packages/haystack/components/generators/chat/__init__.py", line 1, in <module>
from haystack.components.generators.chat.hugging_face_local import HuggingFaceLocalChatGenerator
File …
```
> chore: Use forward references for type hints in HuggingFaceLocalChatGenerator method, avoid NameError

- .gitignore
Noticed .haystack_debug was generated as I was running the getting started sample.
> add .haystack_debug to .gitignore

- proposals/text/6784-integrations-for-eval-framworks.md
Proposal for implementing third-party LLM evaluation frameworks in `haystack-core-integrations`.
[Rendered](https://github.com/shadeMe/haystack/blob/proposal/model-based-eval-components/proposals/text/6784-integrations-for-eval-framworks.md).
- I …
> proposal: Integration of 3rd party evaluation frameworks

- .github/workflows/tests.yml
- haystack/document_stores/mongodb_atlas.py
- releasenotes/notes/mongodb-vector-search-2f40a9c67eed6e7c.yaml
- test/document_stores/test_mongodb_atlas.py
- fixes #6632
- fixes #6643
- Added an optional parameter `vector_search_index` to the init of `MongoDBAtlasDocumentStore`
- Update the implementation of `query_by_embedding` to use MongoDB Atlas Vector Search
- Throw an error if `query_by_embedding` is called but no `vector_search_index` is set, which is required to run vector search
Tested with a M0 free tier cluster and the example code from the issue. As expected, relevant documents are returned after the fix.
Database with a vector search index needs to be configured through the Atlas web UI following their [docs](https://www.mongodb.com/docs/atlas/atlas-vector-search/create-index/#std-label-avs-create-index):
Unfortunately `create_search_index` and `list_search_indexes` require a MongoDB server version 7.0+ Atlas cluster. The free …
> fix: MongoDB Atlas Vector Search

- haystack/components/joiners/document_joiner.py
- releasenotes/notes/weights-normalize-docjoin-rrf-v2-9cad33012fe90a55.yaml
- test/components/joiners/test_document_joiner.py
- fixes #6617 by adding weighting and score normalization for the `DocumentJoiner` node with reciprocal rank fusion.
- Add weighting for `DocumentJoiner` node with reciprocal rank fusion.
- Add score normalization for `DocumentJoiner` node with reciprocal rank fusion.
- Testing pending.
> feat: Weights and score normalization for DocumentJoiner with reciprocal rank fusion

- haystack/components/rankers/transformers_similarity.py
- releasenotes/notes/ranker-prefix-bfaf09cd7da0852d.yaml
- test/components/rankers/test_transformers_similarity.py
- Add query and document prefix options for the TransformerSimilarityRanker, similar to what we have for our Embedders
- added a new unit test
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIB …
> feat: Add query and document prefix options for the TransformerSimilarityRanker

- releasenotes/config.yaml
- releasenotes/notes/speedup-import-b542f7a8323ef376.yaml
We found that `prelude_section_name` is not currently configured correctly.
So, Reno does not generate release notes for the `prelude` section.
- Fix the configuration and the template, renaming the `prelude` section to `highlights`
Not tested.
- …
> chore: improve Reno configuration

- haystack/core/pipeline/pipeline.py
We should add a lint for this common error, incidentally. If there's one available, that is.
> fix: Fix missing format string prefixes in `pipeline.py`

- docs/pydoc/config/generator.yml
- haystack/components/generators/utils.py
- releasenotes/notes/rename-streaming-callback-f4e6653c0aac8765.yaml
- test/components/generators/chat/test_azure.py
- test/components/generators/chat/test_openai.py
- test/components/generators/test_azure.py
- test/components/generators/test_openai.py
- test/components/generators/test_utils.py
- fixes https://github.com/deepset-ai/haystack/issues/6830
the `default` in `default_streaming_callback` is confusing, this function is the go-to-helper you use when you want to quickly print the generated tokens as they come, but it's not used by default.
- I …
> refact: Rename helper function

- haystack/core/pipeline/pipeline.py
Simplify how `Pipeline` instances are compared.
I didn't add a release notes as this doesn't change the behaviour of `__eq__`.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#ins …
> refactor: Simplify `Pipeline.__eq__` logic

- README.md
Remove mention of a specific 1.x release in the README.
(This information may become outdated in a short time).
> README: remove the mention to 1.23

- haystack/core/component/component.py
- haystack/core/pipeline/pipeline.py
- releasenotes/notes/components-reuse-ccc5f2d4b9d7f9ff.yaml
- test/core/pipeline/test_connections.py
- test/core/pipeline/test_distinct_loops_pipeline.py
- test/core/pipeline/test_pipeline.py
- fixes #6431
Add `__haystack_pipeline_owned__` field in all `Component` instances. Defaults to `False`.
Change `Pipeline.add_component()` to fail if the `Component` instance is already used in another `Pipeline`. The method will also set `__haystack_pipeline_owned__` to `True`.
Added a unit test.
N/A …
> feat: Change `Pipeline.add_component` to fail when reusing `Component` instances

- haystack/utils/__init__.py
- haystack/utils/auth.py
- releasenotes/notes/auth-policy-for-components-d576a28135a224db.yaml
- releasenotes/notes/secret-handling-for-components-d576a28135a224db.yaml
- test/utils/test_auth.py
- Fixes https://github.com/deepset-ai/haystack/issues/6851
Expose a `Secret` type to provide common logic for any component that requires a secret for authentication, with the following variants:
- `token` - Use a string literal.
- `env_var` - Resolve the token from the passed environment variable(s).
Token-based secrets are not serializable, i.e., they'll raise an error when serializing a component that uses it. Env vars are serializable.
```python
@component
class MyComponent:
def __init__(self, api_key: Optional[Secret] = None, **kwargs):
self.api_key = api_key
self.backend = None
def warm_up(self):
self.backend = SomeBackend(api_key=self.api_key.resolve_value() if self.api_key else None, ...)
def to_dict(self):
return default_to_dict(self, api_key=self.api_key.to_dict() if …
```
> feat: Implement `Secret` for structured authentication

- test/components/readers/test_extractive.py
- fixes failing CI: https://github.com/deepset-ai/haystack/actions/runs/7727442595/job/21066661586?pr=6857
Fix Roberta test for ExtractiveReader. Due to the recent transformers upgrade, the score is very slightly off and breaks the test.
CI
- I …
> fix: add some tolerance to ExtractiveReader Roberta test

- haystack/dataclasses/byte_stream.py
- releasenotes/notes/meta-in-bytestream-a29816c919c0be5a.yaml
- test/dataclasses/test_byte_stream.py
- fixes [#6217](https://github.com/deepset-ai/haystack/issues/6217)
- Add `meta` parameter to `ByteStream.from_file_path()` and `ByteStream.from_string()`.
- Improve docstrings
- Add tests
Unit tests
n/a …
> feat: Allow setting metadata for `ByteStream` when created from file or from string

- haystack/core/component/component.py
- releasenotes/notes/fix-components-autocompletion-a2d87708309262b6.yaml
This PR fixes auto completion for most Python language servers. 
Most of them are not able to understand the types of classes decorated with `@component` and would treat all instances as `Any`. This happens because we recreate the class dynamically to use a custom metaclass in the `@component` decorator.
Adding the type hint fixes the issue and now the correct type is infered.
I tested it manually in VS Code.
N/A …
> fix: Fix language servers never working with Components

- pyproject.toml
Add `flaky` dependency to mark flaky tests so they're automatically retried when failing.
More info on the library:
https://github.com/box/flaky
Nothing to test.
N/A
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRI …
> test: Add flaky as dev dependency

- haystack/components/generators/chat/hugging_face_tgi.py
The default model for the HuggingFaceTGIChatGenerator has been changed to HuggingFaceH4/zephyr-7b-beta. This update addresses the removal of the previously used model, meta-llama/Llama-2-13b-chat-hf, from the free tier and the additional requirement for license signing, which increased user friction.
> chore: Change HuggingFaceTGIChatGenerator default model to HuggingFaceH4/zephyr-7b-beta

- haystack/core/pipeline/pipeline.py
- releasenotes/notes/rename-connect-arguments-2d99d9d5cbe9ab4c.yaml
`Pipeline.connect()` arguments have renamed for clarity. This is a breaking change if `connect` was called
with keyword arguments only.
`connect_from` and `connect_to` arguments have been renamed respectively to `sender` and `receiver`.
The behaviour of `Pipeline.connect()` is not changed.
This is overdue since we decided on the name convention of `sender` and `receiver`.
N/A …
> refactor: Rename `Pipeline.connect()` arguments

- haystack/document_stores/weaviate.py
- releasenotes/notes/weaviate-handle-empty-list-8d3432080f8bfefd.yaml
- test/document_stores/test_weaviate.py
- fixes #6550
During the conversion of Haystack docs to Weaviate docs,
to determine the type of a field, we were accessing the first element of a list that can also be empty.
https://github.com/deepset-ai/haystack/blob/07950d3961e6536c80b1f0928543cad41950b97b/haystack/document_stores/weaviate.py#L538
Now we skip this access if the list is empty.
CI, new test …
> fix: make Weaviate DS handle fields consisting in empty lists

- haystack/components/builders/prompt_builder.py
- releasenotes/notes/prompt-builder-default-value-95383dd6d17a05d5.yaml
This PR changes `PromptBuilder` so that all its inputs have a default value of `""`.
If `PromptBuilder` inputs are received from a cycle and are meant to optional, the `PromptBuilder` would never run waiting for those inputs. Settings a default value of `""` to all inputs makes sure that the `PromptBuilder` will run even with partial inputs that are not going to be received.
We manually tested a `Pipeline` that has a cycle that connects back in a `PromptBuilder`
N/A
- I've …
> fix: Change `PromptBuilder` to have default values for all inputs

- haystack/document_stores/pinecone.py
- releasenotes/notes/pinecone-change-dummy-vector-b9fa90f2de6fb846.yaml
- fixes #6931 
- similar to https://github.com/deepset-ai/haystack-core-integrations/issues/300
- I changed the value of the dummy vector
- I also refactored the code to create this dummy vector once at init time (to avoid duplication)
CI
Unfortunately, our CI tests are based on an outdated mock, which is also the reason why this problem never emerged until a user reported it. (in haystack-core-integrations, things are way better)
So I reproduced the issue and tested the change locally using this code:
```python
from haystack.utils import fetch_archive_from_http
from haystack.utils import convert_files_to_docs
from haystack.nodes import PreProcessor
from haystack.document_stores.pinecone import PineconeDocumentStore
from haystack.nodes import EmbeddingRetriever
doc_dir = "data/tutorial8" …
```
> Pinecone: change dummy vector

- haystack/core/component/component.py
- haystack/core/component/sockets.py
- releasenotes/notes/component-repr-a6486af81530bc3b.yaml
- test/core/component/test_component.py
- test/core/component/test_sockets.py
- fixes #6779
This PR changes the `@component` decorator so all Components have a `__repr__` method that returns a clear representation of their I/O sockets.
I also changed a bit `Sockets.__repr__` to avoid infinite recursion.
I added new tests.
N/A …
> feat: Add `__repr__` method to all Components

- haystack/nodes/other/route_documents.py
- releasenotes/notes/route-documents-metadata-values-types-7b6bdbc916d2624b.yaml
- test/nodes/test_route_documents.py
The types of meta data values accepted by RouteDocuments was unecessarily restricted to string types. This causes validation errors (for example when loading from a yaml file) if a user tries to use a boolean type for example. 
added new unit tests showing that the sorting works with boolean and int types …
> fix: Update Route docs validation to allow more types 

- haystack/components/extractors/named_entity_extractor.py
> docs: Add missing docstrings to `NamedEntityExtractor`

- .github/workflows/tests.yml
- fixes #6882
Change how the dependencies cache key is generated to use the `pyproject.toml` and `test_requirements.txt` files instead of `github.run_attempt`.
Using `github.run_attempt` is problematic as it changes with partial reruns of a workflow, so the workflow would fail cause of missing dependencies and require a full rerun.
This change makes it possible to partially rerun the workflow.
Manually triggered workflow:
https://github.com/deepset-ai/haystack/actions/runs/7846212021
N/A
- I added unit tests and updated …
> ci: Use better cache key for dependencies in tests.yml
