deepset-ai/haystack

haystack/components/converters/__init__.py
haystack/components/converters/output_adapter.py
releasenotes/notes/add-output-adapter-5fab4cfcb0218925.yaml
test/components/converters/test_output_adapter.py

Part of https://github.com/deepset-ai/haystack/issues/6938
Introduces a new `OutputAdapter` component to facilitate ease of the data flow between components within a pipeline. Its purpose is to transform the output from one component to align with the expected input of a subsequent component. This capability is particularly valuable when integrating components with mismatched interfaces, enhancing the pipeline design's modularity and flexibility.
- partially fixes https://github.com/deepset-ai/haystack/issues/6923
- Added `OutputAdapter` to `haystack/components/converters/__init__.py` to make it available as a component.
- Created a new file `output_adapter.py` implementing the `OutputAdapter` class, which includes adaptation logic utilizing Jinja2 template expressions.
- Introduced tests …

feat: Add OutputAdapter

---

haystack/components/rankers/meta_field.py
releasenotes/notes/metafieldranker-meta-value-type-365ff1bdb412257b.yaml
test/components/rankers/test_metafield.py

- resolves the RecentnessRanker in issue https://github.com/deepset-ai/haystack/issues/6673 
Add a new variable called `meta_value_type` that allows a user to parse the meta value into the data type specified if the meta value is a string. For example, if we specified `meta_value_type="date"` then for the meta value `"date": "2015-02-01"` we would parse the string into a datetime object. However, when returning the documents we still return the documents with their original meta data so the parsing is only used for sorting. 
The available options are:
- 'float' will parse the meta values into floats.
- 'int' will parse the meta values into integers.
- 'date' will parse the meta values into datetime objects.
- 'None' (default) will do no parsing.
- Added unit tests
- I have read the …

feat: Meta field ranker add `meta_value_type`

---

haystack/components/generators/utils.py

We prematurely removed utils:
- serialize_callback_handler
- deserialize_callback_handler
They are used in [haystack-core-integrations ](https://github.com/deepset-ai/haystack-core-integrations) generators and need a smoother transition.

fix: Reintroduce serialize_callback_handler and deserialize_callback_handler

---

haystack/components/converters/openapi_functions.py
test/components/converters/test_openapi_functions.py

The pull request addresses the need to make `system_messages` optional within the `OpenAPIServiceToFunctions` component's `run` method. This allows for flexibility in case system messages are not required or available when processing OpenAPI specifications. 
- Modified method signature for `run` to make `system_messages` an optional parameter with a default value of `None`.
- Updated logic to handle the absence of system messages, initializing `system_messages` as a list of empty strings if not provided.
- Altered creation of document metadata to conditionally include `system_message` only if it is available.
- The feature allows users to invoke the `OpenAPIServiceToFunctions`'s `run` method without providing system messages:
```python
service = OpenAPIServiceToFunctions()
result = …
```

feat: Make system_messages optional in OpenAPIServiceToFunctions run

---

docs/pydoc/config/eval_api.yml

Part of #6903
Add configs to generate documentation for new eval Components.
Nothing to test.
Depends on #6983

docs: Add eval Components docs config

---

haystack/nodes/preprocessor/preprocessor.py
releasenotes/notes/preprocessor-split-by-page-2de0b59175f4203e.yaml
test/nodes/test_preprocessor.py

Add `split_by="page"` to the preprocess (like we have in Haystack v2). Will be needed for a project in deepset Cloud. 
Added unit tests.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING. …

feat: Add split_by="page" to the preprocessor

---

haystack/components/eval/sas_evaluator.py
test/components/eval/test_sas_evaluator.py

- Part of #6903
Remove preprocessing in `SASEvaluator` as we're going to use the `TextCleaner` component from #6997.
Add `warm_up()` method to cache the model used for evaluation.
Move `labels` from `__init__` to `run`.
I updated unit and integration tests.
This stems from feedback received in PR #6980. …

refactor: Refactor `SASEvaluator`

---

haystack/components/preprocessors/__init__.py
haystack/components/preprocessors/text_cleaner.py
releasenotes/notes/text-cleaner-eee0eecbdec21427.yaml
test/components/preprocessors/test_text_cleaner.py

- Part of #6903
Add `TextCleaner` component. This is mostly useful between a generator and an evaluator to cleanup the generated LLM response.
This stems from feedback received in PR #6980. …

feat: Add `TextCleaner` component

---

haystack/components/eval/__init__.py
haystack/components/eval/statistical_evaluator.py
test/components/eval/test_statistical_evaluator.py

- Part of #6903
Remove preprocessing in `StatisticalEvaluator` as we're going to use the `TextCleaner` component from #6997.
Move `labels` from `__init__` to `run`.
I updated unit tests.
This stems from feedback received in PR #6980.
- I ran …

refactor: Refactor `StatisticalEvaluator`

---

haystack/components/embedders/openai_text_embedder.py
releasenotes/notes/fix-openai-base-url-assignment-0570a494d88fe365.yaml
test/components/embedders/test_openai_text_embedder.py

I have made a very small fix for an issue that occurs for the `MistralTextEmbedder` which inherits this class. Without this assignments, serializing the component results in no `api_base_url` being listed.
I am skipping checking for `api_base_url` for now in the tests for mistral, until we can release this fix. …

fix: Adding `api_base_url` to `OpenAITextEmbeder` self assignments

---

test/components/connectors/test_openapi_service.py

Mark `test/components/connectors/test_openapi_service.py::TestOpenAPIServiceConnector::test_run` as flaky as it keeps failing randomly. 
See example failure 👇 
https://github.com/deepset-ai/haystack/actions/runs/7918059826/job/21616198301
I ran the test locally.
N/A
- I …

test: Mark OpenAPIServiceConnector integration test as flaky

---

haystack/components/audio/whisper_local.py
releasenotes/notes/whisper-loc-new-devices-0665a24cd92ee4b6.yaml
test/components/audio/test_whisper_local.py

refactor!: LocalWhisperTranscriber - new devices mgmt

---

test/components/audio/test_whisper_local.py

This test fails if the default device is not CPU.
Now I am explicitly initializing the component with CPU device.

fix: specify CPU device in warm_up test

---

haystack/core/pipeline/pipeline.py
releasenotes/notes/pipeline-same-input-ref-different-components-68d74cb17b35f8db.yaml
test/core/pipeline/test_same_input_different_components.py

- fixes #6986 
Previously, when using the same input reference in different components, the Pipeline run logic had an unexpected behavior (see the original issue). This has been fixed by deepcopying the inputs before passing them to the components.
CI, new test
- I would be happy to discuss better solutions together
- Simply doing `data=deepcopy(data)` does not fix the issue.
I think this happens because the same internal structure is reproduced, so if comp1 and comp2 share the same input reference, this also happens after deepcopy (comp1 and comp2 refer to the same deepcopied input)
- …

fix: deepcopy the inputs of components

---

haystack/dataclasses/byte_stream.py
test/dataclasses/test_byte_stream.py

Adds `to_string` method in the `ByteStream` class which arises from the requirement to convert byte data back into its original string format for certain use cases. This enhancement provides a convenient and intuitive way to achieve this, enriching the class's functionalities.
In addition, we already have a method from_string that creates a ByteStream instance from a string by encoding it to bytes. A to_string method provides the symmetric operation, converting the byte stream to a string. This symmetry in API design improves intuitiveness and usability.
* A new method named `to_string` has been added to the `ByteStream` class in `haystack/dataclasses/byte_stream.py`, enabling conversion of byte data to its original string representation.
* The method accepts an optional encoding …

feat: Add ByteStream to_string method

---

haystack/core/pipeline/pipeline.py
releasenotes/notes/max-loops-in-run-df9f5c068a723f71.yaml
test/core/pipeline/test_pipeline.py

Change `Pipeline.run()` to check if a Component has been ran the number of `max_loops_allowed`.
If we're about to run a Component that already ran the `max_loops_allowed` times we raise a `PipelineMaxLoops` exception.
I added a new unit test.
The name of the argument is semantically incorrect as it doesn't actually check for the number of loops but the number of times a Component ran.
I don't want to cause a breaking change as of now so I chose not to rename it. 
- I've used …

feat: Reintroduce `max_loops_allowed` check in `Pipeline.run()`

---

haystack/components/others/multiplexer.py
haystack/core/component/component.py
haystack/core/pipeline/pipeline.py
releasenotes/notes/component-greedy-d6630af901e96a4c.yaml
test/core/component/test_component.py

Add `is_greedy` argument in `@component` decorator to mark Components as greedy.
This just changes how we mark `Component`s as greedy, previously we just had an `is_greedy` field in the class declaration. This makes it more elegant and also clearer to understand that it's related to the Component.
N/A …

feat: Add `is_greedy` argument in `@component` decorator

---

haystack/components/embedders/sentence_transformers_document_embedder.py
haystack/components/embedders/sentence_transformers_text_embedder.py
releasenotes/notes/sentence-transformers-embedders-new-devices-mgmt-07cb59c6b4a13280.yaml
test/components/embedders/test_sentence_transformers_document_embedder.py
test/components/embedders/test_sentence_transformers_text_embedder.py

- part of #7000
- I refactored the Embedders according to the [new management of devices](https://docs.haystack.deepset.ai/v2.0/docs/device-management).
- no need to change the (Sentence Transformers) backend.
CI, new tests …

refactor!: Sentence Transformers Embedders - new devices mgmt

---

haystack/components/evaluators/statistical_evaluator.py
test/components/evaluators/test_statistical_evaluator.py

- fixes #6064
Add support for Recall Single Hit and Recall Multi Hit metrics in `StatisticalEvaluator` Component.
They both measure how many times a label appears in a list of predictions, the first though takes into account only the first match it finds.
I added new unit tests.
I chose to ignore the release notes as the `StatisticalEvaluator` still has not been release in any beta version and the PR that introduced it already has a release note. …

feat: Add Recall Multi Hit and Single Hit metric in `StatisticalEvaluator`

---

haystack/components/rankers/transformers_similarity.py
haystack/components/readers/extractive.py

Support for `device_map` was recently introduced in #6679.
This requires the `accelerate` library, which is automatically installed with `pip install transformers[torch]` (as underlined by @sjrl in #6679).
If the user has `transformers` but installed differently (as happens in Colab), the component fails at `warm_up`, as reported in https://github.com/deepset-ai/haystack/discussions/7020
**It would be better to make the component fail at init, with a clear error message**, similarly to other import errors in Haystack.
- Add the `accelerate` import to the lazy imports. The library is always (implicitly) used in these components.
CI …

chore: add `accelerate` to lazy imports

---

haystack/components/connectors/openapi_service.py
test/components/connectors/test_openapi_service.py

Rework `OpenAPIServiceConnector.run()` test to avoid making any HTTP request.
Since we rely on an external library to convert OpenAPI specs to a proper client it's fine to test we call the library.
This test keeps failing in CI making it quite annoying, see example faliure. 👇 
https://github.com/deepset-ai/haystack/actions/runs/7970654409/job/21759153102 …

test: Simplify OpenAPIServiceConnector run test

---

haystack/templates/__init__.py
haystack/templates/pipelines.py
haystack/templates/predefined/qa.yaml.jinja2
haystack/templates/source.py
releasenotes/notes/add-pipeline-templates-831f857c6387f8c3.yaml
test/templates/test_templates.py

- fixes n/a
`TemplateSource` is part of the public API to allow more advanced use cases, but that comes at the price of adding complexity to the simplest use cases. It wasn't part of my original UX review of the feature so I didn't know we introduced it and I think it's not needed.
unit tests
Before:
```py
ts = TemplateSource.from_predefined(PredefinedTemplate.RAG)
pipe = PipelineTemplate(ts).build()
```
After this PR:
```py
pipe = PipelineTemplate(PipelineType.RAG).build()
``` …

refact: remove the concept of `TemplateSource` from the public API

---

releasenotes/notes/add-pipeline-templates-831f857c6387f8c3.yaml

- fixes https://github.com/deepset-ai/haystack/actions/runs/8002246058/job/21855066081
Formatting was incorrect and it broke the release notes generation
We should check the release notes syntax when they get merged. …

chore: fix formatting of `add-pipeline-templates-831f857c6387f8c3.yaml`

---

.github/workflows/tests.yml
.github/workflows/tests_skipper.yml
haystack/core/pipeline/pipeline.py

- previously the CI skipped the tests if there was at least one no code change (which is quite normal since you usually add release notes)
- [GH docs on `paths-ignore` filter](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths)
>  If any path names do not match patterns in paths-ignore, **even if some path names match the patterns**, the workflow will run.
- this now adds a separate filter to ensure that there is really no code change
- manual as part of this PR
- I thought I could use `!` (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths) but that faces the same problem as the previous solution …

ci: only only skip tests if no code  changes at all

---

haystack/components/validators/json_schema.py
test/components/validators/test_json_schema.py

After updating https://github.com/deepset-ai/haystack/pull/7034 and flattening the OpenAI function calling schema, we need to update the JsonSchemaValidator to verify the path `["function"]["arguments"]` in the OpenAI function calling payload instead of `["function"]["arguments"]["parameters"]` i.e. not to include ["parameters"] we removed in the above-mentioned PR.
We'll also use the opportunity to slightly change the recovery message because we've empirically found that some LLM providers (like fireworks.ai) insist on the first message always being from the user - which is what we do here as well - reverse the order of messages in a list of recovery message so that user message is always first.

chore: Adjust json_schema.py slightly

---

haystack/tracing/opentelemetry.py

Getting
```
File "/opt/venv/lib/python3.10/site-packages/haystack/tracing/opentelemetry.py", line 15, in OpenTelemetrySpan
def __init__(self, span: opentelemetry.trace.Span) -> None:
NameError: name 'opentelemetry' is not defined
```
when importing Haystack from `main`
Since `opentelemetry` is an optional dependency, use [forward references](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#forward-references) in the type annotations. …

chore: forward-reference opentelemetry

---

haystack/components/converters/output_adapter.py
haystack/components/generators/azure.py
haystack/components/generators/chat/azure.py
haystack/components/generators/chat/hugging_face_local.py
haystack/components/generators/chat/hugging_face_tgi.py
haystack/components/generators/chat/openai.py
haystack/components/generators/hugging_face_tgi.py
haystack/components/generators/openai.py
haystack/components/generators/utils.py
haystack/components/others/multiplexer.py
haystack/components/routers/conditional_router.py
haystack/utils/__init__.py
test/utils/test_callable_serialization.py

We have multiple imports of serialization utilities, such as `(de)serialize_callable` and `(de)serialize_type`, scattered across various modules. This change aims to consolidate these imports into a single location, the `haystack.utils` module. This refactoring enhances code readability, simplifies maintenance, and promotes best practices by reducing duplicated imports.
* Unified import of `serialize_callable` and `deserialize_callable` in `haystack.utils`.
* Unified import of `serialize_type` and `deserialize_type` in `haystack.utils`.
* The original module export locations were left unchanges to minimize the disruption in dependencies. Dependencies like https://github.com/deepset-ai/haystack-core-integrations can update references at their own pace
* Cleaner and more consistent imports …

Export (de)serialize_callable and (de)serialize_type in haystack.utils

---

haystack/components/evaluators/__init__.py
haystack/components/evaluators/answer_exact_match.py
releasenotes/notes/exact-match-evaluator-197bb87b65e19d0c.yaml
test/components/evaluators/test_answer_exact_match.py

- fixes #6067 
Add `AnswerExactMatchEvaluator`. This Component calculates the Exact Match metrics given a list of questions, a list of expected answers for each question and the list of predicted answers for each question.
N/A …

Add `AnswerExactMatchEvaluator`

---

docs/pydoc/config/connectors.yml

We forgot to include these in the API docs. Update the heading for converters to be more generic and reflect the addition of OutputAdapter and OpenAPIServiceToFunctions converters.

chore: Update API docs to include OutputAdapter, OpenAPIServiceConnector,  and OpenAPIServiceToFunctions

---

haystack/core/pipeline/draw.py
releasenotes/notes/pipe-draw-transparent-bg-2e0c8ff586f8e70c.yaml

- fixes #7085
Simply force the image to be a PNG:
this makes the background transparent (https://github.com/jihchi/mermaid.ink/issues/130).
- CI
- [Manual test on Colab](https://colab.research.google.com/drive/1K3qzGvPcAJCyVWFDQzzi54D6ryOZrsZd?usp=sharing)
- Manual test on VSCode …

fix: restore transparent background for Pipeline images

---

haystack/components/generators/__init__.py
haystack/components/generators/chat/__init__.py
haystack/components/generators/chat/openai.py
haystack/components/generators/openai.py
releasenotes/notes/remove-gptgenerator-8eced280d3b720d3.yaml

We deprecated GPTGenerator and GPTChatGenerator components in December in this PR: https://github.com/deepset-ai/haystack/pull/6626. It's time to remove them completely. Users can use OpenAIGenerator and OpenAIChatGenerator instead.

chore: Remove deprecated GPTGenerator and GPTChatGenerator

---

.github/workflows/snippets_tests.yml

`snippets_tests.yml` workflow is currently failing. That's caused by changes introduced with #7079, as we introduce `hatch` to ease some stuff in CI.
[Example failure](https://github.com/deepset-ai/haystack/actions/runs/8050672661/job/21986790151).

ci: Fix `snippets_tests.yml`

---

haystack/components/samplers/top_p.py

`TopPSampler` docstrings

---

haystack/__init__.py
haystack/logging.py
pyproject.toml
releasenotes/notes/structured-logging-2d6cef3fee2b4f0e.yaml
test/test_logging.py
test/tracing/test_datadog.py

- related to https://github.com/deepset-ai/haystack/issues/7027
- add out-of-the-box support for structlog (console logs + JSON logging)
- unit tested it
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#in …

feat: implement support for structured logging

---

haystack/logging.py
haystack/tracing/datadog.py
haystack/tracing/opentelemetry.py
haystack/tracing/tracer.py
releasenotes/notes/log-trace-correlation-78bcf418718b24b4.yaml
test/core/pipeline/test_tracing.py
test/test_logging.py
test/tracing/test_datadog.py
test/tracing/test_opentelemetry.py
test/tracing/utils.py

- part of https://github.com/deepset-ai/haystack/issues/7027
- auto-correlate logs and traces in production settings …

feat: log trace correlation

---

docs/pydoc/config/preprocessors_api.yml
haystack/components/preprocessors/document_cleaner.py
haystack/components/preprocessors/document_splitter.py
haystack/components/preprocessors/text_cleaner.py

- fixes #7111 
- fixes #7166 (a class was missing)

docs: review `Preprocessors` docstrings

---

docs/pydoc/config/classifiers_api.yml
haystack/components/classifiers/document_language_classifier.py
test/components/classifiers/test_document_language_classifier.py

- fixes  #7101
- fixes #7156 (minor change was needed)

docs: review `DocumentLanguageClassifier` docstrings

---

haystack/components/connectors/openapi_service.py
haystack/components/converters/openapi_functions.py
releasenotes/notes/complex-types-openapi-support-84d3daf8927ad915.yaml
test/components/connectors/test_openapi_service.py
test/components/converters/test_openapi_functions.py
test/test_files/json/complex_types_openai_spec.json
test/test_files/json/complex_types_openapi_service.json

Enhances the OpenAPI service connector to handle complex types of requests and responses. This improvement ensures Haystack users can invoke a broader range of OpenAPI specifications via OpenAPIServiceConnector and convert them to OpenAI function calling specification via OpenAPIServiceToFunctions
- In `openapi_service.py`, the connector now supports cases where request parameters or body properties might be missing in the invocation arguments.
- In `openapi_functions.py`, the parsing logic for OpenAPI specifications has been updated to:
- Support more specific requirements for paths, including unique operationIds, descriptions, requestBody, parameters, and schemas.
- Improve parameter handling by merging request body properties and parameters, maintaining the correct schema definitions …

feat: Add complex types in OpenAPI support

---

haystack/logging.py
releasenotes/notes/logging-tty-detection-8136769cb4d1da67.yaml
test/test_logging.py

- related to https://github.com/deepset-ai/haystack/issues/7027
- be a bit smarter than before and automatically switch to JSON logging if there is no tty (following the recipe from here: https://www.structlog.org/en/stable/logging-best-practices.html#pretty-printing-vs-structured-output and adapting it to Jupyter)   
- above behavior is of course disablable …

feat: check tty / jupyter availability for logging config detection

---

haystack/components/rankers/meta_field.py
haystack/components/samplers/top_p.py
haystack/testing/factory.py

I forgot about this in #7205.
Took the opportunity to replace also other instances.

docs: replace `text` with `content` in usage examples

---

.github/utils/delete_outdated_docs.py
.github/workflows/readme_sync.yml

- fixes #7081
This PR adds a `delete_outdated_docs.py` script that can be used to delete documentation from Readme if it doesn't exist anymore.
This script deletes docs only from the categories found in the config files, as of now that's only `haystack-api`.
The `readme_sync.yml` workflow has been changed to run the script after syncing.
I tested manually to verify that only actual documents that don't exist anymore would be deleted, I didn't delete anything though.
I can't use the `rdme docs:prune` with the `readmeio/rdme` action as that would delete all docs, including those in other categories.
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_co …

ci: Add script to delete documentation that don't exist anymore

---

haystack/templates/pipeline.py
haystack/templates/predefined/generative_qa.yaml.jinja2
haystack/templates/predefined/indexing.yaml.jinja2
haystack/templates/predefined/rag.yaml.jinja2
releasenotes/notes/add-pipeline-templates-831f857c6387f8c3.yaml
test/templates/test_templates.py

- No issue, part of the getting start guide
As we better defined the onboarding path for new users, we realised the `override` feature can get in the way, pushing users in the wrong direction. This PR removes the feature altogether, further simplifying the predefined templates.
This is not the last step of the refactoring, more to come. …

refact: Remove the override feature in `PipelineTemplate`

---

.github/workflows/readme_sync.yml
pyproject.toml

Change `readme_sync.yml` job that deletes outdated docs to run command via `hatch`.
This should fix failures like [this](https://github.com/deepset-ai/haystack/actions/runs/8078875531/job/22072073667).
I ran the command locally.
N/A
- I ran …

ci: Fix delete outdated docs job in `readme_sync.yml`

---

.github/utils/delete_outdated_docs.py

Use proper env var in `delete_outdated_docs.py`. The workflow is already setting that one correctly.

ci: Fix delete_outdated_docs.py to get the correct api key

---

haystack/components/builders/answer_builder.py
haystack/components/builders/dynamic_chat_prompt_builder.py
haystack/components/builders/dynamic_prompt_builder.py
haystack/components/builders/prompt_builder.py
test/components/builders/test_prompt_builder.py

fix docstrings for the builder package

---

haystack/components/retrievers/__init__.py

fix: missing init imports for retrievers

---

haystack/components/builders/prompt_builder.py
test/components/builders/test_prompt_builder.py

- reverts wrong commit in #7248

chore: restore to_dict method

---

.pre-commit-config.yaml

- fixes https://github.com/deepset-ai/haystack/issues/5931
- already enabled sorting of imports for ruff here:  https://github.com/deepset-ai/haystack/blob/fe0ac5c4a280b6196fc984d580d3dd2675f893ae/pyproject.toml#L300 …

chore: run ruff with fix during precommit hook

---

haystack/core/pipeline/predefined/chat_with_website.yaml.jinja2
haystack/core/pipeline/predefined/generative_qa.yaml.jinja2
haystack/core/pipeline/predefined/rag.yaml.jinja2
haystack/core/pipeline/template.py
releasenotes/notes/chat-with-website-template-23bec121f1a78726.yaml

- Part of the getting started guide
Add a predefined template to be used like this:
```python
from haystack import Pipeline, PredefinedPipeline
pipe = Pipeline.from_template(PredefinedPipeline.CHAT_WITH_WEBSITE)
result = pipe.run({
"fetcher": {"urls": ["https://haystack.deepset.ai/overview/quick-start"]},
"prompt": {"query": "How should I install Haystack?"}}
)
print(result["llm"]["replies"][0])
``` …

feat: Add new predefined template: chat with website

---

test/core/pipeline/test_tracing.py

- optionals can have different representations depending on the Python version

tests: make `test_tracing` 3.12 compatible

---

haystack/components/converters/azure.py
haystack/components/converters/html.py
haystack/components/converters/markdown.py
haystack/components/converters/openapi_functions.py
haystack/components/converters/output_adapter.py
haystack/components/converters/pypdf.py
haystack/components/converters/tika.py
haystack/components/converters/txt.py

- fixes #7103
Update docstring for all `converters` Components.
I generated docs locally.
N/A

docs: Update `converters` docstrings

---

haystack/core/component/component.py
releasenotes/notes/fix-component-type-checking-issues-8eefa1157ffc3eba.yaml
test/core/component/test_component.py

Changes the `Component` protocol so `Pipeline.add_component()` and other methods expecting a `Component` won't show a warning anymore. This happened only for Language Server and some type checkers.
Before:
After:
N/A
- I …

fix: Update `Component` protocol to fix some type checking issues

---

haystack/core/pipeline/predefined/indexing.yaml.jinja2
haystack/core/pipeline/predefined/rag.yaml.jinja2
releasenotes/notes/add-pipeline-templates-831f857c6387f8c3.yaml

- part of the getting started guide
Make the template use Chroma as document store, so that data is persisted and can be used later from (let's say) a RAG pipeline.
Manually tested
We temporarily removed `use_pdf_file_converter`, it's not used in the getting started and it's one less thing to document right now. …

chore: update the INDEXING and RAG pipeline templates

---

.github/workflows/tests.yml
.github/workflows/tests_skipper.yml
pyproject.toml

- broken CI on `main`
Install `chroma-haystack` when running the tests. This is needed to test the serialization roundtrip of some predefined pipeline templates
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTIN …

fix: Update pyproject.toml

---

haystack/components/websearch/searchapi.py
haystack/components/websearch/serper_dev.py

- fixes #7273
Restrict the output type of links to `List[str]`: this makes it possible to connect WebSearch components to the `LinkContentFetcher`. 
Manual test; CI.
(Maybe in the future, we should also add an e2e test for a Web RAG Pipeline)
- I …

fix: fix output types in WebSearch components

---

haystack/core/pipeline/pipeline.py
releasenotes/notes/run-greedy-fix-6d4559126e7739ce.yaml
test/core/pipeline/test_pipeline.py

This PR fixes a bug that caused Components with default inputs to be executed before variadic greedy Components.
This could happen cause the internal list of Components that can run used in `Pipeline.run()` to keep track of the execution order also depends on the order the Components have been added in the Pipeline.
When starting run we iterate throught the Pipeline graph to understand which Components must run. In the order in which we iterate this graph depends on the order of addition. That reflects also down the line in the execution logic. This won't cause issues most of the times, since Components need to wait for their inputs to run.
Though greedy variadic Components and/or with default input values might be able to run even before they receive all their inputs. So if the order is …

fix: Fix run order of variadic greedy components in Pipeline.run()

---

pyproject.toml

[Tests are failing](https://github.com/deepset-ai/haystack/actions/runs/8137128846/job/22235082544?pr=7289) because pytest 8.1.0 broke the `flaky` plugin. See https://github.com/box/flaky/issues/198 
I am pinning pytest.
Then we will find a better course of action/an alternative to `flaky`.
CI

ci: temporarily pin pytest

---

haystack/nodes/retriever/dense.py

- fixes #7296
Add new model names to those recognized as OpenAI models.
Otherwise, the wrong encoder would be used.
manual test, CI …

fix: add new OpenAI model names to `_infer_model_format`

---

pyproject.toml
test/core/pipeline/test_draw.py

- `flaky` plugin seems unmaintained and is incompatible with the latest release of pytest. See https://github.com/box/flaky/issues/198 https://github.com/box/flaky/issues/192
- replace `flaky` with [`pytest-rerunfailures`](https://github.com/pytest-dev/pytest-rerunfailures), which seems actively maintained
- unpin `pytest`
Local test …

ci/test: replace `flaky` with `pytest-rerunfailures`

---

.pre-commit-config.yaml

The current ruff-pre-commit version fails when parsing the toml after PR https://github.com/deepset-ai/haystack/pull/7266
```
ruff.....................................................................Failed
- hook id: ruff
- exit code: 2
ruff failed
Cause: TOML parse error at line 292, column 12
|
292 | [tool.ruff.lint]
|            ^^^^
unknown field `lint`
```
- Update the ruff-pre-commit version to the latest release v0.3.0. Previously we used v0.0.290: https://github.com/astral-sh/ruff-pre-commit/releases/tag/v0.0.290
locally …

ci: Update ruff pre-commit version

---

docs/pydoc/config/rankers_api.yml

- fixes #7167 
- Add LostInTheMiddleRanker to API docs

docs: Add LostInTheMiddleRanker to API docs

---

haystack/components/rankers/meta_field.py
releasenotes/notes/fix-metafieldranker-weight-in-run-66ce13191e596214.yaml
test/components/rankers/test_metafield.py

- fixes #7304
Use `weight` (`=weight or self.weight`) instead of `self.weight` when computing the scores/rankings.
CI, new test …

fix: `MetaFieldRanker` - use `weight` if passed in the `run` method

---

haystack/core/pipeline/pipeline.py
haystack/core/serialization.py
haystack/telemetry/_telemetry.py
releasenotes/notes/remove-serialization-from-telemetry-a054f7f26f277d2b.yaml
test/core/pipeline/test_pipeline.py
test/core/test_serialization.py
test/test_telemetry.py

- fixes #7255
~~probably also fixing #7277 we need to double check ~~
- fixes #7277 
Instead of using pipeline serialization to get all components, we now loop through the nodes in the pipeline graph. …

fix: Remove pipeline serialization from telemetry code

---

haystack/components/readers/extractive.py
releasenotes/notes/update-secret-management-extractive-reader-4a8ce8df1f2705f8.yaml
test/components/readers/test_extractive.py

- fixes https://github.com/deepset-ai/haystack/issues/7307

chore: migrate `ExtractiveReader` to use secret management

---

test/core/pipeline/test_pipeline.py
test/core/pipeline/test_templates.py

Some tests in a PR by an external contributor are failing: https://github.com/deepset-ai/haystack/actions/runs/8175759835/job/22354455607
They (apparently) would need the OpenAI API key to pass, but in external PRs we don't pass the API key.
(Strangely, tests are only failing on Windows.
I can get the same failures locally on Ubuntu if I unset the environment variable. So maybe in Windows, the env var is set but has 0 length)
These specific tests just need the env var to be set, but they don't need to call OpenAI,
so I am monkeypatching the env var.
Local tests, CI
- I have updated the …

test: monkeypatch some env vars in Predefined Pipelines tests

---

.github/workflows/pypi_release.yml

`pypi_release.yml` workflow right now is triggered for every tag with any suffix, also for `-rc0`.
We must not release those versions as we only tag that to make sure `reno` works correctly when generating release notes.
This is necessary cause it searches for the previous tag in the main trunk and doesn't check the release branches.

ci: Fix `pypi_release.yml` workflow to skip rc0 versions

---

.github/workflows/readme_sync.yml

This PR changes `readme_sync.yml` workflow to handle 2.x version properly.
It also changes the trigger to ignore `1.x.x` branches as that are handled by another workflow.

ci: Fix `readme_sync.yml` workflow to handle unstable 2.x versions

---

.github/workflows/readme_sync.yml

Relates to #7330.
Change `readme_sync.yml` in to ignore version branches different from `1.x.x`, this changes the version used in `v1.x` branch only.

ci: Fix `readme_sync.yml` workflow to ignore non `1.x` versions

---

haystack/components/rankers/meta_field.py
releasenotes/notes/fix-metafieldranker-weight-in-run-method-e4e11011a8b99c34.yaml

- fixes #7341
Simply check if `weight` is not null
CI. Manual test.

fix: `MetaFieldRanker` - make `weight` passed in `run` to be used even if 0

---

haystack/components/routers/file_type_router.py
releasenotes/notes/feature-regex-mime-type-support-36381e74f593eb84.yaml
test/components/routers/test_file_router.py

- fixes #6191 
Added support for matching mime types using Regular expressions 
Did run manual tests

feat: Add support for matching mime types using regex

---

haystack/nodes/connector/crawler.py
releasenotes/notes/correct-crawler-pdf-download-location-82a443be7b07e182.yaml
test/nodes/test_connector.py

- fixes #6829 
- When a .pdf is passed to Selenium's [webdriver.get()](https://selenium-python.readthedocs.io/api.html#selenium.webdriver.remote.webdriver.WebDriver.get) method, the .pdf is automatically downloaded to the current working directory. This issue happens [here](https://github.com/mohitlal31/haystack/blob/fd13e8e8323d6ae87cba3e7b1f4809d073953030/haystack/nodes/connector/crawler.py#L345). Whereas for .html files, the crawler extracts the information and manually saves it in the provided output directory.
- By default, we use Selenium's chromium webdriver that provides additional preferences to set the download location for a file. These preferences are defined [here](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/common/pref_names.h). 
- When a crawler …

bug: Crawler downloads pdfs to project root directory

---

examples/retrievers/in_memory_bm25_documentsearch.py

- fixes Import error in example docs
Fixes import error:
```
>>> from haystack.pipeline import Pipeline
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'haystack.pipeline'
>>> from haystack import Pipeline
>>> 
```
Manual verification
N/A …

[docs] Fixed pipeline import statement

---

.github/workflows/stale.yml

- n/a
Let stalebot deal with stale issues when OP is not responsive

chore: extend stalebot to community triage

---

docs/pydoc/config/audio_api.yml
docs/pydoc/config/builders_api.yml
docs/pydoc/config/caching_api.yml
docs/pydoc/config/classifiers_api.yml
docs/pydoc/config/connectors.yml
docs/pydoc/config/converters_api.yml
docs/pydoc/config/data_classess_api.yml
docs/pydoc/config/document_stores_api.yml
docs/pydoc/config/document_writers_api.yml
docs/pydoc/config/embedders_api.yml
docs/pydoc/config/extractors_api.yml
docs/pydoc/config/fetchers_api.yml
docs/pydoc/config/generators_api.yml
docs/pydoc/config/joiners_api.yml
docs/pydoc/config/others_api.yml
docs/pydoc/config/pipeline_api.yml
docs/pydoc/config/preprocessors_api.yml
docs/pydoc/config/rankers_api.yml
docs/pydoc/config/readers_api.yml
docs/pydoc/config/retrievers_api.yml
docs/pydoc/config/routers_api.yml
docs/pydoc/config/samplers_api.yml
docs/pydoc/config/utils_api.yml
docs/pydoc/config/validators_api.yml
docs/pydoc/config/websearch_api.yml

Change the docs renderer to fix Readme upload failures in `main`.
I generated the docs locally and verified the category id matched the one from `2.1-unstable` instead of the one from `2.0`.
The new renderer has been added with deepset-ai/haystack-pydoc-tools#2.
- I …

ci: Update docs renderer

---

pyproject.toml
test/conftest.py
test/core/pipeline/test_pipeline.py
test/core/pipeline/test_templates.py

This PR skips collection of `test_json_schema.py` as it's causing issues in CI. 
The root of the issue seems to be the `jsonschema` library as reported [here](https://github.com/python-jsonschema/jsonschema/issues/1236) too.
This is a quick fix to make sure CI is not completely blocked.
[Example CI failure](https://github.com/deepset-ai/haystack/actions/runs/8263895299/job/22606670291).
Can't be tested, the issue happens only in CI.
We need to open an issue to monitor this issue and remove the collection skip as soon as the problem is solved.
- I have updated the related issue with new …

ci: Skip collection of `test_json_schema.py` to fix CI failures

---

.github/workflows/tests.yml
.github/workflows/tests_skipper.yml

The file test_requirements.txt was removed in #7079
and now the test dependencies are contained in pyproject.toml and handled using hatch.
Remove all the references to this file, that no longer exists.
CI …

chore: remove references to test_requirements

---

haystack/document_stores/faiss.py
releasenotes/notes/verify-embed-dim-docustore-retriever-9ac88d8f0adc8a32.yaml
test/document_stores/test_faiss.py

- fixes #5188 
- Currently, in haystack v1.x, when `document_store.update_embeddings()` gets called, the embeddings are calculated for all the documents and then saved to the document store. If the embedding dimension set in the document store differs from that of the retriever model, a runtime error is raised. 
- However, we don't need to calculate embeddings for all the documents in the document store to raise this error. This is especially an issue when using paid APIs (openai) or when the embedding calculation is time consuming. 
- A more efficient alternative is to calculate the embedding of a single document and verify that the embedding dimensions match between the document store and the retriever.
- Added two unit tests in `test_faiss.py`
- Modified the `basic_faq_pipeline.py` to …

feat: check document store and retriever dimensions before calculating embeddings for all documents

---

haystack/components/embedders/backends/sentence_transformers_backend.py
haystack/components/embedders/sentence_transformers_document_embedder.py
haystack/components/embedders/sentence_transformers_text_embedder.py
releasenotes/notes/add-trust-remote-code-feature-c133b2b245d2ea7a.yaml
test/components/embedders/test_sentence_transformers_document_embedder.py
test/components/embedders/test_sentence_transformers_embedding_backend.py
test/components/embedders/test_sentence_transformers_text_embedder.py

This change introduces a new parameter `trust_remote_code` in various classes of the Sentence Transformers embedder component. This parameter allows users to enable or disable the use of unverified model architectures, providing more flexibility in model selection.
- The `trust_remote_code` parameter is added to the `__init__` method in `_SentenceTransformersEmbeddingBackend`, `SentenceTransformersDocumentEmbedder`, and `SentenceTransformersTextEmbedder`.
- The `get_embedding_backend` method in `_SentenceTransformersEmbeddingBackendFactory` now accepts `trust_remote_code` as a parameter.
- The `warm_up` method in both `SentenceTransformersDocumentEmbedder` and `SentenceTransformersTextEmbedder` now accepts `trust_remote_code`.
- Test files are updated to include testing for the new …

feat: Add trust_remote_code init param to SentenceTransformer embedders

---

pyproject.toml
test/components/generators/conftest.py

- fixes #7358
Starting from `openai==1.14.0`, `Stream` invokes a method of the client.
This made our test fail since our client was null.
Change the `MockStream` in tests to make it use a mock of the client.
CI.
Manual tests with `openai==1.14.0`  and `openai==1.1.0`
- …

fix: unpin OpenAI and fix problem with mock

---

.github/workflows/tests.yml
.github/workflows/tests_skipper.yml
pyproject.toml

Transformers 4.38.2 was released 2 weeks ago and should be stable.
As usual, we are updating the dependency in the test environment
to ensure we are still compatible.
CI …

chore: Upgrade transformers to 4.38.2 in test environment

---

.github/workflows/benchmarks.yml

Benchmarks are consistently failing.
Let's disable the workflow. It's been broken for months and fixing it seems non trivial, no point in wasting money and CO2 to spin up the runner …

chore: unschedule benchmarks

---

haystack/components/rankers/meta_field.py
releasenotes/notes/updated-ranking-mode-in-meta-field-ranker-d1f1304cc422b202.yaml
test/components/rankers/test_metafield.py

- fixes #7354 
The `_merge_rankings` method uses the `self.ranking_mode` value initialized in the constructor. 
If this value is overridden in the `run` method, the new `ranking_mode` is not considered for ranking calculations. Added an extra param to `_merge_rankings` to accept the updated `ranking_mode` value that is passed in the `run` method. …

bug: run parameter "ranking_mode" does not override init param in meta field ranker

---

haystack/components/generators/chat/hugging_face_tgi.py
haystack/components/generators/hugging_face_local.py
haystack/components/generators/hugging_face_tgi.py
releasenotes/notes/adjust-max-new-tokens-to-512-in-huggingface-generators-76d9aba116b65e70.yaml
test/components/generators/chat/test_hugging_face_tgi.py
test/components/generators/test_hugging_face_local_generator.py
test/components/generators/test_hugging_face_tgi.py

- fixes ##7365
1. Set a default value for `max_new_tokens` to `515` in "Hugging Face generators".
2. Adjustment of the tests that fail due to the change.
Initialization tests had already been implemented but were adjusted based on the change.
There were several tests that were adjusted differently. I hope that the changes are correct, otherwise I will fix them as soon as possible.
There have been changes to the imports that I did not add on my own (I don't know if the pre-commit hooks can influence this or where they come from). If these seem strange, I will fix them as soon as possible.

refactor: default for max_new_tokens to 512 in Hugging Face generators

---

haystack/document_stores/weaviate.py

- fixes #7378 
Updating documentation for the `timeout_config` for the `WeaviateDocumentStore`. It is currently `(retries, time out seconds)` which is inconsistent with the Weaviate client [documentation](https://weaviate-python-client.readthedocs.io/en/stable/weaviate.html#weaviate.Client.timeout_config) of `(connect timeout, read timeout)`. Updating it to this
Verified manually that the parameter for the `connect_timeout` is not a retry parameter and is the connection timeout for the Weaviate DB. 
Weaviate Client documentation: https://weaviate-python-client.readthedocs.io/en/stable/weaviate.html#weaviate.Client.timeout_config …

docs: fix description of timeout config for WeaviateDocumentStore

---

docs/pydoc/config/data_classess_api.yml
haystack/dataclasses/__init__.py
haystack/dataclasses/document.py
haystack/dataclasses/sparse_embedding.py
releasenotes/notes/sparse-embedding-fd55b670437492be.yaml
test/dataclasses/test_document.py
test/dataclasses/test_sparse_embedding.py
test/tracing/test_utils.py

- part of #7355
Introduce a new class to store sparse embeddings.
Contains two fields: `indices` and `values`, which must have the same length.
New unit tests, change some existing tests, CI. …

feat: introduce `SparseEmbedding`

---

README.md

Rendering images on pypi.org does not work with relative URLs. I changed it to use an absolute link for Deepset's logo.
Right now it's being rendered like this:

Fix deepset logo rendering on pypi.org

---

haystack/components/generators/chat/hugging_face_tgi.py
releasenotes/notes/tgi-chat-missing-decorator-799b2a133ee4708c.yaml

- fixes #7379
Add the `@component` decorator to `HuggingFaceTGIChatGenerator`.
The lack of this decorator made it impossible to use the `HuggingFaceTGIChatGenerator` in a pipeline.
CI …

fix: add the `@component` decorator to `HuggingFaceTGIChatGenerator`

---

haystack/core/pipeline/pipeline.py
releasenotes/notes/pipe-disable-autoshow-dbbafd2bfdcce7a4.yaml
test/core/pipeline/test_pipeline.py

- fixes #7244
On Jupyter notebooks, the Pipeline is not automatically rendered as an image.
We use the textual repr by default.
[extensive Colab notebook](https://colab.research.google.com/drive/1l3G73tL27NdFgyQ0BPkxXoJbONNhgoA7?usp=sharing)
- I …

fix: Pipeline - disable autoshow on Jupyter

---

haystack/components/generators/hugging_face_local.py
releasenotes/notes/hugging-face-local-generator-streaming-callback-38a77d37199f9672.yaml
test/components/generators/test_hugging_face_local_generator.py

The change introduces a new `streaming_callback` parameter to the `HuggingFaceLocalGenerator` class, allowing users to handle streaming responses. This enhancement provides greater flexibility and customization in managing real-time responses from Hugging Face's local models.
- fixes https://github.com/deepset-ai/haystack/issues/6048
1. Modifies `haystack/components/generators/hugging_face_local.py`:
- Adds `streaming_callback` as an optional parameter to the `HuggingFaceLocalGenerator` class.
- Implements `streaming_callback` functionality within the `run` method.
- Updates `to_dict` and `from_dict` methods to serialize and deserialize the `streaming_callback` parameter.
2. Adds `releasenotes/notes/hugging-face-local-generator-streaming-callback-38a77d37199f9672.yaml` to document the new …

feat: Add streaming to `HuggingFaceLocalGenerator`

---

haystack/components/generators/chat/hugging_face_tgi.py
haystack/components/generators/chat/openai.py
haystack/components/generators/openai.py
haystack/dataclasses/chat_message.py
test/dataclasses/test_chat_message.py

While investigating on chat use cases, I discovered that we are sending requests like this to OpenAI:
`[{'content': 'You are a helpful assistant.', 'role': <ChatRole.SYSTEM: 'system'>}]`
instead of `[{'content': 'You are a helpful assistant.', 'role': 'system'}]`
Although this probably causes no problems, it is best to pass the correct format.
- introduce a method `to_openai_format` in the ChatMessage dataclass
- use it in OpenAI generators and HF TGI Chat generator
New tests, CI …

refactor: pass a `role` string to OpenAI API

---

haystack/components/generators/hugging_face_local.py
haystack/utils/hf.py

Several core-integrations tests with Haytstack main are failing after #7377
See for example https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8383450235/job/22959180165
This happens because `HFTokenStreamingHandler` import in HFLocalGenerator is not inside a lazy_import block,
even if the class needs `transformers`
put `HFTokenStreamingHandler` in a lazy_import block
- Locally rerun the failed core-integrations tests with this change
- CI
- I've used one …

fix: put `HFTokenStreamingHandler` in a lazy_import block

---

haystack/utils/hf.py

- fixes https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8413165168/job/23034987754
When testing Amazon Bedrock integration with Haystack main, tests are failing due to incorrect import check
- check `torch` import before introducing `StopWordsCriteria`
- more specific name for another import block
Manual tests on Amazon Bedrock integration, CI …

refactor: reorganize imports in HF utils

---

haystack/components/evaluators/answer_exact_match.py
test/components/evaluators/test_answer_exact_match.py

Standardize outputs with other evaluators.
This PR also adds a new test with more complex data.
This decision stems from this [discussion](https://github.com/deepset-ai/haystack/pull/7073#discussion_r1531859980).
I ignored the release notes as this has still not been released and the PR that added this Component already has release notes. …

feat: Change outputs of AnswerExactMatchEvaluator

---

haystack/nodes/prompt/invocation_layer/open_ai.py

- fixes #7410 
Allows users to pass `response_format` and `seed` through the `model_kwargs` of the PromptNode when using OpenAI or Azure OpenAI invocation layers. 
Example usage
```
openai = PromptNode(
model_name_or_path="gpt-3.5-turbo",
model_kwargs={"seed": 42, "response_format": {"type": "json_object"}},
api_key=API_KEY
)
openai.prompt("Create a sample JSON output")
```
Manually tested it. …

feat: Add support for `response_format` and `seed` in OpenAI and Azure OpenAI invocation layers

---

haystack/components/generators/hugging_face_local.py
haystack/utils/hf.py
test/components/generators/test_hugging_face_local_generator.py

- fixes #6082
- kept the test that uses a mocked tokenizer (`test_stop_words_criteria_with_a_mocked_tokenizer`) testing that Haystack's `StopWordsCriteria` works
- added a test stop words using a Hugginface tokenizer, essentially the same as above but downloads a tokenizer from HF and uses it to generate input ids
- added a test that uses a Huggingface model + tokenizer + Haystack's StopWordsCriteria, its tests that all components work. 
- NOTE: the last test doesn't account if the huggingface model pipeline after run actually stopped at the right word, I would say that's covered with the first two tests, check my comments on https://github.com/deepset-ai/haystack/issues/6082 for more context on why I opted for this approach on testing
- cleaned up the …

test: HuggingFaceLocalGenerator test stopwords

---

haystack/components/embedders/hugging_face_tei_document_embedder.py
haystack/components/embedders/hugging_face_tei_text_embedder.py
haystack/components/generators/chat/hugging_face_tgi.py
haystack/components/generators/hugging_face_tgi.py
haystack/utils/hf.py
pyproject.toml
releasenotes/notes/upgrade-tgi-to-new-hf-hub-51fcb3b6122fe020.yaml
test/components/generators/chat/test_hugging_face_tgi.py
test/components/generators/test_hugging_face_tgi.py

- fixes #7418
- Adopt all new abstractions of `huggingface_hub`: they are now public (and less susceptible to breaking changes, I hope)
- Encourage users to install `huggingface_hub>=0.22.0` in lazy_import message and release note. Since it is not a core dependency, there seems to be no effective way to make this encouragement mandatory.
- Remove pin from tests dependencies
- CI, adapted tests
- manual tests for both the generators, in streaming and non-streaming mode, with the HF Inference API and a local TGI container
- …

refactor!: make TGI generators compatible with `huggingface_hub>=0.22.0`

---

haystack/components/evaluators/document_recall.py
releasenotes/notes/recall-evaluator-5595470406e93ad2.yaml
test/components/evaluators/test_document_recall.py

- fixes #6064
Add `DocumentRecallEvaluator` Component. It can ben used to calculate Recall single-hit or multi-hit metric.
I didn't add the component in the package `__init__.py` on purpose to avoid conflicts with future PRs. 
When all the evaluators are done I'll update it. …

feat: Add `DocumentRecallEvaluator`

---

haystack/core/pipeline/pipeline.py
releasenotes/notes/fix-pipeline-run-disorder-382da1e6bd6db510.yaml
test/core/pipeline/test_pipeline.py

- fixes #7243
Changes the behaviour of `Pipeline.run()` to treat Components that have only default inputs the same way we treat Component with Variadic that are marked as lazy. This is done only when trying to remove Components from the internal `waiting_for_input` queue.
I added a new unit test and verified other weren't breaking.
N/A …

Fix: Fix Pipeline.run() running components with only defaults in the wrong order

---

.github/workflows/e2e.yml

- fixes #5334
- introduce a job that send failure events to Datadog in case of nightly failures
- (in Datadog: configure the related monitor that sends notifications)
Tested on https://github.com/deepset-ai/haystack/pull/7429/commits/60fbefedad25e0386f84f56dfcd114a07cd99c3a -> triggered a Slack notification …

ci: notify e2e nightly failures

---

haystack/nodes/prompt/prompt_node.py
test/prompt/test_prompt_node.py

We've found that in some situations we'd prefer the model provider (e.g. OpenAI) to return with an error message if the prompt is too long rather than truncate the end of the prompt which can lead to non-sensical answers depending on how the PromptTemplate is constructed. So I propose adding a parameter to toggle this behavior with the default behavior being unchanged (i.e. `truncation=True` is the same as the previous default behavior).
Added a unit test.
I also tested this manually with an Azure deployment and did see an error message returned as expected when setting `truncate=False`
```
haystack.errors.OpenAIError: OpenAI returned an error.
Status code: 400
Response body: {
"error": {
"message": "This model's maximum context length is 8192 tokens. However, you …
```

feat: Add boolen to toggle prompt truncation

---

haystack/components/builders/dynamic_chat_prompt_builder.py
haystack/dataclasses/chat_message.py
releasenotes/notes/dynamic-chat-prompt-templating-enhancement-e8d36cbf3be46da7.yaml
test/components/builders/test_dynamic_chat_prompt_builder.py

Enhances the `DynamicChatPromptBuilder` component by introducing more advanced and flexible chat message templating capabilities. The update ensures that not only the last user message but all user and system messages within a chat can be dynamically templated with provided variables. 
- fixes https://github.com/deepset-ai/haystack/issues/6926
- **Dynamic Chat Prompt Templating Improvement**: The core change involves updating the `_process_chat_messages` method within `dynamic_chat_prompt_builder.py` to apply templating to all user and system messages based on provided template variables instead of just the last user message. This is achieved by iterating through each chat message and rendering it with the template variables if applicable.
- **New ChatMessage Class Method**: A new method …

feat: DynamicChatPromptBuilder add templating to all user/system messages

---

haystack/testing/document_store.py
releasenotes/notes/fix-document-store-in-test-3640b8b079ff4539.yaml

Ensure test_comparison_in checks an actual subset of documents

---

haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline.py

- related to #7243
Add a missing check in `Pipeline.run()` that prevented Components with only default inputs to run when the Pipeline is stuck in a loop.
I ran the failing end to end test that was failing.
No need for release notes as the bug was created with #7426 and it still has not been released. …

fix: Fix `Pipeline.run()` getting stuck in a loop even though there are components that can run

---

haystack/components/websearch/searchapi.py
releasenotes/notes/update-searchapi-new-format-74d8794a8a6f5581.yaml
test/components/websearch/test_searchapi.py

The update in the web search API component focuses on updating to a new format and also enhancing flexibility. Specifically, it addresses the need for users to specify their preferred search engine when conducting web searches through the API. 
- fixes https://github.com/deepset-ai/haystack/issues/7447
- Extended the documentation to inform users they can now specify a search engine via the `search_params` argument, with Google being the default.
- Altered the payload creation process by:
- Checking if the `engine` parameter is not present in `search_params` and setting it to "google" by default.
- Removing the JSON serialization process for the `payload` variable.
- Adjusting the way the API key is included in the request, moving it from the request headers to the payload.
- Simplifying …

feat: Update searchapi format, default to Google, allow search engine selection

---

haystack/components/evaluators/document_map.py
releasenotes/notes/document-map-evaluator-de896c94b54fe3fa.yaml
test/components/evaluators/test_document_map.py

- fixes #6066
Add `DocumentMeanAveragePrecision` Component to calculate Mean Average Precision of a retrieved documents given a list of ground truth documents.
N/A …

feat: Add `DocumentMeanAveragePrecision`

---

haystack/components/evaluators/document_mrr.py
releasenotes/notes/document-mrr-evaluator-fa7c266cc91201a7.yaml
test/components/evaluators/test_document_mrr.py

- fixes #6065
Add `DocumentMeanReciprocalRank` Component to calculate Mean Reciprocal Rank of a retrieved documents given a list of ground truth documents.
N/A …

feat: Add `DocumentMeanReciprocalRank`

---

haystack/utils/device.py

- fixing some docstrings to comply with style defined here: https://github.com/deepset-ai/haystack/pull/7463

fixing some docstrings

---

haystack/components/evaluators/document_map.py
haystack/components/evaluators/document_mrr.py
releasenotes/notes/document-map-evaluator-de896c94b54fe3fa.yaml
releasenotes/notes/document-mrr-evaluator-fa7c266cc91201a7.yaml
test/components/evaluators/test_document_map.py
test/components/evaluators/test_document_mrr.py

Rename `DocumentMeanAveragePrecision` and `DocumentMeanReciprocalRank` to `DocumentMeanAveragePrecisionEvaluator` and `DocumentMeanReciprocalRankEvaluator` respectively.
N/A
N/A …

refactor: Rename `DocumentMeanAveragePrecision` and `DocumentMeanReciprocalRank`

---

haystack/components/evaluators/llm_evaluator.py
test/components/evaluators/test_llm_evaluator.py

none
- Removed the  name 'llm' from LLMEvaluator output. While other eval frameworks include the metric name in the output dict, we agreed that there is no need for that in Haystack and none of the other evaluator components includes a name in the output.
unit test updated …

refactor: Remove name 'llm' from LLMEvaluator output

---

test/components/generators/chat/test_hugging_face_local.py
test/components/rankers/test_sentence_transformers_diversity.py
test/components/rankers/test_transformers_similarity.py
test/components/readers/test_extractive.py
test/components/routers/test_zero_shot_text_router.py

This should fix failures in `main` caused by #7490.

CI: Fix unit tests failing if `HF_API_TOKEN` is set

---

haystack/utils/callable_serialization.py
haystack/utils/hf.py
haystack/utils/url_validation.py

just some more quick fixes

---

haystack/components/builders/prompt_builder.py

- Relates to #7441
Change wrong `PromptBuilder` docstring.
Nothing to test.
N/A

docs: Fix inaccuracy in `PromptBuilder` docstring

---

haystack/testing/sample_components/accumulate.py
haystack/testing/sample_components/greet.py
haystack/testing/sample_components/hello.py
haystack/testing/sample_components/joiner.py
haystack/testing/sample_components/self_loop.py
haystack/testing/sample_components/subtract.py
haystack/testing/sample_components/text_splitter.py
haystack/testing/sample_components/threshold.py

chore: fix docstring for the sample_components package

---

pyproject.toml

- fixes n/a
We should come up with a desired value for the maximum line length in the source code. Meanwhile, set the `line-length` linter parameter to the minimum possible without touching the code.
While there, let's do the same for other linting params
- I documented …

chore: set linting parameters to the minimum

---

.github/workflows/github_release.yml

- fixes #7506
- trigger on the right tag
- make it properly run both on minor releases (X.Y.0) and bugfix releases (X.Y.Z; Z!=0)
- used to release 2.0.1 on v2.0.x branch
-  …

ci: fix release notes generation on `github_release` workflow

---

test/components/embedders/test_hugging_face_api_document_embedder.py
test/components/embedders/test_hugging_face_api_text_embedder.py
test/components/embedders/test_hugging_face_tei_document_embedder.py
test/components/embedders/test_hugging_face_tei_text_embedder.py
test/components/generators/chat/test_hugging_face_api.py
test/components/generators/test_hugging_face_api.py

We recently introduced new integration tests for HF components.
Now tests are failing when running from forks, since the correct token/API key is missing (https://github.com/deepset-ai/haystack/actions/runs/8613243181/job/23604793945?pr=7504).
Skip tests if the `HF_API_TOKEN` env var is not set,
as we usually do.
CI.
I created this PR from a fork to make sure everything is in place. …

test/CI: skip HF integrations tests if running from fork

---

haystack/components/converters/azure.py
releasenotes/notes/AnalyzeResult-forward-declaration-5ed1bd9b6dc62c6f.yaml

- tests of Unstructured core-integration with the main branch of Haystack are failing: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8623976624
Forward declaration of `AnalyzeResult` type in `AzureOCRDocumentConverter`.
`AnalyzeResult` is already imported in a lazy import block.
The forward declaration avoids issues when `azure-ai-formrecognizer>=3.2.0b2` is not installed.
CI.
Tried to run Unstructured core-integration tests with this fix. :heavy_check_mark:  …

fix: `AzureOCRDocumentConverter` - forward declaration of `AnalyzeResult` types

---

haystack/components/evaluators/answer_exact_match.py
haystack/components/evaluators/document_map.py
haystack/components/evaluators/document_mrr.py
haystack/components/evaluators/document_recall.py
haystack/components/evaluators/faithfulness.py
haystack/components/evaluators/llm_evaluator.py
haystack/components/evaluators/sas_evaluator.py
test/components/evaluators/test_document_recall.py

None
- Updated imports in docstring examples
- Fixed one example where answers were used but documents are actually required
- Changed type of individual scores from bool to float and adjust test case. Recall scores of 0 or 1 make more sense than bool. You wouldn't say " Recall is True" or "Recall is False". It's also more consistent with all other metrics.
Tested the examples locally and updated the unit test to include a check that individual scores are not bool. Previously the check should have used `is False` or `is True` instead of `== False`. The previous check also passed if the value was 0.0.
If there are doubts about the data type of recall individual scores, we could also leave it out of this PR and just merge the docstring updates. I think it's better to have float but I also …

docs: Fix eval metric examples in docstrings

---

haystack/nodes/file_converter/image.py
haystack/nodes/other/join_docs.py
haystack/nodes/other/shaper.py
haystack/nodes/prompt/prompt_node.py
haystack/pipelines/base.py
releasenotes/notes/fix-pipeline-with-join-node-5f23a426cd4d88d9.yaml
test/nodes/test_join_documents.py
test/pipelines/test_pipeline.py

We have started to develop multi prompt node pipelines for clients. Some of the most popular ones include rewriting the query during the pipeline execution. Here is a simple example using a PromptNode as a spell checker for the incoming user query. 
```python
from haystack.nodes import BM25Retriever, EmbeddingRetriever, PromptNode, Shaper, JoinDocuments, PromptTemplate
from haystack.document_stores import InMemoryDocumentStore
document_store = InMemoryDocumentStore(use_bm25=True)
dicts = [{"content": "The capital of Germany is Berlin."}, {"content": "The capital of France is Paris."}]
document_store.write_documents(dicts)
query_prompt_node = PromptNode(
model_name_or_path="gpt-3.5-turbo",
api_key="", …
```

fix: Fix pipeline with join node

---

haystack/core/pipeline/pipeline.py
releasenotes/notes/fix-pipeline-run-loop-99f7ff9db16544d4.yaml
test/core/pipeline/test_pipeline.py

With PR #7434 we introduced this bug that would cause a Pipeline to get stuck in an infinite loop when running if the following conditions are met:
- The first Component has all defaults for its inputs
- The first Component receives one input from the user
- The first Component receives one input from a loop in the Pipeline
- The second Component has at least one default input
This PR fixes this bug by making sure that a Component with defaults has all the necessary inputs to run when adding it in the `to_run` list when we notice we're stuck in a loop with Components that can still run.
I added a unit test to reproduce the issue.
This bug has been discovered after [this message](https://discord.com/channels/993534733298450452/1226997620988444783/1226997620988444783) on Discord.
- I have …

fix: Fix corner case when running Pipeline that causes it to get stuck in a loop

---

docker/docker-bake.hcl

- fixes n/a
Use the latest Python version in the Haystack docker images.

chore: use the latest Python image

---

pyproject.toml

- n/a
Pass the hatch args down to pytest, so you can do something like
```
hatch run test:unit -xv
```

chore: forward hatch command args to pytest

---

haystack/lazy_imports.py
haystack/marshal/protocol.py
haystack/tracing/tracer.py
haystack/utils/auth.py
haystack/utils/device.py

- Part of [#7096](https://github.com/deepset-ai/haystack/issues/7096)

chore: fix linting errors

---

docs/pydoc/config/evaluators_api.yml

Adding Evaluators documentation to Haystack docs.

docs: add evaluators component reference

---

.github/CODEOWNERS

Twin PR of #7538
update CODEOWNERS to make sure a member of open-source engineering is automatically assigned to review PRs in v1.x branch (example: this didn't happen for #7543) …

chore: update CODEOWNERS in v1.x branch

---

haystack/components/caching/cache_checker.py
haystack/components/retrievers/filter_retriever.py
haystack/components/writers/document_writer.py
haystack/core/component/component.py
haystack/core/pipeline/pipeline.py
releasenotes/notes/fix-logger-reserved-attributes-9e4d4920c1e41a62.yaml
test/components/generators/chat/test_openai.py
test/components/generators/test_openai.py
test/test_logging.py

- fixes #7516
Remove all the occurrences of reserved attributes in the logging calls

fix: do not use reserved attributes in the logger

---

haystack/nodes/file_classifier/file_type.py
test/nodes/test_filetype_classifier.py

- fixes #DC-1108
https://deepset.atlassian.net/browse/DC-1108
Allow skipping of unspecified file types in FileClassifier using a newly introduced flag `raise_on_error`. If `raise_on_error` is set to False, the file will be skipped (sent to a dead edge). Additionally, a warning is logged.
**Use cases:**
We want to enable deepset Cloud users: 
- to upload other file types than .txt/.pdf in their workspace and run pipelines independent of file types available in their workspace
- schedule directories of files for indexing (containing different file types) without pre-cleaning and matching for specific pipelines
unit test …

feat: skip unknown file types [DC-1108]

---

haystack/components/evaluators/faithfulness.py
test/components/evaluators/test_faithfulness_evaluator.py

None. Came up in the implementation of ContextRelevanceEvaluator
- FaithfulnessEvaluator specifies run method inputs explicitly
- Move out examples
- Add integration test
- Extend docstring to explain that default examples are used if none are provided
existing unit tests, new integration test …

refactor: FaithfulnessEvaluator specifies inputs explicitly

---

haystack/document_stores/opensearch.py
haystack/document_stores/search_engine.py
test/document_stores/test_search_engine.py

All docstore methods normally take `self.index` as index param of opensearch / elasticsearch requests if no value for `index` has been passed explicitly. `get_metadata_values_by_key` misses this behavior. 
- `get_metadata_values_by_key` uses `self.index` if `index=None` 
- `batch_size` param added to `get_metadata_values_by_key` to controll efficient paging
- existing tests
- additional test for `batch_size` …

fix: use docstore.index for get_metadata_values_by_key (OpenSearch / elasticsearch)

---

haystack/nodes/prompt/invocation_layer/amazon_bedrock.py
releasenotes/notes/bedrock-support-for-llama3-a1c2c4fcfb5a8395.yaml
test/prompt/invocation_layer/test_amazon_bedrock.py

feat: support Llama3 models on Bedrock

---

haystack/components/evaluators/llm_evaluator.py
haystack/components/extractors/named_entity_extractor.py
haystack/components/joiners/document_joiner.py
haystack/core/component/component.py

fixing all issues raised by A002, e.g.: `Argument "type" is shadowing a Python builtin`
run `ruff` with the appropriate config locally

fix: renaming vars that use built-in names

---

test/components/evaluators/test_context_relevance_evaluator.py

- Similar to the PR https://github.com/deepset-ai/haystack/pull/7582 for FaithfulnessEvaluator, we want to make the ContextRelevanceEvaluator integration tests more robust
Check only that the fields exist but not the values in the result
Ran the test locally
- I …

test: Make ContextRelevanceEvaluator integration test more robust

---

haystack/dataclasses/sparse_embedding.py
releasenotes/notes/sparse-emb-eq-773ef04ae3ed83ea.yaml
test/dataclasses/test_sparse_embedding.py

While working on hybrid retrieval, I noticed we lack a proper way to compare `SparseEmbedding` objects.
Add an `__eq__` method to `SparseEmbedding` class to compare two `SparseEmbedding` objects.
CI, new test …

add `__eq__` method to `SparseEmbedding`

---

haystack/nodes/prompt/prompt_template.py
releasenotes/notes/fix-output-parser-in-prompt-template-22975013f44c435b.yaml
test/prompt/test_prompt_node.py

- enabled and ran all skipped tests of `test_prompt_node.py`

fix: OutputParser when used within PromptTemplate

---

haystack/core/pipeline/descriptions.py
haystack/core/pipeline/pipeline.py
releasenotes/notes/pipeline-io-connected-sockets-db862d045944f788.yaml
test/core/pipeline/test_pipeline.py

The current implementation of the `Pipeline.inputs/outputs` methods implicitly assumes that the user only cares about I/O sockets that are disconnected, i.e., they do not have an edge leading to them in the graph. This change introduces a boolean parameters to include components and sockets that are connected.
Maintains backward-compatibility by defaulting to not including connected sockets.
Unit tests
To be leveraged by the evaluation harness. …

feat: Expand `Pipeline.inputs` and `Pipeline.outputs` to include connected sockets

---

haystack/nodes/file_classifier/file_type.py
test/nodes/test_filetype_classifier.py
test/pipelines/test_pipeline.py

- followup from https://github.com/deepset-ai/haystack/pull/7542
- route not identified file to dead end.
- not yet. First want to validate that this is feasible solution
- turned out that this does not work: https://github.com/deepset-ai/haystack/pull/7542#discussion_r1562336195. 
This results in: 
```
Failed to index because of: 'Exception while running node 'FileTypeClassifier': 'NoneType' object has no attribute 'get'
Enable debug logging to see the data that was passed when the pipeline failed.'. Skipping handling indexing requests.
AttributeError: 'NoneType' object has no attribute 'get'
/opt/venv/lib/python3.10/site-packages/haystack/pipelines/base.py, line 567, run
/opt/venv/lib/python3.10/site-packages/haystack/pipelines/base.py, line 469, _run_node …
```

fix: route not identified files to dead end edge

---

releasenotes/notes/add-dead-end-for-classifier-8c87716695efd86a.yaml

- ad-hoc
add correct release node

fix: reno nodes dead end classifier

---

.github/workflows/tests.yml

Github macos-latest now points to M1 runners (macos-14-arm64) which is nice but that kills our python version test matrix. Let's rollback to macos-12 until we see what versions of python shall we test if we use macos-latest (has only python 3.10 and after)
More details: https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
Available macos runners: https://github.com/actions/runner-images/tree/main/images/macos
Avialable python versions on macos-12: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#python

chore: Rollback macos-latest to macos-12

---

docs/pydoc/config/evaluation_api.yml

- fixes Sync docs with Readme failing workflow: https://github.com/deepset-ai/haystack/actions/runs/8845590640/job/24289790847
- follows #7594
- remove the no longer existing `evaluation_result` module from pydoc config for Evaluators
- add pydoc config for the evaluation package
Local run of `hatch run readme:sync`; CI. …

docs: add pydoc config for evaluation

---

haystack/evaluation/eval_run_result.py

- fixes #5336 
- this is quick fix part of this PR: https://github.com/deepset-ai/haystack/pull/7601

fix: `EvaluationRunResult` should compare only input keys

---

haystack/components/builders/prompt_builder.py
releasenotes/notes/add-required-flag-for-prompt-builder-inputs-f5d3ffb3cb7df8d0.yaml
test/components/builders/test_prompt_builder.py

- changes PromptBuilder behavior according to #7441
PromptBuilder now takes a new optional parameter `required_variables` upon initialization to specify a list of jinja template variables that must be provided at all times. During pipeline or component runs, a proper`ValueError` will be thrown if some of the required variables are missing.
Added a new unit test.
Tested by following the 2.0 RAG pipeline recipe from https://docs.haystack.deepset.ai/docs/creating-pipelines
For the sake of completeness, I also added a validation check in `PromptBuilder.run()`. 
- I have updated the related …

feat: add required flag for prompt builder inputs

---

haystack/nodes/prompt/invocation_layer/handlers.py
haystack/nodes/prompt/invocation_layer/hugging_face_inference.py
releasenotes/notes/support-hf-inference-gated-repos-c04be10438e08501.yaml

- this allows us to use `meta-llama/Meta-Llama-3-8B-Instruct` via HF inference API
- pass hf token to `DefaultPromptHandler` for tokenizer
- chore: add `stop` param to `HFInferenceInvocationLayer` (for usage via model_kwargs)
- ran locally, e.g.
```python
pn = PromptNode(
model_name_or_path="meta-llama/Meta-Llama-3-8B-Instruct", 
api_key="TOKEN",
use_auth_token="TOKEN",
model_kwargs={
"stop": ["<|end_of_text|>", "<|eot_id|>"],
}
)
pn("What is the capital of Germany?")
```
- …

feat: hf inference support for gated repos

---

haystack/core/component/component.py

No issue opened
The `instance` argument was missing from the sample code in the docstrings for `component.set_output_types` and `component.set_input_types`. This caused me to write code that didn't work. I fixed my code, I would like to fix the docs.
I haven't yet. 
I hope you have a nice day.
[X] I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_conduct.txt)
[ ] I have updated the related issue with new insights and changes
[ ] I added unit tests and updated the docstrings
[X] I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, …

docs: Add instance argument to code samples in docstrings for component.py

---

haystack/components/evaluators/context_relevance.py
haystack/components/evaluators/faithfulness.py
haystack/components/evaluators/llm_evaluator.py
haystack/components/evaluators/sas_evaluator.py
test/components/evaluators/test_faithfulness_evaluator.py
test/components/evaluators/test_llm_evaluator.py

- fixes #7620 
- fixes #7528 
- Make SASEvaluator output format for bi-encoder models consistent with its output format for cross-encoder models fixing #7620 
- Rename FaithfulnessEvaluator input `responses` to `predicted_answers`. This renaming makes the parameter name consistent with the parameter name of SASEvaluator and AnswerExactMatchEvaluator. Downside is that it's a different name than in the integrations of Ragas and DeepEval. These two use `responses` as the input parameter name.
- Minor change of the prompt for LLMEvaluator adding a whitespace
I decided to keep the `contexts` input param of `FaithfulnessEvaluator` and `ContextRelevanceEvaluator` unchanged. Changing its type from str to Document and the name from `contexts` to `retrieved_documents` doesn't work well with how we …

refactor: Rename FaithfulnessEvaluator input `responses` to `predicted_answers`

---

haystack/components/embedders/hugging_face_api_document_embedder.py
haystack/components/embedders/hugging_face_api_text_embedder.py
haystack/components/embedders/hugging_face_tei_document_embedder.py
haystack/components/embedders/hugging_face_tei_text_embedder.py
haystack/components/generators/chat/hugging_face_api.py
haystack/components/generators/chat/hugging_face_tgi.py
haystack/components/generators/hugging_face_api.py
haystack/components/generators/hugging_face_tgi.py
haystack/utils/hf.py
pyproject.toml
releasenotes/notes/upgrade-huggingface-hub-dependency-9b8a89d50eb88fea.yaml
test/components/generators/chat/test_hugging_face_api.py
test/components/generators/chat/test_hugging_face_tgi.py
test/components/generators/test_hugging_face_api.py
test/components/generators/test_hugging_face_tgi.py

Upgraded the required version of `huggingface_hub` to `>=0.23.0` across various modules to ensure compatibility and leverage the latest features. This update includes modifications to error handling for token generation details and introduces adjustments in the chat and text generation interfaces to enhance functionality and developer experience. Users are advised to upgrade their `huggingface_hub` dependency.

chore: Update huggingface_hub classes used after library upgrade

---

.github/workflows/minor_version_release.yml

This PR changes `minor_version_release.yml` to create a PR to bump the version in `main` or `v1.x` instead of pushing directly to those branches.
Pushing to `v1.x` is fine actually since it's not a protected branch, but `main` is so it fails. See [this workflow run](https://github.com/deepset-ai/haystack/actions/runs/8936143640/job/24545924772).
We used a similar strategy in the past that would bump the version with a PR. That was problematic as we were using the workflow GH token, opening a PR with that token doesn't trigger workflows in that PR.
To work around that I used the `HAYSTACK_BOT_TOKEN`, that will trigger workflows. 
I tested by opening PR #7641 with that token via REST API and it triggered workflows with no issues.
I'll update the release process after this is merged.

ci: Rework `minor_version_release.yml` to create PR that bumps version

---

e2e/pipelines/test_evaluation_pipeline.py

- e2e eval test failed because the FaithfulnessEvaluator expects `predicted_answers` but received only `responses`: https://github.com/deepset-ai/haystack/actions/runs/8932162279/job/24535543678
- The renaming was done in https://github.com/deepset-ai/haystack/pull/7621
- Rename the input  when it is sent to FaithfulnessEvaluator from responses to predicted_answers
- Use predicted answers instead of ground truth answers as input for FaithfulnessEvaluator
- Fixed typo in component name groundness - groundedness
- I added …

test: Rename `responses` and use preds instead of ground truth answers in e2e eval test

---

docs/pydoc/config/rankers_api.yml

N/A
Add "sentence_transformers_diversity" module to add SentenceTransformersDiversityRanker api reference
Havent tested it. This is a small change
You can try to generate docs locally to check if it works …

Add "SentenceTransformersDiversityRanker" api reference

---

haystack/components/evaluators/document_recall.py
releasenotes/notes/fix-serialization-docrecallevaluator-91ad772ffed119ed.yaml
test/components/evaluators/test_document_recall.py

- similar to #7660
this fails because the `RecallMode` Enum is not YAML-serializable:
```python
from haystack.components.evaluators.document_recall import DocumentRecallEvaluator
p = Pipeline()
p.add_component("eval", DocumentRecallEvaluator())
dump = p.dumps()
p2 = Pipeline.loads(dump)
```
- add `to_dict` method to handle the serialization
CI, new unit tests, manual test …

fix: fix serialization of `DocumentRecallEvaluator`

---

.github/labeler.yml

Do not label PRs with `2.x`, Haystack 2.0 is around for enough time now to assume that's by default

chore: Stop labelling PRs with 2.x, assuming it's default now

---

.github/workflows/stale.yml

The Stalebot workflow is properly running, but it never applies the `stale` label,
because the current configuration requires all the labels `proposal` and `community-triage` to be present.
logs: https://github.com/deepset-ai/haystack/actions/runs/9011090473/job/24758184788
Replace `only-labels` with `any-of-labels` in config.
docs: https://github.com/actions/stale?tab=readme-ov-file#any-of-labels …

chore: make Stalebot workflow work

---

haystack/dataclasses/document.py
haystack/dataclasses/sparse_embedding.py
releasenotes/notes/sparse-embedding-dataclass-d75ae1ee6d75e646.yaml

This PR changes `SparseEmbedding` so that it's a dataclass instead of a simple class.
This is done so it's easier to for libraries like FastAPI to parse the class for serialization. This also helps solve an issue with Hayhooks.
I ran unit tests.
This doesn't change in any way the class behaviour. …

refactor: Make `SparseEmbedding` a dataclass

---

haystack/components/fetchers/link_content.py
haystack/components/routers/file_type_router.py
releasenotes/notes/enhanced-mime-type-handling-182fb64a0f5fb852.yaml
test/components/routers/test_file_router.py

Enhances consistency and clarity in handling MIME types in ByteStream across Haystack. ByteStream's `mime_type` attribute gets set properly for web originating ByteStreams. In web originating ByteStream's `content_type` is still left intact in meta dictionary for backward compatibility. 
- fixes https://github.com/deepset-ai/haystack/issues/7633
- Sets `mime_type` attribute of ByteStream instead of indirect storage of MIME types within a meta dictionary. This change allows direct and uniform access to MIME types, simplifying handling for both web resources and local files.
- **Fetching and Routing Based on MIME Types**: Users can now straightforwardly fetch and route documents based on their MIME types, applying specific processing or handling routines directly:
```python
if …
```

feat: Set ByteStream's mime_type attribute for web based resources

---

haystack/components/audio/whisper_local.py
haystack/components/embedders/sentence_transformers_document_embedder.py
haystack/components/embedders/sentence_transformers_text_embedder.py
haystack/components/extractors/named_entity_extractor.py
haystack/components/rankers/sentence_transformers_diversity.py
releasenotes/notes/fix-device-deserialization-st-embedder-c4efad96dd3869d5.yaml
test/components/audio/test_whisper_local.py
test/components/embedders/test_sentence_transformers_document_embedder.py
test/components/embedders/test_sentence_transformers_text_embedder.py
test/components/extractors/test_named_entity_extractor.py
test/components/rankers/test_sentence_transformers_diversity.py

I would like to be able to specify `None` or `null` when deserializin a pipeline that uses: 
- `SentenceTransfomersTextEmbedder`
- `SentenceTransfomersDocumentEmbedder`
- `NamedEntityExtractor`
- `SentenceTransformersDiversityRanker`
Currently I get an error if I try and I'm required to provide a specific device following the `ComponentDevice.to_dict()` format. 
Following implementation that is used for ExtractiveReader to overcome the same problem. 
- added two unit tests …

fix: Update device deserialization for components that use local models

---

haystack/components/extractors/named_entity_extractor.py
releasenotes/notes/named-entity-extractor-serde-improvements-28b594be5a38f175.yaml
test/components/extractors/test_named_entity_extractor.py

Fixes serialization and deserialization (serde) in the `NamedEntityExtractor` component. Important for usecases where  `NamedEntityExtractor` needs to be serialized to a pipeline yaml file.
- fixes https://github.com/deepset-ai/haystack/issues/7666
- Modified the serialization method to correctly serialize the backend type by calling `.name` on the `_backend.type` attribute, ensuring that it is stored as a string rather than an object reference.
- Adjusted the deserialization method to transform the `backend` string back into the correct `NamedEntityExtractorBackend` enumeration before attempting to use it in constructing a `NamedEntityExtractor` instance.
- Included a new test ensuring that the `NamedEntityExtractor` can be serialized and deserialized correctly, particularly when used …

fix: Fix NamedEntityExtractor serde

---

haystack/core/pipeline/pipeline.py
releasenotes/notes/pipeline-run-fix-extra-outputs-a6c750a91faaa8fd.yaml
test/core/pipeline/test_intermediate_outputs.py

- fixes #7695
Previously, we wouldn't add the accumulated outputs of intermediate components to the final pipeline output if the latter contained the name of the former. This approach was not fined-grained enough to account for components that returned multiple outputs and only some which were used as inputs to the other components. 
The PR fixes this by iterating over the individual outputs of each intermediate component and adding any missing ones to the final output.
Unit test, repro code …

fix: `Pipeline.run` correctly returns all outputs when the `include_outputs_from` parameter is used

---

haystack/components/evaluators/context_relevance.py
haystack/components/evaluators/faithfulness.py
releasenotes/notes/avoid-LLM-based-evaluators-returning-NaN-579bc4593febb691.yaml
test/components/evaluators/test_context_relevance_evaluator.py
test/components/evaluators/test_faithfulness_evaluator.py

- fixes #7671
- unit tests, 
- integration tests
- manual verification

fix: avoid FaithfulnessEvaluator and ContextRelevanceEvaluator return `Nan`

---

haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline.py

This PR has the only purpose to clean up the logic of the `run` method by moving code around, no functional changes.
It should also make the code more testable, but knowing we have #7611 pending, I'm not touching them.
There's more code to move, but I want to keep the diff small to speed up the review process.
Existing tests …

chore: Simplify `Pipeline.run` method by moving code to the base class

---

haystack/components/generators/azure.py
haystack/components/generators/chat/azure.py
releasenotes/notes/fix-azure-generators-serialization-18fcdc9cbcb3732e.yaml
test/components/generators/chat/test_azure.py
test/components/generators/test_azure.py

- fixes #7693
- adding the missing `@component` decorator
- run all unit and integration tests

fix: Adding missing `component` decorator to AzureOpenAIGenerator

---

haystack/utils/type_serialization.py
releasenotes/notes/improve-type-serialization-support-18822a5b978b1e77.yaml
test/utils/test_type_serialization.py

Improves type serialization, particularly focusing on better support for PEP 585 types (e.g., `list[Document]`, including nested versions). This enhancement is crucial for enabling more accurate serialization of generics and nested types, which directly impacts the ability to match types like `list[X]` and `List[X]` in component connections after serialization. 
- fixes https://github.com/deepset-ai/haystack/issues/7609
- **`haystack/utils/type_serialization.py` modification:** Introduced better handling of PEP 585 types 
- **Test enhancements:** Added multiple test cases in `test/utils/test_type_serialization.py` to verify the serialization and deserialization of PEP 585 types, including more complex nested types like `list[list[int]]`.
- **Serialization of PEP 585 and nested types:** …

fix: Adjust serialization to handle PEP-585 generic types

---

haystack/components/readers/extractive.py
releasenotes/notes/add-inf-mode-reader-e6eb79920e73c956.yaml

Adds inference mode to model call of the ExtractiveReader. This prevents gradients from being calculated during inference time in pytorch which saves on resources. This addition does not change the output of the model.
- I …

feat: Add inference mode to ExtractiveReader

---

haystack/components/preprocessors/document_cleaner.py
releasenotes/notes/add-keep-id-to-document-cleaner-2a9854b5f195bb78.yaml
test/components/preprocessors/test_document_cleaner.py

- fixes #7557
The `DocumentCleaner` has now an optional property called `keep_id` that keeps the original id of all the input documents.
Added one extra unit test and edited the one that checks correct initialisation of the object.
This PR is a clone of the #7618 original PR that cannot be reopened because I messed up with git. 
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_conduct.txt) ✅
- I have updated the related issue with new insights and changes ✅
- I added unit tests and updated the docstrings ✅ …

feat: add keep-id to DocumentCleaner

---

haystack/components/converters/html.py
pyproject.toml
releasenotes/notes/trafilatura-html-conversion-e9b9044d31fec794.yaml
test/components/converters/test_html_to_document.py

- fixes #7605
As discussed offline, we want to replace boilerpy3 with Trafilatura, which is robust and well-maintained.
During my recent work on AutoQuizzer, I battle-tested this library, which worked well for a diverse range of HTML pages.
I'm trying not to break the existing API. The implementation is simpler.
CI, new tests. …

feat: change HTML conversion backend from boilerpy3 to Trafilatura

---

releasenotes/notes/feat-widen-support-of-envars-vars-on-openai-components-efe6203c0c6bd7b3.yaml

The "issues" section of release notes has the following meaning:
https://github.com/deepset-ai/haystack/blob/7181f6b7e9792f0e24dff1602522200609c258fb/releasenotes/config.yaml#L28
I'm removing this section from a recently introduced release note.

chore: fix release note

---

haystack/components/evaluators/llm_evaluator.py
haystack/components/generators/openai.py

- fixes [#7713](https://github.com/deepset-ai/haystack/issues/7713)
- when the LLMEvaluator uses OpenAI API make the call with the the `seed` parameter set, to force more determinism
- run several evaluations + LLMEvaluator tests

feat: LLMEvaluator uses OpenAI API with the the `seed` parameter

---

haystack/components/websearch/serper_dev.py
releasenotes/notes/serperdev-more-robust-229ba25c8fc9306d.yaml
test/components/websearch/test_serperdev.py

- fixes https://github.com/deepset-ai/haystack-tutorials/actions/runs/9187125815/job/25264156611
Do not assume `snippet` is always present in Serper's response
Unit tests …

fix: make SerperDevWebSearch more robust

---

haystack/components/evaluators/context_relevance.py
haystack/components/evaluators/faithfulness.py
haystack/components/evaluators/llm_evaluator.py
test/components/evaluators/test_llm_evaluator.py

This adds an optional `progress_bar` to the `run()` method of the base LLMEvaluator class and its dependents. Depending on the dataset, a faithfulness or context relevance evaluation can take several minutes, and the user can opt to be informed of ongoing progress.

style: adding progress bar to llm-based evaluators

---

haystack/components/readers/extractive.py
releasenotes/notes/reader-crash-no-docs-53085ce48baaae81.yaml
test/components/readers/test_extractive.py

- fixes #7731 
Immediately return from `run()` if the list of input documents is empty.
Unit tests
There are a couple of minor, unrelated changes.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installat …

fix: exit early if the component receives no documents

---

haystack/components/joiners/document_joiner.py
releasenotes/notes/fix-documentjoiner-topk-173141a894e5c093.yaml
test/components/joiners/test_document_joiner.py

- fixes #7702
The issue was caused by the `DocumentJoiner` component's `run` method not accepting the `top_k` parameter. This resulted in a `ValueError` when trying to pass `top_k` at query time using `pipe.run("DocumentJoiner": {"top_k": top_k})`.
To solve this issue, I updated the `run` method to accept the `top_k` parameter and use it to limit the number of returned documents. The relevant lines in the `run` method were modified to check for the `top_k` parameter and apply it accordingly.
I added a unit test to the `test_document_joiner.py` file to ensure the `top_k` parameter works correctly when provided in the `run` method. The test verifies that the `run` method limits the number of returned documents to the specified `top_k` value.
None …

feat: allow DocumentJoiner to accept top_k parameter in run method

---

haystack/components/generators/azure.py
haystack/components/generators/chat/azure.py
releasenotes/notes/azure-openai-generator-timeout-c39ecd6d4b0cdb4b.yaml
test/components/generators/chat/test_azure.py
test/components/generators/test_azure.py

- fixes #7722 
Add a `timeout` argument to the `AzureOpenAIGenerator`
Unit tests

add timeout to AzureOpenAIGenerator

---

haystack/components/evaluators/context_relevance.py
haystack/components/evaluators/faithfulness.py
haystack/components/evaluators/llm_evaluator.py
releasenotes/notes/add-failsafe-for-LLM-based-evaluators-34cdc183ab545315.yaml
test/components/evaluators/test_context_relevance_evaluator.py
test/components/evaluators/test_faithfulness_evaluator.py
test/components/evaluators/test_llm_evaluator.py

- fixes [#7712](https://github.com/deepset-ai/haystack/issues/7712)
The LLM-based evaluators can fail due to:
- an error when making a call the LLM 
- an output returned by the LLM which is an invalid JSON
This PR adds safeguards to LLM-based evaluators:
- If an LLM-based evaluator (e.g., `Faithfulness` or `ContextRelevance`) is initialised with `raise_on_failure=False`, and if a call to an LLM fails or an LLM outputs an invalid JSON, it returns `np.nan` and continues the evaluation. 
- The user being notified with a warning, and with the number of requests that failed.

fix: failsafe for non-valid json and failed LLM calls

---

test/tracing/test_tracer.py

Rewrite some telemetry testing that make `pytest` to not run.
Technically those tests are not causing failures since they're not technically running at all for `pytest`. Thought they might cause other plugins to fail.
Example failure:
```
ImportError:
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/silvanocerza/Library/Application Support/hatch/env/virtual/haystack-ai/ZmvGEzQW/test/lib/python3.12/site-packages/_pytest/main.py", line 285, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File …
```

test: Fix telemetry tests so they don't fail

---

haystack/components/builders/chat_prompt_builder.py
haystack/components/builders/dynamic_chat_prompt_builder.py
releasenotes/notes/add-chatpromptbuilder-19acd18a6486909d.yaml
test/components/builders/test_chat_prompt_builder.py

- follow up from https://github.com/deepset-ai/haystack/pull/7655 regarding `ChatPromptBuilder`
This extends ChatPromptBuilder to change prompts at query time.
```python
default_template = [ChatMessage.from_user("This is the default prompt: \\n Query: {{query}}")]
prompt_builder = ChatPromptBuilder(template=default_template)
pipe = Pipeline()
pipe.add_component("prompt_builder", prompt_builder)
result = pipe.run(
data={
"prompt_builder": {
"query": "Where does the speaker live?",
},
}
)
result = pipe.run(
data={
"prompt_builder": {
"template": [ChatMessage.from_user("This is the dynamic prompt:\\n Query: {{query}}")],
"query": "Where does the speaker live?",
},
}
)
```
- added tests
- There are no breaking changes
- `DynamicChatPromptBuilder` is being deprecated
- I have read the …

feat: add ChatPromptBuilder, deprecate DynamicChatPromptBuilder

---

haystack/components/extractors/named_entity_extractor.py
releasenotes/notes/fix-named-entity-entity-extractor-backend-enum-2e64e25f8d7f1b08.yaml

Change `NamedEntityExtractorBackend` to better handle conversion of strings to enum values.
This fixes a crash in `NamedEntityExtractor` when using a string as `backend` argument when creating the Component in Python 3.12.
I ran tests locally using Python 3.12.
CI runs tests using Python 3.8 so this won't fail, I recommend running tests locally with Python 3.12 just to be sure. …

fix: Fix `NamedEntityExtractor` crashing in Python 3.12 if constructed using a string backend argument

---

haystack/components/converters/pdfminer.py
releasenotes/notes/fix-pdfminer-converter-54e6d7e1a82d6e7b.yaml

- fixes #7749
changed the PDFMinerToDocument converter output_type to 'documents'
manually ran my repro from the issue

fix: use correct output annotation for pdfminer converter

---

haystack/components/audio/whisper_local.py
haystack/components/evaluators/sas_evaluator.py
haystack/components/extractors/named_entity_extractor.py
haystack/components/generators/chat/hugging_face_local.py
haystack/components/generators/chat/hugging_face_tgi.py
haystack/components/generators/hugging_face_local.py
haystack/components/generators/hugging_face_tgi.py
haystack/components/rankers/sentence_transformers_diversity.py
haystack/components/rankers/transformers_similarity.py
haystack/components/readers/extractive.py
releasenotes/notes/make-warm-up-consistent-0247da81b155b136.yaml
test/components/generators/test_hugging_face_local_generator.py
test/components/rankers/test_sentence_transformers_diversity.py
test/components/rankers/test_transformers_similarity.py

- fixes #7021 
Make the usage of `warm_up` consistent according to these criteria:
- Calling `run()` on a component that has not been warmed up raises a `RuntimeError`
- The warmup check is performed first thing in the `run()` method
Sometimes the "warm up" state cannot be determined by evaluating a single field (e.g. `self._model is not None`). In those cases I introduced a boolean field `self._warmed_up`. …

chore: make `warm_up()` usage consistent

---

docs/pydoc/config/joiners_api.yml
haystack/components/joiners/__init__.py
haystack/components/joiners/branch.py
releasenotes/notes/add-branch-joiner-037298459ca74077.yaml
test/components/joiners/test_branch_joiner.py

- fixes n/a
Introduce `BranchJoiner` and deprecate the `Mulitplexer`

Add BranchJoiner and deprecate Multiplexer

---

haystack/components/builders/dynamic_chat_prompt_builder.py
haystack/components/builders/dynamic_prompt_builder.py

Both Dynamic Builders are being deprecated in 2.2 and will be removed in 2.4.

fix: update Haystack version when Dynamic Builders are to be removed

---

e2e/pipelines/test_named_entity_extractor.py

- Fixes https://github.com/deepset-ai/haystack/issues/7761
- Check for RuntimeError instead of ComponentError
I am not convinced there really is a need for an end-to-end test here. We're not testing the warm up of any of the other components with end-to-end tests. In my understanding it's also not a good end-to-end because it doesn't do more than initializing. 
I suggest we merge this fix so that the end-to-end test runs through again. We can open a separate issue about making all the tests in the fail unit or integration tests and only keep test_ner_extractor_in_pipeline as e2e test.
- …

test: Check for RuntimeError instead of ComponentError in NamedEntityExtractor test

---

test/core/pipeline/features/README.md
test/core/pipeline/features/conftest.py

This PR changes a bit the boilerplate functions that handle running the `Pipeline` in the `run` tests.
While I was migrating the other tests I noticed that some tests run a `Pipeline` multiple times, mostly when it has conditional branching, loops, and the likes. I thought of just running a `Pipeline` once but some actually require to be run with different inputs to actually verify their correct behaviour.
I tried using `@pytest.mark.parametrize` on the `@given` steps that define the `Pipeline` to test but that doesn't work, `pytest-bdd` forbids that.
Another option would have been to define the function that returns the `Pipeline` multiple times as different `@given` steps, one for each different input. That would be more error prone in my opinion as the `Pipeline` would be defined …

test: Support multiple runs for Pipeline run tests

---

haystack/document_stores/in_memory/document_store.py
releasenotes/notes/in-memory-docstore-memory-share-82b75d018b3545fc.yaml
test/components/retrievers/test_filter_retriever.py
test/components/retrievers/test_in_memory_bm25_retriever.py
test/document_stores/test_in_memory.py

This PR adds the `index` argument in `InMemoryDocumentStore`.
If two or more different instances of `InMemoryDocumentStore` use the same `index` they will use the same memory, so writing or deleting a document from one will affect the others too.
I added some tests and run all existing tests.
This will bring two extra possibile enhancements. We can change the default `Pipeline` templates to use `InMemoryDocumentStore` with the same index, thus removing the dependency to `chroma-haystack`. This will also make it possible to remove some steps from the [Pipeline templates](https://docs.haystack.deepset.ai/docs/pipeline-templates) documentation.  …

feat: Add memory sharing between different instances of `InMemoryDocumentStore`

---

haystack/components/preprocessors/document_splitter.py
haystack/components/preprocessors/text_cleaner.py

- fixes #7736 
Tested the examples:)

docs: add examples to preprocessors

---

test/core/pipeline/features/README.md
test/core/pipeline/features/conftest.py
test/core/pipeline/features/test_run.py

- Part of #7611
Add a new `PipelineRunData` dataclass that holds all the information necessary to run a `Pipeline` and verify its correct execution. This dataclass will be returned by the functions marked with `@given` together with the `Pipeline` instance to run.
I also added a `_PipelineResult` dataclass used in the boilerplate code that runs and verifies the `Pipeline.run()` execution.
I also changes slightly the tests for the "bad" `Pipeline` runs as they were unnecesssarily returning the expected `Exception` class too. This made it simpler to structure the `PipelineRunData` dataclass. …

test: Rework `Pipeline.run()` tests to ease declaration with dataclasses

---

e2e/pipelines/test_hybrid_doc_search_pipeline.py
haystack/document_stores/in_memory/document_store.py

- fixes #7788
This PR fixed the `InMemoryDocumentStore` so that all the information that must be shared with other instances that use the same index is actually shared.
I fixed and ran the end to end test that was failing.
I'm ignoring the release notes as this features has not be released yet. …

fix: `InMemoryDocumentStore` not sharing some document stats with other instances

---

docs/pydoc/config/builders_api.yml
haystack/components/builders/__init__.py

- fixes #7794
- add `ChatPromptBuilder` to `__init__.py`
- add it to pydoc configuration

chore: export `ChatPromptBuilder` and add it to pydoc config

---

haystack/core/pipeline/predefined/indexing.yaml.jinja2
haystack/core/pipeline/predefined/rag.yaml.jinja2
pyproject.toml
test/core/pipeline/test_pipeline.py
test/core/pipeline/test_templates.py

Change indexing and rag default templates to use shared `InMemoryDocumentStore` instead of `ChromaDocumentStore`.
N/A …

chore: Update indexing and rag default templates to use `InMemoryDocumentStore`

---

haystack/components/evaluators/context_relevance.py

The ContextRelevanceEvaluator doesn't use the answer as stated in the docstring.

docs: fixing ContextRelevance documentation

---

haystack/utils/import_utils.py
releasenotes/notes/safe-fetch-4ba829def3241eec.yaml

- fixes deepset-ai/haystack-tutorials#326
Add `fetch_archive_from_http` to fetch zip or gzip archives.
This function has been previously removed for security reasons as it also supported tar files unpacking via `tarfile` module.
This version drops support for tar files so it's safe to use.
I didn't ran any test, this function wasn't tested previously.
I'll make a new release after this is merged. …

feat: Add `fetch_archive_from_http` to fetch zip or gzip archives

---

haystack/components/converters/html.py
pyproject.toml
releasenotes/notes/change-trafilatura-dependency-575985a2271c8370.yaml

This PR removes `trafilatura` as a direct dependency and adds it as a lazily imported one.
The dependency has been added as a test dependency.
This is done because `trafilatura` is not a package available on Conda. Having it as a direct dependency prevents us from releasing Haystack on Conda.
See failures on conda-forge/haystack-ai-feedstock#10
N/A …

chore: Change trafilatura dependency to use lazy import

---

haystack/utils/__init__.py

- fixes failures in tutorials tests https://github.com/deepset-ai/haystack-tutorials/actions/runs/9392855560/job/25867859115
- export the `fetch_archive_from_http` utility function to utils/__init__.py
No need to test this …

Add fetch_archive_from_http to utils/__init__.py

---

haystack/nodes/retriever/_embedding_encoder.py
pyproject.toml
releasenotes/notes/specify-sentence-transformer-model-version-55b633e8b294189c.yaml

- fixes #7810 
Manual testing locally. 
I would appreciate any pointers to where you might like me to include a test.

fix: specify embedding retriever version

---

haystack/evaluation/eval_run_result.py
test/evaluation/test_eval_run_result.py

The DataFrame generated by the EvaluationRunResult.score_report() is missing the column `metrics`.

fix: `EvaluationRunResult.score_report()` is missing the `metrics` column 

---

haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
releasenotes/notes/fix-conditional-branching-a0f0d65c7ac97f71.yaml
test/core/pipeline/features/pipeline_run.feature
test/core/pipeline/features/test_run.py
test/core/pipeline/test_pipeline.py

Fixes 
- #7744
- #7533.
This PR changes a bit how we collect the initial list of Component that can run when calling `Pipeline.run()`.
Instead of getting only Component that have no inputs, or have a least one input that is not connected or is variadic, we also get Components that receive inputs from the user.
It also changes how we handle conditional outputs. Now if a Component with a conditional output runs and doesn't send anything to a certain socket we remove from `to_run` and `waiting_for_input` all the Components connected to that socket.
I updated tests locally and ran unit, `Pipeline.run()` and e2e tests.
N/A …

fix: Fix running `Pipeline` with conditional branch and Component with default inputs

---

e2e/pipelines/test_evaluation_pipeline.py

a column `metrics` was missing

fix: end2end evaluation pipeline failing

---

haystack/components/evaluators/llm_evaluator.py
releasenotes/notes/llm-evaluator-serde-fix-aa5b27d2524db9c5.yaml
test/components/evaluators/test_llm_evaluator.py

- fixes #7768
The `inputs` init parameter of the `LLMEvaluator` component accepts a list of tuples containing an input name and its corresponding type. Previously, we were saving this parameter as-is - problematic due to the serialization code supporting neither raw tuples nor raw types. This PR fixes the above issue by converting the tuples to lists and the correctly serializing the types.
Unit tests …

fix: Fix `LLMEvaluator` serialization

---

.github/workflows/docker_release.yml

- fixes #7833
Since the workflow doesn't seem intended for forks, I decided to disable it altogether for runs outside `deepset-ai` org.
I haven't.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installat …

ci: only run Docker release workflow under GitHub org

---

haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline.py

Part of #7614
Isolate and make slightly safer the logic to check if a Component can run.
Added a new unit test and run test.
N/A …

refactor: Isolate logic to check if a Component can run

---

haystack/components/converters/docx.py
test/components/converters/test_docx_file_to_document.py

- fixes errors like this: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/9491529913/job/26157131998
- `python-docx` is an optional dependency, but we are explicitly using its `DocxDocument` type in the signature of `_get_docx_metadata`
- use forward reference
CI, local tests …

fix: `DocxToDocument` - use forward reference

---

haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline.py

Isolate logic that distributes Components output after run.
This also slightly changes the `_run_component()` method to resetting variadics as it was done in the wrong place.
I added tests and ran them locally.
N/A
- I ran …

refactor: Isolate logic that distributes Components output after run

---

haystack/marshal/yaml.py
releasenotes/notes/serialization-tuple-support-ffe176417e7099f5.yaml
test/marshal/__init__.py
test/marshal/test_yaml.py

- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/694
Currently, serialization to YAML does not support Python tuples. This PR extends support to them on the marshaller level, allowing all components and integrations to take advantage of it.
All tests …

feat: Extend YAML serialization to allow Python tuples

---

.github/workflows/tests.yml
haystack/__init__.py

- no issue, trying to restore the dependency cache that was removed as ineffective in #7754 
- The venv created by the unit tests is carried over and reused by the integration tests and the linting job. 
- This saves about one minute (pulling the cache vs. installing packages).
- The cache is short-lived, it's created at every commit. …

ci: add dependency cache step

---

pyproject.toml
releasenotes/notes/pin-numpy-2304f88504d5041a.yaml

Several failures in core integrations: Chroma, Fastembed, Optimum and Qdrant.
Pin numpy<2
CI

chore: pin numpy<2; tenacity!=8.4.0

---

haystack/__init__.py
haystack/logging.py
releasenotes/notes/fix-auto-tracing-51ed3a590000d6c8.yaml
releasenotes/notes/structlog-contextvars-c13bb3c59a6a92c7.yaml
test/test_logging.py

- **fix: fix auto-tracing** (this should work out of the box but so far didn't, see [docs](https://docs.haystack.deepset.ai/docs/tracing))
- **feat: add context var logging to structlog**
- **docs: add release notes**
- I ran …

fix: enable tracing upon import / improve logging setup

---

haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline.py

Part of #7614.
This PR isolates the logic that moves Components from `waiting_for_input` to `to_run` queue when `to_run` is empty and `waiting_for_input` is not.
I added unit tests and ran tests locally.
There's some formatting changes too as we changed the default formatted from `black` to `ruff`. …

refactor: Isolate logic that finds next runnable component waiting for input

---

docs/pydoc/config/evaluation_api.yml
haystack/evaluation/__init__.py
haystack/evaluation/base.py
haystack/evaluation/eval_run_result.py

- fixes #7829
- Add docstrings for `EvaluationRunResult`
- Move the abstract class to a dedicated module

docs: add docstrings for EvaluationRunResult

---

haystack/components/evaluators/context_relevance.py
haystack/components/evaluators/faithfulness.py
releasenotes/notes/fix-llmevaluator-subclass-deserialization-c633b2f95c84fe4b.yaml
test/components/evaluators/test_context_relevance_evaluator.py
test/components/evaluators/test_faithfulness_evaluator.py

- related to https://github.com/deepset-ai/haystack/issues/7824
- fixes https://github.com/deepset-ai/haystack/issues/7884
The subclass of the `LLMEvaluator` component were not using the `@component` decorator, which prevented them from being added to the internal component registry. This caused a failure when deserializing a pipeline that contained on those components. Furthermore, both subclasses were missing `to_dict` methods, which lead to the wrong base class method being invoked resulting in yet another failure.
Unit tests …

fix: Fix deserialization of pipelines that contain `LLMEvaluator` subclasses

---

haystack/core/pipeline/base.py

Part of #7614
Move the following functions out of `_enqueue_next_runnable_component`:
* `_is_lazy_variadic`
* `_has_all_inputs_with_defaults`
* `_add_missing_input_defaults`
They're going to be used in other functions.
N/A
- I …

Move utility functions from `_enqueue_next_runnable_component`

---

haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline.py

Part of #7614
Isolate the logic to check if `Pipeline.run()` is stuck in a loop.
Added tests and ran them locally.
N/A

Isolate logic to check if we're stuck in a loop when running `Pipeline`

---

haystack/document_stores/types/filter_policy.py
releasenotes/notes/add-apply_filter_policy-function-ae3152e6afe0ca57.yaml
test/document_stores/test_filter_policy.py

Added the apply_filter_policy function to standardize the application of filter policies across all document store-specific retrievers, allowing for consistent handling of initial and runtime filters based on the chosen policy (replace or merge).
Add unit tests for  `apply_filter_policy` function

feat: Add apply_filter_policy function

---

haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline.py

Part of #7614
Depends on #7900
Add utility function to move Components from `waiting_for_input` to `to_run` queue.
This is not used as of now and will be used in upcoming PRs.
Added tests and ran them locally.
N/A …

Add utility function to move `Component`s in queues

---

haystack/components/embedders/backends/sentence_transformers_backend.py
haystack/components/evaluators/sas_evaluator.py
haystack/components/rankers/sentence_transformers_diversity.py
pyproject.toml
releasenotes/notes/update-sentence-transformers-import-error-msg-895b8ed2355ae2fe.yaml

While helping a user in #7850, I discovered that we are suggesting to install `sentence-transformers>=2.2.0`,
while the parameter `trust_remote_code` (introduced in Haystack in #7356) is only compatible with >=2.3.0 (https://github.com/UKPLab/sentence-transformers/issues/2272).
- update the import error message
- update also the test dependencies in pyproject
CI …

chore: update sentence transformers import error message

---

haystack/core/component/component.py
test/core/pipeline/test_pipeline.py

The pipeline deserialization callbacks make use of an internal hook to override the init parameters of components during the deserialization process. Prior to this PR, the hook would get invoked incorrectly under the following conditions:
- The code path with the hook is taken.
- The component's c'tor is invoked with the overridden init parameters.
- Inside the c'tor, another component is directly instantiated.
This causes the hook to be invoked yet again but with the same callback, which is bound to the first component's name. We fix this by using an additional flag to detect if we're still executing the hook and exiting early.
Unit test …

fix: Prevent component pre-init hook from being called "recursively"

---

haystack/components/evaluators/sas_evaluator.py
releasenotes/notes/check-for-None-SAS-eval-0b982ccc1491ee83.yaml
test/components/evaluators/test_sas_evaluator.py

- fixes #7842
Properly raises ValueError if any input in input list for predicted_answers contains None.
Checked for Value Error raise.
N/A …

fix: check for None in SAS eval input

---

haystack/document_stores/in_memory/document_store.py
releasenotes/notes/add-serialization-to-inmemorydocumentstore-2aa4d9ac85b961c5.yaml
test/document_stores/test_in_memory.py

- fixes #7887 
Added two `save_to_disk` and `load_from_disk` functions.
Added a test `test_save_to_disk_and_load_from_disk`
The test has an issue due to `cls.from_dict` methods somehow caching `InMemoryDocumentStore.values()`. I added an overwrite policy to avoid this but it is not the cleanest way. Not sure what is happening. …

feat: InMemoryDocumentStore serialization

---

haystack/components/evaluators/document_map.py
haystack/components/evaluators/document_mrr.py
releasenotes/notes/fix-issue-7758-d35b687ca226a707.yaml
test/components/evaluators/test_document_map.py

- fixes #7758
Fixed errors of MRREvaluator:
* Corrected the logic for calculation of MRR 
* Added a flag to break the loop when condition is fulfilled
* Optimized the loops
Fixed errors of MAPEvaluator:
* Corrected the logic for calculation of MAP
* Optimized the loops
Fixed errors in pytest file of `test_document_map.py`:
* Corrected values for `test_run_with_complex_data()`
Ran unit tests for both evaluators
Verify the correctness of the calculated scores for an example.
- …

bug: fix MRR and MAP calculations

---

haystack/components/evaluators/context_relevance.py
releasenotes/notes/improve-ContextRelevance-evaluator-prompt-6b80229c99e3bc38.yaml
test/components/evaluators/test_context_relevance_evaluator.py

- fixes #7803
- added a few more examples containing multiple non-relevant statements
- added one more line to the prompt mentioning that each statement should be scored
- run unit tests and live test, also added one more live test
- I ran …

fix: explicitly tell `ContextRelevanceEvaluator` that each statement should be scored

---

haystack/components/generators/openai.py
releasenotes/notes/fix-serialization-openai-generator-cf7e9a04562dde75.yaml
test/components/generators/test_openai.py

- fixes #7903 
Add the missing `organization` parameter to the serialization function.
Updated the unit tests to check `organization` parameter during serialization and deserialization.
Though about it , but makes sense to not serialize `timeout` and `max_retries` parameters to allow dynamic configuration as also mentioned in the issue. …

Add the missing parameter for serialization

---

test/conftest.py

- fixes #7923
Disable tracing in CI to fix failures like these:
```
ERROR    ddtrace.internal.writer.writer:writer.py:399 failed to send, dropping 12 traces to intake at http://localhost:8126/v0.5/traces after 3 retries
```
https://github.com/deepset-ai/haystack/actions/runs/9664504239/job/26659322073#step:5:117
N/A …

ci: Disable tracing when running tests

---

haystack/core/pipeline/base.py
test/core/pipeline/test_pipeline.py

Part of #7614
Change `_add_missing_input_defaults` so it handles Components that have receive no inputs yet.
Added tests and ran them locally.
Depends on #7925.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTIN …

Make `_add_missing_input_defaults` less error prone and add tests

---

haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline.py

Add a `_find_next_runnable_lazy_variadic_or_default_component` to find a Component with lazy variadic input or all inputs with default values. 
I added tests and ran them locally.
N/A …

Add method to find Component with lazy variadic input or all inputs with defaults

---

haystack/components/converters/__init__.py
haystack/components/converters/docx.py
releasenotes/notes/docxtodocument-rename-3acf592c89aea430.yaml
test/components/converters/test_docx_file_to_document.py

Update name to `DOCXToDocument` from `DocxToDocument` to be consistent with the naming format of other converters. This was decided on internally. …

chore: Capitalize DOCX in DOCXToDocument converter

---

haystack/components/fetchers/link_content.py
releasenotes/notes/link-content-fetcher-enhancements-49babe1c60888043.yaml
test/components/fetchers/test_link_content_fetcher.py

Enhances `LinkContentFetcher` to broaden its content handling capabilities. The primary motivation behind these changes is to allow more content type support utilizing pattern matching for content types and allow fetching web content that includes text, applications, audio, and video files.
Direct motivation for this enhancement was an experiment to fetch an audio file and transcribe it via Groq i.e:
```
from haystack.components.audio import RemoteWhisperTranscriber
from haystack.components.fetchers import LinkContentFetcher
from haystack.utils import Secret
transcriber = RemoteWhisperTranscriber(Secret.from_env_var("GROQ_API_KEY"),
api_base_url="https://api.groq.com/openai/v1",
model="whisper-large-v3")
pipe = Pipeline()
pipe.add_component("fetcher", …
```

feat: Improve LinkContentFetcher content type handling

---

haystack/components/preprocessors/document_splitter.py
releasenotes/notes/add-split_id_and_overlap_to_DocumentSplitter-8180ad8f13495741.yaml
test/components/preprocessors/test_document_splitter.py

- fixes [#7389](https://github.com/deepset-ai/haystack/issues/7389)
When a `split_overlap` is set each produced chunk Document will have information:
- about the `split_id` allowing an ordering over the document chunks
- each document chunk will have in the `meta` the `_split_overlap`, telling with which other docs it overlaps and on what range
- added new unit tests, did manual verification and  run integration tests …

feat : adding `split_id` and `split_overlap` to `DocumentSplitter`

---

haystack/core/pipeline/pipeline.py

Adjusting code due to new ruff version enforces more strict linting.
```python
if expected_inputs != current_inputs:
return False
return True
```
now has to be:
```python
return expected_inputs == current_inputs
```
run local tests + linting and typing …

fix: adjusting code due to new ruff version enforcing more strict linting

---

haystack/components/evaluators/llm_evaluator.py
releasenotes/notes/adding-metadata-info-from-OpenAI-f5309af5f59bb6a7.yaml
test/components/evaluators/test_context_relevance_evaluator.py
test/components/evaluators/test_faithfulness_evaluator.py
test/components/evaluators/test_llm_evaluator.py

- fixes [#7905](https://github.com/deepset-ai/haystack/issues/7905)
pass the `meta` entry from openai api to the result for all the LLM-based evaluators, containing the following fields:
- model
- prompt tokens
- answer tokens
- total tokens
manual veritifcation + run local tests + end2endtests …

feat: LLM-based evaluators return meta info from OpenAI

---

haystack/components/joiners/document_joiner.py
releasenotes/notes/add-distribution-based-rank-fusion-mode-JoinDocuments-6fca30b82fd535ce.yaml
test/components/joiners/test_document_joiner.py

- fixes #7914 
How it works:
```
from haystack import Document
from haystack.components.joiners.document_joiner import DocumentJoiner
joiner = DocumentJoiner(join_mode="distribution_based_rank_fusion")
documents_1 = [
Document(content="a", score=0.6),
Document(content="b", score=0.2),
Document(content="c", score=0.5),
]
documents_2 = [
Document(content="d", score=0.5),
Document(content="e", score=0.8),
Document(content="f", score=1.1, meta={"key": "value"}),
Document(content="g", score=0.3),
Document(content="a", score=0.3),
]
output = joiner.run([documents_1, documents_2])
```
unit tests
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_conduct.txt …

Add Distribution based rank fusion mode

---

haystack/components/routers/conditional_router.py
releasenotes/notes/add-custom-filters-to-conditional-router-631eba8bab3c2ae7.yaml
test/components/routers/test_conditional_router.py

- fixes #7940 
Added a `custom_filters: Optional[Dict[str, Callable]]` field to the `ConditionalRouter` constructor to allow users to pass in and use custom Jinja2 filters when creating route conditions.  Also added the same field to `from_dict` to allow users to provide callables when de-serializing a `ConditionalRouter` that was serialized with custom filters.
Added 3 unit tests to `test/components/routers/test_conditional_router.py`:
- `test_custom_filter` - ensures a custom test filter works with the router
- `test_custom_filter_serialization` - ensures the router with the custom filter attribute can be serialized and de-serialized
- `test_custom_filter_bad_deserialization` - ensures that a custom exception is generated when a router with custom filers is deserialized without …

feat: add custom jinja filter handling to ConditionalRouter

---

haystack/components/converters/azure.py
releasenotes/notes/fix-azure-ocr-bytestream-meta-0d2c8e6ea761b791.yaml
test/components/converters/test_azure_ocr_doc_converter.py

fix: meta from ByteStream input for AzureOCRDocumentConverter

---

haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline.py

Part of #7614
Split `_dequeue_components_that_received_no_input` into two separate functions, one to find the Components and one to remove them form queues.
I added tests and run them locally.
N/A …

Split `_dequeue_components_that_received_no_input` into separate functions

---

haystack/components/generators/azure.py
releasenotes/notes/max-retries-for-AzureOpenAIGenerator-0f1a1807dd2af041.yaml
test/components/generators/test_azure.py

- fixes #7945
AzureOpenAIGenerator can be initiated using `max_retries`.
Unit tests
I thought it'd be a good idea also to return `max_retries` when `to_dict` is called since we are doing it for `timeout` as well. Let me know if this is not required. …

feat: Add max_retries to AzureOpenAIGenerator

---

haystack/components/evaluators/context_relevance.py
releasenotes/notes/add-deprecation-warning-context-relevance-937df7e807ac1a8d.yaml

- Adding a deprecation warning when the ContextEvaluator is initialized

fix: adding deprecation warning ContextEvaluator

---

pyproject.toml
releasenotes/notes/add-haystack-experimental-dependency-96ff02e71bc2af13.yaml

Adds haystack-experimental dependency so that users then don't need to manually install the experimental features via `pip install haystack-experimental` but instead automatically have them when they install Haystack.
- fixes https://github.com/deepset-ai/haystack/issues/7911

feat: Add haystack-experimental dependency

---

haystack/components/embedders/azure_document_embedder.py
releasenotes/notes/retries-and-timeout-for-AzureOpenAIDocumentEmbedder-006fd84204942e43.yaml
test/components/embedders/test_azure_document_embedder.py

max_retries: if not set is read from the OPENAI_MAX_RETRIES env variable or set to 5.
timeout: if not set is read from the OPENAI_TIMEOUT env variable or set to 30.
- fixes #7945 
AzureOpenAIDocumentEmbedder now supports max_retries and timeout for initialization.
timeout can also be set using the env variable OPENAI_TIMEOUT. Default: 30
max_retries can also be set using the env variable OPENAI_MAX_RETRIES. Default: 5
Unit tests
There are a few other similar PRs for the issue. This is the 4/4 PR. …

feat: Configure max_retries and timeout for AzureOpenAIDocumentEmbedder

---

haystack/components/embedders/azure_text_embedder.py
releasenotes/notes/timeout-and-retries-for-AzureOpenAITextEmbedder-b02b760e9d6f28aa.yaml
test/components/embedders/test_azure_text_embedder.py

max_retries: if not set is read from the OPENAI_MAX_RETRIES env variable or set to 5.
timeout: if not set is read from the OPENAI_TIMEOUT env variable or set to 30.
- fixes #7945 
AzureOpenAIChatGenerator now supports  max_retries and timeout for initialization.
timeout can also be set using the env variable OPENAI_TIMEOUT. Default: 30
max_retries can also be set using the env variable OPENAI_MAX_RETRIES. Default: 5
Unit tests
There are a few other similar PRs for the issue. This is the 3/4 PR. …

feat: Configure max_retries & timeout for AzureOpenAITextEmbedder

---

haystack/components/converters/pypdf.py
releasenotes/notes/improve-pypdf-backwards-compatibility-bcc75871005e9aba.yaml
test/components/converters/test_pypdf_to_document.py

- make PyPDF converter backward compatible with Pipelines pre 2.3
- added a test

fix: make PyPDF backward compatible

---

haystack/components/generators/hugging_face_local.py
haystack/components/routers/transformers_text_router.py
haystack/components/routers/zero_shot_text_router.py
releasenotes/notes/transformer-router-from-dict-fix-04cb41b38ca61043.yaml
test/components/routers/test_transformers_text_router.py
test/components/routers/test_zero_shot_text_router.py

Update `TransformersZeroShotTextRouter` and `TransformersTextRouter` from_dict methods to work when `init_parameters` only contains required parameters. …

fix: `TransformersZeroShotTextRouter` and `TransformersTextRouter` from_dict to work with default value for huggingface_pipeline_kwargs

---

haystack/components/fetchers/link_content.py
releasenotes/notes/fix-linkcontentfetcher-encoding-6c8df3c5b09fbc50.yaml
test/components/fetchers/test_link_content_fetcher.py

- fixes https://github.com/deepset-ai/haystack/issues/7976
- use `_binary_content_handler` for content type `text/html`
- adjusted tests …

fix: LinkContentFetcher html text encoding

---

haystack/utils/filters.py
releasenotes/notes/deprecate-legacy-filters-7c9530644d972089.yaml

- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/875, https://github.com/deepset-ai/haystack-core-integrations/issues/876, https://github.com/deepset-ai/haystack-core-integrations/issues/877, https://github.com/deepset-ai/haystack-core-integrations/issues/878, https://github.com/deepset-ai/haystack-core-integrations/issues/879, https://github.com/deepset-ai/haystack-core-integrations/issues/880, https://github.com/deepset-ai/haystack-core-integrations/issues/881, https://github.com/deepset-ai/haystack-core-integrations/issues/882, https://github.com/deepset-ai/haystack-core-integrations/issues/882
Add a deprecation notice for legacy metadata filters.
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the …

chore: Deprecate legacy document/metadata filters

---

haystack/components/audio/whisper_local.py
haystack/components/embedders/sentence_transformers_document_embedder.py
haystack/components/embedders/sentence_transformers_text_embedder.py
haystack/components/extractors/named_entity_extractor.py
haystack/components/rankers/sentence_transformers_diversity.py
haystack/components/rankers/transformers_similarity.py
haystack/components/readers/extractive.py
releasenotes/notes/hf-models-from-dict-default-values-47c2c73136ea6643.yaml
test/components/audio/test_whisper_local.py
test/components/embedders/test_sentence_transformers_document_embedder.py
test/components/embedders/test_sentence_transformers_text_embedder.py
test/components/extractors/test_named_entity_extractor.py
test/components/rankers/test_sentence_transformers_diversity.py
test/components/rankers/test_transformers_similarity.py
test/components/readers/test_extractive.py

This updates the components, `TransformersSimilarityRanker`, `SentenceTransformersDiversityRanker`, `SentenceTransformersTextEmbedder`, `SentenceTransformersDocumentEmbedder` and `LocalWhisperTranscriber` `from_dict` methods to work when loading with `init_parameters` only containing required parameters. …

fix: Fix from_dict methods of components using HF models to work with default values

---

haystack/components/retrievers/__init__.py
haystack/components/retrievers/sentence_window_retrieval.py
haystack/core/serialization.py
releasenotes/notes/add-sentence-window-retrieval-5de4b0d6b2e8b0d6.yaml
test/components/retrievers/test_sentence_window_retriever.py
test/core/test_serialization.py

- fixes [#7971](https://github.com/deepset-ai/haystack/issues/7971)
- adds the sentence window retrieval technique to Haystack by levering on the `split_id` in the Document's meta.
- unit tests, integration tests and manual verification
- The idea  is to have the `SentenceWindowRetriever` as a component coming after any retriever component in the pipeline, and just implementing the logic of getting the surrounding documents based on the retrieved documents from the previous component.
- In this way we avoid having to create a BM25SentenceWindowRetriever and the EmbeddingSentenceWindowRetriever.
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_condu …

feat: add sentence window retrieval

---

haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline.py

Reorganize functions by moving most of them in `pipeline/base.py`.
Run tests locally.
N/A

Reorganize functions used by Pipeline.run

---

haystack/components/converters/pypdf.py
releasenotes/notes/improve-pypdf-backwards-compatibility-bcc75871005e9aba.yaml
test/components/converters/test_pypdf_to_document.py

This reverts commit 58b48e36eb56a896365133ab4a9d8e327989948c from PR - https://github.com/deepset-ai/haystack/pull/7996
The PR introduced a workaround to add support for deserializing pre-2.3.x pipelines containing `PyPDFToDocument` components. This was a mistake as the [original PR](https://github.com/deepset-ai/haystack/pull/7362) correctly communicated the intention to deprecate support for the affected init parameter in line with the [deprecation policy](https://docs.haystack.deepset.ai/docs/breaking-change-policy#deprecation-of-existing-features).
- I have updated the related issue …

Revert "fix: make PyPDF backward compatible (#7996)"

---

haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline.py

This only changes variables and functions names in Pipeline and its tests, logic has been left untouched.
Variables have been renamed like so:
* `to_run` -> `run_queue`
* `waiting_for_input` -> `waiting_queue`
* `before_last_waiting_for_input` -> `before_last_waiting_queue`
* `last_waiting_for_input` -> `last_waiting_queue`
* `last_inputs` -> `components_inputs`
* `inputs_by_component` -> `components_inputs`
Only one function has been renamed:
* `_init_to_run` -> `_init_run_queue`
N/A
- …

Rename variables used in Pipeline.run() for clarity

---

haystack/components/caching/cache_checker.py
haystack/components/retrievers/filter_retriever.py
haystack/components/writers/document_writer.py

- fixes #8011
- reuse a utility function to import a generic DocumentStore (or any other component) based on it's fully qualified name
- unit test
- integration tests
- end2end tests …

chore: normalise the use of `importlib` in getting an object from a qualified name string across the codebase

---

haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline.py

Add `_enqueue_waiting_component` and `_dequeue_waiting_component` functions to easily update `waiting_queue`.
Depends on #8009
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBU …

Add functions to easily update `waiting_queue`

---

haystack/components/joiners/document_joiner.py
releasenotes/notes/refactor-documentjoiner-992e662bee8ca219.yaml
test/components/joiners/test_document_joiner.py

- fixes #7922 
- Refactored `DocumentJoiner` to use enum pattern for its `join_mode` parameter instead of bare string.
- Unit tests
- Also tested using the below code
```python
from haystack import Document
from haystack.components.joiners.document_joiner import DocumentJoiner
docs_1 = [
Document(content="Paris is the capital of France.", score=0.5),
Document(content="Berlin is the capital of Germany.", score=0.4),
]
docs_2 = [
Document(content="Paris is the capital of France.", score=0.6),
Document(content="Rome is the capital of Italy.", score=0.5),
]
joiner = DocumentJoiner(join_mode="merge")
print(joiner.run(documents=[docs_1, docs_2]))
``` …

refactor: refactor DocumentJoiner to follow enum pattern for join_mode parameter

---

haystack/core/pipeline/base.py
releasenotes/notes/fix-execution-order-1121cedd9c68c560.yaml
test/core/pipeline/features/pipeline_run.feature
test/core/pipeline/features/test_run.py
test/core/pipeline/test_pipeline.py

- fixes #7985
Change the `_init_run_queue` method to check if the `Pipeline` graph is a directed and acyclic.
If it is it returns a `run_queue` that is the list of Component in the `Pipeline` graph sorted topologically. This makes the Components run in the expected order.
This fixes execution order only for `Pipeline`s that are acyclic as we can't sort nodes topologically if there are cycles.
I added a new test with the Pipeline that caused the bug as reported in the original issue.
N/A …

Fix bug in Pipeline.run() executing Components in a wrong and unexpected order

---

haystack/components/writers/document_writer.py
haystack/core/pipeline/base.py
releasenotes/notes/fix-pipeline-deserialization-a3909bb6b623c588.yaml

- fixes #7961 
The `from_dict` method of some components modifies the original payload during deserialization. Update these to prevent this behaviour.
- Ran the unit tests
- Manually verification with example in issue
N/A …

fix: Prevent `Pipeline.from_dict` from modifying the dictionary parameter passed to it

---

haystack/components/converters/html.py
releasenotes/notes/remove-htmltodocument-deprecated-init-params-2f81cf6a3b13710d.yaml

- fixes #7710 
Removes deprecated init paramters from `HTMLToDocument`. 

chore: Remove deprecated init paramters from `HTMLToDocument`

---

pyproject.toml
test/test_logging.py

- unpin structlog
- adapted the tests so that they pass (nothing critical was changed, seems structlog is now only omitted empty values correctly) …

build: unpin structlog

---

haystack/core/pipeline/pipeline.py
releasenotes/notes/deprecate-pipeline-run-debug-param-e69190338a8e041b.yaml

- fixes #8015
It's a vestigial/unused parameter in 2.x.

chore: Deprecate the `debug` parameter in `Pipeline.run`

---

haystack/components/embedders/sentence_transformers_text_embedder.py

- fixes #8064 
Standardize and improve docstrings.

Docs: Standardize and improve SentenceTransformersTextEmbedder docstrings

---

haystack/components/builders/chat_prompt_builder.py
haystack/components/builders/prompt_builder.py
haystack/components/converters/output_adapter.py
haystack/components/routers/conditional_router.py
haystack/core/pipeline/template.py
releasenotes/notes/fix-jinja-env-81c98225b22dc827.yaml
test/components/routers/test_conditional_router.py

Fix issue with Jinja templates.
N/A

fix: Fix issue that could lead to RCE if using unsecure Jinja templates

---

haystack/components/builders/dynamic_chat_prompt_builder.py
haystack/components/builders/dynamic_prompt_builder.py
releasenotes/notes/fix-jinja-env-81c98225b22dc827.yaml

Brings fix from #8095 in for dynamic prompt builders.
N/A

fix: Fix issue that could lead to RCE if using unsecure Jinja templates in dynamic prompt builders

---

haystack/components/routers/file_type_router.py

docs: clean up docstrings of FileTypeRouter

---

haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
releasenotes/notes/fix-run-loop-63bf0ffc26887e66.yaml
test/core/pipeline/features/pipeline_run.feature
test/core/pipeline/features/test_run.py
test/core/pipeline/test_pipeline.py

- fixes #8059
This changes a bit the internal run logic in two ways:
Components that have variadic input and not greedy will be put in the `waiting_queue` when outputs are distributed, previously they would have been put in the `run_queue`. This will prevent them from running before they're supposed to.
It also changes which Components we remove from the `run_queue` and `waiting_queue` when a Component produces only parts of its output, like the `ConditionalRouter`. Now we remove from the queues Components that directly would have received that output, but also their descendants. This prevents the Pipeline to get stuck in a loop waiting for inputs for Components that will never receive it.
I added a new Pipeline in the behavioural tests similar to the one reported in the above issue and …

fix: Fix infinite loop when running Pipeline

---

haystack/components/embedders/openai_text_embedder.py

docs: clean up docstrings of OpenAITextEmbedder

---

test/components/converters/test_html_to_document.py

https://github.com/deepset-ai/haystack/actions/runs/10176181855/job/28145024482
A new version of Trafilatura was released, where the extraction parameters are still valid but the extraction is handled a bit differently.
Transform the test into a real unit test: we now check that Trafilatura is called with the right parameters and not the extraction result
CI …

chore: fix `HTMLToDocument` test

---

haystack/components/embedders/backends/sentence_transformers_backend.py
haystack/components/embedders/sentence_transformers_document_embedder.py
haystack/components/embedders/sentence_transformers_text_embedder.py
haystack/components/rankers/transformers_similarity.py
releasenotes/notes/add-model-and-tokenizer-kwargs-4b7618806665f8ba.yaml
test/components/embedders/test_sentence_transformers_document_embedder.py
test/components/embedders/test_sentence_transformers_embedding_backend.py
test/components/embedders/test_sentence_transformers_text_embedder.py
test/components/rankers/test_transformers_similarity.py

- fixes #8055 
Adds `model_kwargs` and `tokenizer_kwargs` to the components `TransformersSimilarityRanker`, `SentenceTransformersDocumentEmbedder`, `SentenceTransformersTextEmbedder`
Expanded existing unit tests …

feat: Add model and tokenizer kwargs to `TransformersSimilarityRanker`, `SentenceTransformersDocumentEmbedder`, `SentenceTransformersTextEmbedder`

---

haystack/components/generators/chat/hugging_face_api.py
haystack/components/generators/chat/openai.py
haystack/components/generators/openai.py
haystack/components/generators/openai_utils.py
haystack/dataclasses/chat_message.py
releasenotes/notes/deprecate-method-to-openai-format-fb2538cf3f610d2a.yaml
test/components/generators/chat/test_hugging_face_api.py
test/components/generators/test_openai_utils.py

- part of  #8144
- deprecate `to_openai_format`
- create `_convert_message_to_openai_format` in `components/generators/openai_utils.py`
- create `_convert_message_to_hfapic_format` in `components/generators/chat/hugging_face_api.py`
CI, new tests
I'm introducing some duplication, but it might make sense, considering how different formats can evolve. …

chore: deprecate `to_openai_format` and create similar utility functions

---

haystack/components/preprocessors/document_cleaner.py
releasenotes/notes/add-unicode-normalization-and-ascii-mode-to-document-cleaner-ba536b46e499663c.yaml
test/components/preprocessors/test_document_cleaner.py

Added two new parameters to the `DocumentCleaner` Component, `unicode_normalization` and `ascii_only`.
`unicode_normalization` allows to normalize unicodes within documents using python's [unicodedata module](https://docs.python.org/3/library/unicodedata.html#unicodedata.normalize).
`ascii_only` mode converts letters with accents to regular ascii letters, removes other non ascii characters. 
I decided not to use [unidecode](https://pypi.org/project/Unidecode) since it would add a new dependency with possible unknown transformations but could be a path for improvement, adding support for languages / alphabets.
Added 2 new unit tests to the DocumentCleaner component (1 per new parameter/step).
I made the arbitrary decision to have the unicode normalization run first, followed by ascii …

feat: add unicode normalization & ascii_only mode for DocumentCleaner

---

haystack/components/builders/chat_prompt_builder.py
releasenotes/notes/fix-chat-prompt-builder-from-dict-template-none-56c91effe61e823c.yaml
test/components/builders/test_chat_prompt_builder.py

When initialisizing `ChatPromptBuilder` component `from_dict` with value {"template": None}, 
we receive `'NoneType' object is not iterable`.
Fix `from_dict` method.
Unit test …

fix: ChatPromptBuilder from_dict if template is None

---

haystack/components/preprocessors/document_cleaner.py
releasenotes/notes/fix-document-cleaner-page-tag-15c66d6433b82b0a.yaml
test/components/preprocessors/test_document_cleaner.py

- fixes https://github.com/deepset-ai/haystack/issues/8053
Split on "\f" before performing cleaning and join in the end.
End to end testing using it as a custom component in my pipeline. "\f" are not removed anymore and page number detection from Splitter is correct.
Could be optimized probably. …

fix: DocumentCleaner: keep the \f in text

---

haystack/components/generators/utils.py
releasenotes/notes/rm-serialize-callback-handler-5c104eafc6673932.yaml

These utility functions are probably a leftover.
I checked that they are not used anywhere: haystack, core-integrations, integrations page, website, tutorials, cookbook...
Some related issues (in case you are interested in history :smiley:): #6979 #6988 https://github.com/deepset-ai/haystack-core-integrations/issues/415
Remove these functions
CI …

chore: remove unused functions `serialize_callback_handler` and `deserialize_callback_handler`

---

haystack/components/converters/output_adapter.py
releasenotes/notes/fix-output-adapter-from_dict-custom-filters-none-70705cbb474fe982.yaml
test/components/converters/test_output_adapter.py

The OutputAdapter's from_dict method was failing when custom_filters = None in spite being an Optional parameter.
unit test …

fix: Output Adapter from_dict with custom_filters None

---

haystack/components/embedders/sentence_transformers_document_embedder.py
haystack/components/embedders/sentence_transformers_text_embedder.py
releasenotes/notes/release-note-42273d88ce3e2b2e.yaml
test/components/embedders/test_sentence_transformers_document_embedder.py
test/components/embedders/test_sentence_transformers_text_embedder.py

- fixes #8040 
Added `precision` parameter to SentenceTransformersEmbedder
unit tests
@anakin87 please check if it's what you expect. …

added `precision` parameter to sentence transformers embeddings

---

docs/pydoc/config/retrievers_api.yml
haystack/components/retrievers/__init__.py
haystack/components/retrievers/sentence_window_retrieval.py
releasenotes/notes/deprecate-sentence-window-retrieval-9d7f8a61429a514b.yaml
test/components/retrievers/test_sentence_window_retrieval.py

Created a stub class named SentenceWindowRetrieval that inherits from SentenceWindowRetriever. This stub issues a deprecation warning to guide users to transition to the SentenceWindowRetriever class while maintaining backward compatibility.
- Ran the existing tests
- Added new tests to check inheritance in SentenceWindowRetrieval
NA …

chore: deprecate SentenceWindowRetrieval

---

haystack/components/preprocessors/text_cleaner.py

clean up docstrings: TextCleaner

---

test/core/pipeline/features/conftest.py

Small utility that ease visualization of a Pipeline graph.
To use it we just need to add a new `Then` step in a scenario like so:
```
Scenario Outline: Running a correct Pipeline
Given a pipeline <kind>
When I run the Pipeline
Then draw it to file
Then it should return the expected result
And components ran in the expected order
```
The images will be saved in a `test_pipeline_graphs` folder in the project's root.
This just an utility step meant to be used locally to ease some debugging.
I added a `Then` step to a scenario and run it.
N/A
- I have updated the related issue with new …

test: Add utility then step in feature testing to draw pipeline to file

---

haystack/components/routers/text_language_router.py

clean up docstrings: TextLanguageRouter

---

haystack/components/builders/chat_prompt_builder.py

clean up docstrings: ChatPromptBuilder

---

haystack/components/caching/cache_checker.py
haystack/components/retrievers/filter_retriever.py
haystack/components/retrievers/sentence_window_retriever.py
haystack/components/writers/document_writer.py
releasenotes/notes/use-document-store-from-dict-db7975d0e0e5e451.yaml

- fixes #8204
Make these generic components (`SentenceWindowRetriever`, ...) deserialize a Document Store using its specific `from_dict` class method (if available) instead of `default_from_dict`.
CI …

fix: deserialize Document Stores using specific `from_dict` class methods

---

haystack/components/caching/cache_checker.py
haystack/components/retrievers/filter_retriever.py
haystack/components/retrievers/sentence_window_retriever.py
haystack/components/writers/document_writer.py
haystack/utils/__init__.py
haystack/utils/docstore_deserialization.py
releasenotes/notes/docstore-deserialization-in-init-params-a123a39d5fbc957f.yaml
test/components/caching/test_url_cache_checker.py
test/components/retrievers/test_sentence_window_retriever.py
test/components/writers/test_document_writer.py
test/utils/test_docstore_deserialization.py

- follow up of #8207
- Introduce a utility function to perform this common operation
- test it properly
CI, new tests

refactor: utility function for docstore deserialization

---

haystack/dataclasses/chat_message.py
releasenotes/notes/deprecate-chatmessage-toopenaiformat-9b1b2987a568d3d7.yaml
test/dataclasses/test_chat_message.py

- related to #8169
Removes deprecated method and updates tests.
CI
Multiple core integrations need to be updated after this PR is merged. Details in the linked issue. …

chore: Remove deprecated `ChatMessage.to_openai_format`

---

haystack/components/routers/zero_shot_text_router.py

clean up docstrings: TransformersZeroShotTextRouter

---

haystack/components/audio/whisper_local.py
haystack/components/audio/whisper_remote.py

clean up docstrings: WhisperTranscribers

---

haystack/components/samplers/top_p.py
releasenotes/notes/add-min-top-k-top-p-sampler-dc65f97d420e70b0.yaml
test/components/samplers/test_top_p.py

This adds the parameter `min_top_k` to the TopPSampler which sets the minimum number of documents to be returned when the top-p sampling algorithm results in fewer documents being selected. The documents with the next highest scores are added to the selection.
This is useful when we want to guarantee a set number of documents will always be passed on, but allow the Top-P algorithm to still determine if more documents should be sent based on document score. 
Also some minor refactoring was done. The biggest change/addition was changing `ComponentError`s to `logger.warning` messages to allow the component to still run even when running into small edge cases. 
Expanded tests
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONT …

feat: Add `min_top_k` to TopPSampler

---

haystack/components/converters/docx.py
releasenotes/notes/docx-para-forwardref-31941f54ab3b679f.yaml

`from haystack.components.converters import DOCXToDocument`
this fails if `python-docx` is not installed
related to #8232
similar to  #7852
Use forward reference to `Paragraph`.
If the library is not installed, we will have a clear `ImportError` at init time.
Manual tests, (CI) …

fix: `DOCXToDocument` converter - use forward reference to `Paragraph`

---

haystack/components/converters/docx.py
releasenotes/notes/docxmetadata-json-serializable-e4205ce70d042aed.yaml
test/components/converters/test_docx_file_to_document.py

- fixes #8251
Simply convert the `datetime` object to strings
CI

fix: make meta produced by `DOCXToDocument` JSON serializable

---

haystack/components/retrievers/sentence_window_retriever.py
releasenotes/notes/sentence-window-retriever-output-docs-d3de2ac4328488f1.yaml
test/components/retrievers/test_sentence_window_retriever.py

Adds an extra key in the output of the `SentenceWindowRetriever`, returning a `List[Document]` containing all the Document objects belonging to the context window
unit tests, integration tests, manual verification
I've decided for a extra output key so that there are no breaking changes. …

feat: The SentenceWindowRetriever has now an extra output key containing all the documents belonging to the context window

---

haystack/core/pipeline/pipeline.py
releasenotes/notes/remove-deprecated-pipeline-run-debug-eab0c31ea0ce513d.yaml
test/core/pipeline/test_tracing.py

- fixes #8076 
Removes deprecated parameter from `Pipeline.run`.
CI

chore: Remove deprecated `debug` param from `Pipeline.run`

---

haystack/core/component/component.py
haystack/core/component/sockets.py
releasenotes/notes/async-component-support-machinery-6ea4496241aeb3b2.yaml
test/core/component/test_component.py

- related #6012 
This PR extends the core component machinery to add support for an `async def async_run(self)` method in components. The `async_run` method is optional. If it's present, it should have the same parameters (and output types) as the `run` method and must be implemented as a coroutine (`await`able).
Unit tests …

feat: Extend core component machinery to support an async run method (experimental)

---

haystack/components/embedders/backends/sentence_transformers_backend.py
haystack/components/evaluators/sas_evaluator.py
haystack/components/rankers/sentence_transformers_diversity.py
pyproject.toml
releasenotes/notes/update-sentence-transformers-3-3bca4e3f3ad3e7ba.yaml

Starting from `haystack-ai==2.4.0`, Haystack is only compatible with `sentence-transformers>=3.0.0`, due to `model_kwargs` parameter.
- https://github.com/deepset-ai/haystack/issues/8248#issuecomment-2312689180
- update the test dependency pin
- update the `LazyImport` message to suggest installing `sentence-transformers>=3.0.0`
CI …

chore: update test dependency and `LazyImport` block to make compatibility with `sentence-transformers>=3.0.0` explicit

---

releasenotes/config.yaml

- fixes #7315 
- Remove emojis from release notes config
no tests
The issue is a bit old already. I didn't try to reproduce it and I wonder why there were not more complaints about problems on Windows. I am not convinced that emojis caused frequent trouble in the past but I also don't see a reason to keep them. One alternative could be to close the issue as won't fix. …

chore: Remove emojis from release notes config

---

haystack/nodes/preprocessor/preprocessor.py
pyproject.toml
releasenotes/notes/upgrade-ntlk-1e94de2d6f5dd3b6.yaml
test/nodes/test_preprocessor.py

- We needed to update a few more deps to get a green CI
- We needed to skip nltk preprocessing tests that load pickle models (seems to be forbidden in nltk 3.9)
- fixes https://github.com/deepset-ai/haystack/issues/8238

fix: 1.x - nltk upgrade, use `nltk.download('punkt_tab')`

---

haystack/components/retrievers/sentence_window_retriever.py
releasenotes/notes/fix-sentence-window-retriever-filter-b7b136eedf6e8488.yaml

- fixes [#8308](https://github.com/deepset-ai/haystack/issues/8308)
- added the prefix `meta` in the filter used by the `SentenceWindowRetriever`
- unit tests and integration tests from the CI
- ran locally an end2end example for the `SentenceWindowRetriever`: 
- splitting and indexing document chunks
- querying and making sure the full context window is returned without crashing or an empty return
- this test was run successfully for the following DBs:
- Astra
- ElasticSearch
- OpenSearch
- PGVector
- PineCone
- Qdrant
- …

fix: `meta` prefix missing in the sentence window retriever filters

---

.github/workflows/release_notes.yml
releasenotes/notes/releasenotes-lint-4c2943da39f93876.yaml

- fixes #8319
Add a new step to prevent merging of badly formatted release notes files.
Added a fake release notes file in this PR, I'll remove it when CI is green.
N/A …

Add step to verify release notes files are correctly formatted

---

haystack/components/embedders/sentence_transformers_document_embedder.py
haystack/components/embedders/sentence_transformers_text_embedder.py
releasenotes/notes/update-max-seq-lenght-st-1dc3d7a9c9a3bdcd.yaml
test/components/embedders/test_sentence_transformers_document_embedder.py
test/components/embedders/test_sentence_transformers_text_embedder.py

This brings a change we had in v1 that updates the Sentence Transformer specific variable `max_seq_length` that allows us to change the max sequence length. Previously we though using `model_max_length` through `tokenizer_kwargs` would fix this, but a recent inveistgation from @bglearning shows it does not. So we make an update here such that `model_max_length` updates the value of `max_seq_length`.  …

feat (v2): Update so `model_max_length` updates `max_seq_length` for Sentence Transformers

---

haystack/components/routers/conditional_router.py
releasenotes/notes/make-from-dict-more-robust-for-conditionalrouter-c6ed6f841ad8e58d.yaml
test/components/routers/test_conditional_router.py

- fixes from_dict for conditional router to be resilient against explicit "None" mappings
- parse explicit None mappings for deserialization as empty dict
- unit test
although this can't happen if you call from_dict(to_dict) it can still happen if you change the yaml and (maybe by accident) set the key `custom_filters` to "None" based on the function signature.  …

fix: make from dict conditional router more resilient

---

haystack/components/generators/azure.py
haystack/components/generators/chat/azure.py
releasenotes/notes/add-azure-kwargs-6a5ab1358ef7f44c.yaml
test/components/generators/chat/test_azure.py
test/components/generators/test_azure.py

- fixes #8243 
I explicitly chose to expose default_headers and add an optional azure_kwargs for the other more niche parameters that some users might find useful. This can be condensed into azure_kwargs if preferred.
Tested with empty dictionary as we would need someone that uses an Azure Organizational Project with APIM to test.
As noted above, let me know whether exposing default_headers is the preferred way. …

feat: Expose default_headers and add kwargs for Azure Client

---

haystack/core/pipeline/draw.py
releasenotes/notes/fix-pipe-rendering-50261e0472f0d267.yaml

- fixes #8348 
Simply replace the not allowed `*` character with `&ast;` in Pipeline drawing.
Manual tests.
With this fix, the Pipeline visualization is working properly again.
See the original issue for details. …

fix: fix Pipeline rendering by replacing `*` with `&ast;`

---

haystack/components/rankers/transformers_similarity.py
releasenotes/notes/ranker-add-batching-during-inference-f077411ec389a63b.yaml
test/components/rankers/test_transformers_similarity.py

We added batching during inference time to the TransformerSimilarityRanker to help prevent OOMs when ranking large amounts of Documents.
Added an integration test and existing tests. …

feat: TransformerSimilarityRanker add batching across Documents during inference

---

haystack/components/builders/chat_prompt_builder.py
haystack/components/builders/prompt_builder.py
haystack/components/evaluators/context_relevance.py
haystack/components/evaluators/faithfulness.py
haystack/core/component/component.py
haystack/core/component/sockets.py
releasenotes/notes/component-set-input-type-constraints-0b1130c1b49d9648.yaml
test/components/evaluators/test_context_relevance_evaluator.py
test/components/evaluators/test_faithfulness_evaluator.py
test/core/component/test_component.py
test/core/component/test_sockets.py
test/core/pipeline/features/test_run.py

- fixes #8280
- Prevent `set_input_types`/`set_input_type` from being used when the `run` method is missing a `kwargs` parameter.
- Prevent `set_input_types`/`set_input_type` from overriding parameters in the `run` method's signature.
- Correct the handling of variadic kwargs when validating `run`/`async_run` signatures.
- Fix component string repr breaking when errors are raised during the `ComponentMeta` init phase.
CI …

fix: Add constraints to `set_input_type(s)` based on `run` method

---

haystack/components/preprocessors/document_splitter.py
releasenotes/notes/feat-DocumentSplitter-add-split-by-function-77501f439b63bb49.yaml
releasenotes/notes/feat-documentsplitter-add-split-by-function-77501f439b63bb49.yaml
test/components/preprocessors/test_document_splitter.py

Adding the possibility to pass a function and personalise the way in which DocumentSplitter defines a unit.
This means a user can, for example, use the following to split and define units:
`splitter_function = lambda text: re.split('[\n]{2,}, text)`
(or use spacy or anything else).
Added two tests with two "mock" splitter functions.
There are some issues related to document splitting #5922 . Given the fact that the current methods are very basic and the issues have been open for moths, I think it would make sense to let the user define how text is split.

feat : DocumentSplitter, adding the option to split_by function

---

.github/workflows/minor_version_release.yml

This step is not necessary anymore as we don't release Haystack 1 by branching off anymore as only push patch releases to the latest version of it. That is `1.26.x`.

ci: Remove version choice for workflow dispatch in `minor_version_release.yml`

---

haystack/core/pipeline/base.py
releasenotes/notes/deprecate-debug-path-976bb5a851365233.yaml

- fixes #8352
Deprecate `Pipeline` init argument `debug_path` as it's unused.
N/A

chore: Deprecate `Pipeline` init argument `debug_path`

---

haystack/components/preprocessors/__init__.py
haystack/components/preprocessors/nltk_document_splitter.py
haystack/components/preprocessors/utils.py
pyproject.toml
releasenotes/notes/nltk-document-splitting-enhancement-6ef6f59bc277662c.yaml
test/components/preprocessors/test_nltk_document_splitter.py

Introduces a new document splitter component utilizing NLTK for enhanced text processing.
- **Implemented NLTKDocumentSplitter:** A new component that leverages the Natural Language Toolkit (NLTK) for splitting documents based on words, sentences, passages, or pages.
- **Configuration Options:** The splitter supports various configuration parameters such as `split_by`, `split_length`, `split_overlap`, `respect_sentence_boundary`, `language`, `use_split_rules`, and `extend_abbreviations` for fine-tuning the document splitting process.
- **Split Mechanics Enhancement:** Improvements in split mechanics, including respecting sentence boundaries when splitting by words and addressing special cases with split rules and extended abbreviations for improved tokenization.
- **Testing:** …

feat: Port NLTKDocumentSplitter from dC to Haystack

---

haystack/components/preprocessors/nltk_document_splitter.py

- Fixes failed linter on the NLTKDocumentSplitter
- Failure showed up because NLTKDocumentSplitter extends DocumentSplitter and DocumentSplitter init method was changed on main after NLTKDocumentSplitter PR was opened
- Merge PRs to main before merge-ing!

chore: NLTKDocumentSplitter: add 'function' to split_by init param

---

haystack/components/classifiers/zero_shot_document_classifier.py
haystack/core/component/component.py
releasenotes/notes/component-set-output-type-override-852a19b3f0621fb0.yaml
test/core/component/test_component.py

fix: Prevent `set_output_types` from being called when the `output_types` decorator is used

---

docs/pydoc/config/classifiers_api.yml
docs/pydoc/config/preprocessors_api.yml

docs: add NLTKSplitter and ZeroShotClassifier to pydocs

---

haystack/utils/filters.py

Now that legacy filters are disabled, we need a centralized check for basic filter syntax.

feat: Add utility function to check metadata filter syntax

---

haystack/components/generators/chat/hugging_face_api.py
releasenotes/notes/add-usage-huggingfaceapi-generators-de8979cad6b6ec45.yaml
test/components/generators/chat/test_hugging_face_api.py

Adds  token `usage` metadata to responses from HuggingFaceAPIChatGenerator. `usage` dictionary response meta field has the following two keys `prompt_tokens` and `completion_tokens` matching OpenAI format in token counting. 
This feature, i.e. OpenAI token usage format compatibility, aside from chat generators interchangeability benefits, is needed for full support of Langfuse GENERATION token usage renderings in traces. See https://github.com/deepset-ai/haystack-private/issues/82 for more details. 
- Added a new `usage` meta field with the keys `prompt_tokens` and `completion_tokens` to `HuggingFaceAPIChatGenerator`.
- Modified the streaming and non-streaming response generation code to include the new `usage` information in the message metadata.
```python
usage_info = …
```

feat: HuggingFaceAPIChatGenerator add token `usage` data

---

code_of_conduct.txt
pyproject.toml

Fix `codespell` not skipping test paths.

chore: Fix `codespell` config

---

.pre-commit-config.yaml

Fix `codespell` pre-commit hook not using configs from `pyproject.toml.`

chore: Fix `codespell` pre-commit hook

---

test/core/pipeline/features/test_run.py

Updated the pipeline behavior tests to set the `max_runs_per_component` to 1 for pipelines that should only call each component within them once. 
All tests still pass, I just think this would be good to check since we have had issues in the past where components were run multiple times in linear pipelines.  …

test: Set max_runs_per_component to 1 for pipelines that are linear

---

haystack/core/pipeline/predefined/chat_with_website.yaml.jinja2
haystack/core/pipeline/predefined/generative_qa.yaml.jinja2
haystack/core/pipeline/predefined/rag.yaml.jinja2
releasenotes/notes/fix-chat-web-pipe-template-0b00144b1099cda3.yaml

- fixes #8391
Update the `CHAT_WITH_WEBSITE` Pipeline template to reflect the changes in the `HTMLToDocument` converter component.
Manual tests.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installatio …

fix: fix `PredefinedPipeline.CHAT_WITH_WEBSITE` template

---

haystack/components/joiners/branch.py
haystack/core/component/component.py
haystack/core/component/types.py
haystack/core/pipeline/base.py
releasenotes/notes/deprecate-greedy-argument-4b8c39572f5df25c.yaml
test/core/component/test_component.py
test/core/pipeline/test_pipeline.py

- fixes #7871
Deprecate `@component` decorator `is_greedy` argument and add a new `GreedyVariadic` input type in its place.
N/A
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#in …

feat: Deprecate `@component` decorator `is_greedy` argument

---

haystack/core/pipeline/base.py
releasenotes/notes/deprecate-self-connection-665647384ae2792b.yaml

Calling `Pipeline.connect()` with the same Component both as `sender` and `receiver` will now emit a warning.
This will change in `2.7.0` and raise an exception. This change will come together with the internal `Pipeline.run()` rework release.

chore: Deprecate connecting a Component to itself

---

docs/pydoc/config/converters_api.yml
haystack/components/converters/__init__.py
haystack/components/converters/json.py
pyproject.toml
releasenotes/notes/json-converter-a747e9c44543dfb5.yaml
test/components/converters/test_json.py

- fixes #7784
Add a new `JSONConverter` Component.
Usage:
```python
import json
from haystack.components.converters import JSONConverter
from haystack.dataclasses import ByteStream
data = {
"laureates": [
{
"firstname": "Enrico",
"surname": "Fermi",
"motivation": "for his demonstrations of the existence of new radioactive elements produced "
"by neutron irradiation, and for his related discovery of nuclear reactions brought about by"
" slow neutrons",
},
{
"firstname": "Rita",
"surname": "Levi-Montalcini",
"motivation": "for their discoveries of growth factors",
},
],
}
source = ByteStream.from_string(json.dumps(data))
converter = JSONConverter(
jq_schema=".laureates[]", content_key="motivation", extra_meta_fields=["firstname", "surname"]
)
results = converter.run(sources=[source]) …
```

feat: Add `JSONConverter` Component

---

.github/workflows/tests.yml
pyproject.toml

In #7597, we introduced `macos-12` (instead of `macos-latest`) because the CI was broken.
After several months, `haystack-core-integrations` and `haystack-experimental` use `macos-latest`.
I also found out that our CI works properly with `macos-latest` (it also seems faster than `macos-12`).
Reintroduce `macos-latest`.
CI (triggered with a temporary change to pyproject -> https://github.com/deepset-ai/haystack/actions/runs/11029975901) …

ci: reintroduce `macos-latest` in tests

---

haystack/utils/__init__.py

- The utility function `raise_on_invalid_filter_syntax` introduced in this [PR](https://github.com/deepset-ai/haystack/pull/8386) is missing from `haystack/utils/__init__.py`.
Update `haystack/utils/__init__.py`. …

fix: Expose `raise_on_invalid_filter_syntax` in `haystack.utils`

---

haystack/core/pipeline/base.py
releasenotes/notes/remove-support-to-connect-component-to-self-6eedfb287f2a2a02.yaml
test/core/pipeline/features/pipeline_run.feature
test/core/pipeline/features/test_run.py
test/core/pipeline/test_pipeline.py

- fixes #8369
As described in the issue to remove support for connecting a component to self , we now raise an error instead of a deprecating warning

feat: `Pipeline.connect()` will now raise a `PipelineConnectError` if `sender` and `receiver` are the same Component

---

haystack/components/converters/pypdf.py
releasenotes/notes/pypdf-converter-robust-from-dict-35ebe6aaab944b19.yaml
test/components/converters/test_pypdf_to_document.py

- that's a fix which would help us greatly for studio. Basically what happens is that the constructor has a default of `None` for the converter but when we call the `from_dict` method with no converter then it breaks
- I ran …

fix: make `from_dict` of `PyPDFToDocument` more robust

---

haystack/core/pipeline/base.py
releasenotes/notes/remove-debug-path-68e9b2e41d7d43fd.yaml

- fixes #8366
Remove deprecated `Pipeline` init argument `debug_path`
N/A

chore: Remove deprecated `Pipeline` init argument `debug_path`

---

releasenotes/notes/refactor_deserialize_document_store_in_init_parameters-b7f05173f0c56452.yaml

- releasenotes/notes/refactor_deserialize_document_store_in_init_parameters-b7f05173f0c56452.yaml has a wrong indentation and caused a release workflow to fail https://github.com/deepset-ai/haystack/actions/runs/11108077435/job/30860188401
- fix indentation
no tests
- I …

fix: fix release note indentation of #8302

---

haystack/components/converters/pypdf.py
releasenotes/notes/pypdf-converter-robust-from-dict-35ebe6aaab944b19.yaml
test/components/converters/test_pypdf_to_document.py

- main version of https://github.com/deepset-ai/haystack/pull/8422
- **fix: make `from_dict` of `PyPDFToDocument` more robust**
- **chore: drop trailing space**
- **converting method to static and making the comment shorter**
- **reverting method to static**
- I …

fix: make pypdf converter more robust

---

docs/pydoc/config/evaluators_api.yml
haystack/components/evaluators/__init__.py
haystack/components/evaluators/document_ndcg.py
releasenotes/notes/document-ndcg-evaluator-d579f51dd76ae76a.yaml
test/components/evaluators/test_document_ndcg.py

- fixes #8415 
* Adding a new DocumentNDCGEvaluator component and corresponding unit tests
* New unit tests
* The implementation of this component could benefit from any work on https://github.com/deepset-ai/haystack/issues/8412 In this PR, I am simply comparing document ids to evaluate whether two documents are equal.
* I can recommend reading https://en.wikipedia.org/wiki/Discounted_cumulative_gain#Example for understanding the calculations and the values used in the test assertions …

feat: Add DocumentNDCGEvaluator component 

---

haystack/tracing/datadog.py

`mypy` is failing when linting `tracing/datadog.py`, this fixes it. 
```
❯ hatch run test:types
haystack/tracing/datadog.py:65: error: Incompatible types in assignment (expression has type "DatadogSpan", variable has type "Span")  [assignment]
haystack/tracing/datadog.py:67: error: Argument 1 to "set_tags" of "Span" has incompatible type "dict[str, Any]"; expected "dict[str | bytes, Any]"  [arg-type]
haystack/tracing/datadog.py:69: error: Incompatible types in "yield" (actual type "ddtrace._trace.span.Span", expected type "haystack.tracing.tracer.Span")  [misc]
haystack/components/converters/tika.py:30: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
Found 3 errors in 1 file (checked 191 source files)
```
I ran …

chore: Fixing linting of `tracing/datadog.py`

---

haystack/components/converters/markdown.py

docs: `MarkdownToDocument` example - adding missing import

---

haystack/components/converters/pypdf.py
releasenotes/notes/pypdf-serde-fixes-revert-22fcdad91951d3c2.yaml
test/components/converters/test_pypdf_to_document.py

- https://github.com/deepset-ai/haystack/pull/8430/
The above PR unintentionally broke the deserialization of YAMLs that were generated with Haystack < 2.6.0, so we re-add support for it. This will be removed in 2.7.0 once the default converter is merged into the component.
Unit tests …

fix: (Temporarily) Re-add suport for pre-2.6.0 YAMLs with `PyPDFConverter`

---

haystack/logging.py
releasenotes/notes/fix-logs-containing-json-1393a00b4904f996.yaml
test/test_logging.py

- fixes logs getting lost if str-interpolation-like message is passed, e.g. JSON
```python
from haystack.logging import getLogger
logger = getLogger(__name__)
logger.info('My service responed with: {"key": "value"}')
```
- try-except string interpolation
- fallback to non-interpolated msg …

fix: logs containing JSON getting lost

---

haystack/utils/callable_serialization.py

Rename obviously wrong variable name

nit: Fix variable naming in deserialize_callable

---

releasenotes/notes/compatibility-hh-hub-0.26.0-a5b61f7bf99a97b7.yaml
test/components/generators/test_hugging_face_api.py

- Tests failing on main https://github.com/deepset-ai/haystack/actions/runs/11399870792/job/31719542345
-  `huggingface_hub==0.26.0` introduced a new mandatory `input_length` parameter for `TextGenerationStreamOutputStreamDetails`. We were not using it in our mock.
- Update the mock in the test to set `input_length`
CI …

test: ensure compatibility with `huggingface_hub==0.26.0`

---

haystack/components/routers/file_type_router.py
pyproject.toml
releasenotes/notes/pip-test-dep-b797879f1d73b3eb.yaml

- After the introduction of `uv`, [some typing tests are failing](https://github.com/deepset-ai/haystack/actions/runs/11443115369/job/31835396458?pr=8473).
- This happens because `pip` is no longer installed by default and it is needed by `mypy` for installing missing stub packages.
Add `pip` to `test` dependencies
CI. In https://github.com/deepset-ai/haystack/pull/8475/commits/875c4133f422ee62968fa48795255d5d4a31b367, I modified a python file to trigger the `lint` workflow.
See [lint/typing tests passing](https://github.com/deepset-ai/haystack/actions/runs/11455951671/job/31873387408?pr=8475).
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_condu …

ci: add `pip` to `test` dependencies

---

pyproject.toml

Latest `ddtrace` release is causing issues with `pytest` during tests collection.
This PR pins `ddtrace` tests dependency to `2.15.0rc2` to fix the issue.
Example CI failure:
https://github.com/deepset-ai/haystack/actions/runs/11457182414/job/31876910579
I'll create an issue to remember unpinning as soon as `2.15.0` is released. …

test: Pin `ddtrace` test dependency to fix tests

---

haystack/core/pipeline/base.py
haystack/core/serialization.py
haystack/marshal/yaml.py
releasenotes/notes/enforce-python-types-serde-0c5cd0a716bab7d0.yaml
test/core/test_serialization.py
test/marshal/test_yaml.py

- fixes #8458
The pipeline serialization code now explicitly restricts the usage of custom types in serialized component data. Previously, custom types were serialized to a generic Python object representation by the YAML marshaller even though the loader did not support them.
Additionally, errors related to serde have been expanded to provide information about the problematic component whenever possible.
All tests. …

fix: Enforce basic Python types restriction on serialized component data and improve related errors

---

haystack/components/routers/file_type_router.py
releasenotes/notes/meta-in-filetyperouter-d3cf007f940ce324.yaml
test/components/routers/test_file_router.py

- fixes #8465
- allow passing `meta` in the `run` method of `FileTypeRouter`: when metadata is provided, the sources are internally converted to `ByteStream` objects and the metadata is added.
- general refactoring of the component
CI, several new tests.
- I documented …

feat: allow passing `meta` in the `run` method of `FileTypeRouter`

---

haystack/core/pipeline/pipeline.py
haystack/tracing/datadog.py
haystack/tracing/logging_tracer.py
haystack/tracing/opentelemetry.py
haystack/tracing/tracer.py
releasenotes/notes/tracing-with-concurrency-5daadfde0a36f94a.yaml
test/core/pipeline/test_tracing.py
test/tracing/test_tracer.py
test/tracing/utils.py

- fixes #8488
Issue: I ran into some issues after deploying a pipeline as a service with tracing enabled. If there are concurrent calls to run the pipeline, the structure of spans kinda messed up due to the fact that the "haystack.component.run" spans are attached to the "haystack.pipeline.run" span. I experimented primarily with Langfuse, and this gave me a giant span with nested pipeline runs overlapping each other, which is definitely not ideal.
Purposed solution: I have come up with a solution by adding an optional `parent_span` parameter in the trace context. Furthermore, I tweaked the Langfuse tracer integration such that it creates a new span/generation on top of the parent span if it is provided, or create a root span if not.
1. unit test
2. I also tried running concurrent …

feat!: tracing with concurrency

---

haystack/components/routers/conditional_router.py
releasenotes/notes/conditional-routes-validation-b46fc506d35894d4.yaml
test/components/routers/test_conditional_router.py

- fixes #8445
Add routes output type validation in `ConditionalRouter`.
To enable instantiate `ConditionalRouter` with `validate_output_type=True`.
Added new tests.
N/A …

feat: Add route output type validation in `ConditionalRouter`

---

haystack/components/generators/hugging_face_api.py
releasenotes/notes/hfapigen-forwardref-5c06090282557195.yaml

- After the changes in #8406, we started to see some failures in tests using Haystack main branch: https://github.com/deepset-ai/haystack-tutorials/actions/runs/11584421300/job/32251536345
- We should use forward references when types in methods signature come from a lazy import block
- use forward references
- small refactoring to remove `type: ignore` blocks
CI …

fix: `HuggingFaceAPIGenerator` - use forward references

---

.github/workflows/readme_sync.yml

Fix `readme_sync.yml` so that documentation is pushed to correct version before the stable version is released.
Can't test really, I tested the bash script I edited and it returns what I expect though.
Example failure:
https://github.com/deepset-ai/haystack/actions/runs/11157243880/job/31011161262 …

ci: Fix `readme_sync.yml`

---

pyproject.toml

- fixes #8479
Unpin `ddtrace` in tests dependencies.
N/A
N/A

chore: Remove `ddtrace` version pin

---

releasenotes/notes/update-transformers-e83863bbe69ddceb.yaml

Forgot to add release note to the latest commit and we need it for the successful build.

chore: Add release note for the upcoming v1.26.4 

---

test/components/generators/test_openai.py

fix: lowercase comparison in `OpenAIGenearator` with system prompt tests

---

haystack/components/embedders/hugging_face_api_document_embedder.py
haystack/components/embedders/hugging_face_api_text_embedder.py
haystack/components/generators/chat/hugging_face_api.py
haystack/components/generators/hugging_face_api.py

- Error messages not being displayed
- Needed to add pylint disable too-many-arguments, since the file is changed, it's now checked
- CI tests …

fix: huggingface embedder error messages not being displayed

---

haystack/components/joiners/document_joiner.py
releasenotes/notes/fix-document-joiner-division-by-zero-b24f95d37b007264.yaml
test/components/joiners/test_document_joiner.py

- This PR fixes an issue with the distribution based rank fusion join mode of the DocumentJoiner class when an empty list of documents is passed.
- It additionally fixes division by zero errors when no document list is passed to the merge and rrf join modes.
- Locally by running `hatch test -- test/components/joiners/test_document_joiner.py` …

fix: document joiner division by zero with distribution based rank fusion

---

haystack/components/preprocessors/nltk_document_splitter.py
releasenotes/notes/fix-nltk-doc-splitter-d0864dda906c45b0.yaml
test/components/preprocessors/test_nltk_document_splitter.py

Brings in the fix first introduced here https://github.com/deepset-ai/deepset-cloud-custom-nodes/pull/367
- To avoid fully subsuming the previous chunk, we ignore the first sentence from that chunk when calculating sentence overlap. i.e. we want to avoid cases of: Doc1 = [s1, s2], Doc2 = [s1, s2, s3].
- Only applies when splitting by word and respecting sentence boundary.
- This mirrors the implementation in v1's PreProcessor.
Since this component was a port of the functionality of Haystack v1 I view this as a bug fix. 
A few other changes:
- While I was here I also finished adding function support for this component by updating the `_split_into_units` function and added the `splitting_function` init parameter. 
- Also fixed another bug which was caused by the introduction of the …

fix: Bring in fix from custom nodes

---

pyproject.toml

As discovered by @silvanocerza and also reported in https://github.com/deepset-ai/haystack/discussions/8543, there are some incompatibiliets with python 3.13.
We should explicitly declare this in pyproject, to avoid problems when installing the project with hatch.
- `requires-python = ">=3.8,<3.13"`
CI …

chore: declare `requires-python<3.13` in pyproject

---

haystack/components/embedders/openai_document_embedder.py
releasenotes/notes/patch-1-34479efe3bea0e4f.yaml
test/components/embedders/test_openai_document_embedder.py

if ever an error is raised by the OpenAI API, don't fail the entire processing
Manual tests

feat(openai): be tolerant to exceptions

---

.gitignore

I'm trying [Zed](https://zed.dev), it saves configs on the workspace much like VS Code.
It's good to ignore them.

chore: Add Zed config folder to `.gitignore`

---

haystack/components/preprocessors/document_splitter.py
haystack/components/preprocessors/nltk_document_splitter.py
releasenotes/notes/split-by-function-62ce32fac70d8f8c.yaml
test/components/preprocessors/test_document_splitter.py

- fixes #8490
`DocumentSplitter` was working incorrectly if user provided a `splitting_function` as that would not override all the other settings, included the default ones.
With this change if `split_by` is set to `function` and the `splitting_function` is set only that function will be used to split `Document`s.
I updated existing tests and ran them locally.
N/A …

Fix `DocumentSplitter` not splitting by function

---

haystack/components/embedders/backends/sentence_transformers_backend.py
test/components/embedders/test_sentence_transformers_embedding_backend.py

There is a deprecation warning in Sentence Transformers here
https://github.com/UKPLab/sentence-transformers/blob/e156f38b1007e7860218c27223e1d577f3a021fe/sentence_transformers/SentenceTransformer.py#L194-L203
Update Backend to use the non-deprecated parameter …

chore: Use token instead of use_auth_token because of deprecation warning

---

haystack/components/rankers/meta_field_grouping_ranker.py

Noticed that we left the dC component name in the docstirngs.

docs: update MetaFieldGroupingRanker name in docstrings

---

haystack/components/generators/chat/openai.py
haystack/components/generators/openai.py
releasenotes/notes/fix-openai-streaming-usage-c3dbad63fd9a8020.yaml
test/components/generators/chat/test_openai.py
test/components/generators/test_openai.py

- fixes #8507
Fix `OpenAIChatGenerator` and `OpenAIGenerator` to correctly return usage when using a `streaming_callback` and `generation_kwargs` contain `{"stream_options": {"include_usage": True}}`.
Previously that would cause it to crash.
I added new integration tests.
N/A …

fix: `OpenAIChatGenerator` and `OpenAIGenerator` crashing when streaming with usage tracking

---

haystack/components/rankers/meta_field_grouping_ranker.py

- tests failing in unrelated PRs: https://github.com/deepset-ai/haystack/actions/runs/11971004264/job/33374908224?pr=8568
- probably because of a ruff update
Simplify the code to make the linter happy
CI …

chore: fix linting of `MetaFieldGroupingRanker`

---

haystack/components/converters/csv.py
haystack/components/converters/docx.py
haystack/components/converters/html.py
releasenotes/notes/add-store-full-path-param-to-converters-60007b232e279a33.yaml
test/components/converters/test_csv_to_document.py
test/components/converters/test_docx_file_to_document.py
test/components/converters/test_html_to_document.py

- partial fix for  #8440 
Add a new parameter to the run method to allow users to toggle whether the file_path in metadata stores the complete file path or only the base file name. A warning is generated about the upcoming change in file_path storage behavior in the next release.
Added new test for checking the parameter function
This is 1/3 PRs that will add the same change to other converters. …

feat: Add `store_full_path` to converters (1/3)

---

haystack/components/preprocessors/document_cleaner.py
releasenotes/notes/fix-document-cleaner-4e18a63fd7dc2bd9.yaml
test/components/preprocessors/test_document_cleaner.py

- fixes #8571
Change `DocumentCleaner` to keep all fields for cleaned `Document`s.
Added a new unit test.
N/A

Fix `DocumentCleaner not preserving `Document` fields

---

haystack/components/routers/conditional_router.py
releasenotes/notes/conditional-router-optional-parameters-f02c598d7c751868.yaml
test/components/routers/test_conditional_router.py

Enhances the ConditionalRouter component by adding support for optional parameters, enabling default/fallback routing behavior when certain inputs are not provided at runtime.
- fixes https://github.com/deepset-ai/haystack/issues/8556
Introduces `optional_variables` parameter to specify which route variables can be omitted
Improves documentation with clear examples of fallback routing patterns
Implements proper serialization/deserialization for the new field
Define routes with fallback behavior when certain parameters are missing:
```python
from haystack.components.routers import ConditionalRouter
routes = [
{
"condition": '{{ path == "rag" }}',
"output": "{{ question }}",
"output_name": "rag_route",
"output_type": str
},
{
"condition": "{{ True }}",  # …
```

feat: Add variable to specify inputs as optional to ConditionalRouter

---

haystack/dataclasses/chat_message.py
releasenotes/notes/chatmessage-text-5bd06f6ac70ac649.yaml
test/dataclasses/test_chat_message.py

- part of #8587 (see #8583 for the motivation)
- Introduce a `text` property that mirrors `content`
- If users/applications directly access the `content` attribute, show a deprecation warning telling that `content` will be removed in 2.9.0 and to use `text` instead
CI, new tests
Adaptation of all Haystack components to use `text` instead of `content` will be done in a future PR. …

refactor: `ChatMessage` - introduce `text` property and deprecate `content`

---

haystack/core/pipeline/base.py

Revert previous change committed directly to `main`

chore: Revert change to deserialization error in  `Pipeline`

---

.github/pull_request_template.md

- None
- Mention `!` in the PR template together with the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/)
does not apply
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#install …

chore: Mention breaking changes in PR template

---

haystack/components/retrievers/sentence_window_retriever.py
releasenotes/notes/sentence-window-deprecation-b7db8efc56f33940.yaml

- Adds a deprecation warning coming from this [PR](https://github.com/deepset-ai/haystack/pull/8590) and this [issue](https://github.com/deepset-ai/haystack/issues/8557) …

chore: adding a deprecation warning on the `SentenceWindowRetriever`

---

haystack/components/joiners/document_joiner.py
releasenotes/notes/converting-docjoiner-methods-to-static-4668f5d227667dd5.yaml

`_concatenate()` and `_distribution_based_rank_fusion()` should be static methods
- local unit tests
- CI tests …

refactor: converting some DocumentJoiner methods to staticmethod

---

haystack/components/embedders/sentence_transformers_document_embedder.py
haystack/components/embedders/sentence_transformers_text_embedder.py
releasenotes/notes/fix-docstrings-normalize-embedding-fd2dba50ba9e51a1.yaml

fix: docstring for normalization

---

haystack/components/fetchers/link_content.py
releasenotes/notes/add-missing-mime-type-assignment-to-the-link-content-fetcher-7581e2728e2130b8.yaml
test/components/fetchers/test_link_content_fetcher.py

The mime type assignment for the stream is missing in the `LinkContentFetcher`. Because of it the pipelines that use `FileTypeRouter` can fail if receive a single url as an input.
Unit tests, integration tests …

fix: add missing stream mime type assignment to the `LinkContentFetcher`

---

haystack/components/converters/azure.py
haystack/components/converters/csv.py
haystack/components/converters/docx.py
haystack/components/converters/html.py
haystack/components/converters/json.py
haystack/components/converters/markdown.py
haystack/components/converters/pdfminer.py
haystack/components/converters/pptx.py
haystack/components/converters/pypdf.py
haystack/components/converters/tika.py
haystack/components/converters/txt.py
releasenotes/notes/update-store-full-path-default-value-129f701ba07b944b.yaml
test/components/converters/test_azure_ocr_doc_converter.py
test/components/converters/test_csv_to_document.py
test/components/converters/test_docx_file_to_document.py
test/components/converters/test_html_to_document.py
test/components/converters/test_json.py
test/components/converters/test_pptx_to_document.py
test/components/converters/test_pypdf_to_document.py
test/components/converters/test_textfile_to_document.py

- fixes #8607
- Updated the default value of `store_full_path` to `False` in all converters and update tests accordingly.
- Local unit tests …

chore: update default value of `store_full_path` to `False` in converters

---

haystack/components/converters/azure.py
haystack/components/converters/csv.py
haystack/components/converters/docx.py
haystack/components/converters/html.py
haystack/components/converters/json.py
haystack/components/converters/markdown.py
haystack/components/converters/pdfminer.py
haystack/components/converters/pptx.py
haystack/components/converters/pypdf.py
haystack/components/converters/tika.py
haystack/components/converters/txt.py

- follow up of #8619
- remove deprecation warnings
CI

chore: remove deprecation warnings related to `store_full_path`

---

haystack/components/preprocessors/nltk_document_splitter.py
releasenotes/notes/deprecating-NLTKDocumentSplitter-e9a621e025e9a49f.yaml

docs: add deprecation warning nltk document splitter

---

pyproject.toml
releasenotes/notes/pin-openai-1-56-1-43d50ebfbb8b5a8d.yaml

- Related: https://github.com/deepset-ai/devrel-board/issues/539
- The situation is quite complex and hard to debug. https://github.com/openai/openai-python/issues/1902
- It has been fixed in the OpenAI client with releases 1.55.3 and 1.56.1
- Unfortunately, Colab has 1.54.5, which is compatible with Haystack, but then the error pops up 
- pin to `openai>=1.56.1` to make sure that Haystack works and, when installed in Colab, updates the OpenAI client.
CI
- I've used one of …

chore: pin `openai>=1.56.1`

---

test/components/classifiers/test_zero_shot_document_classifier.py
test/components/generators/chat/test_hugging_face_local.py
test/components/generators/test_hugging_face_local_generator.py
test/components/rankers/test_sentence_transformers_diversity.py
test/components/rankers/test_transformers_similarity.py
test/components/readers/test_extractive.py
test/components/routers/test_transformers_text_router.py
test/components/routers/test_zero_shot_text_router.py

Just a quality of life improvement.
When you have a local Hugging Face token (in a `HF_TOKEN` env var), our tests fail.
So I am using `monkeypatch.delenv` to ignore this specific environment variable during the test execution.
https://docs.pytest.org/en/stable/how-to/monkeypatch.html
My local tests now run properly; CI …

test: ignore `HF_TOKEN` in some unit tests

---

e2e/pipelines/test_dense_doc_search.py
e2e/pipelines/test_preprocessing_pipeline.py

- local end2endtests + CI tests

fix: end2end tests due to behaviour of DocumentSplitter "sentence" being replaced by "period"

---

haystack/components/preprocessors/__init__.py

- Adding `SentenceSpitter` to `haystack.preprocessores.init`

fix: adding `SentenceSplitter` to init imports

---

.github/workflows/e2e.yml
e2e/pipelines/test_named_entity_extractor.py
haystack/components/extractors/named_entity_extractor.py
releasenotes/notes/add-token-to-named-entity-extractor-3124acb1ae297c0e.yaml
test/components/extractors/test_named_entity_extractor.py
test/components/generators/test_hugging_face_local_generator.py

- fixes #8633 
- I've added `token` support to `NamedEntityExtractor` and then update HF backend to pass it down to tokenizer and model `from_pretrained` methods.
- I've duplicated public [dslim/bert-base-NER](https://huggingface.co/dslim/bert-base-NER) to private [deepset/bert-base-NER](https://huggingface.co/deepset/bert-base-NER) and added required tests.
- I've also fixed formatting of an existing error message about failed backend initialization.
Local unit testing / e2e …

Named entity extractor private models

---

haystack/components/embedders/openai_text_embedder.py

The constants below were introduced in #7653
https://github.com/deepset-ai/haystack/blob/99e7e343b28d2d076a63f9d5823d0e1cf23f68ca/haystack/components/embedders/openai_text_embedder.py#L13-L14
but the actual access to env vars happen here:
https://github.com/deepset-ai/haystack/blob/99e7e343b28d2d076a63f9d5823d0e1cf23f68ca/haystack/components/embedders/openai_text_embedder.py#L95-L99
- Remove the unused constants
CI …

chore: `OpenAITextEmbedder` - remove unused constants

---

haystack/utils/callable_serialization.py
releasenotes/notes/use-importlib-when-deserializing-callable-1f36f07c4518c2cf.yaml
test/utils/test_callable_serialization.py

- fixes #8647
Supports local package imports via importlib.import_module
Existing unit tests passed. I also added a new negative test for this.
This is a rather small change but it is causing issues for me right now. Really hope this can be included in 2.9.0!
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added …

feat: use importlib when deserializing callables

---

haystack/dataclasses/byte_stream.py
releasenotes/notes/fix-bytestream-str-8dd6d5e9a87f6aa4.yaml
test/dataclasses/test_byte_stream.py

- fixes logs getting too big, e.g. https://github.com/deepset-ai/haystack/blob/04fc187bc44c39fcd5d8c29ce7f27f91667065ce/haystack/components/converters/txt.py#L90
- truncate `data` in str representation of `ByteStream` to 1k
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in case the PR includes breaking …

fix: truncate ByteStream string representation

---

haystack/utils/callable_serialization.py
releasenotes/notes/improve-callables-serde-6aa1e23408063247.yaml
test/components/generators/chat/test_hugging_face_local.py
test/components/generators/chat/test_openai.py
test/components/generators/test_openai.py
test/components/preprocessors/test_document_splitter.py
test/utils/test_callable_serialization.py

- fixes #8643
- Improve serialization and deserialization of callables.
- Allow serialization of classmethods and staticmethods
- Explicitly prohibit serialization of instance methods, lambdas, and nested functions.
CI, new tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in case the PR includes …

refactor: improve serialization/deserialization of callables (to handle class methods and static methods)

---

haystack/testing/document_store.py
releasenotes/notes/reorganize-docstore-testing-for-dataframes-3825910ade718d51.yaml
test/document_stores/test_in_memory.py

- related to #8627
To initiate the removal of the `dataframe` field from `Document`, the first step would be to remove its support across all Document Stores.
Currently, most Document Stores test suites (in core-integrations) inherit from `DocumentStoreBaseTests` in Haystack.
In this PR, I'm isolating dataframe filter tests by removing them from `FilterDocumentsTest` (a part of `DocumentStoreBaseTests`) and grouping them into a new utility class, `FilterDocumentsTestWithDataframe`. This new class is not included in `DocumentStoreBaseTests`.
**What will change after a Haystack release including this PR?**
- All Document Stores which inherit from `DocumentStoreBaseTests` or `FilterDocumentsTest` won't automatically test Documents containing `dataframe`.
- To test dataframe functionality, …

test: reorganize docstore test suite to isolate dataframe tests

---

docs/pydoc/config/tool_components_api.yml
docs/pydoc/config/tools_api.yml
haystack/components/generators/chat/hugging_face_api.py
haystack/components/generators/chat/openai.py
haystack/components/tools/tool_invoker.py
haystack/dataclasses/__init__.py
haystack/tools/__init__.py
haystack/tools/tool.py
releasenotes/notes/tool-refactor-7ed98e3ee4de14c3.yaml
test/components/generators/chat/test_hugging_face_api.py
test/components/generators/chat/test_openai.py
test/components/tools/test_tool_invoker.py
test/tools/test_tool.py

Since we plan to introduce some subclasses of `Tool` (`ComponentTool` etc.), we thought of moving the dataclass into a dedicated package and make serialization/deserialization more flexible.
- Move `Tool` to a new dedicated `tools` package.
- Refactor `Tool` serialization and deserialization to make it more flexible and include type information. (Same approach as POC in https://github.com/deepset-ai/haystack-experimental/pull/164)
CI, adapted tests
@dfokina your input here is necessary for the API reference docs.
- I removed the `tool` module from `data_classes_api`.
- I renamed `tools_api` (which previously contained components related to Tools, such as `ToolInvoker`) to `tools_components_api`.
- I put the new module `tool` (from `tools` package) into `tools_api`.
LMK if this makes …

refactor: move `Tool` to a separate package; refactor serde

---

haystack/components/audio/whisper_local.py
haystack/components/converters/openapi_functions.py
haystack/components/generators/chat/hugging_face_local.py
haystack/components/rankers/lost_in_the_middle.py
haystack/core/component/component.py
haystack/core/pipeline/draw.py
haystack/document_stores/in_memory/document_store.py
haystack/marshal/yaml.py
haystack/utils/filters.py
haystack/utils/hf.py
test/components/audio/test_whisper_local.py
test/components/converters/test_docx_file_to_document.py
test/components/embedders/test_openai_document_embedder.py
test/components/embedders/test_openai_text_embedder.py
test/components/joiners/test_document_joiner.py
test/components/preprocessors/test_document_cleaner.py
test/components/routers/test_conditional_router.py
test/core/pipeline/features/test_run.py

CI: fix format after newly introduced formatting rules from ruff release

---

haystack/components/converters/pypdf.py
releasenotes/notes/pypdf-docid-293dac08ea5f8491.yaml
test/components/converters/test_pypdf_to_document.py

- related to https://github.com/deepset-ai/haystack/issues/8692
- Initialize the Document returned by PyPDFToDocument with content and meta so that both are taken into account for document ID generation. Previously only the content was used for the initialization of the Document and the meta data was updated later …

fix: PyPDFToDocument initializes documents with content and meta

---

docs/pydoc/config/tools_api.yml
haystack/tools/__init__.py
haystack/tools/errors.py
haystack/tools/from_function.py
haystack/tools/tool.py
releasenotes/notes/create-tool-from-function-b4b318574f3fb3a0.yaml
test/tools/test_from_function.py
test/tools/test_tool.py

Since we are introducing some subclasses of `Tool` (`ComponentTool`, `OpenAPITool` in the future, ...), the `Tool.from_function` class method becomes inappropriate. These subclasses would inherit the method, potentially leading to unintended behaviors (e.g. `ComponentTool.from_function` makes no sense).
To address this, I'm proposing a replacement: `create_tool_from_function` utility function (+ a `tool` decorator).
- Replace the `Tool.from_function` class method with a `create_tool_from_function` utility function.
- Add a simple `tool` decorator, to simplify programmatic use cases
```python
from typing import Annotated, Literal
from haystack.tools import create_tool_from_function
def get_weather(
city: Annotated[str, "the city for which to get the weather"] = "Munich",
unit: …
```

refactor: `create_tool_from_function` + `tool` decorator

---

haystack/components/generators/chat/openai.py
releasenotes/notes/do-not-pass-tools-to-openai-if-none-1fe09e924e7fad7a.yaml
test/components/generators/chat/test_openai.py

In the `OpenAIChatGenerator`, when no tools are provided, we pass `None` to the client.
This is problematic for OpenAI-compatible APIs which do not support tools.
This issue was encountered in https://github.com/deepset-ai/haystack-core-integrations/pull/1274
- do not pass tools to the OpenAI client when none are provided
CI, adapted existing tests to check whether we pass `tools` or not …

fix: `OpenAIChatGenerator` - do not pass tools to the OpenAI client when none are provided

---

haystack/components/embedders/azure_document_embedder.py
haystack/components/embedders/azure_text_embedder.py
releasenotes/notes/add-default-headers-azure-embedders-6ffd24ec1502c5e4.yaml
test/components/embedders/test_azure_document_embedder.py
test/components/embedders/test_azure_text_embedder.py

- fixes #8534 
Replaces the old PR: #8535 
Add `default_headers` parameter as a keyword argument to `AzureOpenAIDocumentEmbedder` and `AzureOpenAITextEmbedder`.
Ran the tests and CI
- I ran …

feat: add `default_headers` for Azure embedders

---

docs/pydoc/config/tools_api.yml
haystack/tools/__init__.py
haystack/tools/component_tool.py
pyproject.toml
releasenotes/notes/add-component-tool-ffe9f9911ea055a6.yaml
test/tools/test_component_tool.py

Adds `ComponentTool` enabling Haystack components to be wrapped and used as LLM-compatible tools thus integrating them into Haystack's new tooling architecture.
- Added `ComponentTool` class to facilitate the use of Haystack components as callable tools.
- Modified `__init__.py` to include `ComponentTool` in the module exports.
- Updated `pyproject.toml` to include the `docstring-parser` dependency for documentation extraction.
This implementation enables the creation of LLM-compatible tools from existing components. Here’s an example of usage:
```python
from haystack import component, Pipeline
from haystack.dataclasses import ChatMessage, ChatRole
from haystack.tools import ComponentTool
from haystack.components.tools import ToolInvoker
from haystack.components.generators.chat import …
```

feat: Add `ComponentTool` to Haystack tools

---

docs/pydoc/config/preprocessors_api.yml

- Adding `RecursiveSplitter` to pydoc

docs: adding `RecursiveSplitter` to pydoc

---

test/components/generators/chat/test_hugging_face_api.py

- Whenever the temperature returned by the tool has the `ºC` unit in the response the model returns an empty message, making the tests fail - I'm removing it and simply keeping it at `22`
- manual (local) verification + CI test
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in case the PR includes …

test: updating `HuggingFaceAPIChatGenerator` tests

---

haystack/components/retrievers/sentence_window_retriever.py

- the deprecation warning was added in https://github.com/deepset-ai/haystack/pull/8597 and included in 2.8.0
- (related to #8590)
- we forgot to remove it before releasing 2.9.0
- remove the deprecation warning
- I …

chore: remove deprecation warning from `SentenceWindowRetriever`

---

haystack/dataclasses/chat_message.py
releasenotes/notes/rm-function-chat-role-ab401a1fb19713a7.yaml
test/dataclasses/test_chat_message.py

- fixes #8653
- deprecated in 2.9.0 -> to be removed in 2.10.0
- remove deprecated `function` `ChatRole`
- remove `from_function` class method in `ChatMessage`
CI …

chore: remove deprecated `function` `ChatRole` and `from_function` class method in `ChatMessage`

---

haystack/components/generators/chat/hugging_face_api.py
haystack/components/generators/chat/openai.py
haystack/components/generators/hugging_face_api.py
haystack/components/generators/openai.py
releasenotes/notes/add-streaming-completion-timestamp-c0ad3b8698a2d575.yaml
test/components/generators/chat/test_hugging_face_api.py
test/components/generators/chat/test_openai.py
test/components/generators/test_hugging_face_api.py
test/components/generators/test_openai.py

Enhances Langfuse integration to track the time-to-first-token (TTFT) in streaming responses. The new entry in chat message metadata `completion_start_time` enables TTFT tracking in Langfuse. We'll separately update all other relevant generators in https://github.com/deepset-ai/haystack-core-integrations/ 
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1261
- Added `completion_start_time` metadata in the `Hugging Face API` and `OpenAI` chat and non-chat generators to record the TTFT.
- Modified test cases to validate the inclusion of the `completion_start_time` and its format correctness.
This change allows developers to track the exact start time of streaming completions, aiding in performance diagnostics
Included updated unit tests for both `Hugging Face API` …

feat: Add completion start time timestamp to relevant generators

---

haystack/components/converters/pypdf.py
test/components/converters/test_pypdf_to_document.py

- fixes #8491 
- I added a test assuring that when defined like this `PyPDFToDocument(extraction_mode=PyPDFExtractionMode.LAYOUT)`, text passages are correctly extracted from PDF
- unit tests, manual verification
- CI tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in case the PR includes breaking …

test: test that PyPDF can extract passages so that they are detect by `DocumentSplitter`

---

test/components/generators/chat/test_hugging_face_api.py

- failing test in main https://github.com/deepset-ai/haystack/actions/runs/12826740828/job/35767504647
- use a more reliable model for the test (it's not easy to find alternatives, because the model should be warm and not gated)
- add the `flaky` marker to retry the live tests in this test suite if failing (unfortunately, the LM response is cached, so the marker only helps with network issues, etc.)
CI …

test: fix HF API flaky live test with tools

---

.pre-commit-config.yaml

While investigating formatting issues in https://github.com/deepset-ai/haystack/pull/8745,
I noticed an inconsistency:
- we are pinning ruff in our pre-commit hook
- our `format` job in test workflow uses the latest version of ruff
This can sometimes create this cycle:
- the `format` job fails
- you manually try to fix the format using `hatch run format` (because pre-commit hook did not take care of it)
- the pre-commit hook reverts changes
- ♾️
- pin ruff to 0.9.2 in the pre-commit hook
- unfortunately, there is no way to depend on the latest version ([pre-commit docs](https://pre-commit.com/#using-the-latest-version-for-a-repository))
In the long run, there could be better ways to fix this problem, such as running `pre-commit autoupdate` in the CI or pinning ruff also in our pyproject …

chore: update ruff version in pre-commit hook

---

haystack/components/validators/json_schema.py
haystack/tools/tool.py
pyproject.toml
releasenotes/notes/jsonschema-core-dependency-d38645d819eb0d2d.yaml

- the `jsonschema` library is used in our `Tool` implementation. The library is lightweight, and having it as a core dependency would mean making life easier for our users.
- I had previously decided not to add it as a core dependency because in the past we had some issues with testing it in the CI (see #7353 and linked PRs). These issues are fixed now.
- Many big and small projects [depend on this library](https://github.com/python-jsonschema/jsonschema/network/dependents); it is also installed by default in Colab. So I would say it's pretty safe to add it as a core dependency.
- add `jsonschema` to core dependencies and remove related lazy imports.
CI …

build: add `jsonschema` library to core dependencies

---

haystack/components/generators/chat/hugging_face_api.py
haystack/components/generators/chat/hugging_face_local.py
releasenotes/notes/streaming-callback-run-param-support-for-hf-chat-generators-68aaa7e540ad03ce.yaml
test/components/generators/chat/test_hugging_face_api.py
test/components/generators/chat/test_hugging_face_local.py

- fixes run method param support for `streaming_callback` in `HuggingFaceAPIChatGenerator` and `HuggingFaceLocalChatGenerator`
- add `streaming_callback` param to run methods of `HuggingFaceAPIChatGenerator` and `HuggingFaceLocalChatGenerator`
- extended tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added …

feat: support streaming_callback as run param for HF Chat generators

---

haystack/components/classifiers/document_language_classifier.py
haystack/components/classifiers/zero_shot_document_classifier.py
releasenotes/notes/fix-classifiers-docstrings-messages-dcae473d2bd3cb95.yaml

While trying these components, I found that we were sometimes suggesting to use nonexistent components to classify text.
- fix error messages …

fix: Document Classifiers - fix error messages

---

haystack/core/component/component.py
releasenotes/notes/component-registration-052467bb409d2e4c.yaml

The pyright language server is now able to resolve the import and provide completions for the component.
- fixes #8624
Reuse of the name of the newly created class caused a type error and the type checker did not recognize the parameters. Renaming the newly created class to `new_class` seems to fix the problem. …

fix: update component registration to use new class reference

---

license-header.txt

- Causes github CI to fail for this PR https://github.com/deepset-ai/haystack/pull/8775
Newest version of [hawkeye](https://github.com/korandoru/hawkeye/releases/tag/v6.0.0) was released earlier today. it contains breaking changes for how templates work. Check out release notes [here](https://github.com/korandoru/hawkeye/releases/tag/v6.0.0).  
Trying to test in the PR https://github.com/deepset-ai/haystack/pull/8775 since it will trigger the license header check. The changes in this PR don't seem to trigger it. 
**Update:** The change does fix the failing `Tests / format` in the PR https://github.com/deepset-ai/haystack/pull/8775 …

fix: Update license-header.txt with breaking changes from hawkeye

---

haystack/core/pipeline/draw.py
releasenotes/notes/compress-mermaid-graph-bf23918c3da6e018.yaml

- fixes #8089
When pipelines get too big, the resulting base64 output is too long when we send a request to the mermaid server leading to a HTTP 400 error. Mermaid supports compressed URLS using [Pako](https://github.com/jihchi/mermaid.ink/pull/33). With `zlib`, we are able to compress our input in the expected format and send it off to Mermaid.
I wanted to do as close to a 1:1 change so that this has 0 impact to the user. The same tests were used which *hopefully* means the changes are 1:1 as they have all passed. 
I am also asking for tests from Haystack users with big pipelines on [Discord](https://discord.com/channels/993534733298450452/993539071815200889/1332232320081592321).
I will make another PR that will use this change as a foundation for:
- Extension parameters (jpg, png, webp, …

fix: compress pipeline graphs before sending to mermaid

---

pyproject.toml

- related to #8791
- integration tests are failing for several PRs: https://github.com/deepset-ai/haystack/actions/runs/13057568264/job/36432622828?pr=8789
- temporarily pin `huggingface_hub<0.28.0` to unblock CI (and allow proper investigation)
CI
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in case …

chore: temporarily pin `huggingface_hub<0.28.0`

---

haystack/dataclasses/answer.py
haystack/dataclasses/document.py
releasenotes/notes/deprecate-dataframe-ExtractedTableAnswer-3d85649a4a7e222f.yaml

- part of #8738
- deprecate `dataframe` field in `Document`
- deprecate `ExtractedTableAnswer`
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#instal …

chore: deprecate `dataframe` field in `Document` and `ExtractedTableAnswer`

---

haystack/components/preprocessors/sentence_tokenizer.py
pyproject.toml

- fixes: using `DocumentSplitter` with nltk==3.8.1 or lower versions raises the below error
`nltk.find:No such file or directory: '/root/nltk_data/tokenizers/punkt/PY3_tab'
`Related issue in nltk: https://github.com/nltk/nltk/issues/3305
Pin `nltk==3.9.1` for `SentenceTokenizer` and `DocumentSplitter`.
This PR is a suggestion, open to discussion.
Ran the tests
Tested an example. …

fix: Pin nltk version for sentence tokenizer

---

haystack/components/preprocessors/document_splitter.py

chore: Remove DocumentSplitter warning - split_by='sentence'

---

haystack/core/pipeline/base.py
haystack/core/pipeline/draw.py
releasenotes/notes/compress-mermaid-graph-bf23918c3da6e018.yaml
releasenotes/notes/custom-mermaid-server-and-params-b88ca837375c3e0f.yaml
test/core/pipeline/test_draw.py

- - - 
this is a copy of a @lbux PR - https://github.com/deepset-ai/haystack/pull/8772 - but this one is branched from our main repo instead of the user's fork which I suspect was the reason for the failure of some integrations tests - it keeps keeps the commit history, giving the correct credit to @lbux 
- information below is a copy of the original PR
- - - 
- fixes https://github.com/deepset-ai/haystack/issues/7896
This PR is an attempt at adding support for offline pipeline draw() and show() calls for users in constrained environments where no requests to outside servers are allowed. This PR builds upon https://github.com/deepset-ai/haystack/pull/8767 and introduces no breaking changes to regular draw() and show() calls (from what I've tested). Additionally, all parameters supported …

feat: Add support for custom (or offline) Mermaid.ink server and support all parameters

---

haystack/components/embedders/hugging_face_api_document_embedder.py
haystack/components/embedders/hugging_face_api_text_embedder.py
pyproject.toml
releasenotes/notes/hf-embedders-feature-extraction-ea0421a8f76052f0.yaml
test/components/embedders/test_hugging_face_api_document_embedder.py
test/components/embedders/test_hugging_face_api_text_embedder.py

- fixes #8791
Our HF API Embedders support 3 different HF APIs using the `huggingface_hub` client: Serverless Inference API, Text Embeddings Inference (deployed locally or elsewhere), and HF Paid Inference Endpoints.
For several reasons, in the past we have opted to use `InferenceClient.post` method, but this is fragile, subject to changes (as has happened recently) and will soon be removed (in 0.31).
This is why I'm migrating to the `InferenceClient.feature_extraction` method. This solution works but may not be ideal, as explained in the comments.
- Use `feature_extraction` instead of `post`.
- Add some checks on the shape of the embeddings obtained from the API.
CI; new tests
In the CI, we are only testing the Serverless Inference API.
For these reasons, I also tested the current …

refactor: HF API Embedders - use `InferenceClient.feature_extraction` instead of `InferenceClient.post`

---

haystack/components/routers/metadata_router.py
haystack/utils/filters.py
releasenotes/notes/fix-date-comparison-ced1d6ef64534951.yaml
test/components/routers/test_metadata_router.py
test/utils/test_filters.py

I tried using the `MetadataRouter` in an indexing pipeline to only consider files uploaded after a certain date `2025-02-01`. I ran into two issues:
- Our filters utils uses `datetime.fromisoformat(value)` which doesn't support all types of ISO formatted strings resulting in an error. See more info [here](https://stackoverflow.com/questions/55542280/why-does-python-3-find-this-iso8601-date-2019-04-05t165526z-invalid). So I created a `_parse_date` function which first uses `datetime.fromisoformat(value)` for backwards compatibility and then tries to use `dateutil.parse` which is the recommended solution to handle all types of ISO formatted strings. 
- After fixing the above I tried to compare two date times `2025-02-01` and `2025-02-03T12:45:46.435816Z` where I ran …

fix: Fix filters to handle date times with timezones (loading and comparison)

---

haystack/components/connectors/openapi_service.py
releasenotes/notes/update-openapi-service-connector-e49f665968013425.yaml
test/components/connectors/test_openapi_service.py

Update `OpenAPIServiceConnector` to handle new `ChatMessage` format
- fixes https://github.com/deepset-ai/haystack/issues/8774
- Patched the `request` method in OpenAPI to handle raw responses more effectively.
- Reworked the processing of chat messages to extract tool calls and handle them for OpenAPI function invocations.
The changes affect how `OpenAPIServiceConnector` handles new `ChatMessage` format involving build in `tool_calls` property. 
Example usage:
```python
connector.run(messages=[message], service_openapi_spec=a_spec_as_a_dict_object)
```
Where `message` should now contain `tool_calls` property.
Tests verify new behavior of message processing with checks for valid tool calls. Patched OpenAPI methods are mocked to assess correct invocation and response handling. Integration …

fix: Update OpenAPIServiceConnector to new ChatMessage

---

pyproject.toml
test/components/extractors/test_llm_metadata_extractor.py

- removing AWS Bedrock related tests, removing extra dependencies from pyproject.toml …

removing from_dict/to_dict AWS tests

---

haystack/components/preprocessors/csv_document_splitter.py
test/components/preprocessors/test_csv_document_splitter.py

- Fix csv document splitter when table is only one row wide
- added a test
- I don't think any release notes for this is needed because it's a fix for a component that hasn't been released yet
- Original PR is here: https://github.com/deepset-ai/haystack/pull/8815 …

fix: Fix csv document splitter when table is only one row wide

---

pyproject.toml

- mypy is failing with `posthog==3.12.0`: https://github.com/deepset-ai/haystack/actions/runs/13259957485/job/37014402929
- pin `posthog<3.12.0`
CI …

chore: pin `posthog<3.12.0`

---

haystack/components/generators/chat/openai.py
releasenotes/notes/improve-tool-call-chunk-search-986474e814af17a7.yaml
test/components/generators/chat/test_openai.py

Enhances the processing logic to support various LLM platforms—not just OpenAI. Testing with the OpenAI Python package using the Mistral platform revealed that some platforms may place `tool_calls` in any streamed chunk (not only in the first). This change ensures that all chunks are scanned for the  `tool_calls` payload.
- Refined detection of tool calls across all streaming chunks.
- Changed the assumption that `tool_calls` appear only in the first chunk to a search that finds them anywhere.
This update ensures robust tool call tracking in streaming messages, accurately constructing payloads regardless of where the `tool_calls` appear:
```python
tool_call_index = next((i for i, chunk in enumerate(chunks) if chunk.meta.get("tool_calls")), None)
tools_len = …
```

fix: Look through all streaming chunks for tools calls

---

docs/pydoc/config/pipeline_api.yml

- Adding `AsyncPipeline` to pydocs

docs: adding `AsyncPipeline` to pydocs

---

haystack/core/pipeline/async_pipeline.py

- fixes https://github.com/deepset-ai/haystack-experimental/issues/194 …

fix: AsyncPipeline logging  name can't be overwritten

---

haystack/telemetry/_environment.py

- related to https://github.com/deepset-ai/haystack/pull/8831
- stop collecting `transformers` and `torch` in telemetry
CI …

chore: stop collecting `transformers` and `torch` in telemetry

---

haystack/components/converters/xlsx.py
releasenotes/notes/add-store-full-path-xlsx-convter-535bcb48433f7717.yaml
test/components/converters/test_xlsx_to_document.py

- Related to https://github.com/deepset-ai/haystack/pull/8619
- The `store_full_path` parameter was missed in the original implementation of `XLSXToDocument`
- Added a test …

feat: Add store_full_path to converter

---

README.md

- None
- Mention Hayhooks in README
Does not apply
As an alternative, we could add a link to the deployment page in the documentation: https://docs.haystack.deepset.ai/docs/deployment
- I ran …

chore: Add Hayhooks to README

---

haystack/__init__.py

- fixes #8048 
Add `__version__` to `__init__.py` so users can run 
```python
import haystack
print(haystack.__version__)
print(haystack.version.__version__)
``` …

fix: Add `__version__` to hasytack init

---

haystack/components/joiners/list_joiner.py
releasenotes/notes/update-list-joiner-0a068cfb058f3c35.yaml
test/components/joiners/test_list_joiner.py

Update ListJoiner to only optionally need list_type_ to be passed. By default it uses type List which acts like List[Any].
- This allows the ListJoiner to combine any incoming lists into a single flattened list.
- Users can still pass list_type_ if they would like to have stricter type validation in their pipelines.
Added type validation tests …

feat: Update list joiner

---

docs/pydoc/config/evaluation_api.yml

- "Sync docs with Readme" workflow is failing in main: https://github.com/deepset-ai/haystack/actions/runs/13371679839/job/37341382104
- remove `base` from evaluation pydoc config: the module was removed in #8838
CI …

chore: remove `base` from evaluation pydoc config

---

haystack/tools/component_tool.py
releasenotes/notes/fix-tool-description-truncation-011e8275fea4ccb0.yaml
test/tools/test_component_tool.py

`ComponentTool` truncates the tool description to 512 characters. This leads to unexpected results where because the user is not warned about it. Additionally, models support longer descriptions.
This led to a problem where the model would not even follow the schema because the description was cut too early. It makes ComponentTool not useful for many more complex use cases.
Ideally, we could get a patch release for this.
- unit tests, manual tests …

fix: ComponentTool description should not be truncated

---

test/components/generators/test_openai.py

- fixes blocking tests on this [PR](https://github.com/deepset-ai/haystack/pull/8871)
Shortened the string check and updated prompt to more reliably get name of theorem in the answer.
- I ran …

chore: Make openai test more robust

---

haystack/utils/type_serialization.py
releasenotes/notes/fix-serialize-any-type-ea0ca14eadb21b3d.yaml
test/utils/test_type_serialization.py

- fixes #8719 
Updates if check to specially handle `typing.Any` in `serialize_type`
Expanded unit tests
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING …

fix: Fix serialization of `typing.Any` when using `serialize_type` utility

---

haystack/core/pipeline/base.py
haystack/core/pipeline/component_checks.py
pyproject.toml
releasenotes/notes/fix-component-checks-with-ambiguous-truth-values-949c447b3702e427.yaml
test/components/generators/chat/test_hugging_face_api.py
test/core/pipeline/features/conftest.py
test/core/pipeline/features/pipeline_run.feature
test/core/pipeline/features/test_run.py
test/core/pipeline/test_component_checks.py
test/core/pipeline/test_pipeline_base.py

Components that returned dataframes would fail because we use '!=' to compare to the sentinel value (`_NO_OUTPUT_PRODUCED`), changing to `is not` prevents this from happening.
unit tests
- I …

fix: component checks failing for components that return dataframes

---

haystack/components/tools/__init__.py

As noticed by @sjrl in the haystack-experimental repo, we are not using the proper dunder syntax in the __init__.py for the tools package. …

fix: use dunder all for ToolInvoker

---

haystack/components/generators/chat/openai.py
releasenotes/notes/fix-openai-chat-generator-with-tools-and-streaming-9776040f0732a8aa.yaml
test/components/generators/chat/test_openai.py

- fixes #8876
Updates the `_convert_streaming_chunks_to_chat_message` method to properly accumulate the streamed chunks when constructing the arguments for a tools call. 
- added a more realistic unit test by saving data from an openai call
- added an integration test …

fix: Fix OpenAIChatGenerator + tools + streaming

---

haystack/components/joiners/list_joiner.py
test/components/joiners/test_list_joiner.py

Default output type was `List` and should be `List[Any]`.  This is a fix for a change that is not yet in a Haystack release so it's not a breaking change. 
Updated test to reflect this. 
- I …

chore: Update default output type of list joiner to be correct

---

haystack/components/generators/chat/openai.py
haystack/dataclasses/__init__.py
haystack/dataclasses/streaming_chunk.py
haystack/utils/asynchronous.py
pyproject.toml
releasenotes/notes/add-run-async-to-openai-chat-generator-3b4724af4fe4707a.yaml
test/components/generators/chat/test_openai.py
test/components/generators/chat/test_openai_async.py
test/components/generators/conftest.py

- fixes #8859
This adds `run_async` to `OpenAIChatGenerator`. It uses internally the async version of OpenAI client (which has the same methods, but ofc they return awaitable coroutines).
unit tests, integration tests, manual verification
- I've basically duplicated all the relevant tests in `test_openai_async` and make them run `run_async`. 
- The `streaming_callback` is still a `Callable[[StreamingChunk], None]`. I've tried make it support also an `Awaitable` but it breaks since `run_async` of components expects the same exact params of `run`.
- The sync and async client instances are created at init time. We may decide to create a factory method to get the correct client instance (using lru_cache on the output) as an alternative. …

Add `run_async` to `OpenAIChatGenerator`

---

test/components/builders/test_chat_prompt_builder.py
test/components/converters/test_csv_to_document.py
test/core/pipeline/test_component_checks.py
test/core/test_serialization.py
test/evaluation/test_eval_run_result.py

- I've noticed a few unused imports and unneeded imports with wildcards
- Suggestion: we could think about a set of lighter lint rules for the tests, e.g.: unused imports, unused variables - currently it seems nothing is being checked …

chore: cleaning up unused imports in tests

---

test/core/test_importing.py

test: make sure no extra modules are being imported due to `__init__` definitions

---

pyproject.toml

- part of #8896
- (failing tests: https://github.com/deepset-ai/haystack/actions/runs/13443883797/job/37565096377?pr=8878)
- pin `ddtrace<3.0.0`
CI
As explained in #8896, at some point we should make Haystack compatible with `ddtrace>=3.0.0` …

chore: pin `ddtrace<3.0.0`

---

haystack/tracing/tracer.py

- pretty sure the old import path is invalid when I look at the code here: https://github.com/DataDog/dd-trace-py/blob/main/ddtrace/__init__.py …

fix: right tracer import path

---

haystack/components/routers/file_type_router.py
releasenotes/notes/add-msg-mime-type-file-router-b33d8916caaf5976.yaml
test/components/routers/test_file_router.py

In the FileTypeRouter add explicit support for classifying .msg files with mimetype "application/vnd.ms-outlook" since the mimetypes module returns None for .msg files by default.
I did this by updating the `CUSTOM_MIMETYPES` dict. …

feat: In FileTypeRouter add `.msg` to "application/vnd.ms-outlook" mapping

---

haystack/core/pipeline/async_pipeline.py

- partial resolution of https://github.com/deepset-ai/haystack/issues/8864 but not a full fix
Any operations on the span (set_tag) should be performed before the context manager exits.
To keep the reference to the parent span, we actually need to implement async support for our tracers since the context managers context is not carried over to co-routines. There are also issues with how we handle `parent_span` (we just ignore it in most (all?) of our tracers).
Ignoring for release notes to wait for the full fix.
- I added …

fix: set tracing tags before context manager exits

---

test/components/embedders/test_hugging_face_api_document_embedder.py
test/components/embedders/test_hugging_face_api_text_embedder.py
test/components/generators/chat/test_hugging_face_api.py
test/components/generators/test_hugging_face_api.py

This reverts commit 56a3a9bd61b7391ae91e3d8179b3b33918ef4932.
- fixes #8890 
I upgraded Haystack Bot to a PRO subscription on HuggingFace. It's token should now have a higher API limit, which is why we can re-enable the HF API live integration tests that were temporarily skipped.
CI, for example https://github.com/deepset-ai/haystack/actions/runs/13500630092/job/37718234502?pr=8914#step:8:98 …

Revert "test: skip HF API live integration tests (#8889)"

---

test/components/generators/test_hugging_face_api.py

- https://github.com/deepset-ai/haystack/pull/8936 fails due to weird responses from [zephyr-7b-beta](https://huggingface.co/HuggingFaceH4/zephyr-7b-beta) model.
- temporarily skip these tests
CI …

skip HF API integration test

---

haystack/components/routers/conditional_router.py
releasenotes/notes/fix-conditional-router-to-dict-5af887da50effe11.yaml
test/components/routers/test_conditional_router.py

- fixes #8904 
This PR includes changes to ensure that the `to_dict` method in the `ConditionalRouter` class does not mutate the original `routes` and adds a corresponding test to verify this behavior.
unit tests
- …

Avoid mutating self.routes in ConditionalRouter to_dict method

---

haystack/core/pipeline/base.py
releasenotes/notes/fix-socket-input-overwriting-6c29d657e4887458.yaml
test/core/pipeline/features/pipeline_run.feature
test/core/pipeline/features/test_run.py
test/core/pipeline/test_pipeline_base.py

- fixes [#8937](https://github.com/deepset-ai/haystack/issues/8937)
Check if a component run produced an output and only overwrite inputs on an existing socket if an output was actually produced.
- integration tests, unit tests
- 
The test for the cyclic case is a bit constructed and I don't know what use case would need this pattern but it's good to make sure that it would work. The BranchJoiner example is something that a customer actually ran into. …

fix: only overwrite existing socket inputs when we provide a new value

---

test/components/generators/chat/test_openai.py

Test `test_init_should_also_create_async_client_with_same_args` was present both in `test_openai.py` and `test_openai_async.py`.
CI …

test: remove duplicate test on OpenAIChatGenerator

---

haystack/components/generators/chat/openai.py
haystack/tools/component_tool.py
releasenotes/notes/fix-componenttool-for-openai-tools_strict-998e5cd7ebc6ec19.yaml
test/components/generators/chat/test_openai.py
test/components/generators/chat/test_openai_async.py
test/tools/test_component_tool.py

- fixes https://github.com/deepset-ai/haystack/issues/8912
- always set `additionalProperties: false` for function schema
- added integration test …

fix: in OpenAIChatGenerator set additionalProperties to False when tools_strict=True

---

haystack/components/generators/chat/azure.py

Replace `AzureOpenAIGenerator` with `AzureOpenAIChatGenerator` in docstrings.

fix: error in docstring of AzureOpenAIChatGenerator

---

haystack/components/embedders/azure_document_embedder.py
releasenotes/notes/add-azure-embedder-exception-handler-c10ea46fb536de3b.yaml
test/components/embedders/test_azure_document_embedder.py

- fixes #8869 
- Add error handling in _embed_batch to continue processing remaining documents
- Log failed embeddings with batch range information
- Match error handling behavior with OpenAIDocumentEmbedder
- Add unit tests for graceful error handling
- Added unit tests for graceful error handling in the `AzureOpenAIDocumentEmbedder` class …

feat: Enhance error handling in Azure document embedder

---

haystack/evaluation/eval_run_result.py

- Related to https://github.com/deepset-ai/haystack/issues/8955
- Update the DeprecationWarning to warn about the removal of the deprecated methods in 2.12 because the warning was not part of the 2.10 release as Stefano pointed out: https://github.com/deepset-ai/haystack/blob/v2.10.x/haystack/evaluation/eval_run_result.py …

chore: update EvalRunResult deprecation warning to 2.12

---

CONTRIBUTING.md
pyproject.toml
releasenotes/notes/python-3.13-support-68d6f52887611eac.yaml

- fixes #8825
I experimented with Python 3.13 locally (Ubuntu) and in a draft PR (https://github.com/deepset-ai/haystack/pull/8959; Ubuntu, MacOs, Windows).
**What I found**
- our core dependencies work well with Python 3.13 except for Spacy (and, to some extent, Whisper).
- Spacy (used in the `NamedEntityExtractor`) is not yet compatible: https://github.com/explosion/spaCy/issues/13658.
- Whisper has some installation issues with `uv` (but works with `pip`): https://github.com/astral-sh/uv/issues/6852
- **Contributors** using Python 3.13 will encounter errors when installing test dependencies due to Spacy and Whisper.
- In my opinion, this shouldn't prevent **final users** from using Python 3.13.
- support Python 3.13 and communicate it
CI; if you are curious, check also tests in …

build: support python 3.13

---

pyproject.toml

`openapi-llm` dependency was introduced in https://github.com/deepset-ai/haystack/pull/8808.
Probably due to an oversight, it was introduced as a required dependency instead of an optional one.
- Make `openapi-llm` an optional dependency
CI …

chore: make `openapi-llm` an optional dependency

---

.github/workflows/e2e.yml
haystack/core/pipeline/base.py
haystack/core/pipeline/draw.py
releasenotes/notes/mermaid-timeout-d0bd83dfa90f8544.yaml
test/core/pipeline/test_draw.py

- fixes #8967
- increase default timeout to 30 seconds (instead of 10)
- expose the `timeout` parameter in `Pipeline.draw` and `Pipeline.show`, so that users can control this behavior.
CI; new unit test.
I also triggered e2e tests that were failing due to the timeout. -> https://github.com/deepset-ai/haystack/actions/runs/13673782419/job/38229648241?pr=8973
I think that waiting more than 10 seconds to get a Pipeline rendering is not nice.
I have the feeling that this might be related to the fact that we are now sending compressed data to the server (introduced in https://github.com/deepset-ai/haystack/pull/8767) and decompression can also take time on the server. However, there have also been several recent changes in [mermaid.ink](https://github.com/jihchi/mermaid.ink) that may have an …

feat: increase Mermaid timeout and make it configurable

---

haystack/components/writers/document_writer.py
releasenotes/notes/async-document-writer-9458ced66c1c38c7.yaml
test/components/writers/test_document_writer.py

- fixes #8961 
- Add run_async implementation to DocumentWriter from haystack-experimental including tests. Compared to the implementation in haystack-experimental I only changed docstrings.
Tests require an InMemoryDocumentStore with write_documents_async to pass. Open issue: https://github.com/deepset-ai/haystack/issues/8960 …

feat: Add async run to DocumentWriter

---

test/components/generators/chat/test_hugging_face_api.py
test/components/generators/test_hugging_face_api.py
test/components/generators/test_hugging_face_local_generator.py

- fixes #8939 
- update to mistral model which is better at following instructions
- make sure to add instruction tokens or use tokenizer.apply_chat_template when not using the chat completion endpoint
Only updated tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in case the PR includes breaking …

fix: Update flaky HugginFace Generator tests to use more reliable model and add instruction tokens

---

test/components/generators/chat/test_hugging_face_api.py
test/components/generators/test_hugging_face_api.py

refactor: Use Phi instead in HF API tests

---

haystack/components/converters/output_adapter.py
haystack/core/component/component.py
haystack/core/component/types.py
pyproject.toml
releasenotes/notes/drop-python-3.8-868710963e794c83.yaml
test/components/converters/test_markdown_to_document.py
test/core/component/test_component.py
test/tools/test_from_function.py

- fixes #8894
- drop support for Python 3.8
CI

build: drop Python 3.8 support

---

.github/workflows/release_notes.yml
.github/workflows/release_notes_skipper.yml
releasenotes/config.yaml
releasenotes/notes/add-batch_size_faiss_init-5e97c1fb9409f873.yaml
releasenotes/notes/run-async-azure-54450f0c2495f5c8.yaml

While releasing 2.11.0, an incorrectly formatted release note caused errors.
Currently, our release notes linting is based on `yamllint`, which is too permissive and does not check reno format.
- use [`reno lint`](https://docs.openstack.org/reno/latest/user/usage.html#checking-notes)
- fix incorrect release notes
CI; problematic release notes were found -> https://github.com/deepset-ai/haystack/actions/runs/13680619540/job/38251779192 …

ci: improve release notes format checking

---

haystack/components/joiners/branch.py
releasenotes/notes/update-docs-branch-joiner-bcabe5158bdb03af.yaml

While working on the deserialization issue I found that the doc strings of the `BranchJoiner` were a little confusing and in some cases out of date so I updated them. Hopefully this makes it more understandable where `BranchJoiner` should be used.  …

docs: Update docstrings of `BranchJoiner`

---

haystack/components/converters/pdfminer.py
releasenotes/notes/adding-CID-detection-PDFMinerToDocument-0195a929d64cd502.yaml
test/components/converters/test_pdfminer_to_document.py

- fixes #8905 
- Added functionality to detect and report undecoded CID characters in PDF text extraction, helping users identify potential text extraction quality issues when processing PDFs with non-standard fonts.
- Added CID_PATTERN regex constant to detect CID character patterns
- Implemented new `detect_undecoded_cid_characters()` method to analyze text for CID characters
- Enhanced the run() method to include CID character detection and warning logs
- unit tests, integration tests, manual verification
- I added unit …

feat: adding function to detect unmapped CID characters in `PDFMinerToDocument`

---

haystack/document_stores/in_memory/document_store.py
test/document_stores/test_in_memory.py

- keep track of whether the class itself created the thread executor and if so we clean up when the class is destroyed
- unit tests, integration tests, manual verification, instructions for manual tests -->
- I …

fix: cleaning up `InMemoryDocumentStore` executor when created inside the class

---

haystack/utils/type_serialization.py
releasenotes/notes/fix-type-sede-optional-ea3c9a6b9de60c6e.yaml
test/utils/test_type_serialization.py

- fixes https://github.com/deepset-ai/haystack/issues/8971
- Updates the serialization and deserialization methods in `haystack/utils/type_serialization.py` to handle `Optional` properly.
- Refactored the serialization code to be simpler
- Refactored nested function to be a private helper function
- Updated deser to allow users to not have to specify `typing.` for `typing` library types (e.g. can use `List[str]` instead of `typing.List[str]`)
Greatly expanded tests
- I've …

fix: Fix type serialization and deserialization

---

haystack/core/type_utils.py
releasenotes/notes/add-bare-type-validation-a4720bc66ccaf5ef.yaml
test/core/pipeline/test_type_utils.py

- fixes #8874 
- Treat bare types (e.g., List, Dict) as generic types with Any arguments during type compatibility checks.
- added unit tests  …

feat: Improve type validation for bare types

---

haystack/dataclasses/document.py
releasenotes/notes/add-dataframe-to-legacy-fields-0f2c9abc00c67aa5.yaml
test/dataclasses/test_document.py

- fixes https://github.com/deepset-ai/haystack/issues/9025
- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/1528
- add `dataframe` to legacy fields for the `Document` dataclass: these fields are skipped but allowed for backward compatibility.
CI; new specific test. …

fix: add `dataframe` to legacy fields for `Document`

---

haystack/components/builders/chat_prompt_builder.py
haystack/components/builders/prompt_builder.py
releasenotes/notes/warning-chat-and-prompt-builder-ca42295df9c1b770.yaml
test/components/builders/test_chat_prompt_builder.py
test/components/builders/test_prompt_builder.py

- fixes https://github.com/deepset-ai/haystack/issues/8901
Related to https://github.com/deepset-ai/haystack/issues/8903
Add warning to ChatPromptBuilder and PromptBuilder if they have variables, but `required_variables` is not set
Added tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in case the …

feat: Add warning to ChatPromptBuilder and PromptBuilder if they have variables, but `required_variables` is not set

---

haystack/core/serialization.py

- We missed a import module call when first moving over to a thread safe version so I updated it
- Also updated logger calls to use the correct syntax and remove f-strings
Existing tests
- I …

chore: Use thread safe import in `import_class_by_name` utility function

---

haystack/components/generators/chat/openai.py
test/components/generators/chat/test_openai.py
test/components/generators/chat/test_openai_async.py

- fixes failing Mistral [tests](https://github.com/deepset-ai/haystack-core-integrations/actions/runs/13888924382) in core-integrations
Changes how we look for the `finish_reason` when processing streaming chunks. OpenAI and Mistral put the finish_reason in different chunks so we just now look for the last one that is not None.
Tested manually for mistral and ensured existing OpenAI tests still work. …

refactor: Update how we look for finish_reason

---

haystack/evaluation/eval_run_result.py
releasenotes/notes/removing-deprecated-EvalRunResult-d28c2eb407da0051.yaml

chore: removing `EvalRunResult` deprecation warnings

---

haystack/__init__.py
releasenotes/notes/haystack-init-eager-imports-b0aa339bf8845186.yaml

While working on #9037, I ran into a very strange type checking issue:
I added type hints to the `@component.output_types` decorator but I could not get mypy to check the type of the underlying `run` method.
After a while debugging, it turned out that `from haystack import component` had some issues, while `from haystack.core.component import component` worked perfectly in terms of static type checking.
If we revert to eager imports in `haystack/__init__.py`, this problem goes away.
- use eager imports in `haystack/__init__.py`
- no strange type checking issues
- code is much simpler, to read and maintain
CI
Ofc, this comes at a (small) cost in terms of performance.
 `import haystack` (full Haystack installation, CPU import times in milliseconds - User time + System time):
- before this …

fix: use eager imports in `haystack/__init__.py`

---

haystack/components/joiners/branch.py

- update docstring, OutputAdapter needs to be initialised with `unsafe=True` and .text instead of .content for the ChatMessage …

docs: updating docstring `BranchJoiner`

---

e2e/pipelines/test_evaluation_pipeline.py

fix: adding pylint disable for end2end tests evaluation

---

haystack/logging.py
releasenotes/notes/fix-logging-index-error-c58691db633542c5.yaml

- fixes haystack logging raising another error when logging exceptions
We've seen this for a production pipeline:
```
IndexError: Replacement index 0 out of range for positional args tuple
```
Here's the logline that caused this error:
```python
except Exception as e:
logger.error(
f"Component {component.__class__.__name__} with prefix '{prefix}' failed with exception: {str(e)}",
exc_info=True,
)
```
relevant stacktrace:
```
File "/home/haystackd/.local/lib/python3.12/site-packages/haystack/logging.py", line 144, in _log_only_with_kwargs
return func(
^^^^^
File "/home/haystackd/.pyenv/versions/3.12.8/lib/python3.12/logging/__init__.py", line 1568, in error
self._log(ERROR, msg, args, **kwargs)
File "/home/haystackd/.pyenv/versions/3.12.8/lib/python3.12/logging/__init__.py", line 1682, in …
```

fix: don't break on IndexError in logging

---

haystack/core/pipeline/base.py
test/core/pipeline/test_pipeline_base.py

- fixes #9002
The current error message is misleading. Improve it and show registry for imported components.
Existing tests …

fix: improve error message for incorrect component types

---

test/components/generators/chat/test_openai.py

- this test sometimes fails because the two times do not differ : https://github.com/deepset-ai/haystack/actions/runs/13952175226/job/39054633236?pr=9067
- relax the flaky test
CI
- I ran …

test: OpenAIChatGenerator - relax flaky test

---

examples/resume_breakpoints.py
haystack/core/pipeline/pipeline.py

- Add a new `load_state` function in pipeline logic
- add a metadata key in `resume_state` and store state_id
- add `validate_state` to validate the `debug_state` has all the required high level keys
- add `validate_component_state` to validate if components passed in `debug_state` are in pipeline
Manual testing …

Improve state resuming mechanism

---

haystack/dataclasses/chat_message.py
releasenotes/notes/chatmessage-serde-updates-f211c930e59c59b6.yaml
test/components/builders/test_chat_prompt_builder.py
test/dataclasses/test_chat_message.py

- fixes #9009, fixes #8740
- modify `ChatMessage.to_dict()` to return a dictionary with the keys: `role`, `content`, `meta`, and `name` (instead of `_role`, ...)
- make `ChatMessage.to_dict()` support and deserialize these formats:
- current format (`role`, `content`, ...) - 2.12.0
- previous format (`_role`, `_content`, ...) - >=2.9.0, <2.12.0 
- pre 2.9.0 format (`content` is a string) - <2.9.0
CI; new tests
If users explicitly consume `ChatMessage.to_dict()` output, this is a breaking change -> communicated in the release note. 
For pipeline users, I don't expect this to break anything.
However, please review this PR carefully in case I missed something.
Once this is merged, I will coordinate with @dfokina to remove the last 2 sections from 2.12.0 [`ChatMessage` …

refactor!: `ChatMessage` serialization-deserialization updates

---

haystack/components/converters/openapi_functions.py
haystack/components/converters/output_adapter.py
haystack/components/embedders/hugging_face_api_document_embedder.py
haystack/components/embedders/hugging_face_api_text_embedder.py
haystack/components/evaluators/llm_evaluator.py
haystack/components/readers/extractive.py
haystack/components/routers/conditional_router.py
haystack/evaluation/eval_run_result.py
test/components/embedders/test_hugging_face_api_document_embedder.py
test/components/embedders/test_hugging_face_api_text_embedder.py
test/components/routers/test_conditional_router.py

Across our codebase, we mostly use `logging.warning` but sometimes we also use `warnings.warn`.
We have decided to:
- use `logging.warning`
- use `warnings.warn` (`DeprecationWarning`) only for deprecations
- replace `warnings.warn` with `logging.warning` (taking also care of structured logging)
CI; adapted some tests on warnings …

chore: make Haystack warnings consistent

---

haystack/components/audio/whisper_local.py

- adding missing parameter in whisper local docstrings

docs: fixing docstrings

---

haystack/components/extractors/llm_metadata_extractor.py
releasenotes/notes/llmmetadataextractor-chatgenerator-a038b2d32d2bfc5d.yaml
test/components/extractors/test_llm_metadata_extractor.py

- fixes #9061
- allow passing a `chat_generator: ChatGenerator` init parameter in the `LLMMetadataExtractor` to configure the underlying LLM
- deprecate `generator_api` and `generator_api_params` initialization parameters; deprecate `LLMProvider`.
CI; new tests
Most of the code in this PR is to handle this intermediate phase where `chat_generator`, `generator_api` and `generator_api_params` are all acceptable init parameters. Removing the latter two will greatly simplify the code. …

refactor: `LLMMetadataExtractor` - adopt `ChatGenerator` protocol: deprecate `generator_api`, `generator_api_params` and `LLMProvider`

---

haystack/core/component/component.py
releasenotes/notes/output-types-decorator-better-type-hinting-51bb3f28f55954b4.yaml

- type hinting for the `component.output_types` decorator was introduced in https://github.com/deepset-ai/haystack/pull/9074
- I forgot to explicitly support `run_async` methods which have a different type and now we have mypy failures: https://github.com/deepset-ai/haystack/actions/runs/14040072535/job/39308204626
- extend type hinting to support `run_async` methods
- choose more expressive names for the `TypeVar`s and `ParamSpec`
- CI
- locally run mypy on all Haystack
- checked that the `ChatGenerator` protocol still works (we are not overshadowing `run` methods types). I used the following code.
```python
from haystack.components.extractors.llm_metadata_extractor import LLMMetadataExtractor, LLMProvider
from haystack.components.generators.chat.openai import OpenAIChatGenerator
from …
```

fix: improve `component.output_types` decorator type hinting to support `run_async` methods

---

.github/workflows/tests.yml
haystack/__init__.py

- happened that in #9074 we changed some types in core classes
- since mypy is currently configured to run only on the changed python files of a PR, it did not catch errors
https://github.com/deepset-ai/haystack/blob/dae8c7babaf28d2ffab4f2a8dedecd63e2394fb4/.github/workflows/tests.yml#L249
- whenever at least one python file is changed, make mypy run across all the codebase
CI; triggered a run by temporarily changing a python file (https://github.com/deepset-ai/haystack/pull/9103/commits/9b5457a543c001c02572f23bb6ea056633806527) -> [mypy run](https://github.com/deepset-ai/haystack/actions/runs/14042523294/job/39316170468) (failures in the logs are related to #9102)
In this case, mypy spent 1m22s (for comparison, in #9099, mypy ran on a single file and took 1m5s).
Perhaps we have not done …

ci: run mypy across the codebase

---

haystack/core/pipeline/async_pipeline.py
haystack/core/pipeline/pipeline.py
releasenotes/notes/add-error-message-component-run-failure-b956852263d41c3c.yaml
test/core/pipeline/test_pipeline.py

- fixes https://github.com/deepset-ai/haystack-private/issues/115
Enhance error handling by raising a detailed runtime error when a component fails, including the component's `name` and `type` in the error message for better debugging.
Added a test
Existing tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and …

enhancement: add detailed error message for failed component run

---

test/components/generators/chat/test_openai_async.py

- in #9075, we relaxed the requirements of a sync flaky test which sometimes failed.
- now the corresponding async test is failing sometimes: https://github.com/deepset-ai/haystack/actions/runs/14057739202/job/39361225095
- relax also the async test
CI
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in …

test: `OpenAIChatGenerator` - relax async test

---

test/core/pipeline/test_draw.py

- related to #9107 
- skip/remove some `Pipeline.draw` integration tests (better explained in the comments)
CI
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRI …

test: skip/remove some `Pipeline.draw` integration tests

---

haystack/components/evaluators/llm_evaluator.py
releasenotes/notes/llm-evaluators-chat-generator-bf930fa6db019714.yaml
test/components/evaluators/test_context_relevance_evaluator.py
test/components/evaluators/test_faithfulness_evaluator.py
test/components/evaluators/test_llm_evaluator.py

- part of #9062 (I decided to split the work to keep PRs small)
- refactor `LLMEvaluator` and child classes (`ContextRelevanceEvaluator` and `FaithfulnessEvaluator`) to use a Chat Generator instead of a Generator
- breaking: replace the public attribute `self.generator` with `self._chat_generator`
This would not be strictly required but:
- in a future PR we will allow users to pass a `chat_generator` instance and I think exposing a `generator` attribute would be confusing
- I believe that the `generator`/`_chat_generator` attribute should not be part of the public API of this component
CI; adapted tests
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code …

refactor!: use Chat Generator in LLM evaluators

---

haystack/components/evaluators/document_recall.py

- fix:  converting methods to `staticmethod`
- docs: typo
- unit tests, integration tests, manual verification, instructions for manual tests --> …

fix:  converting methods to `staticmethod` and fixing docstrings in `DocumentRecallEvaluator`

---

test/core/pipeline/test_draw.py

- https://github.com/deepset-ai/haystack/issues/9107
- today this test keeps failing: https://github.com/deepset-ai/haystack/actions/runs/14104890422/job/39510021594?pr=9120
- temporarily skip `test_to_mermaid_image` integration test
CI …

test: temporarily skip `test_to_mermaid_image` integration test

---

haystack/components/embedders/azure_document_embedder.py
haystack/components/embedders/azure_text_embedder.py
haystack/components/generators/azure.py
haystack/components/generators/chat/azure.py
releasenotes/notes/fix-9127-a16104e9efd4b8f2.yaml
releasenotes/notes/fix-max-retries-azure-open-ai-a16104e9efd4b8f2.yaml
test/components/embedders/test_azure_document_embedder.py
test/components/embedders/test_azure_text_embedder.py
test/components/generators/chat/test_azure.py
test/components/generators/test_azure.py

- fixes #9127
Check is max_retries is None and only in that case check env var.
Unit tests
None
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#insta …

fix: manage max_retries=0 in AzureOpenAIGenerator, AzureOpenAIChatGenerator, AzureOpenAITextEmbedder, AzureOpenAIDocumentEmbedder

---

haystack/components/embedders/azure_document_embedder.py
haystack/components/embedders/azure_text_embedder.py
haystack/components/generators/azure.py
haystack/components/generators/chat/azure.py
haystack/components/generators/openai_dalle.py
releasenotes/notes/dalle-fix-max-retries-703c36ce354a2e45.yaml
test/components/generators/test_openai_dalle.py

- similar to #9127: when the initialization parameter is provided and is equal to 0, `max_retries` was incorrectly set to an env var value or 5
- same fix as #9128: if the initialization parameter is not `None`, take it into account
- I also made the same fix to `timeout` in some components for the sake of consistency: in this case, 0 is not a very meaningful value
CI; small new test …

fix: `DALLEImageGenerator` - ensure `max_retries` is correctly set when 0

---

haystack/components/agents/agent.py
releasenotes/notes/agent-exit-conditions-d8ffd979d961cd6d.yaml
test/components/agents/test_agent.py

- fixes #9093 
- Rename init param of Agent component from `exit_condition` to `exit_conditions` 
- Change type from str to ~~List[str]~~ Optional[List[str]] and update the validation in the init method and the check in the run method accordingly
- Add a test case
CI
We could also keep the name of the init param unchanged as just `exit_condition`. Basically one could argue it's one big OR condition defined by the list of str in `exit_condition`. I though `exit_conditions` makes it more visible that there can be more than one value. Happy to discuss.
- I have updated the related issue …

feat: support multiple exit conditions in Agent and rename init param

---

haystack/components/agents/agent.py
releasenotes/notes/check-chatgenerator-tools-support-f684c1ad0d9ad108.yaml
test/components/agents/test_agent.py

- fixes #9133 
- Raise an error in the init of the Agent if the run method of the chat_generator does not have a tools input parameter
- Added a unit test with a ChatGenerator that implements the protocol but doesn't accept tools in its run method
new unit test
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added …

feat: Agent checks that its chat_generator supports tools

---

haystack/components/agents/agent.py
test/components/agents/test_agent.py

- to deserialize `chat_generator` in `Agent`, use the `deserialize_chatgenerator_inplace` utility function (introduced in #9122)
CI …

chore: use `deserialize_chatgenerator_inplace` utility function in `Agent`

---

haystack/components/preprocessors/recursive_splitter.py
pyproject.toml
releasenotes/notes/recursive-splitter-token-df56428887ac45bd.yaml
test/components/preprocessors/test_recursive_splitter.py

- Related to https://github.com/deepset-ai/haystack-private/issues/117
- Add `"token"` as `split_unit` with hardcoded tiktoken tokenizer
- Add tiktoken as extra dependency
- Fix bug in fallback logic when `split_overlap` is not 0
- Update warmup method to only load nltk if needed
Added new tests, ran locally
I am convinced I found a bug in the RecursiveDocumentSplitter's logic that handles overlap in the fallback implementation. What I need to better understand is the expected behavior and if the fix that I propose results in that behavior.
- I have updated the related issue with new …

feat: Add option to split by number of tokens to RecursiveDocumentSplitter

---

haystack/components/agents/agent.py
haystack/dataclasses/state.py
haystack/dataclasses/state_utils.py
releasenotes/notes/add-messages-to-state-1d10f1dc449be694.yaml
test/components/agents/test_agent.py
test/dataclasses/test_state.py

- partially addresses https://github.com/orgs/deepset-ai/projects/5/views/39?pane=issue&itemId=101983958&issue=deepset-ai%7Chaystack-experimental%7C237
- Moves storage of messages into State rather than just in the while loop inside of Agent. This means State requires having a `messages` field defined in its schema. 
- This allows a user to pass a custom handler through the State schema to modify how to accumulate messages throughout an Agent run. 
- Renamed `max_runs_per_component` to `max_agent_steps` to better reflect what the variable does.
Added integration and unit tests.
- I have …

feat: Move storing of messages into State in Agent

---

haystack/components/tools/tool_invoker.py
haystack/tools/component_tool.py
haystack/tools/tool.py
releasenotes/notes/add-outputs-to-string-fa3380fd072c8850.yaml
test/components/generators/chat/test_hugging_face_api.py
test/components/generators/chat/test_hugging_face_local.py
test/components/generators/chat/test_openai.py
test/components/tools/test_tool_invoker.py
test/tools/test_tool.py

- fixes https://github.com/deepset-ai/haystack-experimental/issues/237
Adds `outputs_to_string` to Tool and ComponentTool to allow users to customize how the output of a Tool should be converted into a string so that it can be provided back to the ChatGenerator in a ChatMessage. 
If `outputs_to_string` is not provided a default converter is used within ToolInvoker. The default handler uses the current default behavior. 
Updated tests. …

feat: Add `outputs_to_string` to Tool and ComponentTool

---

haystack/core/pipeline/base.py
test/core/pipeline/test_pipeline_base.py

- add a check that a component name cannot contain `.` (dot) 
- unit tests, integration tests, manual verification, instructions for manual tests  …

test: adding `Pipeline` component name checks - cannot have `.` (dot characters)

---

pyproject.toml

- fixes  #9159
- pin `blis<1.2.1` for python 3.9, as proposed in the issue
CI.
Unit tests times seem to have acceptable values now. …

ci: pin blis for python 3.9

---

haystack/core/pipeline/async_pipeline.py
releasenotes/notes/fix-content-tag-name-async-pipeline-efda4b6298ccd11c.yaml

- fixes https://github.com/deepset-ai/haystack/issues/9139
Updates the tag name to be `haystack.component.output` instead of `haystack.component.outputs` (so drop the `s`). Our tracers expect the tag name to be `haystack.component.output` and this typo is what caused all component outputs to not be logged when using AsyncPipeline in Langfuse.
E.g. Here is what it looks like with the misnamed tag
And with the correctly named tag
Tested locally using langfuse integration
- I've …

fix: Fix content tag name to match one we use in Pipeline

---

e2e/pipelines/test_dense_doc_search.py
e2e/pipelines/test_extractive_qa_pipeline.py
e2e/pipelines/test_hybrid_doc_search_pipeline.py
e2e/pipelines/test_preprocessing_pipeline.py
e2e/pipelines/test_rag_pipelines_e2e.py

- e2e nightly test fail due to Mermaid timeouts: https://github.com/deepset-ai/haystack/actions/runs/14232107561/job/39890226888
- investigated in #9107
- do not draw pipelines in e2e tests
CI …

test: stop drawing pipelines in e2e tests

---

e2e/pipelines/test_extractive_qa_pipeline.py

fix: removing unused imports in e2e tests

---

test/components/embedders/test_azure_document_embedder.py
test/components/embedders/test_azure_text_embedder.py

- new tests for these components have been introduced in #9136
- since they do not monkeypatch the required environment variables, these tests fail in PR from forks (where these env var are not set) - see #9140
- monkeypatch the specific environment variables
- CI
- local test: I ran the unit tests in a local environment without the required environment variables …

test: make Azure embedders tests correctly run on PRs from forks

---

haystack/components/generators/chat/azure.py
haystack/components/generators/chat/hugging_face_api.py
haystack/components/generators/chat/hugging_face_local.py
releasenotes/notes/support-toolset-initialization-1ccbc174abf16bd2.yaml
test/components/generators/chat/test_azure.py
test/components/generators/chat/test_hugging_face_api.py
test/components/generators/chat/test_hugging_face_local.py

Update ChatGenerators to support initialization with a Toolset. 
- Modified the `tools` parameter to accept either a list of `Tool` objects or a `Toolset` instance 
- Added new serialization logic to handle `Toolset` in the `to_dict()` methods across relevant classes.
- Updated tests to validate the initialization and usage of `Toolset` in existing generators.
The updated chat generators can now be instantiated with a `Toolset`, enhancing tool management:
```python
toolset = Toolset(tools)  # where tools is a list of Tool objects
generator = AzureOpenAIChatGenerator(azure_endpoint="your-endpoint", tools=toolset)
```
Users can seamlessly pass a `Toolset` instead of a list of Tool instances
Test cases were added to ensure that the chat generators can be initialized with a `Toolset` …

feat: Add Toolset support in ChatGenerator(s)

---

haystack/components/generators/chat/azure.py
haystack/components/generators/chat/hugging_face_api.py
haystack/components/generators/chat/hugging_face_local.py
haystack/components/generators/chat/openai.py
haystack/components/tools/tool_invoker.py
haystack/tools/__init__.py
haystack/tools/serde_utils.py
haystack/tools/tool.py
haystack/utils/misc.py
test/tools/test_serde_utils.py
test/tools/test_tool.py

In #9161, a new utility function `serialize_tools_or_toolset` was introduced in utils/misc.py.
The corresponding deserialization function `deserialize_tools_inplace` is in tools/tool.py.
- move all Tool serde utility functions in tools/serde_utils.py
- add unit tests for uncovered cases
CI …

refactor: reorganize Tool serde utility functions

---

haystack/components/agents/agent.py
haystack/components/generators/chat/azure.py
haystack/components/generators/chat/hugging_face_api.py
haystack/components/generators/chat/hugging_face_local.py
haystack/components/generators/chat/openai.py
haystack/components/tools/tool_invoker.py
haystack/tools/__init__.py
haystack/tools/serde_utils.py
releasenotes/notes/rename-deserialize_tools_inplace-f10d72127be54bed.yaml
test/tools/test_serde_utils.py

Rename `deserialize_tools_inplace` serde util method to `deserialize_tools_or_toolset_inplace` to have better symmetry with the companion method `serialize_tools_or_toolset`

chore: Rename deserialize_tools_inplace -> deserialize_tools_or_toolset_inplace

---

haystack/components/embedders/azure_text_embedder.py
haystack/components/embedders/openai_text_embedder.py
releasenotes/notes/azure-text-embedder-inherit-ea230e61cba3a90f.yaml
test/components/embedders/test_azure_text_embedder.py

- fixes #9017
- twin PR of #9189
- make `AzureOpenAITexttEmbedder` inherit from `OpenAITextEmbedder`
- get `run_async` implementation for free!
- CI
- I did not remove or add new tests for `AzureOpenAITexttEmbedder` (I tested `run_async locally` and works as expected) …

feat: make `AzureOpenAITexttEmbedder` inherit from `OpenAITextEmbedder` - async support 

---

haystack/components/embedders/azure_document_embedder.py
haystack/components/embedders/openai_document_embedder.py
releasenotes/notes/azure-doc-embedder-inherit-1028a68e99561ab2.yaml
test/components/embedders/test_azure_document_embedder.py
test/components/embedders/test_openai_document_embedder.py

- fixes #9016
- make `AzureOpenAIDocumentEmbedder` inherit from `OpenAIDocumentEmbedder` (similar to what was done for Generators)
- get `run_async` implementation for free!
- do not replace newlines with spaces in the text to embed (see https://github.com/deepset-ai/haystack/pull/9084#discussion_r2025599166).
- CI
- I did not remove or add new tests for `AzureOpenAIDocumentEmbedder` (I tested `run_async` locally and works as expected) …

feat: make `AzureOpenAIDocumentEmbedder` inherit from `OpenAIDocumentEmbedder` - async support

---

haystack/core/errors.py
haystack/core/pipeline/async_pipeline.py
haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
releasenotes/notes/add-attributes-to-pipeline-runtime-error-03941943aaf89880.yaml
test/core/pipeline/features/pipeline_run.feature
test/core/pipeline/test_pipeline.py

- fixes #9166 
- Adds attributes `component_type`, and `component_name` to `PipelineRuntimeError`
- Adds class methods for constructing `PipelineRuntimeError` from two different scenarios (`from_exception` and `from_invalid_output`)
Updated tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in case …

enhancement: Add attributes to PipelineRuntimeError

---

.github/workflows/tests.yml
pyproject.toml

When changing dependencies, the `lint` workflow (including mypy) should run appropriately to find type issues.
This did not happen, for example, in #9178.
- make the `lint` workflow also monitor pyproject.toml
I tested this in this PR, triggering `lint` with a change to pyproject.toml. Mypy ran: https://github.com/deepset-ai/haystack/actions/runs/14353439800/job/40237681508 …

ci: make `lint` workflow check pyproject.toml

---

haystack/components/agents/agent.py
haystack/dataclasses/state.py
releasenotes/notes/fix-agent-output-messages-550404a95199bb67.yaml
test/components/agents/test_agent.py
test/dataclasses/test_state.py

- fixes #9193 
- Set `messages` in state_schema at init time of Agent. This is needed to properly set `messages` as an output type of Agent and was the original intent of this PR https://github.com/deepset-ai/haystack/pull/9150
- Added tests
- Also added more tests for State
Most of the line changes come from adding tests. …

fix: Set `messages` in state_schema at init time of Agent

---

haystack/components/embedders/hugging_face_api_text_embedder.py
releasenotes/notes/adding-async-huggingface-api-text-embedder-ad68e201fcef09bb.yaml
test/components/embedders/test_hugging_face_api_text_embedder.py

- fixes #9019 
I have added run_async method for HuggingFaceAPITextEmbedder and unit test for it
I have added an integration test. All the unit tests are passing locally. …

feat: add run_async for HuggingFaceAPITextEmbedder

---

test/components/embedders/test_hugging_face_api_text_embedder.py

- removing some of the async tests

fix: removing for `HuggingFaceTextEmbedder` async test for non-existant model

---

.github/workflows/tests.yml
pyproject.toml

- In https://github.com/deepset-ai/haystack/pull/9199, I made the `lint` job trigger when pyproject.toml is changed (to check type issues with mypy)
- The `lint` job includes mypy and pylint. Pylint runs on the changed files.
- Doing `pylint pyproject.toml` is not expected and causes errors. See an example: https://github.com/deepset-ai/haystack/actions/runs/14381662538/job/40327103358
- change the `lint` job to trigger when pyproject.toml is changed but do not pass pyproject.toml to pylint
CI; made a change in pyproject in https://github.com/deepset-ai/haystack/pull/9217/commits/f1313dc537c068a0b0664336bbafba0ad3ef240a to trigger the job -> https://github.com/deepset-ai/haystack/actions/runs/14399118142/job/40381073183 no errors …

ci: fix lint job

---

.github/workflows/stale.yml

We renamed the `community-triage` label to `information-needed` to better communicate its purpose. This label can be applied to issues that need additional information from the user.
Modify stalebot configuration to reflect the new label name.
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in case the …

chore: update label name for stalebot

---

haystack/components/embedders/hugging_face_api_document_embedder.py
releasenotes/notes/add-async-support-for-HuggingFaceAPIDocumentEmbedder-016bbb1f8964cf3f.yaml
test/components/embedders/test_hugging_face_api_document_embedder.py

- fixes #9018
I refactored the code for HuggingFaceAPIDocumentEmbedder  to add async support.
I have added an integration test. All the unit tests are passing locally.
issues in the implantation:
- doc string: unsure how to update it to give an example of run_async
- code duplication: Async/sync Python requires separate implementations.  As a result I just did the tests pretty much twice and embed_batch/embed_batch_async and run/run_Async where 90 percent of the code. How can I do it smarter? I tried but the problem is I can't call an async function from a sync one thus having to duplicate my code( especially tests!) …

 feat: add `run_async` for `HuggingFaceAPIDocumentEmbedder`

---

haystack/components/converters/txt.py

- fix the erroneous docstring: for `TextFileToDocument`, "HTML file paths" should be "text file paths"
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.m …

chore: `TextFileToDocument` - fix erroneous docstring

---

haystack/components/rankers/transformers_similarity.py
releasenotes/notes/fix-to-dict-transformer-ranker-f981b37f67f6eec5.yaml
test/components/rankers/test_transformers_similarity.py

Add `batch_size` to `to_dict` of TransformersSimilarityRanker. This means serialization of batch_size now works as expected.
Updated to_dict and from_dict tests
- I ran …

fix: Add `batch_size` to `to_dict` of TransformersSimilarityRanker

---

haystack/core/super_component/super_component.py
releasenotes/notes/allow-non-leaf-outputs-in-supercomponents-outputs-adf29d68636c23ba.yaml
test/core/super_component/test_super_component.py

- fixes #9231 
- map nonleaf pipelines outputs to the supercomponenets output
- added unit test
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#insta …

feat: allow SuperComponent to Include outputs from non leaf pipeline components

---

.github/workflows/tests.yml
haystack/components/agents/agent.py

- after #9217, mypy is not running since `steps.files.outputs.any_changed == 'true'` is not valid when using `files_yaml`
- for this reason, mypy did not run on #9240 and now some issues are detected on `Agent`
- fix lint job appropriately
- fix some type errors on `Agent`
CI
I could not fix all type errors without altering `Agent` tracing, so I need help from @sjrl to fix the remaining errors.
See https://github.com/deepset-ai/haystack/actions/runs/14494497923/job/40659163363?pr=9250 …

fix: make mypy run + some type fixes on Agent

---

.github/workflows/e2e.yml
.github/workflows/tests.yml

I noticed that we currently re-run tests (and e2e tests) when a PR is marked as "Ready for review".
Since tests already run when the PR is opened, reopened or synchronized, this should not be necessary.
Avoiding this behavior, we can save time and compute.
- stop rerunning tests on PRs ready for review
CI
In case something does not work as expected, it is easy to revert this change. …

ci: stop rerunning tests on PRs ready for review

---

haystack/components/evaluators/llm_evaluator.py

-
The bug was caused by using double braces ({{received}}) in the f‑string, which escaped the placeholder and rendered the literal text {received} instead of substituting the variable’s value. This change updates the f‑string in llm_evaluator.py to use single braces ({received}), ensuring the variable is correctly interpolated.
Manually verified by invoking the evaluator with a mock response and inspecting the output string.
- …

fix: Fix f-string interpolation of `received` variable in llm_evaluator

---

haystack/components/preprocessors/document_preprocessor.py
test/components/preprocessors/test_document_preprocessor.py

Updates `from_dict` to handle `splitting_function: None`
Updated from_dict test for this behavior …

fix: Fix `from_dict` of `DocumentPreprocessor` super component

---

haystack/components/agents/agent.py
test/components/agents/test_agent.py

Uses `_schema_to_dict` when creating the span for the agent tracing. 
Updated tracing tests to reflect this …

fix: Fix state_schema serialization for agent tracing

---

haystack/components/connectors/openapi.py

The documentation uses `parameters` but the actual name is `arguments`.
N/A …

docs: Update openapi.py to use arguments

---

test/components/fetchers/test_link_content_fetcher.py
test/components/generators/test_openai.py
test/core/pipeline/test_async_pipeline.py
test/core/pipeline/test_pipeline.py

As suggested by @mpangrazzi, I did some profiling to detect more slow tests (on macOS).
**Unit tests**
```
12.08s call     test/components/fetchers/test_link_content_fetcher.py::TestLinkContentFetcherAsync::test_run_async_error_handling
2.03s  call     test/components/fetchers/test_link_content_fetcher.py::TestLinkContentFetcher::test_run_bad_status_code
2.01s  call     test/core/pipeline/test_pipeline.py::TestPipeline::test_pipeline_thread_safety
2.00s  call     test/core/pipeline/test_async_pipeline.py::test_async_pipeline_reentrance
```
**Integration tests**
I'm treating most of them in #9296 (by running them on a separate workflow) but I also found that
`test/components/generators/test_openai.py::TestOpenAIGenerator::test_run_with_system_prompt`
is quite slow (around 7s).
- fix the …

test: improve some slow tests

---

CONTRIBUTING.md

- part of #9266
- we want to clearly document how the Slow Integration Tests workflow works
- add a detailed section to Contribution guidelines
This information is mostly useful for us maintainers, but I think it doesn't hurt to share it, and having a public and easily findable documentation can help. …

docs: update Contribution guidelines with a section about Slow/Unstable tests

---

haystack/components/generators/openai_dalle.py
haystack/tools/__init__.py
haystack/tools/serde_utils.py
haystack/tools/tool.py
releasenotes/notes/move-deserialize_tools_inplace-b379fd7465eeb1b8.yaml

fix: Move `deserialize_tools_inplace` to original import path

---

haystack/tools/component_tool.py
releasenotes/notes/fix-component-tool-deepcopy-969c611ca028d294.yaml

Updates the error catching in the `__deepcopy__` of ComponentTool to handle `NotImplementedError`
The original error was 
```
NotImplementedError: object proxy must define __deepcopy__()
/home/haystackd/.local/lib/python3.12/site-packages/haystack/core/pipeline/pipeline.py, line 60, _run_component
/home/haystackd/.local/lib/python3.12/site-packages/haystack/components/agents/agent.py, line 255, run
/home/haystackd/.local/lib/python3.12/site-packages/haystack/core/pipeline/pipeline.py, line 57, _run_component
/usr/local/lib/python3.12/copy.py, line 136, deepcopy
/usr/local/lib/python3.12/copy.py, line 221, _deepcopy_dict
/usr/local/lib/python3.12/copy.py, line 136, deepcopy
/usr/local/lib/python3.12/copy.py, line 196, _deepcopy_list
/usr/local/lib/python3.12/copy.py, …
```

fix: Update to ComponentTool `__deepcopy__`

---

haystack/components/generators/chat/openai.py
haystack/components/generators/openai.py
releasenotes/notes/fix-openai-chat-generator-wrapped-streaming-f3a08f83a7528c3f.yaml
releasenotes/notes/fix-openai-generators-wrapped-streaming-f3a08f83a7528c3f.yaml
test/components/generators/chat/test_openai.py
test/components/generators/chat/test_openai_async.py
test/components/generators/test_openai.py

- fixes #9014 
Since some tools like [weave](https://github.com/wandb/weave) are wrapping OpenAI `Stream` type, internal checks like `isinstance(chat_completion, Stream)` are breaking the streaming usage. I've updated the check to be less strict but still reliable and added tests for sync/async envs.
unit tests, integration tests, manual verification …

Fix OpenAIGenerator and OpenAIChatGenerator to allow wrapped streaming objects usage

---

haystack/components/generators/chat/hugging_face_api.py
haystack/dataclasses/chat_message.py
releasenotes/notes/hfapichatgenerator-toolcall-str-args-b857e65073ba9f2b.yaml
test/components/generators/chat/test_hugging_face_api.py

- fixes #9298
Fixed import sorting in `hugging_face_api.py` to comply with Ruff linting rules. The imports are now properly organized in the standard Python order:
1. Standard library imports
2. Third-party imports
3. Local imports
- Verified that all pre-commit hooks pass successfully, including:
- Ruff linting checks
- Python AST checks
- Code formatting
- Other standard checks
- The code functionality remains unchanged as this was purely a style fix
The changes only affect import statement ordering in `hugging_face_api.py`. No functional changes were made to the code.

fix: make `HuggingFaceAPIChatGenerator` convert Tool Call `arguments` from string

---

haystack/core/component/component.py
releasenotes/notes/adding-check-sync-async-run-parameters-a437b821d503d2cd.yaml
test/core/component/test_component_signature_validation.py

- fixes #9308 
Component signature validation mismatches between `run` and `run_async` method signatures, this is bound to happen with custom components as all haystack core and integration components by design don't have this issue.
- new function `_compare_method_signatures` that provides detailed information about signature mismatches about:
- Parameter count differences
- Parameter name mismatches
- Type annotation mismatches
- Default value mismatches
- Parameter kind mismatches (positional vs keyword)
- new test file `test_component_signature_validation.py` with comprehensive test cases cover all possible signature mismatch scenarios described above …

feat: validation function for `run()` and `run_async()` parameters signature for (custom) components

---

test/core/component/test_component.py

- removing unused imports in Component tests
- noting unused variables …

chore: cleaning imports and unused variables in `Component` tests

---

.github/workflows/tests.yml
pyproject.toml

- investigated in #9319
- disable caching on Windows tests
CI - triggered tests in https://github.com/deepset-ai/haystack/pull/9318/commits/c33c2dd932fdfb5a20911510e0b338eb9787151c
Non-Windows test times are included for context but are unaffected by the Windows caching configuration.
| Test | [With Windows Cache](https://github.com/deepset-ai/haystack/actions/runs/14709162118) | [Without Windows Cache](https://github.com/deepset-ai/haystack/actions/runs/14712345305) |
|------|-------------------|----------------------|
| Unit / windows-latest | 5m 2s | 4m 58s |
| Integration / windows-latest | 6m 11s | **3m 24s** |
| Integration / ubuntu-latest | 2m 7s (not impacted) | 2m 0s (not impacted) |
| Integration / macos-latest | 2m 12s (not impacted) | 1m 51s (not impacted) |
| Total tests …

ci: disable caching on Windows tests

---

haystack/components/preprocessors/recursive_splitter.py
releasenotes/notes/fixing-bug-recursive-splitter-88d5714529f84e4e.yaml
test/components/preprocessors/test_recursive_splitter.py

- fixes #9311 
- Removed the line that was making a cumulative count in the case where a `split_text` is found to be longer than `split_length` and recursive chunking is triggered.
- A new test case was added to the `RecursiveDocumentSplitter` that verifies its behavior regarding the issue mentioned above.
- Adding the new test function `test_run_complex_text_with_multiple_separators()` to the existing test file
- Running the test suite to verify that the new test passes + CI tests …

fix: `RecursiveSplitter` bug in the case when the recursive chunking is triggered

---

test/components/generators/chat/test_openai.py
test/document_stores/test_in_memory.py

- in #9306, I accidentally introduced a sync test in an async function
- this can also create issues with the event loop of tests
- fix the test, which should be sync
CI …

test: fix test incorrectly marked as async

---

haystack/components/preprocessors/sentence_tokenizer.py
releasenotes/notes/SentenceSplitter-ReDoS-fix-ca91b020cab50bf6.yaml
test/components/preprocessors/test_sentence_tokenizer.py

- fixes #9315 
Replaced the vulnerable regular expression pattern in QUOTE_SPANS_RE inside SentenceSplitter with a ReDoS-safe alternative.
- Ran unit tests locally using hatch run test:unit
- Ensured that all pre-commit hooks passed
- This was originally from this [PR ](https://github.com/deepset-ai/haystack/pull/9335) - but due to the way I cloned the repo/branch or permissions I (@davidsbatista) could not push my changes into the community member PR, therefore this new one. Still, user commits are tracked on this PR, and he will be credited as contributor.
- I have updated the related …

fix: make `SentenceSplitter` QUOTE_SPANS_RE regex ReDoS-safe

---

haystack/core/pipeline/async_pipeline.py
haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
haystack/core/pipeline/utils.py
haystack/tools/component_tool.py
releasenotes/notes/fix-deepcopy-in-pipeline-run-2b575c7b860f642f.yaml
test/core/pipeline/test_utils.py
test/tools/test_component_tool.py

- fixes https://github.com/deepset-ai/haystack/issues/9011
Adds a `deepcopy_with_fallback` utility function that gracefully handles deepcopy errors by returning the original object in the case the deepcopy fails. 
- Added test in ComponentTool when using a Jinja2 based component (e.g. PromptBuilder)
- Also manually triggered end to end tests in GH which passed …

fix: Update deepcopying in Pipeline to have a fallback in case of error

---

e2e/pipelines/test_evaluation_pipeline.py
haystack/components/converters/multi_file_converter.py
haystack/components/preprocessors/document_preprocessor.py
haystack/core/component/component.py
releasenotes/notes/py-typed-724eea7222640e6d.yaml
test/components/generators/chat/test_openai.py
test/document_stores/test_in_memory.py

- fixes #9289
- Add py.typed file to the repository: this enables type information to be used by downstream projects, in line
with PEP 561 ([Python typing docs](https://typing.python.org/en/latest/spec/distributing.html#packaging-typed-libraries)). Previously, users got `Skipping analyzing "haystack": module is installed, but missing library stubs or py.typed marker` and all Haystack types were treated as `Any`.
- Change how we define the `run` method in the `Component` Protocol. This reverts https://github.com/deepset-ai/haystack/pull/7270 because I found that the previous definition caused type-checking issues (better explained in the code comments).
The main risk of this change is that users performing static type checking may start seeing new errors, since Haystack types were …

feat: add py.typed; adjust `Component` protocol

---

haystack/components/generators/chat/hugging_face_api.py
releasenotes/notes/hf-tool-definition-0.31.0-c8403da8769fff1d.yaml
test/components/generators/chat/test_hugging_face_api.py

In `huggingface_hub==0.31.0`, released today, `arguments` attribute of `ChatCompletionInputFunctionDefinition` has been renamed to `parameters` (see https://github.com/huggingface/huggingface_hub/pull/3015).
This breaks our implementation. https://github.com/deepset-ai/haystack/actions/runs/14886759255/job/41808326761
- make tool conversion compatible with both the legacy and the new version (also because we cannot pin `huggingface_hub`, which is only a test dependency)
- extract tool conversion in a new utility function
CI, new tests
- I have updated the related issue with new insights …

fix: `HuggingFaceAPIChatGenerator` - make tool conversion compatible with `huggingface_hub>=0.31.0`

---

haystack/components/agents/agent.py
haystack/core/pipeline/async_pipeline.py
haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
haystack/core/pipeline/utils.py
releasenotes/notes/dont-deepcopy-components-tools-b1be7ef7b4365116.yaml
test/core/pipeline/test_utils.py
test/tools/test_component_tool.py

- partially address https://github.com/deepset-ai/haystack/issues/9349
In our pipeline run methods we deepcopy the inputs and outputs of components to ensure that we don't cause unintended behavior such as altering the Pipeline run logic unepxectedly when the same input reference is passed to multiple components. 
This has worked well under the assumption that all run time inputs and outputs are data-like objects (e.g. strings, dataclasses, numbers, etc.) but has recently caused issues with the introduction of being able to pass Tools as runtime parameters to ChatGenerators. Since Tools can and often contain Components (e.g. ComponentTool) or even full pipelines (e.g. SuperComponent wrapped by ComponentTool) we find that our Pipeline run logic tries to deepcopy said tool leading to …

perf: Don't deepcopy Components, Tools, or Toolsets

---

.github/ISSUE_TEMPLATE/breaking-change-proposal.md

The Tasks checklist in `breaking change` issue template is currently displayed as a code block. Updated it to render as an interactive checklist instead.

fix: fix Task checklist in Issue Template

---

haystack/components/generators/chat/hugging_face_api.py
test/components/generators/chat/test_hugging_face_api.py

The meta dict was initialized in a for loop instead of outside of it while still being accessed outside of the for loop. Saw originally via Pycharm with `Local variable 'meta' might be referenced before assignment`
Updated some integration tests to do more checks on returned content of meta data
Ran against existing tests and made sure referenced before assignment warnings were gone. …

fix: Small fix to `HuggingFaceAPIChatGenerator` and update tests

---

haystack/tools/__init__.py
haystack/tools/serde_utils.py
haystack/tools/tool.py
releasenotes/notes/rm-deserialize_tools_inplace-cb3b1a9a36f17e3d.yaml

- fixes #9197
- remove the deprecated function
- remove some inner imports introduced in https://github.com/deepset-ai/haystack/pull/9301
CI …

chore: remove deprecated `deserialize tools inplace` function

---

haystack/components/rankers/sentence_transformers_diversity.py

Dealing with the warning: 
```text
The use of x.T on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release
```
Full warning:
```text
haystack/components/rankers/sentence_transformers_diversity.py:368: UserWarning: The use of x.T on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider x.mT to transpose batches of matrices or x.permute(*torch.arange(x.ndim - 1, -1, -1)) to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:4416.)
diversity_score = max(doc_embeddings[idx] @ doc_embeddings[j].T for j in selected)
```
using 
```python
x.permute(*torch.arange(x.ndim - …
```

using permute to reverse the dimensions of a tensor

---

haystack/core/component/component.py
releasenotes/notes/improve-component-typing-7aca4d188be6b549.yaml

- Add type annotations to the `_Component.__call__` function that backs `@component`. This fixes "decorator ignored" warnings of Pyright in "strict" type-checking mode.
- Type-check that a `@component` class conforms to the `Component` protocol (i.e., that it has a `run()` method).
- Relax the `run()` return type required by the `Component` protocol from `Dict[str, Any]` to `Mapping[str, Any]`. The former is incompatible with `TypedDict`, which makes it impossible to type a component's precise outputs. `Mapping` fixes this because it is covariant, i.e. the value type may be more specific than `Any`.
I checked the changes against the following script using Pyright in "strict" type-checking mode. Placing the file somewhere in the Haystack repo and opening in Visual Studio Code with the …

fix: Improve typing of @component allow TypedDict output types

---

haystack/components/agents/agent.py
haystack/components/generators/utils.py
haystack/components/tools/tool_invoker.py
releasenotes/notes/agent-as-a-component-tool-78696bd25deedad2.yaml
test/components/agents/test_agent.py
test/components/tools/test_tool_invoker.py

- fixes https://github.com/deepset-ai/haystack/issues/9313
- fixes https://github.com/deepset-ai/haystack/issues/9293
A variety of improvements have been made so an Agent component can be directly used in ComponentTool enabling straightforward building of Multi-Agent systems.
These improvements include:
- Adding a `last_message` field to the Agent's output which returns the last generated ChatMessage.
- Improving the `_default_output_handler` in the `ToolInvoker` to try and first serialize the outputs in the tool result before converting it into a string. This is especially relevant for getting a better representation when stringifying dataclasses like ChatMessage.
- Updated the `ToolCallResult` `StreamingChunk` to respect `outputs_to_string` when sending the tool result in the …

feat: Streamline using `Agent` as a `ComponentTool`

---

.github/workflows/slow.yml
.github/workflows/tests.yml

Sometimes some tests jobs get stuck and run for 6h before being automatically cancelled,
resulting in a waste of computational resources.
- Set [`timeout-minutes`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) to 30 for some test jobs
(unfortunately, there's no way to set a default for this parameter, so I'm only setting it where relevant. If needed, we can modify more jobs in the future)
We cannot test it. We'll keep tests durations monitored.
- I added …

ci: add `timeout-minutes` to relevant CI jobs

---

haystack/tools/component_tool.py
haystack/tools/parameters_schema_utils.py
releasenotes/notes/preserve-docstrings-super-component-tools-1fd9eb8a73b5c312.yaml
test/tools/test_component_tool.py

SuperComponents currently don't preserve parameter docstrings from underlying pipeline components, making them less informative when used with tools like ComponentTool. This limits their usefulness with LLMs for function calling.
- fixes https://github.com/deepset-ai/haystack/issues/9291
Adds docstring preservation for SuperComponent runtime input parameters by:
- Creating a new utility function to extract parameter descriptions from components
- Adding support to retrieve docstrings from underlying pipeline components
- Preserving these descriptions when a SuperComponent is used with ComponentTool
LLMs get more descriptive parameter information when working with SuperComponents:
```python
from haystack import Pipeline, SuperComponent
from haystack.components.websearch.serper_dev import …
```

feat: ComponentTool - preserve docstrings from underlying pipeline components

---

haystack/components/embedders/openai_document_embedder.py
haystack/components/embedders/openai_text_embedder.py
releasenotes/notes/add-timeout-and-max-retries-to-dict-openai-c9ad3661609ba339.yaml
test/components/embedders/test_openai_document_embedder.py
test/components/embedders/test_openai_text_embedder.py

Add missing params to to_dict method of `OpenAITextEmbedder` and `OpenAIDocumentEmbedder`
Updated unit tests …

fix: Add missing `timeout` and `max_retries` to `OpenAITextEmbedder` and `OpenAIDocumentEmbedder`

---

haystack/components/builders/answer_builder.py
releasenotes/notes/adjust-answer-builder-for-agent-f4428aea59e32809.yaml
test/components/builders/test_answer_builder.py
test/core/pipeline/features/test_run.py

Enhances the AnswerBuilder component to preserve conversation history when processing Agent outputs.
- fixes https://github.com/deepset-ai/haystack/issues/9330
- Addresses the need to maintain agent message context in GeneratedAnswer objects
- Enables seamless integration between Agent components and the AnswerBuilder
- Updates AnswerBuilder to store entire conversation history in metadata
- Adds "all_messages" field to GeneratedAnswer metadata containing all messages
- Preserves backward compatibility with existing pipelines
- Updates tests to verify the new functionality
Connect Agent and AnswerBuilder in a pipeline to maintain conversation context:
```python
from haystack.components.builders import AnswerBuilder
from haystack.components.agents import Agent …
```

feat: Extend AnswerBuilder for Agent

---

haystack/components/generators/utils.py
haystack/components/tools/tool_invoker.py
releasenotes/notes/improve-print-streaming-chunk-1b3f389e30967208.yaml

- Updates `StreamingChunk` construction in ToolInvoker to also stream a chunk with a finish reason. This is useful when using the `print_streaming_chunk` utility method
- Update the `print_streaming_chunk` to have better formatting of messages especially when using it with Agent.
- Also updated to work with the current version of the AWS Bedrock integration by working with the dict representation of ChoiceDeltaToolCall
- Further improvements will come in https://github.com/deepset-ai/haystack/pull/9424 but wanted to get this into the 2.14.0 release
Here is an example of a before and after:
- Biggest improvement is the spacing between headers e.g. `[TOOL CALL]`
- The too many newlines will be addressed in the previously mentioned other PR 
Here is a before
and an …

feat: Improve formatting in print streaming chunk

---

haystack/core/pipeline/async_pipeline.py
releasenotes/notes/preserve-context-async-pipeline-ce363ae95bbdb8bf.yaml

- fixes https://github.com/deepset-ai/haystack/issues/9203
- fixes https://github.com/deepset-ai/haystack/issues/8864
The underlying issue occurs as follows:
1. Create an AsyncPipeline
2. Add a component that only has a sync run method (so no run_async) **and** this component has tracing set up inside it's run method. 
3. Run the AsyncPipeline
The component from Step 2 then tries to log something to the tracer, but this trace has lost the parent context so is logged as a new trace.
Following the suggestion here https://github.com/deepset-ai/haystack/issues/9203#issuecomment-2826581005 we add 
```python
import contextvars
ctx = contextvars.copy_context()
outputs = await loop.run_in_executor(None, lambda: ctx.run(lambda: instance.run(**component_inputs)))
```
in the …

fix: Copy context when using `ThreadPoolExecutor` in `AsyncPipeline.run_async

---

haystack/utils/type_serialization.py

- fixes #8991
- remove the check, since we only support python >= 3.9
CI …

chore: drop python>=3.9 check in type serialization

---

haystack/components/writers/document_writer.py
test/components/writers/test_document_writer.py

Recently, the CI sometimes blocks during `DocumentWriter` tests. An example: https://github.com/deepset-ai/haystack/actions/runs/15205617087/job/42767953097?pr=9345
While this does not always happen, I was able to reproduce it locally when running all unit tests (`hatch run test:unit`).
The `InMemoryDocumentStore` creates a `ThreadPoolExecutor` for async operations.
It also has a `__del__` method, that calls `executor.shutdown(wait=True)`.
My impression is that garbage collection doesn't play well with the test event loop.
When `__del__` is called during unpredictable garbage collection (maybe during event loop teardown), the `shutdown(wait=True)` call can hang indefinitely.
- Use a Document Store fixture that gets created and destroyed for each test, in a predictable way.
CI; I also ran …

test: prevent `DocumentWriter` tests from blocking CI

---

haystack/dataclasses/chat_message.py
releasenotes/notes/to_openai_dict_format-require-tool-call-ids-9e40a5751740ad89.yaml
test/dataclasses/test_chat_message.py

- related to https://github.com/deepset-ai/haystack-core-integrations/issues/1780
- add `require_tool_call_ids` parameter to `ChatMessage.to_openai_dict_format`
- If `True` (default), if the `id` field is missing in a Tool Call, an error is raised.
- Using `False` is useful for shallow OpenAI-compatible APIs, where the `id` field is not
required.
CI; new tests …

feat: `ChatMessage.to_openai_dict_format` - add `require_tool_call_ids` parameter

---

docs/pydoc/config/agents_api.yml

State was moved into the `agents` folder. We should also add it to the correct place in the API docs. …

fix: Add state to agent pydocs

---

haystack/dataclasses/chat_message.py
releasenotes/notes/improve-chatmessage-error-messages-llm-agents-a1b2c3d4e5f6g7h8.yaml
test/dataclasses/test_chat_message.py

During execution of itinerary agent where we wrap daily itinerary Agent with ComponentTool - LLMs were encountering vague error messages when ChatMessage deserialization failed, leading to failed tool invocations, wasted debugging cycles, and unnecessary token costs. The original error `"Unsupported part in serialized ChatMessage: ..."` provided no guidance on the expected ChatMessage schema structure.
- **Core component**: Enhanced error message in `_deserialize_content()` function in `haystack/dataclasses/chat_message.py`
- **Key features**: 
- Clear explanation of required ChatMessage content structure (list of dictionaries)
- Concrete examples showing valid formats for 'text', 'tool_call', and 'tool_call_result'
```python
```
- **Error message validation**: Unit test added
- **Using …

feat: Improve ChatMessage _deserialize_content ValueError - make it more LLM friendly

---

test/components/generators/chat/test_hugging_face_api.py

- nightly tests often failing due to errors in NousResearch/Hermes-3-Llama-3.1-8B (the model we use for testing tool calling in the HF API): https://github.com/deepset-ai/haystack/actions/runs/15479832631/job/43583453403
- replace the model with [Qwen/Qwen2.5-72B-Instruct](https://huggingface.co/Qwen/Qwen2.5-72B-Instruct), served with HF inference API, which seems more reliable
CI
This choice might change over time, depending on the availability of the models served on the HF API …

test: replace tool calling model in tests with Qwen2.5-72B-Instruct

---

haystack/components/classifiers/document_language_classifier.py
haystack/components/connectors/openapi_service.py
haystack/components/evaluators/llm_evaluator.py
haystack/components/extractors/llm_metadata_extractor.py
haystack/components/routers/text_language_router.py
haystack/core/serialization.py
haystack/tools/component_tool.py
haystack/utils/auth.py
pyproject.toml
test/core/pipeline/test_pipeline_base.py
test/document_stores/test_in_memory.py

- review pylint/ruff settings to increase strictness where possible
- minor type/format fixes
- make sure that `document_store` fixture is correctly shutdown in `InMemoryDocumentStore` tests (similar to #9448)
- avoid that Pipeline tests permanently write files on disk (using temp files)
- mark 2 slow unit tests (5s in my macOS) as integration tests -> this is the reason why coverage decreases
CI …

chore: cleanup - lint and tests

---

haystack/components/agents/agent.py
releasenotes/notes/warning-or-error-missing-messages-agent-c9bb7f1fd3708df1.yaml
test/components/agents/test_agent.py

- fixes https://github.com/deepset-ai/haystack/issues/9440
Logs a warning message to users if only system messages are passed to the Agent at runtime causing potentially unexpected behavior.
- I …

feat: Warn users if Agent is called with only system messages

---

haystack/core/pipeline/async_pipeline.py
haystack/core/pipeline/base.py
haystack/core/pipeline/pipeline.py
releasenotes/notes/make-validate-input-public-e547ef5b75069bd7.yaml

- fixes https://github.com/deepset-ai/haystack-private/issues/142
Make PipelineBase._validate_input public so users can use it to validate pipelines before runtime. Currently Haystack only calls this internally at runtime.
Making it public signals to users they can use with the confidence it won't receive breaking changes without following our breaking change policy.
Existing tests …

feat: Make `PipelineBase().validate_input` public

---

haystack/components/preprocessors/recursive_splitter.py
releasenotes/notes/fix-recursive-splitter-unique-ids-5ae9901b81131302.yaml
test/components/preprocessors/test_recursive_splitter.py

- fixes #9508 
The issue occurred because `Document.id` is generated based on the `content` and `meta` at creation time.  
However, meta fields like `split_id` and `parent_id` were added **after** the `Document` was instantiated, causing chunks with identical content and meta to produce identical `id`s.
- Includes a unit test that verifies uniqueness of IDs and correct metadata assignment
- Added a unit test: `test_recursive_splitter_generates_unique_ids_and_correct_meta`
-  [x] I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_conduct.txt) …

Fixes incorrect ID generation for identical chunks in RecursiveDocumentSplitter

---

haystack/core/super_component/super_component.py
releasenotes/notes/supercomponent-class-async-serde-4bfc357570b252db.yaml
test/core/super_component/test_super_component.py

- fixes #9509
- added a new serialization parameter `is_pipeline_async` to the serialized dictionary of SuperComponent to store this information
- use this parameter to choose the appropriate pipeline class during deserialization
CI, new unit test
In case this information is missing, we default to sync Pipeline: this should make sure that deserialization does not break for SuperComponents serialized before we release this change. …

fix: fix SuperComponent class serialization/deserialization for async Pipelines

---

haystack/components/generators/chat/hugging_face_local.py
haystack/tools/component_tool.py
haystack/tools/tool.py
releasenotes/notes/fix-serialization-tool-and-comp-tool-017caac6bb56e744.yaml
test/tools/test_component_tool.py
test/tools/test_tool.py

- fixes https://github.com/deepset-ai/haystack/issues/9523
Update `to_dict` method of `ComponentTool` and `Tool` to properly serialize `outputs_to_string`. Added unit tests.
Added unit tests. …

fix: Fix Tool and ComponentTool serialization when specifying `outputs_to_string`

---

haystack/components/generators/chat/hugging_face_local.py
haystack/components/generators/chat/openai.py
haystack/components/generators/openai.py
haystack/components/generators/utils.py
haystack/dataclasses/streaming_chunk.py
releasenotes/notes/update-streaming-chunk-more-info-9008e05b21eef349.yaml
test/components/generators/chat/test_openai.py
test/components/generators/test_utils.py
test/dataclasses/test_streaming_chunk.py

- fixes https://github.com/deepset-ai/haystack/issues/9502
* Update `_convert_chat_completion_chunk_to_streaming_chunk` to properly set `index=None` in the case for streaming chunks that only contain role information or have their content set to None (e.g. when providing `finish_reason`). This was the original intent of `StreamingChunk.index`, but was missed in the original PR.
* Update StreamingChunk to have a `tool_calls` field instead of a singular `tool_call`. So `tool_calls` becomes `Optional[List[ToolCallDelta]]` to better reflect that a OpenAI Chunk can have multiple tool calls in it. I was able to test this behavior for the first time when using the MistralChatGenerator. 
* Updated relevant parts of the code and tests to reflect this change.
* Updated the original release note to …

refactor: Update to `StreamingChunk`, better `index` setting and change `tool_call` to `tool_calls`

---

haystack/components/tools/tool_invoker.py
releasenotes/notes/enable-parallel-tool-calling-96c6589f116c7e7b.yaml
test/components/tools/test_tool_invoker.py

- fixes #9008 
- Update `run_async` to gather all `tool_calls` and execute them in parallel.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installa …

feat: enable parallel tool execution in ToolInvoker

---

.github/utils/check_imports.py
.github/utils/create_unstable_docs.py
.github/utils/deepset_sync.py
.github/utils/delete_outdated_docs.py
.github/utils/docstrings_checksum.py
.github/utils/promote_unstable_docs.py
.github/utils/pyproject_to_requirements.py
.github/utils/readme_api.py
.github/workflows/tests.yml
.github/workflows/tests_skipper_trigger.yml
pyproject.toml

- pylint failing on main: https://github.com/deepset-ai/haystack/actions/runs/15919213367/job/44902536363
- pylint did not run on the original PR: #9555
- ruff and pylint settings for checking .github/ are not aligned
- fix linting of the offending file
- make sure that pylint is executed for ./github/utils/*.py files
- have ruff check those files as well (and fix format)
CI …

chore: fix deepset_sync.py for pylint + general linting improvements

---

haystack/components/generators/utils.py
releasenotes/notes/fix-convert-streaming-chunks-to-chat-message-290f69b64581f109.yaml
test/components/generators/test_utils.py

This should have been already included in the PR https://github.com/deepset-ai/haystack/pull/9525 but was overlooked. It was missed in tests, because it only becomes necessary for certain providers like Mistral. So it was caught while working on this [PR](https://github.com/deepset-ai/haystack-core-integrations/pull/1953) in this [commit](https://github.com/deepset-ai/haystack-core-integrations/pull/1953/commits/f49d68585c211bdb4b97559c93db25a35bacbf9e).
Added a unit test to have in main, not just in core-integrations.
- I have updated the related issue with new …

fix: Fix `_convert_streaming_chunks_to_chat_message`

---

haystack/dataclasses/byte_stream.py
haystack/dataclasses/document.py
releasenotes/notes/add-sede-to-bytestream-0a06db79a96a0e75.yaml
test/dataclasses/test_byte_stream.py
test/dataclasses/test_document.py

- fixes https://github.com/deepset-ai/haystack/issues/9543
- Add `to_dict` and `from_dict` to ByteStream
- Update `Document.to_dict` and `from_dict` to use the ByteStream methods
- Serialization and deserialization of ByteStream from within Document was missing the `meta` field which is now included.
- Existing Document tests
- Added unit tests …

feat: Add `to_dict` and `from_dict` to ByteStream

---

haystack/components/generators/utils.py
releasenotes/notes/fix-print-streaming-chunk-501aaa208354d211.yaml
test/components/generators/test_utils.py

Reported by @bilgeyucel:
```
[TOOL CALL]
Tool: {tool_call.tool_name} -> supposed to print the tool name
Arguments: ...
```
- fix the tool name printing
- add tests for this utility function
CI, new tests
- I …

fix: fix `print_streaming_chunk` + add tests

---

haystack/dataclasses/streaming_chunk.py
releasenotes/notes/relax-tool-call-delta-a9e1f3e9c753cdf4.yaml
test/components/generators/chat/test_openai.py
test/components/generators/test_utils.py
test/dataclasses/test_streaming_chunk.py

- fixes https://github.com/deepset-ai/haystack/issues/9581
We relaxed the requirement that in ToolCallDelta (introduced in Haystack 2.15) which required the parameters arguments or name to be populated to be able to create a ToolCallDelta dataclass. We remove this requirement to be more in line with OpenAI's SDK and since this was causing errors for some hosted versions of open source models following OpenAI's SDK specification. …

feat: Relax requirement for creating a ToolCallDelta dataclass

---

haystack/components/generators/chat/hugging_face_api.py
pyproject.toml
test/components/embedders/test_hugging_face_api_document_embedder.py
test/components/embedders/test_hugging_face_api_text_embedder.py
test/components/generators/chat/test_hugging_face_api.py

- related to #9586
- reenable HF API embedders integration tests: sentence similarity models are back online
- improve docstrings of `HFAPIChatGenerator` to clarify that it is expected to specify a provider (the default `hf-inference` provider no longer supports text generation models)
CI
The `HFAPIGenerator` need more substantial changes. I'll open a different PR for it.
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my …

chore: reenable HF API Embedders tests + improve `HFAPIChatGenerator` docstrings

---

.github/workflows/docusaurus_sync.yml
docs/pydoc/config_docusaurus/data_classess_api.yml

- fixes https://github.com/deepset-ai/haystack-private/issues/150
Add workflow to generate docs using `haystack_pydoc_tools.renderers.DocusaurusRenderer` and sync with [Docusaurus repo](https://github.com/deepset-ai/haystack-docs).
Will test manually
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in …

chore: Workflow to sync docs with Docusaurus repo

---

haystack/components/evaluators/faithfulness.py
haystack/tools/component_tool.py
haystack/tools/from_function.py
haystack/tools/tool.py

- The build process using yarn for docusaurus on the generated pydocs markdown files failed because of errors
fix code examples in docstrings …

docs: fix curly brackets

---

haystack/components/evaluators/llm_evaluator.py

- fixes an issue with xml tags not rendered correctly in LLMEvaluator docs …

docs: fix < > tags in LLMEvaluator

---

haystack/components/generators/chat/hugging_face_api.py
test/components/generators/chat/test_hugging_face_api.py

- Nightly/slow tests are failing: https://github.com/deepset-ai/haystack/actions/runs/16208724721/job/45764625697
- The model we use for testing (Phi-3.5-mini-instruct) is no longer served reliably
- change the model in tests to Qwen2.5-7B-Instruct, via Together AI Inference Provider
CI; adjusted tests …

fix: test `HuggingFaceAPIChatGenerator` with a different model

---

haystack/components/retrievers/sentence_window_retriever.py
releasenotes/notes/update-sentence-window-retriever-61435bc3d1c5f66b.yaml
test/components/retrievers/test_sentence_window_retriever.py

- fixes https://github.com/deepset-ai/haystack/issues/9592
- Added `source_id_meta_field` and `split_id_meta_field` to `SentenceWindowRetriever` for customizable metadata field names.
- Added `raise_on_missing_meta_fields` to control whether a ValueError is raised if any of the documents at runtime are missing the required meta fields (set to True by default). If False, then the documents missing the meta field will be skipped when retrieving their windows, but the original document will still be included in the results. This was added based on feedback from @ju-gu since it's hard to guarantee all docs will definitely have these meta fields when working with 60 million + documents. 
- Updated tests
- Added tests
cc @ju-gu  …

feat: Update sentence window retriever to add `source_id_meta_field`, `split_id_meta_field `, and `raise_on_missing_meta_fields `

---

haystack/components/generators/chat/hugging_face_api.py

- failing tutorial test: https://github.com/deepset-ai/haystack-tutorials/actions/runs/16431007196/job/46432251109#step:7:30
- the problem is that `ChatCompletionOutput.choices` is declared as `List[ChatCompletionOutputComplete]` in the spec but can sometimes be `None`
- check if `ChatCompletionOutput.choices` is `None` and return empty `replies` instead of raising an error
CI …

chore: `HuggingFaceAPIChatGenerator` - check if `ChatCompletionOutput.choices` is `None`

---

docs/pydoc/config/routers_api.yml
docs/pydoc/config_docusaurus/routers_api.yml
haystack/components/routers/__init__.py
haystack/components/routers/document_type_router.py
haystack/components/routers/file_type_router.py
haystack/dataclasses/byte_stream.py
haystack/utils/misc.py
releasenotes/notes/doc-type-router-8ff863f493c2ce3c.yaml
test/components/routers/test_document_type_router.py

- part of #9624
- Brings over `DocumentTypeRouter` from haystack-experimental to haystack main
Added tests
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTI …

feat: Add DocumentTypeRouter

---

haystack/components/embedders/backends/sentence_transformers_backend.py
haystack/components/embedders/image/sentence_transformers_doc_image_embedder.py
test/components/embedders/image/test_sentence_transformers_doc_image_embedder.py

resolve this comment
https://github.com/deepset-ai/haystack/blob/8e792a3d12932da73ba9831aa32e7cf12740c3fc/haystack/components/embedders/image/sentence_transformers_doc_image_embedder.py#L275-L278
- include images in `SentenceTransformersEmbeddingBackend.embed` type hint
- while doing this, I discovered that while `SentenceTransformers.encode` works with images, their type hint does not reflect that (I may open an issue on their repository for this)
CI …

chore: update `SentenceTransformersEmbeddingBackend.embed` type hint to include images

---

haystack/dataclasses/chat_message.py
pyproject.toml
releasenotes/notes/chatmessage-fromuser-allow-empty-text-1fd34aab49e40946.yaml
test/dataclasses/test_chat_message.py

- (reported by Platform) In Haystack 2.16.0, with the introduction of multimodality, we are rasing an error in `ChatMessage.from_user` if `text` and `content_parts` are both empty or `None`. The error should be raised only if they are `None`.
- fix the validation, raising an error only if `text` and `content_parts` are both `None`.
- due to [recent errors](https://github.com/deepset-ai/haystack/actions/runs/16592744217/job/46932163130), I am also pinning `ddtrace`. This is a test dependency and this change won't directly impact users.
CI; new test
- I have updated the related issue with …

fix: `ChatMessage.from_user` - raise error if `text` and `content_parts` are `None`; pin `ddtrace`

---

haystack/components/converters/image/__init__.py
haystack/components/embedders/image/__init__.py

- In #9521, we re-exported all symbols to the appropriate `__init__.py` files but during the multimodality migration, we forgot to do that for some new components. This is needed to avoid Pylance/VSCode errors (https://github.com/deepset-ai/haystack/issues/9506).
- re-export missing symbols in `__init__.py` files …

chore: re-export missing symbols in __init__.py files

---

haystack/utils/jinja2_chat_extension.py

fixes an issue with Docusaurus throwing an error which docs featuring special characters not wrapped as code
Similar to https://github.com/deepset-ai/haystack/pull/9600, https://github.com/deepset-ai/haystack/pull/9599, https://github.com/deepset-ai/haystack/pull/9598 …

docs: add code backticks around special characters

---

haystack/components/rankers/sentence_transformers_similarity.py
releasenotes/notes/fix-SentenceTransformersSimilarityRanker-score-float-a1988363b01dfc32.yaml
test/components/rankers/test_sentence_transformers_similarity.py

- fixes #9664
The SentenceTransformersSimilarityRanker CrossEncoder model was returning score as a numpy.float32 without casting to float, which can cause JSON serialization issues in downstream integrations.
Explicitly cast the score to a standard Python float before assigning it to Document.score.
Added a unit test to verify that Document.score is always a Python float.
Ran all existing unit tests with hatch run test:unit to ensure no regressions.
The change is minimal but important for serialization compatibility.

fix: ensure sentence_transformers_similarity score is a float to not np.float

---

haystack/components/generators/chat/hugging_face_api.py
haystack/utils/hf.py
releasenotes/notes/add-image-support-huggingface-api-chat-generator-9671.yaml
test/components/generators/chat/test_hugging_face_api.py
test/utils/test_hf.py

Fixes #9671
This PR adds multimodal support to `HuggingFaceAPIChatGenerator` to enable vision-language model (VLM) usage with images
and text. The implementation follows the HF VLM API format specification.
- **Extended `convert_message_to_hf_format()`** in `haystack/utils/hf.py` to handle `ImageContent` objects
- **Added proper HF VLM API format**: `{"type": "image_url", "image_url": {"url": "data:image/jpeg;base64,..."}}`
- **Supports base64 images** with MIME type handling (defaults to `image/jpeg`)
- **Maintains full backward compatibility** with text-only messages
- **Updated component documentation** with VLM usage examples
- ✅ **Unit tests**: Added 6 comprehensive test cases covering:
- Text + image messages
- Multiple images in one message
- Image without MIME type (defaults to …

  feat: add image support to `HuggingFaceAPIChatGenerator`

---

test/components/generators/chat/test_openai.py
test/components/generators/chat/test_openai_async.py

OpenAI released their new client, changing/moving some types.
Nightly tests failures: https://github.com/deepset-ai/haystack/actions/runs/16818692685
- adapt tests for the OpenAI client changes
CI …

fix: fix OpenAI tests for `openai==1.99.3`

---

haystack/components/tools/tool_invoker.py
releasenotes/notes/tool-invoker-tools-in-run-ff346a1eb510d377.yaml
test/components/tools/test_tool_invoker.py

- fixes #9685
- make `ToolInvoker` accept `tools` in `run`: if passed, they override those set at init
- I noticed that this component grew in complexity and I refactored it to make it a bit simpler and consistent
- extracted tool validation (also needed to pass tools in `run`)
- aligned `_execute_single_tool_call` (sync) and `invoke_tool_safely` (async) as much as possible; simplified `_execute_single_tool_call`
- aligned `run` and `run_async`
- other minor simplifications
- reorganized the test module: split into logical classes, removed redundant tests and added some for uncovered code paths
CI, new tests …

feat: `ToolInvoker` - pass `tools` in `run` + general refactoring

---

haystack/components/retrievers/sentence_window_retriever.py
releasenotes/notes/update-sentence-window-retriever-7e28965608b84808.yaml
test/components/retrievers/test_sentence_window_retriever.py

- fixes https://github.com/deepset-ai/haystack/issues/9687
Updated `SentenceWindowRetriever`'s source_id_meta_field parameter to also accept a list of strings. If a list of fields are provided, then only documents matching both fields will be retrieved.
Added a unit test. …

feat: Update `source_id_meta_field` in `SentenceWindowRetriever` to also accept a list of values

---

.github/workflows/tests.yml
haystack/components/caching/cache_checker.py

Coveralls hosts our test coverage data. At the moment, the service is not working.
We call Coveralls in Ubuntu unit tests.
This step fails -> Ubuntu unit tests fail -> No integrations tests -> CI blocked -> No PRs can be merged
- make the Coverall step in Ubuntu unit tests continue on errors
CI. Triggered unit tests in https://github.com/deepset-ai/haystack/pull/9713/commits/04e2681da3733c226f413928b28d72d077f818e9 ->  …

ci: avoid coveralls blocking CI

---

haystack/core/pipeline/async_pipeline.py
releasenotes/notes/fix-asyncpipeline-run-error-e82ede5c4f37f485.yaml
test/core/pipeline/test_async_pipeline.py

- fixes https://github.com/deepset-ai/haystack/issues/9677
If `run()` is called from an async context, we raise a RuntimeError saying that `await pipeline.run_async(...)` is the correct method to call.
unit tests
- …

fix: raise `RuntimeError` when `AsyncPipeline.run()` is called from within an async context

---

haystack/components/rankers/sentence_transformers_diversity.py
releasenotes/notes/st-diversity-ranker-top-k-consistency-29535a76a07a8ff3.yaml
test/components/rankers/test_sentence_transformers_diversity.py

- fixes https://github.com/deepset-ai/haystack/issues/9695
- changed elif to if in run() method to ensure top_k validation always runs regardless of whatever top_k comes from init or runtime
- Both scenarios now consistently raise ValueError with descriptive message format: 'top_k must be between 1 and X, but got Y'
- Fixes inconsistency where init top_k gave confusing MMR error while runtime top_k gave clear validation error

fix: fix inconsistent `top_k` validation in `SentenceTransformersDiversityRanker`

---

haystack/dataclasses/__init__.py

- export `ReasoningContent` to `haystack.dataclasses`, as we do for other `ChatMessage` content parts
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md …

chore: export `ReasoningContent` to `haystack.dataclasses`

---

haystack/components/routers/metadata_router.py
releasenotes/notes/metadata-router-output-type-optional-16a4d4d583202fde.yaml
test/components/routers/test_metadata_router.py

fix: Make `output_type` optional in `MetadataRouter.from_dict` for YAML loading

---

haystack/components/generators/chat/openai.py
releasenotes/notes/openai-better-exclude-custom-tcs-35e52e359b248fc8.yaml

Failing Mistral tests after 2.17.0 release: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/17085056523/job/48447452402
- improve the logic to exclude unsupported custom tool calls
CI; locally tested with Mistral integration
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:` and added `!` in case …

fix: `OpenAIChatGenerator` - improve the logic to exclude custom tool calls

---

haystack/components/tools/tool_invoker.py
releasenotes/notes/fix-trace-parentage-sync-toolinvoker-27eb727cb563a46f.yaml

Fixes missing trace context parentage for all tools executed via the synchronous ToolInvoker path. This ensures spans emitted by any tool (ComponentTool, Agent wrapped in ComponentTool, or other custom tools) are correctly linked to the outer component trace (e.g Agent or pipeline), improving end-to-end observability across the entire tool execution chain.
- Updated `haystack/components/tools/tool_invoker.py` (sync path) to propagate `contextvars` into `ThreadPoolExecutor` workers:
- Wrap each submission with `contextvars.copy_context().run(...)`
- Preserves the active tracing span so all tool spans become children of the ToolInvoker/Pipeline spans
- No public API changes; no configuration changes
After this change, any tool invoked through ToolInvoker (ComponentTool, Agent wrapped in …

fix: Propagate tracing context in sync ToolInvoker.run(...)

---

haystack/core/errors.py
haystack/core/pipeline/async_pipeline.py
haystack/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline_crash_regular_pipeline_outputs_raised.py

@davidsbatista I wanted to propose a slightly different way to attach the `pipeline_outputs` to the `PipelineRuntimeError`. Mostly, I noticed that `Pipeline._run_component` already raises a `PipelineRuntimeError` so to avoid having to `PipelineRuntimeError`'s present in the traceback I thought it best to intercept the one raised by `_run_component` and just attach the `pipeline_outputs` to it. 
What do you think? …

Suggested changes pipeline crash

---

haystack/components/agents/agent.py

- Improve the incorrect `Agent` docstring in relation to `exit_conditions` …

docs: fix `exit_conditions` in Agent docstring

---

haystack/components/agents/state/state.py

- part of #9738 
Expanded the State class docstring to explain its purpose as shared context for Agents and tools
Clarified how schema entries are defined (type, optional handler)
Added a minimal usage snippet for quick understanding
Manual verification: built and imported the State class to ensure the docstring renders correctly
This change only affects documentation (no functional changes) …

Docs: clarify purpose of State class

---

haystack/components/agents/agent.py

- changing two Agent util methods to `@staticmethod`: `_check_chat_generator_breakpoint` and `_check_tool_invoker_breakpoint`
- CI tests …

fix: changing Agent `_check_chat_generator_breakpoint` and `_check_tool_invoker_breakpoint` to `staticmethod`

---

haystack/core/component/component.py

- minor typos in code comments

docs: fixing comment typos

---

haystack/components/agents/agent.py
releasenotes/notes/add-system_prompt-to-agent-run-params-5423944e1eebb572.yaml
test/components/agents/test_agent.py

In order to change the system prompt at runtime (e.g. for platform's PromptExplorer), we need `system_prompt` as run parameter as well. 
- add `system_prompt` as parameter for `run` and `arun` …

feat: add system_prompt to Agent run parameters

---

haystack/tools/component_tool.py
releasenotes/notes/fix-parameter-schema-generation-component-tool-c3353ff7437115a1.yaml
test/tools/test_component_tool.py

- fixes https://github.com/deepset-ai/haystack/issues/9780
Fixed parameter schema generation in `ComponentTool` when using `inputs_from_state`. Previously, parameters were only removed from the schema if the state key and parameter name matched exactly. For example, `inputs_from_state={"text": "text"}` removed `text` as expected, but `inputs_from_state={"state_text": "text"}` did not. This is now resolved, and such cases work as intended.
added a new unit test that failed before making the change …

fix: Fix parameter schema generation in `ComponentTool` when using `inputs_from_state`

---

test/components/embedders/test_sentence_transformers_text_embedder.py
test/components/evaluators/test_sas_evaluator.py
test/components/rankers/test_sentence_transformers_diversity.py
test/components/rankers/test_sentence_transformers_similarity.py
test/components/rankers/test_transformers_similarity.py

While working on Sentence Transformers Sparse Embedders, I noticed that the project Sentence Transformers uses some small models in the CI
- adopt small models in testing, to hopefully save time in downloading and inference
CI, small adaptations to existing tests
It's hard to measure the speed improvements because the duration of this workflow often depends on how responsive HF is for model downloading. With only this PR as a comparison point, exact gains are unclear, but some improvement is expected.
- I added unit tests …

test: use small Sentence Transformers models in tests

---

haystack/components/agents/agent.py
releasenotes/notes/fix-openai-agent-snapshot-init-1ca26789564a53fe.yaml
test/components/agents/test_agent.py
test/components/agents/test_agent_breakpoints.py

- fixes issue that initializing from an AgentSnapshot after a ToolBreakpoint results in an error from OpenAI since we added in the ToolCall message from the assistant twice into the chat history
- In general we were erroneously copying the last message from the assistant whether restarting from a chat generator break point or a tool break point
- Don't duplicate the last message in the chat history
- Updated unit tests to better test for this behavior
- Added integration test to cover this behavior
@mpangrazzi the large diff is mostly coming from tests where I'm comparing against a full agent snapshot. The actual code changes are small. …

fix: Fix initializing an Agent from an AgentSnapshot

---

haystack/components/generators/chat/types/protocol.py

- remove unused `TypeVar` (it was used in the past when this protocol included `to_dict`/`from_dict`)
CI
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING …

chore: remove dead code in `ChatGenerator` protocol

---

.github/workflows/slow.yml
haystack/components/embedders/backends/sentence_transformers_backend.py
haystack/components/embedders/backends/sentence_transformers_sparse_backend.py
releasenotes/notes/fix-sentence-transformers-backend-embedding-id-uniqueness.yaml-63f83bd8ad30d4c6.yaml
test/components/embedders/test_sentence_transformers_embedding_backend.py

- fixes #9804 
- Fixed embedding backend id key for sentenece transformers backend uniqueness, by passing all the arguments. Previously we didn't account for arguments like `trust_remote_code, local_files_only, model_kwargs, tokenizer_kwargs, config_kwargs`.
- Also as a small enhancement we are making use of kwargs instead of passing parameters to the `_SentenceTransformersSparseEncoderEmbeddingBackend`
Ran the exisiting test suite under `test/components/embedderstest_sentence_transformers_*`
Ensured no regression caused. …

fix: embedding backend id key for sent trans backend

---

haystack/components/tools/tool_invoker.py

docs: Fix docstring of `ToolInvoker._inject_state_args`

---

haystack/components/generators/chat/openai.py
releasenotes/notes/fix-openaichat-serialization-json-object-925de0a6387ff115.yaml
test/components/generators/chat/test_openai.py

CI failures: https://github.com/deepset-ai/haystack/actions/runs/18338584146/job/52228270117?pr=9857
`TypeError: issubclass() arg 1 must be a class`
This happens because in `OpenAIChatGenerator`:
https://github.com/deepset-ai/haystack/blob/5c69b08a76448503a918a1f89a44faa041c88bf1/haystack/components/generators/chat/openai.py#L219-L223
But `{"type": "json_object"}` is a valid `response_format`, which is a dictionary object, not a class.
(IDK why this error only emerged now)
- allow proper serialization of `response_format` dictionary objects
New serialization test, CI
- I have updated …

fix: fix `OpenAIChatGenerator` `response_format` serialization errors
